### PR TITLE
Enhance Embedded Components and MOX to support custom width and paddings

### LINKED ISSUE #9919: Update Embedded Components to support custom width and padding styles
We need to update our Stripe embedded component to support custom width and padding styles. We can test this in December ahead of the live release of the update in early January.

### Acceptance Criteria

- Sync with design to agree on improvements to our embedded component in line with what is possible within the scope of the changes.
- Implement the changes and test them.
- Include them in a release of WooPayments ahead of the live release (there should be no risk to this, because the styling will be ignored by the embedded component until the update is live).

### Links

p1733911705220789-slack-C03KTTK2YMA - Slack conversation about issue

### PR DESCRIPTION
**Pull request by mordeth**
Fixes #9919

#### Changes proposed in this Pull Request
This PR updates the width of MOX input fields and Embedded Components to align with Stripe’s recent changes to their embedded components, which now expand to full width. The update ensures that the MOX input fields and Embedded Components are styled appropriately to maintain consistency and usability across various screen sizes.

Demo video: https://www.loom.com/share/9c593f9c6a634333861771016af5d61c

Screenshot 2024-12-18 at 22 40 43

Screenshot 2024-12-18 at 18 28 33

#### Testing instructions
- Reset any connected accounts.
- Navigate to the connect page and start onboarding with MOX.
- Verify MOX input/select fields have a max width of 615px Desktop and Tablet.
- Ensure the embedded components iframe has a width of 615px on Desktop and Tablet.
- Verify MOX input/select fields have 100% width with 1rem padding on Mobile.
- Ensure the embedded components iframe has 100% width with 1rem padding on Mobile.

#### Additional context
Design discussions: p1734451485224089-slack-C03KTTK2YMA

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9995` or branch name `update/9919-embedded-components-width` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=update/9919-embedded-components-width) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: ba3a223fffa9a9c0c18f60530a4fdd18660a2556
- Build time: 2024-12-19 10:17:19 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by dpaun1985 — APPROVED** [review]
✅ LGTM
Code looks good
The viewport is 615px wider on desktop and 100% on mobile

Screenshot 2024-12-19 at 10 52 37
Screenshot 2024-12-19 at 10 52 23

**Review by elazzabi — APPROVED** [review]
It didn't work at first, but rebuilding the app fixed it.

Looks good! 🚢

**Review by dmallory42 — APPROVED** [review]
LGTM, thanks for working on this! 🚢

**Pull request merged**
