### PR TITLE
Reporting: Preset date range selector for payment gateway widget

### LINKED ISSUE #8734: Show preset date ranges dropdown
Show a dropdown on the right of Payment Activity widget header.

image-16

Date range presets:
- Today
- Last 7 days
- Last 4 weeks
- Last 3 months
- Last 12 months
- Month to date
- Quarter to date
- Year to date
- All time

The dropdown can do nothing for the acceptance of this issue because functionality is covered in https://github.com/Automattic/woocommerce-payments/issues/8735.
```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/woocommerce-payments/pull/8910
- [ ] Update new custom select component
```

### PR DESCRIPTION
**Pull request by nagpai**
Fixes part of  #8734

#### Changes proposed in this Pull Request

* Add a basic date preset dropdown 
* Selecting the options should render a label with exact date ranges 

#### What is not covered
* Updation of the payment activity data shown below in reference to the dropdown change
* The final UI that resembles the design is being [developed separately](https://github.com/Automattic/woocommerce-payments/pull/8896). It will be integrated once it is reviewed and merged in a separate PR. 

#### Testing instructions
* Make sure the feature flag - `_wcpay_feature_payment_overview_widget`  is enabled
* Checkout this branch
* Make sure you see the date range selection dropdown to the top right of the widget
  * Try out various options and make sure the dates
  * Selecting `Today` should show only today's date and no end date ( check screenshot )
  * Select `Last 12 months` - It should show the year on both start and end date, since the years are different
 

##### Today 
image

##### Different year for start and end
image

##### Same year for start and end
image

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8910` or branch name `add/1-8482-preset-date-selector-for-payment-widget` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=add/1-8482-preset-date-selector-for-payment-widget) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: c7ce9866038ec2aba634cf51f728c2ab0f5e2f55
- Build time: 2024-06-06 07:35:57 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by jessy-p — CHANGES_REQUESTED** [review]
While we can integrate the selector implemented as part of https://github.com/Automattic/woocommerce-payments/pull/8896 in a separate PR, can we align this PR to the design more closely?

At present this PR appears to have two components, a selector and a label
image
Many date related functions and logic have been added to the Payment Activity Component.

Could we instead have a single selector component with the following options:

- Today: June 6, 2024
- Last 7 days: May 30 - June 5, 2024
- Last 4 weeks: May 9 - June 5, 2024
- Last 3 months: March 6 - June 5, 2024
- Last 12 months: June 6, 2023 - June 5, 2024
- Month to date: June 1 - June 6, 2024
- Quarter to date: April 1 - June 6, 2024
- Year to date: January 1 - June 6, 2024
- All time: Jan 1, 2024 - June 6, 2024

i.e.
Figma Design:
image

In this PR we could do it this way:
image

All date related functionality should be encapsulated in the date related component.

Using the selector from #8896 can be added in a separate PR.

**Comment by haszari** [comment]
Marking blocked, I think we're getting bogged down here and should focus on merging ⇒ adopting the new component (e.g. rework this PR or start new PR).

**Comment by haszari** [comment]
We'll need a tracks event for when user changes the time period. Here's my proposal:

- Event name: `wcadmin_wcpay_overview_payment_activity_period_change`
- Event props:
  - `start_date` yyyy-mm-dd
  - `end_date` yyyy-mm-dd
  - `preset_name` 

Feel free to iterate on the name & props, and update the registration if needed. I have work-in-progress event name & props in [registration repo](https://github.com/Automattic/tracks-events-registration/issues/2466).

**Comment by nagpai** [comment]
Closing in favor of #8927 , where we have reworked and implemented this using the new `InlineLabelSelect` component.

**Comment by nagpai** [comment]
Closing this in favor of #8927

**Pull request closed without merging**
