### PR TITLE
Update enabled currencies list/table design.

### LINKED ISSUE #2096: Enabled currencies table design updates
The following updates should be made to align the enabled currencies table with the original designs

Screen Shot 2021-06-08 at 3 00 54 PM

- [ ] Remove `border-top` from the first child of the enabled currencies list  
- [ ] The default currency should not be editable (remove the edit icon)
- [ ] The default currency should use the `is-shady` card background color to differentiate it from the other rows in the table. 
- [ ] Reduce the size of the emoji flags to 24px
- [ ] remove edit / delete icons, replace with single tertiary style `Edit`  button. (Remove currency button should be added to an individual currencies page

### PR DESCRIPTION
**Pull request by jessepearson**
Fixes #2096

#### Requested changes

* Remove border-top from the first child of the enabled currencies list
* The default currency should not be editable (remove the edit icon)
* The default currency should use the is-shady card background color to differentiate it from the other rows in the table.
* Reduce the size of the emoji flags to 24px
* keep the trash can icons on the list, (they should be the same grey color as the payments list) but replace the edit icon with the word manage, separated from the delete button without the vertical pipe.

#### Changes proposed in this Pull Request

* Removed border-top for the first-child in the list.
* Removed edit/manage button from the default currency (first-child).
* Set background color of default currency to `$studio-gray-0`.
* Set the size of the flags to 24px.
* Changed pencil icon to "manage", and removed border from trash icon so there's no dividing line. Adjusted other spacing accordingly to allow for items to line up.
* Added flex wrapping and min widths to currency and rate columns to allow for better mobile experience.

#### Testing instructions

* Navigate to WooCommerce > Settings > Multi-Currency.
* Make sure there is no way to edit/delete the default currency.
* Default currency background should be grey.
* Reduce screen size to mobile size to confirm things still lay out in a logical fashion.

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

**Comment by jessepearson** [comment]
@LevinMedia Can you give this a once over before I send it to the team for a code review? Thanks in advance 😄

**Comment by LevinMedia** [comment]
@jessepearson this is looking great, thanks! 

Two small points of feedback, I think the fist can be address in this PR, and the second could possibly be addressed in a follow up depending the amount of work involved. 

- Can you update the left margin on the delete button to 24px please? 
- I'd like to add a loading state to the table that mocks up a couple rows and uses the rectangular animated loading effect we're using elsewhere in WC-admin

Screen Shot 2021-07-15 at 8 49 47 AM

**Comment by jessepearson** [comment]
@LevinMedia I've updated the margin for the trash/delete icon, as requested. For the loading state, I've created a new issue: https://github.com/Automattic/woocommerce-payments/issues/2460

**Comment by jessepearson** [comment]
For whomever reviews this, can you merge it right after since I will be AFK. Thank you!

**Review by LevinMedia — APPROVED** [review]

**Review by ismaeldcom — APPROVED** [review]
LGTM, I'll merge it 🎉

**Comment by jessepearson** [comment]
@ismaeldcom Thanks for the review and the merge 😁

**Comment by tpaksu** [comment]
@LevinMedia the loading indicators are added on https://github.com/Automattic/woocommerce-payments/pull/2692. You can test the design.

**Pull request merged**
