### PR TITLE
Suppress extra console logs for E2E tests

### LINKED ISSUE #3614: Suppress asset blocking error from E2E test logs
### Description

We do selective asset blocking for E2E tests to avoid loading extra assets like fonts, certain CSS, etc which in turn speeds up the overall test suite. The event handler logs this as a failure in the test suite which leads to flooding of the console with error messages that are not related to the actual test.

### Acceptance criteria

* Resource loading failures shouldn't show up in the pipeline.

### Testing instructions

1. Go to E2E tests in the actions tab
2. Trigger a new workflow.
3. Scroll down to see the test run logs
4. Observe that resource loading errors don't show up there

### Additional context

These changes were made in the repo [here](https://github.com/Automattic/woocommerce-payments/pull/3332/files#diff-921e0699277e9df88b9482084fc31e413f848faebff9fb041b314017c81b9a14R106) but since we moved to using the upstream dependency for config [here](https://github.com/Automattic/woocommerce-payments/pull/3575), it started showing up in the test logs again.

### PR DESCRIPTION
**Pull request by deepakpathania**
Fixes #3614 

#### Changes proposed in this Pull Request
Use the `addConsoleSuppression` method to suppress extra console logs that flood the E2E test due to selective asset blocking.

#### Testing instructions

- Go to E2E tests in the actions tab
- Trigger a new workflow.
- Scroll down to see the test run logs
- Observe that resource loading and CSP errors don't show up there

-------------------

- [ ] Added changelog entries to both `readme.txt` and `changelog.txt` (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) : _Add link here / 'QA Testing Not Applicable'_

### CODE REVIEW

**Comment by naman03malhotra** [comment]
Somehow I am still able to see this error: https://github.com/Automattic/woocommerce-payments/runs/4803960988?check_suite_focus=true

I ran E2E test for this branch, am I missing something?

image

**Comment by deepakpathania** [comment]
@naman03malhotra Checking.

**Comment by deepakpathania** [comment]
Fixed, please check now, [reference job](https://github.com/Automattic/woocommerce-payments/runs/4804266177?check_suite_focus=true). @naman03malhotra

**Review by naman03malhotra — APPROVED** [review]
Nice work, LGTM! :shipit:

**Pull request merged**
