### PR TITLE
Remove "Set-up refund policy" Inbox note

### LINKED ISSUE #7776: Remove "Setup refund policy" note from the Inbox
### Description

“Set up a Refund policy” note should be removed from “Inbox”. There is a similar task in the list of things to do.

See: pdqJU4-3q4-p2

afbeelding

### Acceptance criteria

* Then creating a new store, "Setup refund policy" note doesn't appear in the Inbox

### Testing instructions

1. Set-up a new store with WooPayments plugin
2. Open WooCommerce dashboard
3. "Setup refund and return policy" shouldn't be in the Inbox.

### PR DESCRIPTION
**Pull request by dmvrtx**
Fixes #7776

#### Changes proposed in this Pull Request

 - Removes "Set-up returns & refund policy" note .

See: pdqJU4-3q4-p2

 - Update Psalm configuration to let Psalm continue if it cannot access parts of `docker` directory, which is completely normal due to uids mess between container and host.

#### Testing instructions

 - Set-up a new WooCommerce store with WooPayments
 - Onboard WooPayments
 - Ensure that Inbox doesn't contain a note titled "Set-up refund policy"

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7800` or branch name `update/change-setup-refund-policy-note-into-task` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=update/change-setup-refund-policy-note-into-task) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 6d473e4a63b958222c523ea9ce3017052132916b
- Build time: 2023-12-11 09:09:53 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by KarlisJ — COMMENTED** [review]
Code review only LGTM

**Comment by dmvrtx** [comment]
@elizaan36 , can you take a look if it works from the UX perspective? I'm on the fence about the `Read more` link, as clicking on it does two actions: opens a new tab/window with documentation _and_ changes the page to WooCommerce -> Advanced settings.

**Comment by elizaan36** [comment]
I think there was some misunderstanding. This is a duplicate inbox note that needs to be removed, there was no discussion about making it a task instead. This wouldn't fix the problem and would only increase the redundancy.

**Comment by dmvrtx** [comment]
@elizaan36 , no problem then, it greatly simplifies the change 😀

**Review by mgascam — COMMENTED** [review]
Pre-approving, looks good code wise, I intend to test manually before final approval.

**Review by KarlisJ — APPROVED** [review]
LGTM!

**Review by mgascam — APPROVED** [review]
LGTM! Tested in a fresh installation and works as expected

**Pull request merged**
