### PR TITLE
Ensure Currency Configurations Are Set Correctly When Multi-Currency Is Enabled

### LINKED ISSUE #8559: Store currency inherits all default currency options except decimal separator when multi-currency is enabled
### Describe the bug

When WooPayments multi-currency is enabled, the store's default currency will inherit the (1) default thousands separator, (2) currency position, and (3) number of decimals from the WooCommerce currency settings at WooCommerce > Settings > General — but not the decimal separator.

Using PLN as an example, it uses the following standards by default:
- A space (` `) for the thousands separator
- A comma (`,`) for the decimal separator
- A currency position of `Right with space` 
- Two decimal places

As a result, something that is one thousand PLN will display as `1 000,00 zł`.

#### 1. Thousands separator

If a site’s default currency is set to PLN and both separators are set to ` `, the currency will appear as `1 000,00 zł`. However, if both are set to `'`, then it will appear as `1’000,00 zł`.

In turn, if the store’s default currency is set to PLN with the thousands separator as `,` and the decimal separator set to `.`, the currency will appear as `1,000,00 zł`, which can inadvertently trigger https://github.com/woocommerce/woocommerce/issues/46045

If the default currency is **not** PLN, but a customer pays in PLN via the WooPayments multi-currency functionality, prices will display in the standard format (e.g., `1 000,00 zł`) and not interface with any of the Core currency options.

#### 2. Currency position

If a site's default currency is set to PLN and the currency position is set to `Left`, the currency position will follow that setting (e.g., `zł1 000,00`). However, the standard for PLN is to have a `Right with space` currency position.

If the default currency is **not** PLN, but a customer pays in PLN via the WooPayments multi-currency functionality, prices will display in the standard format (e.g., `1 000,00 zł`) and not interface with any of the Core currency options.

#### 3. Number of decimals

If a site's default currency is set to PLN and the number of decimals is set to something other than `2`, this option will show for customers paying in PLN (e.g., six decimal places will show as `1 000,000000 zł`)

If the default currency is **not** PLN, but a customer pays in PLN via the WooPayments multi-currency functionality, prices will display in the standard format (e.g., `1 000,00 zł`) and not interface with any of the Core currency options.

### To Reproduce

1. Enable multi-currency
2. Change the store's currency to one whose format you are familiar with 
3. Modify the other currency options so that they are non-standard, such as:
- Change the currency position to `Left`
- Change the thousands separator to `'`
- Change the decimal separator to `'`
- Change the number of decimals to `6`
4. Save your settings.
5. Change your presentment currency to match the site's default
6. Add enough product to your cart to increase the value so that a thousands separator is displayed
7. Note that the currency position, thousands separator, and number of decimals match the settings configured in step 3 — but not the decimal separator.
8. Change the presentment currency
9. Note that the currency position, thousands separator, number of decimals, and decimal separator do not inherit any of the settings configured in step 3
10. Disable multi-currency
11. Refresh the cart page
12. The presentment currency now matches all of the settings configured in step 3

### Actual behavior

When multi-currency is enabled, it creates inconsistent formatting for the site's default currency.

### Screenshots

---
CleanShot 2024-04-02 at 10 33 56
---
CleanShot 2024-04-02 at 10 34 25
---
CleanShot 2024-04-02 at 10 35 27
---
CleanShot 2024-04-02 at 10 36 08
---
### Expected behavior

Either:
1. Multi-currency overwrites _all_ of the currency options for the site's default currency.
2. Multi-currency doesn't overwrite the decimal separator currency option for the site's default currency.

### Additional context

p1711621558983609-slack-C02TS23QJ1X

### PR DESCRIPTION
**Pull request by lovo-h**
Fixes #8559 

#### Changes proposed in this Pull Request

The changes in this PR ensure that the currency formatting options are applied correctly to the default currency when the multi-currency feature is enabled.

#### Testing instructions

**Test: Ensure the issue is reproducible**
* Switch over to the `develop` branch.
* Ensure the cart page is using the WCBlocks-cart.
* Enable multi-currency.
* Change the store's currency to one whose format you are familiar with.
* Modify the other currency options so that they are non-standard, such as:
  - Change the currency position to `Left`
  - Change the thousands separator to `-`
  - Change the decimal separator to `*`
  - Change the number of decimals to `4`
* Save your settings.
* Change your presentment currency to match the site's default.
* Add enough product to your cart to increase the value so that a thousand separator is displayed
* Note that the currency position, thousands separator, and number of decimals match the settings configured in Step 3 — but not the decimal separator.

**Test: Ensure the changes in this PR fix the issue**
* Switch to the `fix/8559-multi-currency-decimal-separator-not-applying` branch.
* Ensure the cart page is using the WCBlocks-cart.
* Enable multi-currency.
* Change the store's currency to one whose format you are familiar with.
* Modify the other currency options so that they are non-standard, such as:
  - Change the currency position to `Left`
  - Change the thousands separator to `-`
  - Change the decimal separator to `*`
  - Change the number of decimals to `4`
* Save your settings.
* Change your presentment currency to match the site's default.
* Add enough product to your cart to increase the value so that a thousand separator is displayed
* Ensure that the currency position, thousands separator, number of decimals, and decimal separator all match the settings configured in Step 3.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8617` or branch name `fix/8559-multi-currency-decimal-separator-not-applying` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/8559-multi-currency-decimal-separator-not-applying) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 3ef37b2be5d833ba303a5706987114bfd00bbe91
- Build time: 2024-04-11 17:36:37 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by lovo-h** [comment]
@reykjalin, I also added you here as a reviewer, but mainly to make sure we weren't missing any edge cases that may have been missed from our previous solution in https://github.com/Automattic/woocommerce-payments/pull/8387.

**Review by reykjalin — COMMENTED** [review]
> @reykjalin, I also added you here as a reviewer, but mainly to make sure we weren't missing any edge cases that may have been missed from our previous solution in https://github.com/Automattic/woocommerce-payments/pull/8387.

Looks like you haven't missed anything 👏 . I tested both the order details and order received pages and they're fine 👍

**Review by rafaelzaleski — APPROVED** [review]
✅ Test: Ensure the issue is reproducible
✅ Test: Ensure the changes in this PR fix the issue

LGTM!

**Pull request merged**
