### PR TITLE
Experiment: add/e2e tests

### PR DESCRIPTION
**Pull request by vbelolapotkov**
Fixes: #85 

#### Changes proposed in this Pull Request

* Add first E2E test for making a purchase with test stripe card.
* ~~Setup Travis to run test against preconfigured publicly available test site.~~
* Add E2E environment setup script to run tests in travis and locally #746 .
* Setup slack reporter (travis config).
* Add E2E readme.
* Copy utility flows from wc core.

#### Testing instructions

* Take a look at Travis checks.
* Follow the instructions in tests/e2e/README.md to run tests locally.

-------------------

- [ ] Tested on mobile (or does not apply)

### CODE REVIEW

**Comment by jrodger** [comment]
Is there a tidy way of closing down the Docker containers used in the e2e tests?

I can run `docker-compose down` from `tests/e2e/deps/wcp-server` to take the server ones down, is there a similar command I could run to take down the `wcp_e2e_*` containers?

For now I'll just do it manually (I'm trying to wipe my environment out and retry the tests as you suggested in the other PR).

**Comment by jrodger** [comment]
> I can run docker-compose down from tests/e2e/deps/wcp-server to take the server ones down, is there a similar command I could run to take down the wcp_e2e_* containers?

Ignore me. Found it, `tests/e2e/env`.

**Comment by vbelolapotkov** [comment]
I used a good command `docker stop $(docker ps -aq)` to stop all running containers. But it's a good idea for improvement. E.g. we could add a script like `npm run test:e2e-down` to stop both e2e server and client containers.

**Comment by jrodger** [comment]
I've got `test:e2e-dev` running successfully now. It turns out there is a difference between running it from the terminal in my IDE and running it from an actual terminal. It's still not working from my IDE, but that can be a problem for another time.

The failure from the actual test was down to my test Stripe account not supporting level 3 data. So having fixed that the test passes in headless mode.

I do have a strange issue with running non-headless, the test times out with:

```
  ● Successful purchase › successful purchase

    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)
```

Which is strange. As far as I can tell we're setting the timeout to `1000000` directly on the test itself (using the `TIMEOUT` constant). Have you seen anything like that? How long does the test take to run non-headless for you?

Apart from that we could probably do with updating the PR or commits to make it clear what we're merging in (i.e. this is everything from both branches). That aside, if there wasn't anything else you wanted to handle here then I think we can get this merged in.

**Comment by vbelolapotkov** [comment]
> I've got `test:e2e-dev` running successfully now. It turns out there is a difference between running it from the terminal in my IDE and running it from an actual terminal. It's still not working from my IDE, but that can be a problem for another time.

It might be IDE is using different environment/$PATH and some required tools are not available.

> The failure from the actual test was down to my test Stripe account not supporting level 3 data. So having fixed that the test passes in headless mode.

It happened to me many times. IMO we either should add a workaround in dev tools or use platform account for e2e which is not so bad IMO.

> I do have a strange issue with running non-headless, the test times out with:
> 
> ```
>   ● Successful purchase › successful purchase
> 
>     Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.
> 
>       at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)
> ```
> 
> Which is strange. As far as I can tell we're setting the timeout to `1000000` directly on the test itself (using the `TIMEOUT` constant). Have you seen anything like that? How long does the test take to run non-headless for you?

I have a feeling @v18 had something like this but I can't reproduce it locally 😕. Not sure where it comes from.

> Apart from that we could probably do with updating the PR or commits to make it clear what we're merging in (i.e. this is everything from both branches). 

Good point. Will update PR description soon.

> That aside, if there wasn't anything else you wanted to handle here then I think we can get this merged in.

I've added a couple of improvements in https://github.com/Automattic/woocommerce-payments/pull/539/commits/76941b0c7a8095f5873c9c3e843ce3eab6bd1ed6 and https://github.com/Automattic/woocommerce-payments/pull/539/commits/8c3857c06bcc251ed446a1423d05fa836994fc3f. Besides that I feel the PR is in a good enough shape and ready for merging unless you notice anything else worth addressing. 

Probably worth asking someone else to take a look with fresh 👀

**Comment by vbelolapotkov** [comment]
> Probably worth asking someone else to take a look with fresh 👀

Asked @marcinbot to take a fresh look 🙂

**Comment by vbelolapotkov** [comment]
> Ran through the setup steps, it worked ok.

Awesome!

>     * The install took a while

Yeah it is. Probably we can find ways to cache or prebuild some components to make setup faster.

>     * The install conflicted with the existing server container and I had to remove it before rerunning the install. Probably nothing that can be done about it, though.

Yeah, this is known problem atm. I'd experiment with overriding containers names/ports via env variables.
>     * The headless run completed right away

🎉 

>     * The non-headless (headful?) run timed out on the first run but completed successfully on the subsequent 3 runs, even though there was a difference of maybe 3 seconds). Maybe it has something to do with running Chromium on my system for the first time? Either way, it works now.

Maybe. You're the lucky one to make it run from the first attempt 😆 
> 
> At some point in the future we might want to consider moving this to a separate repo, if it's possible/easy enough. There might not be enough value in it for the people outside of the GH org and the volume of extra scripts and dependencies to install might get in the way. But that's something to consider outside of this PR.

Fair point. Worth running the same set of tests for server PRs as well.

**Pull request merged**
