### PR TITLE
Update express checkout max button height to 55px

### LINKED ISSUE #9006: [ECE] Button max-height is 55px due to constraints in Stripe's API
## Description

> I reacted too quickly to the 55px and didn't think of the repercussions to other gateway's buttons sizes which have slowly been adhering to our design guidelines. Let me spin up a conversation with @nikkivias and Stripe.
>
> _Originally posted by @pierorocca in https://github.com/Automattic/woocommerce-payments/issues/8951#issuecomment-2183177946_

This issue is mostly for tracking a resolution here. Either Stripe fix the maximum allowed height (we need it to be 56px to be consistent with previous designs), or we need to adjust the max height for all payment gateways.

### PR DESCRIPTION
**Pull request by bborman22**
Fixes #9006 

#### Changes proposed in this Pull Request

This is a small update to set the maximum button height to 55px for WooPay, Google Pay, and Apple Pay. This was the result of this [discussion](https://github.com/Automattic/woocommerce-payments/issues/8951#issuecomment-2183177946) in which it was observed the Stripe Express Checkout Element (ECE) has a max height of 55px. In the linked issue it was determined we should match Stripe's setting here of 55px. This PR makes the adjustment so that all buttons under our control will share this max height for consistency. 

#### Testing instructions

1. Enable ECE locally with `npm run wp option set _wcpay_feature_stripe_ece 1`
2. Enable WooPay and Google Pay/Apple Pay
3. From the Payments Settings page, confirm that the Button size options lists `Large (55 px)` 
4. From the Payments Settings page, confirm that changing the button size option adjusts all of the displayed buttons.
5. From the Payments Settings page, set the button size to `Large (55 px)`. Inspect all buttons displayed and confirm they are rendering at 55px height.
6. From the shop single product page, confirm the buttons display and render at 55px height.
7. From the shop single product page, confirm in browser dev tools that `wcpayConfig.woopayButton.height` and `wcpayExpressCheckoutParams.button.height` are both `55`. (Depending on some options `wcpayConfig` may need to be `wcpay_upe_config`).
8. Repeat steps 6 and 7 for:
    - Cart shortcode
    - Cart blocks
    - Checkout shortcode
    - Checkout blocks
9. Disable ECE locally with `npm run wp option set _wcpay_feature_stripe_ece 0`
10. Repeat steps 3 through 8 to confirm max heigh of 55px is still applied to Payment Request Buttons just as an additional precaution in case we need to disable ECE unexpectedly. Note that the dev tools check should be against `wcpayPaymentRequestParams.button.height` in this case.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9117` or branch name `update/9006-express-checkout-button-height` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=update/9006-express-checkout-button-height) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 614fef7065334dd885a2b88ccde10753dc4c6d81
- Build time: 2024-07-18 15:26:08 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by reykjalin — CHANGES_REQUESTED** [review]
The buttons render at the correct height _according to the devtools (see issue below)_ on the customer-facing pages, but the WooPay button is still `56px` in the settings preview for me 🤔 

image

I also see the ECE preview has it's min-height set to 56px:

image

I was able to fix the ECE preview min-height by changing the `buttonSizeToPxMap`:

https://github.com/Automattic/woocommerce-payments/blob/53dc3a31d5c18ecfb335ab5f475aaae359eba625/client/settings/express-checkout-settings/payment-request-button-preview.js#L29-L33

I was able to fix the WooPay button by modifying the stylesheet for the button:

https://github.com/Automattic/woocommerce-payments/blob/53dc3a31d5c18ecfb335ab5f475aaae359eba625/client/checkout/woopay/style.scss#L241

***

For some reason the WooPay button at 55px is smaller than the Google Pay ECE button at 55px???

image

Both are 55px according to the dev tools. Maybe the ECE buttons don't take the border into account so a `1px` border means the end result is a height of `57px`? That seems to be right:

image

Setting the `max-height` of the container to `55px` results in an obvious cut-off:

image

It's only just _barely_ noticable when they're side-by-side so I think we can get away with fixing this in a separate PR once all the correct changes have been made here. Or maybe this warrants a bug report to Stripe?

**Comment by bborman22** [comment]
Great catch! Sorry I missed those preview changes, but was a quick fix like you suggested.

> I think we can get away with fixing this in a separate PR once all the correct changes have been made here. Or maybe this warrants a bug report to Stripe?

I would lean that way of a separate PR, but only because it seems like this only applies to Light / Outline mode. I was wondering if you could confirm that as well? And if we don't involve changes to Stripe, our fix would be the set WooPay button to 57px essentially?

**Review by reykjalin — APPROVED** [review]
Looks good! 🚀 

> I would lean that way of a separate PR, but only because it seems like this only applies to Light / Outline mode. I was wondering if you could confirm that as well?

Ah yes, nice catch! Yes, this seems to be limited to Light/Outline mode. I wonder if it's related to the approach Stripe needed to take for margins 🤔  https://github.com/Automattic/woocommerce-payments/issues/9005#issuecomment-2237489263

> And if we don't involve changes to Stripe, our fix would be the set WooPay button to 57px essentially?

I think so? That, at least, seems to be the only way to make them match for the light and outline versions 🤔

**Comment by bborman22** [comment]
> That, at least, seems to be the only way to make them match for the light and outline versions 

Having to make that distinction is what held me back from addressing here. I created this [issue](https://github.com/Automattic/woocommerce-payments/issues/9137) to track it going forward.

**Pull request merged**
