### PR TITLE
Fix WooPay component spacing

### LINKED ISSUE #9699: Unexpected spacing on the blocks checkout on mobile when WooPay is enabled
### Describe the bug

When WooPay is enabled and the shopper is logged into WooPay, the blocks checkout on mobile has some unexpected spacing.

### To Reproduce

1. Enable WooPay on the merchant store
2. Add a product to the cart and go to the blocks checkout page
3. View the page as in a mobile device using the browser inspector tools
4. Notice that the "Save my info" component is displayed
5. Log into WooPay
6. Reload the checkout page
7. Make a change on the email address field to re-render the "Save my info" component
8. Notice that there's some space between the payment options and the "Add order note" checkbox. For reference, see the screenshot below to see how this looks when WooPay is disabled, which is the expected appearance

### Actual behavior

There's some space between the payment options and the "Add order note" checkbox. For reference, see the screenshot below to see how this looks when WooPay is disabled, which is the expected appearance.

### Screenshots

| WooPay enabled | Not logged into WooPay| WooPay disabled |
|--------|--------|--------|
|   |   |   | 

### Expected behavior

When the "Save my info" component isn't displayed, the space between the available payment methods and the "Add order notes" checkbox must be the same as when WooPay is disabled.

### PR DESCRIPTION
**Pull request by alefesouza**
Fixes #9699

#### Changes proposed in this Pull Request

This PR fixes the WooPay component spacing and border issues on mobile.

| Existing email | Non existing email | Unchecked |
|-|-|-|
|  Screenshot 2024-11-18 at 1 39 02 PM | Screenshot 2024-11-18 at 5 03 37 PM | Screenshot 2024-11-18 at 5 07 07 PM |

#### Testing instructions

Test on desktop and mobile viewports.

* Enable WooPay
* Add products to the cart
* Access checkout page
* Type an existent WooPay address
* The WooPay `Save my info` should be shown
* The spacing and borders should be working as expected
* Type a non existent WooPay address
* The WooPay `Save my info` component should be hidden
* The spacing and borders should be the same as WooPay disabled

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9748` or branch name `fix/woopay-component-spacing` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/woopay-component-spacing) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: fcb3e8f2e3903d90a6eab0450df3831c58ab63c6
- Build time: 2024-11-25 14:58:28 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by hsingyuc — COMMENTED** [review]
@alefesouza correct me if I am wrong. I noticed if we remove below mentioned code can fix the styling. Let me know what do you think.

* It seems we have [extra line](https://github.com/Automattic/woocommerce-payments/blob/27c562b200ecb8059eec36af4d99f0de05617c19/client/components/woopay/save-user/style.scss/#L10-L21) added here.
Screenshot 2024-11-20 at 2 27 16 PM

* Remove [these code](https://github.com/Automattic/woocommerce-payments/blob/27c562b200ecb8059eec36af4d99f0de05617c19/client/components/woopay/save-user/style.scss/#L31-L39) will get the line back for payment options.
Screenshot 2024-11-20 at 2 31 18 PM

* Remove margin from `#remember-me` for @media<600 solves the `Add a note to your order` top gap issue

* Remove [this](https://github.com/Automattic/woocommerce-payments/blob/27c562b200ecb8059eec36af4d99f0de05617c19/client/components/woopay/save-user/style.scss/#L27) and [this](https://github.com/Automattic/woocommerce-payments/blob/27c562b200ecb8059eec36af4d99f0de05617c19/client/checkout/blocks/style.scss/#L104) margin removes the gap above `Add a note to your order`.
Screenshot 2024-11-20 at 4 54 22 PM

Recording of remove above mentioned code, WooPay enabled, Blocks seperator disabled:

https://github.com/user-attachments/assets/da3b73b1-359f-49f9-8215-0e3471f072c2

cc @pierorocca

**Comment by alefesouza** [comment]
@hsingyuc interesting, I added these styles due to visual issues introduced on WooCommerce 9.1, removing those styles cause issues when using WC 9.0 or lower but I don't think we need to support it anymore, fixed on https://github.com/Automattic/woocommerce-payments/pull/9748/commits/63f2c14cb24b4e9aa91223a7847413ab12b21ff4.

**Review by hsingyuc — COMMENTED** [review]
Thank you for double-checking! 
I see you revert [this PR ](https://github.com/Automattic/woocommerce-payments/pull/9131/files)here, and I believe `.without-margin-right` is no longer needed from [here](https://github.com/Automattic/woocommerce-payments/blob/63f2c14cb24b4e9aa91223a7847413ab12b21ff4/client/components/woopay/save-user/style.scss#L50-L52) and [here](https://github.com/Automattic/woocommerce-payments/blob/63f2c14cb24b4e9aa91223a7847413ab12b21ff4/client/components/woopay/save-user/checkout-page-save-user.js#L305).  [This styling](https://github.com/Automattic/woocommerce-payments/blob/63f2c14cb24b4e9aa91223a7847413ab12b21ff4/client/components/woopay/save-user/style.scss#L50-L52) seems redundant if we have [only one](https://github.com/Automattic/woocommerce-payments/blob/63f2c14cb24b4e9aa91223a7847413ab12b21ff4/client/components/woopay/save-user/checkout-page-save-user.js#L289-L329) checkbox  under `wc-block-components-checkbox`.

**Comment by alefesouza** [comment]
@hsingyuc thanks, fixed on https://github.com/Automattic/woocommerce-payments/pull/9748/commits/b57a4f86b3f9c7ce75af85dd72c5a1da17bb826e

**Review by hsingyuc — APPROVED** [review]
@alefesouza Thank you for the fixes! I tested again and looking good to me. 👍

**Pull request merged**
