### PR TITLE
Only remove all E2E tests dependencies if FORCE_E2E_DEPS_SETUP is true

### LINKED ISSUE #6647: E2E tests setup script: do not delete dependencies unless a specific env variable is supplied
### Description

The setup script always removes the dependencies (server, dev tools, subscriptions, ...)

https://github.com/Automattic/woocommerce-payments/blob/b2e21e92f939149a7b2ae4477c7f6d939ed6fdc4/tests/e2e/env/setup.sh#L33

We should do that only if the env variable `FORCE_E2E_DEPS_SETUP` is true.

### PR DESCRIPTION
**Pull request by jbordonado**
Fixes #6647 

#### Changes proposed in this Pull Request

- We delete E2E dependencies only if `FORCE_E2E_DEPS_SETUP` is true

That way:
- Client E2E tests NOT using a local server (i.e. on the GitHub CI) are unaffected and work as before 
- Client E2E tests using a local server (i.e. potentially on a local if the right variables are set in `local.env`) can decide whether they want to rebuild the dependencies or reuse them
- Server E2E tests are fixed, i.e. since the server workflow sets everything up reg. the server and dev tools repo, we don't delete those dependencies when we start running the client setup script, and it works as before.

Note that for E2E tests to start working again, this fix needs to be also brought into `trunk` (the server workflow targets `trunk` on the client)

#### Testing instructions

* This is to fix the server E2E workflow. You'd need a temporary server branch targeting this client branch. If the server E2E tests run fine (i.e. use the code from your server branch and do not fail) when the workflow is triggered from your server branch, it's fixed.

I tested myself:
- Temporary server branch targeting this client branch: https://github.com/Automattic/woocommerce-payments-server/compare/trunk...test/e2e-workflow-fix
- E2E workflow passed: https://github.com/Automattic/woocommerce-payments-server/actions/runs/5442793898/jobs/9898489230?pr=3580

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6648` or branch name `fix/e2e-test-workflow` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=fix/e2e-test-workflow) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 50f7731f94e59ce6b7f4249c9ae37cc4755c3c06
- Build time: 2023-06-30 13:01:48 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by deepakpathania — APPROVED** [review]
Changes make sense to me, haven't tried the workflow myself though.

**Comment by jbordonado** [comment]
I added in the testing instructions an example to show that it works as expected with a server branch targeting that client branch: E2E workflow is ✅ on the server

**Comment by jbordonado** [comment]
Cherry-picked bd01196d2c289d8e06f833a605380ee05758b14a to `trunk` to fix the E2E tests on the server.

**Pull request merged**
