### PR TITLE
Improve PHP code coverage

### LINKED ISSUE #5977: Cooldown - Improve PHP code coverage
### Description

The idea is to improve PHP code coverage so we can increase the minimum coverage percentage – or at least prevent future `Total code coverage is 59.98 % which is below the accepted 60%` CI errors.

For comparison, this is the code coverage before the changes:

```
Total code coverage is 60.31 % – OK!
```

Screenshot 2023-04-04 at 21 40 36

### PR DESCRIPTION
**Pull request by eduardoumpierre**
Fixes #5977 

#### Changes proposed in this Pull Request

- Add unit tests to files that lack code coverage
- Fix search by order id on Risk Review/Blocked tabs on the transactions page

| Before | After |
|--------|--------|
| Code coverage: `60.31%`  | Code coverage: `62.12%` |
| Screenshot 2023-04-04 at 21 40 36 | image | 

The 100% coverage files jumped from 68% to 71% and the 0-10% from almost 20% to around 10%.

#### Testing instructions

* Unit tests should be passing
* Checkout to this branch
* Build the client `npm run start`
* Listen to Stripe webhooks `npm run listen`
* Make sure the version on `woocommerce-payments.php` is at least `5.8.0`
* Make sure the fraud settings feature flag is enabled by running `npm run wp option add wcpay_fraud_protection_settings_active 1`
* Go to **Payments > Settings**, scroll to the Fraud protection section, select the advanced protection level, and click on "Configure"
* Scroll to the "Order items threshold" rule, enable the screening, and set the maximum items to 3
* Save the settings
* Go to your test site, add 4 items to the cart, and perform the checkout – do it a second time (so we can filter it later)
* Go to **Payments > Transactions**, click on the "Risk review" tab
* There should be at least 2 items on that list – click on the first one
* Copy the order number
* Go to **Payments > Transactions**, click on the "Risk review" tab
* Paste the order number into the search input
* There should be a suggestion

image

* Select the suggested option
* Only the selected order item should appear in the transactions list

image

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `5978` or branch name `dev/5977-php-coverage` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=dev/5977-php-coverage) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 4791f832ad4f9a23a07e17714c5468a18ebab9fd
- Build time: 2023-04-13 13:23:44 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by jessepearson** [comment]
@eduardoumpierre I went through the testing instructions before looking at the code, and it doesn't seem to work as expected. When selecting the order that's suggested, nothing appears in the list.

**Comment by jessepearson** [comment]
Regarding the above comment, it was my error. I had switched back to develop because I needed to onboard my local site again after working on some stuff yesterday. I thought I had switched back to the PR branch, but I hadn’t.

**Review by jessepearson — APPROVED** [review]
Test functions as described. There was only one minor functionality change, the rest was adding tests that did not already exist. 

Thank you for doing this.

**Pull request merged**
