### PR TITLE
Fix preview print receipt functionality

### LINKED ISSUE #4056: Preview print receipt functionality seems to be broken
### Describe the bug

The preview print receipt page on Card Reader settings is showing a blank box. It seems the following change in #4034 broke the JSON contract expected by client-side React code:

https://github.com/Automattic/woocommerce-payments/blob/86c577c394915530cfc59e0675aa4183f381428e/includes/admin/class-wc-rest-payments-reader-controller.php#L321

### To Reproduce

- Navigate to `Payments` -> `Card Readers page` -> `Receipt details`.
- Click the "Preview a printed receipt" link.

### Actual behavior

The preview box is empty.

### Screenshots

image

### Expected behavior

A preview of the print receipt with dummy data should be displayed.

### PR DESCRIPTION
**Pull request by mgascam**
Fixes #4056 

#### Testing instructions

* Navigate to Payments -> Card Readers page -> Receipt details.
* Click the "Preview a printed receipt" link.
* Check that the preview is generated correctly, like in the screenshot below

Screen Shot 2022-03-30 at 15 30 44

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) :  QA Testing Not Applicable

### CODE REVIEW

**Review by anu-rock — APPROVED** [review]
✅ Code changes look good.
✅ The fix works in Chrome and Safari.

However, it doesn't work in FF. We might want to create a separate issue to investigate that.

**Comment by kalessil** [comment]
@mgascam: the changes look good.

Confirming issue in FF: initially frame loading content, then for a short period of time shows receipt, then receipt content disappears. Would you please look into it?

**Comment by kalessil** [comment]
The issue with rendering receipt under FF also exists in develop.

**Comment by mgascam** [comment]
We will tackle the FF bug in a different [issue](https://github.com/Automattic/woocommerce-payments/issues/4070).

**Review by kalessil — APPROVED** [review]
LGTM!

**Pull request merged**
