### PR TITLE
Add BNPL to cart summary

### LINKED ISSUE #8144: Add BNPL Payment Method Messaging below the Cart summary total
### Description
BNPL is an important payment method that allows shoppers to spread payments over a longer time period. As a new category of online payment, consumer adoption and awareness continues to be in a growth phase. Thus, how this category of payment method is presented to shoppers is important to adoption and perception.

In the initial implementation of BNPL, [payment method messaging](https://stripe.com/docs/payments/payment-method-messaging) was added to the product page. This messaging e.g. As low as $14/month or 0% APR is critical to driving shopper awareness, usage, and conversion.

The problem is that not all shoppers will click into the product page to see that messaging. Even if they do see the messaging, it may be forgotten by the time the shopper completes filling up their basket/cart. 

WooPayments lacks that messaging at other important touch points such as the cart and checkout pages.

This feature adds the Stripe payment method messaging element below the cart summary total.

### Acceptance criteria
1. The payment method messaging copy is displayed below the cart summary total per the design.
2. The copy is based on providing the appropriate `paymentMethodTypes` values that correspond to those enabled on the store.
3. The messaging language matches the browser locale language.
4. The styling closely matches the site theme
 
**Out of scope:** Mini-cart

**Unknowns**: 

1. What does Stripe return if the messaging/values don't match between brands? Are multiples returned? https://stripe.com/docs/payments/payment-method-messaging#supported-plans

2. Styling - does the Appearance API provide enough customizability to be able to closely match the site theme?

### Designs
Design needed - @nikkivias I'll connect with you directly with a few options for consideration

### Testing instructions
1. Enable Affirm on your test store
2. Shop and add a simple $50+ product to the cart
3. View the cart
5. Observe that the payment method messaging displays below the cart summary total per the design
6. Repeat for Afterpay/Clearpay and Klarna
7. Repeat testing on mobile
8. Enable both Affirm and Afterpay and repeat 2-4.
9. Enable Affirm, Afterpay, and Klarna and repeat 2-4.
10. Change the browser locale to a supported non en-US language and observe that the copy language matches the new locale. 

### Additional context
Inspirational examples

image

image

image

image

cc @FangedParakeet

### PR DESCRIPTION
**Pull request by mdmoore**
Fixes #8144 

#### Changes proposed in this Pull Request

This adds the Stripe BNPL Payment Method Messaging Element to the cart summary on cart pages. For for classic cart, the PMME is mounted to a div that's added to the page. For the cart block, the Stripe `<PaymentMethodMessagingElement />` component is used. Using this element required updating the `stripe/react-stripe-js` package. I've used the latest version of the package, so one thing to consider is whether this update will cause any issues and if an earlier package should be used.

This also integrates the Appearance API based on #8421. 

#### Testing instructions

1. Enable BNPL methods, i.e. Affirm, After Pay, Klarna
2. Add a product to the cart
3. Ensure that the shopper currency, country, and total amounts align with the requirements for BNPL payment methods. Each set of requirements can be found in the payment methods class. For example, the Klarna requirements can be found [here](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/payment-methods/class-klarna-payment-method.php#L34-L102).
4. Check that the BNPL message is rendered on the following pages/scenarios and that the displayed amount updates when cart totals change(quantity change or coupons): 

- Classic theme using cart shortcode and cart block
- Block based theme using cart shortcode(cart block will be displayed) and cart block
- Product page

**Testing the Appearance API**
For classic themes, add some custom CSS to change fonts and background colors, such as: 
```
body { 
    background: #000; 
    color: #fff;
}
```

Closing the Customizer will clear the transient.

For block based themes, change to a dark style. In Twenty Twenty-Four, easy to go **Appearance > Editor  > Styles > Onyx**. Saving this style doesn't clear the transient, unfortunately. It will have to be cleared manually. `npm run wp transient delete wcpay_upe_bnpl_cart_block_appearance` and `npm run wp transient delete wcpay_upe_bnpl_cart_block_appearance_theme` should do the trick.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8427` or branch name `add/8144-bnpl-cart-summary` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=add/8144-bnpl-cart-summary) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 1779c07b6fa41f20a5b062bd33992ac90ce2f981
- Build time: 2024-03-28 15:10:16 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by gpressutto5 — CHANGES_REQUESTED** [review]
There's an issue with the price when updating the cart in the cart page.

1. Add some items to the cart.
2. Change the quantity of one of them and hit Updated Cart.

image

image

**Comment by mdmoore** [comment]
>There's an issue with the price when updating the cart in the cart page.

@gpressutto5 Looks like this is due decimals being set to 0. The updated value is coming from the store API and isn't prepared like the initial amount is via `prepare_amount()`. I'll need to think on it. If there's not a way handle this the conversion on the front-end, I might need to use an ajax request and pass the value through `prepare_amount()`. That's how I was originally handling this request but I switched to using the Store API last minute.

**Comment by mdmoore** [comment]
@gpressutto5 The updated amount is correct now. It was also an issue on the cart block when decimal precision was not 2. It's resolved now when you have time for another look.

**Review by gpressutto5 — APPROVED** [review]
Everything looks great!

image

**Pull request merged**
