### PR TITLE
Fix fatal error on expired fraud prevention token

### LINKED ISSUE #5166: Fraud prevention token check causes fatal error
### Describe the bug
As stated in p1669140141614499-slack-CLEPPN1EX, when fraud prevention token can't be verified because of a session error, it throws a fatal error instead of displaying an error notice. Details are in the Slack thread.

### PR DESCRIPTION
**Pull request by tpaksu**
Fixes #5166

#### Changes proposed in this Pull Request

Related Slack convo: p1669140141614499-slack-CLEPPN1EX Details are there.

#### Testing instructions

* Tests shall pass. 
* Enable `card_testing_prevention_enabled` meta flag for your store on the local server DB, if it doesn't exist, add it to `wcpay_account_meta` table with "1" as the value. 
* Refresh the client account info by clicking the "Clear" button on WCPay dev tools. Verify that you see `'card_testing_protection_eligible' => true,` in the new account cache.
* Apply this patch to simulate session token returning `null`:
```patch
diff --git a/includes/fraud-prevention/class-fraud-prevention-service.php b/includes/fraud-prevention/class-fraud-prevention-service.php
index fdb2f1a9..632e3969 100644
--- a/includes/fraud-prevention/class-fraud-prevention-service.php
+++ b/includes/fraud-prevention/class-fraud-prevention-service.php
@@ -118,6 +118,7 @@ class Fraud_Prevention_Service {
 	 */
 	public function verify_token( string $token = null ): bool {
 		$session_token = $this->session->get( self::TOKEN_NAME );
+		$session_token = null;
 
 		// Check if the tokens are both strings.
 		if ( ! is_string( $session_token ) || ! is_string( $token ) ) {
```
* Try to sell something, you should see an error saying `We're not able to process this payment. Please refresh the page and try again.`.
* No fatal errors should be added.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Review by jbordonado — APPROVED** [review]
Tests well 👍 

With card testing prevention enabled, I got a PHP warning (warning because I'm on PHP 7.4) with the previous code, while nothing was logged with the PR changes. I was also shown the generic error message as expected.

Also checked that `is_string` covers the right cases and it does (`is_string(NULL) = bool(false)` as per https://www.php.net/manual/en/function.is-string.php)

LGTM

**Comment by tpaksu** [comment]
> With card testing prevention enabled, I got a PHP warning (warning because I'm on PHP 7.4) with the previous code

I'm also on PHP 7.4 and I didn't get a warning, or didn't see it, can you share what you saw @jbordonado?

**Comment by jbordonado** [comment]
> > With card testing prevention enabled, I got a PHP warning (warning because I'm on PHP 7.4) with the previous code
> 
> I'm also on PHP 7.4 and I didn't get a warning, or didn't see it, can you share what you saw @jbordonado?

You should see the warning log in `docker/wordpress/wp-content/debug.log`.
Below is a screenshot of what is logged in my case:

image

**Comment by tpaksu** [comment]
Then does it mean `is_string` doesn't work for `null`? It should be as it's stated so in the php.net documentation. I also looked to that page before I decided to use that.

**Comment by tpaksu** [comment]
Ok, nvm, I missed the last part, which was the vital part :D "previous code" 

> With card testing prevention enabled, I got a PHP warning (warning because I'm on PHP 7.4) with the **previous code**

Then it works as expected. Thanks for the approval!

**Pull request merged**
