### PR TITLE
Fix transaction/document list advanced filter styling issue preventing dates to be input on mobile screens

### LINKED ISSUE #8782: Reporting: Transactions - can't set a date range filter on mobile, `To` date picker is clipped/offscreen
### Describe the bug

The mobile view of the date range filter ( `Between`  two dates ) , is broken for the Transactions page. It should be made similar to that of `Deposits` and `Disputes` 

### To Reproduce
* Switch to mobile view or a very narrow viewport
* Browse to `Payments` > `Transactions`
* Click on `Advanced filter` and choose `Date`
* Further, select `Between` to be able to specify a date range
* You will see the date selectors appearing squished like in the screenshot below

### Expected behavior

The date selector should appear the way it does for `Disputes` or `Deposits` section.

### PR DESCRIPTION
**Pull request by Jinksi**
Fixes #8782

#### Changes proposed in this Pull Request

This PR fixes an issue with advanced filter styling that prevents merchants from interacting with date inputs on mobile screens.

The desired styling overrides for the advanced filter component are now applied consistently for all list screen instances of this (deposits, disputes, documents, transactions) from `/client/style.scss`, rather than individually for each screen.

**Before**
image

**After**

image

#### Testing instructions

* View the following screens on mobile viewports smaller than 782px **and** larger viewports.
* On each list screen, select `Advanced filters` → `Date` → `Between`.
* Ensure the layout of these inputs allow merchants to view and input both `from` and `to` dates.
* Ensure the styling of advances filters looks consistent across all screens.
* Screens to test:
	* Payments → Transactions
	* Payments → Deposits
	* Payments → Disputes
	* Payments → Documents

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9013` or branch name `fix/8782-transaction-list-data-filters-mobile` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/8782-transaction-list-data-filters-mobile) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: c77f7b8b4871eb8502fb62eed64ef408a64639d3
- Build time: 2024-06-25 22:47:45 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by shendy-a8c — APPROVED** [review]
Code diff makes sense. Tested transactions, deposits, disputes, and documents list page on desktop and mobile and they look good.

Unrelated and I think it's a browser thing but dropdown shows up unexpectedly.

Untitled


It happens to dropdown on product edit page as well, so it's just a quirk of the browser IMO.

Untitled2

**Comment by Jinksi** [comment]
Thanks @shendy-a8c 🙌

> Unrelated and I think it's a browser thing but dropdown shows up unexpectedly.

On iOS Safari, I see the select options closer to the input.




I agree this may be browser-specific and a separate issue. Which browser are you seeing this bug in?

**Comment by shendy-a8c** [comment]
> Which browser are you seeing this bug in?

Chrome on a Mac but made my viewport mobile via the dev tools.

**Pull request merged**
