### PR TITLE
Checking if wcpayPaymentRequestPayForOrderParams before using it

### LINKED ISSUE #7996: Pending payment order issue: Can't find variable: wcpayPaymentRequestPayForOrderParams on login page
### Describe the bug
The "Can't find variable: wcpayPaymentRequestPayForOrderParams" error appears in specific circumstances on the Customer payment log in page after manually creating a pending order.

### To Reproduce

1. Create a pending payment order for an existing user.
2. Copy the link for the Customer payment page into a new incognito/private browser window in Chrome or Safari (or a browser when not logged in to the site).
3. The wcpayPaymentRequestPayForOrderParams localization wcpayPaymentRequestPayForOrderParams param will not be defined.

Note: This issue does not happen on a guest order given there is no login required. No error appears after logging in to the site.

#### Error on Chrome:
image

#### Error on Safari:
image

### Expected behavior
No error should happen when opening a pending payment order when not logged in.

### Desktop (please complete the following information):
N/A

### Smartphone (please complete the following information):
N/A

### Merchant's suggestion for a fix
A merchant suggested the following to fix this issue:

In the file where this is hooked in `woocommerce-payments\includes\class-wc-payments-payment-request-button-handler.php` with the method `display_pay_for_order_page_html`, this can be moved from:

```
add_action( 'before_woocommerce_pay_form', [ $this, 'display_pay_for_order_page_html' ], 1 );
```
to:

```
add_action( 'before_woocommerce_pay', [ $this, 'display_pay_for_order_page_html' ], 1 ); 
```

Then update the method to get the order from the query vars:

```
/**
 * Displays the necessary HTML for the Pay for Order page.
 *
 * @param WC_Order $order The order that needs payment.
 */
public function display_pay_for_order_page_html() {
    global $wp;
    $order_id = !empty( $wp->query_vars['order-pay'] ) ? $wp->query_vars['order-pay'] : false;
    if ( !$order_id ) {
        return;
    }

    $order = wc_get_order($order_id);
    if ( !$order ) {
        return;
    }

    $currency = get_woocommerce_currency();
```

### Additional context
7556917-zd-a8c

### PR DESCRIPTION
**Pull request by gpressutto5**
Fixes #7996

#### Changes proposed in this Pull Request

This PR adds a check for wcpayPaymentRequestPayForOrderParams before using it so no error appears in the console. The checkout works fine already, we're just not triggering an error anymore.

image

#### Testing instructions

- Create a pending payment order for an existing user.
- Copy the link for the Customer payment page into a new incognito/private browser window in Chrome or Safari (or a browser when not logged in to the site).
- The wcpayPaymentRequestPayForOrderParams localization wcpayPaymentRequestPayForOrderParams param will not be defined, but there should be no error in the console

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8014` or branch name `7996-wcpayPaymentRequestPayForOrderParams` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=7996-wcpayPaymentRequestPayForOrderParams) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 55c77521aa27a41bc54c83232d1aef06273b8ea7
- Build time: 2024-01-17 17:27:39 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by frosso — APPROVED** [review]
The changes look good! I do wonder whether we should add additional checks around [here](https://github.com/Automattic/woocommerce-payments/blob/3877aef6ec7fcd50fdec4fbbe71562cff90659ad/includes/class-wc-payments-payment-request-button-handler.php#L537-L537), to instead prevent enqueueing scripts when they're not needed (e.g.: WooPayments scripts shouldn't be needed in the login page for pay-for-order 🤷 )

**Comment by sandgreenOU** [comment]
When will the bugfix be delivered?  or is it possible to get the fixed plugin for manual installation?  thanks a lot for helping!!

**Comment by frosso** [comment]
@sandgreenOU thanks for reaching out! The next release (WooPayments 7.1.0) is planned for Jan 24th, and it will contain this fix.

**Comment by sandgreenOU** [comment]
When will the update with the bugix be released? today it's the 25th of january. Thanks.

**Comment by frosso** [comment]
@sandgreenOU apologies for the delay; we have been debugging an issue that we thought might have been related to the release. Unless something else critical comes up, the new 7.1.0 release will be published today.

**Pull request merged**
