### PR TITLE
Bump WooCommerce Tested To version to 8.9.2

### PR DESCRIPTION
**Pull request by dmvrtx**
8.9.2 is the [latest stable release](https://github.com/woocommerce/woocommerce/releases/latest) of WooCommerce. The next version, 9.0 shall be released only after the next WooPayments release, according to 7bje6-p2 release plan (sidebar).

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8930` or branch name `dev/bump-woocommerce-tested-to-8.9.2` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=dev/bump-woocommerce-tested-to-8.9.2) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 2e9a40dcf12b5cc6f937095185a13313c261f0e9
- Build time: 2024-06-10 09:22:47 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by htdat — COMMENTED** [review]
🤔 Woo core will be released tomorrow (June 11). And WooPayments will be released next week (June 19). So I think we can postpone this a bit, and make changes directly to 9.0.0 before the end of this week (June 16)?

**Comment by dmvrtx** [comment]
I'd love to have an actual version for testing with GlobalStep tomorrow, since we can't guarantee a time of Woo release.

**Review by deepakpathania — APPROVED** [review]
LGTM.

**Pull request merged**
