### PR TITLE
Card readers branding settings UI spacing adjustments

### PR DESCRIPTION
**Pull request by mordeth**
#### Changes proposed in this Pull Request

Spacing adjustment for color picker and file upload preview components.

Before:
Screenshot 2022-03-18 at 14 03 56
Screenshot 2022-03-18 at 14 04 07

After:
Screenshot 2022-03-18 at 14 00 19
Screenshot 2022-03-18 at 14 00 34

#### Testing instructions
- Update the `_wcpay_feature_card_readers` option to `1`.
- Update the `card_present_eligible` to `true`.
- Update `isBrandingEnabled` feature flag to `true` in `client/card-readers/settings/index.js`.
- Navigate to `Payments` -> `Card Readers page` -> `Receipt details`.
- Verify file upload preview and color picker components have correct spacings.
-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

**Review by anu-rock — APPROVED** [review]
Code-wise, the changes look good to me!

It seems that you've removed the top margin for color pickers. But it's not apparent in the screenshot. Perhaps I misunderstood this change?

**Comment by mordeth** [comment]
> Code-wise, the changes look good to me!
> 
> It seems that you've removed the top margin for color pickers. But it's not apparent in the screenshot. Perhaps I misunderstood this change?

Actually, the change is removing the extra spacing between the color picker block and the `Clear` button. It should be only `12px`.

**Review by elazzabi — APPROVED** [review]
Changes look good to me 👍

**Review by kalessil — APPROVED** [review]
LGTM!

**Pull request merged**
