### PR TITLE
Use shared utility function when comparing dispute `due_by` dates to improve code quality

### LINKED ISSUE #6823: [Disputes] Use shared `isDueWithin` util function for dispute `due_by` date comparisons to ensure consistent approach across UI
We have multiple places throughout disputes code where we determine how many days remain until a dispute is due. We have had bugs and discrepancies arise from these pieces of logic.

The `isDueWithin` utility function was created in #6723 to resolve this, along with unit tests to help ensure the logic is solid.

https://github.com/Automattic/woocommerce-payments/blob/e886d81b5fa81f082c189d22a1c5c545ccbce548/client/disputes/utils.ts#L27

We should use and/or adapt this function to ensure we are consistently using the same logic to determine if a dispute is due within a particular number of days.

### PR DESCRIPTION
**Pull request by Jinksi**
Fixes #6823 

#### Changes proposed in this Pull Request

This PR uses the `isDueWithin` utility function in the dispute task to remove duplicate logic. Using the shared utility function is preferred, since it and is covered by unit tests. No change in behaviour is expected.

https://github.com/Automattic/woocommerce-payments/blob/d0797feea0092676c2290cf5919af997ec2e6973/client/disputes/utils.ts#L16-L27

#### Testing instructions

* Ensure JS tests pass, `client/overview/task-list/test/tasks.js` in particular for "dispute resolution task" tests.
  https://github.com/Automattic/woocommerce-payments/blob/aea79dcab69b60696cb4960b09882870e112457a/client/overview/task-list/test/tasks.js#L271

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6825` or branch name `dev/share-dispute-due-by-comparison-logic` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=dev/share-dispute-due-by-comparison-logic) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: c4136137ae8c069277121bdbfd0c333c12cbafa5
- Build time: 2023-08-07 03:20:53 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by jessepearson — APPROVED** [review]
Code is clear as to what it is doing, and tests pass as described:

> Test Suites: 232 passed, 232 total
> Tests:       1 skipped, 1516 passed, 1517 total
> Snapshots:   360 passed, 360 total
> Time:        74.809 s

**Review by shendy-a8c — COMMENTED** [review]
I see another potential usage of `isDueWithin()` in [smartDueDate()](https://github.com/Automattic/woocommerce-payments/blob/98c291141b41f87213f480a4ce271260fef29fb8/client/disputes/index.tsx#L155).

What do you think?

**Comment by Jinksi** [comment]
> I see another potential usage of `isDueWithin()` in [smartDueDate()](https://github.com/Automattic/woocommerce-payments/blob/98c291141b41f87213f480a4ce271260fef29fb8/client/disputes/index.tsx#L155).
> 
> What do you think?

The difference with that logic is that it requires the hours returned, not just a boolean which is returned by `isDueWithin`. There are probably additional cases where we need to know the number of hours.

We could:
1. Create a new shared function that returns the hours until due. Keep `isDueWithin` as a separate util function.
2. Refactor and rename `isDueWithin` to return the hours rather than a boolean. Refactor consumers of the function to handle a number rather than boolean.

**Review by shendy-a8c — APPROVED** [review]
Ah! You're right. I think this PR is good as is for now. We can always do improvements in separate PRs.

**Comment by Jinksi** [comment]
@shendy-a8c let's keep our eye on improving this shared logic as we progress with the Dispute/Transaction details screen changes in #6883

**Pull request merged**
