### PR TITLE
Consolidate Woopay First-Party Auth and Direct Checkout Functionality

### PR DESCRIPTION
**Pull request by lovo-h**
Fixes 2446-gh-Automattic/woopay

#### Changes proposed in this Pull Request

This PR refactors both the WooPay First Party Checkout flow and the WooPay Direct Checkout flow so that common functionality can be shared between the two.

#### Testing instructions

* Ensure the WooPay First Party Auth flow works as intended. See 2192-gh-Automattic/woopay testing instructions.
* Ensure the WooPay Direct Checkout flow works as intended. See 2390-gh-Automattic/woopay testing instructions.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8170` or branch name `add/2446-woopay-first-party-and-direct-checkout-commonality` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=add/2446-woopay-first-party-and-direct-checkout-commonality) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: a39b660808569ca5182b2f9383abf17f57fd5ba7
- Build time: 2024-02-12 22:45:27 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by bborman22 — COMMENTED** [review]
I've been able to take a look at these changes now. I tested both sets of flows through several different scenarios (logged in vs logged out, 3rd party enabled / disabled) and they all seemed to work as expected. I had some odd "misses" on the direct checkout flow at times (it would always take me to merchant checkout no matter what), but it didn't seem consistent and I wasn't able to trigger it repeatedly, so I'm going to keep taking a look at that piece, but wanted to drop some questions in now ahead of time.

Two things that stood out to me as odd for the benefit of this change and was wondering if you could expand on it? The first is that I was surprised that the package size for the JS is net higher after this change. I was thinking we might be able to get some saved file size by combining some functionality across both flows and was curious if you had any thoughts around that (for example, my assumption / expectation may have just been wrong to begin with).

The other is that I'm seeing two connect page loads on the cart still and again thought this PR would get that down to one, but might have misunderstood. This is what my requests look like on the cart page and I believe the cancelled one is from the second frame not having to check third party cookies, but not sure?

Screenshot 2024-02-12 at 12 28 22 PM

I'm just going to spend a little more time on the functionality checks based on that intermittent issue I was getting, but figured I'd ask those questions in the meantime!

**Comment by lovo-h** [comment]
```
I'm just going to spend a little more time on the functionality checks based on that intermittent
issue I was getting, but figured I'd ask those questions in the meantime!
```

@bborman22, awesome, that sounds good. Thanks 🙏 

```
I had some odd "misses" on the direct checkout flow at times (it would always take me to 
merchant checkout no matter what), but it didn't seem consistent and I wasn't able to trigger 
it repeatedly...
```

Good observation. This is a known limitation and is outside the scope of this issue but I should point out that this is something we will want to handle in a future change.

The likely reason this is occurring is because the request, to determine whether the `Proceed to checkout` button should redirect to WooPay, had not completed by the time it was clicked. Therefore, it defaulted to the merchant checkout. In a future solution, we would override the click handle of the `Proceed to checkout` button on page load.  That way, when the shopper clicks the button, it will wait for the request that determines a redirection to WooPay or timeout and default to redirect to merchant checkout.


```
The first is that I was surprised that the package size for the JS is net higher after this change.
I was thinking we might be able to get some saved file size by combining some functionality
across both flows and was curious if you had any thoughts around that...
```

We briefly discussed this previously but we didn't fully get to expand on this issue. The reason this is occurring is due to how we have WebPack configured, where there are two entry points: `woopay-express-button` and `woopay-direct-checkout`.  Since this newly added functionality is imported on both entries, WebPack duplicates the code in both of the entries outputs. That's why we are seeing an increase in package size.

To solve this, we could modify our WebPack configuration so that this common code is packaged in a separate JS file and requested from each entry point. I am not a fan of this approach because I believe it would impact performance since each entry point would not be able to execute until they retrieved the common JS file. 

So, an alternative solution would be to merge these two entry points into one. This is something we discussed as an option we could take, in order to reduce the package size. However, something we didn't have a chance to explore is whether we want these two features to always be packaged together. A drawback here would be that we may be potentially introducing dead code, under certain circumstances. For example, if the First Party Auth flow were enabled but the Direct Checkout flow were disabled, the Direct Checkout JS code would be unnecessarily downloaded since it would be tied with the First Party Auth JS code. The vice versa also applies. 

However, if we anticipate these two flows to always co-exist, then merging them into one entry point would be ideal.

As a final alternative, leaving things the way they currently are allows us to make these two flows independent from each other. But the drawback, as noted, is that we increase the package size.


```
The other is that I'm seeing two connect page loads on the cart still and again thought
this PR would get that down to one, but might have misunderstood...
```

No, that's correct. We talked about making only one `connect/` call. However, while working on this, I discovered that the request to determine whether third-party cookies were enabled was interfering with other requests (since it requires a page reload). So, I introduced a temporary iFrame in order to make the third-party cookie request. This temporary iFrame makes that additional `connect/` call. More details can be found here: https://github.com/Automattic/woocommerce-payments/pull/8170/files#diff-f88756bb7dbb449783ade2ef40333effcf4738310457d4ca3283b40949d176b8R21-R33


```
This is what my requests look like on the cart page and I believe the cancelled
one is from the second frame not having to check third party cookies, but not sure?
```

Is the canceled `connect/` request reproducible? 

I expected the first three `connect/` calls but not the canceled ones. Here are the three I expected:
1. For the main iFrame that will be used to communicate with WooPay.
2. For the temporary iFrame used to detect third-party cookies. This sets the third-party cookie and refreshes the page, which leads to the next `connect/` call.
3. For the temporary iFrame used to detect third-party cookies after refresh.

**Comment by bborman22** [comment]
> The reason this is occurring is due to how we have WebPack configured, where there are two entry points: woopay-express-button and woopay-direct-checkout.

Sorry about that, this is coming back to me now as something we discussed. I think longer term it would be nice to have just that "one" WooPay iframe to communicate through, but as this feature is behind a flag for now I think it makes sense to keep separate for now.

> I expected the first three connect/ calls but not the canceled ones. Here are the three I expected:

This was a helpful list. For the canceled request, that happens to me every time and it's what ultimately made me wonder if there was some additional connect page load happening unnecessarily.

> The likely reason this is occurring is because the request, to determine whether the Proceed to checkout button should redirect to WooPay, had not completed by the time it was clicked.

This was also my thought (and that ultimately might be the issue still), but I tried giving it a ton of time after page load and still got some misses, but after some additional testing I can't seem to make it happen again so might have just been a fluke.

I'd say if we can nail down the root cause of the canceled connect request this PR LGTM!

**Review by bborman22 — APPROVED** [review]
I was now able to test this PR and confirmed all functionality worked as expected against the matrix of scenarios:
- Direct checkout feature enabled vs disabled
- Third party cookies enabled vs disabled
- Logged into WooPay vs logged out
- Using direct checkout vs express checkout button
- Blocks and shortcode cart

Biggest thing that we discussed and you addressed was the connect page loading one extra time, but with the latest commits that was fixed!

LGTM!

**Pull request merged**
