### PR TITLE
Add subscription variation support to WooPay button

### LINKED ISSUE #7588: Google/Apple pay buttons: Conflict between WooPay and payment button handlers.
### Describe the bug
The implementation of `wc_ajax_wcpay_add_to_cart` is done twice on two different files. If the product is `subscription_variation` and the user clicks the ApplePay or GooglePay button, the logic from WooPay will still trigger. This WooPay logic doesn't recognize a `subscription_variation` product so after removing all Products from the cart, these products won't be added back causing a `$0` amount in the GooglePay/ApplePay modal.

The files implementing the same AJAX function are:
 - `/includes/class-wc-payments-payment-request-button-handler.php`
 - `/includes/class-wc-payments-woopay-button-handler.php`

The second one, `woopay-button-handler`, has this condition to add the products back:
```
if ( in_array( $product_type, [ 'simple', 'subscription', 'bundle', 'mix-and-match' ], true ) ) {
    ...
}
```

The above should probably include support for `subscription_variation`, just like it's done in `class-wc-payments-payment-request-button-handler.php`:

```
$subscription_types = [
    'subscription',
    'subscription_variation',
];


if ( 'simple' === $product_type || in_array( $product_type, $subscription_types, true ) ) {
  ...
}
```

If there's no way WooPay can support `subscription_variation`, then some condition needs to be added so that WooPay implementation doesn't interfere with Google Pay and Apple Pay experience in case both are enabled.

A nice solution would be to have a third file from where this logic can be pulled by both files, to avoid future similar problems.

Reference of how this was fixed for the standard button handler: https://github.com/Automattic/woocommerce-payments/pull/5964

### To Reproduce

1. Enable the Express checkout buttons for Google Pay and Apple Pay
2. Create or look for a product of type`subscription_variation`
3. Go to the product and click the Google Pay or Apple Pay button
4. A modal opens with the correct price information
5. Go back to the WordPress Admin and enable WooPay
6. Repeat steps 2 and 3

### Actual behavior
The Google Pay modal shows a $0 amount

### Expected behavior
The Google Pay modal should show the actual product price.

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### PR DESCRIPTION
**Pull request by mdmoore**
Fixes #7588

#### Changes proposed in this Pull Request

This adds support for the `subscription_variation` product type to the WooPay button, similar to [what's done for payment request buttons](https://github.com/Automattic/woocommerce-payments/blob/0640c56368ba792b20164a48e8811194b402e299/includes/class-wc-payments-payment-request-button-handler.php#L1185).

#### Testing instructions

This covers an edge case and is a bit awkward to test. Variable Subscription products have the type, `variable-subscription` and the actual variations have the type,`subscription_variation`. When navigating to a variable subscription product and purchasing a variation, the the express checkout buttons will see `variable-subscription` as the product type. There is some case in which a subscription variation can be purchased while not attached to it's parent product, at which point the product type will be `subscription_variation`. Myself and others haven't been able to find a way to purchase a subscription variation via normal core flows.

### Instructions

1. Install WooCommerce Subscriptions and create a variable subscription with a few variations
2. Find the ID of one variation in the **Variations** tab within the product settings
3. Set the `$product_id` to the ID of the variation [here](https://github.com/Automattic/woocommerce-payments/blob/0640c56368ba792b20164a48e8811194b402e299/includes/class-wc-payments-woopay-button-handler.php#L229). This will result in that `subscription_variation` being added to the cart any time the WooPay or payment request button is used.
4. Navigate to any product and purchase via the WooPay button. _You must be logged in to purchase subscriptions via WooPay_
5. Verify the subscription variation was added to the cart and can be purchased in WooPay and that the total is correct
6. Repeat steps 4 and 5 using Google Pay, paying particular attention that the total is correct and not $0.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7884` or branch name `fix/7588-woopay-subscription-variation` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/7588-woopay-subscription-variation) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 9f789aba94a78a10fa126a43e77eafa628e1b51e
- Build time: 2023-12-18 22:13:19 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by gpressutto5 — COMMENTED** [review]
While testing this I noticed it already works in `trunk`, how can I simulate the case where this is broken?

image

I also noticed the Apple Pay / Google Pay button is never displayed in the product page of Variable Subscriptions. Is this expected?

**Comment by mdmoore** [comment]
>I also noticed the Apple Pay / Google Pay button is never displayed in the product page of Variable Subscriptions. Is this expected?

I don't think this is expected. I'm seeing the buttons on variable subscription products on `develop`. I can't think of what might prevent the buttons from appearing on variable subscriptions. Maybe try some refreshes 🤔. 

image<br>  


>While testing this I noticed it already works in trunk, how can I simulate the case where this is broken?

This is where the weirdness comes in. It will work fine with a normal variable subscription product. To reproduce, you'll need to grab the ID of the subscription variation and hardcode it[ here](https://github.com/Automattic/woocommerce-payments/blob/0640c56368ba792b20164a48e8811194b402e299/includes/class-wc-payments-woopay-button-handler.php#L229). This will simulate purchasing a `subscription_variation` product. You could dump the product type [here](https://github.com/Automattic/woocommerce-payments/blob/0640c56368ba792b20164a48e8811194b402e299/includes/class-wc-payments-woopay-button-handler.php#L247) to be sure the product is a `subscription_variation`. Just keep in mind that dumping or throwing an exception here might prevent the error from appearing since it happens after the cart is emptied [here](https://github.com/Automattic/woocommerce-payments/blob/0640c56368ba792b20164a48e8811194b402e299/includes/class-wc-payments-woopay-button-handler.php#L249).

### Find the variation ID here:

image

The product is initially added to the cart and the GPay modal might show the correct total, but then will update to 0 after.

### Reproducing the error will look like this:

image<br>  



Let me know if you're still unable to reproduce it and I'll try my best to help. It's a strange thing.

**Review by gpressutto5 — APPROVED** [review]
After some time debugging I discovered the button was not appearing because my subscription offered a 1-month trial 😓

I can confirm this PR fixes the issue.

| Before | After |
| ---- | ---- |
| image | image |
| image | image |

**Comment by mdmoore** [comment]
>After some time debugging I discovered the button was not appearing because my subscription offered a 1-month trial 😓

Ah, nice catch! Sorry I didn't notice that in your screenshot.

There's [one JS test failing](https://github.com/Automattic/woocommerce-payments/actions/runs/7254400600/job/19763046979?pr=7884), but that's due to a [different PR](https://github.com/Automattic/woocommerce-payments/pull/7851#issuecomment-1861694785). I'll proceed with merging this one.

**Pull request merged**
