### PR TITLE
Hide WooPay button on zero total orders without shipping address

### LINKED ISSUE #7895: WooPay button appears on zero total orders
### Describe the bug
On zero total orders (eg 100% Off discount code) the Apple and Google Express Pay buttons are removed from both the Cart and Checkout pages.

The WooPay button remains in place on Checkout pages in an enabled state. Following the WooPay flow prevents payment as the place order button is disabled on the pay.woo.com 

### To Reproduce

1. Create Simple Product
2. Create 100% Discount Coupon
3. Enable WooPay express pay button
4. Purchase product
5. On the cart apply the discount code (cart total will be zero)
6. On the cart (shortcode) page the woopay button is present but disabled (expected)
7. Continue to the checkout  (shortcode)  page
8. On the checkout (shortcode) page the woopay button is enabled
9. Click WooPay
10. Complete WooPay flow until it comes time to palce the order
11. Observe the Place Order button is disabled

When using checkout (blocks)

6. On the cart (blocks) page the woopay button is not present (expected)
7. Continue to the checkout  (blocks)  page
8. On the checkout (blocks) page the woopay button is not shown (expected)
9. Remove coupon code
10. On checkout (blocks) page the woopay button is shown (expected)
11. Purchase the product via WooPay
12. Return to the Sample Product, add to cart
13. On the cart (blocks) page apply the 100% discount coupon
14. Click through to the checkout (blocks) page
15. As the cookies have been set, the WooPay popover will show and an SMS be triggered

### Actual behavior
WooPay is enabled and leads to a dead end, unable to place order of zero total cart.

### Screenshots

(Don't worry about the street address in these screen shots, it's the Automattic office address)

WooPay button on Checkout (shortcode) page
Screen Shot 2023-12-13 at 1 17 55 pm

WooPay Payment screen showing disabled "Place order" button
Screen Shot 2023-12-13 at 1 20 11 pm

Zero total order upon return to checkout (block) page

Screen Shot 2023-12-13 at 1 29 28 pm

### Expected behavior

Either:
* The WooPay button should be disabled for zero total orders
* The WooPay popover should not show for zero total orders if the cookies are set

Or:
* pay.woo.com allows for the placing of zero total orders

### Desktop (please complete the following information):

* OS: macOs
* Browser Chrome 120

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### PR DESCRIPTION
**Pull request by alefesouza**
Fixes #7895

#### Changes proposed in this Pull Request

This PR hides the WooPay button on zero total orders, or when buying zero total subscription (0 sign up fee and 0 renewal price) when the cart does not need shipping.

This PR also fixes an issue where other express payment buttons do not get hidden when the order gets to 0 after applying gift cards on classic checkout.

#### Testing instructions

* Create a $0 virtual product.
* Access this product page.
* The WooPay express checkout button should be hidden.
* Add this product to the cart.
* Access the cart or checkout pages on blocks and classic checkout.
* The WooPay express checkout button should be hidden.
* Interact with WooPay email field on checkout page, it should not check if the email exists or redirect if you are already authenticated. 
* Add another virtual product with any value greater than 0.
* Access the cart or checkout pages on blocks and classic checkout.
* The WooPay express checkout button should be shown.
* Add coupons and gift cards to make the order total decrease to 0.
* The WooPay express checkout button should be hidden (using gift cards on classic checkout now should hide the other express payment buttons too).
* Create a $0 virtual subscription, without sign up fee.
* Access this subscription page.
* The WooPay express checkout button should be hidden.
* Add this subscription to the cart.
* Access the cart or checkout pages on blocks and classic checkout.
* The WooPay express checkout button should be hidden.
* Interact with WooPay email field on checkout page, it should not check if the email exists or redirect if you are already authenticated.
* Change the sign up fee to any value greater than 0.
* Reload the cart or checkout page.
* The WooPay express checkout button should be shown.
* For any other scenario, the WooPay express checkout button should work as it worked before.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9846` or branch name `fix/hide-woopay-button-on-zero-total-orders` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/hide-woopay-button-on-zero-total-orders) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 35a4234581823ef8930cf0d02ae2762b37ad3588
- Build time: 2024-11-29 18:05:31 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by malithsen** [comment]
@alefesouza I haven't reviewed the changes yet, but wanted to double-check:
My understanding from @pierorocca's comments https://github.com/Automattic/woocommerce-payments/issues/7895#issuecomment-2494629234 and p1732303062924459/1732300628.585199-slack-C3NCP7ZJ6 is that we should not hide the WooPay button for 0$ orders, instead update WooPay to support those. Did that decision change?

**Comment by pierorocca** [comment]
There are scenarios when it's not showing up and should, and where it is and shouldn't like when there's no billing or shipping to collect, no future payment. Also there's the bug where on hosted checkout for $0 the place order button is disabled.

Similarly with ECE I opened an issue because the logic is ignoring sign-up fees for subscriptions and sometimes doesn't show the button.


I'll run through an audit later today.

**Comment by alefesouza** [comment]
@malithsen I talked with @pierorocca on Slack and my understanding was to hide the button:

* On $0 orders with no shipping (virtual products).
* On $0 subscriptions with no shipping and $0 sign up fee and renewal price (the subscription is always $0).

This PR implements that.

**Comment by pierorocca** [comment]
Let's also please check the button shows up when it should as well as part of the testing.

I'm also pausing for a moment...what if the shopper wants even free order receipts to be centralized with WooPay? Taking away the button and DC in these scenarios removes that possibility. 


OK if we did always keep WooPay visible, can we properly transact $0 orders and hide the appropriate sections?

**Comment by pierorocca** [comment]
I'm remembering now I'm the one who made this argument before and felt there's value for WooPay to be a single place for order history.

**Comment by pierorocca** [comment]
Hey guys, let's pause on this change. There is value in keeping WooPay visible even for $0 purchases, regardless of the scenario so that WooPay can be a central store of order history.

That being said in addition to the bugs in https://github.com/Automattic/woopay/issues/2224 and #9777, there's missing border when there's no billing and shipping sections.

image

And variable subscriptions with a free trial does not show the correct information if clicking the WooPay button from the product page.

image


https://github.com/user-attachments/assets/eaefba33-d23a-44af-92a6-5333336a703b

Happy to close this out and address these in separate issues.

**Pull request closed without merging**
