### PR TITLE
Bump wcpay_empty_state_preview_mode Version

### LINKED ISSUE #2612: Update Preview Mode experiment name to wcpay_empty_state_preview_mode_v2
In issue #2511, this Preview Mode ExPlat experiment was stopped.

For the 2.8 release, the experiment needs to be restarted once fixes for #2511 and #2556 are in place. On the ExPlat side the previous experiment has been cloned with a new name `wcpay_empty_state_preview_mode_v2`.

Note this will need to be bumped again to v3 just prior to the release of 2.8 to avoid any impact on the results from testing. @RadoslavGeorgiev would this be possible? We are not currently able to use the staging mode of ExPlat, which would have prevented the need for this.

### PR DESCRIPTION
**Pull request by adrianduffell**
Fixes #2612

#### Changes proposed in this Pull Request

Bumps version number of ExPlat experiment `wcpay_empty_state_preview_mode`

This experiment was stopped in issue #2511 and needs to be re-started for the 2.8 release. This is done by cloning the previous experiment and incrementing the version number in the name.

Note this will need to be bumped again to `v3` just prior to the release of 2.8 to avoid any impact on the results from testing. @RadoslavGeorgiev will this be possible? We are not currently able to use the `staging` mode of ExPlat, which would  have prevented the need for this.

#### Testing instructions

- Check that all instances of `wcpay_empty_state_preview_mode_v1` have been changed.

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

**Review by htdat — COMMENTED** [review]
I think this only changes the test name. It does not fix the issue for #2511

IMHO, this change can be incorporated into #2555, where it addressed the root cause for #211.

**Comment by adrianduffell** [comment]
@htdat Yeah this is just changing the test name. Sorry for the confusion, I shouldn't have linked it to #2511. I have created a new issue for this and updated the description.

I still think it would be good to keep this change standalone because PR https://github.com/Automattic/woocommerce-payments/pull/2557 also needs it. If we merge this first then both PRs #2555 and #2557 can be tested with the new experiment name.

**Review by htdat — APPROVED** [review]
Appreciate your context. 

> I still think it would be good to keep this change standalone because PR #2557 also needs it. If we merge this first then both PRs #2555 and #2557 can be tested with the new experiment name.

I have no strong opinion about this. If that makes those two PRs easier to work with, this PR is great for me. 🚢

**Comment by adrianduffell** [comment]
Thanks @htdat !

**Pull request merged**
