### PR TITLE
Check for payment method details before referencing

### LINKED ISSUE #2665: When payment failed for Giropay / sofort, got WSOD
Tested with wcpay 2.8.1.

1. Enable giropay and sofort payment method from wcpay settings page.
2. Purchase with giropay / sofort.
3. Fail the payment.
4. You will see this error:
```
Notice: Trying to access array offset on value of type null in /srv/users/user082cb71c/apps/user082cb71c/public/wp-content/plugins/woocommerce-payments/includes/payment-methods/class-upe-payment-gateway.php on line 466

Warning: Cannot modify header information - headers already sent by (output started at /srv/users/user082cb71c/apps/user082cb71c/public/wp-content/plugins/woocommerce-payments/includes/payment-methods/class-upe-payment-gateway.php:466) in /srv/users/user082cb71c/apps/user082cb71c/public/wp-includes/pluggable.php on line 1340

Warning: Cannot modify header information - headers already sent by (output started at /srv/users/user082cb71c/apps/user082cb71c/public/wp-content/plugins/woocommerce-payments/includes/payment-methods/class-upe-payment-gateway.php:466) in /srv/users/user082cb71c/apps/user082cb71c/public/wp-includes/pluggable.php on line 1343
```

Error thrown from [here](https://github.com/Automattic/woocommerce-payments/blob/2.8.1/includes/payment-methods/class-upe-payment-gateway.php#L466).

### PR DESCRIPTION
**Pull request by bborman22**
Fixes #2665

#### Changes proposed in this Pull Request

This PR is to check for the payment_method_details before referencing it as an array. This error would show up when a Giropay or Sofort payment was failed and kicked back to the store site.

#### Testing instructions

* Enable giropay and sofort payment method from wcpay settings page.
* Purchase with giropay / sofort.
* Fail the payment.
* Get generic error message: "We're not able to process this payment. Please try again later."

-------------------

- [x] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

### CODE REVIEW

**Review by vbelolapotkov — APPROVED** [review]
LGTM! :shipit:

**Review by FangedParakeet — APPROVED** [review]
I tested both forks in the road for both payment intents and setup intents with the redirection payment flow, by succeeding and failing payments via Stripe and everything worked as expected! The issue here is that when the intent has an error, there are a few expected fields that are unexpectedly no longer present, and attempting to reference these fields--even though they won't be used, since there is an error--causes a painful PHP error. I can't see any more opportunities for PHP errors any more in this scenario and my testing proved just as much.

Cheers whoever caught this just in time and thanks for getting the fix out so fast, @bborman22! L.G.T.M. :shipit:

**Comment by shendy-a8c** [comment]
I haven't checked in details but I see [a bit down in the same function](https://github.com/Automattic/woocommerce-payments/pull/2675/files#diff-b541c0a287f40f82a1d0e43c52c7c7a2b67ae233f261655cbb437726fec83feeR488), `$payment_method_type` that now might be null, is used as array's key. I guess it's OK since it's used in `isset()`?

**Comment by FangedParakeet** [comment]
@shendy-a8c `$payment_method_type` should only be `null` if there is an error on the intent, in which case we throw a `Process_Payment_Exception`, which returns the user to the checkout, before we touch any of the code that might use that variable. I don't think it's possible for Stripe to return us an empty object for that parameter without an error. 

If that were to somehow be the case, something very, very bad has happened along the way! 😂 But I think you're right to state that that `isset` would protect us in the event of this ultimate, apocalyptic disaster.

**Pull request merged**
