### PR TITLE
Ajax load selected customer tokenized cards during subscription creation on admin

### LINKED ISSUE #3101: When creating subscriptions from admin, logged-in admin's saved payments show up instead of the chosen customer's.
### Describe the bug

When creating subscriptions from admin, logged-in admin's saved payments show up instead of the chosen customer's.

### To Reproduce

1. Purchase a product as a logged in admin user.
2. When paying, save the payment.
3. Create a new customer. Admin > Users > Add New. Choose Role: Customer.
4. Create a new subscription. Admin > WooCommerce > Subscriptions > Add Subscription.
5. Choose the newly created customer.
6. Choose Payment Method 'Credit card / debit card' or 'WooCommerce Payments' if that option shows up.

### Actual behavior

A Saved payment method dropdown shows up with saved payment of the logged-in admin user even though customer is the newly created customer.

### Expected behavior

Saved payment method dropdown should show up saved payments that belong to the selected customer instead of the logged-in user.

### PR DESCRIPTION
**Pull request by leonardola**
Fixes #3101

#### Changes proposed in this Pull Request
This PR creates a way to ajax load the selected customer's tokenized cards when creating a new subscription via wp-admin. Before when creating a subscription the credit cards loaded were the merchant ones. Now after selecting a customer the correct credit cards are shown.
##### 1
- With WC Subscriptions Pro **disabled**
- Logged in as a merchant go to My account > Payment Methods
- Add a new credit card
- As a merchant go to WooCommerce > Subscriptions > Add new
- Select the shopper as a customer
- Edit the billing and select WooCommerce Payments as Payment Method
- Make sure the Saved payment methods shown are the shopper's cards and not the merchant's
- Repeat with WC Subscriptions pro **enabled**

##### 2
- As a shopper buy any subscription product
- As a merchant go to WooCommerce > Subscriptions and edit the latest subscription
- Make sure the Saved payment methods shown are the shopper's cards and not the merchant's 
- Make sure the Saved payment method selected is the correct one

**Post merge**
- [ ] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply)

### CODE REVIEW

**Comment by leonardola** [comment]
@aprea can you take another look here so we can merge this?

**Comment by haszari** [comment]
Thanks for the reminder @leonardola - I've re-requested review from `@helix` so someone can take another look.

As I understand it, this issue affects a less important flow - admin manually editing payment info for a subscription. If this PR is a safe, robust fix then it will be great to improve this area.

**Comment by aprea** [comment]
Testing package below

[woocommerce-payments.zip](https://github.com/Automattic/woocommerce-payments/files/7836162/woocommerce-payments.zip)

**Comment by aprea** [comment]
I noticed an issue when creating a subscription manually via WooCommerce > Subscriptions > Add new. The selected saved payment method is not "sticking" when updating the subscription.

Though this might be expected, i.e. this was an existing problem and not strictly related to the changes in this PR.

**Steps to reproduce:**
- WCS is disabled.
- Create a simple subscription product.
- As the admin/merchant, go to My account > Payment Methods.
- Add one or two new credit card payment methods (I added 2 Visa cards).
- Log out.
- As a shopper, register for a new account via My account (you must enable sign-ups via my account option on WooCommerce > Settings.)
- Go to My account > Payment Methods.
- Add one or two new credit card payment methods (I added 2 Mastercard cards).
- Log out.
- Log back into the merchant/admin account.
- Go to WooCommerce > Subscriptions > Add new.
- Select the shopper as a customer.
- Edit the billing details and select WooCommerce Payments as Payment Method.
- Note that "Saved payment method" should show the customers saved payment methods.
- Select one of the saved payment methods.
- Add the subscription product to the subscription.
- Click the "Update" button.
- Observe, after the page request completes, the "Payment Method" has reverted to "Manual Renewal".

I also noticed we have this existing GH issue - https://github.com/Automattic/woocommerce-payments/issues/3384

> When creating a new subscription manually via the admin screen, selecting WooCommerce Payments as the payment method and selecting a card/token won't actually save as WCPay because the subscription will be treated as manual because it doesn't have a WCPay Subscription ID.

And the expected behaviour is:

> We should remove all payment method options from this dropdown so admin users aren't given an option that isn't valid. ie Manual renewal should be the only option.

cc @james-allan, does this invalidate the fix/changes in this PR? Or do we still need these changes for WCS?

**Comment by james-allan** [comment]
> cc @james-allan, does this invalidate the fix/changes in this PR? Or do we still need these changes for WCS?

I believe we'd still need these changes for WC Subscriptions (the plugin).

That is:

1. With the WC Subscriptions plugin active, when creating a subscription you should only see tokens associated with the customer - fixed with this PR I'm assuming. 
2. Without WC Subscriptions, you can only really create manual subscriptions so no payment method options should be shown. At the moment this is bugged because options are shown, you could try to select WC Pay, select a token and then save, however, it would get set to manual anyway. 

I think leaving (2) to be fixed separately is fine. It was dropped from the original launch of WC Pay Subscriptions as it had a backstop anyway so isn't a huge priority.

**Comment by shendy-a8c** [comment]
Hi all, I think we can close this PR without merge.

Hear me out =)

I created issue https://github.com/Automattic/woocommerce-payments/issues/3101 (which this PR is trying to fix) based on my observation that the logged-in admin's saved payments are the ones that show up when admin is trying to create a subscription from the admin page. I just tested again and it's actually *all* saved payments show up at the dropdown.
Screen Shot 2022-06-16 at 16 20 22

Recently, I worked on PR https://github.com/Automattic/woocommerce-payments/pull/4307 which fixes a bug when a payment for renewal failed and the subscription is updated with a new payment, on a payment retry, the renewal order doesn't pick up the new payment.

It reminded me of https://github.com/Automattic/woocommerce-payments/issues/3101 and this PR because I thought if https://github.com/Automattic/woocommerce-payments/issues/3101 is a valid bug, when admin updates subscription, they won't be able to choose the correct customer's saved payment.

Upon closer look, I see that we don't have any problem here because:
- All saved payments will show up from the dropdown only when customer is not yet set. After selecting a customer and clicking the 'Update' / 'Create' button, only the saved payments belonging to the customer attached to that subscription will show up, correctly.

- When creating a subscription and only selecting a customer from the dropdown before clicking the 'Create' button, all saved payments will show up, and if the admin happens to select a saved payment that doesn't belong to the selected customer, an error will show up and payment will be set as `Manual Renewal`.

Screen Shot 2022-06-16 at 16 48 13

Screen Shot 2022-06-16 at 16 50 42

This is similar as observed by @aprea in his [comment](https://github.com/Automattic/woocommerce-payments/pull/3221#issuecomment-1008450677).

Therefore, we will never end up setting a saved payment that doesn't belong to the customer that is attached to the subscription.

On top of that, @haszari [brought up](https://github.com/Automattic/woocommerce-payments/pull/3221#issuecomment-1008359051) a good point that this flow, creating a subscription from admin page and admin chooses a saved payment for that subscription, is pretty rare. It makes more sense for admin to: a) create a subscription, b) create a pending parent order, and c) send the link to the customer to make payment.

Screen Shot 2022-06-16 at 17 18 52

I see @leonardola has done great work in this PR and there were already a lot of discussion in this PR but I feel like it'd be simpler not to ship this fix because there is no issue initially.

What do you think?

**Comment by haszari** [comment]
Your analysis makes sense to me @shendy-a8c  - I agree we can close this PR and issue #3101. Feel free to proceed - I'll leave the closing to you 😁

**Comment by shendy-a8c** [comment]
Closing this. Feel free to reopen if it makes more sense.

**Pull request closed without merging**
