### PR TITLE
Saving Payments -> Settings fails because of the Card Readers settings validation along with E2E tests

### LINKED ISSUE #3737: Unable to update settings due to requirements for in person payments settings
### Describe the bug
In the latest develop branch if you go to Payments > Settings and try to make any changes, they will not work. This appears to be due to validation for certain fields for in person payments as included in https://github.com/Automattic/woocommerce-payments/pull/3535 . 

### To Reproduce

* Go to Payments > Settings
* Make a change to a setting.
* Attempt to save.

### LINKED ISSUE #3740: E2E tests breaking due to failed card reader receipt settings validation
The merging of #3535 seems to have introduced breakages in our E2Es. See this [failed run](https://github.com/Automattic/woocommerce-payments/actions/runs/1773565020) for reference.

@deepakpathania's investigation uncovered the following error:

> ``` {"code":"rest_invalid_param","message":"Invalid parameter(s): account_business_support_email","data":{"status":400,"params":{"account_business_support_email":"Error: Support email address is required!"},"details":{"account_business_support_email":{"code":"rest_invalid_pattern","message":"Error: Support email address is required!","data":null}}}} ```

### PR DESCRIPTION
**Pull request by mordeth**
Fixes #3740  
Fixes #3737

#### Changes proposed in this Pull Request

- Fixing saving `Payments` -> `Settings` when the `business_email_address` setting field is not presented from Card Readers settings page.
- Fixing E2E tests. 

#### Testing instructions

- Go to Payments > Settings.
- Make a change to a setting.
- Attempt to save.
- Verify the saving is successful and the setting is updated.

-------------------

- [x] Added changelog entries to both `readme.txt` and `changelog.txt` (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

**Comment by kalessil** [comment]
Probably related: https://github.com/Automattic/woocommerce-payments/issues/3737

**Comment by anu-rock** [comment]
> Probably related: #3737

Indeed. We should add that this PR will fix it.

**Comment by anu-rock** [comment]
Created #3740 which better describes this PR. Also, updated the PR description to reflect the issues it fixes.

**Review by kalessil — APPROVED** [review]
Code changes looking good! Didn't test though.

**Review by anu-rock — APPROVED** [review]
LGTM 👍 I've also done a code-only review. I'm also relying on the [successful run](https://github.com/Automattic/woocommerce-payments/actions/runs/1782854868) of E2Es on this branch.

**Comment by kalessil** [comment]
Giving a try to manually testing.

**Comment by kalessil** [comment]
Test well, all good!

**Pull request merged**
