### PR TITLE
Delete `client/disputes/details`

### LINKED ISSUE #7363: Clean up legacy dispute screen code
Part of #6883

Now that we've added all dispute details to the Transaction Details screen, we can remove code related to the now unused `/payments/disputes/details` screen.

- [x] Update/rename the accept dispute action function to become the default hook, removing the legacy one. Addressed by https://github.com/Automattic/woocommerce-payments/pull/7456.
	 - Legacy `acceptDispute` action function can be removed
		 - https://github.com/Automattic/woocommerce-payments/blob/8c1558bd3fe67596eb32803357380194d23d0b2c/client/data/disputes/actions.js#L42
	 - New action function added in #7093 can be renamed `acceptDispute`
		 - https://github.com/Automattic/woocommerce-payments/blob/8c1558bd3fe67596eb32803357380194d23d0b2c/client/data/disputes/actions.js#L101
- [x] Remove [openDisputeDetails()](https://github.com/Automattic/woocommerce-payments/blob/a8069441a4be0c5e21a0eb7ba6b579fc76de18aa/tests/e2e/utils/flows.js#L517) used by e2e tests. Addressed in https://github.com/Automattic/woocommerce-payments/pull/7448.
- [x] Remove the [legacy dispute details page](https://github.com/Automattic/woocommerce-payments/blob/2eb4de5d4bca3573339e15197987a3943ffeddf4/client/disputes/details/index.tsx). Addressed in https://github.com/Automattic/woocommerce-payments/pull/7456.
- [x] Remove 'disputes' from the [`details-link` `ParentSegment` type](https://github.com/Automattic/woocommerce-payments/blob/efd9c5a5a0068972eab6827967eac6c8be4ccf6e/client/components/details-link/index.tsx#L18). Addressed in https://github.com/Automattic/woocommerce-payments/pull/7460.
- [x] Delete any other unused code used solely by the `/payments/disputes/details` screen. Addressed in https://github.com/Automattic/woocommerce-payments/pull/7456.

### PR DESCRIPTION
**Pull request by shendy-a8c**
Partially fixes https://github.com/Automattic/woocommerce-payments/issues/7363

Note: this PR's branch is based of https://github.com/Automattic/woocommerce-payments/pull/7456's branch.

#### Changes proposed in this Pull Request

- Delete `client/disputes/details` as it's not used anywhere anymore.
- Clean up `client/disputes/style.scss`.

In `client/disputes/details`, there are 2 components:
- [LegacyDisputeDetails](https://github.com/Automattic/woocommerce-payments/blob/a4cded7f89e90f274468888a2878dbd9b927366d/client/disputes/details/index.tsx), and
- [Actions](https://github.com/Automattic/woocommerce-payments/blob/a4cded7f89e90f274468888a2878dbd9b927366d/client/disputes/details/actions.tsx).

For each, I tried to find imports ([#](https://github.com/Automattic/woocommerce-payments/blob/a4cded7f89e90f274468888a2878dbd9b927366d/client/disputes/details/index.tsx#L13-L24) and [#](https://github.com/Automattic/woocommerce-payments/blob/a4cded7f89e90f274468888a2878dbd9b927366d/client/disputes/details/actions.tsx#L13-L14)) that are only used by them, so I could delete. Can't find any.

I also looked for any `className` so I could clean them up from `client/disputes/style.scss`. I found some:
- `wcpay-dispute-details` (used by `DisputeEvidencePage`, so not deleting), and
- `header-dispute-overview` (not referenced anywhere after `LegacyDisputeDetails` is deleted).

#### Testing instructions

Affected client/disputes/evidence/index.js
Make sure imports from `client/disputes/details/index.tsx` are used by others, so we don't need to delete.
Make sure imports from `client/disputes/details/actions.tsx` are used by others, so we don't need to delete.

* Make sure tests are passing.
* Make sure dispute flows are still working.

Since `client/disputes/evidence/index.js` is the most affected component, make sure the UX and look for the dispute challenge form is not affected by this PR.
* Purchase a product with `4000000000000259` so it triggers a dispute.
* Go to Payments > Transactions > click on the transaction for the new purchase.
* Click on the 'Submit evidence'.
* You will be on the [dispute challenge page](https://github.com/Automattic/woocommerce-payments/blob/a4cded7f89e90f274468888a2878dbd9b927366d/client/index.js#L174-L175).
* Compare base branch and PR branch and make sure that page has the same UI and UX.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7458` or branch name `remove/7363-legacy-dispute-details` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=remove/7363-legacy-dispute-details) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 9352018bc4367010d78da5677a398327d0b8233c
- Build time: 2023-10-12 02:00:06 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by Jinksi** [comment]
As mentioned in https://github.com/Automattic/woocommerce-payments/pull/7456#discussion_r1355944858:

This `doAccept` function returned by the `useDispute` hook can be removed:
https://github.com/Automattic/woocommerce-payments/blob/6b6c530b6ac0604c3b266d4a97d0255e03d9a0a1/client/data/disputes/hooks.ts#L50


Since `LegacyDisputeDetails` was the only consumer of this function:
https://github.com/Automattic/woocommerce-payments/blob/3d4d7a594cf4681a71b4c6b41971b0b67bf50749/client/disputes/details/index.tsx#L31

**Comment by Jinksi** [comment]
> This `doAccept` function returned by the `useDispute` hook can be removed:

I've committed this change in 9352018bc4367010d78da5677a398327d0b8233c

**Comment by shendy-a8c** [comment]
OMG, I meant to hit the merge button for https://github.com/Automattic/woocommerce-payments/pull/7456 but instead I merged this PR.

**Comment by shendy-a8c** [comment]
A bit fortunate that the base branch is not `develop` but https://github.com/Automattic/woocommerce-payments/pull/7456's. Depending on your review to this PR @Jinksi, I can open a new PR.

**Comment by Jinksi** [comment]
> A bit fortunate that the base branch is not develop but https://github.com/Automattic/woocommerce-payments/pull/7456. Depending on your review to this PR @Jinksi, I can open a new PR.

🤭 I'll get back to you shortly with a review, but I think it was looking good! If there is anything, we can address it in #7456.

**Review by Jinksi — COMMENTED** [review]
✅ Post-merge approval! This looks good to me @shendy-a8c 

I tested various flows and all work well and look unchanged, including:
* Accept dispute
* Challenge dispute
* Redirect Dispute Details → Transaction Details

I couldn't find any other legacy code aside from the `useDispute` change I committed in 9352018bc4367010d78da5677a398327d0b8233c. If we spot some in the future, we can remove it.

**Pull request merged**
