### PR TITLE
Pass previous Exception with Exception

### PR DESCRIPTION
**Pull request by hsingyuc**
#### Changes proposed in this Pull Request
While investigating successfully captured and failed orders root causes, I found we could use more information on error ['We're not able to process this request. Please refresh the page and try again.'](https://github.com/Automattic/woocommerce-payments/blob/5b9809465e0fb9ec3476d40f82b85daf82d512e9/includes/class-wc-payments-utils.php#L576-L579)

Changes made in this PR:
1. Passes the previous Exception with `Exception`.
2. Updates `Process_Payment_Exception` inside the `process_payment` to more unique Exceptions like `Fraud_Prevention_Enabled_Exception`, `Invalid_Phone_Number_Exception`, and `Rate_Limiter_Enabled_Exception` so when WC catches the Exception that throws from `process_payment`, we can pass the Exception class as additional data with the Exception to help WooPay better understanding where the errors come from.

#### Testing instructions
1. Test with [WooCommerce PR](https://github.com/woocommerce/woocommerce/pull/47489)
2. Return `true` in [check_nonce](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/StoreApi/Routes/V1/AbstractCartRoute.php#L285)
3. Run the PHP unit tests
4. Test through Postman for each Exception case inside `process_payment`:
    ( I tested them by commenting out the condition check )
   1. Add an item to your cart `{YOUR_DOMAIN}/wp-json/wc/store/v1/cart/add-item`
   
```
Body - Raw - JSON
{
  "id": 2040,
  "quantity": 1
}
```
    
     ii. Checkout with the cart `{YOUR_DOMAIN}/wp-json/wc/store/v1/checkout`
   
 
```
{
  "billing_address": {
        "first_name": "Test",
        "last_name": "Billing",
        "company": "",
        "address_1": "123 test",
        "address_2": "",
        "city": "San Diego",
        "state": "CA",
        "postcode": "92103",
        "country": "US",
        "email": “test@test.com”,
        "phone": "+14708274627"
    },
    "shipping_address": {
        "first_name": "Test",
        "last_name": “Shipping”,
        "company": "",
        "address_1": "123 test",
        "address_2": "",
        "city": "San Diego",
        "state": "CA",
        "postcode": "92103",
        "country": "US",
        "email": "test@test.com",
        "phone": "+14708274627"
    },
  "payment_method": "woocommerce_payments"
}
```
5. See previous exception class in response

*

-------------------

- [X] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8824` or branch name `update/pass-previous-error-to-exception` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=update/pass-previous-error-to-exception) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 3b1598e7f8140f1adeb075c28c6b90ecbf99c080
- Build time: 2024-05-22 18:00:19 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by malithsen** [comment]
Hi @hsingyuc 

Thanks for working on this. 
I haven't fully reviewed this PR yet, but from what I understand, the current problem is that WooPay is receiving a redacted error message, which is the output of `get_filtered_error_message`. This redacted error message isn't helpful for understanding why a merchant order failed from WooPay's perspective.

So, in order to work around this issue, this PR depends on a core change in WooCommerce that retrieves the error class and sends it through the `additional_data` field. Although this works, WooPay will only see the benefits of these changes once merchants update their WooCommerce version. It may take some time for merchants to make this upgrade.

What are your thoughts of conditionally throwing the exception in `process_payment`. If the merchant is processing the payment for WooPay, don't redact the error message. If not, do what we're doing now.

Untested code:

```
if ( ! empty( $_POST['is_woopay'] ) ) {
    // We can also append any other metadata that we think is useful. 
    throw new Exception( $e->getMessage() );
} else {
    // Re-throw the exception after setting everything up.
    // This makes the error notice show up both in the regular and block checkout.
    throw new Exception( WC_Payments_Utils::get_filtered_error_message( $e, $blocked_by_fraud_rules ) );
}
```

**Comment by hsingyuc** [comment]
>This redacted error message isn't helpful for understanding why a merchant order failed from WooPay's perspective.

If I understood you correctly, that's the reason for this PR to log the Exception class so it will be easier for us to find where the error comes from.

>So, in order to work around this issue, this PR depends on a core change in WooCommerce that retrieves the error class and sends it through the additional_data field. Although this works, WooPay will only see the benefits of these changes once merchants update their WooCommerce version. It may take some time for merchants to make this upgrade.

I agree with you that it would take some time.  I think retrying orders and auto refunding gives us time to solve the other issues and If we had merged the [previous](https://github.com/Automattic/woocommerce-payments/pull/7873) PRs, we would have the information to find the root causes of this issue by now.  I believe we can and should both add additional data and look for another faster solution this time.

>What are your thoughts of conditionally throwing the exception in process_payment. If the merchant is processing the payment for WooPay, don't redact the error message. If not, do what we're doing now.

Wouldn't this error message be shown to shoppers?  We can try to check if it's WooPay and then use `WooPayMeta` like I did before, but I think we should get a proper solution in place long-term.

**Comment by malithsen** [comment]
> Wouldn't this error message be shown to shoppers? 

@hsingyuc No, it won't be shown to the shopper. It will just be logged on WooPay logs. WooPay shows a custom error to the shopper instead of showing the error from the merchant site as-is.

https://github.com/Automattic/woopay/blob/5e1060b18b607c16499a3c79571203b0b9d47690/src/Checkout/PaymentsHandler.php#L400

**Review by malithsen — APPROVED** [review]
Thanks for working on this @hsingyuc, I've tested this with the WC-core PR and was able to get the class-name on to WooPay error logs, which will help narrow down merchant-store errors WooPay shoppers encounter.

> If we had merged the https://github.com/Automattic/woocommerce-payments/pull/7873 PRs, we would have the information to find the root causes of this issue by now.

I disagree. The PR you linked sends `intent_meta_order_id` and `order_id` via `additional_data`, same information is currently available to us via the changes in https://github.com/Automattic/woocommerce-payments/pull/7951. 

I do agree that, had we gone ahead with your core changes earlier, it would help us with the additional logs we are adding now :)

**Comment by hsingyuc** [comment]
@malithsen, thank you for the review!

>I disagree. The PR you linked sends intent_meta_order_id and order_id via additional_data, same information is currently available to us via the changes in https://github.com/Automattic/woocommerce-payments/pull/7951.

Sorry, I meant to link to the [WC PR that allows us to pass additional data to exceptions.](https://github.com/woocommerce/woocommerce/pull/42685).  This would mean that a number of WooCommerce stores already allow additional data in the Store API responses so we could try and diagnose some of these errors.

Screenshot 2024-05-22 at 1 53 03 PM

**Pull request merged**
