### PR TITLE
Format the currency properly in the exchange preview field

### LINKED ISSUE #2375: Use target currency format in the exchange preview
The conversion preview is missing the thousands separator. More specifically, I think it should use the local currencies format, (currency position, thousand and decimal separators) since it's representing what the customer will see on the site, formatted for their locale.

h/t @LevinMedia

### PR DESCRIPTION
**Pull request by DanReyLop**
Fixes #2375

#### Changes proposed in this Pull Request

Properly format the "Preview" money amount in the currency exchange settings. This includes:
- Putting the currency symbol in the right/left side of the amount, as expected.
- Proper thousands and decimal separators.
- Correct amount of decimal digits.

Instead of using the `@woocommerce/currency` package, or trying to replicate the PHP logic in JS, I just used the built-in [`Number.toLocaleString()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString#browser_compatibility) function. It will take care of every localization issue.

Note that, as the locale, I passed `undefined`. That's equivalent of using the `"default"` locale for a given currency. Since this is the admin user seeing it, that seemed like the most sensible approach. We can't know at this point where will the customer visit the store from, so any locale we put there would be a guess.

#### To test:
- Set your store to USD.
- Go to the Multi-currency settings.
- Add a second currency (EUR, for example).
- Click on "manage" to get to the `Euro (EUR)` settings screen.
- On the Preview section, you'll see that the amount has a valid format (or, at least, valid for some locale. As a Spaniard, I find the `€99` quite weird, but a default is a default).
- Try and break it. Non-numeric amounts, price rounding, charm pricing, manual exchange, thousands, decimals, zero-decimal currencies...

### CODE REVIEW

**Comment by ismaeldcom** [comment]
Code LGTM and works as expected.

Only have a little doubt about the symbol. Already saw p1627053786048300-slack-C01B8KNUYSW. But not sure if this will consistent with the customer side.

Few examples:
| Currency | Admin preview | Store |
|-|-|-|
| ALL | ALL | L |
| DZD | DZD | د.ج |
| AMD | ֏ | AMD |
| AWG | AWG | Afl. |
| AZN | ₼ | AZN |
| BGN | BGN | лв. |
| MMK | K | Ks |
| BIF | BIF | Fr |
| XPF | CFPF | Fr |
| CVE | CVE | $ |
|  |  |  |
|  |  |  |
|  |  |  |
|  |  |  |
| DKK | kr  | DKK |

**Comment by ismaeldcom** [comment]
Code LGTM and works as expected.

Only have a little doubt about the symbol. Already saw p1627053786048300-slack-C01B8KNUYSW. But not sure if this will consistent with the customer side.

Few examples:
| Currency | Admin preview | Store |
|-|-|-|
| ALL | ALL | L |
| DZD | DZD | د.ج |
| AMD | ֏ | AMD |
| AWG | AWG | Afl. |
| AZN | ₼ | AZN |
| BGN | BGN | лв. |
| MMK | K | Ks |
| BIF | BIF | Fr |
| XPF | CFPF | Fr |
| CVE | CVE | $ |
| XAF | FCFA | CFA |
| DKK | kr  | DKK |

**Comment by DanReyLop** [comment]
That's a good point. I really think we shouldn't try to reinvent the wheel in the client. If there's a built-in solution to format currencies and take care of all the nuances related to internationalization, then we should try to use that.

I've just tried testing `ALL` (Albanian Lekë). This is what I found:
```
> (123).toLocaleString('al-AL', {style:"currency", currency:"ALL"})
< "ALL 123.00"
> (123).toLocaleString(undefined, {style:"currency", currency:"ALL", currencyDisplay:"name"})
< "123.00 Albanian lekë"
> (123).toLocaleString(undefined, {style:"currency", currency:"ALL", currencyDisplay:"narrowSymbol"})
< "ALL 123.00"
> (123).toLocaleString('sq-AL', {style:"currency", currency:"ALL", currencyDisplay:"narrowSymbol"})
< "123,00 Lekë"
> (123).toLocaleString('es-ES', {style:"currency", currency:"ALL", currencyDisplay:"narrowSymbol"})
< "123,00 ALL"
> (123).toLocaleString('sq-AL', {style:"currency", currency:"ALL", currencyDisplay:"narrowSymbol"})
< "123,00 Lekë"
```

So, it looks like my browser (Safari 14) defaults to printing the currency code (`ALL`) unless the locale is set to Albania. That's not ideal. I've also found that on our massive `locale-info.php` array, we don't have a `short_symbol` defined for the `ALL` currency. That symbol (`L`) is on WC Core. The `short_symbol` property is also never used in our code, unless there's an in-progress PR that makes use of it?

The main issue here is that there are tons of different ways we're formatting currencies:
- Using the `@woocommerce/currency` package in JS. It just has a handful of currencies defined, so the most obscure ones will just be rendered using their currency code.
- Using our massive `locale-info.php` array, hooking into WC Core filters.
- Letting WC Core do its thing. WC Core also has a massive array of `currencyCode => currencySymbol` mapping.
- Using the built-in `toLocaleString()` in the client (this PR).

Using the `@wc/currency` package seems like the worst possible option. So, when we need to format a currency in JS, we must either use `toLocaleString()`, or create a new way of formatting currencies in JS.

I'll leave this open to discussion. I think there are tradeoffs in all the approaches, but I think that at least in this case it's not terribly important. The preview is there mainly to show off the charm/rounding settings.

**Review by ismaeldcom — APPROVED** [review]
💯  Agree. I think we could merge this for the MVP. And let the discussion open to discuss how we want to approach this in the future. At least for me, this is the best client side solution. Thinking of maintain another custom formatter for JS having a standard one looks like a terrible approach.

I'll approve it now.

**Pull request merged**
