### PR TITLE
Prevent WooPay webhook creation attempt when account is suspended

### PR DESCRIPTION
**Pull request by malithsen**
Fixes https://github.com/Automattic/woopay/issues/2443

#### Changes proposed in this Pull Request
- Adds a check to prevent the WooPay webhook creation request when the WCPay account is suspended

##### Recreate the error
- Mark the WCPay account as suspended by updating the `account_suspended` column in the `wcpay_accounts` table in your local WCPay server for your test account.
- In WCPay Dev Tools in WCPay client, clear the account cache.
- In WCPay client's `/wp-admin/admin.php?page=wc-settings&tab=advanced&section=webhooks` disable any existing WooPay webhooks.
- Refresh the page.
- In WCPay server logs (`logstash.log`) note the `Could not process the account.` errors from requests to the `accounts/platform_checkout` endpoint.

##### Test the fix
- Checkout this branch
- Visit the WCPay client's admin area.
- There shouldn't be any errors from the `accounts/platform_checkout` endpoint.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8118` or branch name `fix/woopay-webhook-on-suspended-accounts` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/woopay-webhook-on-suspended-accounts) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 831531aaba281c6c05670cb6f94904a17019e61e
- Build time: 2024-02-08 05:23:25 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by hsingyuc — COMMENTED** [review]
@malithsen Thank you for working on this!  I see `Could not process the account` errors from requests to the `accounts/platform_checkout` on the WCPay server logs(logstash.log) on both `develop` and this branch.   On the WCPay client's admin area, I don't see any errors from the `accounts/platform_checkout` on either `develop` or this branch.   Can you tell me what difference should I see here or any steps I missed? Thanks!

**Comment by malithsen** [comment]
> On the WCPay client's admin area, I don't see any errors from the accounts/platform_checkout on either develop or this branch

@hsingyuc this issue will not log any errors in the client logs. However if you still see log entries in the following format in your server logs with this PR applied + on a suspended account + no WooPay webhooks active that could be an indication of other sources of the error. If it helps here is the complete entry I see in my server logs

```
[06-Feb-2024 04:29:58 UTC] WCPay url: /wp-json/wpcom/v2/sites/REDACTED/wcpay/accounts/platform_checkout?home=http%3A%2F%2Fwcpay.test&siteurl=http%3A%2F%2Fwcpay.test&idc=1&token=REDACTED&timestamp=1707193792&nonce=gzuChPyRt3&body-hash=Dzu76EpoYJwJtjRPiWwqTdqbkjs%3D&signature=REDACTED
[06-Feb-2024 04:29:58 UTC] WCPay method: POST
[06-Feb-2024 04:29:58 UTC] WCPay properties: {"request_route":"\/wpcom\/v2\/sites\/REDACTED\/wcpay\/accounts\/platform_checkout"}
[06-Feb-2024 04:29:58 UTC] WCPay tags: ["wcpay_client_7.1.0","sandbox","api-debug"]
[06-Feb-2024 04:29:58 UTC] WCPay es_retention: 1w
[06-Feb-2024 04:29:58 UTC] WCPay trace: API data: {
[06-Feb-2024 04:29:58 UTC] WCPay     "home": "http:\/\/wcpay.test",
[06-Feb-2024 04:29:58 UTC] WCPay     "siteurl": "http:\/\/wcpay.test",
[06-Feb-2024 04:29:58 UTC] WCPay     "idc": "1",
[06-Feb-2024 04:29:58 UTC] WCPay     "token": "REDACTED",
[06-Feb-2024 04:29:58 UTC] WCPay     "timestamp": "1707193792",
[06-Feb-2024 04:29:58 UTC] WCPay     "nonce": "gzuChPyRt3",
[06-Feb-2024 04:29:58 UTC] WCPay     "body-hash": "Dzu76EpoYJwJtjRPiWwqTdqbkjs=",
[06-Feb-2024 04:29:58 UTC] WCPay     "signature": "REDACTED",
[06-Feb-2024 04:29:58 UTC] WCPay     "test_mode": true,
[06-Feb-2024 04:29:58 UTC] WCPay     "webhook_secret": "REDACTED"
[06-Feb-2024 04:29:58 UTC] WCPay }

[06-Feb-2024 04:29:58 UTC] WCPay blog_id: REDACTED
[06-Feb-2024 04:29:58 UTC] WCPay feature: wcpay-sandbox-debug
[06-Feb-2024 04:29:58 UTC] WCPay message: Could not process the account.
[06-Feb-2024 04:29:58 UTC] WCPay user_id: 1
[06-Feb-2024 04:29:58 UTC] WCPay severity: debug
[06-Feb-2024 04:29:58 UTC] WCPay plugin: woocommerce-payments-server
[06-Feb-2024 04:29:58 UTC] WCPay error_code: wcpay_could_not_process_account
[06-Feb-2024 04:29:58 UTC] WCPay http_response_code: 403
```

If you continue to see similar log entries with this PR applied, can you try adding a breakpoint [here](https://github.com/Automattic/woocommerce-payments/blob/9a42921fc5f89c6a15e1c2833962f587264b6c2b/includes/woopay/class-woopay-order-status-sync.php#L80) and checking if it reaches that line for you?

**Comment by malithsen** [comment]
@hsingyuc Thinking more about what you noticed, after updating the server db to suspend the account, you might also want to clear the account cache via WCPay dev tools. I just updated the test instructions to include this.

**Review by hsingyuc — APPROVED** [review]
Thank you for the update that make sense.  Tests are as expected and LGTM.

**Pull request merged**
