### PR TITLE
Fix Klarna E2E tests

### LINKED ISSUE #8416: Placing an order with Klarna e2e test keeps failing
### Describe the bug

[Placing an order with Klarna e2e test](https://github.com/Automattic/woocommerce-payments/blob/67e989e1eaec3066cb0589e114c75727838cfa59/tests/e2e/specs/wcpay/shopper/shopper-klarna-checkout.spec.js#L80) keeps failing.

Example run: https://github.com/Automattic/woocommerce-payments/actions/runs/8335400815

### PR DESCRIPTION
**Pull request by ricardo**
Fixes #8416

### Changes proposed in this Pull Request

The Klarna test environment UI has been updated.

This PR updates the selectors as needed and adds a few 2s intervals to account for page transition and animations.

### Testing instructions

No testing is required, but ensure [the workflow run for this branch](https://github.com/Automattic/woocommerce-payments/actions/runs/9184811190) passes for `wcpay - shopper` Klarna checkout spec:

```
PASS tests/e2e/specs/wcpay/shopper/shopper-klarna-checkout.spec.js
```

We still have other specs failing at this branch, but in `develop` all Klarna tests are failing: [E2E Tests - All](https://github.com/Automattic/woocommerce-payments/actions/workflows/e2e-test.yml).

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8858` or branch name `fix/8416-klarna-e2e-tests-final` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/8416-klarna-e2e-tests-final) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: bd54857b277b9f11e26424255bd5cb7ad88deb87
- Build time: 2024-05-22 19:40:36 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by rafaelzaleski — COMMENTED** [review]
I tried to [run the tests in the CI twice](https://github.com/Automattic/woocommerce-payments/actions/runs/9191869913/job/25279206010#logs), but I'm encountering an error. Do you know what it can be?

```
 at Frame.<anonymous> (/home/runner/work/woocommerce-payments/woocommerce-payments/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.waitForSelector (/home/runner/work/woocommerce-payments/woocommerce-payments/node_modules/puppeteer/lib/Page.js:1122:29)
    at getNewKlarnaIframe (/home/runner/work/woocommerce-payments/woocommerce-payments/tests/e2e/specs/wcpay/shopper/shopper-klarna-checkout.spec.js:109:41)
    at Page.frameNavigationHandler (/home/runner/work/woocommerce-payments/woocommerce-payments/tests/e2e/specs/wcpay/shopper/shopper-klarna-checkout.spec.js:119:34)
```

**Comment by ricardo** [comment]
Klarna seems to be iterating pretty fast on their UI. I had seen changes in DOM elements while working on this fix, and they seem to have changed a selector just now – [bd54857](https://github.com/Automattic/woocommerce-payments/pull/8858/commits/bd54857b277b9f11e26424255bd5cb7ad88deb87).

[Now tests are passing](https://github.com/Automattic/woocommerce-payments/actions/runs/9197377143/job/25297666469#step:4:627) again, but if Klarna continues to update the selectors we might need to fix them again. 😬 

@rafaelzaleski can you give it another look?

**Review by rafaelzaleski — APPROVED** [review]
The code looks good to me. [The Klarna tests passed on a second attempt](https://github.com/Automattic/woocommerce-payments/actions/runs/9208707800/job/25331521277#step:4:527).

**Comment by ricardo** [comment]
> [The Klarna tests passed on a second attempt](https://github.com/Automattic/woocommerce-payments/actions/runs/9208707800/job/25331521277#step:4:527).

I'll merge although the tests might be failing sometimes. As I mentioned above, they have been changing their UI [quite frequently](https://github.com/Automattic/woocommerce-payments/pull/8858#issuecomment-2125672902).

**Pull request merged**
