### PR TITLE
Migrate link-item to typescript

### LINKED ISSUE #7052: Migrate link-item.js and woopay-item.js to typescript.
### Description

Migrate `link-item.js` and `woopay-item.js` to typescript.

As part of https://github.com/Automattic/woocommerce-payments/issues/6428 improvements, it would be good to convert all the js files to tsx. It would be nice to handle it as a separate issue as target in `tsconfig` needs to be updated to `es6` to convert `link-item` to tsx.
### Acceptance criteria

* Migrate `link-item.js` and `woopay-item.js` to typescript.

### Testing instructions

1. Perfome smoke testing
2. Make sure there are on ts related errors
3. E2E tests should pass

### PR DESCRIPTION
**Pull request by naman03malhotra**
Fixes #7052 

#### Changes proposed in this Pull Request
- Migrated `link-item.js` to typescript.
- Updated target to `es6` in `tsconfig` to allow spread operator.

#### Testing instructions

* Test if link-item is working as expected in settings page in both desktop and mobile
* Please verify it visually as I have moved CSS in JS to CSS file.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [x] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [x] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7080` or branch name `imp/7052-migrate-to-ts` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=imp/7052-migrate-to-ts) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: cc9d6075b84a4e77da5fd4cf5a41cc3645570a28
- Build time: 2023-08-29 18:35:37 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by naman03malhotra** [comment]
@ismaeldcom I've updated the target in tsconfig to ES6, can you please check it once.

**Comment by ismaeldcom** [comment]
Hey @naman03malhotra! I wonder what's the use case for the tsconfig target update. I see `Updated target to es6 in tsconfig to allow spread operator` on the proposed changes, but we don't actually need to modify the target for that.

The target option in TS config stand for which target of JavaScript will be emitted, but doesn't affect which TS/JS features we can use while coding.

Although, with our current browser support it's probably okay to start targeting ES6 instead of ES5 🙂

**Comment by naman03malhotra** [comment]
>I wonder what's the use case for the tsconfig target update. I see Updated target to es6 in tsconfig to allow spread operator on the proposed changes, but we don't actually need to modify the target for that.

With the target as ES5, ts throws an error regarding the usage of ES6 goodies. There are other ways to solve it, but I found this the recommended way.

**Comment by naman03malhotra** [comment]
This what you get when using spread operator with ES5 as target.
```
Type 'Set<any>' can only be iterated through when using the '--downlevelIteration' flag or with a '--target' of 'es2015' or higher.ts
```

I think it should be safe to update the target to ES6 with the present browser support.

**Review by ismaeldcom — APPROVED** [review]
Oh! I thought it was due to the use of the spread operator, but it's due to the iteration of `Set`. Yep, updating the target to ES6 is probably the easiest way to do it.

I just checked our current supported browsers, and can confirm that it's safe to use ES6 from now on 🙂

**Comment by naman03malhotra** [comment]
@ismaeldcom can you please take a look at https://github.com/Automattic/woocommerce-payments/pull/7081 which is an extension of this PR :)

**Review by zmaglica — APPROVED** [review]
LGTM! I tested the changes on my local env. and everything is working.

**Pull request merged**
