### PR TITLE
Fix missing customer information after guest checkout via Checkout Block

### LINKED ISSUE #2296: No customer information available after guest checkout via the Checkout Block
## Reproduction Steps

**Setup**

1. Install the [WooCommerce Blocks](https://wordpress.org/plugins/woo-gutenberg-products-block/) plugin
2. Create a new page and add the Checkout block to that page

**Reproducing the issue**

1. Open up a new private browser window (or any other form of a _new session_)
2. Navigate to the new block-based checkout page
3. Fill in the required information to checkout
4. Navigate to **Payments > Transactions** in wp-admin
5. Note that there is no customer information associated with the transaction in the transaction list or transaction details.
6. Click the order number in the transactions list to navigate to the order associated with the transaction
7. Note that the customer information is present

## Expected results

| Payment Details | Payment Overview | Transactions List |
|:---:|:---:|:---:|
| image | image | image |

## Actual results

| Payment Details | Payment Overview | Transactions List |
|:---:|:---:|:---:|
| image | image | image |

### PR DESCRIPTION
**Pull request by malithsen**
Fixes #2296 

#### Changes proposed in this Pull Request

When checking out as a guest with checkout block customer information is not captured and payment methods are created on Stripe with empty billing address fields. This change fixes this by adding `billingData` as a dependency to the `onPaymentProcessing` effect so that it registers updates to the `billingData` fields.

#### Testing instructions

1. Install the [WooCommerce Blocks](https://wordpress.org/plugins/woo-gutenberg-products-block/) plugin
2. Create a new page and add the Checkout block to that page
3. Open up a new private browser window (or any other form of a new session)
4. Navigate to the new block-based checkout page
5. Fill in the required information to checkout
6. Navigate to Payments > Transactions in wp-admin
7. Ensure that customer information associated with the transaction is visible in the transaction list and the transaction details.
8. Click the order number in the transactions list to navigate to the order associated with the transaction
9. Ensure that the customer information is present

Screen Shot 2021-10-01 at 1 54 39 PM

-------------------

- [x] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply)

### CODE REVIEW

**Comment by ricardo** [comment]
@malithsen You probably have noticed this, but when I click a guest customer name from **Payments > Transactions**, it links me to `?page=wc-admin&path=/customers&filter=single_customer&customers=0`, which shows an empty table.

If you provide the customer ID to the `customers` param, it will display the given customer in that table.

Since the guest customer column wasn't showing up before, I'm not sure if the above could be part of this issue or not. Let me know what you think. If it's not an easy fix we can split into a different issue.

**Comment by malithsen** [comment]
Hi @ricardo AFAICT they are separate issues, so created https://github.com/Automattic/woocommerce-payments/issues/3037. When checking out as a guest, we don't seem to populate Customer entries on WooCommerce side, although a guest customer entry on Stripe is created.

**Review by ricardo — APPROVED** [review]
Sounds good 👍 

LGTM!

**Comment by malithsen** [comment]
Above e2e tests failures are caused by changes in `develop`. See p1634131666010900-slack-C026J0AL8NS

**Pull request merged**
