### PR TITLE
Fix BNPL payment method messaging loading state

### LINKED ISSUE #9244: BNPL - Respect minimum order amounts when adding the PMME to the page
### Describe the bug

BNPL has [minimum order amounts](https://github.com/search?q=repo%3AAutomattic%2Fwoocommerce-payments%20limits_per_currency&type=code). Stripe uses the total when determining which BNPL methods are applicable. If no payment methods are applicable, say due to the total not hitting the minimum, no payment methods are displayed. Until recently, this wasn't a problem because nothing would be displayed on the page. However, the container with id `payment-method-message` is still added to the page and contains an empty Stripe iframe. Since https://github.com/Automattic/woocommerce-payments/pull/9166, a skeleton loader is added. When minimum order amounts aren't hit, the skeleton loader still appears, but no PMME is displayed when loading is finished. The result is a loader that appears to load nothing.

### To Reproduce

1. Enable all BNPL payment methods
2. Set your currency to USD
3. Create a product that is less than $1. 
4. Navigate to the product and see the skeleton loader appear

### Screenshots

https://github.com/user-attachments/assets/680ace22-648f-4849-bf80-1d691b33de22

### Expected behavior

The loader shouldn't appear if minimum order amounts aren't met for the selected currency.

### PR DESCRIPTION
**Pull request by cesarcosta99**
Fixes #9244.

#### Changes proposed in this Pull Request

This fixes the BNPL payment method messaging loading state. Previously, the skeleton was being displayed even if the product amount was lower than the minimum.

I needed to make the frontend aware of the minimum value so it has a value to compare to. Stripe doesn't provide a way to retrieve that information from [their API](https://docs.stripe.com/api), so I needed to build up a hardcoded list - sourced this idea from the Stripe extension [[ref](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/64e953a09e4c162af6e853c74c74cb279308c793/includes/class-wc-stripe-helper.php#L346-L382)]. I pulled the values for this list from [the Stripe docs](https://docs.stripe.com/currencies#minimum-and-maximum-charge-amounts).

#### Testing instructions

**Setup**

1. After switching to this branch, build the assets: `npm run build:client`.
2. As a merchant, navigate to **Payments > Settings**.
3. Scroll down to the **Buy now, pay later** section and enable Affirm, Afterpay and Klarna.
4. Save the changes.
5. Navigate to **Products > Add New**.
6. Insert a product that is less than $0.50 and publish it.

**Test: Ensure the payment method messaging skeleton works as expected**

1. As a shopper, navigate to the shop and set your currency to USD.
2. Click on a regular product.
3. You should see a skeleton indicating the messaging component is loading - as in the screenshot below.
4. The messaging component should load and be displayed as expected.

image

5. Navigate to the shop and click on the product you created that is less than $0.50.
6. You should **not** see the skeleton and the messaging component should **not** load or be displayed.
7. No **new** console errors should be observed.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9355` or branch name `fix/9244-pmme-skeleton` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/9244-pmme-skeleton) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: db768369585974dec6006558e15505c6304323a1
- Build time: 2024-08-30 18:41:19 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by rafaelzaleski — CHANGES_REQUESTED** [review]
Hiding the skeleton worked, but we still have a blank space that looks a bit odd.

Screen Shot 2024-08-30 at 10 15 59 AM


Screen Shot 2024-08-30 at 10 16 40 AM

**Comment by cesarcosta99** [comment]
> Hiding the skeleton worked, but we still have a blank space that looks a bit odd.

@rafaelzaleski, good call. I initially had thought about conditionally call `initializeBnplSiteMessaging` based on the amount condition we're introducing, however, I wasn't sure what could be impacted since BNPL is new to us.

We can achieve a good UI flow by hiding the container via CSS and I did that in [db76836](https://github.com/Automattic/woocommerce-payments/pull/9355/commits/db768369585974dec6006558e15505c6304323a1). It's a low-risk approach and it keeps the UI looking good. I opted for hiding the message container by default in the product pages (instead of the opposite) as the majority of products should have an amount higher than the minimum, being those an exception.

---

**Update**: ~It looks like Playwright tests are failing, but I'm pretty sure it's flakiness as we can see the same in other PRs and the changes here are unrelated to the failing tests. There is an [issue open](https://github.com/Automattic/woocommerce-payments/issues?q=is%3Aopen+is%3Aissue+label%3A%22category%3A+e2e%22+label%3A%22e2e%3A+broken+test%22) tracking that.~ They passed in the 3rd attempt 😅

**Review by rafaelzaleski — APPROVED** [review]
@cesarcosta99, I tested a product below the minimum amount and another above it, and the UI looks good in both scenarios now. The blank space is gone—thanks for the changes!

**Pull request merged**
