### PR TITLE
Hide the deposits card for merchants without an estimated deposit and deposit history

### LINKED ISSUE #6193: Simplify deposits UI - Hide deposits card until first estimated deposit
### Describe the bug

The Deposits card shouldn't appear for the brand new user. 

This card contains a notice that says: "Your first deposit is held for 7 days". Showing this card before the merchant has even received a payment is misleading and confusing. Merchants could interpret this as starting their 7 day period, when in fact that doesn't start until after they receive their first payment. Before the first estimate, this card doesn't contain any particularly useful information so it should be hidden.

Following advice from @elizaan36, this card should be hidden until the first deposit is estimated.   

### To Reproduce

1. Go to Payments admin menu.
2. For new accounts without any deposits, the deposit card shouldn't be shown. 
3. It should only be shown to merchants with at least an estimated deposit.

### Actual behavior

The deposits card is shown all the time. 

### Screenshots

For new merchants (without an at least 1 estimated deposit):

image

image

### Expected behavior

It shouldn't be shown until there's an estimated deposit.

### PR DESCRIPTION
**Pull request by james-allan**
Fixes #6193

#### Changes proposed in this Pull Request

This PR hides the deposit card when the merchant doesn't have any estimated deposit and no history. 

Prior to this PR, brand new merchants after on-boarding would be shown this screen.

<p align="center">
Screenshot 2023-05-03 at 2 11 19 pm
</p>

Showing the deposits card when the merchant hasn't taken any payments and there's no estimate isn't intended by the design. 

This PR makes sure this card is hidden until the merchant has an estimated deposit (taken at least 1 payment).

| No estimate (fresh account)      | With an estimate |
| ----------- | ----------- |
|  Screenshot 2023-05-03 at 11 53 39 am    | Screenshot 2023-05-03 at 12 35 11 pm       |

#### Testing instructions

**Fresh account**
1. Onboard a fresh WCPay account
2. On `develop` or the live version of WC Payments you will see the Deposits card shown.
3. On this branch the deposits card is hidden.
4. Make a purchase. 
5. View the **Payments > Overview** screen. 
    - The deposits card should now been shown.

** Existing store
1. This change should have no impact on existing merchants with deposits.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6195` or branch name `fix/6193-hide-deposits-card-for-new-merchants-no-deposits` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=fix/6193-hide-deposits-card-for-new-merchants-no-deposits) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: e5dc9a909c2d83de32658442f940844100d705f5
- Build time: 2023-05-10 20:21:38 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by james-allan** [comment]
For new merchants this is how the page loads: 

https://user-images.githubusercontent.com/8490476/235834601-783d475d-891c-4e0e-875b-00bf017299c3.mov

You'll notice that the Deposits card shows while in the loading state and then disappears once we've determined this merchant doesn't have any deposits. 

I'm assuming that's ok @elizaan36? The alternative was to not show any loading state at all and the deposits card would just appear fully loaded.

Given this only impacts brand new users this seemed like it was the better approach than having the card just pop in fully loaded for existing users.

**Comment by haszari** [comment]
> You'll notice that the Deposits card shows while in the loading state and then disappears once we've determined this merchant doesn't have any deposits.

If it's easy / doable to hide it by default, that would be cleaner IMO :)

**Comment by james-allan** [comment]
> If it's easy / doable to hide it by default, that would be cleaner IMO :)

If we hide it by default then it will appear once loading the data is complete and it will appear fully loaded. Like this:

https://user-images.githubusercontent.com/8490476/235846001-df79c8d0-045d-4cbd-8685-121c72c985a7.mov

It's definitely doable.

**Comment by Jinksi** [comment]
> If it's easy / doable to hide it by default, that would be cleaner IMO :)


Is this PR awaiting this change to loading behaviour before review?

**Comment by elizaan36** [comment]
The loading state seems consistent with other areas like Woo home, transitions in Woo are generally a bit jarring. One other thing, I think this will be fixed as part of the Disputes project but the "Things to do" task will be prioritized above the Deposits card.

**Comment by Jinksi** [comment]
Thanks for your feedback @elizaan36 🙌 

I've marked this PR as ready for review, since the loading state as it is currently implemented is suitable (show the deposits card in it's loading state for new and established merchants).

**Review by Jinksi — APPROVED** [review]
LGTM @james-allan 🙌 

I've tested with an established account that has historical deposits and the deposits card displays as expected.

With a new account with no previous/expected deposits, the Deposits card briefly shows the Deposits card in it's loading state before disappearing. Although it may be a jarring loading experience for accounts with no deposits, this should no longer be a problem when the "Things to do" card is moved above the deposits in a future PR, as mentioned by @elizaan36.

image

**Note:** if we do want to create an optimal loading experience for _both_ new and existing merchants, we could add a variable to the [`wcpaySettings` global](https://github.com/Automattic/woocommerce-payments/blob/e5dc9a909c2d83de32658442f940844100d705f5/client/globals.d.ts#L26) to determine if the account has deposits before the initial render.

**Pull request merged**
