### PR TITLE
E2E: fix `merchant-orders-full-refund` missing order amount (#8319)

### LINKED ISSUE #8330: E2E test `merchant-orders-full-refund` failing due to incorrect order total (`$0.00`)
### Describe the bug

The `merchant-orders-full-refund` e2e test suite is failing due to an incorrect order total being extracted from the page. The test currently attempts to extract the order total `$18.00` from the WC order screen using the target element `.woocommerce-Price-amount`, which incorrectly return `$0.00`.

https://github.com/Automattic/woocommerce-payments/blob/25eb75f2c777c5f8e33917591d98ec72ed9d6984/tests/e2e/specs/wcpay/merchant/merchant-orders-full-refund.spec.js#L49-L54

This page has many elements matching `.woocommerce-Price-amount` and not all of them will return the order total.

One alternative is to extract the order total amount the shopper order received page prior to navigation to the merchant order details screen.

### To Reproduce

1. View the `E2E Tests - Pull Request / WC - latest | wcpay - merchant` GH check results for a PR [example](https://github.com/Automattic/woocommerce-payments/actions/runs/8164189583/job/22318982725?pr=7671)
2. Notice the `merchant-orders-full-refund` test fails due to an order total `$0.00`
```
# this should evaluate as $18.00 if the order total was correctly extracted from the page
(text: "A payment of $0.00 was successfully refunded.") not found
```

### PR DESCRIPTION
**Pull request by Jinksi**
Fixes #8330

#### Changes proposed in this Pull Request

> [!WARNING]  
> Don't press `Update branch` since we don't want `develop` commits pushed to `trunk`

This PR carries over changes introduced to `trunk` via PR #8319 to `develop`.

It fixes the `merchant-orders-full-refund` e2e test suite by changing the target element used to get the order amount.

#### Testing instructions

* Inspect the results of this PR's GH check `E2E Tests - Pull Request / WC - latest | wcpay - merchant (pull_request)`
* Ensure the test suite `merchant-orders-full-refund` passes (see [passing test](https://github.com/Automattic/woocommerce-payments/actions/runs/8182157985/job/22373071597?pr=8342#step:4:108)) ✅

-------------------

- [x] Run `npm run changelog` to add a changelog file, **changelog N/A, pulling over a single commit**
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile **N/A**

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8342` or branch name `trunk` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=trunk) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 3d6939d86f3616597aa1d9d13b20a6c187824338
- Build time: 2024-03-07 09:50:58 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by shendy-a8c — APPROVED** [review]
Looks good. I only looked at the diff and compared it with https://github.com/Automattic/woocommerce-payments/pull/8319/files. Confirmed that GH check `E2E Tests - Pull Request / WC - latest | wcpay - merchant` is green too.

This process (commit to `trunk` and this PR brings that commit to `develop`) feels weird though as it's not usual. Had that commit was made before the 7.3.0 release, it would have been included in the commit that merges trunk to develop https://github.com/Automattic/woocommerce-payments/commit/ca8c7c0d04400b6e4753e6baa919209e88752154.

**Comment by shendy-a8c** [comment]
> Don't press Update branch since we don't want develop commits pushed to trunk

It's like an instinct to click that button. Fortunately, I read the PR body first. Scary.

**Comment by Jinksi** [comment]
Another commit has been added to `trunk`, but already exists in `develop` so should be fine to merge.

**Comment by Jinksi** [comment]
> It's like an instinct to click that button. Fortunately, I read the PR body first. Scary.

@shendy-a8c totally! Although, I hope branch protection would protect us. Next time I might do a cherry-pick rather than `trunk` → `develop`.

**Pull request merged**
