### PR TITLE
Fix caching dispute issues after accepting a dispute

### LINKED ISSUE #4373: Disputes list and notification badge show cached state after accepting a dispute
### Describe the bug

With the addition of the changes introduced in https://github.com/Automattic/woocommerce-payments/pull/4326, when a store has disputes that need a response we display a notifications indicator and automatically direct them to the disputes list filtered by disputes that need a response. 

Screen Shot 2022-06-28 at 2 14 28 pm

After accepting a dispute however, the merchant is directed back to the disputes list table but the dispute they just accepted is still cached as its previous status. 

https://user-images.githubusercontent.com/8490476/176094468-34f79259-9551-4b41-ad39-cfb491bed3ad.mov

### To Reproduce

1. Purchase a product with a card that will result in a Dispute. eg (`4000000000000259`)
2. Go to **Payments → Disputes**
3. Make a mental note of the notifications badge number and the dispute order ID.
4. Click on the dispute and accept it.
5. You will be redirected to the Disputes list table and the dispute you just accepted (lost) will still show as needs response. 

### Actual behavior

After being redirected to the Disputes list table, the dispute you just accepted (lost) will still show as needs response and then notifications badge will still indicate 1 more than it should. Once you refresh the page, the dispute will go and the notification indicator will update too. 

### Expected behavior

Ideally, when you are redirected after submitting evidence or accepting a dispute, the list table should reflect that change and the notification indicator should too.

### PR DESCRIPTION
**Pull request by james-allan**
Fixes #4373 

#### Changes proposed in this Pull Request

After accepting a dispute, the user is redirected back to the disputes table. Currently, because of caching issues, the dispute the user just accepted will still appear in the list as needing a response. 
 

To resolve this issue this PR does 2 things:

1. Use a standard JS redirect after accepting the dispute. This replaces the existing `getHistory().push()` call. The `getHistory().push()` approach caused this issue because it just pushes the URL onto the stack with no page load.
2. Delete the status count cache after updating or accepting a dispute. This fixes the notifications badge in the side panel. Without this cache delete, it would wait for the webhook to be received and that will be too late. 

https://user-images.githubusercontent.com/8490476/179916571-af964cc0-e010-4457-8a3b-a3296207f90f.mov

**Note:** You'll notice this in the video and when testing - compared to the current behaviour, the interaction is a little different. After accepting the dispute the page fully reloads on the new Lost dispute screen before the redirect to the list table occurs. 

#### Testing instructions

* Purchase a product using a disputed payment method (eg `4000000000000259`)
* Go to **Payments → Disputes**
* Make a mental note of the notifications badge number and the dispute order ID.
* Click on the dispute and accept it.
     * On **`develop`** - You will be redirected to the Disputes list table and the dispute you just accepted (lost) will still show as needs response.
     * On this branch, the notifications badge, and list table should no longer include the dispute you just accepted.

I had some changes to WCPay Server that I thought were necessary to improve this flow, however they don't appear to be necessary. 

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by james-allan** [comment]
@Jinksi @mattallan I noticed that when you update a dispute by submitting evidence it would have similar caching issues. I've fixed that by using the same approach after submitting evidence with [c20a807](https://github.com/Automattic/woocommerce-payments/pull/4458/commits/c20a807e9f0e389e24ad4f2085b61e115741cec0)

to test that: 

1. Purchase a product using a disputed payment method (eg 4000000000000259)
1. Go to Payments → Disputes
1. Make a mental note of the notifications badge number and the dispute order ID.
1. Click on the dispute and click Challenge dispute.
1. In the Additional details enter the string `"winning_evidence"`. Submit.
    - On develop - You will be redirected to the full disputes list table and the dispute you just challenged (lost) will still show as needs response.
   - On this branch, you'll be redirected to the disputes needing a response, the notifications badge and list table should no longer include the dispute you just challenged.

**Comment by Jinksi** [comment]
I've been testing this on a JN site and it is working well. The outdated disputes list is fixed, which I found to be the most glaring part of this bug. I've hit 2 other minor issues worth discussing:

1. After accepting/challenging, the badge still keeps the cached value until I do a manual page refresh.
2. When accepting the final dispute awaiting a response, it will redirect to the `awaiting_response` filter. Should it change to the `all` filter? We could change the behaviour to use the `all`  filter in every case.

**Steps Tested**
* Built & uploaded to a JN site, setup WCPay in test mode.
* Created 3 disputed purchases.
* Observed the 3 disputes in the disputes list and menu badge.
* When accepting dispute 1
	* redirected to a correctly updated disputes list. ✅
	* badge remains at 3 until I do a manual page refresh.  ⚠️
* When challenging dispute 2
	* redirected to a correctly updated disputes list. ✅
	* badge remains at 2 until I do a manual page refresh. ⚠️ 
* When accepting dispute 3 (final dispute awaiting a response)
	* redirected to an empty disputes list with `awaiting_response` filter selected. ⚠️
	* badge remains at 1 until I do a manual page refresh. ⚠️

**Comment by james-allan** [comment]
> After accepting/challenging, the badge still keeps the cached value until I do a manual page refresh.

I wonder if this is because of those planned server changes I had but decided weren't necessary. 🤔

**Comment by Jinksi** [comment]
> After accepting/challenging, the badge still keeps the cached value until I do a manual page refresh.

I should have mentioned: when testing locally with a local WCPay-server instance running, the badge value updates correctly. The page takes a lot longer to load locally, so it could be a timing issue?

**Comment by james-allan** [comment]
>  so it could be a timing issue?

Yeah that's likely part of it for sure.

**Comment by james-allan** [comment]
I could submit the PR to server to update the dispute's db/repository immediately after closing the dispute. The thing is we won't be able to test it on the JN site anyway until its deployed.

The other idea I have is a somewhat hacky kinda idea. 🤠  

Would it be possible to update the notifications badge via JS from the dispute list table summary?

**Comment by james-allan** [comment]
> Would it be possible to update the notifications badge via JS from the dispute list table summary?

So I looked into this a little and it works but its a bit gross and really dependant on a couple of things. The page loads with the incorrect count and then once the list table is populated and the summary at the bottom (`x disputes`) is rendered, the badge updates. They way I've done it though, you'd have to be on the awaiting response page to get an accurate figure and all a bit flaky.

**Comment by james-allan** [comment]
For the record these are the changes I planned to make to server if you want to take a look. We could still look at doing this if you think it might resolve the lag issues on fast stores like JN sites. https://github.com/Automattic/woocommerce-payments-server/compare/update_dispute_record_after_update

**Comment by Jinksi** [comment]
> We could still look at doing this if you think it might resolve the lag issues on fast stores like JN sites

🚀 This sounds like the best path forward. Fixing the small delay at the source of truth (WCPay-server) would be more robust than any other JS-hacky way I can think of.

**Comment by Jinksi** [comment]
> so it could be a timing issue?

After more tests, the disputes count is _sometimes_ correctly updated without throttling. In these cases, I guess the server must be updated to the correct value just in time.

> 2. When accepting the final dispute awaiting a response, it will redirect to the awaiting_response filter. Should it change to the `all` filter? We could change the behaviour to use the `all` filter in every case.

What do you think about redirecting to the `all` filter rather than `awaiting_response` to fix 2?

**Comment by james-allan** [comment]
> After more tests, the disputes count is sometimes correctly updated without throttling. In these cases, I guess the server must be updated to the correct value just in time. 

Yeah I think it must be a really close timing thing. Basically between the admin menu being rendered and the list table being populated. Either that or the status cache is being repopulated much earlier then the menu navigation generation. 🤷 

> What do you think about redirecting to the all filter rather than awaiting_response to fix 2?

Oh I forgot about that. I don't know what options we have to do that honestly. The redirect occurs in JS after accepting/challenging the dispute so to have a conditional redirect we'd need to know that this item was the only dispute left. Now that we're injecting count that into the JS, we might be able to do something like that. 🤷‍♂️ 

Having said that, I don't personally don't have an issue with the current behaviour. Putting the merchant back on the disputes screen which is now empty explicitly tells them there's nothing left to do here. Landing on the full list of disputes wouldn't necessarily have that same communicative value. I think this is something we'd need to run by a designer to know what the intended interaction should be.

**Comment by james-allan** [comment]
> This sounds like the best path forward. Fixing the small delay at the source of truth (WCPay-server) would be more robust than any other JS-hacky way I can think of.

PR submitted here: 2244-gh-Automattic/woocommerce-payments-server

**Review by Jinksi — APPROVED** [review]
🏆  LGTM @james-allan! To summarise my thoughts (non-blocking):

* I had it set in my mind that the current behaviour of redirecting to an empty list of disputes was **bad**. I now [agree with you](https://github.com/Automattic/woocommerce-payments/pull/4458#issuecomment-1191077390) that this behaviour is **good**, as the user will see that by closing their last dispute they have reached "inbox-zero". 
* On fast-loading sites, such as JN, the badge count remains outdated when accepting/challenging a dispute. We've determined that the client is correctly displaying the count it has received from the server and that the server has not updated the dispute status in time for the client request. This can be resolved server-side (2244-gh-Automattic/woocommerce-payments-server)

**Steps Tested**
* Built & uploaded to a JN site, setup WCPay in test mode.
* Created 3 disputed purchases.
* Observed the 3 disputes in the disputes list and menu badge.
* When accepting dispute 1
	* redirected to a correctly updated disputes list. ✅
	* badge remains at 3 until I do a manual page refresh.  ⚠️
* When challenging dispute 2
	* redirected to a correctly updated disputes list. ✅
	* badge remains at 2 until I do a manual page refresh. ⚠️ 
* When accepting dispute 3 (final dispute awaiting a response)
	* redirected to an empty disputes list with `awaiting_response` filter selected. ✅
	* badge remains at 1 until I do a manual page refresh. ⚠️

**Pull request merged**
