### PR TITLE
Fix Bug: Prevent Multi-Currency Conversion During REST API Request

### LINKED ISSUE #9181: Possible bug with Store API requests and MultiCurrency
### Describe the bug

Relates to this slack thread: p1722254839910269-slack-C7U3Y3VMY

In short: when Multi Currency is enabled in WooPayments, requests made to the Store API, e.g. `https://<store-url>/wp-json/wc/v2/products/<product_id>` return the amount based on the _customer session_, rather than returning in base store currency.

### To Reproduce

1. Enable Multi Currency in WooPayments, and add at least one extra currency. In my case, GBP was my store default currency and I added EUR as an extra currency.
2. Create a product and make a note of the price in your default currency.
3. Edit the site using the Blocks Editor to add a "Currency Switcher" block somewhere on the page.
4. Go to the store as if you are a customer and use the currency switcher block to change the display currency to EUR.
5. Make an API request to ``https://<store-url>/wp-json/wc/v2/products/<product_id>`
6. The price of the product will display in EUR.

### Expected behaviour

I believe the product price should display in the store default currency when using the REST API. Display currencies should only be for frontend requests.

### Screenshots

In this case, the product should be £10 in my store, but it's displaying as 12 EUR

Screenshot 2024-07-29 at 16 34 41

### Additional context

We use this logic to disable conversions on Admin API requests: https://github.com/Automattic/woocommerce-payments/blob/2101d7620b84699e0dd816f4a886be42e5261d91/includes/multi-currency/Utils.php#L59

We should consider adding similar logic for Store API requests.

### PR DESCRIPTION
**Pull request by lovo-h**
Fixes #9181 

#### Changes proposed in this Pull Request

The changes in this PR ensure that the REST API requests are idempotent. This is accomplished by preventing multi-currency from converting the currency and price based on the user's session. Previously, if a shopper updated their frontend currency with a currency-switcher block, the REST API requests from the frontend would also be unintentionally impacted.

#### Testing instructions

**Replicate bug: Updating the frontend currency impacts the REST API requests**
* Switch to the `develop` branch.
* As a merchant, enable multi-currency in WooPayments and add at least one extra currency (e.g. `GBP` (default) + `EUR`).
* Create a new product and note the price in the default currency (e.g. `GBP`) and the ID.
* Add a "Currency Switcher" block widget ( **Appearance > Widgets**).
* As a shopper, navigate to the merchant shop and use the "Currency Switcher" to switch to the non-default currency (`EUR`).
* Make a REST API request to `https://merchant.com/wp-json/wc/v2/products/<product_id>?consumer_key=<key>&consumer_secret=<secret>` in the browser's search bar.
* Confirm that the price has changed and that the currency code reads `&euro;`.

**Confirm fix: Updating the frontend currency does not impact the REST API requests**
* Switch to the `fix/9181-unintended-mccy-conversion-during-rest-api-request` branch.
* As a merchant, enable multi-currency in WooPayments and add at least one extra currency (e.g. `GBP` (default) + `EUR`).
* Create a new product and note the price in the default currency (e.g. `GBP`) and the ID.
* Add a "Currency Switcher" block widget ( **Appearance > Widgets**).
* As a shopper, navigate to the merchant shop and use the "Currency Switcher" to switch to the non-default currency (`EUR`).
* Make a REST API request to `https://merchant.com/wp-json/wc/v2/products/<product_id>?consumer_key=<key>&consumer_secret=<secret>` in the browser's search bar.
* Confirm that the price has _not_ changed and that the currency code reads `&pound;` (default).
* Confirm that the correct price and currency appear in the `price_html` field.

**Ensure compatibility: Updating the frontend currency does not impact the REST API requests for compatible plugins**
* Switch to the `fix/9181-unintended-mccy-conversion-during-rest-api-request` branch.
* As a merchant, enable multi-currency in WooPayments and add at least one extra currency (e.g. `GBP` (default) + `EUR`).
* Using a [compatible plugin from this list](https://github.com/Automattic/woocommerce-payments/blob/4c417bca2ee072ddb342bcd9e0d85c0055ed3dd0/includes/multi-currency/Compatibility.php#L59-L67):
  * Create a new product (booking, subscription, etc.) and note the price in the default currency (e.g. `GBP`) and the ID.
* Add a "Currency Switcher" block widget ( **Appearance > Widgets**).
* As a shopper, navigate to the merchant shop and use the "Currency Switcher" to switch to the non-default currency (`EUR`).
* Make a REST API request to `https://merchant.com/wp-json/wc/v2/products/<product_id>?consumer_key=<key>&consumer_secret=<secret>` in the browser's search bar.
* Confirm that the price has _not_ changed and that the currency code reads `&pound;` (default).
* Confirm that the correct price and currency appear in the `price_html` field.

**Ensure unit tests all pass**
* Run the following command `npm run test:php`.
* Ensure all tests pass.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9477` or branch name `fix/9181-unintended-mccy-conversion-during-rest-api-request` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/9181-unintended-mccy-conversion-during-rest-api-request) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: ff76ccfa237215d8a102f8efb811edb105a24541
- Build time: 2024-09-26 17:10:47 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by bborman22 — COMMENTED** [review]
This tested well for the issue being described! As we've discussed, it's a bit challenging to determine what the correct approach is here for the REST API, but I feel this approach is the best balance as it still allows currency conversion if desired, but makes it explicit now. 

Also as we discussed this could cause breaking changes if there are uses of the REST API that are depending on the currency conversion today, but at least this approach provides an easy update path to get back to the functionality with the currency parameter.

It was already highlighted in the Slack thread by @frosso that this still has a side effect of changing the "shopper's" currency in their meta. The concern raised there was that if we're changing it on a request, we should also honor it on a request. This presents a challenge just given how the functionality is designed today. One possible alternative is to make use of the `override_selected_currency` filter when the currency parameter is provided as well so that it doesn't pull from the user meta (and thus doesn't have to set it during a REST API request).

Let me know what you think of an approach like that, and @frosso feel free to weigh in here as well!

**Comment by lovo-h** [comment]
> It was already highlighted in the Slack thread by @frosso that this still has a side effect of changing the "shopper's" currency in their meta. The concern raised there was that if we're changing it on a request, we should also honor it on a request. This presents a challenge just given how the functionality is designed today. One possible alternative is to make use of the `override_selected_currency` filter when the currency parameter is provided as well so that it doesn't pull from the user meta (and thus doesn't have to set it during a REST API request).
> 
> Let me know what you think of an approach like that, and @frosso feel free to weigh in here as well!

Good call. Fixed in [398610c](https://github.com/Automattic/woocommerce-payments/pull/9477/commits/398610cbbe7f093242e8effd8008781d78a9273d).

**Review by bborman22 — COMMENTED** [review]
Thanks for making those changes @lovo-h! This tests well for me now with no side effects. I confirmed that I can pass in the currency parameter and get the correct price from the REST API and it doesn't update the authenticated user's currency meta. I also confirmed that no currency parameter always returns in the default currency as expected.

I wanted to do some quick regression testing with the Store API side of it and found one issue that is pre-existing, but causes a breaking issue with this PR. In short `/batch` requests on the Store API will return `false` on `\WC_Payments_Utils::is_store_api_request()`. This is because the `batch` path isn't included in `STORE_API_ROUTE_PATTERNS` that are compared. This can be observed in the following test:
- Add an item to the cart
- Visit the cart block
- Change currency to non-default currency (I had default of GBP and selected JPY)
- Note that the cart prices are in JPY
- Now update the quantity on an item and this should trigger a `batch` request
- Note that the prices now go back to GBP

I'm unsure the best approach here (add batch to the list or handle this check separately?) my only concern with adding batch to the list is if that has implications outside of this flow that would trigger a WooPay flow. I don't believe that would be a problem as all of our WooPay checks are combined with a `is_request_from_woopay` check. I also see the `is_store_api_request` is used in multiple places and surprised this hasn't come up in other areas so wanted to get a double check on my thoughts here?

**Comment by frosso** [comment]
@bborman22 that `/batch` endpoint is a great callout!
I believe the original `is_store_api_request()` utility was initially added for WooPay's specific case.
But I also believe that WooPay calls aren't coming in batches on the merchant's site.

I don't know if there's an easy fix to that detection mechanism 😬 it could be an enhancement 🤷

**Comment by lovo-h** [comment]
> I wanted to do some quick regression testing with the Store API side of it and found one issue that is pre-existing, but causes a breaking issue with this PR. In short /batch requests on the Store API will return false on \WC_Payments_Utils::is_store_api_request(). This is because the batch path isn't included in STORE_API_ROUTE_PATTERNS that are compared. This can be observed in the following test:
> 
> * Add an item to the cart
> * Visit the cart block
> * Change currency to non-default currency (I had default of GBP and selected JPY)
> * Note that the cart prices are in JPY
> * Now update the quantity on an item and this should trigger a batch request
> * Note that the prices now go back to GBP

Good catch. I was able to reproduce the issue.

> I'm unsure the best approach here (add batch to the list or handle this check separately?) my only concern with adding batch to the list is if that has implications outside of this flow that would trigger a WooPay flow.

Agreed. I don't think we should add the `/batch` request to the list of `STORE_API_ROUTE_PATTERNS` because it could cause unintended side effects. 

In order to keep things narrow, we could make an exception for when we apply the patch. That is, when it's not a `/batch` request. In other words, we could do something like the following [here](https://github.com/Automattic/woocommerce-payments/pull/9477/files#diff-c722c76bb4254c6fe1a32099d4ea5fa641addb44c5cd685a164e8baaff879e1aR255-R272):

```php
if ( ! \WC_Payments_Utils::is_store_batch_request() && ! \WC_Payments_Utils::is_store_api_request() && WC()->is_rest_api_request() ) {
  // Apply patch.
}
```

This would maintain the same functionality as before and apply the patch on the REST API requests, as needed.

What are your thoughts on this @bborman22 @frosso?

**Review by bborman22 — APPROVED** [review]
I was able to test this again with the above scenarios and confirmed that Store API (batch really) requests now keep the correct currency and the logic is being applied correctly there. I also finished the last test case by testing the REST API with a subscription product and a bookings product and all the pricing behaved as expected by returning in default currency unless the currency parameter was provided.

Thanks for all your effort on getting this here @lovo-h!

LGTM!

**Pull request merged**
