### PR TITLE
Add action when payment has "requires_action" status

### PR DESCRIPTION
**Pull request by millerf**
Related to TumblrPay's https://github.com/Automattic/multiwoo/issues/566

#### Changes proposed in this Pull Request

Adds an action when payment requires action. It will eventually allow us to trigger some warning when it happens on an off-session payment (renewal).

### CODE REVIEW

**Review by DanReyLop — APPROVED** [review]
Looks good as a stopgap measure. However, https://github.com/Automattic/woocommerce-payments/issues/2113 and https://github.com/Automattic/woocommerce-payments/issues/2114 should make this solution obsolete.

Do the TumblrPay customers have valid email addresses? Or is it still a bogus email address like `afadsadfasfsdfasd@invalid.email`?

**Comment by millerf** [comment]
> Do the TumblrPay customers have valid email addresses? Or is it still a bogus email address like afadsadfasfsdfasd@invalid.email?

Still bogus :)  If you are talking about notifying the user for re-auth, we would need to work with webhooks and notify Tumblr for them to notify the user...

**Comment by millerf** [comment]
Are you fine with me adding that specific change directly to WPCOM?

**Comment by DanReyLop** [comment]
> If you are talking about notifying the user for re-auth

Yes, I'm talking about that :)

> we would need to work with webhooks and notify Tumblr for them to notify the user...

Ok, so when I implement https://github.com/Automattic/woocommerce-payments/issues/2113, I'll add a filter so TumblrPay has a chance to notify Tumblr instead of letting Woo send an email to an invalid address.

> Are you fine with me adding that specific change directly to WPCOM?

It will be simpler to make this change in the WCPay plugin. We are already doing it (sending an email to the customer on `requires_action`) in the Stripe plugin, so I'll just have to copy the logic. I can add a filter so TumblrPay can override sending that email. Does it sound good?

**Comment by millerf** [comment]
> Ok, so when I implement #2113, I'll add a filter so TumblrPay has a chance to notify Tumblr instead of letting Woo send an email to an invalid address.

Perfect 👍 

> It will be simpler to make this change in the WCPay plugin. We are already doing it (sending an email to the customer on requires_action) in the Stripe plugin, so I'll just have to copy the logic. I can add a filter so TumblrPay can override sending that email. Does it sound good?

Sorry, there is a misunderstanding here. I was talking about modifying this PR. I meant making the changes of this PR on WPCOM, so I can move forward with https://github.com/Automattic/multiwoo/issues/566 and add the callback for us to use `woocommerce_woocommerce_payments_payment_requires_action`

**Comment by DanReyLop** [comment]
I'm fine merging this PR, if the filter is going to be used just for logging. But if you want to implement the "notify the user for re-auth" mechanism, please wait until #2113 is done (it should be ready for review later this week or early next week).

**Comment by millerf** [comment]
> I'm fine merging this PR, if the filter is going to be used just for logging. 
Yes, that is its only purpose. So we can also have an idea of how often this is used

> "notify the user for re-auth" 
No, that is not in the scope of this task :)

**Comment by jrodger** [comment]
Was this merged to `trunk` on purpose? If not can we revert this and commit to `develop` instead? Just checking so that it doesn't get missed out of the 2.6.0 release.

**Comment by millerf** [comment]
Oh. I messed up!

**Comment by jrodger** [comment]
No worries, easily done!

**Pull request merged**
