### PR TITLE
Update readme.txt

### PR DESCRIPTION
**Pull request by tckasa**
P2 post: https://wcpay.wordpress.com/2022/09/30/wp-org-repo-seo-improve-wcpays-plugin-search-ranking/

In line with the work done by @Timstreep, Update wp.org repo listing content for WooCommerce (https://woomarketplace.wordpress.com/2022/09/05/project-proposal-update-wp-org-repo/), we're also introducing a few changes to update the title and tags (WooCommerce Payments Plugin: https://wordpress.org/plugins/woocommerce-payments/) aiming to improve WooCommerce Payments' ranking on the Wordpress.Org Repo search plugins engine.

Fixes #

#### Changes proposed in this Pull Request

**Update WooCommerce Payments listing content**

As of now, the WooCommerce Payments plugin is not well ranked for payment-related keywords on the WordPress.org repo, and the title and tags are two important ranking factors that we can improve. We'll monitor the impact of these changes by using Pugin Rank (https://app.pluginrank.com/).

#### Testing instructions

- Check that the plugin title was changed correctly.
- Check that the plugin tags were changed correctly.

Alt text

*

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by vbelolapotkov** [comment]
@Automattic/gamma could you please review the change? See paJDYF-5Rk-p2 for more context.

**Comment by zmaglica** [comment]
I looked at the changes and everything seems fine. I double-check `woorelease` and our internal codebase, and this change should not break anything. 

Could you please create a changelog entry? I do know that change is minimal, but we have our CI/CD that will prevent us from merging it.

**Comment by Timstreep** [comment]
Thanks @zmaglica - I'm not sure who this request is directed to? Can you confirm? We've love to publish these changes asap.

_Could you please create a changelog entry? I do know that change is minimal, but we have our CI/CD that will prevent us from merging it._

**Review by deepakpathania — APPROVED** [review]
LGTM

**Comment by deepakpathania** [comment]
@Timstreep I have added the changelog and approved the PR. I will merge when the CI checks are complete.

> We've love to publish these changes asap.

This would be released as part of WCPay 4.9.0, scheduled for Oct 19th, 2022. paJDYF-5T0-p2

**Comment by Timstreep** [comment]
@deepakpathania - could we push this sooner than the next WCPay release? We were able to do this independently with recent updates to the Woo Core plugin page on .org.

**Comment by zmaglica** [comment]
> @deepakpathania - could we push this sooner than the next WCPay release? We were able to do this independently with recent updates to the Woo Core plugin page on .org.

We can do it. It will require us that we manually change affected files both on wp.org and woocommerce.com. WooCommerce Payments plugin is scheduled to release in 5 days. If it's urgent, I can update this read me file directly on SVN(s) of both websites and if not, could we wait 5 days when we have a scheduled release?

The reason why we avoid situation like this (where we have to manually update something on SVN) is that we have to step out of our defined processed. Usually, we do that when it is an emergency, and if you think that this change needs to be published ASAP, please let me know, and I will make necessary changes.

**Comment by tckasa** [comment]
Hi @deepakpathania and @zmaglica - Can you please confirm if it'll be released today?

**Comment by deepakpathania** [comment]
Hi @tckasa, this was released yesterday and I can see the updated title and tags on the plugin page:

Screenshot 2022-10-21 at 4 14 50 PM

**Pull request merged**
