### PR TITLE
Added Jurassic Tube setup script

### LINKED ISSUE #1181: Add Setup Script for Jurassic Tube
As discussed on p1608695276129400-slack-CGGCLBN58, it would be useful to have a setup script to install/run Jurassic Tube for a local instance of WC Payments, this may improve the setup process as it is necessary to have a domain to make the initial connection to JetPack. 

There is a similar script for setting up WC Payments Server that could be used as a starting point, and there is already a guide with a set of manual steps for installing and using Jurassic Tube.

### PR DESCRIPTION
**Pull request by dmallory42**
Fixes #1181 

#### Changes proposed in this Pull Request

* Adds shell script to handle Jurassic Tube setup
* Documentation of script and add method of running through `npm run` to `package.json`.

#### Testing instructions

* `git checkout -b update/1181-jt-setup`
* Run the command `npm run setup:jurassic-tube`
* Follow the steps in the script. Verify that it correctly sets up Jurassic Tube.

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

Note: currently in draft form awaiting discussion and documentation.

### CODE REVIEW

**Review by dwainm — COMMENTED** [review]
It works for me with an existing key not being overwritten. One minor comment, the instructions should say: 

```
Use the command: docker/bin/jt/tunnel.sh <usernam> <subdomain> ....
```

**Comment by dmallory42** [comment]
Thanks a lot for testing @dwainm.

During the setup, it should set `username` and `subdomain` in the Jurassic Tube config (it should take your user input for this). This means that you can then just run `docker/bin/jt/tunnel.sh` without needing to specify username and subdomain every time.

Did it not do this for you?

**Comment by dwainm** [comment]
I don't think it updated my config as I selected no to one of the options. I'll test again to see if this is a cause for concern.

**Comment by dwainm** [comment]
@dmallory42 the first part works like a charm.

Now for the part where you can run it and it updates the site address to match the jTube address.

**Comment by dmallory42** [comment]
Hey @dwainm , thanks for testing this again and for the feedback. Just to confirm, when you say:

> Now for the part where you can run it and it updates the site address to match the jTube address.

Do you mean that the script should run these two commands?

```
# npm run wp option update home https://${subdomain}.jurassic.tube/
# npm run wp option update siteurl https://${subdomain}.jurassic.tube/
```

I noticed some issues when I tried to run these as part of the script which I need to dig into further. However, in my case I noticed they weren't actually necessary for jTube to work for me. Can I just confirm that these are needed?

**Comment by dwainm** [comment]
I had specific issues around this so I think have two options:
- `npm run setup:jurassic-tube`
- `npm run start:jurassic-tube` 
- `npm run stop:jurassic-tube` 

Where start would run jtube and set the hosts up and stop would restore the hosts and break the tunnel.

**Comment by dmallory42** [comment]
Ah, good thinking! I think that sounds like a good solution. Let me work on adding that and then I may ask you to re-test if that's okay. Thanks again.

**Comment by dwainm** [comment]
Thank you, these are extra bits though so maybe we should rather open another issue for them? I don't want to distract from the work on fraud. Also with this code-approved we can ship it and close the issue, which doesn't scope out the two suggested commands.

**Review by dwainm — APPROVED** [review]

**Comment by dmallory42** [comment]
Thanks Dwain, that sounds like a good idea. I'll close this issue and make new ones for the additional updates you mentioned.

**Pull request merged**
