### PR TITLE
Fix WooPay express checkout behavior with product bundles on product page

### LINKED ISSUE #6634: WooPay button is disabled when conditions for variable product have not been met
### Describe the bug
The WooPay button is in a disabled state if the shopper has not met the requirements for the variable product attributes such as color and logo. The Add to Cart and Google Pay buttons however are always and correctly in an enabled state.

### To Reproduce
1. Enabled WooPay and Apple Pay/GPay on the product page
2. Shop on test site and pick a variable type product
3. Note that WooPay will be disabled while the Google Pay and the Add to cart buttons are enabled. On Blocks the button will look enabled but is not functionally enabled.

### Actual behavior
The WooPay button is in a disabled state until the variable product options are selected.

### Screenshots

https://github.com/Automattic/woocommerce-payments/assets/109928953/818f50b4-8631-4f89-9f37-0819c3b442b7

### Expected behavior
PRBsm including WooPay, should be enabled, and a warning message presented until the required options for the product are selected

### Desktop (please complete the following information):
* Device: MacBook Pro
* Browser: Chrome
 
Note: Above Updated July 5th based on Elizabeth correctly pointing out that enabled, not disabled, is the correct button state.

### LINKED ISSUE #7157: WooPay empty cart page when adding a bundle with express checkout button on product page
### Describe the bug

When we click the WooPay express checkout button on product page, we are redirected to WooPay with a "Your cart is currently empty!" message.

### To Reproduce

1. Install Product Bundles
2. Create a bundle
3. Access bundle page
4. Click WooPay checkout page
5. You'll be redirected but the cart will be empty

### Screenshots

Screenshot 2023-09-07 at 11 40 15 PM

### PR DESCRIPTION
**Pull request by alefesouza**
Fixes #7157
Fixes #6634

#### Changes proposed in this Pull Request

* Remove the WooPay express checkout button disabled state and show an alert when it's clicked with the `Add to cart` button disabled.
* Update the WooPay `add_to_cart` hook to support product bundles, this way the bundle will be added to the cart with the expected configuration before the redirect.

#### Testing instructions

* Create a variable product.
* Access the product page.
* Click WooPay button without select any options.
* An alert should be shown.
* Fill out the variable product options.
* Click `Clear` button or reset an option.
* Click WooPay button.
* An alert should be shown.
* Fill out the variable product options.
* Click the WooPay button, you should be redirected as expected.
* Create a bundle with and without variable products.
* Access the bundle without the variable products.
* Click the WooPay button, you should be redirected as expected and no empty cart error message should be shown.
* Access the bundle with the variable products.
* Click WooPay button without select any options.
* An alert should be shown.
* Fill out the variable product options.
* Click `Clear` button or reset an option on any variable product.
* Click WooPay button.
* An alert should be shown.
* Fill out the variable product options.
* The WooPay button should be enabled.
* Click the WooPay button, you should be redirected as expected and no empty cart error message should be shown.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7158` or branch name `fix/fix-bundles-on-product-woopay-express-checkout-button` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/fix-bundles-on-product-woopay-express-checkout-button) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 4acfb4e4b3e8f7b981222e7f2c655994ed681219
- Build time: 2023-09-22 20:14:59 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by alefesouza** [comment]
The original version of this PR would update the WooPay express checkout button disabled state for bundles with variable products, but then I noticed that https://github.com/Automattic/woocommerce-payments/issues/6634 requires the disabled state to be removed, so I took the opportunity to fix it on this PR.

**Review by hsingyuc — COMMENTED** [review]
@alefesouza Thank you for working on this!  I can't reproduce this issue.  I got redirected to the WooPay checkout page with the correct cart items.   Do I need any other settings besides activating the product bundle plugin?

Screen Shot 2023-09-11 at 6 43 59 PM

**My product bundle**
Screen Shot 2023-09-11 at 6 45 24 PM

**Comment by alefesouza** [comment]
@malithsen for some reason Emma is getting a 302 redirection on `?wc-ajax=wcpay_add_to_cart` when clicking the WooPay button on this PR, I couldn't reproduce it, could you review this PR as well?

**Review by malithsen — DISMISSED** [review]
@alefesouza Thanks for working on this Alefe. I was not able to reproduce the redirection issue @hsingyuc mentioned. However, I wonder how it would behave when the WooPay user is logged in, and we automatically redirect to WooPay without showing the OTP screen. I think it should still behave the same. I just haven't been able to get automatic redirection working on my local machine to test it.

Variable Product

https://github.com/Automattic/woocommerce-payments/assets/6216000/fd41b60f-303d-46a2-9af3-87085f2fc409


Product Bundle with variable product

https://github.com/Automattic/woocommerce-payments/assets/6216000/fe7ed529-be67-4e58-befa-eae647645707

Product bundle without variable product

https://github.com/Automattic/woocommerce-payments/assets/6216000/89ee215f-e5ef-4bfd-a093-28e5606ec689

**Comment by alefesouza** [comment]
> I wonder how it would behave when the WooPay user is logged in, and we automatically redirect to WooPay without showing the OTP screen.

It does not apply to the product page, on checkout page the products already are added to the cart, also if the user clicks the WooPay button while logged in they are redirected as expected as this PR fixes runs before the redirection.

**Review by hsingyuc — COMMENTED** [review]
I found that product bundles adds `add-to-cart` to the form data when adding to cart.  You can see this in the payload to the `wc-ajax=wcpay_add_to_cart` endpoint.

If the `woocommerce_cart_redirect_after_add` option is checked under WooCommerce -> Settings -> Products -> Add to cart behaviour, the endpoint gets a 302 redirect because of [this code](https://github.com/woocommerce/woocommerce/blob/be6982432ebe901d5dcc7aefe343ec05d0e09964/plugins/woocommerce/includes/class-wc-form-handler.php#L816-L819).

If we uncheck that setting it works, but I don't think we can ask merchants to uncheck this.  When we handle the form submit for the WooPay express button, do you think we should remove the `add-to-cart` param?

**Comment by malithsen** [comment]
> If the woocommerce_cart_redirect_after_add option is checked under WooCommerce -> Settings -> Products -> Add to cart behaviour, the endpoint gets a 302 redirect because of [this code](https://github.com/woocommerce/woocommerce/blob/be6982432ebe901d5dcc7aefe343ec05d0e09964/plugins/woocommerce/includes/class-wc-form-handler.php#L816-L819).

@hsingyuc Ah good catch! I forgot about these settings. Can confirm that the express button doesn't work when "Redirect to the cart page after successful addition" is enabled.

**Comment by alefesouza** [comment]
Great catch @hsingyuc, fixed on https://github.com/Automattic/woocommerce-payments/pull/7158/commits/4acfb4e4b3e8f7b981222e7f2c655994ed681219.

**Review by hsingyuc — APPROVED** [review]
LGTM 👍

**Pull request merged**
