### PR TITLE
Fix error log messages incorrecty categorized as info

### LINKED ISSUE #9889: Error Level in Logger is ignored
### Describe the bug
 

When using the internal methods to log WooPayments errors to the log such as `Logger::log_error()` the priority of these messages are ignored.

https://github.com/Automattic/woocommerce-payments/blob/eaa5abbb2243d432d42fadeb2e9e8d60696b9996/includes/class-logger.php#L83-L85

https://github.com/Automattic/woocommerce-payments/blob/eaa5abbb2243d432d42fadeb2e9e8d60696b9996/includes/class-logger.php#L38-L40

In this snippet, `$level` is ignored.

### PR DESCRIPTION
**Pull request by brucealdridge**
Fixes #9889 

#### Changes proposed in this Pull Request

Calls to `Logger::log_error()` were being incorrectly labelled as `info`

This PR passes the log level categorization onto the WooCommerce logger.

#### Testing instructions

* In WooPayments Dev Tools, select `Force the WCPay plugin to act as disconnected from the WCPay Server` and save settings.
* Visit the WooPayments dashboard
* View the logs, ensure you see `error` level logs.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9890` or branch name `fix/9889-log-level` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/9889-log-level) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: e6b7189e320cdd3f6e6aaf3f23396e9b0afabe19
- Build time: 2024-12-08 16:33:20 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by nagpai** [comment]
When I did a manual test with the steps shared by you, I checked `WooCommerce > Status > Logs` and I seem to see only `Info` level logs 🤔 

I tried this on my local setup, as well as Pressable test site ( with JP beta + WooPayments checked into this branch ) . 

image

**Review by shendy-a8c — APPROVED** [review]
Same with @nagpai, I have a hard time confirming the change following the testing instruction.

However, I run this on WP Console both on base branch and PR branch and I can confirm the expected result.

```php
\WCPay\Logger::log( 'something', 'error' );
```
Screenshot 2024-12-08 at 23 57 14

**Comment by shendy-a8c** [comment]
> I have a hard time confirming the change following the testing instruction.

Might be because my local wcpay server setup is broken (context p1733466302429219/1733402031.658199-slack-CGGCLBN58).

**Pull request merged**
