### PR TITLE
Bump minimum WC version to 7.0 for the upcoming WCPay 5.2 release

### PR DESCRIPTION
**Pull request by mattallan**
#### Changes proposed in this Pull Request

This PR updates the minimum version of WC to 7.0.0 following our L-2 policy.
WooCommerce 7.2 is scheduled to be released on December 13th which falls within the upcoming WC Pay 5.2 release cycle therefore it needs to be updated.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Review by Jinksi — APPROVED** [review]
Thanks, @mattallan! Changes look good and GitHub checks passing ✅

**Review by Jinksi — CHANGES_REQUESTED** [review]
Oh, hold that thought, should it be WC 7.0.1?

To clarify, I think that the GH workflows should use WC 7.0.1, looking at a previous version bump PR for inspiration:

https://github.com/Automattic/woocommerce-payments/pull/5144/files#diff-0ff6bcc45c7c09bfcb5419c83559f190add597ec3b82ad238ddb1d6e43e9517eL7

**Comment by mattallan** [comment]
Thanks @Jinksi and good catch!! Fixed in [0e7a38d](https://github.com/Automattic/woocommerce-payments/pull/5245/commits/0e7a38d0f5216805b699150eafbbca05d484a1cd)

I'll wait for the checks to pass before merging

**Review by Jinksi — APPROVED** [review]

**Comment by jbordonado** [comment]
I'm curious: did you use the [wcpay:bump-versions](https://github.com/woocommerce/woorelease-extensions/blob/trunk/class-woocommerce-payments-bump-versions.php) woorelease extension command mentioned in the [release doc](https://wcpay.wordpress.com/dev-resources/release-train-model/)?

image

Doesn't look like it, given the commit messages I'm seeing

**Pull request merged**
