### PR TITLE
[Experiment] What would it look like to use framework agnostic web components?

### PR DESCRIPTION
**Pull request by reykjalin**
## Changes proposed in this Pull Request

- Replace some of the `@wordpress/components` we use with custom-made Web Components.
    - So far the replaced elements are:
        - The `<Card>` components in the payment method list in the settings `client/payment-methods/index.js`.
        - The `<Button>` component in the WooPayments settings for the `Save changes` button `client/settings/save-settings-section/index.js`.

### Screenshots and recordings

>[!NOTE]
> I'll add these when the experiment is over, but for now things look and work the same.

## Testing instructions

> [!NOTE]
> This is an experiment so testing and reviewing is not required.

### CODE REVIEW

**Comment by tyxla** [comment]
Sorry for the naive question, but what's the motivation for replacing `@wordpress/components` with another library in the wp-admin?

**Comment by reykjalin** [comment]
Let me preface this by saying that this is just a HACK week experiment, I wanted to see if this was possible.

The biggest reason I want to explore this is to try to reduce our dependency on React in a way that would allow us to move to a different framework when that time comes, whether that's a year from now or 15 years from now. Since Web Components are a web standard they'll likely be supported for longer than any particular framework so it grants us some flexibility with choosing 1 (or many!) frameworks to use depending on what's right for any given application.

There's also an argument to be made that we could reduce bundle sizes, but I won't be exploring that since I won't be developing the HACK week components to have feature parity with `@wordpress/components`.

The shadow DOM approach I've been using for the components also makes the styles more isolated than the React components from `@wordpress/components`, which is either a drawback or benefit depending on your point of view. It can be harder to customize the components because only the component itself can style the shadow DOM. There's better encapsulation at the cost of increased complexity if you want to expose an API to style the shadow DOM in the web component. That said I think we'd want to lean into the uniformity of components for WP so things in wp-admin use the same design language. In that case better encapsulation can be seen as a good thing.

And lastly I don't think this would be a WooPayments package, I'm just using WooPayments to demonstrate the principle. If we were to adopt this at some point I think the components in `@wordpress/components` should be replaced with Web Components.

**Comment by tyxla** [comment]
Thanks for elaborating!

> this is just a HACK week experiment, I wanted to see if this was possible.

> I'm just using WooPayments to demonstrate the principle

This is good to know, thanks!

> try to reduce our dependency on React in a way that would allow us to move to a different framework when that time comes, whether that's a year from now or 15 years from now

Sounds quite distant from us, but makes sense. FWIW, I'd be surprised if such an effort in the future starts from the inside out, but I guess we can also learn from this if we view it as an experiment.

> I won't be developing the HACK week components to have feature parity with @wordpress/components.

> If we were to adopt this at some point I think the components in @wordpress/components should be replaced with Web Components.

I'm curious what's the context/rationale behind that? We've been talking about unifying any wp-admin experiences we maintain to be genuine and to all utilize the WordPress design system, and not using `@wordpress/components` seems like a departure from that goal.

> That said I think we'd want to lean into the uniformity of components for WP so things in wp-admin use the same design language. In that case better encapsulation can be seen as a good thing.

While I agree on the premise, I'm not sure I follow the argument about encapsulation. One could argue that any 3rd party plugin would still want to customize and extend any UI components while still using the same design language.

**Comment by reykjalin** [comment]
> not using `@wordpress/components` seems like a departure from that goal.

Ah, I'm not suggesting we remove `@wordpress/components`, what I meant was that the components in the package should be replaced with Web Components. So, for example, when you `import { Button } from '@wordpress/components` it's a Web Component (or a React wrapper around a Web Component as would have to be the case atm).

> One could argue that any 3rd party plugin would still want to customize and extend any UI components

Of course! And this could be exposed through a style API, or people could fork the components to build on them. It is also possible to make the shadow DOM open to manipulation from CSS outside the component itself which would make them work pretty much the same as our current components.

And the children of the component are styled according to the stylesheet of the "light DOM", so in the case of

```html
<wp-button><span class="italic-font">Click me</span></wp-button>
```

the `span` would be affected by any CSS targeting `.italic-font` from the code consuming the component, not from the component itself (i.e. the shadow DOM). So even with the encapsulation it's not like there is no customization possible.

**Comment by tomalec** [comment]
> One could argue that any 3rd party plugin would still want to customize and extend any UI components

Web Components are IMHO, way much better than any other framework here. Instead of implementing any kind of opinionated, custom JS-in-CSS theming or style-injection solution, we can use well-established framework-agnostic standard of CSS variables and shadow DOM parts. 

3rd party plugin needs to customize the look of `wp-card`:

```css
wp-card::part(header):hover {
  background-color: #0c0d33;
}
wp-post:state(draft){
	--main-color: grey;
}
```
No tooling, no build process, no library forced, just plain native CSS.

Thanks to the style encapsulation, we can expose what things we want for styling and hide the other. So even though we used `div{ border: 1px solid red; }` inside, no other div outside will get affected, and no external stylesheet will affect us unless we allow it to.


Some other 3rd party plugin needs to read something in their JS from our `<wp-post-comment>` element? They can use the API they know for sure: DOM API.
```js
document.querySelector('wp-post-comment').gatAttribute('likes-count')
```

Or maybe they, want to create `<wp-post-comment>` that behaves and look like ours, but shoot lasers when clicked?
```js
customElements.define( 'laser-post-comment', class LaserPostComment extends WPPostComment {
   connectedCallback(){
    super();
    this.addEventListener('click', shotLasers);
   }
});
```

No tooling, no build process, no secret lore, no framework collisions, no framework version collisions, just work.

I think it's hard to achieve the above with React components.

**Comment by tyxla** [comment]
> Ah, I'm not suggesting we remove @wordpress/components, what I meant was that the components in the package should be replaced with Web Components. 

I see. So shouldn't that experimentation be taking place in Gutenberg where `@wordpress/components` is being developed and maintained? 

> Web Components are IMHO, way much better than any other framework here. Instead of implementing any kind of opinionated, custom JS-in-CSS theming or style-injection solution, we can use well-established framework-agnostic standard of CSS variables and shadow DOM parts.

Not arguing what's better or worse, but it's fair to say this would go against the current direction of creating a unified design system for all products to follow, which is core-first. In any case, I'd recommend keeping a core-first approach, where such a change should follow the WP core and should likely be started by the WP core and implemented there first.

**Comment by reykjalin** [comment]
> shouldn't that experimentation be taking place in Gutenberg where `@wordpress/components` is being developed and maintained?

Sure, but I have no idea what the general dev setup is for `@wordpress/components`, so for a 1 week long HACK project it made more sense to work in codebases that I'm intimately familiar with so I could get more work done.

> this would go against the current direction of creating a unified design system for all products to follow, which is core-first

I'm not sure I understand how this is going against that direction? The whole point of the experiment was to determine if it would be viable to use Web Components in `@wordpress/components` instead of React components. I'm not sure how that goes against a unified design system, even if it's a slightly different take on that?

**Comment by reykjalin** [comment]
Closing this since HACK week is over and a post has been published on the experiment at pcrvl0-1gP-p2.

**Pull request closed without merging**
