### PR TITLE
Fixed a JS error causing empty transactions list

### PR DESCRIPTION
**Pull request by kalessil**
Fixes a JS error causing empty transactions list.

```
Uncaught TypeError: e.order.subscriptions is undefined
    j index.js:165
    rc index.js:155
    renderWithHooks react-dom.js:15246
    updateFunctionComponent react-dom.js:17063
    beginWork$1 react-dom.js:18636
    callCallback react-dom.js:341
    invokeGuardedCallbackDev react-dom.js:391
    invokeGuardedCallback react-dom.js:448
    beginWork$$1 react-dom.js:23355
    performUnitOfWork react-dom.js:22349
    workLoopSync react-dom.js:22323
    renderRoot react-dom.js:22016
    runRootCallback react-dom.js:21692
    flushSyncCallbackQueueImpl react-dom.js:11491
    unstable_runWithPriority react.js:2820
    runWithPriority$2 react-dom.js:11443
    flushSyncCallbackQueueImpl react-dom.js:11487
    flushSyncCallbackQueue react-dom.js:11476
    scheduleUpdateOnFiber react-dom.js:21569
    dispatchAction react-dom.js:15954
    onStoreChange data.js:3355
    unsubscribe data.js:3371
    globalListener data.js:2418
    globalListener data.js:2417
    subscribe data.js:2024
    dispatch data.js:1101
    createMiddleware Redux
    promiseMiddleware data.js:1560
    createResolversCacheMiddleware data.js:1619
    dispatch data.js:1505
    Redux 13
    promiseMiddleware data.js:1560
    createResolversCacheMiddleware data.js:1619
    _callee2$ data.js:2285
    tryCatch wp-polyfill.js:6517
    invoke wp-polyfill.js:6746
    method wp-polyfill.js:6569
    asyncGeneratorStep data.js:3975
    _next data.js:3997
    _asyncToGenerator data.js:4004
    _asyncToGenerator data.js:3993
    fulfillResolver data.js:2247
    _callee$ data.js:2208
    tryCatch wp-polyfill.js:6517
    invoke wp-polyfill.js:6746
    method wp-polyfill.js:6569
    asyncGeneratorStep data.js:3975
    _next data.js:3997
    _asyncToGenerator data.js:4004
    _asyncToGenerator data.js:3993
    _fulfillSelector data.js:2220
    fulfillSelector data.js:2175
    selectorResolver data.js:2223
    v hooks.js:59
    useSelect data.js:3308
    rc hooks.js:30
    renderWithHooks react-dom.js:15246
    mountIndeterminateComponent react-dom.js:17480
    beginWork$1 react-dom.js:18624
    beginWork$$1 react-dom.js:23331
    performUnitOfWork react-dom.js:22349
    workLoopSync react-dom.js:22323
    renderRoot react-dom.js:22016
    scheduleUpdateOnFiber react-dom.js:21557
    scheduleRootUpdate react-dom.js:24457
    updateContainerAtExpirationTime react-dom.js:24485
    updateContainer react-dom.js:24574
    legacyRenderSubtreeIntoContainer react-dom.js:25101
    unbatchedUpdates react-dom.js:21825
    legacyRenderSubtreeIntoContainer react-dom.js:25100
    render react-dom.js:25180
    561 index.js:2
    561 index.js:2
    a index.js:2
    app index.js:2
    <anonymous> index.js:2
```

#### Changes proposed in this Pull Request

* Harden subscriptions availability checks

#### Testing instructions

* Ensure transactions lists is shown in your local client instance

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

**Comment by dechov** [comment]
The change looks good, but just curious: is the error reproducible in `trunk`, and how? ([This code](https://github.com/Automattic/woocommerce-payments/blob/85aa68f8d5f34f6f064176f703aa3ba0c05d5626/includes/wc-payment-api/class-wc-payments-api-client.php#L1024-L1025) was intended to make sure that a `subscriptions` array was present whenever Subscriptions was active, but perhaps it wasn't enough.)

**Comment by kalessil** [comment]
It was possible to reproduce the issue on trunk on Friday, but currently, the issue has gone.
The referenced code looks good and should cover the case, hence not sure what to do with this PR.

What do you think @dechov?

**Comment by dechov** [comment]
Hm, both appear to be unchanged from a few months ago so I wonder how the error was triggered – in any case, I reproduced the error by removing that linked code adding the `subscriptions` array, and this branch tests well guarding against the error. Can't hurt – I'm in favor of merging this 👍

**Review by dechov — APPROVED** [review]
Code change looks good and tests well. Pre-approving – any idea why the checks are failing?

**Comment by kalessil** [comment]
@dechov: thanks for approving. Yes, we addressed the failure already - this branch doesn't' contain the fix yet. Will rebase and merge once the build is green.

**Pull request merged**
