### PR TITLE
Demo site deploy branch –  Simplify deposits project

### PR DESCRIPTION
**Pull request by brucealdridge**
> **Warning**
> This PR should not be merged. It is used for testing work in progress for the Simplify Deposits project. All work in this project will be tracked and merged from individual PRs. 

This branch has been created to test work in progress for the Simplify Deposits project. If you want to test this on a site, install the [Jetpack Beta](https://jetpack.com/download-jetpack-beta/) plugin and select the "Simplify Deposits" feature branch on WC Payments.

This work is hidden behind a feature flag, `_wcpay_feature_simplify_deposits_ui` to enable it you can use WPCLI ` wp option update _wcpay_feature_simplify_deposits_ui 1` to set this flag.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `5899` or branch name `feature/simplify-deposits` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=feature/simplify-deposits) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 64d0c1d9305d7b170b8b7dbb589d4a0dd8653757
- Build time: 2023-04-19 00:00:19 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by shendy-a8c** [comment]
Built zip for this branch here: https://github.com/Automattic/woocommerce-payments/actions/runs/4719311017.

**Comment by haszari** [comment]
I think this can be closed now the project is complete! @brucealdridge - can you close or comment with next steps?

**Comment by brucealdridge** [comment]
Closing, not required anymore.

**Pull request closed without merging**
