### PR TITLE
Release: actualized changelog headers

### PR DESCRIPTION
**Pull request by kalessil**
#### Changes proposed in this Pull Request

* Updates changelog headers

-------------------

- [ ] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

### CODE REVIEW

**Review by vbelolapotkov — APPROVED** [review]
LGTM. :shipit:

**Comment by jrodger** [comment]
The stable tag in the readme is still 2.2.0, should that be updated by this PR as well?

**Comment by vbelolapotkov** [comment]
> The stable tag in the readme is still 2.2.0, should that be updated by this PR as well?

It shouldn't be updated by this PR. It's already 2.3.0 in trunk, but still 2.2.0 in develop. @kalessil did you sync develop with trunk after release?

**Comment by kalessil** [comment]
Nope, that was missing part. Fixed in 522c984358305312358ee8c710b6176ea2d08093.

**Pull request closed without merging**
