### PR TITLE
Add idempotency key to post requests

### LINKED ISSUE #530: Add idempotency key to headers of all POST requests to the server API
To facilitate debugging (the key should be logged with the request) and reduce the likelihood of unwanted duplicate charges

### PR DESCRIPTION
**Pull request by chickenn00dle**
Fixes #530 

#### Changes proposed in this Pull Request

This adds an idempotency key to all post requests sent to the server. This also adds request headers to logs so the idempotency key is useful for debugging.

#### Testing instructions

- Trigger a post request by doing something like completing checkout
- Confirm idempotency key is present in headers. Be sure to also check logs.
- Trigger a get or delete request
- Confirm idempotency key is not present in headers. Be sure to also check logs.

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply)

### CODE REVIEW

**Review by leonardola — APPROVED** [review]

**Comment by leonardola** [comment]
LGTM 🚢

**Comment by leonardola** [comment]
LGTM 🚢

**Comment by jrodger** [comment]
I don't know how much of an issue this is, but is this the first time we're requiring an OpenSSL function in the plugin? Does that mean PHP would need the OpenSSL module available?

I've seen other plugins require it, so maybe it's generally available - but is it worth considering the case where the `openssl_random_pseudo_bytes` isn't found? I haven't checked if it would be appropriate in this case, but [random_bytes](https://www.php.net/random-bytes) is a more portable method that might also do the trick?

Are we looking at this purely from an improved logging point of view? I don't think there is a situation where this would guard against duplicate requests right? Because a new key is going to get generated for every call.

**Comment by chickenn00dle** [comment]
Thanks for looking into this @jrodger!

> is it worth considering the case where the openssl_random_pseudo_bytes isn't found?

I always thought openssl extension was a requirement for WordPress generally, but am seeing now it is [only a recommendation](https://make.wordpress.org/hosting/handbook/server-environment/).

>  I haven't checked if it would be appropriate in this case, but random_bytes is a more portable method that might also do the trick?

`random_bytes` does do the trick. I've made the change to this in https://github.com/Automattic/woocommerce-payments/pull/3303/commits/e9f8279d6aa02d435fffb8370c4af4d77b2fdeb9 to be safe.

> Are we looking at this purely from an improved logging point of view? I don't think there is a situation where this would guard against duplicate requests right? Because a new key is going to get generated for every call.

Yeah, at least this was my impression going into this issue. It looks like we are already generating a unique id for each post request on server unless one is provided, so this only passes the buck to the client and adds this to logs. That said, I'm happy to look further into using the key to guard against duplicate requests.

**Comment by jrodger** [comment]
> It looks like we are already generating a unique id for each post request on server unless one is provided, so this only passes the buck to the client and adds this to logs.

Good point.

> That said, I'm happy to look further into using the key to guard against duplicate requests.

I looked at it briefly a while back and came to the conclusion that it's complicated 😅. Just updating the issue or raising a new one would be a good first step.

**Comment by chickenn00dle** [comment]
> Just updating the issue or raising a new one would be a good first step.

Good call @jrodger. I've created a new issue for this here: https://github.com/Automattic/woocommerce-payments/issues/3352

Let me know if you noticed any other issues. 

Thanks again!

**Comment by jrodger** [comment]
I don't have any other comments, thanks for looking at my drive-by review!

**Pull request merged**
