### PR TITLE
Change IP country fraud rule after selling country settings change on WC settings

### LINKED ISSUE #8134: Update "International IP Address" ruleset after changes to Woo Core settings
### Describe the bug

The International IP Address setting allows a merchant to automatically block a transaction if the customer's IP address is from a country that the merchant does not sell to.

The countries that a merchant does not sell to are defined in the Woo general settings at **WooCommerce > Settings > General > Selling location(s)**. If `Block transactions for international IP addresses` is enabled, it creates a "snapshot" of the selling location settings in Woo core. This means that if the selling locations are updated, the countries that are blocked by the `Block transactions for international IP addresses` setting won't be updated _until_ the fraud settings are re-saved.

### To Reproduce

1. Set the `Selling locations` to `Sell to all countries, except for...` and add your country of residence to the list.
2. Enable `Block transactions for international IP addresses` in the WCPay fraud settings.
3. Attempt a purchase using an address from another country.
4. The payment will be blocked, as expected, because your IP is from a country that the site does not sell to.
5. Change the `Selling locations setting to...` to either (a) `Sell to all countries` or (b) `Sell to all countries, except for...` — but remove your country and add a different country.
6. Attempt another purchase. The payment will still be blocked.
7. To allow the transaction to succeed, you can (a) disable the `Block transactions for international IP addresses` setting, (b) re-save your advanced settings, or (c) change the fraud settings to `Basic`.

### Actual behavior

The `Block transactions for international IP addresses` setting does not update the block rules dynamically based on a store's core settings, which means that if a merchant makes an adjustment to their core settings, it can create instances where customer purchases are inadvertently blocked.

### Expected behavior

The `Block transactions for international IP addresses` setting is updated when the Selling location(s)` option is updated in the Woo core settings.

Additionally, if the `Block transactions for international IP addresses` setting is enabled, we should consider adding a notice in the Woo core settings when the `Selling location(s)` is adjusted that informs the merchant that modifying their selling locations will also modify their fraud rules.

### Additional context
7690249-zd-a8c
p1707100669928329-slack-C7U3Y3VMY

### PR DESCRIPTION
**Pull request by tpaksu**
Fixes #8134

#### Changes proposed in this Pull Request

This PR adds the functionality to update the server ruleset when the ruleset contains the IP country rule, which checks for the countries the user is selling and blocks the payment if the order isn't originated from one of the countries in the allowed list, and the country settings are changed on WooCommerce general settings page. 

- If the fraud ruleset settings level is not "advanced", it skips the ruleset update.
- If the IP country rule isn't activated on the ruleset, it skips the ruleset update.
- If the user has changed the selling countries, it updates the ruleset configuration.
- If the user has chosen to sell to all countries, it doesn't disable the rule on the ruleset, it converts it to `IN []` to never match and block the payment, so another update can change the ruleset again. 

> [!NOTE]
> The last item has a contradiction with the UI, as when the user changes the WC General settings page to sell to all countries, while the rule is enabled on the advanced settings page, the rule stays enabled, but the UI doesn't show the toggle to turn it off. It has no effect on the processing, so it can stay like this. When the user saves the advanced fraud settings, the rule will get disabled, which will have the same effect with `IN []`.

#### Testing instructions

* Checkout this branch. 
* Apply the below patch to see things clearer: 

```diff
diff --git a/includes/class-wc-payment-gateway-wcpay.php b/includes/class-wc-payment-gateway-wcpay.php
index 64e404dff..98a8429c0 100644
--- a/includes/class-wc-payment-gateway-wcpay.php
+++ b/includes/class-wc-payment-gateway-wcpay.php
@@ -2986,9 +2986,12 @@ class WC_Payment_Gateway_WCPay extends WC_Payment_Gateway_CC {
 	public function update_fraud_rules_based_on_general_options() {
 		// If the protection level is not "advanced", no need to run this, because it won't contain the IP country filter.
 		if ( 'advanced' !== $this->get_current_protection_level() ) {
+			wc_get_logger()->debug( 'Fraud protection is not in advanced state, skipping updates.' );
 			return;
 		}
 
+		wc_get_logger()->debug( 'Fraud protection is in advanced state, continuing.' );
+
 		// If the ruleset can't be parsed, skip updating.
 		$ruleset = $this->get_advanced_fraud_protection_settings();
 		if (
@@ -2996,27 +2999,37 @@ class WC_Payment_Gateway_WCPay extends WC_Payment_Gateway_CC {
 			|| ! is_array( $ruleset )
 			|| ! Fraud_Risk_Tools::is_valid_ruleset_array( $ruleset )
 		) {
+			wc_get_logger()->debug( 'Fraud protection configuration is not valid. Skipping update' );
 			return;
 		}
 
+		wc_get_logger()->debug( 'Fraud protection configuration is valid, continuing.' );
+
 		$needs_update = false;
 		foreach ( $ruleset as &$rule_array ) {
+			wc_get_logger()->debug( 'Currently processing rule: ' . $rule_array['key'] );
 			if ( isset( $rule_array['key'] ) && Fraud_Risk_Tools::RULE_INTERNATIONAL_IP_ADDRESS === $rule_array['key'] ) {
 				$new_rule_array = Fraud_Risk_Tools::get_international_ip_address_rule()->to_array();
 				if ( isset( $rule_array['check'] )
 					&& isset( $new_rule_array['check'] )
 					&& wp_json_encode( $rule_array['check'] ) !== wp_json_encode( $new_rule_array['check'] )
 				) {
+					wc_get_logger()->debug( 'Rule is changed. Commencing update.' );
 					$rule_array   = $new_rule_array;
 					$needs_update = true;
+				} else {
+					wc_get_logger()->debug( "Rule isn't changed. Skipping update." );
 				}
 			}
 		}
 
 		// Update the possibly changed values on the server, and the transient.
 		if ( $needs_update ) {
+			wc_get_logger()->debug( 'Ruleset is changed. Sending update.' );
 			$this->payments_api_client->save_fraud_ruleset( $ruleset );
 			set_transient( 'wcpay_fraud_protection_settings', $ruleset, DAY_IN_SECONDS );
+		} else {
+			wc_get_logger()->debug( "Ruleset isn't changed. Skipping server update." );
 		}
 	}
 
```

* Open the logs on `docker\wordpress\wp-content\uploads\wc-logs\plugin-woocommerce-[today].php`, clear the file, and save it.
* Set the fraud protection level to Basic.
* Go to WooCommerce > Settings, change the selling countries to some specific ones. Save the settings.
* Check if the log file shows that nothing is updated.
* Set the fraud protection level to Advanced, edit the configuration with enabling something different than the International IP address. 
* Go to WooCommerce > Settings, change the selling countries to some specific ones. Save the settings.
* Check if the log file shows that nothing is updated.
* Go to advanced fraud configuration again, enable the International IP address rule.
* Go to WooCommerce > Settings, change the selling countries, add/remove countries. Save the settings.
* See that it's now updating the ruleset on the server.
* Go to your server DB, and check if the `wcpay_fraud_rulesets` table contains the updated row with the last country change. The ruleset will be added as a new row, not updating the previous one.
* Go to WooCommerce > Settings, change the selling countries to sell to all countries. Save the settings.
* See that it's now updating the ruleset on the server.
* Go to your server DB, and check if the `wcpay_fraud_rulesets` table contains the updated row with the last country change with an empty list. The ruleset will be added as a new row, not updating the previous one.

> [!IMPORTANT] 
> These testing instructions assumes that the filter is running correctly, and doesn't contain any sale testing. If you want to test it, you can sell something with adding/removing the country your IP shows to the list on WooCommerce > General page. A good testing instruction is included in the acceptance criteria on the linked issue. This change only focuses on updating the ruleset modifications, therefore skips the payment blocking part.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8524` or branch name `fix/8134-update-ip-ruleset-after-core-country-change` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/8134-update-ip-ruleset-after-core-country-change) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 962c76486b2a995a43fa86c3b4d9ea5ade4770c4
- Build time: 2024-04-03 14:09:28 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by eduardoumpierre — CHANGES_REQUESTED** [review]
I followed the testing instructions and everything worked as expected, but I had an issue while testing the blocks. After some debugging, I found out that we're saving the selling location strings using different capitalizations on the WooCommerce Settings page (all uppercase) and the Advanced Fraud Settings (all lowercase).

Ruleset saved from the WooCommerce Settings page:
```json
[
  ...,
  {
    "key": "international_ip_address",
    "outcome": "review",
    "check": { "key": "ip_country", "operator": "in", "value": "BR" }
  }
]
```

Ruleset saved from the Advanced Fraud Protection page:
```json
[
  ...,
  {
    "key": "international_ip_address",
    "outcome": "block",
    "check": { "key": "ip_country", "operator": "in", "value": "br" }
  }
]

```

Since we [modify the IP country data](https://github.com/Automattic/woocommerce-payments-server/blob/trunk/server/wp-content/rest-api-plugins/endpoints/wcpay/service/class-fraud-ruleset-service.php#L232) to be lowercase, the comparison using [`in` and `not_in`](https://github.com/Automattic/woocommerce-payments-server/blob/trunk/server/wp-content/rest-api-plugins/endpoints/wcpay/service/class-fraud-ruleset-service.php#L376-L379) fail, because the `in_array()` function expects the strings to be the same.

Just to summarize, we're saving an uppercased selling location string on the WooCommerce Settings page, which makes the rule engine `in` and `not_in` checks fail. The version saved from the Advanced fraud protection page works as expected.

**Comment by tpaksu** [comment]
@eduardoumpierre thanks for the review, I checked the code and saw that it was like that since the beginning! Thanks for catching that.

Added the conversion to lowercase part in [0ae4b71](https://github.com/Automattic/woocommerce-payments/pull/8524/commits/0ae4b71ec3e81dc60a29de98366f2db7607bd7d1). Can you check that part again? Thanks in advance!

**Review by eduardoumpierre — CHANGES_REQUESTED** [review]
The ruleset that is saved from the WooCommerce Settings page has the outcome `REVIEW` instead of `BLOCK`, causing the payment to be processed.

Ruleset saved from the WooCommerce Settings page:
```json
[
  {
    "key": "international_ip_address",
    "outcome": "review",
    "check": {
      "key": "ip_country",
      "operator": "in",
      "value": "br|bn"
    }
  }
]
```

Opening the Advanced Fraud Protection page and just hitting save creates the following ruleset:
```json
[
  {
    "key": "international_ip_address",
    "outcome": "block",
    "check": {
      "key": "ip_country",
      "operator": "in",
      "value": "br|bn"
    }
  }
]
```

Since this breaks the feature, I think we need to address it in this PR.

**Comment by tpaksu** [comment]
Yes, that wasn't something I changed in this PR, it was all like that from before. I've included the fix for that in this PR in https://github.com/Automattic/woocommerce-payments/pull/8524/commits/962c76486b2a995a43fa86c3b4d9ea5ade4770c4. Now it needs all rules to be tested. I'll appreciate if you can confirm if it's working too @eduardoumpierre.

**Review by eduardoumpierre — APPROVED** [review]
I followed the testing instructions and it worked as expected. The changes from the WooCommerce Settings page are reflected in the latest ruleset.

As you commented, I tested all the rules to make sure that the latest change didn't break anything.

| Rule | Block | Allow |
|--------|--------|--------|
| AVS Mismatch | ⏩  | ⏩ |
| International IP Address | ✅ | ✅ |
| IP Address Mismatch | ✅ | ✅ | 
| Address Mismatch | ✅ | ✅ | 
| Purchase Price Threshold | ✅ | ✅ | 
| Order Items Threshold | ✅ | ✅ | 
| CVC Verification | ⏩ | ⏩ | 

Thanks for working on this issue! LGTM :shipit:

**Pull request merged**
