### PR TITLE
Fix deprecated string interpolation in Analytics.php

### LINKED ISSUE #7169: Deprecated string interpolation ${var} with {$var} in /woocommerce-payments/includes/multi-currency/Analytics.php
### Describe the bug
When using the WooCommerce Payments plugin, we've encountered a deprecation issue related to string interpolation.

### To Reproduce
1. Install and activate the WooCommerce Payments plugin.
2. Visit WordPress Dashboard

### Actual behavior
Upon inspecting the server logs, we observe the following deprecation warnings:

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /plugins/woocommerce-payments/includes/multi-currency/Analytics.php on line 330
Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /plugins/woocommerce-payments/includes/multi-currency/Analytics.php on line 331
Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /plugins/woocommerce-payments/includes/multi-currency/Analytics.php on line 332

### Desktop (please complete the following information):

* OS: macOS 13.3 (22E252)
* Browser: chrome
* Version: 116.0.5845.140

### Smartphone (deemed not neccessary):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### Additional context
* PHP Version: 8.2 - as of this version using ${var} in strings is deprecated
* Woocommerce Version: 8.0.3
* Woocommerce Payments Version: 6.4.1

### PR DESCRIPTION
**Pull request by ridonibishi**
Fixes #7169 

#### Changes proposed in this Pull Request

**Title:** Fix deprecated string interpolation in Analytics.php

**Description:**
This PR addresses a deprecation issue in `/var/www/html/web/app/plugins/woocommerce-payments/includes/multi-currency/Analytics.php`. The problem involves the use of `${var}` for string interpolation, which is deprecated. This change replaces `${var}` with the correct `{$var}` format, resolving the following warnings:

- Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /plugins/woocommerce-payments/includes/multi-currency/Analytics.php on line 330
- Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /plugins/woocommerce-payments/includes/multi-currency/Analytics.php on line 331
- Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /plugins/woocommerce-payments/includes/multi-currency/Analytics.php on line 332

**Testing instructions:**
To test this change, follow these steps:

No tests are required because the code changes involve straightforward syntax updates to resolve deprecation warnings. These changes are low-risk and don't introduce new functionality. Visual inspection and basic validation confirm the correctness of the fix. If further testing is required:

1. *Clone the repository and switch to the branch with this fix:*
   ```bash
   git clone https://github.com/your-username/your-repo.git
   cd your-repo
   git checkout bug-fix
2. *Ensure you have the necessary development environment set up for WooCommerce Payments.*
3. *Locate the Analytics.php file in the multi-currency folder within the WooCommerce Payments plugin.*
4. *Check lines 330-332 and the suggested fix*
5. *Identify test cases that previously triggered the deprecation warnings related to string interpolation using ${var}.*
6. *Execute the identified test cases and confirm that the deprecation warnings no longer appear.*
7. *Verify that the correct {$var} interpolation is now in place and that the affected code still functions as expected.*


-------------------

- [x] Run `npm run changelog` to add a changelog file (is `patch`).
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios): _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos, etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by dwainm** [comment]
Thank you for the PR @ridonibishi ! We'll take a look at it and provide any feedback as soon as possible.

**Review by tpaksu — APPROVED** [review]
The changes make sense, there's no need to test because the alternatives the PR provides were already in use in their previous occurrences. LGTM! And thanks for providing this fix!

**Comment by tpaksu** [comment]
@ridonibishi can you add a changelog before we merge this to the main repo? You can run `npm run changelog` after installing the necessary packages. Select `patch` and skip the message, add your change as a comment (the script will ask after skipping the message), since it's not a big change.

**Comment by tpaksu** [comment]
I took the initiative and pushed the changelog and added it to the merge queue. Thank you for catching and fixing this!

**Comment by ridonibishi** [comment]
Sorry - was on a band tour the past 4 days! Thanks for reviewing and patching! Godspeed! 💯

**Pull request merged**
