### PR TITLE
Rename log title to woopayments

### LINKED ISSUE #7927: Rename log title to woopayments
### Description

I was recently testing WooPayments and attempted to check the log. I searched the log dropdown for `woopayments`and no log was returned. I figured it's still using the old product name. Though not a significant change, I think it might be beneficial to update the log title to match the product name to ensure consistency. 

The natural thing is to search for the product name (I also search for `woopayments` first when trying to find this repo. 😂

### PR DESCRIPTION
**Pull request by oaratovskyi**
Fixes #7927 

#### Changes proposed in this Pull Request

Update the log title to match the product name to ensure consistency.

#### Testing instructions

* Checkout the branch `fix/7927-rename-log-title-to-woopayments`
* Perform some actions on your store (onboarding / buy and order / etc)
* Visit http://localhost:8082/wp-admin/admin.php?page=wc-status&tab=logs
* Observer there's new `woopayments` log file alongside with `woocommerce-payments`
* Open it and check that logs are being written to the new file
* Search by `woopayments` and see that results are in both old and new log

image

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _'QA Testing Not Applicable'_
- [x] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [x] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8255` or branch name `fix/7927-rename-log-title-to-woopayments` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/7927-rename-log-title-to-woopayments) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: b09c346ee2ae894dce0b6b96389802e23cfb088e
- Build time: 2024-02-23 10:26:02 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by dmallory42** [comment]
I'm a little unsure about this change - on the one hand I can see it does make things easier for people trying to find the logs, but on the other hand this would mean that a store would have logs WCPay in two different places and I wonder if this could lead to confusion, especially if people have build things like monitoring tools around the existing log names. 

Maybe I am overthinking it, but I prefer to mention it before we merge the PR 🙂  WDYT?

**Comment by oaratovskyi** [comment]
>  especially if people have build things like monitoring tools around the existing log names
hmmm, that's a good point 🤔 
I didn't think about this specific case, I don't know how many of our merchants use these logs as input for monitoring etc

@marcinbot could you help us here a bit? maybe you know more about how our merchants use plugin logs

**Comment by oaratovskyi** [comment]
Thanks Marcin!

**Review by dmallory42 — APPROVED** [review]
LGTM, thanks for working on it! :shipit: 

I think we should make sure HE's are aware of it so that they know from the next version of WCPay that they need to look for `woopayments` rather than `woocommerce-payments` and handle any documentation updates that may be needed. 👍

**Pull request merged**
