### PR TITLE
Ignore filesystem sniffs for GH workflows and tests

### LINKED ISSUE #8435: Fix filesystem interaction phpcs reports
## Description

This is a follow up to https://github.com/Automattic/woocommerce-payments/pull/8415 where there are some issues reported by phpcs that were not a straight-forward fix.

Running

```sh
./vendor/bin/phpcs --standard=phpcs.xml.dist $(git ls-files | grep '.php$') --sniffs='WordPress.WP.AlternativeFunctions'
```

Results in a list of issues in these files:

* `.github/workflows/scripts/get-next-version.php`
* `tests/unit/subscriptions/test-class-wc-payments-subscription-migration-log-handler.php`

We should go through all of these issues and either:

1. Fix the issue; or
2. If it's not an issue add an ignore in place.

This is a rule that I think is valuable so we should probably not add a project-wide ignore for these.

## Acceptance criteria

No more issues reported by `phpcs`.

### PR DESCRIPTION
**Pull request by reykjalin**
Fixes #8435 

## Changes proposed in this Pull Request

* Ignore the `WordPress.WP.AlternativeFunctions` sniff for the `.github` and `tests` folder.

## Testing instructions

* Run `npm run lint:php` and make sure no issues are reported.

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8535` or branch name `fix/filesystem-phpcs-reports` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/filesystem-phpcs-reports) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 1f104c49866f73d2935a9f7e946576871784b003
- Build time: 2024-04-03 16:51:01 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by lovo-h — APPROVED** [review]
Code changes look good and test well 👍 

#### Testing Instructions
* ✅ Run `npm run lint:php` and make sure no issues are reported.
* ✅ Confirmed that without these rules, the `./.github/workflows/scripts/get-next-version.php` and `./tests/unit/subscriptions/test-class-wc-payments-subscription-migration-log-handler.php` files throw warnings.
* ✅ According to the [coding standards, the `AlternativeFunctions`](https://github.com/WordPress/WordPress-Coding-Standards/blob/develop/WordPress/Sniffs/WP/AlternativeFunctionsSniff.php), "Discourages the use of various functions and suggests (WordPress) alternatives". These standards do not appear to be necessary in the `tests/` and `.github/` directories.

**Comment by lovo-h** [comment]
@reykjalin, the only thing missing is the changelog (e.g. `npm run changelog`).

**Comment by reykjalin** [comment]
I've added the changelog entry (thanks Hector!) and will merge when the checks are done 👍

**Pull request merged**
