### PR TITLE
Getting settings directly from the db in Logger

### PR DESCRIPTION
**Pull request by gpressutto5**
#### Changes proposed in this Pull Request

This PR does the same as #8037 in a different way, following the same logic used in #8003. It removes the dependency of an instance of WC_Payment_Gateway_WCPay from the Logger class, allowing it to be used before init.
This fixes the issue discussed in this thread p1705353944976299-slack-CGGCLBN58

#### Testing instructions

**Do not update branch**

- Ensure the `(clear)` option from devtools works.
- Ensure errors are still logged correctly. 
- Smoke tests and ensures everything still works fine.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8038` or branch name `refactor-logger` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=refactor-logger) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 309c856472d3a6401ca5f2acf7cebc1c830f77e7
- Build time: 2024-01-18 15:00:41 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by mdmoore — CHANGES_REQUESTED** [review]
On this branch, the account cache is returning `[]`. Using `Force update WCPay Server Stripe cache` -> `Clear` has the same effect. It appears that running `get_account_country()` is leading to an early call to `get_cached_account_data()`. When removing the try block from the `get_account_country` function in `class-wc-payment-gateway-wcpay.php` the call to `get_cached_account()` via `$account->get_account_country()` is skipped and the full account data is returned.

**Comment by gpressutto5** [comment]
I had the same problem when I first checkout out #8037 (p1705513477163079/1705353944.976299-slack-CGGCLBN58), but I thought it was something in the server as it worked after a few minutes and I never got the same issue again.

**Comment by gpressutto5** [comment]
Are you using the latest devtool commited today @mdmoore?

**Comment by mdmoore** [comment]
> Are you using the latest devtool commited today @mdmoore?

I was not. After updating devtools to the latest, the account cache refreshes as expected. Logging is working as expected also. This looks good to me now.

**Review by mdmoore — APPROVED** [review]
LGTM after the latest changes to devtools.

**Comment by gpressutto5** [comment]
Double checking the Logger still works before merging this PR

image

**Pull request merged**
