### PR TITLE
Fix missing customer data from transactions report

### LINKED ISSUE #7595: Transactions Report - Fix missing customer data
### Describe the bug

The customer name, email, and country details - as seen on the Transactions page and its exported CSV file - are sometimes missing. My hunch is that we store this information only when an order is created by a logged-in user.

Screenshot 2023-11-01 at 6 11 55 PM

### To Reproduce

1. Check out an order as a logged-in user.
2. Check out an order as a guest (not logged in).
3. Make an in-person payment for an existing or new order.
4. Compare the customer data on the Transactions page for all three.

### Actual behavior

Customer details are sometimes not shown for transactions made by a guest shopper. This is always true for IPP transactions.

### Expected behavior

Customer details should be shown for all transactions irrespective of whether the shopper is a guest or whether it's an IPP transaction.

IMO, we can fix this behavior by falling back to the customer name and email in the order details:

image

and to the customer country in the transaction details:

image

### PR DESCRIPTION
**Pull request by dpaun1985**
Fixes #7595 

#### Changes proposed in this Pull Request
For WooPayments Subscriptions that uses [Stripe Billing](https://stripe.com/en-gb-ro/billing), update transaction to contain also the customer name, email and country.

#### Testing instructions

**Enable Stripe Billing subscriptions**

1. In `wp_options` table, set `_wcpay_feature_subscriptions` to `1`
2. Setup WCPay Dev tools with Test Clocks setup. FG article available here: PCYsg-DQ4-p2 

We need to test it together with 4227-gh-Automattic/woocommerce-payments-server

**On develop branch:**
1. Purchase a subscription product to create a Stripe Billing subscription
2. In the admin panel, go to Woo->Subscription and go to the new created subscription. In the left you will find Dev tools panel, with the test clock
Screenshot 2023-11-22 at 17 17 43

3. enable testing mode, in order to trigger the next payment events.
Screenshot 2023-11-22 at 17 30 10

4. trigger `invoice.paid` event
5. Go to `Payments->Transactions` and download the report. The customer name is missing from the report
6. Switch to this branch and test again. The order id should be added to the report for the new transactions.
7. check the server database. The transaction should have the customer name, email and country.

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7790` or branch name `fix/7595-reports-customers` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/7595-reports-customers) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 3dd0d89a67c583b5548e191b0d95f6947d9b2f4e
- Build time: 2023-12-07 10:50:28 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by mordeth — APPROVED** [review]
✅ The code appears to be in good shape!
✅ Done manual testing with subscription renewals, and the customer data is displayed correctly.
Screenshot 2023-11-28 at 16 47 53

**Review by mattallan — APPROVED** [review]
Code changes look good to me :+1:

Confirmed meta is populated on this branch:
image

**Comment by csmcneill** [comment]
Just to confirm: this change _will not_ retroactively add information to the `Customer` column if it was missing previously. Is this correct?

**Comment by anu-rock** [comment]
> Just to confirm: this change will not retroactively add information to the Customer column if it was missing previously. Is this correct?

@csmcneill That's right. Only merchants with with the latest version of WooPayments will benefit from this change.

@dpaun1985 How hard is it to pull the missing data for existing transactions? IIRC, we receive the customer data from Stripe Billing via webhooks, so it's not possible (or difficult) to pull it for past transactions. Is my understanding correct?

**Comment by dpaun1985** [comment]
> @dpaun1985 How hard is it to pull the missing data for existing transactions? IIRC, we receive the customer data from Stripe Billing via webhooks, so it's not possible (or difficult) to pull it for past transactions. Is my understanding correct?

 I created a spike for that  4280-gh-Automattic/woocommerce-payments-server

**Pull request merged**
