### PR TITLE
Make updating existing customer details during checkout async

### LINKED ISSUE #4490: Explore updating customer details during checkout async
### Description

Currently we update the customer details for existing customers during checkout flow which is blocking and makes a downstream API call to Stripe.

### Acceptance criteria

* Explore whether this affects any flow and is needed for the sync flow.
* If not, update it to be async during the checkout flow.

### Additional context

pdpOw2-Sb-p2#comment-1184

### PR DESCRIPTION
**Pull request by deepakpathania**
Fixes #4490 

#### Changes proposed in this Pull Request
- Make updating existing customer details during checkout async for performance benefits.

#### Testing instructions

- Follow the normal checkout flow(both UPE and non UPE) for an existing customer.
- Ensure there is a scheduled action created as `wcpay_update_customer_with_order_data` in Scheduled Actions (Tools > Scheduled Actions)
- Run the action and ensure there are no errors, additionally check logs to ensure a POST `wcpay/customers/{{customer_id}}` call was made (check WP-Admin > WooCommerce > Status > Logs and there should be a log for WooCommerce Payments with today's date)
- Ensure any UPE and subscription flows are not affected by this change. 
  - Context for subscriptions: p1658831357623559-slack-C02BW3Z8SHK

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Review by jbordonado — APPROVED** [review]
I tried a few scenarios with or without UPE, and I haven't faced any issue.
Stripe will link to an outdated customer in the account's dashboard until the async job runs, but I don't think that's a big problem..?

Code-wise, nothing to say; looks good.

For the instructions, please try to add details on where to look for the logs. If you copy/paste it like that for the release testing instructions, GlobalStep will ping us with a request to ask for that step, which can be avoided.

**Comment by deepakpathania** [comment]
> Stripe will link to an outdated customer in the account's dashboard until the async job runs, but I don't think that's a big problem..?

@jbordonado  Could you clarify this once? Do you mean the customer details will not be updated in the dashboard till the async job runs? If yes, that is fine since it doesn't affect the checkout flow directly and we are scheduling the update immediately so delay is only the time between the next queue picking it up. If you meant something else, please let me know.

**Comment by jbordonado** [comment]
I meant that there's a Customer (in blue) at the top when looking at the details of a payment on Stripe dashboard.
If I land on the checkout page with some info prefilled (because I already ordered something before), then a payment intent is created, along with a "customer".
I then change the checkout info and pay. 

Before the async job runs, it will show and link to the initial customer (the info that was prefilled initially on checkout). 
After the async job runs, it then shows the right customer's name and the right link (/customers/cus_xxx), i.e. the one with the info I updated on checkout.

**Review by jessy-p — APPROVED** [review]
Tested by disabling the scheduler and appears that functionalities work fine.

**Pull request merged**
