### PR TITLE
Update Jetpack dependencies, including the autoloader

### LINKED ISSUE #751: Jetpack Connection: Update jetpack-autoloader to the latest version
`jetpack-autoloader` version 2.0 is going to be released soon ([PR](https://github.com/Automattic/jetpack/pull/15106)). It's a significant upgrade, big enough to warrant a major version number. We should start using it as soon as possible. The  upgrade should be trivial for us (just bumping the version number), but we should consider spending some time testing it alongside Jetpack-the-plugin.

### PR DESCRIPTION
**Pull request by DanReyLop**
Fixes #751 

#### Changes proposed in this Pull Request

Upgraded all the composer `Automattic/jetpack-*` dependencies. The significant changes are:
- Upgraded the `jetpack-autoloader` to `2.3.0`. That version includes https://github.com/Automattic/jetpack/pull/16755, which fixes a possible crash related to OPCache when updating a plugin that uses the Jetpack autoloader. With that bug fixed, we can safely upgrade from `jetpack-autoloader` `1.x` to `2.x`.
- The new version of `jetpack-connection` includes [the Heartbeat package](https://github.com/Automattic/jetpack-heartbeat), which will send daily stats to wp.com.

#### Testing instructions

I tested that my site doesn't crash with the latest version of Jetpack's `Client-Example` plugin, and with the latest version of Jetpack. I' not sure what else to test, honsetly. Apart from the autoloader, the other upgrades are "semver minor", which means they should be backwards-compatible. And the autoloader upgrade has already been tested by @jrodger in https://github.com/Automattic/woocommerce-payments/pull/813 (before it was reverted).

### CODE REVIEW

**Comment by DanReyLop** [comment]
> I get a lot of warnings with Jetpack 8.6.1 installed alongside WCPay

Wow, you weren't exaggerating, those are A LOT of warnings.

They come from [this line](https://github.com/Automattic/jetpack/blob/master/packages/status/src/class-status.php#L24) in the `jetpack-status` package. So, if there's older code (such as `Jetpack 8.7` or earlier) that calls `Status()->is_development_mode()`, the warning will be triggered.

All references to `Status()->is_development_mode()` were changed to `Status()->is_offline_mode()` on `Jetpack 8.8`, but sinde the Autoloader will pick up the newest version of a package, if WCPay is installed alongside an older Jetpack version, you'll get all these warnings.

It doesn't help that it talks about something being deprecated in `Jetpack 8.8` yet you have an **older** version of Jetpack installed. That was very confusing for me, for an user it would be even more so. The message says that something got deprecated in Jetpack 8.8, yet the solution is to update **to 8.8**.

@sergeymitr Wht do you think? Should we update `jetpack-status` to have a better deprecation message, or to remove the message alltogether?

**Comment by sergeymitr** [comment]
Hi @DanReyLop.

I brought it up on the team meeting yesterday, and we think that it would be counterproductive to hide those notices for older Jetpack versions.
They are only displayed if WordPress is in the debugging mode, and are supposed to be an incentive to update Jetpack.

> It doesn't help that it talks about something being deprecated in Jetpack 8.8 yet you have an older version of Jetpack installed. That was very confusing for me, for an user it would be even more so.

That's a good point. We're thinking to switch those deprecation notices to the [package versions](https://github.com/Automattic/jetpack-connection/tags), which are not related to Jetpack. That should be less confusing to users.

**Comment by DanReyLop** [comment]
> We're thinking to switch those deprecation notices to the package versions, which are not related to Jetpack. That should be less confusing to users.

That would be better, altough a user wouldn't know what `jetpack-connection 1.7.X` is or why is it in their site. But there's no easy solution for that problem. Thanks for looking into it!

> They are only displayed if WordPress is in the debugging mode

What do you think about this @marcinbot ? As Sergey said`WP_DEBUG` isn't supposed to be used in production sites. On the other hand, if a user left it enabled by accident and has a version of Jetpack that's just a few weeks outdated, their site would become basically unuseable. We don't have much choice, but I'd feel better if you agree that this is a compromise we should make.

**Comment by DanReyLop** [comment]
Cool, thanks for chiming in @marcinbot !

This PR then can be merged as soon as there's a new version of `jetpack-connection` with [this fix](https://github.com/Automattic/jetpack/pull/17158) included. I'm marking it as "Blocked" in the meantime.

**Comment by sergeymitr** [comment]
@DanReyLop we just tagged the new package version: https://github.com/Automattic/jetpack-connection/releases/tag/v1.17.2
Should be ready to merge now.

Thanks for integrating the fix.

**Comment by DanReyLop** [comment]
@sergeymitr Thanks for cutting a release so quickly!

I've updated `jetpack-connection` to `^1.7.2`, I'm merging this PR now. If you eventually decide to remove the deprecation from `jetpack-status` I'll just update the dependency again.

**Pull request merged**
