### PR TITLE
Remove leftovers of the "Boost your sales by accepting new payment methods" task

### LINKED ISSUE #3434: Remove leftovers of the "Boost your sales by accepting new payment methods" task
### Description

After [this PR](https://github.com/Automattic/woocommerce-payments/pull/3134) got merged, there is an unused screen and variable that should be removed:

1. The non-UPE version of `%2Fpayments%2Fadditional-payment-methods`
  The non-UPE version of the `%2Fpayments%2Fadditional-payment-methods` path can't be accessed when the UPE preview is disabled. UPE preview is enabled by default and can only be disabled by changing the value directly in the DB, so this isn't a normal flow for merchants

2. The variable `wcpaySettings.additionalMethodsSetup.isTaskVisible` isn't used anymore, so it should be removed

### Acceptance criteria

* When the UPE preview is disabled, going to `<yousite>/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fadditional-payment-methods` should...? TBD. Should we just display the same screen as when the UPE preview is enabled? Or should we display nothing since this screen isn't relevant without the UPE preview?

* The `wcpaySettings.additionalMethodsSetup.isTaskVisible` variable must not be set in the localized array since it's not used on the JS side

### Testing instructions

For the `%2Fpayments%2Fadditional-payment-methods` screen:
1. Change (or create it if it doesn't exist) `_wcpay_feature_upe_settings_preview` to `0` in `wp_options`
2. Look for ways to get to `<yousite>/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fadditional-payment-methods` without going directly to the URL. Checking out the code for this should be simpler. There shouldn't be links/redirects going to that URL
3. Go to that URL by entering it into your browser directly. And... TBD, based on the acceptance criteria above.

For the `wcpaySettings.additionalMethodsSetup.isTaskVisible` variable:
1. Look for this variable being used in the JS part of the codebase, there must not be any instance of this
2. Thus it must not be defined in the localized `wcpaySettings` array

### Additional context

These are follow-up improvements coming from https://github.com/Automattic/woocommerce-payments/pull/3134

We might also want to remove the whole additionalMethodsSetup around [here](https://github.com/Automattic/woocommerce-payments/pull/2358/files#diff-dcc31bbf337cce3033cea17561d762d4e2511007a0f70c81bdf168a271727516R40). To double-check and update this description.

### PR DESCRIPTION
**Pull request by a-danae**
Fixes #3434

#### Changes proposed in this Pull Request

Remove an unused component and variables.

* Displaying the wizard to set up the UPE payment methods at `&path=%2Fpayments%2Fadditional-payment-methods`, even when UPE preview is disabled. There shouldn't be links or redirects taking the user to this page when the preview is disabled
* Deleting the `MethodsSelector` component that used to be displayed on this page when UPE preview was disabled
* Deleting the tests and variables that were only used by this component or by the removed task functionality

#### Testing instructions

Functional instructions:
* Make sure UPE is disabled. Disable it via WCPay Dev tools. If you do it via WCPay settings the admin note might not show up
* Make sure the UPE preview is enabled. It's enabled by default, but in case it's not, simply remove `wcpay_additional_methods_setup_completed` from wp_options
* Go to Payments -> Overview
* Find the admin note titled "Boost your sales by accepting new payment methods" and click on "Enable on your store"
* It should take you to the additional-payment-methods wizard at `&path=%2Fpayments%2Fadditional-payment-methods` and everything should continue to work as expected there
* Disable the UPE preview by setting `_wcpay_feature_upe_settings_preview` to '0' in wp_options. Looks like the notes are cached. Deactivating WCPay and activating it back prevents the note from persisting
* There shouldn't be links or redirects going to the additional-payment-methods wizard (it's probably simpler to check this in the code)
* If you go to `/admin.php?page=wc-admin&path=%2Fpayments%2Fadditional-payment-methods` directly, the wizard should still be there and it shouldn't error when you go through it

In the code:
* The variable `wcpaySettings.additionalMethodsSetup.isTaskVisible` that's localized to the JS files shouldn't exist or be used
* The variable `wcpaySettings.additionalMethodsSetup.isSetupCompleted` that's localized to the JS files shouldn't exist or be used
* The wp_option `wcpay_additional_methods_setup_completed` shouldn't be used anywhere
* The component `MethodsSelector` that used to be defined at `client/additional-methods-setup/methods-selector/index.js` shouldn't exist or be used, along with the code used only by it
* Ideally, there shouldn't be any code that's left unused as the result of the removal of the "Boost your sales by accepting new payment methods" task at https://github.com/Automattic/woocommerce-payments/pull/3134

-------------------

- [x] Added changelog entries to both `readme.txt` and `changelog.txt` (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply)

### CODE REVIEW

**Comment by leonardola** [comment]
If before the `Disable the UPE preview by setting wcpay_additional_methods_setup_completed to 'yes' in wp_options`
step I disable UPE on dev tools the `Boost your Sales` Note still shows up. Is this the expected behavior?
I tested this because even if I skipped the `Disable the UPE preview by setting wcpay_additional_methods_setup_completed to 'yes' in wp_options` step with the UPE enabled the `Boost your Sales` note would not show up.

Also the issue talks about the `_wcpay_feature_upe_settings_preview` option and I see no mention of it here. Maybe the option in `Disable the UPE preview by setting wcpay_additional_methods_setup_completed to 'yes' in wp_options` is wrong? Although `Boost your Sales` still shows up with `_wcpay_feature_upe_settings_preview` set to 0 and the and UPE disabled. It seems like it is not respecting both options. I am doing something wrong here?

**Comment by a-danae** [comment]
Thanks for checking this and sorry for the delay @leonardola!

> Also the issue talks about the _wcpay_feature_upe_settings_preview option and I see no mention of it here. Maybe the option in Disable the UPE preview by setting wcpay_additional_methods_setup_completed to 'yes' in wp_options is wrong?

Yep, it's wrong. More on this below.

> If before the Disable the UPE preview by setting wcpay_additional_methods_setup_completed to 'yes' in wp_options
step I disable UPE on dev tools the Boost your Sales Note still shows up. Is this the expected behavior?

I made a mistake in the instructions. The option we should add is `_wcpay_feature_upe_settings_preview` and set it to `0`. The notes seem to persist for some reason (cache maybe?), so, deactivate WCPay and activate it back. Then the note shouldn't show up anymore. I've updated the instructions with this.

That also refers to this behavior you mentioned:
> Although Boost your Sales still shows up with _wcpay_feature_upe_settings_preview set to 0 and the and UPE disabled. It seems like it is not respecting both options. I am doing something wrong here?

**Review by leonardola — APPROVED** [review]
> The variable wcpaySettings.additionalMethodsSetup.isSetupCompleted that's localized to the JS files shouldn't exist or be used

I think [this one](https://github.com/Automattic/woocommerce-payments/blob/develop/client/additional-methods-setup/upe-preview-methods-selector/test/setup-complete-task.test.js#L25) can also be removed.


Other than that, this can be merged. So I am approving this. 
Please remove the code if it really is not necessary for anything else and make sure the tests pass. After that you can go ahead and merge this

**Comment by a-danae** [comment]
Good catch. Updated and merging.

**Pull request merged**
