### PR TITLE
Fix fatal errors when subscription classes are not available

### PR DESCRIPTION
**Pull request by wjrosa**
#### Changes proposed in this Pull Request

Fixing fatal errors when subscription classes are not available

This PR fixes fatal errors thrown when subscription classes are not available. It includes a check for the existence of `store_has_active_wcpay_subscriptions` before calling it. Without it, the following fatal error is thrown:
```
2023-04-03T01:52:59+00:00 CRITICAL Uncaught Error: Call to undefined function wcs_get_subscriptions() in woocommerce-payments/includes/subscriptions/class-wc-payments-subscription-service.php:1029
Stack trace:
#0 woocommerce-payments/includes/subscriptions/class-wc-payments-subscriptions-plugin-notice-manager.php(63): WC_Payments_Subscription_Service::store_has_active_wcpay_subscriptions()
#1 wp-includes/class-wp-hook.php(308): WC_Payments_Subscriptions_Plugin_Notice_Manager->enqueue_scripts_and_styles('plugins.php')
#2 wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
```

#### Testing instructions

* Install WooCommerce Subscriptions
* Include an `exit;` before the declaration of `WC_Subscriptions`
* Activate the plugin (with Subscriptions Products / Orders)
* No fatal errors should be thrown with this change applied (in `develop` it would throw the fatal error above)

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8823` or branch name `fix/fatal-errors-when-subscriptions-are-unavailable` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/fatal-errors-when-subscriptions-are-unavailable) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: e20898ed090fdc0fd5a284cce14a4cd60d2ad126
- Build time: 2024-07-16 15:15:20 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by a-danae** [comment]
@wjrosa I'm just noticing this PR is still open. Since this change is in the WooPayments plugin, I'd suggest asking for a review from the teams that are more involved in it. I'd ask in Slack which team is the best one to assign as a reviewer.

**Comment by wjrosa** [comment]
> @wjrosa I'm just noticing this PR is still open. Since this change is in the WooPayments plugin, I'd suggest asking for a review from the teams that are more involved in it. I'd ask in Slack which team is the best one to assign as a reviewer.

thanks, Danae! I will do some digging to find out 👀

**Review by frosso — APPROVED** [review]
The changes look pretty straightforward and read well 👍

**Pull request merged**
