### PR TITLE
Set min width for ECE Google Pay button in blocks checkout

### PR DESCRIPTION
**Pull request by bborman22**
Fixes #

#### Changes proposed in this Pull Request

This was discovered during our exploratory Express Checkout Element (ECE) testing. When testing with Storefront theme with the sidebar enabled, the checkout blocks page becomes quite narrow. This narrowness combined with WC Core's `grid-template-columns` on the `.wc-block-components-express-payment__event-buttons` container lead to the spacing for the Google Pay button to be too small and automatically hidden by Stripe.

To account for this we determined the minimum width the Google Pay button needs to render (208px) and replaced the calculated minimum width on the `grid-template-columns` with this fixed minimum width. 

**This applies only to narrow checkout blocks pages (Storefront with sidebar enabled) and when more than 2 express checkout options are enabled.**

**Before**
CSS: `grid-template-columns: repeat(auto-fit, minmax(calc(33% - 10px), 1fr));`
When three or more items were present in the Express Checkout (i.e. WooPay, Google Pay, and PayPal) the 33% - 10px was not wide enough for Google Pay to render leading to this display:
Screenshot 2024-07-17 at 4 01 32 PM
When breaking below the media query breakpoint the CSS becomes `grid-template-columns: 1fr` and renders as a single column and all buttons:
Screenshot 2024-07-17 at 4 02 13 PM

**After**
CSS: `grid-template-columns: repeat( auto-fit, minmax( 208px, 1fr ) ) !important;`
The 208px is determined through experimentation and was found to be the minimum size that still renders the Google Pay button on ECE. This now leads to a single column list rendering like this:
Screenshot 2024-07-17 at 4 06 41 PM
When breaking below the media query breakpoint, there is a point where it goes into two columns before going back to a single column:
Screenshot 2024-07-17 at 4 07 42 PM

Here is what it looks like with the sidebar disabled which I think is a more common display:
Screenshot 2024-07-17 at 4 09 57 PM

With sidebar and just two buttons:
Screenshot 2024-07-17 at 4 11 20 PM

#### Testing instructions

Screenshot 2024-07-26 at 10 37 23 AM

* Have a store with the Storefront theme and a checkout blocks page with the sidebar enabled (see example screenshot above)
* Enable both WooPay and Google Pay / Apple Pay.
* In a browser where you will be presented with both options, add a product to cart and go to the checkout block page.
* Without this PR applied adjust the browser window width to get smaller until the Google Pay button disappears (like in the Before image above).
* Now with this PR applied repeat the same steps and confirm that the Google Pay button never disappears and instead bumps to a new row.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by bborman22** [comment]
@pierorocca @nikkivias @alexflorisca Since you've all been taking a look at Express Checkout button rendering recently I wanted to run this approach by you all and get some opinions. The problem should be laid out well in the PR description, but in short, Google Pay through Stripe ECE requires a minimum width to render or else Stripe hides it automatically. In some scenarios (narrow checkout) the grid calculations would prevent Google Pay from rendering. Our proposed solution is to adjust this minimum column width to allow Google Pay to render when using ECE.

@ricardo No need to review this PR yet, but wanted to confirm with you all that this matches what was discussed and that this is the right way to apply it. cc @rafaelzaleski FYI.

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9124` or branch name `fix/express-checkout-button-grid` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/express-checkout-button-grid) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: ca1c208e61670479dd995e028a29a73fe232b6ff
- Build time: 2024-07-26 14:43:39 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by pierorocca** [comment]
Looks good to me @bborman22. Awesome catch during the test exploration.  Your solution looks aligned with the current design guidelines. 

@danielvann777 you provided a perspective on the existing design choice to left align the lone button. We could instead center align here as we finalize this migration effort. If we were to make a change, this would be great timing if the design team thinks this change is warranted.

FYI @nikkivias  

FYI the WooPay font size is being increased in a different PR/Issue. Here it's smaller than desired.

image

**Comment by ricardo** [comment]
> @ricardo No need to review this PR yet, but wanted to confirm with you all that this matches what was discussed and that this is the right way to apply it.

@bborman22 Yes, it matches, but for me the Google Pay button is hidden when the container width is below `232px`, can you confirm if it's the same for you? See below:

https://github.com/user-attachments/assets/5efa4049-5ea2-4426-8bf1-e86b8ef346ee

**Comment by alexflorisca** [comment]
Hey @bborman22  thank for this work, but I've already got a PR up for addressing this (https://github.com/woocommerce/woocommerce/pull/49304). In my testing, the button needed 240px of space so that's what I gave it. There seems to be a bit of variation on this reading the comments above, I say we go with the largest of them to be sure.

**Comment by pierorocca** [comment]
Hey Alex does that hold up for translated buttons?

**Comment by bborman22** [comment]
Sorry for the delay here, @alexflorisca given ECE will be releasing with WooPayments 8.0 on July 31st should we include this fix as a temporary solution until the WC Core fix is in? This way the buttons don't get hidden during that gap? And I agree on going with the largest of our results which seems to be 240px as you said!

**Review by rafaelzaleski — APPROVED** [review]
Great job! LGTM!

**Comment by alexflorisca** [comment]
Sure thing

**Comment by danielvann777** [comment]
> @danielvann777 you provided a perspective on the existing design choice to left align the lone button. We could instead center align here as we finalize this migration effort. If we were to make a change, this would be great timing if the design team thinks this change is warranted.

Sorry for the lateness here @pierorocca. I would ask Nikki for the final say here since she probably knows all the permutations here but it does feel like a centered version would feel better in balancing the three buttons.

**Comment by nikivias** [comment]
@pierorocca for 3 buttons, would it be okay if the first button were to be full width, while the remaining 2 split the space at the bottom? I ask "would it be ok" because this layout gives preference to first button, and I'm not sure if they can currently assign the order of buttons.

Checkout-3-buttons

**Comment by pierorocca** [comment]
On WooPayments the most buttons that can dispaly currently is 3 so it works well as WooPay would be at the top.

If we add other buttons in the future, there's a chance that Apple or Google or other brands could be placed more favorably than another competing brand. Technically, that violates their usage guidelines. For our own brand, I'm willing to go there.  To put Amazon pay more prominently than Google or Google over Apple or any other combo, that's tricky especially if we have any sort of incentive agreements or partnerships in place.

**Comment by alexflorisca** [comment]
Again pointing out that this is pretty difficult to achieve as we don't know the number of payment extensions installed on a merchant's website, and the number of express payment methods that will be displayed. Our grid currently treats each of those equally and adds / removes grid items as payment methods are activated / deactivated. This layout _may be_ possible with some client side logic to detect the WooPay button, place it first and make it take up two spaces in the grid instead of one. But it won't be possible to do this generically.

**Comment by danielvann777** [comment]
So I can see two solutions here: one where every button gets a similar treatment (I think that's what competitors do) or we prioritize one, Woo Payments. Regardless, we need to find an elegant solution when it scales and I'm mocking up here an idea. I've tried adding a mockup here of my logic:

Mockup of logic

**Pull request merged**
