### PR TITLE
Fix keyboard navigation for account balance tooltips

### LINKED ISSUE #6053: Simplify deposit UI - navigate tooltip using keyboard tab
Tooltips from https://github.com/Automattic/woocommerce-payments/issues/5724 should be accessible using keyboard tab.

This is a feedback from @elizaan36: pdjTHR-2u8-p2#comment-3243

### PR DESCRIPTION
**Pull request by Jinksi**
Fixes #6053

#### Changes proposed in this Pull Request

This PR fixes the tab-based keyboard navigation for the **Payments → Overview** account balance tooltips.

The `TooltipBase` component has been updated to accept a `parentElement` prop that replaces the `rootElement` variable, which now allows a custom parent element for rendering the tooltip content within. All instances of `ClickTooltip` will pass in a custom parent element to `TooltipBase` that ensures the `tabIndex` of the rendered tooltip content will be able to be tabbed to directly after focusing on the tooltip button element.

The following screen recording demonstrates navigating the account balance tooltips + content via keyboard, using `Tab`/`Shift+Tab`:

https://github.com/Automattic/woocommerce-payments/assets/3147296/0458119c-f77f-43dc-9709-76c8d636f69b

#### Testing instructions

* Visit **Payments → Overview**
* Use the `Tab` key to navigate to each account balance tooltip.
* Pressing the `Enter` key should hide/show each tooltip.
* If a tooltip is visible, using the `Tab` key should focus on any link element present within.
* Ensure tooltip interaction via click and touch (mobile) is not affected.
  * **Note** I've fixed a bug on mobile safari that was introduced by this PR: [comment below](https://github.com/Automattic/woocommerce-payments/pull/6252#issuecomment-1543245775).

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6252` or branch name `fix/6053-overview-deposit-tooltip-keyboard-navigation` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=fix/6053-overview-deposit-tooltip-keyboard-navigation) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 5775e2ead4b25d41e4b505bcb4e33d59f2f5009a
- Build time: 2023-05-14 17:43:26 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by Jinksi** [comment]
**Update on progress**

I have keyboard navigation working for the icon elements.

I'm figuring out a suitable way to ensure tab-based navigation works for any link elements within the tooltip that appears:

https://user-images.githubusercontent.com/3147296/236982563-3443efc3-1d24-42ef-a08d-2671623c6498.mov

**Comment by Jinksi** [comment]
Unfortunately I've noticed that the tooltip's rendered position is inaccurate on mobile safari. Next step is to see if this PR has introduced this bug (likely) and either fix in this PR or open an issue.

**Update**
Fixed in c00a140.

image

**Comment by Jinksi** [comment]
Note to reviewer. If approved, feel free to merge this PR to make it into the next WCPay code freeze 🚤

**Review by shendy-a8c — APPROVED** [review]
Function well. Code diff looks good.

Nice work, @Jinksi! So many `til`s for me like tab index, ref (and `useRef`), how to unit-test clicking tab, etc.

Approving and merging...

**Pull request merged**
