### PR TITLE
Make experiment Payments task onboarding flow treatment final

### LINKED ISSUE #9540: Make experiment Payments task onboarding flow treatment final
### Description

After the successful completion of our experiment (pbxNRc-48S-p2#comment-6100) we need to make the treatment variation final. This means that all onboardings originating from the payments task will skip the Connect page and jump straight to MOX (with the possible interim Jetpack connection setup)

### Acceptance criteria

* All onboardings originating from the payments task will skip the Connect page and jump straight to MOX (with the possible interim Jetpack connection setup).
* The code added for the experiment is removed ([experiment PR](https://github.com/Automattic/woocommerce-payments/pull/9383)).

### Additional context
pbxNRc-48S-p2
https://github.com/woocommerce/woocommerce/pull/51956

### PR DESCRIPTION
**Pull request by vladolaru**
Fixes #9540 

#### Changes proposed in this Pull Request

All onboardings originating from the WooCommerce payments task(s) skip the WooPayments Connect page and go directly to the MOX for live account onboarding. If there isn't a site WPCOM/Jetpack connection, go to the WPCOM/Jetpack connection and then redirect to the MOX.

#### Testing instructions - WooCommerce 9.3.x

1. Create a new Jurassic Ninja site with latest WooCommerce and _without_ WooPayments (here is a [direct JN create link](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce))
1. Go through the WooCommerce core profiler by clicking on the `WooCommerce` main menu item (if it doesn't start automatically), skip it by clicking "Skip guided setup" in the upper right corner, and select 'US' as your store's location
1. Go to `Plugins` and **install** WooPayments from either a locally built zip of this PR's branch or you can download it from here: [woocommerce-payments.zip](https://github.com/user-attachments/files/17309752/woocommerce-payments.zip). Don't activate WooPayments.
1. Go to the `Payments` main menu item and dismiss the incentive by clicking on "No thanks", then on "Just dismiss WooPayments" in the modal.
1. Go to `WooCommerce > Home` and click on the "Get paid with WooPayments" task. 
1. After WooPayments is activated, you  will be redirected to set up your site's WPCOM/Jetpack connection - accept your connection.
1. After you've connected your site to WPCOM you should be redirected straight into the WooPayments MOX:
Screenshot 2024-10-09 at 17 27 55
1. Exit the MOX by clicking on "Cancel" in the upper right corner
1. Go to `Plugins` and deactivate WooPayments
1. Go to `Plugins > Add new`, search from "stripe" and install and activate the [WooCommerce Stripe Payment Gateway](https://wordpress.org/plugins/woocommerce-gateway-stripe/) extension 
1. Go to `WooCommerce > Settings > Payments` and click on "Finish setup" for the Stripe payment gateway. Then click on "Create or connect a test account instead" to set up the gateway - finish the Stripe KYC.
1. Go to `WooCommerce > Home` and you should see a "Get paid" task that is completed (striked out).
1. In the "Things to do next" task list you should see a "Set up additional payments options" task. Click on it and you should see the Payments task page with WooPayments at the top.
Screenshot 2024-10-09 at 17 35 37
1. Click on "Get started" and you should see the installation/activation stepper:
Screenshot 2024-10-09 at 17 36 33
1. Click on "Connect" and you should be redirected to the MOX.

#### Testing instructions - WooCommerce trunk

1. Create a new Jurassic Ninja site with just WooCommerce using the latest `trunk` (here is a [direct JN create link](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce=trunk))
1. Go through the WooCommerce core profiler by clicking on the "WooCommerce" main menu item (if it doesn't start automatically) and select 'US' as your store's location
1. Go to `Plugins` and **install** WooPayments from either a locally built zip of this PR's branch or you can download it from here: [woocommerce-payments.zip](https://github.com/user-attachments/files/17309752/woocommerce-payments.zip). Don't activate WooPayments.
1. Go to the `Payments` main menu item and dismiss the incentive by clicking on "No thanks", then on "Just dismiss WooPayments" in the modal.
1. Go to `WooCommerce > Home` and click on the "Get paid with WooPayments" task. 
1. You should see the install/activation stepper
Screenshot 2024-10-09 at 17 49 24
1. Click on "Connect" and you should be redirected to the WPCOM/Jetpack connection setup flow - accept your connection.
1. After you've connected your site to WPCOM you should be redirected straight into the WooPayments MOX:
Screenshot 2024-10-09 at 17 27 55
1. Exit the MOX by clicking on "Cancel" in the upper right corner
1. Go to `Plugins` and **deactivate** WooPayments
1. Go to the Payments main menu item and then click on "Get started" for WooPayments:
Screenshot 2024-10-09 at 17 52 43
1. You should see the install/activation stepper
Screenshot 2024-10-09 at 17 49 24
1. Click on "Connect" and you should be redirected to the MOX.

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9541` or branch name `update/9540-payment-task-onboarding-flow` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=update/9540-payment-task-onboarding-flow) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 8fe9c34fd09a42d6044aaae9e08e169ad0289306
- Build time: 2024-10-09 15:00:44 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by oaratovskyi — APPROVED** [review]
@vladolaru thanks for removing the experiment!
Everything works well, just one small thing: on the step 14 (Woocommerce 9.3.3) this snackbar notice is duplicated. Is this expected?
image

Pre-approving since everything else works well and the code looks good.

**Comment by vladolaru** [comment]
Thank you for reviewing this, @oleks! The double snackbar notice is expected with WooCommerce 9.3.3 since I've [fixed it recently](https://github.com/woocommerce/woocommerce/pull/51956) and it is now in `trunk`.

**Comment by oleks** [comment]
> Thank you for reviewing this, @oleks!

I think you got the wrong handle :wink:

**Comment by vladolaru** [comment]
Definitely the wrong handle, @oleks 😅 But nice to meet you. I didn't think for a moment and used my colleague's short name, Oleks (his handle is @oaratovskyi). Sorry for the unnecessary ping.

**Pull request merged**
