### PR TITLE
Match the Node version in nvm with the minimum version in package.json

### PR DESCRIPTION
**Pull request by anu-rock**
#### Changes proposed in this Pull Request

Node version in our plugin was recently upgraded from 16 to 20 in #9121. nvm was configured to use any v20 release. This is out of sync with the minimum version specified in `package.json` - 20.11 - which may cause issues for someone with 20 < v < 20.11 installed. This PR brings the nvm version in sync with the one in package.json.

#### Testing instructions

* All tests are passing.

Without this change:

* Install any node v20 release before 20.11 locally.
* In the root of the repo, run `nvm use`. This will pick up your local v20 installation.
* Run `npm install`. It will fail saying you do not need the minimum node version.

With this change:

* Install any node v20 release before 20.11 locally.
* In the root of the repo, run `nvm use`. You will be prompted to install a newer node version. Go ahead with it.
* Running `npm install` will succeed.

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9190` or branch name `update/nvm-node-version` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=update/nvm-node-version) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 450d08461d6b6a68589710f2409464d36b954ba1
- Build time: 2024-07-30 13:19:52 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by danielmx-dev — APPROVED** [review]
Looks good!

**Comment by shendy-a8c** [comment]
I had this problem the other day. Was thinking to create a PR with exactly the same change (my locally installed node was also 20.11) but decided not to because the [readme](https://github.com/Automattic/woocommerce-payments?tab=readme-ov-file#install-dependencies--build) clearly states to run `nvm install` which will install the latest v20 (currently 20.16).

**Comment by anu-rock** [comment]
@shendy-a8c Interesting. Thanks for highlighting this tidbit. I always start with `nvm use` by habit. I think this habit comes from reading the docs of other projects. I suspect others might fall into this trap.

**Pull request merged**
