### PR TITLE
Show UTC label in date time column header of transactions CSV

### LINKED ISSUE #8522: CSV exports have date/time in UTC, not clear to merchant (vs. localised timezone) (all – e.g. Transactions, Disputes, Deposits)
### Describe the bug

When exporting a CSV of Transactions, Disputes, or Deposits, the date time columns are shown in UTC but this is not communicated.

Times are shown in local time when viewing the transactions, disputes, or deposits pages. For both the plugin and server-generated CSV exports, UTC is used.

A simple fix would be to label the column in the CSV exports as UTC.

### To Reproduce

1. Go to Payments > Transactions
2. See dates/times in local time.
3. Download as a CSV
4. See dates/times in UTC.

### PR DESCRIPTION
**Pull request by shendy-a8c**
Fixes https://github.com/Automattic/woocommerce-payments/issues/8522

Fixes https://github.com/Automattic/woocommerce-payments-server/issues/2847

I had a hard time digesting the problem here so summarizing it here:
- There are 3 timezones at play here: browser's timezone (in my case UTC+7), store's timezone (set at General > Settings > Timezone), and server's (UTC).
- The behavior on base branch is as follow:
  - I'll use an example of a transaction I created at `2024-09-19 06:11` in my local time (UTC+7).
  - I set my store's timezone to be UTC+1.
  - On server, transaction time is stored as UTC, `2024-09-18 23:11`.
  - When plugin fetches the transaction from server, it will receive the time in UTC.
  - [This Javascript code shows the time in store's locale](https://github.com/Automattic/woocommerce-payments/blob/c83f5de040a7b846bb5f15ac87009b98bf9cae44/client/transactions/list/index.tsx#L467-L470), ie in store's timezone. Read [`dateI18n`'s description](https://github.com/WordPress/gutenberg/blob/trunk/packages/date/src/index.js#L523). Therefore, I see the transaction time on the Transactions list page as `2024-09-19 00:11`.
  - I can download CSV in 2 different ways based on the length of data.
    - If it's just one page, I will download the CSV right away. This is called 'browser' download. The times displayed in the CSV are in UTC.
    - Otherwise, the server will email me the CSV file. This is called 'endpoint' download. The times displayed in the CSV are in UTC.

Problem:
- When I 'browser' download, in the CSV, the header says `Date / Time` and it's not clear what the timezone is.
- The header on transaction list page is `Date / Time` and it's not clear what the timezone is. *This is not within the scope of this PR*. Created a separate issue: https://github.com/Automattic/woocommerce-payments/issues/9472.

#### Changes proposed in this Pull Request

- Since times in CSV are in UTC, add `(UTC)` to the date time column header. Apply the same for blocked transactions. This PR will add UTC for 'browser' download only because CSV from 'endpoint' download already has UTC in the Date / Time header.

Screenshot 2024-09-19 at 03 56 36

I do not add UTC to the other list pages (deposits and disputes) because they are showing dates only (without time).

#### Testing instructions

* Set your blog's timezone to non-UTC. Go to wp-admin > Settings > General > Timezone.
* `npm run build:client`.
* Go to wp-admin > Payments > Transactions. Click download.

* Go to wp-admin > Payments > Transactions > Blocked. Click download. I don't have any blocked transactions, so the download button does not appear for me.

* Test the 2 types of download: from browser and from server.
  - Modify this [line](https://github.com/Automattic/woocommerce-payments/blob/542e27f93037c23007799c7b9b020b12e7c84a93/client/transactions/list/index.tsx#L720).

To force it using the `browser` method:
```
const downloadType = 1 > rows.length ? 'endpoint' : 'browser';
```

To force it using the `endpoint` method:
```
const downloadType = 1000000 > rows.length ? 'endpoint' : 'browser';
```

Confirm that the date time header column is `Date / Time (UTC)`. For CSV coming from server, if no email arrives at your inbox, check the mail logger installed in your local server WordPress.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9461` or branch name `add/8522-utc-list-page-csv` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=add/8522-utc-list-page-csv) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 0eea6286e2568cfe72a06d78cc559355a05e70fa
- Build time: 2024-09-23 10:47:26 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by shendy-a8c** [comment]
As I am working on this PR, I found a bug. Created here: https://github.com/Automattic/woocommerce-payments/issues/9471.

**Review by nagpai — APPROVED** [review]
The changes look fine and test well for the Transactions report. 

I was unable to test the blocked tab, since I am unable to add transactions there. 

I am approving the PR but it would be good to have one more review.

**Review by haszari — APPROVED** [review]
Approving, as this is a surgical small change that will make the CSVs more consistent and correct – the CSVs are always UTC, so should be labelled as such.

> I do not add UTC to the other list pages (deposits and disputes) because they are showing dates only (without time).

We'll need follow up here, because dates can also be affected by timezone. e.g. `Disputed at` column shows date only but the stored value includes a time, and the date can shift in the UI depending on the WordPress (view) timezone.

In the example below, the transaction / dispute date is 24 Sept, but renders as 23 Sept for some timezones.

Screenshot 2024-09-24 at 2 27 55 PM
Screenshot 2024-09-24 at 2 27 26 PM
Screenshot 2024-09-24 at 2 25 50 PM

### Bigger picture – we need to audit how we display dates & times
I got a little bit rabbit holed reviewing this PR and trying to understand what the correct behaviour is – i.e. what we designed.

I think we need to review the various screens with dates/times and audit if they are displayed as UTC, or localised using WordPress timezone (or something else). 

Then we can either…

- (a) Confirm the intended design and fix any discrepancies.
- **OR**
- (b) Refine the design so its consistent, and then fix discrepancies.

I don't think we can fix these bugs in isolation without confirming the intended design. Getting clarity on this might also help with the payment activity card on overview screen.

I had been assuming that we could go with (b) and use UTC everywhere, but I see there are lots of places in the UI where we adjust to WordPress timezone. As noted by @souravdebnath1986 ideally we'd [show all times/dates in store timezone](https://github.com/Automattic/woocommerce-payments/issues/9135#issuecomment-2238159785) (this could be interpreted as WordPress site timezone).

Here are the issues & PRs I found in my research:

##### open issues
- https://github.com/Automattic/woocommerce-payments/issues/8522
- https://github.com/Automattic/woocommerce-payments-server/issues/2847
- https://github.com/Automattic/woocommerce-payments-server/issues/4845
- https://github.com/Automattic/woocommerce-payments/issues/9472
- https://github.com/Automattic/woocommerce-payments/issues/9135 - timeline view, `focus: payments acceptance & processing` - not `reporting`
#### merged PRs / closed issues
- https://github.com/Automattic/woocommerce-payments/pull/9162
- https://github.com/Automattic/woocommerce-payments/pull/4711
- https://github.com/Automattic/woocommerce-payments-server/issues/2275

**Comment by nagpai** [comment]
>We'll need follow up here, because dates can also be affected by timezone. e.g. Disputed at column shows date only but the stored value includes a time, and the date can shift in the UI depending on the WordPress (view) timezone.

Created two followup issues with basic details here:

https://github.com/Automattic/woocommerce-payments/issues/9485
https://github.com/Automattic/woocommerce-payments/issues/9484

**Pull request merged**
