### PR TITLE
Ensure shipping is re-added after payment request is aborted

### LINKED ISSUE #8097: Shipping is removed if quanity increased after Payment Request has been initialized
### Describe the bug

On simple products, when clicking the Google Pay button the first time, shipping costs are added and appear in the itemized costs inside the popup. When closing the popup and increasing the quantity, then click the Google Pay button again, shipping isn't re-added and doesn't appear in the list. 

### To Reproduce

1. Enabled Payment Requests
2. Add a shipping method
3. Navigate to a product and attempt to checkout via Google Pay, confirming that shipping appears in the order details inside the popup
4. Close the popup
5. Increase the product quantity
6. Click the Google Pay button once more and notice that shipping no longer appears in the order details

### Screenshots

First time, with shipping

image

Next, without shipping

image

### Expected behavior

Shipping should be recalculated and added when increasing product quantity after opening and closing the Google Pay popup.

### Additional context

The Payment Request API emits a `onshippingaddresschange` event that is fired when the shipping address changes inside the popup. The event is emitted on initialization as well but no when closing the popup and changing product quantity, since the Google Pay shipping address has not changed. Variable products get around this by re-initializing the Payment Request which is likely what needs to happen here.

### PR DESCRIPTION
**Pull request by mdmoore**
Fixes #8097 

#### Changes proposed in this Pull Request

The solution in this PR currently is to re-initialize the payment request if a previous payment request has been aborted and the product quantity has changed. This is similar to how the same problem is handled with switching variations after an aborted payment request.

The reason that shipping isn't re-added when adjusting quantity after an aborted payment request comes down to the payment request update that is performed using data from `get_selected_product_data()`. Here the shipping item isn't calculated and `pending` is set to `true`, which tells the payment sheet to not display this item. 

https://github.com/Automattic/woocommerce-payments/blob/c4f63dba07b17a92a4c309ba1c21e0b3e1d6996b/includes/class-wc-payments-payment-request-button-handler.php#L1023-L1036

#### Testing instructions

1. Enabled Payment Requests
2. Add a shipping method that calculates dynamically, such as a flat rate with a value of `[fee percent="10"]`.
3. Navigate to a product and attempt to checkout via Google Pay, confirming that shipping appears in the order details inside the payment request sheet
4. Close the sheet
5. Increase the product quantity
6. Click the Google Pay button once more and check that shipping still appears and the cost is correct

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8109` or branch name `8097/payment-request-update-shipping-on-quantity-change` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=8097/payment-request-update-shipping-on-quantity-change) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 284f9d62576e0bcde140268866b6c79698230e68
- Build time: 2024-02-13 21:16:07 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by gpressutto5 — COMMENTED** [review]
I'm getting this weird behavior, can you reproduce it?

google-pay

**Comment by mdmoore** [comment]
>I'm getting this weird behavior, can you reproduce it?

@gpressutto5 I can. Nice catch! Turns out this was due to a check I added in an attempt to keep the button from re-rendering up re-initialization. I reverted that check in https://github.com/Automattic/woocommerce-payments/pull/8109/commits/284f9d62576e0bcde140268866b6c79698230e68 and the shipping options/rates are correctly updated now upon re-initialization. Let me know if it's working better now!

**Review by gpressutto5 — APPROVED** [review]
This PR fixes the issue for Google Pay. Apple Pay did not have the same problem and keeps working as before.

**Pull request merged**
