### PR TITLE
[WIP] Tweak/6914 enhance design of bnpl payment methods status

### PR DESCRIPTION
**Pull request by mgascam**
Fixes #

#### Testing instructions

*

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7068` or branch name `tweak/6914-enhance-design-of-bnpl-payment-methods-status` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=tweak/6914-enhance-design-of-bnpl-payment-methods-status) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 8c149bc9782b6448b9430d879c8b6c7c8ad0c1d2
- Build time: 2023-09-28 09:55:51 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by kalessil** [comment]
@mgascam: can we add the PR somehow to ZH board (perhaps by linking the ticket and adding the ticket to the board)? Currently, this PR is hanging in limbo.

**Comment by mgascam** [comment]
> @mgascam: can we add the PR somehow to ZH board (perhaps by linking the ticket and adding the ticket to the board)? Currently, this PR is hanging in limbo.

Thanks @kalessil I added it to the sprint and assigned to me and now it shows in the ZH board. It's a bit weird that it wasn't showing because I already linked the issue, maybe because it's a draft.

**Comment by mgascam** [comment]
Discarding this draft in favor of https://github.com/Automattic/woocommerce-payments/pull/7406

**Pull request closed without merging**
