### PR TITLE
Prepare for 1.7.0 release

### LINKED ISSUE #1113: Release 1.7.0

### PR DESCRIPTION
**Pull request by marcinbot**
Fixes #1113 

#### Changes proposed in this Pull Request

* Bump the version number and fill the dates on the changelog

#### Testing instructions

* Confirm the changes look good

### CODE REVIEW

**Comment by allendav** [comment]
Tests fine on my own site. Would love one more set of eyes before merge?

**Review by vbelolapotkov — APPROVED** [review]
LGTM! :shipit: once travis is happy :)

**Comment by allendav** [comment]
Travis failed due to `Error: Cannot find module 'puppeteer'`

I verified I was running the latest npm (6.14.8)

I removed the node_modules and re-ran npm install and npm run build

I noticed the package-lock changes (things had been rearranged substantially for modules related to puppeteer) were now minimized. I checked in the minor package lock change in https://github.com/Automattic/woocommerce-payments/pull/1088/commits/39eeb8a08e9e96ebb79e1b3e7b06e93fdcd6f881

**Comment by allendav** [comment]
Not going to wait for E2E tests to finish because the package change is covered by non E2E tests.

**Pull request merged**
