### PR TITLE
Ensure gateway functionality for disabled payment method

### LINKED ISSUE #8058: UPE: compatibility with refunds (a case with disabled payment methods)
### Describe the bug

In the latest UPE variations, if a payment method is disabled on the settings page, refunds for orders made with that payment method are broken.

Broken in 2 ways:
- refunds from transaction details page: error, painting to the disabled gateway
- refunds from the order page: no errors, but gateway not requesting refunds via processor

### To Reproduce

- Place an order with a payment method (non-card)
- Disable the payment method in the setting
- Try refunding the order from the transaction and order pages

### Expected behavior

- Refunds via transaction and order pages are performed (incl. refund request on the processor side)

### Additional context

paJDYF-bPM-p2 and see also accepted comment as guideline to fix.

### PR DESCRIPTION
**Pull request by timur27**
Closes https://github.com/Automattic/woocommerce-payments/issues/8058

#### Problem background
According to https://github.com/Automattic/woocommerce-payments/issues/8058, transactions made with payment methods that were disabled when trying to refund cannot be refunded. This issue arises because WooPayments only registers payment gateways enabled for checkout, whereas WooCommerce Core requires all gateways, including those not enabled for checkout, to be registered. This impacts refunds, among other things. 

Fortunately, there is an `enabled` property in the gateway class that allows a gateway to be enabled or disabled at checkout while remaining registered in the system for other uses, such as refunds. Currently, WooPayments does not utilize this property, and this PR aims to address that.

To address the issue, we need to:

1. Register all payment gateways in WooCommerce Core, not just the ones that are enabled at checkout.
2. Ensure the enabled property accurately indicates whether a gateway is active and can be used at checkout.

Step 2 can be tackled in various ways. The simplest solution was chosen, prioritizing ease of maintenance and minimizing risks. Below is a short analysis of two options, which is optional for reading but can be helpful in case you're curious. 2️⃣ was eventually chosen.

To ensure the enabled property accurately indicates whether a gateway is active we could: 

1️⃣ Re-visit the structure of the `woocommerce_woocommerce_payments_settings` option in the database, which currently has the list of `upe_enabled_payment_method_ids` and the single `enabled` property. The single settings object is used by all gateways, meaning that the `enabled` property can't cover values for separate gateways. There are multiple options to improve this (for example, by replacing `upe_enabled_payment_method_ids` with `payment_methods` and adding the enabled value as a key for every payment method or using separate settings object for every gateway) but all options will require two more things: modify the reading part to accommodate the new structure and implement migration scripts to ensure stores don't lose the state of enabled gateways after the update. 

2️⃣ Leverage the existing `upe_enabled_payment_method_ids` array in the settings, and, while reading from settings (during the gateway initialization step), decide if the gateway is enabled by checking if enabled IDs list contains the gateway's ID. The advantages of such an approach are it's less complex due to way fewer changes, it doesn't require any migration, and it doesn't add complexity to using `wp_options` in WooPayments.

#### Testing instructions

1. Place order with any payment method except card (because it cannot be disabled for testing purposes)
2. After the successful order, navigate to payment settings and disable the payment method used in (1)
3. Navigate to order details -> click payment intent details and you will be redirected to transaction details page
4. In the top right corner, click `Refund in full`, confirm no errors appeared and the payment was refunded, navigate to Stripe Dashboard and confirm the refund was captured there as well
5. Perform steps 1-4, but this time click `Partial refund` instead of `Refund in full`. Partial refund will navigate you to the order details page.
6. After successful step 5, perform steps 1-4 but attempt the full refund from the order page.
7. Access `WooCommerce -> Settings -> Payments`, and toggle the WooPayments option. Save your changes. Refresh the page and confirm the setting is applied correctly, showing it as enabled or disabled.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8216` or branch name `fix/refunds-with-pms-disabled-on-checkout` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/refunds-with-pms-disabled-on-checkout) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 4a26a8c100984872d376de438fc3bb7599d13c24
- Build time: 2024-02-28 14:03:15 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by timur27** [comment]
Hey @Automattic/pulsar! Sorry for the team ping, would anyone be so kind as to help us testing out if refunds are working well, as discussed in https://github.com/Automattic/woocommerce-payments/issues/8058#issuecomment-1928961884? Thanks in advance 🙏

**Review by gpressutto5 — CHANGES_REQUESTED** [review]
The refunds are working fine, but it broke something in the checkout I can't use any UPE method to pay and the billing country filter is not working properly:

**develop:**
image

**fix/refunds-with-pms-disabled-on-checkout:**
image

**Comment by timur27** [comment]
@gpressutto5 the first iteration of this implementation used a broader filter that didn't check the currencies and some other things, thanks for catching this! There's the updated solution now, may I ask you for another review & testing round of steps from the description and currency/country filters tests you performed previously? Thanks!

#### Description of the problem and solutions' analysis (please read at your leisure, this is not a must-read)

Instead of `get_upe_enabled_payment_method_ids()`, the more restrictive filtering logic should be applied which is implemented in `get_payment_method_ids_enabled_at_checkout()`. 

The problem is that the state checked within `get_payment_method_ids_enabled_at_checkout()` is not ready at the moment of gateway initialization, currency is not ready yet and not sure if anything else. This means that the initial approach should be updated. One option was to run `init_settings()` once more when registering gateways, but this option wasn't clean enough and also led to some fundamental fatals, that's why I didn't invest time into it and checked other two options. 

Another option is to add a hook to [the `woocommerce_available_payment_gateways` filter](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-payment-gateways.php#L333), which is supposed to allow plugins dynamically filter out payment methods (e.g by currencies or countries like in our case). We would run it as part of plugin WooPayments `init()` which runs after `plugins_loaded`. The small downside of this was that introducing a new hook always increases a risk of creating more dependencies or breaking something else. That's why I looked at other options. 

The final option and the one I chose was to extend the `is_available()` logic which is [executed by Woo Core](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-payment-gateways.php#L324) to establish the list of "enabled" payment methods. I noticed that [this method implementation](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payment-gateway-wcpay.php#L781-L791) already includes some business logic, and adding new rules there also means no changes to plugin initialization/hooks. 

While I hope it's clear now what's the current approach is, one thing remains unanswered: what to do with the `enabled` flag? Basically, I've found a few areas to improve with this flag which are unrelated to this PR and I'm planning to initiate discussions on this separately.

**Review by gpressutto5 — APPROVED** [review]

**Pull request merged**
