### PR TITLE
Fix translation strings domain

### LINKED ISSUE #1429: Spike - Audit WC Pay for missing translation strings
We need to audit the WC Pay extension for missing translation strings so that we can ensure we have total coverage for our language packs.

Hints and resources:
- Guide to being localization ready: PCYsg-3AU-p2

Deliverables:
- [GitHub issue](https://github.com/Automattic/woocommerce-payments/issues/new) detailing the translation strings that need to be implemented

### PR DESCRIPTION
**Pull request by diegocurbelo**
Fixes #1429

#### Changes proposed in this Pull Request

This PR corrects (or adds) the domain 'woocommerce-payments' for all i18n translation strings

#### Testing instructions

* N/A

-------------------

- [ ] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

### CODE REVIEW

**Comment by v18** [comment]
> This PR corrects (or adds) the domain 'woocommerce-payments' for all i18n translation strings

@diegocurbelo does this mean there aren't any strings in the extension that aren't being translated using `__` etc?

**Comment by diegocurbelo** [comment]
> > This PR corrects (or adds) the domain 'woocommerce-payments' for all i18n translation strings
> 
> @diegocurbelo does this mean there aren't any strings in the extension that aren't being translated using `__` etc?

Correct,Correct, I couldn't find any text that doesn't use `__`

**Comment by dechov** [comment]
@diegocurbelo Nice – found just a couple more: https://github.com/Automattic/woocommerce-payments/blob/e1da77811acfc3488ffef85c0a777f81a93807a6/client/disputes/evidence/index.js#L496 https://github.com/Automattic/woocommerce-payments/blob/e1da77811acfc3488ffef85c0a777f81a93807a6/client/payment-details/timeline/map-events.js#L197

**Comment by diegocurbelo** [comment]
> @diegocurbelo Nice – found just a couple more:
> 
> https://github.com/Automattic/woocommerce-payments/blob/e1da77811acfc3488ffef85c0a777f81a93807a6/client/disputes/evidence/index.js#L496
> 
> https://github.com/Automattic/woocommerce-payments/blob/e1da77811acfc3488ffef85c0a777f81a93807a6/client/payment-details/timeline/map-events.js#L197

@dechov Good catch!

**Comment by dechov** [comment]
@diegocurbelo Just found some `wpoocommerce-payments`, `woocomerce-payments`, and `woocommmerce-payments` as well. I don't suppose there's a way to get a list of all textdomains used in the code?

**Comment by dechov** [comment]
@diegocurbelo Sounds good. I did try some regexes and that's how I found those, but it probably wasn't too comprehensive and didn't span multiple lines.

**Comment by diegocurbelo** [comment]
> @diegocurbelo Sounds good. I did try some regexes and that's how I found those, but it probably wasn't too comprehensive and didn't span multiple lines.

@dechov Used `'w(?!oocommerce-payments).*?'` to do and additional review (550 matches)

I'm going to look at the `checkdomain` grunt task, it's for php files.. maybe we can tweak it to work with js, or implement it using just js, so we don't need to add Grunt to the toolchain... but I'll do that in another PR so we can merge this translation fixes

**Review by dechov — APPROVED** [review]
LGTM – didn't run all of the affected code myself but changes look perfect based on careful inspection.

**Pull request merged**
