### PR TITLE
Fix FedEx shipping multi-currency rates

### LINKED ISSUE #10022: [MCCY] Incorrect shipping amount conversion in the Woo FedEx Extension
### Describe the bug
When adding a shippable product to the cart with the store currency set to USD, the shipping option `FedEx Ground Home Delivery` shows a cost of approximately $40. However, when the shopper switches the currency to JPY using the currency switcher, the same shipping option is displayed as 11,000 JPY. According to the WooPayments conversion rate (1 USD = 142 JPY), the correct converted amount should be approximately 5,680 JPY (~$40 USD), but the system is calculating it closer to 77 USD.

### To Reproduce
Instructions to set up the extension: https://github.com/Automattic/woocommerce-payments/pull/3131

1. Set the store currency to USD.
2. Add a shippable product to the cart.
3. Observe the `FedEx Ground Home Delivery` shipping cost in USD.
4. Switch the store currency to JPY using the currency switcher.
5. Observe the `FedEx Ground Home Delivery` shipping cost in JPY.

### Screenshots
Screenshot 2024-09-11 at 16 58 18
Screenshot 2024-09-11 at 16 58 03
Screenshot 2024-09-11 at 16 57 44

### Additional context
- Destination address used: San Francisco, CA, 94110
- Origin postcode: 34480

### PR DESCRIPTION
**Pull request by ricardo**
Fixes #10022 

#### Changes proposed in this Pull Request

Originally, we had discovered the inconsistency with shipping rates only happened with JPY. It turns out it wasn't because JPY is a zero decimal currency, but because of the value after conversion.

The MCCY compatibility works by changing the WooCommerce store currency on the fly, but the FedEx API gets the converted values of the product in absolute terms, so if it surpasses a certain threshold, it applies insurance to it.

The way we pass the actual store currency in `set_settings`, but with the price already converted, makes it so that the FedEx API adds insurance to the shipping rates.

To avoid this problem, we're now preventing the price from being converted so that the calculations can be made correctly.

#### Testing instructions

Follow instructions to set up the Woo FedEx shipping extension: https://github.com/Automattic/woocommerce-payments/pull/3131

**Test: Ensure shipping rates are the same in different currencies**

1. As a merchant, set the store currency to USD.
2. Create a shippable product with dimensions and weight (It can be 5 for everything).
3. As a shopper, add the shippable product to the cart.
4. Enter a US address to the cart, e.g `San Francisco / CA / 94110`.
5. Observe the shipping costs in USD.
6. Open a new tab and switch the store currency to JPY using the currency switcher.
7. Ensure the FedEx shipping costs in JPY respect the converted amount in USD – To double check, you can use the conversion preview from **WooCommerce > Settings > Multi-currency > JPY**.

**Regression test: insurance remains for higher-ticket products when paying with USD**

1. As a merchant, change the shippable product price to 1000 USD.
2. As a shopper, switch the currency to USD and notice the shipping rates are slightly higher due to insurance.
3. As a merchant, navigate to **WooCommerce > Settings > Shipping** and edit the shipping zone with FedEx as a shipping method. 
4. Change the currency to JPY using the currency switcher and observe the shipping rates are equivalent from step 2 when converted.
5. Click "Edit" from FedEx, uncheck "Enable Insurance" and save the changes.
6. As a shopper, repeat step 2 or refresh the tab and notice there's no insurance added to the shipping rates.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9985` or branch name `fix/198-mccy-fedex-conversion` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/198-mccy-fedex-conversion) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 568f0487e93bfdfc1c0e56089ae8735d5796913f
- Build time: 2024-12-18 19:05:12 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by rafaelzaleski — COMMENTED** [review]
✅ Test: Ensure shipping rates are the same in different currencies
✅ Regression test: insurance remains for higher-ticket products when paying with USD

@ricardo, I don’t understand the logic behind removing insurance based on the currency the customer is using to pay. The underlying value of the item remains the same regardless of the currency, so insurance should be applied based on the item value, not the payment currency. 

Isn’t there a way to fix this by sending the USD value to FedEx for insurance, regardless of the payment currency?

**Comment by ricardo** [comment]
> I don’t understand the logic behind removing insurance based on the currency the customer is using to pay.

I also can't tell with 100% certainty, but when I looked at the [code](https://github.com/woocommerce/woocommerce-shipping-fedex/blame/26382eacb7ed55f76e8cc21caeb4a730d712f24c/includes/class-wc-shipping-fedex.php#L607-L618) from 10 years ago it seemed like a FedEx-specific logic for US and Canada.

> Isn’t there a way to fix this by sending the USD value to FedEx for insurance, regardless of the payment currency?

This approach is probably better. I made the change in [568f048](https://github.com/Automattic/woocommerce-payments/pull/9985/commits/568f0487e93bfdfc1c0e56089ae8735d5796913f) – can you help test it and make sure it doesn't produce any regressions? I'm doing the same.

One thing I noticed is that when I change the product price to 500 or 1000 USD it sometimes doesn't calculate the shipping rates and I'm not sure if this is a bug or a problem on my end.

**Comment by ricardo** [comment]
@rafaelzaleski one key difference with this new approach is that we're still adding insurance to the shipping rates if the store currency is USD and the base address is US, but it will be consistent with other currencies and not only apply to JPY like before this PR.

**Review by rafaelzaleski — APPROVED** [review]
The code looks good and tests well. Great job!  
Please update the PR description so that anyone referring to it in the future won't need to read through the comments.

**Pull request merged**
