### PR TITLE
[Cooldown] Add confirmation modals on order status change with pending authorization

### LINKED ISSUE #6126: [Spike]: Confirmation Modal while canceling un-captured orders
### Background

Whenever the status of an Authorization is changed, it is desired to have a confirmation modal that gives further information / warning to the merchant with the following scenarios:

* When the status of the order is manually changed to Cancelled, the modal can show a message warning that the authorization would be cancelled too. Sample text:  

>Cancel authorization
>
>This order has been [authorized but not captured](https://woocommerce.com/document/woocommerce-payments/settings-guide/authorize-and-capture/#authorize-vs-capture) yet. Changing the status to Cancelled will also [cancel the authorization](https://woocommerce.com/document/woocommerce-payments/settings-guide/authorize-and-capture/#cancelling-authorizations). Do you want to continue?
>
>[ Do nothing ]     [ Cancel order and authorization ] 

* When the order status is manually changed to `Complete`, the modal will need to show a warning mentioning that the payment will be captured if we proceed. Sample message:

>
>Capture payment
>
>This order has been [authorized but not captured](https://woocommerce.com/document/woocommerce-payments/settings-guide/authorize-and-capture/#authorize-vs-capture) yet. Changing the status to Completed will also [capture the payment](https://woocommerce.com/document/woocommerce-payments/settings-guide/authorize-and-capture/#capturing-authorized-orders). Do you want to continue?
>
>[ Do nothing ]     [ Complete order and capture payment ]
>

### Acceptance criteria
* Document how the scenarios above are currently handled
* Estimate the effort needed to bring about these modals

### Designs
Similar to the modals we have currently 
image

### Dev notes

* Code of [existing cancellation modal](https://github.com/Automattic/woocommerce-payments//blob/29292b783f31af50741b65e21322ee25f5f818b5/client/order/cancel-confirm-modal/index.js) 

### Additional context
* Related P2 Discussion - pdjVC1-1vj-p2
* Related issue - #5712  
* Related Spike on server GH on fixing the actual handling of Auth expiration on orders. - https://github.com/Automattic/woocommerce-payments-server/issues/3254

### PR DESCRIPTION
**Pull request by mgascam**
Fixes #6126 #5712

This PR adds confirmation modals that trigger when the status of the order is changed and there's an authorized payment not yet captured. Depending on the status of the order, the modal asks the merchants if they want to Cancel or Capture the authorization:

- Cancelled -> Cancel authorization
- Completed -> Capture authorization

#### Changes proposed in this Pull Request
- Adds a confirmation modal to **Capture** the authorization when the status is `Completed`.
- Refactor the current code that handles the order status change.
- Refactor to unify the modal components

#### Testing instructions

**Completed status with pending authorization**

1. Enable `Issue an authorization on checkout, and capture later` in `WP Admin > Payments > Settings`.
2. As a shopper, place an order.
3. In WP Admin, change the status of the order to `Completed`.
4. Check that the `Capture Authorization` modal appears. It includes links to public docs.
Screenshot 2024-02-14 at 18 27 25

6. Click the `Do Nothing` button.
7. Check that the order status is back to `On-hold` and nothing happens.
8. Change the status back to `Completed` and click the `Complete order and capture authorization` button.
9. Check that the order is captured, pay attention to the updated status of the order (Completed) and the Order notes section includes information from the capture.

**Cancelled status with pending authorization**

1. Enable `Issue an authorization on checkout, and capture later` in `WP Admin > Payments > Settings`.
2. As a shopper, place an order.
3. In WP Admin, change the status of the order to `Cancelled`.
4. Check that the `Cancel Authorization` modal appears. It includes links to public docs.
Screenshot 2024-02-14 at 18 22 38

6. Click the Do Nothing button.
7. Check that the order status is back to `On-hold` and nothing happens.
8. Change the status back to `Cancelled` and click the `Cancel order and authorization` button.
9. Check that the order is cancelled, pay attention to the updated status of the order (Cancelled) and the Order notes section includes information from the capture.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8169` or branch name `cooldown/6126-confirmation-modal-on-order-status-change-with-authorization` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=cooldown/6126-confirmation-modal-on-order-status-change-with-authorization) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: ef46590048484554c3b1610e2a6a0f96d633491e
- Build time: 2024-02-15 10:57:33 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by kalessil — CHANGES_REQUESTED** [review]
Quick feedback: we should only handle the transition to 'completed' status in this PR. 

Statuses transition to failed, pending, and processing are something we should not engage in. Those statuses are used in payment flows, and we can securely handle only the 'exit' statuses (cancelled, completed).

**Comment by mgascam** [comment]
> Quick feedback: we should only handle the transition to 'completed' status in this PR.
> 
> Statuses transition to failed, pending, and processing are something we should not engage in. Those statuses are used in payment flows, and we can securely handle only the 'exit' statuses (cancelled, completed).

Thanks @kalessil I got this wrong. I'm [limiting the scope to canceled and completed](https://github.com/Automattic/woocommerce-payments/pull/8169/commits/9198611fe1e8a2417bccf67f5d45b0da64366557) then (like to think that it's easier to remove the modal after this bit of refactor, and it will be also easy to add more modals in the future if needed )

**Comment by kalessil** [comment]
:eyes:

**Review by kalessil — APPROVED** [review]
LGTM and tests well!

Great work @mgascam! Don't forget to P2 about this feature!

**Comment by elizaan36** [comment]
hey team, For clarity the message copy needs to be tweaked on the capture modal. In the future please ping someone on the design, ops, or product teams to review customer facing changes so it can be finessed before it’s shipped.

Title should be **Capture payment**
CTA should be **Complete order and capture payment**

**Comment by kalessil** [comment]
Thank you @elizaan36! I posted pdjVC1-2bG-p2, which asks for reviewing all three dialogs together. Can you please share the proposal there?

**Pull request merged**
