### PR TITLE
Change Payment_Intent_Status to Intent_Status

### LINKED ISSUE #6773: Refactor: Change Payment_Intent_Status to Intent_Status
### Description

From https://github.com/Automattic/woocommerce-payments/pull/6586#discussion_r1250367313, change the name of current class name `Payment_Intent_Status` to `Intent_Status` so that it can be agnostic for either payment and setup intents.

https://github.com/Automattic/woocommerce-payments/blob/e3f1820ac05b9932a94ce1900d070363078c7eff/includes/constants/class-payment-intent-status.php#L20-L20

### Acceptance criteria

* Find all occurrences of `Payment_Intent_Status` and makes changes.
* May change the filename too.
* PHP tests should be run fine.

### PR DESCRIPTION
**Pull request by htdat**
Fixes #6773

### Note for myself: 

- [ ] Inherit Payment_Intent_Status from Intent_Status.
- [ ] Add a warning in using Payment_Intent_Status. 

#### Changes proposed in this Pull Request

- Change `Payment_Intent_Status` to `Intent_Status`. 
- Also change the file name respectively.

#### Testing instructions

* All tests pass.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] NO NEED - Tested on mobile (or does not apply)

**Post merge**

- [x] NO NEED - Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [x] NO NEED Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [x] NO NEED Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6957` or branch name `refactor/6773-intent-status` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=refactor/6773-intent-status) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: c586fe3e539c718da98ec814b19ccf761d19d8a4
- Build time: 2023-08-18 04:25:33 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by naman03malhotra — COMMENTED** [review]
Thanks @htdat for taking this up.

Looks good to me. All tests are passing. Did a basic smoke test as well, looks good.

As a caution, can you please check if any external product like TumblrPay or WooPay in any case referencing to `Payment_Intent_Status`

**Comment by naman03malhotra** [comment]
Also, there is a conflict that needs to be resolved.

**Comment by htdat** [comment]
Thanks for the review. 


> Also, there is a conflict that needs to be resolved.

Fixed it. 

> As a caution, can you please check if any external product like TumblrPay or WooPay in any case referencing to Payment_Intent_Status

Good point! That's being said, I am restoring `Payment_Intent_Status`, and add a deprecated PHPDoc annotation for it in this commit 8d3aa61120fa6c57b01ae716e02d8825425ad28d

### Ready to review again.

**Comment by naman03malhotra** [comment]
Thanks for making changes Dat and making it backward-compatible. My question is if the folks use the depicted function, will they get a warning?

>Good point! That's being said, I am restoring Payment_Intent_Status, and add a deprecated PHPDoc annotation for it in this commit https://github.com/Automattic/woocommerce-payments/commit/8d3aa61120fa6c57b01ae716e02d8825425ad28d

@RadoslavGeorgiev and I discussed during 1:1 if [WP deprecate](https://developer.wordpress.org/reference/functions/_deprecated_function/) method should be used for deprecating methods in the future.

**Comment by htdat** [comment]
Good question, @naman03malhotra!

> My question is if the folks use the depicted function, will they get a warning?

They will not. At least, during the development phase, supported IDEs (such as PhpStorm) can understand the PHPDoc annotation `deprecated` and give a warning like this:

Markup on 2023-08-18 at 10:53:01

> @RadoslavGeorgiev and I discussed during 1:1 if [WP deprecate](https://developer.wordpress.org/reference/functions/_deprecated_function/) method should be used for deprecating methods in the future.

I am aware of these [WP core deprecated functions](https://github.com/WordPress/wordpress-develop/blob/2acd0aca7845feda1c4ca4dd708ca4e8a72c422b/src/wp-includes/functions.php#L5432-L5870). However, for this specific class, I am not doing so due to two reasons: 

- Current usage is mostly to call them statically, such as `Payment_Intent_Status::SUCCEEDED`, and all of these deprecate functions do not help. 
- I'd like not to complicate it for this specific use-case. This class is only intended to use our internal products such as "WooPay" or "TumblrPay". (I did search them and they're not using `Payment_Intent_Status` in their repos).  

What do you think about my rationale above? 

Otherwise, reviewing `Base_Constant` class, I could override `__construct` and `get_value` to add these deprecated functions. But that only helps if developers use static method such as `Payment_Intent_Status::SUCCEEDED()` - see [the relevant code](https://github.com/Automattic/woocommerce-payments/blob/f85a74c88728cfa305b073ad9b822246211d880e/includes/constants/class-base-constant.php#L94).

**Comment by htdat** [comment]
Ready to review again.

**Comment by RadoslavGeorgiev** [comment]
> @naman03malhotra : @RadoslavGeorgiev and I discussed during 1:1 if [WP deprecate](https://developer.wordpress.org/reference/functions/_deprecated_function/) method should be used for deprecating methods in the future.

> @htdat: What do you think about my rationale above?

Coming into the PR, and seeing that it's about an ENUM, my first thought was temporarily keeping a hollow `class Payment_Intent_Status extends Intent_Status` in place, while also adding a `@deprecated` tag to it. That happens to be precisely what @htdat did, and I prefer this approach.

Using deprecation functions here is not applicable. All the class's constants are accessed directly, instead of through a method call. So at least in that regard, the current approach has a 🟢 from me.

**Review by naman03malhotra — APPROVED** [review]
Looks good, thanks for prompt replies! 🚢

**Pull request merged**
