### PR TITLE
Fix old subs links

### PR DESCRIPTION
**Pull request by aheckler**
This PR fixes a few documentation links for our subscriptions-related features. The docs went through some major adjustments with 6.6.0, so although the links work as they are now, they could point to slightly more ideal URLs. That's what this PR is for. :) 

For example, brand new stores will not, as we know, be able to use the old built-in subscriptions feature. However, the docs link for the Stripe Billing setting goes to [the comparison page](https://woocommerce.com/document/woopayments/subscriptions/comparison/), when really the best place to point that link is to the new doc I wrote on [the Stripe Billing setting](https://woocommerce.com/document/woopayments/subscriptions/stripe-billing/) itself.

Anyway, some of these non-ideal links are my fault, since originally I did not envision creating a new page, but doing so ended up being the best path forward w/r/t our docs.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7469` or branch name `fix-old-subs-links` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix-old-subs-links) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 0dea21f12e06d6029a7d9ee80d66038699b65d8a
- Build time: 2023-11-15 17:12:03 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by frosso — APPROVED** [review]
Hey @aheckler ! Thanks for making these changes! 
Approving for now.

It looks like the PR now has some conflicts, let me know if you need a hand fixing them!

**Comment by aheckler** [comment]
@frosso I'm on leave and only saw this by chance. Maybe @csmcneill can help in my stead?

**Comment by csmcneill** [comment]
@frosso I resolved the conflicts :) I was going to auto-merge, but I decided to hold off as I am unfamiliar with that process.

**Review by frosso — APPROVED** [review]
The changes still look good and are pointing to live links 👍 Thank you!

**Pull request merged**
