### PR TITLE
add default (= null) for classNames prop so it's optional for `WizardTaskItem` and `CollapsibleBody`

### LINKED ISSUE #9142: TypeScript: `WizardTaskItem` and `CollapsibleBody` require a `className` prop (should be optional)
### Describe the bug
No merchant impact, this bugged me when working on #8926, so logging an issue.

- In the [tax info modal](https://github.com/Automattic/woocommerce-payments/blame/develop/client/vat/form/tasks/vat-number-task.tsx), various components have `classNames={null}` which seems redundant and unnecessary.
- I tried removing, to see what breaks. 
  - No functionality or UI breaks.
  - There is a TypeScript error:
    - `TS2741: Property 'className' is missing in type '{ children: (false | "" | Element | null)[]; }' but required in type '{ [x: string]: any; className: any; }'.`

I think this can be fixed by adding a default (e.g. `classNames = null`) to the relevant JS components (`WizardTaskItem`, `CollapsibleBody`). 

Curious for insights from TypeScript experts @Jinksi  @reykjalin .

### PR DESCRIPTION
**Pull request by haszari**
Fixes #9142

#### Changes proposed in this Pull Request
- Migrates the `WizardTaskItem` and `CollapsibleBody` components to typescript, explicitly defining the `className` as optional
- Remove redundant `className=null` prop in tax modal code – no longer needed.

Clients currently have to pass `classNames = { null }` to appease TypeScript. The prop is actually optional, only used if client wants to customise the `class` of generated markup.

See https://github.com/Automattic/woocommerce-payments/blob/develop/client/vat/form/tasks/vat-number-task.tsx for an example.

The goal of this PR is to streamline code like `VatNumberTask` so it doesn't need to pass meaningless `className={ null }`.

#### Testing instructions

* Run this branch and test any code that uses `WizardTaskItem` and `CollapsibleBody`, e.g. show the VAT modal. See the following PR for instructions for testing the tax documents / tax info modal:
  * https://github.com/Automattic/woocommerce-payments/pull/8974
- Hack any code using `WizardTaskItem` and `CollapsibleBody` and add a custom `className`, to confirm that the rendered component still supports arbitrary custom classes as before.
- Confirm that linters, TypeScript, code checks are all green ✅ and happy.

* ~~Hack on any code that uses `WizardTaskItem` and `CollapsibleBody`~~…
  * ~~Remove the `classNames={ null }`, ensure no errors/linter/typescript warnings and UI works as expected.~~
  * ~~Add custom classes via `classNames` and ensure they are rendered correctly in generated markup.~~

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : **'QA Testing Not Applicable'**
- [x] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable. **N/A**
- [x] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable. **N/A**

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9157` or branch name `fix/9142-classname-optional-default-null` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/9142-classname-optional-default-null) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: faf777f8ade4de56473dacf635d0b0984ec6d2d6
- Build time: 2024-10-02 04:50:33 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by haszari** [comment]
> Hack any code using WizardTaskItem and CollapsibleBody and add a custom className, to confirm that the rendered component still supports arbitrary custom classes as before.

Dang - we now get a TypeScript error if passing a `className`! Which is not cool. 

```js
// Type 'string' is not assignable to type 'null | undefined'.
<WizardTaskItem
	className="gandalf"
```

So I need to find a way to tell TypeScript that this thing can be `null` or `string`. 

@reykjalin @Jinksi if you know how to elegantly fix this let me know! I am trying to avoid a rabbit hole of strongly typing everything (these components are JS, i.e. inferred types - which I think is a good thing).

**Comment by reykjalin** [comment]
Doing this on mobile, sorry for the lack of links and examples. You should be able to use JSDoc to provide type information that TS will use.

**Comment by Jinksi** [comment]
> So I need to find a way to tell TypeScript that this thing can be null or string.

I would consider migrating the `WizardTaskItem` component to TSX. The only change will be adding an interface for the props, which is a common pattern in this codebase we're used to seeing and working with.

image

**Comment by haszari** [comment]
> The only change will be adding an interface for the props, which is a common pattern in this codebase we're used to seeing and working with.

Sounds good, as long as we get some benefits from strongly typing this! It feels like the tooling is forcing us to strongly type everything – once we start, we can't stop. 

To me, strictly typing everything seems like a heavy cost to pay – there should be a way to nudge TypeScript to correctly **infer** that `className` is an optional string parameter.

**Comment by Jinksi** [comment]
If you wanted to keep this as JS and lean more into type inference, without explicitly declaring the prop types (nor in JSDoc), I think `className = ''` would work here.

```jsx
const WizardTaskItem = ( {
	children,
	title,
	index,
	className = '',
} ) => {
```

> To me, strictly typing everything seems like a heavy cost to pay

I agree, we should prefer inference wherever possible. However, writing an interface for a React component is straightforward when TS inference isn't sufficient or accurate. In this case, all the props are inferred as `any` which means the code reader has to look for this information elsewhere. E.g. is `index` meant to be passed as a string, an int, or maybe either is fine?

**Comment by haszari** [comment]
> If you wanted to keep this as JS and lean more into type inference, without explicitly declaring the prop types (nor in JSDoc), I think className = '' would work here.

Great idea! I have updated the PR with this approach, it works great, with minimal code impact.

I'm open to trying full-TypeScript approach, but decided against trying that myself today since I'd need to rename various files – more code impact. @Jinksi if you want to try that approach before merging, feel free to commandeer this PR 🤾🏻

**Comment by haszari** [comment]
Re-requested reviews, this should be good to go. 

I'm happy to for anyone to take this over and merge/wrap up, equally happy to handle myself when I get to it.

**Review by Jinksi — APPROVED** [review]
This looks good @haszari – a nice enhancement to our code quality.

I've tested this with the VAT download task list following the instructions from #8974 and confirm that the wizard renders correctly:

image
image


Also note that snapshot tests are still passing, meaning the correct classNames are being applied. https://github.com/Automattic/woocommerce-payments/blob/faf777f8ade4de56473dacf635d0b0984ec6d2d6/client/multi-currency-setup/tasks/add-currencies-task/test/index.test.js#L220-L222

> I'm open to trying full-TypeScript approach, but decided against trying that myself today since I'd need to rename various files – more code impact. @Jinksi if you want to try that approach before merging, feel free to commandeer this PR 🤾🏻

Note I've tried the TS approach in #9510 that could be merged into this PR – let me know what you think @haszari (I slightly prefer the TS approach and will merge unless you think otherwise 😎).

<details>
<summary>Test instructions followed</summary>


> Note you'll need to test this with a store with [account country that supports tax docs](https://github.com/Automattic/woocommerce-payments-server/blob/8f6bdc2195cd0a99abf888300b292795e7d294c7/server/wp-content/rest-api-plugins/endpoints/wcpay/utils/class-vat-utils.php#L19). Ideally, test with different accounts to see UI for different countries. Tip: if you set `wcpay_accounts[].deleted` to a date in the past, you can onboard a new account. Or switch between accounts by setting wcpay_accounts[].deleted=NULL` on the account you want to use.
> 
> 1. Set up tax docs so you have a document to view at `Payments > Documents`. Fake one up with this CLI command:
>    - `wp wcpay add_document_for_account [account_id] vat_invoice --mode=test --period_from="2024-04-01 00:00:00" --period_to="2024-04-30 23:59:59"`
>    - Or can use `wp wcpay backfill_merchant_vat_invoices`
> 1. If you've added VAT id / tax information previously, clear it out so you can see the modal: 
>    - Delete `company_vat_submitted` `company_vat_number` `company_name` `company_address` from  `wcpay_account_meta` table.
>    - Side note:
>        - https://github.com/Automattic/woocommerce-payments-server/issues/5915
> 1. Go to `Payments > Documents`. 
> 1. Click `Download` for a tax doc row.
> 1. See modal.
> 1. Test adding valid and invalid tax info.
> 1. Test downloading the generated tax doc – confirm the merchant details are correct.

</details>

**Comment by Jinksi** [comment]
I've merged #9510 into this branch (after discussion and approval from @haszari) and mentioned in this PR description that we're migrating the `WizardTaskItem` and `CollapsibleBody` components to typescript, explicitly defining the `className` as optional.

**Comment by haszari** [comment]
Thanks @Jinksi ! 

> > Let's keep our eyes open for examples that might be less amenable to strong typing.
> Some parts of our codebase that are still .js might be a hint.

I like this idea. Maybe we can add a comment to these files as we see them, i.e. intentionally not migrated, with rationale/explanation. That way the code base can be a living record of our decisions ⇒ experience of the trickier aspects of JS ⇒ TS.

**Pull request merged**
