### PR TITLE
Implement `BannerNotice` component

### LINKED ISSUE #7048: Update BannerNotice and InlineNotice components
### Description
As part of the new onboarding project, we need to use the banner notice component from WC Design, which is not available to import. So we need to implement it in WooPayments.

We already have `BannerNotice` and `InlineNotice` components, but they are mixed and don't follow our design guidelines.

### Acceptance criteria
- Update `BannerNotice` and `InlineNotice` components following design specs.
- Check every `BannerNotice` and `InlineNotice` instance and be sure the right one is in use.

### Designs
| BannerNotice | InlineNotice |
|-|-|
|Screenshot 2023-08-23 at 09 39 53|Screenshot 2023-08-23 at 10 41 04|

### Additional context
Figma: Kofpo8jj4zDWXDsVdlSz0f-fi-4171_46004

### PR DESCRIPTION
**Pull request by ismaeldcom**
Fixes #7048 

#### Changes proposed in this Pull Request
Implement `BannerNotice` component based on @wordpress/components `Notice` component applying WooCommerce Admin design library guidelines (Kofpo8jj4zDWXDsVdlSz0f-fi-4260%3A47121).

#### Testing instructions
- Implemented component matches design guidelines.
- It's only used on the new PO flow, to inform about a restored session. You can trigger it finishing the first step (personal) and refreshing the page.

You can use the following code to get all the variations from the following screenshot.
<details>
<summary>Code snippet</summary>

```jsx
<>
	<BannerNotice status="info">
		Don’t abuse the notice system, please; Use them sparingly.
	</BannerNotice>
	<BannerNotice icon status="info">
		Don’t abuse the notice system, please; Use them sparingly.
	</BannerNotice>
	<BannerNotice
		status="info"
		actions={ [
			{ label: 'Label', onClick: () => {} },
			{ label: 'Label', url: '#' },
		] }
	>
		Don’t abuse the notice system, please; Use them sparingly.
	</BannerNotice>
	<BannerNotice status="error">
		Don’t abuse the notice system, please; Use them sparingly.
	</BannerNotice>
	<BannerNotice icon status="error">
		Don’t abuse the notice system, please; Use them sparingly.
	</BannerNotice>
	<BannerNotice
		status="error"
		actions={ [
			{ label: 'Label', onClick: () => {} },
			{ label: 'Label', url: '#' },
		] }
	>
		Don’t abuse the notice system, please; Use them sparingly.
	</BannerNotice>
	<BannerNotice status="warning">
		Don’t abuse the notice system, please; Use them sparingly.
	</BannerNotice>
	<BannerNotice icon status="warning">
		Don’t abuse the notice system, please; Use them sparingly.
	</BannerNotice>
	<BannerNotice
		status="warning"
		actions={ [
			{ label: 'Label', onClick: () => {} },
			{ label: 'Label', url: '#' },
		] }
	>
		Don’t abuse the notice system, please; Use them sparingly.
	</BannerNotice>
	<BannerNotice status="success">
		Don’t abuse the notice system, please; Use them sparingly.
	</BannerNotice>
	<BannerNotice icon status="success">
		Don’t abuse the notice system, please; Use them sparingly.
	</BannerNotice>
	<BannerNotice
		status="success"
		actions={ [
			{ label: 'Label', onClick: () => {} },
			{ label: 'Label', url: '#' },
		] }
	>
		Don’t abuse the notice system, please; Use them sparingly.
	</BannerNotice>
</>
```

</details>

#### Screenshots

| Design guidelines | Implementation |
|-|-|
|Screenshot 2023-08-30 at 11 19 11|

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _QA Testing Not Applicable_
- [x] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [x] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by ismaeldcom** [comment]
Hey @elizaan36! Closing the loop on https://github.com/Automattic/woocommerce-payments/pull/6934#issuecomment-1689204241 🙂  I'd like to double-check that's expected to use the banner notice as it is on a white background. This is how it looks:

Screenshot 2023-08-30 at 11 41 57

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7097` or branch name `add/7048-banner-notice-component` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=add/7048-banner-notice-component) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 4f47a0b7754b82eb320cbdc41d2003e14222c9b7
- Build time: 2023-08-30 12:59:38 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by vladolaru — APPROVED** [review]
Great job, @ismaeldcom! LGTM! The test instructions checked out, and the code looks great! Approving it.

**Review by elizaan36 — COMMENTED** [review]
Looks good to me!

**Pull request merged**
