### PR TITLE
Now the setup intents ids are no more a link to the transaction page

### LINKED ISSUE #6577: Invalid Setup Intent links in the edit page for zero orders
### Describe the bug

Invalid Setup Intent links in the order page for zero orders such as free trial subscription product). 

### To Reproduce

1. Use WCPay Subscription and create a subscription product with free trial.
2. Purchase this product, and check out with a new card.
3. Check the setup intent (starting with prefix `seti_`) attached to the edit page of this order.
4. Click the link for the setup intent ID, which is similar to this http://localhost:8082/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Ftransactions%2Fdetails&id=seti_1NM5QOR67tFB8u4VSbAIJoyW
6. Get the error!  

#### Edit order page:

Markup on 2023-06-23 at 16:24:49

#### Error translation detail page: 

Markup on 2023-06-23 at 16:23:33

### Expected behavior
May not have a link to the transaction page for setup intents.

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### PR DESCRIPTION
**Pull request by leonardola**
Fixes #6577

#### Changes proposed in this Pull Request
This PR removes the link to setup intents because the transaction page does not support setup intents

#### Testing instructions
- Use WCPay Subscription and create a subscription product with free trial.
- Purchase this product, and check out with a new card.
- Check the setup intent (starting with prefix seti_) attached to the edit page of this order.
- Click the link for the setup intent ID, which is similar to this http://localhost:8082/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Ftransactions%2Fdetails&id=seti_1NM5QOR67tFB8u4VSbAIJoyW
- Make sure the setup intent `seti_` id is not a link

Markup on 2023-06-23 at 16:24:49

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7359` or branch name `fix/setup-intent-link` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/setup-intent-link) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 72b558767a673e0e4f0de13316d3125879e78e2f
- Build time: 2023-10-10 14:10:00 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by hsingyuc** [comment]
@leonardola When I tested with the free trial, I don't see the payment intent id and if I test without the free trial the payment intent id prefix is not `seti_`.  Do you know which part I set up wrong?

**with the free trial**
Screen Shot 2023-10-06 at 11 28 57 AM


**without the free trial**
Screen Shot 2023-10-06 at 11 29 15 AM

**Comment by leonardola** [comment]
@hsingyuc payment intents `pi_` are used for actual payments. When orders are not 0 dolar or for renewals.
Setup Intents `seti_` are used when a [new credit card is added](https://stripe.com/docs/payments/setup-intents).


> When I tested with the free trial, I don't see the payment intent id 

Have you used a credit card that was already registered? You'll need to use a brand new credit card for this. Otherwise the setup intent won't show up. Not sure if it should though

**Review by hsingyuc — APPROVED** [review]
>and check out with a new card.

Thank you @leonardola and sorry, I missed this part.  Tests are as expected, and LGTM.

Screen Shot 2023-10-11 at 2 59 33 PM

**Pull request merged**
