### PR TITLE
Fix incorrect channel value in transaction description screen for Tap to Pay for Android transactions

### LINKED ISSUE #6735: Incorrect channel value in transaction description screen for Tap to Pay for Android transactions
### Describe the bug
The channel value for TTP for Android transactions is displayed incorrectly. The correct value should be `Tap to Pay on Android`.

Screenshot 2023-07-11 at 18 47 51

### To Reproduce
- Create a Tap to Pay order on Android device
- Navigate to `Payments` -> `Transactions`
- Click on the transaction to be redirected to the transaction details page
- Verify the channel column value is `Tap to Pay` instead of `Tap to Pay on Android`

### PR DESCRIPTION
**Pull request by mordeth**
Fixes #6735

#### Changes proposed in this Pull Request
Fixes incorrectly displayed channel value for Tap to Pay for Android transactions on transaction details screen.

Screenshot 2023-07-11 at 19 05 03

#### Testing instructions
- Create a Tap to Pay order on Android device
- Navigate to `Payments` -> `Transactions`
- Click on the transaction to be redirected to the transaction details page
- Verify the channel column value is Tap to Pay on Android

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6736` or branch name `fix/6735-incorrect-channel-value` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=fix/6735-incorrect-channel-value) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 5df67b8a32124904dda71f7e9e21272e094478f1
- Build time: 2023-07-12 09:51:18 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by dpaun1985 — APPROVED** [review]
✅ LGTM

**Review by anu-rock — APPROVED** [review]
LGTM 🚢

**Review by elazzabi — APPROVED** [review]
Looks good! Thanks!

**Pull request merged**
