### PR TITLE
Fixed sed invocation in WP tests installabtion script, when running on MacOS

### LINKED ISSUE #3632: Local testing environment error `sed: 1: "/var/folders...": invalid command code f`
### Describe the bug
When trying to run tests, or set up test site, error is given:

```
$ bin/install-wp-tests.sh wcpay-tests root root
Downloading WordPress 5.8.3 (en_US)...
md5 hash verified: 9abc51309a31a0d5846ec40ce475cb86
Success: WordPress downloaded.
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
Success: Generated 'wp-config.php' file.
sed: 1: "/var/folders/g9/jxpj_7d ...": invalid command code f
```

### To Reproduce
Run `bin/install-wp-tests.sh`
It doesn't seem to happen to everyone, so it may be dependent on the environment. 

### Additional context
Seems to have been introduced in this PR: https://github.com/Automattic/woocommerce-payments/pull/3479

### PR DESCRIPTION
**Pull request by kalessil**
Fixes #3632

#### Changes proposed in this Pull Request

- Re-use the existing solution for i-flag when fixing MySQL driver settings

#### Testing instructions

* CI checks shall pass

-------------------

- [x] Added changelog entries to both `readme.txt` and `changelog.txt` (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

### CODE REVIEW

**Comment by ismaeldcom** [comment]
It returns `command i expects \ followed by text` on macOS. To make the insert compatible with both GNU and macOS I think we should use something like:
```sh
sed $ioption "/Happy publishing/{h;s/.*/mysqli_report(MYSQLI_REPORT_OFF);\n/;p;g;}" "$WP_CORE_DIR/wp-config.php"
```

**Comment by jessepearson** [comment]
@kalessil Sorry for the late reply. I just tested this and got the same thing Ismael did:

```
$ bin/install-wp-tests.sh wcpay-tests
Downloading WordPress 5.9.1 (en_US)...
Using cached file '/Users/j/.wp-cli/cache/core/wordpress-5.9.1-en_US.tar.gz'...
Success: WordPress downloaded.
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
Success: Generated 'wp-config.php' file.
sed: 1: "/Happy publishing/i mys ...": command i expects \ followed by text
```

**Comment by kalessil** [comment]
@ismaeldcom , @jessepearson: new update here, would you please try again running the script locally?

**Review by ismaeldcom — APPROVED** [review]
LGTM! It works on macOS without any issue now 🙂

**Comment by jessepearson** [comment]
Thank you 😁

**Pull request merged**
