### PR TITLE
Fix Teams for WooCommerce Memberships on product WooPay Express Checkout Button

### PR DESCRIPTION
**Pull request by alefesouza**
#### Changes proposed in this Pull Request

Fix Teams for WooCommerce Memberships fields data not send when clicking WooPay Express Checkout Button on product page.

#### Testing instructions

* Install WooCommerce Memberships and Teams for WooCommerce Memberships plugins.
* Create a team.
* Create a product to join this team.
* On product page, type the team name and check the `Take up a seat` checkbox.
* Click the WooPay button.
* You should be redirected to WooPay with the correct cart data.
* On product page, do not fill out the team name field.
* Click the WooPay button.
* An error message should be shown.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7239` or branch name `fix/teams-for-wc-memberships-on-product-woopay-express-checkout-button` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/teams-for-wc-memberships-on-product-woopay-express-checkout-button) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 1745365d633e0d0925758e19b188cc693a1f84cf
- Build time: 2024-06-12 00:16:34 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by hsingyuc — COMMENTED** [review]
@alefesouza Thank you for working on this!  If I test a team that doesn't exist, I can still get redirected to WooPay.  Is that intentional?

Screen Shot 2023-09-27 at 2 13 58 PM

**Comment by alefesouza** [comment]
@hsingyuc it looks like it's expected as the same happens on normal checkout flow, the purchase is for the user create a team which have access to a membership plan and then the user can add new users to this team.

While testing I noticed that this extension requires the user to be authenticated on merchant store if an existing email is detected, otherwise the extension will create a new user, currently we cannot create new users from WooPay and probably we would need to show an alert asking the user to login if the email exists on merchant store, @pierorocca should we skip this extension for now?

**Comment by pierorocca** [comment]
@nerrad you mentioned your team is looking at the possibility of enabling this use case. Can you share more detail and tentative timelines to help inform our path forward here? Many thanks.

**Comment by nerrad** [comment]
> you mentioned your team is looking at the possibility of enabling this use case

hmm... I might need my memory refreshed on where I stated this, I don't recall where I might have mentioned that. What I can tell you is that to my knowledge this is not something currently on our roadmaps. How critical is it? 

It looks like the behaviour here is something that the extension needs to implement. What value is there having Woo core handle automatically requesting login if the email provided exists for a given user account?

**Comment by pierorocca** [comment]
> >you mentioned your team is looking at the possibility of enabling this use case

>hmm... I might need my memory refreshed on where I stated this, I don't recall where I might have mentioned that. What I can tell you is that to my knowledge this is not something currently on our roadmaps. How critical is it?

@nerrad it was during the BE showcase Points & Rewards and Gift Card Demo. We have you on video ;). One of the limitations I noted was the inability for WooPay to create a store account so that a shopper could earn points if they hadn't signed up in the store. To which you responded IIRC that your team was looking at a way to help facilitate the account creation. Did I understand incorrectly?

**Comment by nerrad** [comment]
> it was during the BE showcase Points & Rewards and Gift Card Demo. We have you on video ;). One of the limitations I noted was the inability for WooPay to create a store account so that a shopper could earn points if they hadn't signed up in the store. To which you responded IIRC that your team was looking at a way to help facilitate the account creation. Did I understand incorrectly?

Ahh right, this is slightly different than what is being referred to in this issue though. What I was referring to in the call was implementing a "create user" flow that would happen post-purchase (likely embedded within the order confirmation page). 

Right now account creation is already facilitated by WC checkout but one distinction between the blocks and the shortcode based flow is that with the shortcode checkout, one of the available options (depending on how the store is configured) is for the shopper to provide username and password for the created account. The block flow does not provide that option (and that's what ideally would be post-purchase).

**Comment by pierorocca** [comment]
>  a "create user" flow that would happen post-purchase (likely embedded within the order confirmation page).

Thanks @nerrad. Do you think in that scenario the points would be earned on that just completed purchase or only on future purchases? Ideally we'd want the user to not miss out on points. There's the challenge of surfacing store's account / privacy policy which may make it too challenging to do pre-purchase in a hosted context. Post-purchase isn't an acceptable fallback as a start.

**Comment by nerrad** [comment]
> Thanks @nerrad. Do you think in that scenario the points would be earned on that just completed purchase or only on future purchases? Ideally we'd want the user to not miss out on points. There's the challenge of surfacing store's account / privacy policy which may make it too challenging to do pre-purchase in a hosted context. Post-purchase isn't an acceptable fallback as a start.

It is likely when we implement an embedded account creation flow for the new checkout that it will default to post-purchase - for the majority of stores this will prevent shopper friction on checkout causing abandonment. My comments are exclusively about what WC core would likely ship with.
 
In the context of the described features in this issue, it's up to the membership extension (+ however WooPay adds support for the extension) to ensure assigned points on initial purchase (and account creation) - I would think that receiving those points for account creation would even be an incentive to complete the signup?

Regardless, if post-purchase won't work for this particular extension, it sounds like there'd need to be a custom flow added by the extension to the checkout. I must admit though, I'm a bit confused about whether this issue is about attributing earned points or the teams feature in WooCommerce Memberships.

**Comment by pierorocca** [comment]
Typo on my part...post-purchase would be an acceptable place to start and optimize from there.

**Comment by alefesouza** [comment]
@hsingyuc https://github.com/Automattic/woocommerce-payments/pull/8924 fixes the account creation issue on this PR too, could you review this again?

**Review by hsingyuc — APPROVED** [review]
@alefesouza test as expected. 👍

**Pull request merged**
