### PR TITLE
misc: remove deprecated param from asset data registry

### LINKED ISSUE #8662: GH checks fails since WC 8.9 release – `WC compatibility (latest, latest, latest, 7.4)` and `Code coverage`
### Description

The following GitHub checks fail due to a deprecated `AssetDataRegistry` arg – deprecated since WC 8.9:

* `WC compatibility (latest, latest, latest, 7.4)`
* `Code coverage (latest, latest, 7.4, includes)` 

[See example run](https://github.com/Automattic/woocommerce-payments/actions/runs/8731648682/job/23957392556#step:5:743).

**Output from the test failure**:

```
Function Automattic\WooCommerce\Blocks\Assets\AssetDataRegistry::add() was called with an argument that is deprecated since version 8.9! The $check_key_exists parameter is no longer used: all duplicate data will be ignored if the key exists by default
```

### Additional context

The deprecation notice introduced to WC in https://github.com/woocommerce/woocommerce/pull/46139.

### Priority

Low priority – deprecation notice only and does not impact functionality.

### PR DESCRIPTION
**Pull request by timur27**
Fixes https://github.com/Automattic/woocommerce-payments/issues/8662

#### Changes proposed in this Pull Request
`$check_key_exists` param was deprecated in https://github.com/woocommerce/woocommerce/pull/46139 and it's being mentioned that 

```
an optional param $check_key_exists with the default value set to false, which in practice doesn't have any impact in the end results
```

so it seems to be safe to remove this and thus make unit tests pass with newer WC version.

#### Testing instructions
* all unit tests pass for this PR
* first two testing instructions steps from https://github.com/Automattic/woocommerce-payments/pull/4441 are working well 

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8666` or branch name `remove/deprecated-param-from-asset-data-registry` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=remove/deprecated-param-from-asset-data-registry) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 28f8fcc7c270ff2614a9adc8181abdc3d3a17e7b
- Build time: 2024-04-18 14:29:40 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by frosso — DISMISSED** [review]
👑 :shipit:

**Comment by timur27** [comment]
The commits from @dmallory42 within this PR are looking good and test well, I can see the currency information being collected by Analytics.

image

All test jobs are also passing now so I think we can move forward with this change @dmallory42 what are your thoughts? 😄

**Review by dmallory42 — APPROVED** [review]
I think this should solve the problem, it also fixes a previously undiscovered issue where we were re-registering the setting multiple times during runtime (which is not breaking, but inefficient).

Approving the PR!

**Comment by Jinksi** [comment]
Nice one @timur27 – It looks like this is a fix for #8662, so I'll link it.

**Pull request merged**
