### PR TITLE
Fixes Pay for Order page functionality in split-UPE

### LINKED ISSUE #5808: Users encountering an error while attempting to pay for order using UPE method
### Describe the bug
When trying to Pay for order with any of the available UPE methods, user sees an error _**Invalid payment method. Please input a new card number.**_

### To Reproduce

Enable split UPE and:
1. Buy a product using the shortcode checkout and UPE method (e.g. Sofort) 
2. On the third-party test payment page, choose _**Fail test payment**_
3. After redirected back to the checkout page, go to _**My account -> Orders**_, find the failed order and click _**Pay**_
4. On the _**Pay for order**_ page, choose any of the available UPE methods and click _**Pay for order**_

### Actual behavior
Users are seeing _**Invalid payment method. Please input a new card number.**_ error notice. 

### Expected behavior

Users shouldn be able to pay for order successfully, using any of the available payment method on the list.

### Desktop (please complete the following information):

* OS: MacOS
* Browser: Chrome

### PR DESCRIPTION
**Pull request by FangedParakeet**
Fixes #5808 

#### Changes proposed in this Pull Request

# Pay for Order Page: Preserved at Last

Previously when the split-UPE was enabled, the Pay for Order page had very limited functionality. The card payment method could fail, if the customer elected to change their currency, and the other additional payment methods would fail in all cases. I have identified three issues that are causing these frustrating failures.

1. If order currency and customer selected currency do not match, if the customer selected currency is not supported by available payment method, payment intent will produce an error and payment elements will fail to mount.
2. Pay for order form incorrectly detects when WCPay payment method is selected at checkout.
3. Payment intent confirms successfully, but `process_redirect_payment` function exits early, order is not updated, and instead marked as a failure.

I hurdle the first obstacle by ensuring that when the Pay for Order page is open, multi-currency will disregard the currency selected by the customer and enforce that the correct currency on the order is used instead. This ensures that we only present the correct relevant and valid payment methods to the customer on this page and ensures that the customer cannot produce an invalid combination of selected currencies and payment methods. 

I vault the second hurdle by removing the `isWCPayChosen()` function from the Pay for Order client script, instead relying on the `getSelectedUPEGatewayPaymentMethod()` function to test when a WCPay payment method is selected. `isWCPayChosen()` only checks for the presence of the `woocommerce_payments` gateway, ignoring the additional split-UPE gateways, and causing the Pay for Order scripts to consequently be skipped when an alternate WCPay gateway is selected.

The third barrier is the one described in #5854 and should be fixed by #6170.

#### Testing instructions

1. Create an order from WC Admin (WooCommerce > Orders > Add new).
2. Open the newly created order, add an item, customer, billing, and shipping details. Update the order
3. Select the "Customer payment page" to be sent to the Pay for Order page.
4. Fill in payment information and complete checkout for order. Use all payment methods (CC + additional UPE LPMs). 
5. Try to change the currency using the currency switcher widget. Currency displayed on Pay for Order page should remain the same. Payment elements should all load when appropriate without any errors.
6. In all above cases, customer should be able to complete checkout without receiving errors. Order status should be successfully updated to "Processing". Order details on payment intent should all be correct and valid.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6177` or branch name `fix/5808-upe-pay-for-order-page` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=fix/5808-upe-pay-for-order-page) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: cc37adfae6b6c32fadbc7ab34a48fea2b6718cf3
- Build time: 2023-05-16 16:52:11 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by mdmoore — CHANGES_REQUESTED** [review]
I'm able to successfully process orders with all LPMs and CC, so that's all good. When testing the currency switch, the following error is showing up: 

`We're not able to process this payment. Please refresh the page and try again.`

In the console: 
```
Uncaught (in promise) IntegrationError: In order to create a payment element, you must pass a clientSecret or mode when creating the Elements group.

  e.g. stripe.elements({clientSecret: "{{CLIENT_SECRET}}"})
    n (index):1
    r (index):1
    t (index):1
    ro (index):1
    pi (index):1
    t (index):1
    create (index):1
    B (index):1
    mountUPEElement upe-split.js:284
    async* upe-split.js:361
    jQuery 13
v3:1:478949
```

This is occurring when the store/order currency is euros and changed to usd on the Pay for Order page. I haven't been able to pinpoint the cause unfortunately. I'm testing with the Split UPE flag enabled with CC and all LPMs enabled, WooPay/Link disabled. Let me know if you have other questions about the setup.

**Comment by FangedParakeet** [comment]
Nice catch, @mdmoore. The issue was that AJAX requests could not pick up the URL query var for the Order Pay page, so in these cases the order currency was still not being used. Amended in a559588deed2911dc911edcab982a25054f37013, if you wouldn't mind re-checking and double-checking that there aren't any other regressions with other feature flags enabled/disabled (deferred intent flag excepted).

**Review by mdmoore — APPROVED** [review]
The previously mentioned errors are no longer present. All is now working well on the Pay for Order page with both CC and LPMs. Stripe metadata is all looking good with the correct currency and payment methods. I wasn't able to find any regressions when testing the legacy UPE feature flag or with all feature flags disabled. 

Pay for Order under the Split UPE checkout with deferred intent creation isn't functional but that's unrelated to this PR. It looks like it will be handled in #5023. 

This one is ready to go! 🚢

**Pull request merged**
