### PR TITLE
Fix not allowed page when clicking Set up WooPayments from Core and account is already onboarded

### LINKED ISSUE #7625: Clicking on the completed "Set up WooPayments" task from Core takes you to a "Sorry you are not allowed to access this page"
### Describe the bug
See 03:35 in this recorded demo p1698953366764689-slack-C03KTTK2YMA

After clicking on that task, it should redirect the user to the Payments dashboard.

Note: the code lives in Woo Core repo, but opening the issue here for easier management and tracking

### PR DESCRIPTION
**Pull request by oaratovskyi**
Fixes #7625

#### Description

Merchants currently observe an issue with Set up WooPayments task: when account is fully onboarded, the link redirect them to `payments/onboarding` which results in Not allowed page error
image

#### Changes proposed in this Pull Request

I decided that the best experience for merchants will be to get redirected to `payments/overview` page if the account is fully onboarded. I'll create a tech debt issue for that if that sounds good!

**Important**
Tests are not added since there is no tests for `maybe_handle_onboarding` function. Creating tests for it seems like out of scope for this PR.

#### Testing instructions

* Onboard an account as builder (`develop` branch)
* Get back to WC Home and click Set up WooPayments
* Observe the error described in the PR
* Checkout the branch `fix/7625-fix-setup-payments-task-for-completed-accounts` 
* Click Set up WooPayments
* Get redirected to `payments/overview`

Bonus: test that Set up WooPayments link works well when we don't have onboarded account.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions-for-WC-Payments-6.8.0#fix-not-allowed-page-when-clicking-set-up-woopayments-from-core-and-account-is-already-onboarded_
- [x] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [x] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7652` or branch name `fix/7625-fix-setup-payments-task-for-completed-accounts` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/7625-fix-setup-payments-task-for-completed-accounts) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 92d98c588d023936ed1aa610d9e2e6819607f601
- Build time: 2023-11-07 15:36:43 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by vladolaru — APPROVED** [review]
Testing instructions checked out (including bonus one)! Good job, Oleks! 🚢  it!

**Comment by vladolaru** [comment]
Regarding tech debt, @oaratovskyi, I think we should have an issue for normalizing and reducing the redirect logic, so we don't get to pile on more conditional branches to the logic. For that issue, we should strive to have a stable, catch-all logic that would prevent any other such issues in the future (no more ending up on pages with "Sorry you are not allowed"). WDYT?

**Review by daquinons — APPROVED** [review]
Thanks Oleks! I've tested it with the builder (test) account but I imagine this issue would also be occurring with live accounts, so this is perfect.

I do agree with @vladolaru, this seems like a painful area where we tend to have issues and have to revisit quite often. Can you create a tech debt issue in component onboarding pointing to this change and conversation to get the context? 💯

**Comment by oaratovskyi** [comment]
Thanks mates for your reviews! I made a fix to the bug spotted by e2e tests, could you please run the tests one more time? 🙏 
See p1699370136546899/1699365759.939169-slack-C03KTTK2YMA for the full context

**Comment by oaratovskyi** [comment]
> Can you create a tech debt issue in component onboarding pointing to this change and conversation to get the context? 💯

Sure thing! I'll create one and link to this issue.

**Comment by vladolaru** [comment]
Tested again, @oaratovskyi! Works as expected. Thanks for the fix.

**Comment by oaratovskyi** [comment]
Created https://github.com/Automattic/woocommerce-payments/issues/7654 that will address redirects logic

**Comment by oaratovskyi** [comment]
Created #7655 that will improve statuses logic

**Pull request merged**
