### PR TITLE
Use client-side routing for the transaction details `ch_` → `pi_` redirect

### PR DESCRIPTION
**Pull request by Jinksi**
Discovered while working on #6929.

### Changes proposed in this Pull Request

When **Transactions → Details** (`/payments/transactions/details`) is visited using a **charge ID** (`&id=ch_3Ni6ZWC15a3WbJ1t0O8hknEU`), the page must be redirected to the **payment intent ID** URL (`&id=pi_3Ni6ZWC15a3WbJ1t0WyYHnFz`). Implemented in #4348.

On `develop`, this results in a full-page reload.

This PR proposes using client-side routing to achieve this redirect, resulting in quicker page load and improved UX.

### Screenshots

Before (`develop`):

https://github.com/Automattic/woocommerce-payments/assets/3147296/b07abb47-9ed4-40a3-80a5-043657de5276

After (this PR):

https://github.com/Automattic/woocommerce-payments/assets/3147296/f65b0765-ff99-4110-890e-70d610c38576

### Testing instructions

* Navigate to Payments → Disputes and click to view the Dispute Details screen.
	* Create a test dispute by using the card `4000000000000259` at checkout
* Click the **Transaction ID: `ch_abcd`** link to view the Transaction Details screen
	image
* Observe the redirect that occurs on the Transaction Details screen.
	* On `develop`, the redirect will involve a full=page reload
	* On this branch, client-side routing will seamlessly handle the redirect.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

#### Additional details
* In #6929, we are changing all links previously routed to **Dispute → Details** to now route to **Transactions → Details**. This is achieved by using the `dispute.charge_id` property that is readily available.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7089` or branch name `fix/improve-transaction-details-redirect` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/improve-transaction-details-redirect) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: d80f479bcb6f62d101656129760f2fa7b9a93e17
- Build time: 2023-08-31 21:55:38 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by Jinksi** [comment]
@eduardoumpierre it would be great to get your feedback on this approach, as the author of the initial redirect logic in #4348.

Do you think using `getHistory()` is a valid approach?

**Comment by eduardoumpierre** [comment]
Hey @Jinksi, I believe that using client routing for this case is a valid approach and a great UX improvement. Thanks for working on this!

**Comment by Jinksi** [comment]
🙌 Thanks for your feedback @eduardoumpierre.

**Review by shendy-a8c — APPROVED** [review]
Looks good!

**Pull request merged**
