### PR TITLE
Add callback to create new wcpay subscription on manual renewal

### LINKED ISSUE #2960: WCPay Subscriptions: Create WC Pay subscriptions by paying for manual/failed renewal
Part of https://github.com/Automattic/woocommerce-payments/issues/2868 

### Description

When a merchant downgrades their site from the WC Subscriptions plugin, existing subscriptions will be treated as manual renewal and will require the customer to sign up to a WC Pay Subscription via Stripe Billing. This customer flow will be in the form of 1 of 2 approaches. 

1. Paying for a failed/pending renewal order. _Reactivate customer approach_
2. Add/changing the payment method. _Proactive customer approach. See [#2961](https://github.com/Automattic/woocommerce-payments/issues/2961)_

This issue will handle the **first** of those two approaches.  

### Testing instructions

1. Create a manual subscription by:
     - **Via plugin** 
       - Install the WC Subscriptions plugin
       - Purchase a subscription with a payment method like Stripe. 
       - Deactivate the plugin
       - If you have the latest _subscriptions-core_ with [this change](https://github.com/woocommerce/woocommerce-subscriptions/pull/4201 
) included in WC Payments, renewing this subscription will be treated as manual. 
     - **Via Admin**
     - Go to **WooCommerce > Subscriptions > Add new**
     - Add line items
     - Set the billing schedule
     - Set the customer and address fields
     - Save.
2. Renew the subscription manually via the edit subscription actions dropdown. https://d.pr/i/UqsRa2
3. This should place the subscription on-hold and create a pending renewal order. 
4. Paying for that order should set up a Stripe billing subscription.

### PR DESCRIPTION
**Pull request by chickenn00dle**
Fixes #2960 

#### Changes proposed in this Pull Request

This adds callbacks to the `woocommerce_renewal_order_payment_complete` hook that create a new WCPay subscription when a manual renewal order is paid for an order in which the associated WC subscription doesn't have a corresponding Stripe subscription.

#### Testing instructions

- Create a few manual subscriptions following step 1 outlined in #2960 
- Make sure WC Subscriptions is disabled before proceeding
- As the merchant, create a pending renewal order for one of the subscriptions created above
- As the customer, access the `my account` page, find the pending renewal order, and select the pay button
- As the customer, pay for the order with WCPay payment gateway
- Confirm a new subscription has been created in the Stripe dashboard for the connected account
- Confirm the details of the Stripe subscription match the details of the WC subscription
- After testing the main flow above, go through standard renewal flows to ensure there are no side effects

-------------------

- [ ] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [x] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply)

### CODE REVIEW

**Comment by chickenn00dle** [comment]
This is ready for review now. Just one note when reviewing - I noticed that other payment gateways remain available when paying for a manual renewal (pre-migration) on checkout: https://cloudup.com/ct-Qf8HoeZK

If I understand correctly, this shouldn't be the case as we take care of removing all gateways outside of WCPay in subscriptions core here: https://github.com/Automattic/woocommerce-subscriptions-core/blob/503795840b6dc78d91694a6f00169ba571051ca3/includes/gateways/class-wc-subscriptions-core-payment-gateways.php#L66

I'm actually not sure if this is a bug, or if manual renewals are an edge case that need to be handled in WCPay subscriptions code. Either way, I think we can address this in a follow-up PR. In the meantime, I'd love a second opinion before opening an issue for this.

Thank you!

**Review by james-allan — CHANGES_REQUESTED** [review]
Works a treat and the changes look good. I've included below a breakdown of the scenarios I tested.

**With WC Subscriptions active** 
- [x] paying for renewal order with WC Payments (see review comment)
- [x] paying for renewal order with Stripe.

**Without WC Subscriptions active** 
- [x] Purchasing a subscription and WCPay set up (given you changed the initial purchase in this PR I thought retesting that was prudent). 
- [x] Manually created subscription with a manual renewal order

**After downgrading**
- [x] Stripe subscription > Failed renewal payment > downgrade to Subscriptions via WCPay > Pay for renewal
- [x] Stripe subscription > Manual renewal order > downgrade to Subscriptions via WCPay > Pay for renewal.

**Comment by chickenn00dle** [comment]
Thanks for the review @james-allan! I've addressed the feedback on this. I'll be calling it a day here, so I'll leave the merging of this one to you if the change looks good.

**Comment by james-allan** [comment]
Retested this afternoon. Looks good. Thanks @chickenn00dle!

**Pull request merged**
