### PR TITLE
Add new E2E test: Merchant / Disputes / Submit winning dispute

### LINKED ISSUE #1488: Write new e2e test: Merchant / Disputes / Submit winning dispute evidence
Write a new e2e test that covers the following flow:
* Merchant / Disputes / Submit winning dispute evidence

### PR DESCRIPTION
**Pull request by veljkho**
Fixes #1488

#### Changes proposed in this Pull Request

`(i)` I recommend to wait for [this pull request](https://github.com/Automattic/woocommerce-payments/pull/1745) to be merged first, because I created this branch from there in order to use some helpers/crucial changes.
**Update: It has been merged!**
#### Testing instructions

- npm run test:e2e-dev ./tests/e2e/specs/merchant/dispute-submit-winning.spec.js

-------------------

### CODE REVIEW

**Review by reykjalin — APPROVED** [review]
Looks good and tests well! 🚀

**Comment by dechov** [comment]
Looks like the evidence is submitted, but the dispute doesn't end up "won" – this is due to the one test string not being provided, see [test doc](https://stripe.com/docs/testing#disputes).

**Comment by reykjalin** [comment]
Ah, I missed that we're not asserting the dispute status during the tests. Nice catch @dechov 👏 

@veljkho do you think we can add the winning evidence string (see @dechov's comment above ^) and add an assertion that verifies that the dispute has been marked as `Won`?

**Comment by veljkho** [comment]
Hey @dechov 
Didn't know about this trick, thanks! Will make a new PR as a fix this week.

**Comment by veljkho** [comment]
Fixed in another [pull request](https://github.com/Automattic/woocommerce-payments/pull/2329).

**Pull request merged**
