### PR TITLE
E2E test for "Merchant / Order / Manual capture" flow

### PR DESCRIPTION
**Pull request by rodelgc**
Closes https://github.com/Automattic/woocommerce-payments/issues/2211

#### Changes proposed in this Pull Request

Title: E2E Test for the flow "Merchant / Order / Manual capture"

Description: This PR adds an E2E test that covers the "Merchant / Order / Manual capture" flow. The steps in this test are consistent with the testing instructions in https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#manual-capture.

#### Testing instructions

1. Setup the E2E testing environment.
2. Run this new e2e test:
    ```
    npm run test:e2e ./tests/e2e/specs/merchant/merchant-orders-manual-capture.spec.js
    ```
3. You should see the test pass, like so:
    Screen Shot 2021-08-22 at 7 03 58 PM

### CODE REVIEW

**Comment by rodelgc** [comment]
Ready for review.

I think these 2 selectors are brittle, because it seems like their `id`s are dynamic. So these selectors might break in the future:

1. [#inspector-checkbox-control-7](https://github.com/Automattic/woocommerce-payments/blob/c2ad17d3059cff4b68aa6b9581de34a185b24efb/tests/e2e/specs/merchant/merchant-orders-manual-capture.spec.js#L19)
2. [#inspector-text-control-0](https://github.com/Automattic/woocommerce-payments/blob/c2ad17d3059cff4b68aa6b9581de34a185b24efb/tests/e2e/specs/merchant/merchant-orders-manual-capture.spec.js#L28)

However, I couldn't find a more stable way to select these 2 elements. @veljkho are we allowed to add our own `data-test-id` into the source code to prevent these 2 selectors from failing in the future?

**Comment by veljkho** [comment]
Yes we are @rodelgc. In the name of stable tests. There were discussions on that and the result is that we are allowed.

**Review by daquinons — APPROVED** [review]
Hi @rodelgc! Thank you for this, the test runs successfully 🎉

I'm going to approve this, but I don't know if you want to add those `data-test-id` now, or if you prefer to do it in another PR. Whatever you choose, feel free to request another review if needed.

**Comment by rodelgc** [comment]
> if you want to add those `data-test-id` now, or if you prefer to do it in another PR.

Thank you very much for the review @daquinons! And nice to meet you 👋 
I'll add the test id on the next PR I'll submit.

**Pull request merged**
