### PR TITLE
Bump Required Versions for 2.6 Release

### PR DESCRIPTION
**Pull request by adrianduffell**
#### Changes proposed in this Pull Request

Bumps minimum required versions for the 2.6 release.

This PR bumps the required WooCommerce version to 5.2, as per the [L-2 transition timeline](https://developer.woocommerce.com/2021/05/12/woocommerce-payments-is-adopting-a-new-version-support-policy/).

The `WC requires at least` version remains at 4.0, as it is pending improvements in issue https://github.com/Automattic/woocommerce-payments/issues/1775 first.

#### Testing instructions

* Check that versions match the [L-2 transition timeline](https://developer.woocommerce.com/2021/05/12/woocommerce-payments-is-adopting-a-new-version-support-policy/).

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

**Comment by adrianduffell** [comment]
@jrodger Could this make it into the 2.6 release?

**Comment by adrianduffell** [comment]
I've now also bumped `WC tested up to` in  ea27500.

**Review by vbelolapotkov — APPROVED** [review]
LGTM! Thanks @adrianduffell !

@jrodger do we need to rebase on top of release testing branch before merging?

**Comment by adrianduffell** [comment]
@jrodger now merged.

> Thanks so much for staying on top of these @adrianduffell.

No problems at all. I'd like to document the version bumping process and then I think this could be a step in the release cycle. In the meantime I'm happy to keep on top of it. I'll aim to create the PRs earlier next time!

**Pull request merged**
