### PR TITLE
[WIP] Transactions reporting API

### LINKED ISSUE #6342: Create API endpoint for retrieving filtered list of transactions
### Description
Review the existing API endpoint for retrieving transactions to determine if it meets the schema requirements for data reporting while maintaining backward compatibility. If the existing endpoint is sufficient, modify it to include the ability to retrieve a filtered list of transactions based on the provided parameters. If the existing endpoint does not meet the requirements, create a new API endpoint to fulfill the transaction retrieval needs.

The following endpoint need to be checked/added:

[Captures](https://href.li/?https://github.com/Automattic/woocommerce-payments/commit/a3fabba4aff238cb4a0752fb5dd60432db3727dd#diff-f5ce5009262d1356eb28b2a0e36b3473d8bb278e2b61534579520ca7c4918ee3) – includes/core/server/request/class-list-transactions.md

## Filtering Parameters
- `date_before` (string, optional): Filters transactions that took place before this specified date. The date format should be in 'date-time'.
- `date_after` (string, optional): Filters transactions that happened after this particular date. The date format should be in 'date-time'.
- `date_between` (array): Allows you to filter transactions that occurred between specific dates.
- `order_id` (integer, optional): Filters transactions by their associated order ID.
- `deposit_id` (string, optional): Enables transaction filtering based on the linked deposit ID.
- `email` (string, optional): Filters transactions according to the customer's email.
- `payment_method_id` (string, optional): This parameter is for filtering transactions based on the payment method used.
- `type` (string, optional): Filters transactions where the type matches a specified value.
- `transaction_id` (string, optional): Filters transactions based on their unique transaction ID.
- `source_id` (string, optional): Filters transactions using their unique source ID.
- `match` (string, optional): A match filter for transactions.
- `search` (array, optional): A search parameter for transactions.
- `user_timezone` (string, optional): Incorporates the timezone into date filtering.
- `orderby` (string, optional): Sorts transactions based on the specified field. By default, it's sorted by 'date'.
- `order` (string, optional): Orders transactions based on the given field. By default, it's in descending ('desc') order. It can be either 'asc' (ascending) or 'desc' (descending).
- `page` (integer, optional): Indicates the page number. By default, it's set to 1, with a minimum limit of 1.
- `per_page` (integer, optional): Specifies the page size. By default, it's set to 25, with a minimum limit of 1 and a maximum limit of 100.

## Request Schema
The request schema for the API endpoint should follow the specifications outlined in the following GitHub issue: [#6336](https://github.com/Automattic/woocommerce-payments/issues/6336). Please refer to the schema provided in the issue and incorporate it into the API endpoint implementation.

## Response
The API endpoint should return a list of transactions that match the specified filters. Each transaction should include relevant information such as transaction ID, timestamp, type, order ID, deposit ID, customer email, payment method details, and transaction details.

## Note
Please ensure that the API endpoint implementation adheres to RESTful design principles and follows proper error handling practices. If the existing endpoint is sufficient, modify it to accommodate the new requirements. If it is not sufficient, create a new API endpoint to fulfill the transaction retrieval needs.

### PR DESCRIPTION
**Pull request by zmaglica**
Fixes #6342

#### Changes proposed in this Pull Request

The purpose of this PR is to include a reporting API for transactions. The main difference between the existing transactions API endpoint and the new one is that this API endpoint is defined by using [WordPress REST API Schema](https://developer.wordpress.org/rest-api/extending-the-rest-api/schema/). Besides using the REST API schema, new filters have been added and schema is created for this specific resource which will be handy in the future.

#### Testing instructions

1. Make sure that you have configured WooCommerce Rest API
2. Make sure that you have some transactions in the database if you test locally
3. Execute the following endpoint `wp-json/wc/v3/payments/reports/transactions` and make sure that you have some results
4. Apply any of the filters that are added like order_id_is, date_after,source_device_is, ....

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6652` or branch name `dev/6342-reporting-transaction-api` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=dev/6342-reporting-transaction-api) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: f0b2ab3a24f723b370c7c07cd54d9e49646af758
- Build time: 2023-08-03 06:39:42 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by jessy-p** [comment]
@souravdebnath1986 Looking for feedback on API endpoint which is `payments/reports/authorizations` and `payments/reports/transactions`.

**Review by jessy-p — COMMENTED** [review]
I noticed that the parameters mentioned in PRD has slight differences than the schemas in PR. (naming, additional params etc). 
Could you please document these three side by side in a table
PRD schema vs Transaction vs Authorization, so that we could have a better review/awareness of the changes and discuss the reason for them

**Comment by zmaglica** [comment]
> I noticed that the parameters mentioned in PRD has slight differences than the schemas in PR. (naming, additional params etc). Could you please document these three side by side in a table PRD schema vs Transaction vs Authorization, so that we could have a better review/awareness of the changes and discuss the reason for them

The main difference is that authorizations and transactions are similar in terms of fields, but they do a totally different thing. For example, authorization endpoints add additional fields like  amount captured, amount refunded, outcome type, ...

Here is the difference between authorizations, transactions and PRD schema:

| Field                | Transaction schema | Authorization Schema | PRD Schema | Comment                                                                                                                                                   |
|----------------------|--------------------|----------------------|------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------|
| transaction_id       | Yes                | Yes                  | Yes        |                                                                                                                                                           |
| timestamp            | Yes                | Yes                  | Yes        |                                                                                                                                                           |
| order_id             | Yes                | Yes                  | Yes        |                                                                                                                                                           |
| transaction type     | Yes                | No                   | Yes        | There is no type here since they are all 'charges'                                                                                                        |
| transaction currency | Yes                | Yes                  | Yes        |                                                                                                                                                           |
| amount               | Yes                | Yes                  | Yes        |                                                                                                                                                           |
| exchange rate        | No                 | Yes                  | Yes        | All charges are in store currency so we don't have an exchange rate here                                                                                     |
| deposit currency     | No                 | Yes                  | Yes        | Authorizations are not related to the deposits, so all deposits fields are not presented there. Deposit currency can be obtained from store currency field |
| fees                 | Yes                | Yes                  | Yes        |                                                                                                                                                           |
| net amount           | Yes                | Yes                  | Yes        |                                                                                                                                                           |
| risk level           | Yes                | Yes                  | Yes        |                                                                                                                                                           |
| email                | Yes                | Yes                  | Yes        | The name of the field is customer email to make it more clearer.                                                                                          |
| country              | Yes                | Yes                  | Yes        | The name of the field is country email to make it more clearer.                                                                                           |
| deposit date         | No                 | No                   | Yes        | It can be obtained if we join deposits table, but this action is expensive so I removed it for now. If needed, it can be obtained from deposits endpoint  |
| deposit id           | No                 | Yes                  | Yes        | Charges or authorizations are not related to deposits                                                                                                     |
| deposit status       | No                 | Yes                  | Yes        | Not related to deposits                                                                                                                                   |
| channel              | Yes                | Yes                  | No         | It's a nice field we got it for free, so I included it                                                                                                    |
| order                | No                 | Yes                  | No         | Order object that holds additional data for order. It was already included in the transaction API from server so I kept it                                    |
| customer_currency                | No                 | Yes                  | Yes         | The field name is changed to make more clear. authorizations have only one currency                                   |
| customer_name                | Yes                 | Yes                  | No         | It was 'free' and presented in both tabels, so I included it                                   |
| amount_captured                | Yes                 | No                  | No         | Amount captured is specific only to authorizations and could be an interesting field to have                         |
| amount_refunded                | Yes                 | No                  | No         | Amount refunded is specific only to authorizations and could be an interesting field to have                         |
| refunded                | Yes                 | No                  | No         | Refunded is specific only to authorizations and could be an interesting field to have                         |
| outcome_type                | Yes                 | No                  | No         | Outcome type is specific only to authorizations and could be an interesting field to have                         |
| status                | Yes                 | No                  | No         | Status is a specific field for authorization schema, since it tells status of authorization. In transactions, this field is not presented since transactions can be deposit, charge, with their own custom statuses.                         |

**Comment by souravdebnath1986** [comment]
@zmaglica and @jessy-p I have created a [google doc](https://docs.google.com/document/d/1rrBCEzvyXmg_8lQQEbQkV3Ew8rIZnQyDRsqoG1fuOiE/edit) and put in my comments there.

**Comment by naman03malhotra** [comment]
@zmaglica is it still in WIP?

**Comment by naman03malhotra** [comment]
Closing in favor of https://github.com/Automattic/woocommerce-payments/pull/7066

**Pull request closed without merging**
