### PR TITLE
Fix multicurrency widget error on post/page edit screen

### LINKED ISSUE #7135: [GlobalStep] "This block has encountered an error and cannot be previewed." message displayed after inserting "Currency Switcher" block on a new page.
### Bug Description:
"This block has encountered an error and cannot be previewed." message displayed after inserting "Currency Switcher" block on a new page.

### Environment:
Woocommerce Version: WooCommerce 8.0.3
WooCommerce Payments: 6.5.0-test-1
WordPress version: v6.3.1

PC:
Windows 10,
Chrome(Version 116.0.5845.141)
Firefox (Version 117.0)

### Steps To Reproduce:
1. Create any test site.
2. Install and activate all the required plugins.
4. Complete the setup.
5. Go to Pages > Add New and add a test page to your site.
6. Open the block editor for the new page.
7. Add a new block to this page and select Currency Switcher Block.
8. Observe that, "This block has encountered an error and cannot be previewed." message displayed after inserting "Currency Switcher" block on a new page.

### Instruction Link:
https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#as-a-block-via-the-editor

### Actual Result:
"This block has encountered an error and cannot be previewed." message displayed after inserting "Currency Switcher" block on a new page.

### Expected Result:
"Currency Switcher" block should be add on a new page without any error message.

### Video:

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WC Version: 8.0.3
REST API Version: ✔ 8.0.3
WC Blocks Version: ✔ 10.6.6
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.3.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.57 (Unix) OpenSSL/1.0.2g
PHP Version: 8.0.30
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.0.3
WC Database Prefix: wp_
Total Database Size: 8.26MB
Database Data Size: 5.73MB
Database Index Size: 2.53MB
wp_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.13MB + Index: 0.14MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.20MB + Index: 0.20MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.16MB + Index: 0.14MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.17MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.45MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 0.52MB + Index: 0.50MB + Engine InnoDB
wp_posts: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 25
page: 9
post: 2
product: 23
product_variation: 7
revision: 2
shop_coupon: 1
shop_order: 83
shop_order_refund: 5
shop_subscription: 22
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (7) ###

Query Monitor: by John Blackbourn – 3.13.1
Code Snippets: by Code Snippets Pro – 3.4.2
Companion Plugin: by Osk – 1.30
WooCommerce Payments Dev Tools: by Automattic –
WooCommerce Payments: by Automattic – 6.5.0-test-1
WooCommerce Subscriptions: by WooCommerce – 5.4.0
WooCommerce: by Automattic – 8.0.3

### Inactive Plugins (2) ###

Akismet Anti-Spam: Spam Protection: by Automattic - Anti Spam Team – 5.2
Hello Dolly: by Matt Mullenweg – 1.7.2

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.5.2
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://sure-stink.jurassic.ninja
Subscriptions-core Library Version: 6.2.0
Subscription Statuses: wc-active: 21
wc-cancelled: 1

WooCommerce Account Connected: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — California

### Subscriptions by Payment Gateway ###

WooPayments: wc-active: 21
wc-cancelled: 1

### Payment Gateway Support ###

WooPayments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
subscription_amount_changes
subscription_date_changes
tokenization
add_payment_method

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-09-06 06:26:59 +00:00
Options: ✔
Notes: 65
Onboarding: skipped

### WooCommerce Payments ###

Version: 6.5.0-test-1
Connected to WPCOM: Yes
Blog ID: 223146876
Account ID: acct_1NmtLSFdaikvCMOd

### Action Scheduler ###

Canceled: 15
Oldest: 2023-09-05 08:15:31 +0000
Newest: 2023-09-05 13:43:00 +0000

Complete: 535
Oldest: 2023-09-05 06:27:09 +0000
Newest: 2023-09-05 09:26:49 +0000

Failed: 8
Oldest: 2023-09-05 07:13:44 +0000
Newest: 2023-09-05 12:17:57 +0000

Pending: 27
Oldest: 2023-09-05 14:49:13 +0000
Newest: 2023-11-05 09:28:10 +0000

### Status report information ###

Generated at: 2023-09-05 14:47:11 +00:00
`

</details>

### PR DESCRIPTION
**Pull request by tpaksu**
Fixes #7135

#### Changes proposed in this Pull Request

This removes the multi currency feature enabled/disabled check in the `useCurrencies` hook that was added for making the fraud protection level modals show the right text when multi currency is disabled on https://github.com/Automattic/woocommerce-payments/pull/5942, but now the modals are removed and we don't need that. So we can remove the check that's causing the Currency switcher widget to produce an error, because `wcpaySettings` global variable is not defined on the Post/Page edit screens, which makes the hook fail because it depends on it.

The components that use the `useCurrencies` hook are:
- UPE LPM enable/disable screen additional currency info box
- Multi currency settings page
- Multi currency single currency settings page
- Multi currency onboarding page
- Currency switcher widget

##### Testing the widget

- Create a new post and add the currency switcher widget
- You should not get an error
- Preview the page
- You should see the working switcher
- Repeat this for a page

#### UPE LPM enable/disable screen additional currency info box
- Remove all enabled currencies 
- Disable UPE from the three dots menu on the top right of the LPM selection box, you can click cancel on the feedback request.
- Enable it back by clicking "Enable on your store" button on the same box.
- You should be redirected to the LPM onboarding screen.
- Enable one LPM that requires EUR as an enabled currency.
- You should see the box stating that EUR will be enabled. 
- Try it with multi currency disabled.
- You shouldn't see the box, enabling the LPM's should work, but MC shouldn't get enabled.

#### Multi currency settings page
- Will work as usual, and when MC is disabled, it should be hidden. 

#### Multi currency single currency settings page
- Will work as usual, and when MC is disabled, it should be hidden. 

#### Multi currency onboarding page
- On WooCommerce > Home page, in the "Inbox" box, find the task which has the title "[Sell worldwide in multiple currencies](http://localhost:8082/wp-admin/admin.php?page=wc-admin&path=/payments/multi-currency-setup)" (Or click to this link if you're using Docker)  
- When multi currency is enabled, you should see the currencies and can enable some
- When multi currency is disabled, you should get an error stating the currency retrieval has failed. (I don't know if we should fix this, as it looks like an edge case.)

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7141` or branch name `fix/7135-currency-switch-widget-on-edit-post` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/7135-currency-switch-widget-on-edit-post) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 1f239f3fcf0d1aaa1900e54aae85da43134a3493
- Build time: 2023-09-06 15:44:29 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by jessepearson** [comment]
> UPE LPM enable/disable screen additional currency info box

I feel like if someone is enabling a LPM that requires another currency that isn't the store currency, we should do one of two things:

* Enable MC by default and state it in that message.
* Inform them that they need to enable MC manually so that the additional currency can be added. 

If we don't do either one of these then they will not be able to take payments with the LPM.

We could probably address this in another issue so that this fix can be added.

> Multi currency onboarding page
> When multi currency is disabled, you should get an error stating the currency retrieval has failed. (I don't know if we should fix this, as it looks like an edge case.)

That's a bug, the point of the onboarding is to enable Multi-Currency for the merchant. I created a new issue and added it to this sprint:

* https://github.com/Automattic/woocommerce-payments/issues/7151

**Review by jessepearson — APPROVED** [review]
This fixes the issue that we were seeing. I've added an additional comment about possibly creating another issue about the LPMs, and created a new issue for the MC onboarding.

**Comment by tpaksu** [comment]
Thanks for reviewing this and creating the necessary issue @jessepearson! For the other thing, yes we need another issue for that too. I'll open an issue for that.

**Pull request merged**
