### PR TITLE
Return correct product prices datatype in WCPay

### LINKED ISSUE #2827: Wrong returning datatype for prices causes malformed responses
_I'm not 100% sure if we should consider this a bug so I open the question: WooCommerce payments seems to be doing things differently than WooCommerce core regarding price datatypes, hence causing problems when we use these assumptions elsewhere (like in the WooCommerce app, or extensions like Auctions for WooCommerce )._

### Description 

Some merchants have reported issue syncing their product lists when using the WooCommerce app. Looking through their error logs it seemed that some  plugin was altering the return type of product price to numeric values instead of string as we're expecting the values to be (for both the core WooCommerce plugin and the app). This causes parsing failure and hence the syncing failure.

After further debugging we discovered that this was actually WooCommerce Payments. From what I gather is altering the product meta and saving/updating it as Integer rather than String. Some example errors when the JSON decoder attempts to fetch the object:

```
2021/08/05 17:05:26:053  ⛔️ Error loading ProductVariation & Product for siteID: 191752495 productID:27454 variationID:27459 error:AnyError(error: Swift.DecodingError.typeMismatch(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "data", intValue: nil), CodingKeys(stringValue: "regular_price", intValue: nil)], debugDescription: "Expected to decode String but found a number instead.", underlyingError: nil)))
```

Related issues:
https://github.com/woocommerce/woocommerce-ios/pull/3679
https://github.com/woocommerce/woocommerce-ios/pull/4901
https://github.com/woocommerce/woocommerce-ios/issues/4737

Other cases where the plugin alters the product meta and expects a String as returning value, but fails due to the different returning datatype:

https://github.com/woocommerce/woocommerce-ios/issues/2822
https://github.com/woocommerce/woocommerce-ios/issues/3511

Note how the price becomes a double with ~20 decimals in this user site, rather than returning a formatted string :

### PR DESCRIPTION
**Pull request by oaratovskyi**
Fixes #2827 

#### Changes proposed in this Pull Request

Return prices as a string according to the convention with WC Core described in https://github.com/Automattic/woocommerce-payments/issues/2827.

Filters actions that should return prices as string:
- `woocommerce_product_get_price`
- `woocommerce_product_get_regular_price`
- `woocommerce_product_get_sale_price`
- `woocommerce_product_variation_get_price`
- `woocommerce_product_variation_get_regular_price`
- `woocommerce_product_variation_get_sale_price`
- `woocommerce_variation_prices`

#### Testing instructions

* As a shopper go to the Shop page, switch the currency to EUR.
* Add simple product to cart.
* Add variable product to cart.
* Add sale product to cart.
* Switch currencies to JPY and USD and see that the prices are shown correctly.
* Checkout and Pay, should be good without errors.

-------------------

- [x] Added changelog entries to both `readme.txt` and `changelog.txt` (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply)

### CODE REVIEW

**Comment by oaratovskyi** [comment]
@Automattic/sigma I am not sure if this needs to be added for GlobalStep testing. Any thoughts on it?

**Comment by daquinons** [comment]
> @Automattic/sigma I am not sure if this needs to be added for GlobalStep testing. Any thoughts on it?

@oaratovskyi Are there any features that could be directly affected by this? In general, I would say that the biggest one would be MC orders, so I think adding a point to test buying with different currencies making sure that the conversion works even with the new format could be a good thing 💯

**Comment by oaratovskyi** [comment]
@daquinons agree with you about the orders in different currencies, double-check won't hurt. I wonder if GlobalStep could test it with a mobile app to see that everything works as expected?

**Comment by daquinons** [comment]
> @daquinons agree with you about the orders in different currencies, double-check won't hurt. I wonder if GlobalStep could test it with a mobile app to see that everything works as expected?

Not sure how the team handles the release testing! @iamgabrielma Could you help with that?

**Comment by daquinons** [comment]
> @daquinons agree with you about the orders in different currencies, double-check won't hurt. I wonder if GlobalStep could test it with a mobile app to see that everything works as expected?

@oaratovskyi  That's a good idea! Pinging @shiki 👋 How is the best way to test this kind of change? Do you have any testing process in place where you could add this?

**Comment by shiki** [comment]
Hi! 

Based on my understanding of the original issue https://github.com/Automattic/woocommerce-payments/issues/2827, the problem is that the multi-currency feature is causing the Products List syncing to fail. So perhaps a regression test would be simply opening the Products tab in the app? 



I couldn't reproduce the issue described in #2827 though. I had the multi-currency feature configured but the products list still loads fine for me. 🤔 

---

Based on the testing steps described in this PR, perhaps another regression test would be something like this: 

1. Add simple product to cart.
2. Add variable product to cart.
3. Add sale product to cart.
4. Switch currencies to JPY and USD and see that the prices are shown correctly.
5. Switch to JPY again and submit the order.
6. Open the order in the app and confirm that the app displays the correct JPY currency in the order details.

Here's what is shown in the app for my site that is mainly USD. It shows JPY for this specific order:



They won't be able to see the In-Person Payments' Collect Payment button in this case because, AFAIK, we currently only support USD in the app. 

But I suppose they could switch back to USD in step 5 above and confirm that they can collect payment through In-Person Payments if they have a card reader.

---

Does this help or is it confusing? 😅 Let me know!

**Comment by daquinons** [comment]
> Hi!
> 
> Based on my understanding of the original issue #2827, the problem is that the multi-currency feature is causing the Products List syncing to fail. So perhaps a regression test would be simply opening the Products tab in the app?
> 
> 
> 
> I couldn't reproduce the issue described in #2827 though. I had the multi-currency feature configured but the products list still loads fine for me. 🤔
> 
> Based on the testing steps described in this PR, perhaps another regression test would be something like this:
> 
>     1. Add simple product to cart.
> 
>     2. Add variable product to cart.
> 
>     3. Add sale product to cart.
> 
>     4. Switch currencies to JPY and USD and see that the prices are shown correctly.
> 
>     5. Switch to JPY again and submit the order.
> 
>     6. Open the order in the app and confirm that the app displays the correct JPY currency in the order details.
> 
> 
> Here's what is shown in the app for my site that is mainly USD. It shows JPY for this specific order:
> 
> 
> 
> They won't be able to see the In-Person Payments' Collect Payment button in this case because, AFAIK, we currently only support USD in the app.
> 
> But I suppose they could switch back to USD in step 5 above and confirm that they can collect payment through In-Person Payments if they have a card reader.
> 
> Does this help or is it confusing? 😅 Let me know!

Thanks for the quick response! I think this will be helpful in case we use Globalstep for testing that :) 

Seems like the original issue was mostly fixed on the iOS side in here https://github.com/woocommerce/woocommerce-ios/pull/4901 that's why you couldn't reproduce it.

Thanks a lot!

@oaratovskyi Tomorrow I can help you testing this :) I've never used our iOS app but seems like a fun thing to try! Just checking the list is not breaking with this fix (because it was fixed before), and making a simple purchase will be enough. I haven't figured out if we can ask GS to test the iOS app in our workflow.

**Comment by oaratovskyi** [comment]
Thanks, @shiki for a quick response! It's not confusing, it makes sense 🙂 
@daquinons great! I am also curious how our mobile app works 👍

**Comment by daquinons** [comment]
> Thanks, @shiki for a quick response! It's not confusing, it makes sense 🙂 @daquinons great! I am also curious how our mobile app works 👍

I just tested the iOS app with orders in multiple currencies and worked well :) However because this problem was already being accounted there, I tried to check if the response was properly arriving in the API.

I installed a proxy to check the API responses. With these changes, this is the response
IMG_8215

Price is a string.

Without the changes, as develop does, this is the response

IMG_8216

So seems like it's doing what is intended @oaratovskyi 👍

**Comment by oaratovskyi** [comment]
@daquinons Thanks a lot for your effort in testing! That way I suppose we don't need GS testing here, you already covered everything that is needed.

**Review by daquinons — APPROVED** [review]
Looks good and the type returned in the API is a string now as tested 👍

**Pull request merged**
