### PR TITLE
Re-enable Direct-to-Checkout Feature Flag in WooPay OTP Iframe

### PR DESCRIPTION
**Pull request by rafaelzaleski**
Re-enable Direct-to-Checkout Feature Flag in WooPay OTP Iframe that was removed in #8116.

#### Testing instructions

Follow the testing instructions from https://github.com/Automattic/woocommerce-payments/pull/8133.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8365` or branch name `fix/re-add-direct-checkout-feature-flag-to-otp-iframe` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/re-add-direct-checkout-feature-flag-to-otp-iframe) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: ea7c138b89d28a0702f15b2d806a12b0f3c774b1
- Build time: 2024-03-15 14:03:13 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by lovo-h — CHANGES_REQUESTED** [review]
Code changes look good but the required testing instructions do not pass.

I do not believe the tests are failing due to the changes in this PR, but I wanted to confirm whether this was expected and whether this issue is being tracked elsewhere.

### Testing Instructions
* Scenario 1 with `_wcpay_feature_woopay_direct_checkout = 1`:
  * ✅ You are not auto-redirected to the WooPay checkout after navigating to Merchant checkout with an email prepopulated.
  * ✅ The WooPay OTP modal does not appear.
* Scenario 2 with `_wcpay_feature_woopay_direct_checkout = 1`:
  * ✅ The WooPay OTP modal appears after entering the email.
  * ✅ If authenticated, you are auto-redirected to the WooPay checkout after entering the email.
* Scenario 3 with `_wcpay_feature_woopay_direct_checkout = 1`:
  * ✅ The WooPay OTP modal does not appear after entering an email not associated with a WooPay account.
  * ✅ You are not auto-redirected to the WooPay checkout after entering an email not associated with a WooPay account.
* Scenario 4 with `_wcpay_feature_woopay_direct_checkout = 0`:
  * Scenario 1:
    * ❌ You are auto-redirected to the WooPay checkout after navigating to Merchant checkout with an email prepopulated.
    * ❌ The WooPay OTP modal does appear.
  * Scenario 2:
    * ✅ The WooPay OTP modal appears after entering the email.
    * ✅ If authenticated, you are auto-redirected to the WooPay checkout after entering the email.
  * Scenario 3:
    * ✅ The WooPay OTP modal does not appear after entering an email not associated with a WooPay account.
    * ✅ You are not auto-redirected to the WooPay checkout after entering an email not associated with a WooPay account.

### Video Attachments

**Scenario 4 / Scenario 1 Video Attachment**

https://github.com/Automattic/woocommerce-payments/assets/6844516/bfdb67c1-8ae0-4a18-acb4-7067be395c2e

`Scenario 4 / Scenario 1 Video Attachment` Description:
* Confirms: `_wcpay_feature_woopay_direct_checkout = 0`.
* Confirms: Manually inputting an email redirects to WooPay checkout.
* Confirms: The expected behavior from `Scenario 4 / Scenario 1` does not occur.

**Comment by rafaelzaleski** [comment]
@lovo-h, the `wc/store/payment` endpoint ([link](https://github.com/Automattic/woocommerce-payments/blob/9e98720f82da1ef96994567c71ed521efcdfa857/client/checkout/woopay/email-input-iframe.js#L620)) is accessible only within the checkout block context. In the shortcode checkout, it returns an empty object, leading to the user redirection condition being false (`hasWCPayPaymentMethod = false`).

I'll create a new issue to monitor this bug. I believe we can proceed with merging this PR as it isn't the source of the malfunction. I also left a [comment in the PR](https://github.com/Automattic/woocommerce-payments/pull/8116#issuecomment-1998649258) that introduced this condition.

**Comment by rafaelzaleski** [comment]
Issue created: https://github.com/Automattic/woocommerce-payments/issues/8398

**Comment by lovo-h** [comment]
@rafaelzaleski , good find.

> I'll create a new issue to monitor this bug. I believe we can proceed with merging this PR as it isn't the source of the malfunction.

Thank you. I agree, that sounds like a good plan 👍

**Review by lovo-h — APPROVED** [review]
LGTM! 👍

**Pull request merged**
