### PR TITLE
Update readme.txt with better links, accurate info

### LINKED ISSUE #5675: Improvements to WP.org plugin page via readme.txt
> TRY IT NOW

We could link to the [Startup Guide](https://woocommerce.com/document/woocommerce-payments/startup-guide/) under this section.

> How do I set up a store for a client?

The text in this FAQ entry could link [here](https://woocommerce.com/document/woocommerce-payments/account-management/developer-or-agency-setup/).

> How is WooCommerce Payments related to Stripe?

This section uses the older "power by Stripe" language, whereas we now prefer "built in partnership with Stripe".

> Are there Terms of Service and data usage policies?

This section should probably just link [here](https://woocommerce.com/document/woocommerce-payments/our-policies/), which in turn has the TOS, but also all our other WC Pay-related policies, etc.

### PR DESCRIPTION
**Pull request by aheckler**
Fixes #5675

#### Changes proposed in this Pull Request

Update `readme.txt` with better links and more accurate information.

These changes stem from a Slack thread (p1677830070275559-slack-CGGCLBN58) where I was asked to do a quick review of the language, links, etc. we use on our WP.org product page. I found a few items that could use better links or better language, and this PR is the result.

This PR only touches the `readme.txt` file that WP.org parses to create this page:

https://wordpress.org/plugins/woocommerce-payments/

... so there's no code changes, no tests involved, nothing. I'm not sure if this even needs a changelog entry?

Let me know if this can be improved somehow and I'll do my best. 😛

### CODE REVIEW

**Comment by aheckler** [comment]
Changelog file added. Tests are happy now. :)

**Review by barryhughes — COMMENTED** [review]
Hi @aheckler! This looks good to me and the various links all appear to work ... but I'm not normally involved with WooCommerce Payments. Is it possible you intended to select a different reviewer?

**Comment by aheckler** [comment]
Oops! I was trying to add @shendy-a8c as the current Transact janitor, but I must have misclicked. 🤦 Sorry!

**Review by shendy-a8c — APPROVED** [review]
Thank you for this change. It looks good. I checked for typo and made sure links are working.

**Comment by shendy-a8c** [comment]
I stumbled into this PR when cleaning up my email inbox. Looks like this PR is good to merge. Merging it on behalf of @aheckler.

**Pull request merged**
