### PR TITLE
Improve the transition from the WCPay KYC to the WC Admin Payments Task

### LINKED ISSUE #37542: [Enhancement]: Improve the transition from the WCPay KYC to the Payments Task
### Describe the solution you'd like

When a user completes the KYC and returns to the task, the screen does not provide any acknowledgement the merchant completed the process. Instead a list of other payment providers is shown.

To solve this a completion screen could be shown to provide a better transition and acknowledge the progress the merchant has made.

**Edit:**

Per the comments below, we can redirect to the WooPayments success screen. The return URL is handled in the WooPayments plugin [here](https://github.com/Automattic/woocommerce-payments/blob/a090a8571feafb937a3271d9c56faf356f612b1d/includes/class-wc-payments-account.php#L1403-L1404). 

I think the URL will be `static::get_overview_page_url()` + `&wcpay-connection-success=1`

We will now also need to add a new `$wcpay_connect_from` case to handle LYS. This should redirect back to the LYS hub.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by chihsuan**
Fixes https://github.com/woocommerce/woocommerce/issues/37542

#### Changes proposed in this Pull Request

Improve the transition from the WCPay KYC to the WC Admin Payments Task.

When a user from the payment task completes the KYC, send users back to the payment overview page with the success message.

Code changes:

- Remove the `WCADMIN_PAYMENT_TASK` case from the switch statement in the `get_onboarding_return_url` method 

#### Testing instructions

* [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=update/redirect-to-payment-screen-for-wcadmin-task) 🚀
* Go to WooCommerce
* Select the US as store country
* Go to WooCommerce > Home
* Click on `payment task`
* Click on `Connect your store` 
* Complete KYC https://woocommerce.com/document/woopayments/testing-and-troubleshooting/testing/
* Confirm you're redirected back to payment overview screen with success message

Screenshot 2024-05-31 at 12 26 41

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times.
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [x] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8893` or branch name `update/redirect-to-payment-screen-for-wcadmin-task` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=update/redirect-to-payment-screen-for-wcadmin-task) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 01e5f2584b95ca9b09df2b080ec8648ea52d2c11
- Build time: 2024-06-04 08:20:50 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by ilyasfoo — APPROVED** [review]
Tests well! Additionally, perhaps we can remove or at least deprecate the following? It doesn't seem to be used anywhere

https://github.com/Automattic/woocommerce-payments/blob/6c7951d437f0764197bb6fcb4e8780abba0dbf3a/includes/class-wc-payments-account.php#L1235-L1249

**Comment by chihsuan** [comment]
> Tests well! Additionally, perhaps we can remove or at least deprecate the following? It doesn't seem to be used anywhere
> 

Good point! Removed in bbbf72392e94096d2b8a7ac0c216b2ab9b1b6cb8

**Comment by chihsuan** [comment]
> Tests well! Additionally, perhaps we can remove or at least deprecate the following? It doesn't seem to be used anywhere
> 

Good point! Deprecated it in bbbf72392e94096d2b8a7ac0c216b2ab9b1b6cb8

**Review by vladolaru — APPROVED** [review]
The code changes LGTM and the testing instructions checked out! :shipit:

**Pull request merged**
