### PR TITLE
Add descriptive validation to first and last names and business name fields in PO flow

### LINKED ISSUE #6783: [PO] Error validation text need to be more specific
### Description
Error validation in the Progressive Onboarding flow has a few examples where the error message is too generic and not helpful for the user.

In these examples, rather than "Please provide a response", the error string would be more specific.

> Please provide a first name
> Please provide a last name
> Please provide a business name

image

image

Thanks to @poligilad-auto for pointing this out. Reference: p4ya8V-5Ov
cc @dmallory42

### PR DESCRIPTION
**Pull request by daquinons**
Fixes #6783

#### Changes proposed in this Pull Request

This issue adds a descriptive error messages to the empty first name, last name and business name fields.

Screenshot 2023-07-18 at 13 03 27

Screenshot 2023-07-18 at 13 04 46

#### Testing instructions
- Set your currently onboarded account as deleted in the database
- Go Dev Tools and enable Progressive Onboarding
- Select "live account" in the selection mode
- Don't fill "First name" and "Last name" and see the updated messages
- Fill them and go to the next screen
- Don't fill "Business name" and see the updated message
- Make sure the generic message is not there anymore

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6795` or branch name `fix/6783-specific-validation-text-po` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=fix/6783-specific-validation-text-po) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: a435959ad2163277f68c86b783d19d6e0a71dffa
- Build time: 2023-07-20 06:16:55 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by dmallory42 — COMMENTED** [review]
LGTM! Thanks for working on this. This covers perfectly the changes requested in #6783, however I noticed a few other quick things I think we could also consider (either fixing in this PR or a new issue):

Screenshot 2023-07-18 at 10 40 20

- For the business country field, I think we could add a custom validation message - my suggestion would be `Please select a country`
- For the "What type of goods or services does your business sell" field, I noticed we don't have a validation message at all (even though it is required). We should try and fix that (maybe this one could be a new issue since it could be more complex).

Let me know what you think and then I'm happy to approve the PR! 🙂

**Comment by daquinons** [comment]
> LGTM! Thanks for working on this. This covers perfectly the changes requested in #6783, however I noticed a few other quick things I think we could also consider (either fixing in this PR or a new issue):
> Screenshot 2023-07-18 at 10 40 20
> 
>     * For the business country field, I think we could add a custom validation message - my suggestion would be `Please select a country`
> 
>     * For the "What type of goods or services does your business sell" field, I noticed we don't have a validation message at all (even though it is required). We should try and fix that (maybe this one could be a new issue since it could be more complex).
> 
> 
> Let me know what you think and then I'm happy to approve the PR! 🙂

Thank you Dan!

I've added the message for the country and the MCC fields.

Screenshot 2023-07-19 at 14 57 08


As you mention, the MCC is not displaying any message. However, I've discovered that the error is properly passed to the component
Screenshot 2023-07-19 at 14 59 21

I'm going to create a separate issue because it's going to require a bit of deep refactoring, as right now the GroupedSelectControl is not being wrapped by the Field component, which is the one that displays the error https://github.com/Automattic/woocommerce-payments/blob/445cb6647808892037d0f9e5d37c6695c9ecc6eb/client/components/form/fields.tsx#L48

If you agree with it, let's approve with this one that adds its right message and let's take care of the refactoring in a separate issue which will have a much bigger complexity.

**Comment by daquinons** [comment]
@dmallory42 Issue created! https://github.com/Automattic/woocommerce-payments/issues/6813

**Review by dmallory42 — APPROVED** [review]
Thanks for addressing that feedback, @daquinons! 

I totally agree, approved the PR and we'll handle the MCC error not showing in another issue. Nice work!

**Pull request merged**
