### PR TITLE
Remove platform checkout feature flag for upe

### PR DESCRIPTION
**Pull request by harriswong**
Fixes https://github.com/Automattic/woocommerce-payments/issues/3807

#### Changes proposed in this Pull Request
Remove platform checkout feature flagged codes for UPE checkout block.

#### Testing instructions
1. With "shortcode checkout", when you finished typing the email address in the checkout form, you should see an API request that goes out to check if there is a user in platform checkout. 
2. With "block" checkout, when you finished typing the email address in the checkout form, there is no API request going out.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) : _Add link here / 'QA Testing Not Applicable'_

### CODE REVIEW

**Comment by harriswong** [comment]
@superdav42 @waclawjacek We are removing the platform checkout feature flag around UPE block. Please let me know if there are other places we should also remove.

**Comment by superdav42** [comment]
> @superdav42 @waclawjacek We are removing the platform checkout feature flag around UPE block. Please let me know if there are other places we should also remove.

Why are we doing this? Is there something in UPE that is not compatible with platform checkout?

**Comment by superdav42** [comment]
> @superdav42 @waclawjacek We are removing the platform checkout feature flag around UPE block. Please let me know if there are other places we should also remove.

Why are we doing this? Is there something in UPE that is not compatible with platform checkout?

**Comment by harriswong** [comment]
> Is there something in UPE that is not compatible with platform checkout?

@superdav42 It's from [this](https://github.com/Automattic/woocommerce-payments/issues/3807#issuecomment-1047342578). 

@frosso is it because block checkout is not fully supported with platform checkout, so that when we enable the feature flag, block checkout remains untouched?

**Review by brettshumaker — CHANGES_REQUESTED** [review]
Looks like what you have here covers UPE, but we still need to remove it from the blocks checkout ([here](https://github.com/Automattic/woocommerce-payments/blob/develop/client/checkout/blocks/index.js))?

**Comment by harriswong** [comment]
Thanks @brettshumaker. I removed the flags from checkout/block/index.js. The only one left should be the classic one
image
Please take a look again.

**Review by brettshumaker — CHANGES_REQUESTED** [review]
Awesome, thanks for taking that out.

I did just notice that we're still rendering the "Remember your details?" section when UPE is enabled. Should we be?

**Comment by frosso** [comment]
> Why are we doing this? Is there something in UPE that is not compatible with platform checkout?
> @frosso is it because block checkout is not fully supported with platform checkout, so that when we enable the feature flag, block checkout remains untouched?

There are a couple of things here:
- In order for the platform checkout to work, we'll need to explore some changes to the UPE implementation ( paJDYF-3gI-p2 )
- The `_wcpay_feature_platform_checkout` flag controls both the "shortcode" and the "blocks" checkout. We'll start only supporting the "shortcode" checkout and make some changes to support the "blocks" checkout later

**Comment by harriswong** [comment]
> I did just notice that we're still rendering the "Remember your details?" section when UPE is enabled. Should we be?

Thanks @brettshumaker. No. "Remember your details" should be behind the feature flag. I will create a separate issue for this.

**Review by brettshumaker — APPROVED** [review]
🚢

**Pull request merged**
