### PR TITLE
Add/Update required components for progressive onboarding

### LINKED ISSUE #4744: Create or extend components needed for Progressive Onboarding
### Description

This issue will cover either creating or identifying and extending any components which will be needed for Progressive Onboarding. 

Example/psuedocode of the type of components we will need (these could be extensions of existing components or brand new components):

`<OnboardingForm>`
`<OnboardingFormStep>`
`<SocialSecurityInput>`
`<DateOfBirthInput>`

#### Required components so far:
- Searchable custom select control with categories for MCC.
- International phone number field.
- Loading bar.
- Update CustomSelectControl to match other form inputs style.
- Notice component – Use the new BannerNotice component added recently.

### Acceptance criteria

* Either create or identify and then extend any components related to Progressive Onboarding, as defined in the designs paJDYF-5IU-p2.

### PR DESCRIPTION
**Pull request by ismaeldcom**
Fixes #4744

#### Changes proposed in this Pull Request
Implement the following components following PO design.
- **LoadBar** – An infinite load bar.
- **PhoneNumberControl** – Implemented similar to Stripe KYC one, in absence of our own design. It could be replaced later by paJDYF-85M-p2.
  - Country codes coming from `intl-tel-input`.
  - Use native `select` and `input` elements.
  - Selecting a country or clicking on the country code switch focus to the input.
  - Defaults to `wcpaySetting.connect.country` or `US`
  - Returns a phone number in E164 format.
- **GroupedSelectControl**
  - Group provided options by `option.group` which should match `group.key`.
  - Allow to toggle groups visibility, showing the first one by default.
  - Optionally searchable, filtering by option name, and also by the optional property `context`. Restoring visibility state after clearing search.
  - Allow selection by both mouse and keyboard.

Update `CustomSelectControl` to match final design and implement `useUniqueId` hook using `lodash` under the hood.

#### Testing instructions

They should match our design and behave according to our needs.

>**Note** Those are just the components' implementation without using them directly. To check their functionality we need to add somewhere a code like the example below.

<details>
<summary>Example code</summary>

```javascript
import LoadBar from 'components/load-bar';
import PhoneNumberControl from 'components/phone-number-control';
import GroupedSelectControl from 'components/grouped-select-control';
import CustomSelectControl from 'components/custom-select-control';

...

const [ option, setOption ] = React.useState< any >();
const [ phone, setPhone ] = React.useState( '' );

...

<LoadBar />
<PhoneNumberControl
	value={ phone }
	onChange={ setPhone }
	label="Phone Number Control"
/>
<GroupedSelectControl
	label="Grouped Select Control"
	options={ options }
	groups={ groups }
	value={ option }
	onChange={ setOption }
	searchable
	placeholder="Select an option"
/>

<CustomSelectControl
	placeholder="Select an option"
	label="Custom Select Control"
	options={ options }
/>
```
</details>

#### Screenshot and videos

<table><tr>
<td>custom-select-control</td><td>

https://user-images.githubusercontent.com/7670276/230898888-82866f5a-5ee2-4d5f-87a9-23ca96a7b56c.mov
</td><td>

https://user-images.githubusercontent.com/7670276/230898884-d620a982-5dd0-4d7b-b48d-6147815eaccb.mov
</td></tr><tr><td colspan=3>

https://user-images.githubusercontent.com/7670276/230898878-a5bf6d55-6d47-46e8-9cc2-cca353786aa5.mov
</td></tr></table>

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [x] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [x] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `5895` or branch name `add/4744-po-required-component` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=add/4744-po-required-component) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: dde9bd19623cd379a408e6ef1bf74f25d18ed2a0
- Build time: 2023-04-10 11:48:49 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by ismaeldcom** [comment]
cc @elizaan36 for a design review, especially for the those that doesn't have a design reference.

**Review by dmallory42 — APPROVED** [review]
LGTM, thanks for working on this! I tested locally and the components look and behave how I would expect them to. Nice job! 🚀 

The only suggestion I was going to make is that it would be nice to have country names rather than country codes for the telephone dialing code select, but it seems like [the work mentioned in this P2 post](paJDYF-85M-p2) would address that, so I think this would work well for now until we can move over to the new component.

Once we get a design approval I think this is good to 🚢 .

**Comment by elizaan36** [comment]
hey @ismaeldcom thanks for the ping. Curious why we wouldn't use the Gutenberg text field components for the phone and select field dropdowns unless I'm missing something. I believe there's also a loading component available.

**Comment by ismaeldcom** [comment]
Thanks for the quick review!

>The only suggestion I was going to make is that it would be nice to have country names rather than country codes for the telephone dialing code select

I just went with Stripe design here, as before, to make it similar because they merchant will be asked for a phone with a similar input on Stripe. But yeah, we can change to whatever suits our needs 🙂 Full country names might be too long to be shown on the select.

Hey @elizaan36!

>Curious why we wouldn't use the Gutenberg text field components for the phone and select field dropdowns unless I'm missing something.

It's a select and an input wrapped in WP `BaseControl` component. With the intention to have a single field for both, like any phone number input available out there. As a quick example, validation will be shown as a single filed instead of two. If you have a suggested design happy to implement it 🙂 In the current Figma it's just a text field.

>I believe there's also a loading component available.

I wasn't able to find a loading or progress component with that design on WP or WC components, do you have a reference of it at hand?

**Comment by elizaan36** [comment]
> It's a select and an input wrapped in WP BaseControl component. With the intention to have a single field for both, like any phone number input available out there. As a quick example, validation will be shown as a single filed instead of two. If you have a suggested design happy to implement it 🙂 In the current Figma it's just a text field.

Got it, thanks for this context. Yeah there isn't anything currently that I can point to. Your solution makes sense.

> I wasn't able to find a loading or progress component with that design on WP or WC components, do you have a reference of it at hand?

I checked with the Ghidorah team who are implementing the core profiler flow (which we're trying to stay aligned with). They've implemented this progress bar in NUX (WooCommerce.com) but it hasn't been introduced to core yet. It looks like you're on the right track so let's go ahead with the component you've proposed.

**Pull request merged**
