### PR TITLE
Use type wcpay_sepa for payment token to avoid conflicts with stripe plugin

### LINKED ISSUE #1605: WC_Payment_Token_SEPA class already exists if woocommerce-gateway-stripe is installed
### Summary
This is a follow-up from the [SEPA work we did](https://github.com/Automattic/woocommerce-payments/pull/1540#discussion_r612683436).

If both `woocommerce-gateway-stripe` and `woocommerce-payments` are installed, then there are 2 classes of the same name `WC_Payment_Token_SEPA`:
`woocommerce-gateway-stripe`: https://github.com/woocommerce/woocommerce-gateway-stripe/blob/trunk/includes/class-wc-stripe-sepa-payment-token.php
`woocommerce-payments`: https://github.com/Automattic/woocommerce-payments/blob/e8f603a1304cfc16ebf3ff69d6cbdcaa43d2e4a4/includes/class-wc-payment-token-sepa.php

Currently, the token's class name needs to be named `WC_Payment_Token_<payment_method_name>` due to [how core retrieve the token class name](https://github.com/woocommerce/woocommerce/blob/trunk/includes/class-wc-payment-tokens.php#L232). 

### What I tried
- I tried namespacing, ie `WCPay\WC_Payment_Token_SEPA`, but the core code won't find the class.
- I tried renaming it to match "WooCommerce Payments", ie. `WC_Payments_Token_SEPA`, but this doesn't work because of how core find the classname.

We will probably need to use the `woocommerce_payment_token_class` filter to map a custom name. Or to have `woocommerce_payment_token_class` from core to support namespaces.

### PR DESCRIPTION
**Pull request by superdav42**
closes #1605

#### Changes proposed in this Pull Request

Change the type name of the sepa payment token to `wcpay_sepa` this avoids the conflicts that can happen when the Stripe plugin is installed at the same time as WooCommerce Payments. The class name is also changed to match.

Only downside to doing this is existing sepa payment tokens will essentially stop working. Should not be a problem for anyone since it is hidden behind a feature flag. 

#### Testing instructions
* Checkout with SEPA. Check save payment method.
* Try again with saved method
* It should work

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

**Comment by harriswong** [comment]
👀

**Comment by harriswong** [comment]
Should we also rename the hook's prefix? https://github.com/Automattic/woocommerce-payments/blob/72459d244ae7989f917c9cf9ba491d9c4b1033b9/includes/class-wc-payment-token-sepa.php#L57

**Review by harriswong — CHANGES_REQUESTED** [review]
We will need to update `sepa` [here](https://github.com/Automattic/woocommerce-payments/blob/72459d244ae7989f917c9cf9ba491d9c4b1033b9/includes/class-wc-payments-token-service.php#L198) to `wcpay_sepa`. Otherwise, the my-account/payment-methods/ page breaks with this notice:
```
Notice: Undefined index: brand in /var/www/html/wp-content/plugins/woocommerce/templates/myaccount/payment-methods.php on line 51
```

**Comment by superdav42** [comment]
> Should we also rename the hook's prefix?
> 
> https://github.com/Automattic/woocommerce-payments/blob/72459d244ae7989f917c9cf9ba491d9c4b1033b9/includes/class-wc-payment-token-sepa.php#L57

Yes we should. In the rare case a third party wants to modify this token and not stripe plugin's.

**Comment by superdav42** [comment]
> We will need to update `sepa` [here](https://github.com/Automattic/woocommerce-payments/blob/72459d244ae7989f917c9cf9ba491d9c4b1033b9/includes/class-wc-payments-token-service.php#L198) to `wcpay_sepa`. Otherwise, the my-account/payment-methods/ page breaks with this notice:
> 
> ```
> Notice: Undefined index: brand in /var/www/html/wp-content/plugins/woocommerce/templates/myaccount/payment-methods.php on line 51
> ```

Good catch.

**Review by harriswong — APPROVED** [review]
LGTM 🚢 

- Tested checkout with new SEPA card
- Tested checkout with saved SEPA card
- Confirmed SEPA card is saved and show in my-account/payment-methods/
- Tested deleting card in my-account/payment-methods/
- Confirmed SEPA payment received on Stripe dashboard

**Pull request merged**
