### PR TITLE
Even if the site is already fully connected to Jetpack, go through the authorization flow

### LINKED ISSUE #752: Jetpack Connection: Even if the site is already fully connected to Jetpack, go through the authorization flow
See this comment for the updated design: paJDYF-Ei-p2#comment-2819

To make sure that the user is connecting to WCPay/Jetpack with the intended WP.com account, we'll show the Jetpack "Authorize" screen even if the site is already fully connected.

Note: We should check what happens if the user is currently logged-in with a different WP.com account, and/or with another Admin account in the local site.

https://github.com/Automattic/woocommerce-payments/pull/711 has been already opened to address this, but it's pending review and a new version of `jetpack-connection` to be released.

### PR DESCRIPTION
**Pull request by DanReyLop**
Fixes #752 

Parked until the next Jetpack Connection Package release. This PR depends on https://github.com/Automattic/jetpack/pull/16058

### CODE REVIEW

**Comment by DanReyLop** [comment]
@marcinbot Thanks for taking a look! However, I remember having many problems when I first implemented this. The Calypso flow isn't really prepared to "pretend to connect" a site if it's already connected.

I'll test this again soon and talk to David, maybe it makes more sense to build some UI in WP-Admin instead. There are a lot of scenarios and I'm not sure how the UI should work.

Supposing `admin` is the username of the Jetpack Master User in the local site, and the WP.com connected account is `adminuser@example.com`, these would be the use cases that need to work:
- Currently logged in as `admin` in the local site, logged in as `adminuser@example.com` in wp.com. Nothing should happen here, the "Authorize" button should just do a dummy redirect back to WP-Admin.
- Currently logged in as `admin` in the local site, logged in as `anotheruser@example.com` in wp.com. What should happen here? Should the `adminuser@example.com` user be disconnected from the site, and `anotheruser@example.com` become the Master User?
- Currently logged in as `admin` in the local site, logged out of wp.com. I have no idea what should happen here.
- Currently logged in as `shopManager` in the local site, logged in as `adminuser@example.com` in wp.com. 🤷 
- Currently logged in as `shopManager` in the local site, logged in as `anotheruser@example.com` in wp.com. Should this just connect a secondary user to the Jetpack site? Then we'd need to sign all WCPay requests with that secondary user's token, right?
- Currently logged in as `shopManager` in the local site, logged out of wp.com. 🤷

**Comment by DanReyLop** [comment]
> As for other points, I think parts of it might tie to #842. We might have to allow only connected users to manage wcpay, which would require a bunch of new problems to be solved, but could also potentially solve some of the ones here.

I think these are different problems. If the site is connected using the `adminuser@example.com` wp.com account, but I'm logged in with `anotheruser@example.com` when I onboard WCPay, I would expect the "identity" associated with the WCPay account to be `anotheruser@example.com`, and I'd expect all e-mail communication to go to the `anotheruser@example.com` inbox. All that regardless of what token (blog or user) is used to sign requests.

**Comment by vbelolapotkov** [comment]
Hey @DanReyLop , could you please put an estimate on this based on how much effort is left to get it merged?

**Comment by dechov** [comment]
@marcinbot @DanReyLop Does the https://github.com/Automattic/woocommerce-payments/issues/842 fix unblock this PR? Would y'all prefer to see it through, or be happy to have someone from Fractal take it on and try to resolve the remaining issues (it's on our list of issues to pick from this coming sprint)?

**Comment by DanReyLop** [comment]
What @marcinbot said was on point. This is a process that still needs to happen in a user-less world, because the `oauth_init` endpoint still requires a full Jetpack user connection.

The original errors that were blocking this PR have probably been long fixed, but there are a lot of unanswered questions in [this comment](https://github.com/Automattic/woocommerce-payments/pull/711#issuecomment-684768342) about how the Jetpack auth process should work on different cases.

**Comment by dwainm** [comment]
Closing this PR as stale.

**Pull request closed without merging**
