### PR TITLE
Add notice to next deposit card indicating capital loan funds

### LINKED ISSUE #5728: Simplify deposits UI - Add notice to next deposit card indicating capital loan funds
### Description

This issue is part of the larger Epic to add details about notices to the deposits card indicating status and caveats (https://github.com/Automattic/woocommerce-payments/issues/5726).

### Acceptance criteria 

* A notice added to the next deposit section when the next deposit includes a capital loan funds:
    - "This deposit will include funds from your WooCommerce Capital loan. Learn more"
    - 🔗 https://woocommerce.com/document/woocommerce-payments/stripe-capital/overview/

Screenshot 2023-03-10 at 6 12 20 pm

### Designs

P2: paJDYF-7fi-p2

### Additional context

Project: pdjTHR-2i5-p2
WCPay-server issue to add a property that indicates an estimated deposit includes loan disbursement transaction in the `deposits/overview-all` endpoint: 3182-gh-Automattic/woocommerce-payments-server.

### PR DESCRIPTION
**Pull request by Jinksi**
Fixes #5728 

#### Changes proposed in this Pull Request

This PR adds a new notice to the **Next Deposit** section of the overview screen that indicates when the next estimated deposit includes a loan disbursement transaction.

This notice will appear if the store:
* has an active Stripe Capital loan
* has a next estimated deposit that includes a `financing_payout` transaction

We're checking the next deposit for a `financing_payout` transaction by sending a request to `/wp-json/wc/v3/payments/transactions` with the deposit's `id`, which will return a single transaction of type `financing_payout` if it exists. This API request will only be fetched if the conditional requirements above are met.

This notice displays the following content:
- "This deposit will include funds from your WooCommerce Capital loan. Learn more"
- "Learn more" links to the following documentation URL: https://woocommerce.com/document/woocommerce-payments/stripe-capital/overview/

image

### Steps to reproduce

0. Enable the `_wcpay_feature_simplify_deposits_ui` feature flag: Run `update_option( '_wcpay_feature_simplify_deposits_ui', '1' );` in [WP Console](https://wordpress.org/plugins/wp-console/).

**Has loan in next deposit**
1. Onboard to WCPay with a new account US account (this will ensure that the next deposit includes a loan disbursement).
2. Set the account deposit schedule to weekly, daily or monthly.
   - Visit the Stripe dashboard (`https://dashboard.stripe.com/test/connect/accounts/acct_1234/settings`) and update the payout schedule under the Account Balances menu.   
      image
<details>
<summary>3. Create a Stripe Capital loan for the account.</summary>

---

* Visit the Stripe dashboard (`https://dashboard.stripe.com/test/connect/accounts/acct_1234/financing`) and create a financing offer with the status `delivered`.  

1capital-delivered

* Accept the offer via the email provided as the merchant.

2capital-email

* Finalise the financing offer as the merchant.    

3capital-offer-onboarding-1

3capital-offer-onboarding-2

3capital-offer-onboarding-3

3capital-offer-onboarding-4

* Approve the financing offer in the stripe dashboard   

4capital-approve

---

</details>

4. Open browser devtools network requests. We'll be watching for any requests to the `/wp-json/wc/v3/payments/transactions` endpoint.
5. View the Payments → Overview screen.
6. You should see the notice appear with the correct text detailed in the description above.
7. Click the link in the notice. It should take you to the correct URL detailed in the description above.
8. Ensure only a single request to `/wp-json/wc/v3/payments/transactions` occurred, and it responded with a single transaction object.

**Has next deposit without loan**
1. Onboard or use an existing WCPay account without a loan disbursement transaction expected in the next estimated deposit. (e.g. a store without a loan)
3. Open browser devtools network requests. We'll be watching for any requests to the `/wp-json/wc/v3/payments/transactions` endpoint.
5. View the Payments → Overview screen.
7. You should not see the notice appear.
8. Ensure no requests to `/wp-json/wc/v3/payments/transactions` occurred.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `5902` or branch name `add/5728-estimated-deposit-loan-notice` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=add/5728-estimated-deposit-loan-notice) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: eee89275f0c8cf8105ad53f95b448f4f17351b0d
- Build time: 2023-04-06 00:01:25 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by mattallan — APPROVED** [review]
While testing this PR I was running into issues where I could see the capital loan amount in my next deposit on the new overview component, and also on the **Payments > Deposits** table and in **Payments > Transactions** table with the type "Loan dispersement", but the banner wasn't showing up on the overview page.

Turned out the `wcpaySettings.accountLoans.has_active_loan` was still returning false which meant `useDepositIncludesLoan` was never querying the transactions.

I solved this by clearing my accounts cache in WCPay using dev tools but I'm wondering if live merchants will experience this. I don't necessarily have a workaround or solution but just wanted to raise this. I would consider this a very minor issue as well.


---

I didn't have any feedback for the code changes. Overall they look good and I liked the transaction query and `useDepositIncludesLoan` hook approach 🤌

**Comment by mattallan** [comment]
I did actually have a question about the Learn more link. Similar to the feedback on https://github.com/Automattic/woocommerce-payments/pull/5805, should it also have the "opens in new tab" icon at the end of it?

**Comment by Jinksi** [comment]
@mattallan as per https://github.com/Automattic/woocommerce-payments/pull/5861#issuecomment-1497602158, ~I'll remove the "ExternalLink" icons before merging~.

Ah, this PR didn't have the link. So I think we're good to merge, correct @mattallan?

**Comment by mattallan** [comment]
> Ah, this PR didn't have the link. So I think we're good to merge, correct @mattallan?

Correct @Jinksi! :shipit:

**Pull request merged**
