### PR TITLE
Adjust WooPay login modal viewport height unit

### PR DESCRIPTION
**Pull request by mdmoore**
Fixes 1689-gh-Automattic/woopay

#### Changes proposed in this Pull Request

Changes the viewport height unit for the WooPay login modal from `vh` to `dvh`.

#### Testing instructions

1. Check out this branch and 1966-gh-Automattic/woopay
2. On a mobile device, BrowserStack, or iOS Simulator, tap the Buy with WooPay button while the browser URL bar or toolbar is still on the screen. This is easiest from the checkout page where the WooPay button is at the top of the page.
3. Check that the Continue button is fixed to the bottom of the screen and is fully accessible with or without the browser URL or toolbar on screen and that no pinch/zooming is necessary

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6660` or branch name `fix/1689-login-modal-height` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=fix/1689-login-modal-height) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: cdf13584a43f8c21f66ea7badf5b7c7ff946b97d
- Build time: 2023-07-14 14:19:30 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by brettshumaker — APPROVED** [review]
Tests well for me in conjunction with the WooPay branch. 👍

**Comment by pierorocca** [comment]
@bummytime as mentioned can we get this single and very minor css change added to 6.2.1 rather than waiting for 6.3.0. @dpaun1985 I know you're working on the patch for the critical Split UPE issue. While not a functionally critical issue, this PR fixes having a scrollbar present in modals, a highly visible use case and awkward to see.

**Comment by frosso** [comment]
@pierorocca, it seems like the fix is already present in 6.2.0: https://github.com/Automattic/woocommerce-payments/compare/6.1.2...6.2.0

**Pull request merged**
