### PR TITLE
Remove WooCommerce Payments from taking over the WooCommerce Core Settings 

### LINKED ISSUE #4073: Remove WooCommerce Payments from taking over the Settings > Payments screen.
### Description
If I want to manage any payment methods settings, besides WooCommerce Payments, I always have to see the WooCommerce Payments settings needlessly before getting back to the main Payments screen to choose the correct payment method.

Why do we do this?

There is already a very quick way to get to the specific WooCommerce Payments settings from the main WordPress admin menu under Payments > Settings. I'd like us to leave the WooCommerce > Settings > Payments alone.

What would we do if any other developer made their payment method settings take over like WooCommerce Payments does? Would we allow it?

### PR DESCRIPTION
**Pull request by naman03malhotra**
Fixes #4073 

#### Changes proposed in this Pull Request
Remove WooCommerce Payments from taking over the WooCommerce Core Settings  Settings and updated tests. Now when you click `WooCommerce > Settings > Payments` you will goto default WC settings page instead of WC Payments setting page.

#### Testing instructions

- Checkout to this branch
- Goto `WooCommerce > Settings > Payments`
- The default should be WC Core payment settings page
- Goto `Payments > Settings`
- This should open the WC Payments setting tab as selected on WC core settings page

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [x] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [x] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6713` or branch name `4073/imp-woo-deafult-payment-settings` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=4073/imp-woo-deafult-payment-settings) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 37908e93458109c0aadf5b23aea76a22c7462a1e
- Build time: 2023-07-07 17:15:07 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by jessy-p — COMMENTED** [review]
Should we change the order here as well?
image

**Comment by jessy-p** [comment]
Given the limited code now in `WC_Payments_Admin_Sections_Overwrite`, should it just go in `WC_Payments_Admin_Settings` ?

**Comment by naman03malhotra** [comment]
>Should we change the order here as well?

I am not sure, but maybe if the design team thinks this would be good UX-wise, we can create a separate issue for this. cc @elizaan36

**Comment by naman03malhotra** [comment]
>Given the limited code now in WC_Payments_Admin_Sections_Overwrite, should it just go in WC_Payments_Admin_Settings ?

I prefer to keep it separate and modular since this class do override the default section. Also, there is a possibility that we may have to add some modifications in the future.

**Review by jessy-p — APPROVED** [review]

**Comment by naman03malhotra** [comment]
Confirming that it works in Atomic as suggested to test by Jordan p1688979062351459-slack-CGGCLBN58

**Comment by naman03malhotra** [comment]
Some analytics page related e2e tests are failing which doesn't seem to be caused by this PR
cc @deepakpathania

**Comment by naman03malhotra** [comment]
Discussion on slack: p1688979062351459-slack-CGGCLBN58

**Pull request merged**
