### PR TITLE
Set the parent path of the details pages.

### LINKED ISSUE #4312: [Deposits UI] When looking at `Deposit details`, `Payment details` pages the sidebar nav highlight is incorrect
### Describe the bug

Screen Shot 2022-06-02 at 3 25 28 PM

The **deposit**, **payment** (transaction) and **dispute** detail pages highlight `Dashboard > Payments` as the current menu item. This is misleading and confusing.

You can get to this page from a variety of places (e.g. overview or deposits list), and wasn't clear to me what I was looking at. 

I think it would be clearer to highlight `Dashboard > Payments > Deposits` since this is a child of the Deposits page. (and Transactions or [Disputes](https://github.com/Automattic/woocommerce-payments/issues/6394), respectively)

Maybe we also need something to make it clear that you're deeply nested, e.g. breadcrumbs in header.

Note: the page title has a nice clear hierarchy, but this is not always visible.

### To Reproduce
1. Setup & onboard WCPay and purchase some product so you have an estimated payout.
1. Click on `Payments`
2. Click on `1 deposit` under `Pending balance` or `Est [date]` under `Next deposit`.

Where am I?

### LINKED ISSUE #6394: `Payments > Disputes` should be highlighted when working with disputes
### Describe the bug
When a merchant is viewing a dispute detail, or in the process of challenging/accepting/responding, the sidebar nav is incorrect. It should show `Payments > Disputes` as highlighted.

Screenshot 2023-05-29 at 1 02 21 PM

(Spotted by @beaulebens  when reviewing WCPay UI)

### To Reproduce
Preconditions: 

- Store setup, payments onboarded, some active disputes. [See flows docs for details of how to simulate a dispute in test mode](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#add-order-notes-and-update-order-status-when-disputes-are-created-or-closed).

1. Go to `Payments > Disputes`. 
2. Click on `Needs response` or in a row to view dispute detail.
3. Notice nav highlighting is missing.

### Additional info
**Note**: in Phase 2 we'll be combining the **Transactions -> Details** and **Disputes → Details** screens, highlighting the **Transactions** nav menu item when viewing. I'll add this info to the issue. paJDYF-9oX-p2#comment-19421

### PR DESCRIPTION
**Pull request by shendy-a8c**
Fixes https://github.com/Automattic/woocommerce-payments/issues/6394.

#### Changes proposed in this Pull Request

This PR depends on https://github.com/woocommerce/woocommerce/pull/39116.

I found that menu item is highlighted when it has CSS class `current` and [wpNavMenuClassChange()](https://github.com/woocommerce/woocommerce/blob/714e50bf4c26156e487f48447a119df7d89a1ff8/plugins/woocommerce-admin/client/layout/controller.js#L465C8-L465C28) first [removes `current` CSS class from all the menu items](https://github.com/woocommerce/woocommerce/blob/714e50bf4c26156e487f48447a119df7d89a1ff8/plugins/woocommerce-admin/client/layout/controller.js#L467-L471). Then, [it looks for menu item with links that match with the current viewed page and adds `current` CSS class to the matching menu items](https://github.com/woocommerce/woocommerce/blob/714e50bf4c26156e487f48447a119df7d89a1ff8/plugins/woocommerce-admin/client/layout/controller.js#L484-L496).

Since there is no menu item with link that matches with the path of details pages, no menu item is highlighted. For example, dispute details page's path is `/payments/disputes/details` and Payments > Disputes menu item has path `/payments/disputes`.

This PR gives a way to specify the parent path of the details pages. https://github.com/woocommerce/woocommerce/pull/39116 will use this 'parent path' to highlight menu item that matches with the specified parent path.

The details pages covered in this PR:
- Transaction detail page.
- Deposit detail page.
- Dispute detail page.
- Dispute challenge page.

ps:
- I get the list of details pages by looking at `wc_admin_register_page()` in [includes/admin/class-wc-payments-admin.php](https://github.com/Automattic/woocommerce-payments/blob/7cd11f018b240fb80c642e15ff315bf4769167d8/includes/admin/class-wc-payments-admin.php) and `pages.push()` in [client/index.js](https://github.com/Automattic/woocommerce-payments/blob/7cd11f018b240fb80c642e15ff315bf4769167d8/client/index.js).
- I notice for deposit, the id is `wc-payments-deposit-details` ([ref](https://github.com/Automattic/woocommerce-payments/blob/7cd11f018b240fb80c642e15ff315bf4769167d8/includes/admin/class-wc-payments-admin.php#L427C19-L427C46)). I am tempted to change it to `wc-payments-deposits-details`. Should I?
- In this PR change, I pass `navArgs.id` for the affected pages. I don't know why without it the page can load just fine. Per the docs, it's important to have `navArgs.id` matching with the id defined in PHP via `wc_admin_register_page()` ([ref](https://developer.woocommerce.com/extension-developer-guide/working-with-woocommerce-admin-pages/#registering-a-react-powered-page:~:text=When%20supplying%20a%20component%20to%20the%20list%20of%20WooCommerce%20Admin%20Pages%2C%20it%E2%80%99s%20important%20to%20make%20sure%20that%20the%20value%20you%20specify%20for%20navArgs.id%20matches%20the%20id%20for%20the%20page%20you%20register%20with%20the%20Page%20Controller%20in%20your%20call%20to%20wc_admin_register_page())).
- In PHP, we already pass `parent`, for example [here](https://github.com/Automattic/woocommerce-payments/blob/7cd11f018b240fb80c642e15ff315bf4769167d8/includes/admin/class-wc-payments-admin.php#L445)'s for dispute details page, but somehow that is not enough.
- I attempted to solve this issue [another way](https://github.com/Automattic/woocommerce-payments/pull/6693) that does not involve changes in WC core but didn't work.

#### Testing instructions

* Checkout https://github.com/woocommerce/woocommerce/pull/39116 and build (follow the [readme](https://github.com/woocommerce/woocommerce#getting-started), basically `nvm use` then `pnpm install` then `pnpm run build`). Install to your store and activate `plugins/woocommerce`.
* Purchase a product with card `4000000000000259` that [will trigger a fraud dispute](https://stripe.com/docs/testing#disputes).

Test transaction detail page:
* Open Payments > Transactions > click on one of the row in the table.
* With [develop](https://github.com/Automattic/woocommerce-payments/tree/develop), Payments > Transactions will not be highlighted. With PR branch, it will be.

Test deposit detail page:
* Open Payments > Deposits > click on one of the row in the table.
* With [develop](https://github.com/Automattic/woocommerce-payments/tree/develop), Payments > Deposits will not be highlighted. With PR branch, it will be.

Test disputes detail page:
* Open Payments > Disputes > click on one of the row in the table.
* With [develop](https://github.com/Automattic/woocommerce-payments/tree/develop), Payments > Deposits will not be highlighted. With PR branch, it will be.
* Click the `Challenge dispute` button.
* With [develop](https://github.com/Automattic/woocommerce-payments/tree/develop), Payments > Deposits will not be highlighted. With PR branch, it will be.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6694` or branch name `fix/6394-highlight-menu-for-details-pages` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=fix/6394-highlight-menu-for-details-pages) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: b30ad4aeaf64b56f02c51c4dd999b96d64c5d390
- Build time: 2023-07-19 14:37:02 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by shendy-a8c** [comment]
The failing e2e tests are for `latest`, so maybe it's OK.

**Review by Jinksi — COMMENTED** [review]
Noting that I've tested this with https://github.com/woocommerce/woocommerce/pull/39116 and it is working well – great to see the correct nav menu items highlighted when viewing nested menu items in WCPay. Nice one!

The API naming may change in https://github.com/woocommerce/woocommerce/pull/39116 – once that has been confirmed and merged, we can approve this PR.

**Review by Jinksi — APPROVED** [review]
Approved – now that https://github.com/woocommerce/woocommerce/pull/39116 has been merged, this solved the issue and has no backwards compatibility issues.

Note this also solves #4312.

**Pull request merged**
