### PR TITLE
Update Qualitative Feedback note to have more efficient sql query

### LINKED ISSUE #3693: Qualitative feedback inbox note will not appear unless there are saved cards
The feedback inbox note (added in https://github.com/Automattic/woocommerce-payments/pull/1541) is intended to appear after there has been a WCPay transaction, but based on the condition querying the `wp_woocommerce_payment_tokens` table, it would appear if (and only if) there are any saved cards on the store (using any payment gateway).

Also, it would improve performance (especially on large stores) to avoid the DB query on every `admin_init` hook – this will be partially addressed in https://github.com/Automattic/woocommerce-payments/pull/3692.

An approach to checking for WCPay transactions (without a server request querying for transactions) might be to cache the state of there _having been a WCPay transaction_ in the DB (transient?), in `process_payment` perhaps.

### PR DESCRIPTION
**Pull request by jessepearson**
Fixes #3693 

#### Changes proposed in this Pull Request

Update the sql query to no longer use `count` to make it more efficient, and also make it work if there are any WooPayments related transactions, not just stored cards.

#### Testing instructions

* Navigate to _WCPay Dev_ tools.
* Use the _Delete all WCPay notes from WC inbox_ action on the right hand side of the page.
* Navigate to WooCommerce > Home.
* Confirm the note below appears with a low time, such as a few seconds or a minute, based on how long it's been since your last step.
  * Note, this does require at least one transaction in your store.

Screenshot 2023-12-04 at 11 02 45 AM

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7825` or branch name `fix/3693-qualitative-feedback-note` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/3693-qualitative-feedback-note) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: e479d47321df91c6d4d7c4e3f0e3bf520dbf7c55
- Build time: 2023-12-12 11:38:38 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by tpaksu — APPROVED** [review]
I couldn't get the real effect on my local with just 3 payment tokens, but I see it fits for the goal to see if there's a transaction. LGTM.

Before change: 
image

After change:
image

**Comment by tpaksu** [comment]
@jessepearson I just want to ask, what was the reason for switching tables used on this query? Because of the HPOS compatibility? Just asking for curiosity.

**Comment by jessepearson** [comment]
> @jessepearson I just want to ask, what was the reason for switching tables used on this query? Because of the HPOS compatibility? Just asking for curiosity.

Yes, if HPOS is being used, then the meta data is stored in another table, so the query has to look there instead. This is another PR where this has been done: https://github.com/Automattic/woocommerce-payments/pull/6829

**Review by eduardoumpierre — APPROVED** [review]
The changes look good and it worked as expected.

Using the same approach as @tpaksu, I added around 24k items to the `wp_woocommerce_payment_tokens` table and this is the query impact:
Screenshot 2023-12-11 at 11 05 49

This is the result from your branch:
Screenshot 2023-12-11 at 11 08 00

I wonder what would be the impact on big merchants. LGTM!

**Pull request merged**
