### PR TITLE
Remove Order Meta Helper tool toggle, and add url parameter to enable tool

### LINKED ISSUE #6919: Update the text in the Multi-Currency Analytics helper tool
### Description
Update the text in the Multi-Currency Analytics helper tool:
- From: "This tool's intended use is to add or update the Multi-Currency exchange rate for the order if it is missing."
- To: "If the exchange rate meta data is missing, update the order with the suggested exchange rate."

### Acceptance criteria

* The text is updated. 

### Additional context
paJDYF-9qe-p2#comment-19815

### LINKED ISSUE #6935: Move Multi-Currency Order Meta Helper to behind a url parameter
### Description
The Order Meta Helper was added with a button to toggle it under WooCommerce > Status > Tools, which has placed it as a user facing tool. As this tool is only meant to be used when there is an error outside of our control, the tool should be only available if absolutely needed.

### Acceptance criteria

* Remove the ability to toggle the tool on and off through the WooCommerce Tools area.
* Still allow merchants to access the tool, per order, by adding a specific url parameter to the order edit page.

### Additional context
Discussion: p1691149221930449-slack-C01B8KNUYSW

### PR DESCRIPTION
**Pull request by jessepearson**
Fixes #6935 #6919

#### Changes proposed in this Pull Request

* Remove the feature flag for the Order Meta Helper.
* Remove the functionality to add and use the button to toggle the helper on and off.
* Add `try/catch` for call to `get_intent()` to handle if the intent is invalid.
* Remove `$is_wcpay` variable/check since it's not needed anymore.
* Add functionality to enable the tool on a per-order basis via a url parameter: `&wcpay_mc_meta_helper=1`

Note that the `maybe_update_edit_post_link` method seems redundant that it checks to see if the feature is enabled in order to update the url/link. This is needed for when the form is submitted and the page is refreshed. The `$_REQUEST` variable is checked and the `hidden` input is used to make sure the url is updated so the form shows again.

#### Testing instructions

Setup:
* Go to WooCommerce > Settings > Multi-Currency and enable at least one other currency in your store.

Testing:
* Place an order for a product using the default store currency.
* View the order under WooCommerce > Orders in the admin.
* Confirm there is not a meta box named _Multi-Currency Meta Helper_ showing.
* Update the url in the address bar to have `&wcpay_mc_meta_helper=1` on the end and hit return/enter.
* The meta box should still not show.
* Purchase a product in another currency other than the default currency in your store.
* Go to the order under WooCommerce > Orders in the admin.
* Confirm there is not a meta box named _Multi-Currency Meta Helper_ showing.
* Update the url in the address bar to have `&wcpay_mc_meta_helper=1` on the end and hit return/enter.
* Confirm that the meta box named _Multi-Currency Meta Helper_ now shows.
* Copy and paste the suggested rate into the box and hit enter/return or click the _Update_ button for the order.
* A new note should show in the order notes under your user ID.
* The note should state the exchange rate was updated and include the from and to rates.
* The _Multi-Currency Exchange Rate_ value should now be populated in the meta box, the _Stripe Exchange Rate_ value will not be.
* Update the payment intent ID on the order to either remove or add a character on the end.
  * This can be done by adding this snippet somewhere, which enables viewing hidden meta data: `add_filter( 'is_protected_meta', '__return_false', 999 );`, or
  * This can be done in the `wp_postmeta` table by searching for your order number under `post_id`.
* Refresh the order.
* The meta box should now show:
  *  _Charge Exchange Rate_ is _Not found_.
  *  _Charge Currency_ is _Not found_. 
* Check the latest WCPay log either under WooCommerce > Status > Logs or /wp-content/uploads/wc-logs/ for a log that reads something like the below example.
* Go to Products in the left navigation bar, then into an existing product.
* Update the url in the address bar to have `&wcpay_mc_meta_helper=1` on the end and hit return/enter.
* Confirm there is not a meta box named _Multi-Currency Meta Helper_ showing.

Example log:
> 2023-08-04T15:24:42+00:00 ERROR Error when attempting to get intent (pi_3NayaBR8d1QhXXSD0Pwx3yHJ_):
Error: No such payment_intent: 'pi_3NayaBR8d1QhXXSD0Pwx3yHJ_'

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6936` or branch name `fix/6395-move-meta-helper-behind-url-param` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=fix/6395-move-meta-helper-behind-url-param) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 5b3fbdc6b933b0da69bdad9a7e9c9aa8513899f3
- Build time: 2023-08-10 11:35:42 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by allie500 — COMMENTED** [review]
Thanks for working on these updates to the tool. The code changes make sense. The tests passed for me but I did have two observations I wanted to share prior to approving.

> _Copy and paste the suggested rate into the box and hit enter/return or click the Update button for the order._

I didn't see a suggested rate label. I used the Stripe exchange rate in my test. Looking at the code, it looks like a suggested rate should be shown if the MC exchange rate is empty. In the test the MC exchange rate was not empty, it was set to 1. 

Screenshot on 2023-08-08 at 14_44_23

I checked the old testing instructions in #6582 and saw that I needed to delete the MC exchange rate for the order in `wp_postmeta`. After doing that with a follow up test, I got the suggested exchange rate.

Screenshot on 2023-08-08 at 15_08_09

> _The Multi-Currency Exchange Rate value should now be populated in the meta box, the Stripe Exchange Rate value will not be._

The Multi-Currency Exchange Rate was 1 before updating. After updating it was the rate which I set which is to be expected; however, the Stripe Exchange Rate value was the same and shown. 

Screenshot on 2023-08-08 at 14_54_03

In my follow up test where I deleted the MC exchange rate first, I used the suggested exchange rate and updated. Just like in the first test, the Stripe exchange rate remained.

Screenshot on 2023-08-08 at 15_11_07

Is this to be expected or should the Stripe Exchange Rate row be empty or hidden?

**Comment by jessepearson** [comment]
> I didn't see a suggested rate label. I used the Stripe exchange rate in my test. Looking at the code, it looks like a suggested rate should be shown if the MC exchange rate is empty. In the test the MC exchange rate was not empty, it was set to 1.

This is my error. I copied the testing instructions from the previous PR, then modified them to use here. I removed the step to delete the meta data so that the suggested rate would show up, but didn't modify the latter step. 

There were no changes to that code, the purpose of the test was to confirm that the MC exchange rate got updated when the form was submitted. This is due to the form changed how it works and it doesn't look for a database flag in order to process the form data, it looks for the `hidden` form field data passed in the `$_REQUEST`. 

>  the Stripe Exchange Rate value was the same and shown.

This is correct. In the instances where we've seen this issue, both meta fields are missing, so only one needs to be updated. I initially chose to only update the MC exchange rate since it could literally be anything based on the store settings. The Stripe exchange rate will not be added/populated if it is missing.

Something else to note here is that the analytics will use the Stripe exchange rate, and if it doesn't exist, then it will use the MC exchange rate. This means that if someone uses this to try to modify an order that doesn't need it, it will have no effect on the analytical data.

**Comment by jessepearson** [comment]
@allie500 (or other reviewer) I just pushed another change in https://github.com/Automattic/woocommerce-payments/pull/6936/commits/609d8b0e7a9bf0ed99be5ca0b9237b58bfc587a2 , but it was just a text change per the comment here: paJDYF-9qe-p2#comment-19969

The form text now reads: 

> If the exchange rate meta data is missing, update the order with the suggested exchange rate. Once the rate is updated, you can then use the Import historical data tool under Analytics > Settings to correct analytical data.

**Review by allie500 — APPROVED** [review]
Thanks for the additional information in your reply. All that makes sense to me. I also like the updated form description text. I've run back through the tests once more just to be sure everything works and it does. 

LGTM :shipit:

**Pull request merged**
