### PR TITLE
Add the default currency and exchange rate to new orders' meta 

### LINKED ISSUE #1777: Analytics: store the customer total and converted total amounts
As discussed in the design thread ( paJDYF-1l7-p2 ), it is important that we display analytics by default normalised to the stores default currency. In order to do this without having issues with price fluctuations due to exchange rates, it is important that we store the following information at the time of transaction for multi-shopper currency transactions (cases where a customer pays in a currency that is not the store's default currency):

- `customer_total` the amount the customer paid in the currency they paid in (note: would we also store the currency shortcode here, or have a separate field for it?)
- `converted-total` - the `customer-total`, converted to the store's default currency, using the exchange rate at the time of transaction.

As part of multi-currency, we'd need to pass the two sets of totals to WCAdmin, which would then be responsible for accomodating both sets of totals for multi-currency orders and providing a way to filter the data by currency. This would also allow extensibility to other multi-currency extensions as well.

### PR DESCRIPTION
**Pull request by luizreis**
Fixes #1777 

#### Changes proposed in this Pull Request

As part of the analytics effort, we'll have to display the order prices converted to the store's base currency in the reports. To do so, this PR introduces two meta fields to the order: `_wcpay_multi_currency_order_exchange_rate` and `_wcpay_multi_currency_order_default_currency`.

The customer total and currency do not have to be stored in the meta because WooCommerce saves them in the order data already. Are the two metas above enough for our use case or should we store something else?

#### Testing instructions

* Create an order using a currency that needs to be converted
* Check that the order's metadata for the `_wcpay_multi_currency_order_exchange_rate` and `_wcpay_multi_currency_order_default_currency` keys are correct
* Repeat the test using the checkout block

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

**Review by dmallory42 — APPROVED** [review]
LGTM and works well! :shipit: 

One thing I noticed but just wanted to check, when I create an order in the checkout block, the metadata gets created upon hitting the block checkout page (before actually checking out/purchasing the product). The order looks like it has a status of `checkout-draft` at this point.

I just wanted to make sure that this is expected behaviour?

**Comment by dmallory42** [comment]
> The customer total and currency do not have to be stored in the meta because WooCommerce saves them in the order data already. Are the two metas above enough for our use case or should we store something else?

As long as we have the exchange rate at time of purchase, total amount in store currency, amount in customer's currency and customer total, I think that's sufficient for analytics.

We have all of those because customer total and customer currency are stored in the order, and this PR adds the store currency and exchange rate. 🙂

**Comment by luizreis** [comment]
> One thing I noticed but just wanted to check, when I create an order in the checkout block, the order metadata gets created upon hitting the block checkout page (before actually checking out/purchasing the product). The order looks like it has a status of `checkout-draft` at this point.
> 
> I just wanted to make sure that this is expected behaviour?

Thanks for the review @dmallory42! I noticed that as well, and it's due to the way the blocks handle the order creation and checkout. Since the same order is used when checkout is clicked, we should have the data in place when it's completed. Do you think that this could be an issue?

**Comment by dmallory42** [comment]
> Do you think that this could be an issue?

Nope! I don't think it is an issue, it's just something I wasn't expecting, but since this seems to be just how the blocks checkout works, it should all be fine!

**Pull request merged**
