### PR TITLE
Show the correct number of days in the new account waiting period notices (Payments Overview and Settings)

### LINKED ISSUE #7970: New account waiting period says `business days` but the code uses calendar days – inconsistent
### Describe the bug

When a WooPayments merchant captures their first payment, they enter the new account waiting period. This period is seven calendar days per [this](https://github.com/Automattic/woocommerce-payments-server/blob/322e9826eca751bfb9b82a8b384a089c2aca35c6/server/wp-content/rest-api-plugins/endpoints/wcpay/stripe/class-stripe-account.php#L798).

However, we currently indicate in [a couple of places](https://github.com/search?q=repo:Automattic/woocommerce-payments+%22seven+business+days%22&type=code) that this is business days.

### To Reproduce

1. Trigger the new account waiting period.
2. Note that there is a notice on the **Payments > Overview** page that reads:

```
Your first deposit is held for seven business days.
```

### Actual behavior

The merchant is notified that the new account waiting period is seven business days — even though it's seven calendar days.

### Screenshots

seven business days

### Expected behavior

The new account waiting period includes weekends and holidays. Even though deposits will not be initiated on non-business days, for the sake of clarity and accuracy, we should specify that the new account waiting period is seven calendar days (or just seven days) instead of seven business days.

### Additional context

p1703938260739969/1703936807.503649-slack-C3NCP7ZJ6
p1704123858585669-slack-C02BW3Z8SHK
7514473-zen

### PR DESCRIPTION
**Pull request by Jinksi**
Fixes #7970

#### Changes proposed in this Pull Request

This PR changes the text in the new account deposit waiting period notice on **both** the Payments → Overview screen and the settings screen to show the correct number of days (7-14) instead of 7 business days.

Payments → Overview screen:
image

Settings screen:
image

TODO:

- [x] Update settings screen notice text to 7-14 days
- [x] Check for other instances of "seven business days" or similar
- [ ] ~~Update settings screen component~~ (will be handled in another PR since there are other deposit `Notice` components to update on the settings screen – see #6424)

#### Testing instructions

1. Trigger the new account waiting period.
2. Ensure that the notice on the **Payments > Overview** page reads:

```
Your first deposit is held for 7-14 days.
```

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests **Yes**
- [x] Tested on mobile **Yes**

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : **QA Testing Not Applicable**
- [x] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable. **N/A**
- [x] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable. **N/A – minor text change**

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8030` or branch name `fix/7970-clarify-calendar-days-waiting-period-notice` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/7970-clarify-calendar-days-waiting-period-notice) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 80cbd6455f45471f8e72d10f5e45f2704221d3e8
- Build time: 2024-01-18 23:13:35 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by Jinksi** [comment]
It seems that this notice will not render for new accounts who are within the waiting period and therefore have no deposits.

https://github.com/Automattic/woocommerce-payments/blob/81f4be369a8571fa708316dcccbb2290a4732f0e/client/components/deposits-overview/index.tsx#L91-L94

Need to confirm this and potentially open an issue if true.

**Comment by haszari** [comment]
Started trying to test this on a new store via Jurassic Ninja – i.e. a new freshly onboarded store is the scenario where this message should display.

I haven't seen the message in the UI so far. 

- After onboarding (0 all balances, no transactions)
- After completing a normal purchase ($something pending balance)
- After completing a purchase with card that skips pending balance ($something available balance)

Here's a screenshot of overview page:

Screenshot 2024-01-18 at 10 36 58 AM

> It seems that this notice will not render for new accounts who are within the waiting period and therefore have no deposits.

So it seems likely this bug is real, and this notice is not showing … for anyone? I'll open an issue, maybe we can get both fixes in WooPayments 7.1.

- #8040

**Review by haszari — COMMENTED** [review]
We [need to get this notice displaying consistently](https://github.com/Automattic/woocommerce-payments/issues/8040) as well – so this is an interim review in that sense :) 

The code changes look 👌🏻  and zero risk.

I found another notice we might need to update:

Screenshot 2024-01-18 at 10 45 07 AM

So it might be worth doing a more extensive search, alongside updating that notice too.

**Comment by Jinksi** [comment]
Related to #6424 as well, since the settings notice should use the "Inline notice" component.

**Comment by Jinksi** [comment]
> So it seems likely this bug is real, and this notice is not showing … for anyone? I'll open an issue, maybe we can get both fixes in WooPayments 7.1.

Confirmed that this now appears for new accounts that have at least one transaction, now that #8041 has merged.

image

**Review by haszari — APPROVED** [review]
Code still looks 👌🏻 

Tested on my same newish test store and saw both updated notices looking great:

Screenshot 2024-01-19 at 11 04 46 AM

Screenshot 2024-01-19 at 11 04 56 AM

**Comment by Jinksi** [comment]
~~Investigating~~ fixed failing JS linting / tests GH check. Merging shortly.

**Pull request merged**
