### PR TITLE
Use CardNotice component for authorization notification in transaction details page

### LINKED ISSUE #7748: [Authorizations] Capture notification styles are broken
### To Reproduce

1. As a merchant, go to Payments > Settings and enable` Issue an authorization on checkout, and capture later`
2. As a shopper, purchase an order. Take note of the order to use it in the next step.
3. As a merchant, navigate to Payments > Transactions > Uncaptured tab
4. Find the Authorization that matches your order and enter its details

### Actual behavior

The styles for the Capture notification are broken.
### Screenshots

Screenshot 2023-11-20 at 17 58 52

### Expected behavior

The Capture notification has the correct style.

### PR DESCRIPTION
**Pull request by mgascam**
Fixes #7748 

#### Changes proposed in this Pull Request

* Use recently added CardNotice component for authorization notification in transaction details page.

**Before**

284339226-b7c44c40-222c-46c9-a58d-c17d7873cbba

**After**

Screenshot 2023-12-12 at 19 05 43

#### Testing instructions

1. As a merchant, go to Payments > Settings and enable Issue an authorization on checkout, and capture later
2. As a shopper, purchase an order. Take note of the order to use it in the next step.
3. As a merchant, navigate to Payments > Transactions > Uncaptured tab
4. Find the Authorization that matches your order and enter its details

To test an authorization that is blocked by fraud rules you can force `isFraudOutcomeReview` flag. In `client/payment-details/summary/index.tsx`:

```javascript
const isFraudOutcomeReview = true;
``` 
5. Refresh the page.
6. The capture button should not be present and the UI should match the following screenshot:

_Authorization blocked by fraud rules_

Screenshot 2023-12-13 at 14 05 59

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7891` or branch name `fix/7748-capture-notification-styles-are-broken` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/7748-capture-notification-styles-are-broken) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: b381cb6b8aaed193d64263db190876b696441743
- Build time: 2023-12-14 16:15:41 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by kalessil — CHANGES_REQUESTED** [review]
I miss a few things in this PR:
- changelog
- testing instruction for fraud prevention case

**Comment by mgascam** [comment]
> I miss a few things in this PR:
> 
> * changelog
> * testing instruction for fraud prevention case

Thanks @kalessil. Changelog added. I also tried to add testing instructions for fraud prevention rules as explained in this PR https://github.com/Automattic/woocommerce-payments/pull/5888, but no luck. The thing is that the payment lands in the blocked state after I set up the fraud prevention rule. So I updated the testing instructions to explain how to force the flag that controls the fraud prevention case.

**Review by kalessil — APPROVED** [review]
LGTM and tests well.

**Pull request merged**
