### PR TITLE
Allow issue of zero amount refunds

### LINKED ISSUE #7984: Cannot restock items with a $0.00 refund
### Describe the bug
When trying to restock an item on an order which was refunded via the Transaction Page 'Refund in Full' option, I found I cannot perform a $0 refund on an order with WooPayments. In the case of a fully refunded order, a merchant has to fall back to manually editing the product's inventory.

This situation could be rare, but until #7969 is corrected it may come up.

### To Reproduce
1. Refund a linked order in full from the Transaction page.
2. Edit the order, increment the 'Quantity'. You must zero out the refund price and tax to get to $0 (since it is already refunded).
3. Make sure 'Restock refunded items' is checked!
4. Submit the $0 refund. See error.

### Actual behavior
The refund cannot be performed.

### Screenshots
image
image

### Expected behavior
The $0 refund should be performed, restocking the items.

### Desktop (please complete the following information):

* OS: MacOS
* Browser: Firefox: 
* Version: Latest

### PR DESCRIPTION
**Pull request by dmvrtx**
Fixes #7984

#### Changes proposed in this Pull Request

 - A special case for zero amount refunds with early exit.

Zero amount refunds can come handy in case merchant needs to re-stock items for an already refunded order.

#### Testing instructions

 - Create and complete payment for the order.
 - On the order page start a refund process:
   - Choose order items to be refunded and edit refunded amount and tax to be `0`
   - Select a "Re-stock refunded items" option.
 - Click on the "Refund $0.00 with WooPayments" button.
 - Process should complete without errors.
   - Re-stocked items should have a re-stock indicator.
   - There should be no note about $0.00 refund.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8013` or branch name `fix/7984-allow-zero-amount-refunds` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/7984-allow-zero-amount-refunds) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 9a196e50899a29854a455bd1b73da089798d7e93
- Build time: 2024-01-16 16:02:01 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by mgascam — COMMENTED** [review]
Code changes look good to me, I'll submit approval after manual tests

**Review by mgascam — APPROVED** [review]
LGTM! Followed test instructions and works as expected.

**Review by KarlisJ — APPROVED** [review]
Code changes looks good, tests well.

**Pull request merged**
