### PR TITLE
Affirm&Afterpay: flexible payment ranges (optional min/max).

### PR DESCRIPTION
**Pull request by kalessil**
Follow up on #6540 

#### Changes proposed in this Pull Request

- Allow null in min/max for defining ranges (future proof)

#### Testing instructions

* Testing Affirm/Afterpay with min/max ranges on checkout shall respect those ranges

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6545` or branch name `add/affirm-afterpay-ranges-flexible` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=add/affirm-afterpay-ranges-flexible) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 28b9f6e985e47cef8b3fc4a9097f5bbcdcc14cb0
- Build time: 2023-07-18 12:58:27 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by dmvrtx — COMMENTED** [review]
Code-wise looks good, but tests are missing. [Something like this](https://github.com/Automattic/woocommerce-payments/blob/a76784598058607bccae9093cbf51dbf2bda4c5a/tests/unit/payment-methods/test-class-upe-payment-gateway.php#L1561) would be a good addition.

**Comment by kalessil** [comment]
Thanks! Will add.

**Comment by kalessil** [comment]
As followup: created a new PR to add new test cases: https://github.com/Automattic/woocommerce-payments/pull/6585

**Review by dmvrtx — APPROVED** [review]
Looks good to me. It'd be nice to have tests, though.

**Comment by kalessil** [comment]
Thanks, @dmvrtx! I was considering adding some, but the way we do test this functionality is by relying on existing PMs and those are not yet taking advantage of this feature.

**Pull request merged**
