### PR TITLE
Reorganise payments overview currency switcher, welcome message and balances card

### LINKED ISSUE #8790: Reorganise payments overview currency switcher, welcome message and balances card
Part of #8765 

As part of the Payment Activity Card project, we are adding a new currency selector dropdown to the Payment Overview screen. This replaced the existing Balances currency selector.

This currency selector will be a page setting, at top of page and in a sticky header on scroll. It will only be available for merchants with multiple deposit currencies.

This will affect all relevant cards (e.g. Balances, Deposits, Payment activity). Note also the WooPayments logo is removed in the design, and this epic includes that work (removing the logo).

Changes to occur:
- Welcome message now appears outside the Card
- Remove the WooPayments logo on top of the page
- Replace with the Currency switcher dropdown (appears only for merchants with multi-currency setup)
  - The sticky currency switcher on scroll will be handled in #8913
- Remove the currency-switcher tabs from the Balance card
- Ensure that all cards **except Payments Activity Card** on the Payments Overview page reflect the currency switcher dropdown changes
	- A subsequent issue #8490 will handle the Payments Activity Card currency-switching

> [!IMPORTANT]  
> This change is not behind the Payment Activity Widget feature flag and will be launched directly.

> [!NOTE]  
> A subsequent issue #8490 will handle the Payments Activity Card currency-switching, which is not part of this issue

Image

### PR DESCRIPTION
**Pull request by Jinksi**
Fixes #8790

> [!IMPORTANT]  
> This pull request is based on PR #8896 to use the new select component introduced in that PR. Please merge it to `develop` before merging this PR.

> [!CAUTION]  
> These changes are not behind a feature flag. 

### Changes proposed in this Pull Request

This PR replaces the Payments Overview currency-switching tabs with a new currency selector dropdown.

[View design](https://www.figma.com/design/bIfbBgyBPRzvXEl7dEg3cv/Payment-Widget?node-id=2286-68682&t=Nw5bbBNbizhzqQhO-4).

* It is only visible for merchants with multiple deposit currencies.
* This selected currency will affect all relevant cards (e.g. Balances, Deposits, Payment activity).
* The WooPayments logo is removed, as per the [design](https://www.figma.com/design/bIfbBgyBPRzvXEl7dEg3cv/Payment-Widget?node-id=2286-68682&t=Nw5bbBNbizhzqQhO-4).
	* The sticky currency switcher on scroll will be handled in #8913

> [!NOTE]  
> A subsequent issue #8490 will handle the Payments Activity Card currency-switching, which is not part of this PR

https://github.com/Automattic/woocommerce-payments/assets/3147296/25b13867-847c-4925-ba58-9eea6a36bff9

### Before/After

**Before**
image

**After**
image

**After – stores with a single deposit currency**

image

#### TODO

- [x] Add integration tests for currency selection
- [x] Sticky scroll header 
	- The sticky currency switcher on scroll will be handled in #8913
- [x] Add tracks event on currency select, to replace currency tab select event
- [x] Add tracks event suffix `_change` to clarify merchant intent

### Testing instructions

> [!TIP]
> This PR is currently available to test on the [Helix WooExpress demo site](https://woo-delectably-sparkly-ninja.wpcomstaging.com/wp-admin/admin.php?page=wc-admin&path=/payments/overview&selected_currency=chf). Ask a team Helix member for access.

* Open Payments → Overview
* Single deposit currency stores should show the Welcome message without a currency select
* Multi deposit currency stores should show the Welcome message with a currency select
	* You can get a multi-deposit currency store by [onboarding with a country that supports multiple deposit currencies](https://woocommerce.com/document/woopayments/deposits/deposit-currencies/) and adding bank accounts during Stripe KYC
	* Selecting a currency will update the currency shown on the Payments Overview page
		* Check all balances and cards reflect the change of currency (except Payment Activity Card)
		* Ensure the tracks event `wcpay_overview_currency_select_change` is recorded
		* Ensure the `selected_currency` query param reflects the currently selected currency
	* Remove the `selected_currency` query param from the URL and navigate to it. Ensure the default deposit currency is then selected.
	* Add an invalid `selected_currency` query param to the URL (e.g. `selected_currency=123`) and navigate to it. Ensure the default deposit currency is then selected.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Register new tracks event `wcpay_overview_currency_select_change` https://github.com/Automattic/tracks-events-registration/pull/2467
- [x] Link to above from removed tracks event `wcpay_overview_balances_currency_tab_click` https://github.com/Automattic/tracks-events-registration/pull/2467
- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [x] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [x] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.
- [ ]

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8791` or branch name `update/8765-payments-overview-currency-select` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=update/8765-payments-overview-currency-select) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 3cfe03732b559a4429e530e61b734f1f010408ad
- Build time: 2024-06-07 05:11:11 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by Jinksi** [comment]
Marking as `Ready for review` to allow the preparation of a Jetpack beta-tester build. This PR is still a WIP.

**Review by haszari — COMMENTED** [review]
Did a quick test. Looking great and working well 👌



A couple of comments:

- The "sticky" behaviour is not implemented yet. Suggest adding a todo to the PR description so it's clear that's coming (is mentioned in issue, assuming in scope). Could be a separate PR, especially if we want more parallel effort 🚀 
- The update when switching currency is instantaneous. That works, and it's super fast/snappy 🎸 . We might want to look at an animation or transition to make it obvious what's happening – that's a design consideration, and we could definitely postpone that (out of project scope) but important to think about how we make it clear when the data in the UI changes.


Also musing … maybe we want a flag image/emoji in the component as a visual hint?

**Review by jessy-p — COMMENTED** [review]
Tested and working as expected.

Updated to latest develop to continue with #8490

**Comment by Jinksi** [comment]
> The "sticky" behaviour is not implemented yet. Suggest adding a todo to the PR description so it's clear that's coming (is mentioned in issue, assuming in scope). Could be a separate PR, especially if we want more parallel effort 🚀

@haszari I've moved the sticky behaviour to a new issue so we can work in parallel (it may be tricky!) – #8913

**Review by jessy-p — APPROVED** [review]
I have tested these changes as well as implemented & tested #8915 on this branch, its working seamlessly.

**Comment by Jinksi** [comment]
I'll fix a PW e2e test had I've inadvertently broken with these changes

```
1) [basic] › basic.spec.ts:20:8 › A basic set of tests to ensure WP, wp-admin and my-account load › Sign in as admin › Load Payments Overview 
    Error: Timed out 10000ms waiting for expect(locator).toBeVisible()

    Locator: getByAltText('WooPayments logo')
    Expected: visible
    Received: hidden
    Call log:
      - expect.toBeVisible with timeout 10000ms
      - waiting for getByAltText('WooPayments logo')


      24 | 				await page.waitForLoadState( 'domcontentloaded' );
      25 | 				const logo = page.getByAltText( 'WooPayments logo' );
    > 26 | 				await expect( logo ).toBeVisible();
         | 				                     ^
      27 | 			} );
      28 | 		} );
      29 |
```

**✅ Fixed in c6da1bf**

**Comment by nagpai** [comment]
Minor - On the mobile view, the currency switcher appears on top of the greeting and the spacing seems a bit non uniform / awkward. It may need some design input . The center alignment seems off a bit too.

<a href="https://github.com/Automattic/woocommerce-payments/assets/4162931/d374118a-2609-4646-8200-4b87166327d0"></a>

**Comment by Jinksi** [comment]
> On the mobile view, the currency switcher appears on top of the greeting and the spacing seems a bit non uniform / awkward. It may need some design input .

Thanks @nagpai! I noticed this as well and pushed commit be6e613 moments before your comment 😅

image

**Comment by Jinksi** [comment]
> The update when switching currency is instantaneous. That works, and it's super fast/snappy 🎸 . We might want to look at an animation or transition to make it obvious what's happening

@haszari I've opened #8963 for us to improve this

**Review by dalakatt — APPROVED** [review]

**Pull request merged**
