### PR TITLE
Fix date type in create payment intent response schema

### PR DESCRIPTION
**Pull request by dpaun1985**
Fixes 286-gh-Automattic/woocommerce-payments-meta 

#### Changes proposed in this Pull Request

Display formatted created date for payment intent endpoint.

#### Testing instructions

* set the capture later option for the store
* create an order
* using get order API, get the order details ( GET  <URL>/wp-json/wc/v3/orders/<order_id>)
* using the create payment intent API, create a new payment intent for the order 
* URL: POST <URL>/wp-json/wc/v3/payments/payment_intents
* Body: 
 ```
{
	"payment_method":"pm_....",
	"customer":"cus_....",
	"order_id":"xxxxx"
}
 ```
* check the response. `created` should be formatted instead of timestamp
-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**
 

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7534` or branch name `fix/date-type` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/date-type) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: d20839a3d1cc352d534239201fbe3c02b5d93324
- Build time: 2023-10-26 11:32:49 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by elazzabi — APPROVED** [review]
Looks good, thank you for fixing!

**Review by mordeth — APPROVED** [review]
✅ LGTM! 
❌ Changelog is missing!

**Review by jessy-p — COMMENTED** [review]
Would it be better to have a formatted string that makes sense to the merchant or user?
One example of a similar situation I could think of is https://github.com/Automattic/woocommerce-payments/blob/dec54775aa8a344e11ea0255670a8711de148899/includes/admin/class-wc-rest-payments-transactions-controller.php#L260

**Comment by dpaun1985** [comment]
> Would it be better to have a formatted string that makes sense to the merchant or user? One example of a similar situation I could think of is
> 
> https://github.com/Automattic/woocommerce-payments/blob/dec54775aa8a344e11ea0255670a8711de148899/includes/admin/class-wc-rest-payments-transactions-controller.php#L260

I made the changes. could you please re-check the changes. Thank you .

**Review by jessy-p — APPROVED** [review]

**Pull request merged**
