### PR TITLE
Fix WooPay button location Tracks

### PR DESCRIPTION
**Pull request by malithsen**
When a WCPay site is onboarded, on the latest version of WCPay, we enable the WooPay express button by default on all available pages. This is tracked by calling the `woopay_locations_updated` function, which expects a second parameter containing an array of enabled pages. However, we currently pass an associative array, which makes `woopay_locations_updated` not record the enabled pages as expected. This PR fixes it.

#### Changes proposed in this Pull Request
Pass the correct parameters when recording WooPay button updates on new merchants.

#### Testing instructions

* To simulate a new merchant site and access [this branch](https://github.com/Automattic/woocommerce-payments/blob/cce35cc1add4547ee28d96c922db64754987546a/includes/class-wc-payments-woopay-button-handler.php#L115), remove the `platform_checkout_button_locations` key from `woocommerce_woocommerce_payments_settings` option in your `wp_options` table.
* In your admin area, go to Payments -> Settings
* Click 'Customize' button in WooPay
* This should repopulate the `platform_checkout_button_locations` key with default options and record a new Tracks entry.
* In ~5 minutes, go to Tracks Live view in MC and search for `wcadmin_woopay_express_button_locations_updated` event
* Find the event from your local environment and make sure it has the `cart_enabled`, `checkout_enabled` and `product_enabled` props set to 1

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7765` or branch name `fix/woopay-btn-location-updates` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/woopay-btn-location-updates) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 6d3bddf8ec93c47e022930f3bb5846d3c5a5ac89
- Build time: 2023-11-22 17:13:56 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by hsingyuc — COMMENTED** [review]
@malithsen Thank you for working on this!  I've tried both Tracks and Superset.  On Superset, I used my merchant's blog id and I don't see the event `wcadmin_woopay_express_button_locations_updated`.  Any ideas?  Thank you!

**Review by hsingyuc — COMMENTED** [review]
After removing the `platform_checkout_button_locations` key from `woocommerce_woocommerce_payments_settings` option in my `wp_options` table, we disable WooPayments so [we won't be able to reach the update Tracks.](https://github.com/Automattic/woocommerce-payments/blob/6d3bddf8ec93c47e022930f3bb5846d3c5a5ac89/includes/class-wc-payments-woopay-button-handler.php#L96)

**Comment by malithsen** [comment]
> After removing the platform_checkout_button_locations key from woocommerce_woocommerce_payments_settings option in my wp_options table, we disable WooPayments 

@hsingyuc Not sure I understand. Removing the key should not disable WooPayments. Could you point out to the code where we disable WooPayments?

In any case, if removing the key is causing trouble, set up a new merchant site, onboard to WCPay and then continue from the 2nd step of test instructions. We are removing the key to simulate the behavior of a new merchant.

**Comment by hsingyuc** [comment]
Just to make sure I follow the instructions correctly.



https://github.com/Automattic/woocommerce-payments/assets/56378160/3e547c73-3d2b-40c1-b0fd-46503b516f4e

**Comment by malithsen** [comment]
@hsingyuc ah apologies my instructions weren't clear. You should remove both the `platform_checkout_button_locations` and its values. Because you only removed the key, it corrupted the options record, which likely made it think WooPayments is not enabled. In any case, reenabling WooPayments now will also make it repopulate the new key and create the Tracks event.

I see on Superset that your site has emitted the `wcadmin_woopay_express_button_locations_updated` event with the correct props :) 

Just for the sake of completion, exact steps I followed to remove the key was:
1. Copy the entire value of the `woocommerce_woocommerce_payments_settings`
2. Open PHP interpreter `php -a`
3. Unserialize the value `$deserialized_data = unserialize(VALUE)`
4. Remove the key-value pair,   `unset($deserialized_data["platform_checkout_button_locations"]);`
5. `serialize(UPDATED_VALUE)`

**Review by hsingyuc — APPROVED** [review]
@malithsen Thank you for the instructions, and my bad, I'm not sure what I was thinking. 😅 

Tests are as expected and LGTM 👍

**Comment by pierorocca** [comment]
@malithsen does this happen to retroactively enable the button on sites that had the pages pre-checked?

**Comment by malithsen** [comment]
@pierorocca No. This does not affect the actual enablement of buttons, it just fixes a Tracks issue where previously we were not recording the initial button location state (When a merchant onboards with WooPayments)

**Comment by pierorocca** [comment]
Right thanks, hence the source urls that were all defaulting to pay.woo.com. Thanks!

**Pull request merged**
