### PR TITLE
Disable unavailable payment methods due to country restrictions

### LINKED ISSUE #3638: Disable unavailable payment methods
With the inclusion of new payment methods like ACH or BECS that are only available to Stripe accounts in a specific country, we should prevent those payment methods to be enabled through WCPay settings. Otherwise, the customer will see an error while trying to activate them.

### PR DESCRIPTION
**Pull request by ismaeldcom**
Fixes #3638

#### Changes proposed in this Pull Request
Hide payment methods that are not available due to Stripe country restrictions. Like ACH that's only available on US or BECS on AU.

h/t @tpaksu for the suggestion of using payment method fees to check if it's available. I thought of adding the countries list on the client, but doesn't make sense to duplicate it, if we can do the same with the fees that already check the country on the server.

I opted to directly hide the payment method from the list. But we could also disable it and show a pill informing the customer that it isn't available in their country. Something like:
Screenshot 2022-01-14 at 12 14 07

#### Testing instructions
- You need to disable additional payments on the server in order to test it while there are no single country payment methods. Comment your Stripe account country on the countries constant in `Fee Service`
- Go to **Payments > Settings > Payment methods**
- Unavailable payment methods should be hidden now.

-------------------

- [x] Added changelog entries to both `readme.txt` and `changelog.txt` (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

**Comment by jarekmorawski** [comment]
@ismaeldcom Thanks for putting this together! Just to be clear, do you see any technical advantage of showing a pill instead of hiding the unavailable method? I'm wondering if we could somehow communicate that to merchants.

@rogermattic Can you take a look, please? To give you some context, some payment methods may not be available in your country. In ideal scenario, people wouldn't even see them in the list, but in some cases they may.

**Comment by ismaeldcom** [comment]
>do you see any technical advantage of showing a pill instead of hiding the unavailable method?

The only I thought that could be useful to keep visible but disabled (with a pill or any kind of message) is for the uncommon situation of a store that switches to a different Stripe account country.

If we ignore that case, hiding it could be better to avoid showing a few unavailable payment methods.

Anyway, I think is just a user experience decision 🙂

**Comment by rogermattic** [comment]
@ismaeldcom and @jarekmorawski  thanks for adding me to this thread :) 

> If we ignore that case, hiding it could be better to avoid showing a few unavailable payment methods.
I'd opt for hiding the unavailable payment methods to avoid confusion. 

btw...
> I thought that could be useful to keep visible but disabled (with a pill or any kind of message) is for the uncommon situation of a store that switches to a different Stripe account country.
It may be a silly question but is that even possible to switch to a different account country?

**Comment by ismaeldcom** [comment]
> I'd opt for hiding the unavailable payment methods to avoid confusion.

Thanks @rogermattic! We can continue with the implemented solution then 😄 

>It may be a silly question but is that even possible to switch to a different account country?

Not directly, the customer will need to ask for the connected account to be removed and onboard again. That's why I mentioned it's a uncommon situation 🙂

**Review by jarekmorawski — APPROVED** [review]

**Comment by ismaeldcom** [comment]
After thinking about the current implementation, I decided that would be better to filter the available payment methods earlier. So, I ended adding it on `get_upe_available_payment_methods`. This way the JS side will receive only the available/supported ones.

**Comment by tpaksu** [comment]
1. Disabled iDeal and giropay by commenting this code out: 

```php
		if ( in_array( $account->country, self::COUNTRIES_WITH_IDEAL, true ) ) {
			$payment_methods[] = Payment_Method::IDEAL;
		}

		if ( in_array( $account->country, self::COUNTRIES_WITH_GIROPAY, true ) ) {
			$payment_methods[] = Payment_Method::GIROPAY;
		}
```

2. Cleared the account cache on WCPay Dev Tools
3. Navigated to the Payments > Settings page

iDEAL was gone, but giropay was still there, without a fee pill.

image

**Comment by tpaksu** [comment]
Ok, found it. The filter on the last line of the function adds giropay, sofort and sepa_debit back if you have WCPay Dev Tools installed :) Maybe it'll be good to remove the feeless methods after the filters are applied, what do you think?

The code on the devtools: https://github.com/Automattic/woocommerce-payments-dev-tools/blob/753540e3fd4e9e24d7bbd90707e5050210ae4f86/woocommerce-payments-dev-tools.php#L118-L131

**Comment by ismaeldcom** [comment]
>Maybe it'll be good to remove the feeless methods after the filters are applied, what do you think?

Oh! I didn't notice it, because I was using P24 for testing 🙂 I thought of doing the intersect after the filter, but it could interfere if someone wants to add a custom payment method without fees. But thinking on it again, doesn't look like something useful at all, as they need to be added on the server too.

*Addressed in eebbcd3*

**Review by oaratovskyi — COMMENTED** [review]
Looks good! 
I've checked the BECS case by adding `$methods[] = 'au_becs_debit';` to the `get_upe_available_payment_methods()`.
It disappeared :)
So when you merge BECS, it will disappear for non-AU countries.

**Comment by tpaksu** [comment]
> I thought of doing the intersect after the filter, but it could interfere if someone wants to add a custom payment method without fees.

You can split the filter into two, one before the fees check, one after the fees check, so if anyone wants to add a PM without fees, would use the second filter :D So we can understand that this is something intended. Of course, this is something optional, just thinking out loud.

**Review by tpaksu — APPROVED** [review]
LGTM, the code is clean, the approach is perfect, so :shipit:

**Comment by htdat** [comment]
FYI. This PR has been available in WCPay 3.6.0 without going through manual tests done by GlobalStep this week (Jan 18).
p1642611618163400-slack-C01BPL3ALGP

**Comment by ismaeldcom** [comment]
Thanks for pointing it out @htdat. We already discussed that this is something that can't be tested by GlobalStep for now, because all of the single country payment methods are not merged yet.

**Pull request merged**
