### PR TITLE
HPOS: Fix subscriptions remaining on-hold after WCPay Subscription renewal

### LINKED ISSUE #5264: [HPOS] Subscription status remains `on-hold` after successful Stripe Billing renewal order payment.
### Describe the bug

With WC HPOS enabled, a subscription's status remains `on-hold` rather than being updated to `active` after a successful Stripe Billing renewal order payment.

This occurs with either HPOS order syncing enabled or disabled.

> **Note**
> This issue occurs using the WCPay `develop` branch (`5.2.0`) and subscriptions-core `trunk` branch (`5.2.0`).

### To Reproduce

0. Ensure you are using the current WCPay `develop` branch and current subscriptions-core `trunk` branch. I use a pre-release build rather than the subscriptions-core plugin ([instructions](https://github.com/Automattic/woocommerce-subscriptions-core/wiki/Building-a-release-version-of-WCPay-or-WCS-with-a-pre-release-subs-core-version)) uploaded to a non-local site.
1. Ensure you do not have the WooCommerce Subscriptions plugin activated.
2. [Enable HPOS](https://github.com/woocommerce/woocommerce/wiki/High-Performance-Order-Storage-Upgrade-Recipe-Book#how-to-enable-hpos).
3. Create a daily subscription product.
4. Purchase this subscription product.
5. Wait 24h for the Stripe Billing renewal to occur. You can verify the subscription status by visiting `https://dashboard.stripe.com/test/connect/accounts/acct_{your_stripe_account}/subscriptions`.
6. Once the Stripe Billing renewal invoice is created and paid successfully, verify that the renewal order has been created and is marked as `Processing`.
7. View the subscription status in the related orders metabox. This should be `Active` but remains `On hold`.
   image
9. Click the subscription ID in the related orders metabox to view the subscription. Note that subscription order notes indicate that the status was updated to `active`. However, this is not reflected in the subscription status.
   Screenshot 2022-12-09 at 11 08 01

> **Note**
> This may be quicker to replicate with [WCPay-dev-tools and Stripe Billing test clocks](https://github.com/Automattic/woocommerce-payments-dev-tools), which may or may not work as expected with HPOS syncing enabled.

### Actual behavior

The subscription status remains `on-hold` when a renewal order payment is processed successfully. The subscription order notes indicate that the status was updated to `active`. However, this is not reflected in the subscription status.

### Expected behavior

The subscription status should be updated to `active` when a renewal order payment is processed successfully.

### Additional context

Slack discussion: p1670826353622469-slack-C9QDV4TL4

<details>
<summary>HPOS + syncing site status report</summary>

```
### WordPress Environment ###

WordPress address (URL): https://subs-hpos-sync.mystagingwebsite.com
Site address (URL): https://subs-hpos-sync.mystagingwebsite.com
WC Version: 7.1.1
REST API Version: ✔ 7.1.1
WC Blocks Version: ✔ 8.7.6
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.0.26
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.86.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.4.26-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.1.1
WC Database Prefix: wp_
Total Database Size: 3.20MB
Database Data Size: 1.47MB
Database Index Size: 1.73MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.19MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 2
page: 7
post: 1
product: 1
revision: 1
shop_order: 8
shop_subscription: 4
wp_global_styles: 1
wp_template_part: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Query Monitor: by John Blackbourn – 3.10.1
Akismet Anti-Spam: by Automattic – 5.0.2
Jetpack: by Automattic – 11.7-a.1
WooCommerce Payments Dev Tools: by Automattic –
WooCommerce Payments: by Automattic – 5.1.2
WooCommerce: by Automattic – 7.1.1

### Inactive Plugins (0) ###


### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class (Drop-in)
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #5 - /
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Three
Version: 1.0
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://subs-hpos-sync.mystagingwebsite.com
Subscriptions-core Library Version: 5.1.0
Subscription Statuses: wc-on-hold: 3
wc-cancelled: 1

WooCommerce Account Connected: ❌ No

### Store Setup ###

Country / State: United States (US) — California

### Subscriptions by Payment Gateway ###

WooCommerce Payments: wc-cancelled: 1
wc-on-hold: 3


### Payment Gateway Support ###

WooCommerce Payments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
gateway_scheduled_payments
tokenization
add_payment_method


### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-12-10 00:54:59 +00:00
Options: ✔
Notes: 51
Onboarding: skipped

### WooCommerce Payments ###

Version: 5.1.2
Connected to WPCOM: Yes
Blog ID: 212996699
Account ID: acct_1MANhBCBkSjY3M63

### Action Scheduler ###

Canceled: 6
Oldest: 2022-12-02 01:14:51 +0000
Newest: 2022-12-07 04:23:52 +0000

Complete: 210
Oldest: 2022-12-02 01:09:52 +0000
Newest: 2022-12-09 01:27:38 +0000

Pending: 4
Oldest: 2022-12-09 02:16:55 +0000
Newest: 2022-12-10 00:12:15 +0000


### Status report information ###

Generated at: 2022-12-09 01:30:45 +00:00
```

</details>

<details>

<summary>HPOS + no-syncing site status report</summary>

```
### WordPress Environment ###

WordPress address (URL): https://subs-hpos-nosync.mystagingwebsite.com
Site address (URL): https://subs-hpos-nosync.mystagingwebsite.com
WC Version: 7.1.1
REST API Version: ✔ 7.1.1
WC Blocks Version: ✔ 8.7.6
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.0.26
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.86.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.4.26-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.1.1
WC Database Prefix: wp_
Total Database Size: 2.96MB
Database Data Size: 1.26MB
Database Index Size: 1.70MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.19MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 2
page: 7
post: 1
product: 1
revision: 1
shop_order_placehold: 9
wp_global_styles: 2
wp_template_part: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Query Monitor: by John Blackbourn – 3.10.1
Akismet Anti-Spam: by Automattic – 5.0.2
Jetpack: by Automattic – 11.7-a.1
WooCommerce Payments Dev Tools: by Automattic –
WooCommerce Payments: by Automattic – 5.1.2
WooCommerce: by Automattic – 7.1.1

### Inactive Plugins (0) ###


### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class (Drop-in)
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #5 - /
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Three
Version: 1.0
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://subs-hpos-nosync.mystagingwebsite.com
Subscriptions-core Library Version: 5.1.0
Subscription Statuses: –
WooCommerce Account Connected: ❌ No

### Store Setup ###

Country / State: United States (US) — California

### Payment Gateway Support ###

WooCommerce Payments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
gateway_scheduled_payments
tokenization
add_payment_method


### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-12-10 00:55:31 +00:00
Options: ✔
Notes: 51
Onboarding: skipped

### WooCommerce Payments ###

Version: 5.1.2
Connected to WPCOM: Yes
Blog ID: 212996707
Account ID: acct_1MANh3CAitkVB9W2

### Action Scheduler ###

Complete: 60
Oldest: 2022-12-02 01:09:16 +0000
Newest: 2022-12-09 01:14:57 +0000

Pending: 4
Oldest: 2022-12-09 02:16:55 +0000
Newest: 2022-12-10 00:12:15 +0000


### Status report information ###

Generated at: 2022-12-09 01:31:46 +00:00
```

</details>

### PR DESCRIPTION
**Pull request by james-allan**
Fixes #5264 

#### Changes proposed in this Pull Request

On HPOS environments, renewing WCPay Subscriptions would result in the subscription remaining on-hold after the renewal order was successfully paid. 

After some debugging I discovered that this error occurs because WC on HPOS always saves the status, even it hasn't changed. WC Core issue: https://github.com/woocommerce/woocommerce/issues/35951

In this context, the subscription was on-hold because of the following flow:

```php
function handle_invoice_paid()
│ $subscription_a = ...
│ $subscription_a->update_status( 'on-hold' );
│
○ $renewal_order->payment_complete();
│╲
│ ╲
│  ╲
│   ○ function WC_Subscriptions_Renewal_Order::maybe_record_subscription_payment()
│   │ 
│   $subscription_b = ...
│   $subscription_b->update_status( 'active' ) 
│
|
○ function mark_pending_invoice_paid_for_subscription()
|
$subscription_a->save() // overrides the 'active' status with 'on-hold' because that's the status $subscription_a had.
```

To summerise, a separate flow changes the status from on-hold to active, then the original instance that still thinks the subscription is on-hold is saved and that overrides that active status.

This PR fixes that by getting a fresh instance of the subscription after calling `$order->payment_complete()` so that the original instance now knows it has an active status.

#### Testing instructions

Legit testing:

* Enable HPOS
* Create a daily subscription
* Purchase the daily subscription using WCPay
* Wait until the subscription renews tomorrow.
* Confirm that the subscription after renewing has an active status.
    - On trunk the subscription stays on-hold.

Hacky way to test this:

* Enable HPOS
* Create a daily subscription
* Purchase the daily subscription using WCPay
* Run the following code snippet.
     - On `develop` the subscription will remain on-hold
     - On this branch the subscription will renew and have an active status. 

```php
$subscription =  wcs_get_subscription( 1006 );

$mocked_webhook_data = [
    'data'       => [
        'object' => [
            'subscription' => WC_Payments_Subscription_Service::get_wcpay_subscription_id( $subscription ),
            'id'           => 'in_' . gmdate( "U" ), // We need a unique invoice ID to create a new renewal order
        ],
    ],
];

WC_Payments_Subscriptions::get_event_handler()->handle_invoice_paid( $mocked_webhook_data );
```

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by Jinksi** [comment]
I've started the legit 24h testing 🧪🤞

**Comment by haszari** [comment]
> In this context, the subscription was on-hold because of the following flow:

Nice diagram @james-allan , super clear! Can you explain how you fixed the problem, I'm curious. Is there a way we can avoid having multiple copies of the subscription in-memory at the same time? It seems fragile to rely on WC core only persisting changed values (for a specific definition of "changed"!).

**Review by Jinksi — APPROVED** [review]
Nice one @james-allan 🙌 

I've tested this on 2 sites with HPOS enabled, one with syncing enabled, and one without.

After waiting for 24h for a Stripe Billing renewal, each Subscription status is **Active**  after a successful renewal order payment. ✅ 

On the site with syncing disabled, this status is not reflected on the Edit Subscription screen (due to admin screen changes coming in WIP HPOS PRs):

Screenshot 2022-12-15 at 16 29 47

However, I could confirm the **Active** subscription status by viewing the Related Orders metabox on the renewal order:

image

**Note:** there is a PHP unit test falling that needs addressing...

```
1) WC_Payments_Subscriptions_Event_Handler_Test::test_handle_invoice_paid
TypeError: Argument 1 passed to Mock_WC_Payments_Invoice_Service_9e440d51::mark_pending_invoice_paid_for_subscription() must be an instance of WC_Subscription, bool given.
```

**Comment by james-allan** [comment]
> Can you explain how you fixed the problem, I'm curious.

Well the problem is that a separate flow changes the status from on-hold to active, then the original instance that still thought the subscription was on-hold, saves and overrides that active status. 

The fix is to get a fresh instance of the subscription after calling `$order->payment_complete()` so that the original instance now knows it has an active status.

**Comment by james-allan** [comment]
> The fix is to get a fresh instance of the subscription after calling $order->payment_complete() so that the original instance now knows it has an active status.

Btw I've updated the original PR description to include this description, I usually take an approach of writing a PR that says: "This PR fixes that by ..." but hadn't done that in this case. 

> It seems fragile to rely on WC core only persisting changed values (for a specific definition of "changed"!).

Yep. This approach was suggested to us by the WC core team and is similar to what we do in other places too but I agree, this is fragile but tbh parts of this architecture is fragile because there's multiple instances of object existing in memory with all potentially different data. There's no underlying cache that means fetching a subscription or order that already exists in memory, doesn't return that order or subscription.

**Comment by haszari** [comment]
> There's no underlying cache that means fetching a subscription or order that already exists in memory, doesn't return that order or subscription.

Gotcha, so the longer term/ideal fix here would be to implement an [in-memory data access layer](https://en.wikipedia.org/wiki/Data_access_layer) or cache (aka [ORM](https://en.wikipedia.org/wiki/Object–relational_mapping), DAO), to prevent multiple divergent copies of database records (e.g. subscriptions, orders). And that would be a potentially be a good thing for Woo core to either mandate (recommend) or provide.

**Comment by james-allan** [comment]
> Gotcha, so the longer term/ideal fix here would be to implement an [in-memory data access layer](https://en.wikipedia.org/wiki/Data_access_layer) or cache (aka [ORM](https://en.wikipedia.org/wiki/Object%E2%80%93relational_mapping), DAO), to prevent multiple divergent copies of database records (e.g. subscriptions, orders). And that would be a potentially be a good thing for Woo core to either mandate (recommend) or provide.

Absolutely

**Pull request merged**
