### PR TITLE
Sync v1.7.1 changes with master

### PR DESCRIPTION
**Pull request by vbelolapotkov**
#### Changes proposed in this Pull Request

* Updates version within plugin headers.
* Updates readme and changelog with 1.7.1 changes

#### Testing instructions

* Tests should pass
* Smoke test on the site.

No additional tests needed.
No changelog entry required.

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

**Comment by shendy-a8c** [comment]
LGTM.

I am wondering why [the change in client/settings.js](https://github.com/Automattic/woocommerce-payments/pull/1156/files#diff-b97cd0cb6435c6edd80cc56e0d8dfb4499424e14e55a63c8f50c74f3c5d71c0f).

**Comment by vbelolapotkov** [comment]
> I am wondering why the change in client/settings.js.

Those changes are added by precommit hook [here](https://github.com/Automattic/woocommerce-payments/blob/sync%2F1.7.1/package.json#L47).

**Comment by DanReyLop** [comment]
> I am wondering why the change in client/settings.js.

Oops, my bad, I touched those lines as part of solving a merge conflict, and because I did it on the GitHub UI, `prettier` didn't run.

**Review by DanReyLop — APPROVED** [review]
Changes look good 👍

**Pull request merged**
