### PR TITLE
SCA support for subscription renewals

### LINKED ISSUE #2002: SCA Subscription renewals
Allow the customer to authenticate a subscription renewal that fail due to SCA.

### LINKED ISSUE #2113: SCA Subscriptions: Send an email when a renewal fails due to SCA auth required
Stripe PRs for inspiration: https://github.com/woocommerce/woocommerce-gateway-stripe/pull/991 https://github.com/woocommerce/woocommerce-gateway-stripe/pull/996

When a subscription renewal fails due to SCA auth:
- Prevent the Subscriptions engine from retrying the payment.
- Send the customer an special email indicating that the payment needs extra authentication.
- Prevent the Subscriptions engine from sending any further "payment failed" emails.

Note: See the conversation in https://github.com/Automattic/woocommerce-payments/pull/2158#issuecomment-861287024, we'll need to add a filter so TumblrPay can prevent sending an email and handle communicating with the customer themselves.

### LINKED ISSUE #2114: SCA Subscriptions: Allow the customer to re-authenticate a subscription renewal payment
Stripe PR for inspiration: https://github.com/woocommerce/woocommerce-gateway-stripe/pull/986

Add handling for the link included in the "Auth needed" email ([more context](https://github.com/Automattic/woocommerce-payments/issues/2113)). The URL will be to the `order-pay` page with a special GET parameter. Opening that page should:
- Check that, for that order, there's a Payment intent that's pending SCA authorization.
- If there is, immediately trigger the SCA modal.

### PR DESCRIPTION
**Pull request by DanReyLop**
Fixes #2002 
Fixes #2113 
Fixes #2114 

This PR is big, but do not despair. Most of it is just adding the email templates.

#### Changes proposed in this Pull Request

- Add an admin-facing email that's triggered when a Subscription renewal fails due to SCA. That email will replace the built-in email that's sent by WC Subscriptions.
- Add a customer-facing email that's triggered when a Subscription renewal fails due to SCA. That email has a link that the customer can click to immediately authenticate the payment.
- Tweak the Pay For Order page so the SCA modal automatically appears.

#### To test

- Install and activate WC Subscriptions.
- Create a Subscription product. It doesn't matter if it has a free trial.
- As a customer, buy the subscription product with an SCA test card. I recommend `4000002760003184` since that one will ask for SCA auth on every renewal payment.
- Go to `WP-Admin -> WooCommerce -> Subscriptions`, click on the Subscription you just created, and on the `Subscription Actions` metabox select `Process renewal`.
- Note that the Subscription is set to `On Hold` status, the renewal order is set to `Failed` status, and that you received 1 email as an admin and 1 email as a customer (I recommend installing the `WP Mail Logging` plugin).
- Click the `Authorize the payment` link on the email you received as a customer. You should see a bare-bones Pay For Order page and the SCA modal should pop up automatically.
- If you accept the modal, you'll get to the `Thank you` page, and the Subscription will be on `Active` status again.
- If you reject authentication instead, you'll see an error message. If you refresh the page, you'll see the default `Pay For Order` page, and you'll be able to pay for the renewal manually.

### CODE REVIEW

**Comment by dechov** [comment]
@DanReyLop Looks like there are more lint errors, exposed by the recent addition of Psalm?

**Review by oaratovskyi — COMMENTED** [review]
Tested, works as described. Looks good to me!

Just to double check: [this line](https://github.com/Automattic/woocommerce-payments/pull/2369/files#diff-bcfd303d507c33a27671935e724ee64d0df30ff2a18bb6ef4c94f28d48190124R962) sets the order to Failed after Process Renewal is clicked in WooCommerce Subscriptions admin?

**Comment by dwainm** [comment]
Confirmed that this works. Emails look good.

:shipit:

**Review by dwainm — APPROVED** [review]

**Comment by DanReyLop** [comment]
> Just to double check: this line sets the order to Failed after Process Renewal is clicked in WooCommerce Subscriptions admin?

Yes, that's expected. Setting the renewal order to `Failed` will, as a side-effect, set the Subscripion `On Hold`. That's what we want for a payment that hasn't been fully authorized yet.

**Comment by DanReyLop** [comment]
> Looks like there are more lint errors, exposed by the recent addition of Psalm?

@dechov Yes. I've just added most of them to the baseline (Psalm caught a legit error though!). They're just unrecognized functions/classes from WC Subscriptions, and "undefined global variables" used in the email templates.

**Pull request merged**
