### PR TITLE
Enable the Payments → Overview task list for all merchants

### LINKED ISSUE #4457: Launch the Payments → Overview task list
### Description

The **Payments → Overview** `Things to do` task list is considered production-ready and we can remove the feature flag (see pdjTHR-1p8-p2). This will allow users to view and act upon [the following task list items](https://github.com/Automattic/woocommerce-payments/blob/37997a7e550005c1d1ca827e6ffbf8da7b15093e/client/overview/task-list/tasks.js#L65):

* ~`update-business-details`: Update WooCommerce Payments business details.~
* ~`reconnect-wpcom-user`: WooCommerce Payments is missing a connected WordPress.com account. Some functionality will be limited without a connected account.~
* ~`force-secure-checkout`: Protect your customers data and increase trustworthiness of your store by forcing HTTPS on checkout pages.~
* `dispute-resolution-task`: *x* disputed payments needs your response.

> **Note**
> Initially, only the `dispute-resolution-task` will be visible. A separate issue ([#4471](https://github.com/Automattic/woocommerce-payments/issues/4471)) has been created to include all tasks listed above.

### Acceptance criteria

* [x] The **Payments → Overview** `Things to do` task list is visible to both existing and new merchants.   
#4460
* [x] Relevant documentation changes are drafted and ready to publish alongside release. For example, add "What is the payments task list?” to the [FAQ](https://woocommerce.com/document/payments/faq/#section-3). (pdjTHR-1lj-p2#comment-1590)
   **Doc has been added to the [FAQ in the Account Management section](https://woocommerce.com/document/payments/faq/#section-3). [Direct link to page](https://woocommerce.com/document/payments/faq/what-is-the-things-to-do-checklist/).**
   * What it is.
   * Why it exists.
   * What types of notifications it will display.
   * Where it’s available & when it will show up.
   * Perhaps a recommendation on how to best use it.

### Testing instructions

1. If using WCPay Dev Tools, clear the `_wcpay_feature_account_overview_task_list` option (`/wp-admin/options.php`).
2. Ensure one or more of the task list items above will be visible.
    * Create a disputed transaction by purchasing a product using the card number `4000000000000259`.
4. Go to **Payments → Overview**.
5. The `Things to do` task list should be visible.

177257538-a9cf8f3b-c2c3-40a9-90e0-6f37a1bb06cd

### Additional context

* Launch the WCPay Overview task list proposal P2: pdjTHR-1lj-p2
* Launching this task list is a requirement for the **Improve disputes visibility** project: pdjTHR-17C-p2#comment-1661
* Discussion on slack about removing the feature flag: p1656467651769769-slack-CGGCLBN58

### PR DESCRIPTION
**Pull request by Jinksi**
Resolves code changes as part of #4457

#### Changes proposed in this Pull Request

This PR makes the **Payments → Overview** `Things to do` task list visible to all new and existing merchants.

The default value for the `_wcpay_feature_account_overview_task_list` feature flag option is set to `'1'`. Sites that have explicitly set the option to `'0'` (e.g. using WCPay Dev Tools) will not see the task list.

Current task list items include:

* ~`update-business-details`: Update WooCommerce Payments business details.~
* ~`reconnect-wpcom-user`: WooCommerce Payments is missing a connected WordPress.com account. Some functionality will be limited without a connected account.~
* ~`force-secure-checkout`: Protect your customers data and increase trustworthiness of your store by forcing HTTPS on checkout pages.~
* `dispute-resolution-task`: *x* disputed payments needs your response.

> **Note**
> Initially, only the `dispute-resolution-task` will be visible. A separate issue ([#4471](https://github.com/Automattic/woocommerce-payments/issues/4471)) has been created to include all tasks listed above.

#### Testing instructions

1. If using WCPay Dev Tools, clear the `_wcpay_feature_account_overview_task_list` option (`/wp-admin/options.php`).
2. Ensure one or more of the task list items above will be visible.
    * Create a disputed transaction by purchasing a product using the card number `4000000000000259`.
4. Go to **Payments → Overview**.
5. The `Things to do` task list should be visible.

image

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply) Tested on Safari iOS 15.5

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by shendy-a8c** [comment]
> Sites that have explicitly set the option to '0' (e.g. using WCPay Dev Tools) will not see the task list.

I wonder if we should just make the task list enabled for everyone, even for those stores that has `_wcpay_feature_account_overview_task_list` set to `0`, which I assume there is none other than those with WCPay Dev Tools. Therefore, we can also remove `is_account_overview_task_list_enabled()`.

Also, we might then need to remove that toggle from WCPay Dev Tools.

What do you think?

**Comment by aprea** [comment]
> > Sites that have explicitly set the option to '0' (e.g. using WCPay Dev Tools) will not see the task list.
> 
> I wonder if we should just make the task list enabled for everyone, even for those stores that has `_wcpay_feature_account_overview_task_list` set to `0`, which I assume there is none other than those with WCPay Dev Tools. Therefore, we can also remove `is_account_overview_task_list_enabled()`.
> 
> Also, we might then need to remove that toggle from WCPay Dev Tools.
> 
> What do you think?

We might want to consider keeping the option as it would let merchants disable the task list in the scenario that there's a bug that we don't know about.

We can always remove it later when we're pretty confident that the task list is working as expected.

**Comment by aprea** [comment]
FYI there was recently a P2 + designs that showed the "Things to do" component above the balances box - paJDYF-4EQ-p2

I think we're probably okay with this PR as-is but just something to keep in mind.

Otherwise, might be worth reaching out to @elizaan36 for confirmation.

**Comment by Jinksi** [comment]
@aprea Thanks for pointing that out. We've merged #4400 to move the task list above Account Details, but I'll ask for confirmation to see if it should be moved to the top.

**Comment by Jinksi** [comment]
Due to a bug preventing all but the disputes task from being visible, I've updated the description with the following note:

> **Note**
> Initially, only the `dispute-resolution-task` will be visible. A separate issue will be created to include all tasks listed above.

**Review by james-allan — APPROVED** [review]
> Due to a bug preventing all but the disputes task from being visible, I've updated the description with the following note:

With this in mind, these changes look good to me. Thanks @Jinksi!

**Pull request merged**
