### PR TITLE
Display UPE fields in checkout with less than 50 cents in the cart

### LINKED ISSUE #2700: UPE - Checkout with cart total under 50 cents
When trying to checkout with a cart total under 50 cents USD, UPE throws an error when trying to mount. This has been mentioned by a few merchants and they called out that this 50 cent limit should only be applied after shipping cost has been added in. Due to how UPE works though, we need to create the intent before we know the shipping costs which will cause this error. We will need to find a workaround for this issue so that it does not throw an error until shipping costs are calculated in to the total.

**Steps to Reproduce**
1. With UPE enabled and currency set to USD, create a product with a cost of 0.40 USD.
2. Go to checkout with just one of those products.
3. When the payments area begins the load it will throw the following error: `Error: Amount must be at least $0.50 usd`

UPE-50cent-error

### PR DESCRIPTION
**Pull request by RadoslavGeorgiev**
This PR replaces https://github.com/Automattic/woocommerce-payments/pull/2872, which was convoluted because of a strategy change, and would have been tough to review.
Fixes #2700

### Description of the issue

In order to avoid money loss, Stripe has [minimum and maximum charge amounts](https://stripe.com/docs/currencies#minimum-and-maximum-charge-amounts).

When using Stripe Elements (not UPE) Stripe's API returned an error (see image below) when attempting to create and confirm the intent, which happens after the checkout form is submitted.

classic-error

This was acceptable, because it allowed fields to be displayed on the checkout page **and a shipping method to be selected**, which might bring the order total above the minimum required amount.

As noted in https://github.com/Automattic/woocommerce-payments/issues/2700, UPE fields require a payment intent to be created in order to use the secret of that intent for displaying the fields. Whenever it happens that the **cart total** is lower than the minimum amount, payment fields would not be displayed at all.

### The purpose of this PR is to:

- Allow UPE fields to be displayed even when the cart total is less than 50 cents (or the amount for the store currency).
- Include more information in the error message both for UPE fields and for normal fields:

image

This message indicates to customers what necessitates the minimum amount, and lets them potentially choose another payment method. Also, now it is translatable.

#### Strategy for handling the error and displaying fields

Stripe provides a "hard-coded" list of minimum amounts per currency, however it depends on the currencies of the merchant's bank accounts (deposit currencies). For example:

1. A customer browses the store in EUR. There's a minimum amount of EUR 0.50 for transactions.
2. The merchant does not have an EUR bank account, but has an USD default account.
3. The minimum amount of the purchase is actually $0.50, because of the merchant's account, and EUR 0.50 would have to be converted to USD in order to determine the minimum account.

In order to strictly reject orders with less than the minimum amount, this would ideally require:

1. All minimum amounts per currency to be hard-coded **and maintained** on the server.
2. Those amounts to be converted to all presentment currencies and delivered through an endpoint.
3. The client to query/keep those amounts regularly in order to use them during checkout.

~This solution seemed tedious, so I opted to utilize the errors, returned from the Stripe API, and cache their values in order to minimize the number of hoops during checkout.~ `amount_too_low` errors are now thrown by the server in 1204-gh-Automattic/woocommerce-payments-server, and include the minimum amount in the context of the current account, as well as the currency it applies to. 

### Changes proposed in this Pull Request

Handle `amount_too_small` errors, returned from the server.

#### Add the `Amount_Too_Small_Exception` exception class

This exception is now raised within `WC_Payments_API_Client::extract_response_body` instead of a standard exception.

In conjunction with `WC_Payments_Utils::get_filtered_error_message`, this exception will allow a properly formatted and translatable message to be displayed when **not using UPE fields**.

#### Returned errors

In both gateways (standard and UPE), we used to return an array with `'result' => 'fail'` upon errors, and to manually add notices. Turns out that simply throwing an exception works the same way, but is better handled when using the checkout block.

#### Behavior modifications

In `UPE_Payment_Gateway::create_payment_intent` in order to **temporarily increase** the amount for the intent in order to match the minimum amount. If the minimum is not reached when trying to update the intent later, there will be a separate error.

In all cases, the minimum amount will be cached when displaying the message, or increasing the intent amount.

The cached value is used the following places in order to display a message without having to reach the API first:
- `WC_Payment_Gateway_WCPay::process_payment_for_order`
- `UPE_Payment_Gateway::create_payment_intent`
- `UPE_Payment_Gateway::process_payment` in case shipping costs have not increased the order total past the minimum required amount.

### Testing instructions

Preparations:

- Create or modify a physical product in order to have it priced below the threshold. Example: 0.40 EUR or USD
- Create a shipping method (ex. flax rate) priced low enough to not pass the threshold in combination with the product above. Example: 0.05 EUR or USD
- Create another shipping method, priced high enough in order to pass the threshold: 0.5 or more USD or EUR.

#### Standard flow

With UPE fields disabled, use classic checkout to:

1. Add the cheap product to the cart.
2. Navigate to the checkout page.
3. Choose the cheap shipping method and try to check out.
4. Ensure that the error shown is descriptive about the issue (see screenshots above).
5. Select the expensive shipping method.
6. Make sure the order goes through.

Now **enable UPE fields** and:

1. Add the cheap product to the cart.
2. Navigate to the checkout page.
3. **Make sure that UPE fields are visible**, meaning that the minimum amount was handled and temporarily increased.
4. Select the cheap shipping method is selected, and try to check out.
5. Verify that a proper error has been displayed.
6. Select the expensive shipping method and try checking out again.
7. Make sure that checkout goes though.

This should work with both the classic checkout and the checkout block.

-------------------

- [x] Added changelog entry
- [x] Covered with tests
- [x] Tested on mobile does not apply

**Post merge**

- [ ] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply)

### CODE REVIEW

**Comment by naman03malhotra** [comment]
Great PR, with a very detailed description. I've reviewed the code and looks good. But I am getting the following error where the stripe doesn't return the amount at all.

IMO, we can merge this improvement and create a separate ticket for the following error and solve for this as it may come. What do you think?



image

cc @achyuthajoy to test it once, as I was hitting the following error.

**Comment by RadoslavGeorgiev** [comment]
@naman03malhotra when is this error happening? The only situation where I'm expecting to receive an error without amount is when there's a mismatch between the real FX rates and the subs for the local server 🤔

**Comment by naman03malhotra** [comment]
@RadoslavGeorgiev this is happening for me with the normal checkout flow, I have an account where GBP is the deposit currency and EUR as the presentment currency, I am adding items to the cart and checking out normally and this happens. If it helps I can share a screencast or we can jump on a call as well. I could be missing something.

**Review by naman03malhotra — APPROVED** [review]
LGTM! tests well. Beautiful PR I must say. Can't find anything that we should change.
ps: I did not switch to server branching while testing, which was leading to that error.

**Comment by RadoslavGeorgiev** [comment]
Thank you for the kind words @naman03malhotra! Now that the server PR has been deployed, I'm merging this one as well!

**Pull request merged**
