### PR TITLE
Dev: Move Klarna E2E tests to Playwright

### LINKED ISSUE #9376: Fix flaky E2E Klarna tests
### Description
The Klarna E2E tests are currently difficult to maintain given that the contents of the iframes or pages that we are currently using in the flows, are completely outside of our control.

A recent example of an external change breaking the tests can be found here: https://github.com/Automattic/woocommerce-payments/issues/9339#top

The tests are also flaky given the patterns that the Klarna UI uses, where it's difficult to determine when an element is clickable, and causing a lot of issues with puppeteer, since the elements are not being clicked correctly, the next assertions in the flow will create timeouts.

**Output from the test failure**:
```
● Klarna checkout › should successfully place an order with Klarna

    TimeoutError: Waiting for selector `#phoneOtp` failed: Waiting failed: 25000ms exceeded
```

### Additional context
Another recent instance when we had to fix the tests due to an external change can be found here: https://github.com/Automattic/woocommerce-payments/pull/9183

### Priority
Medium. The tests are somewhat stable right now, and the retries usually help, but given the history of these tests, they will eventually break again when the next external change is deployed.

### Reason why this e2e test is broken
External updates.

> [!Important]
> Please, ensure when closing this issue (PR fix) that only one `e2e: broken` label is added and it is accurate.
> - [x] I confirmed there's only one `e2e: broken` label in this issue and it is accurate.

### PR DESCRIPTION
**Pull request by danielmx-dev**
Fixes #9376

#### Changes proposed in this Pull Request

The Klarna E2E tests are currently difficult to maintain given that the contents of the iframes or pages that we are currently using in the flows, are completely outside of our control.

A recent example of an external change breaking the tests can be found here: https://github.com/Automattic/woocommerce-payments/issues/9339#top

This PR does the following:
* Migrate the Klarna tests from Puppeteer to Playwright.
* Reduce the actions performed in Klarna Playground, given the unpredictability of the rendered elements that are completely outside of our control.
* Improve the stability of clicking the place order button in Playwright, which is a common source of flaky tests.

#### Testing instructions

* Follow the instructions in [/tests/e2e-pw/README.md](https://github.com/Automattic/woocommerce-payments/blob/81e3207c2ee13c3d5dc68b40839e984992c5ea12/tests/e2e-pw/README.md) to run the tests locally.
* Alternatively, you can verify the Playwright results in this PR checks and also run the Puppeteer E2E tests in a github action for this branch in the following URL https://github.com/Automattic/woocommerce-payments/actions/workflows/e2e-test.yml

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9377` or branch name `dev/update-klarna-e2e-tests` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=dev/update-klarna-e2e-tests) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: aea0a0db8c9d6a07f36df480e8bb29440cfa3285
- Build time: 2024-09-06 18:21:33 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by danielmx-dev** [comment]
Latest Playwright results https://github.com/Automattic/woocommerce-payments/actions/runs/10725593485/job/29743779558?pr=9377

Note that no retries are needed: 
image

If you compare it to another run, you'll notice that retries are usually needed https://github.com/Automattic/woocommerce-payments/actions/runs/10738192446/job/29781267416
image

Here's also a run of the Puppeteer E2E tests using this branch https://github.com/Automattic/woocommerce-payments/actions/runs/10705116865/job/29679741104

**Review by frosso — APPROVED** [review]
Awesome, thank you for the refactor and for simplifying the tests! 💯 what you did makes sense - we don't really need to test the whole flow, since it's out of our control.

It would still be nice to ensure that, at the end of the Klarna flow, the customer is redirected to the "Order success" page.
But that would require testing the whole flow 😆

**Comment by danielmx-dev** [comment]
> It would still be nice to ensure that, at the end of the Klarna flow, the customer is redirected to the "Order success" page.
But that would require testing the whole flow 😆

Ideally we would want to skip the whole Klarna Playground UI, but I wasn't able to find any way to do it in either documentation (Stripe/Klarna)

**Pull request merged**
