### PR TITLE
Update - Allow viewing Stripe account details only in page Overview.

### PR DESCRIPTION
**Pull request by htdat**
#### Changes proposed in this Pull Request

When working on #2476, I found out users can access their Stripe Connect accounts in two places: 

- Payments > Overview - React (WcAdmin based).
- Payments > Settings (traditional WooCommerce > Settings page).

Then this PR does: 

- ~Redirect users to page Overview from page Settings when they want to edit their Stripe Express account.~
- Remove the Account section in the traditional WooCommerce > Settings page.
- Clean up the current code that is handling this action from two places. 
- ~Change the instruction text.~

Benefits: 

- Code is simplified and easier to maintain. 
- Consistent experience for users as they have only one place to access their Stripe info.

| Before  | After |
| ------------- | ------------- |
| Markup on 2021-07-20 at 19:24:08  | Markup on 2021-07-27 at 18:41:12 |

#### Testing instructions

- Apply this PR. 
- Visit http://site.com/wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments
- Expect: The `Account` section no longer exists. 

**If we have a consensus on this PR, I'd like to have more feedback regarding the wording change**. 

-------------------

- [x] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

**Review by kalessil — APPROVED** [review]
LGTM (also wording looks great, thanks!)

**Comment by kalessil** [comment]
@dmvrtx: any chance to recall, what we were planning to do with the old section on the settings page we are touching here?

**Comment by dmvrtx** [comment]
> @dmvrtx: any chance to recall, what we were planning to do with the old section on the settings page we are touching here?

If my memory serves me well it should become obsolete. But maybe @LevinMedia can provide more insights.

**Comment by LevinMedia** [comment]
@dmvrtx that's correct - with the new settings design, this section is removed, and only accessible from the overview screen. So we don't want to redirect people from the overview to the settings - we'll just want to send them directly to Stripe.

**Review by kalessil — CHANGES_REQUESTED** [review]
@htdat : as per the responses, we should delete this section from the settings screen.

**Comment by htdat** [comment]
> @htdat : as per the responses, we should delete this section from the settings screen.

Updated the code for this (bea4e08 and  ff3db08) and the PR description. Ready for review again.

**Review by kalessil — APPROVED** [review]
LGTM, :shipit: !

**Pull request merged**
