### PR TITLE
Replace overwriting $current_section with overwriting Payments tab URL

### LINKED ISSUE #1646: fix: breadcrumb link on payment methods
## Description

When the grouped settings is enabled, the breadcrumbs on other payment methods redirect to WCPay, instead of the list of all the payment methods.

### PR DESCRIPTION
**Pull request by waclawjacek**
Fixes #1646.

#### Changes proposed in this Pull Request

Okay! So first, a legend:

Markup on 2021-05-31 at 17:34:08

#### Why is this happening

In #1580 we implemented a change to what the default section of the Payments tab is. It is based on the observation that when section links are rendered, the default one always has the `section` query parameter set to an empty string: `&section=` (this is the case in all tabs - see e.g. the Shipping tab's "Shipping zones" section link). This is opposed to the link on the tab itself, from which the `&section` parameter is absent.

As a result, we currently handle three possible situations:

1. `/admin.php?page=wc-settings&tab=checkout` (= link on the "Payments" tab).
    * The section parameter is absent from the URL (`! isset( $_REQUEST['section'] )`).
    * If we detect the `section` parameter is absent, we redirect to the WCPay settings page by tweaking the `$current_section` global variable under the hood.
1. `/admin.php?page=wc-settings&tab=checkout&section=` (= link on the "All payment methods" section).
    * The section parameter is present but empty (`$_REQUEST['section'] === ''`).
    * All default sections have this URL structure so we treat this as a direct request for the "All payment methods" section and do no rewriting.
1. `/admin.php?page=wc-settings&tab=checkout&section=<some section name>`
    * The section parameter has a specific value. No rewriting done because a specific section is requested.

The issue reported here demonstrates that relying on this behavior (distinguishing if `section` is empty/absent) doesn't support all links to the default WC settings page. Some links (such as the back arrow in question) have no `section` param, which is against the above assumption.

#### Proposed approach

We could try to fix the specific back arrow link mentioned in this issue but we might risk running into this issue again with another link somewhere so I'd like to suggest an alternative approach. Instead of redirecting to the WCPay section by default, let's replace the URL on the "Payments" tab button. So instead of the current:

```
/admin.php?page=wc-settings&tab=checkout
```

The link for the tab in the screenshot would now be:

```
/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments
```

This approach is safer because we don't overwrite what's regarded as the default section, potentially breaking links depending on the "All payment methods" being the default but it results in the Payments tab link being the only one with a `&section` parameter.

#### Testing instructions

1. Enable the grouped settings feature flag `_wcpay_feature_grouped_settings`.
1. Visit the WooCommerce > Settings > Payments tab.
    * You should arrive at the "WooCommerce Payments" settings page.
1. Visit the WooCommerce > Settings > Payments > All payment methods section and select a payment method.
    * After clicking the back arrow, you should arrive at the "All payment methods" settings page.

Markup on 2021-06-01 at 13:53:31

*

-------------------

- [x] Added changelog entry (or does not apply)
    - Not added - feature behind feature flag.
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

**Review by frosso — APPROVED** [review]
The changes look good 👍 Thanks for the explanation, that was very useful! The solution looks good to me too!

I noticed there's a few spots that should be updated - maybe as part of this PR, since this PR also updates the functionality of the pages/URLs?
- https://github.com/Automattic/woocommerce-payments/blob/b1ce1cf83232dc27237bafd0b2e64b06d36f1fdb/client/additional-methods-setup/methods-selector/setup-complete-task.js#L98
- https://github.com/Automattic/woocommerce-payments/blob/b1ce1cf83232dc27237bafd0b2e64b06d36f1fdb/client/components/payment-methods-list/delete-button.js#L94

I think those are the last ones - LMK if you find other ones!

**Comment by waclawjacek** [comment]
Great catch and thanks for the review! I have updated these links. I didn't find any others to update.

**Comment by frosso** [comment]
Sounds great, thanks!

**Comment by dechov** [comment]
FYI https://github.com/Automattic/woocommerce-payments/issues/2327 – should it only overwrite if WCPay is connected?

**Comment by waclawjacek** [comment]
@dechov Looks like it! It seems that conditionally binding [these filters](https://github.com/Automattic/woocommerce-payments/pull/1974/files#diff-1a16c5b7ee4e56444d93dbef661956fa97aa38c41976ccb7c5831188e9dcc513R29-R33) or adding an `if` to the method bodies will resolve that.

Will you implement a fix for that or should I create an issue to get it resolved?

**Comment by dechov** [comment]
:+1: Up to you – I can do it later this week if no one else gets to it first.

**Comment by frosso** [comment]
Thanks both, since it seems pretty straightforward, I'm working on testing a quick patch here: https://github.com/Automattic/woocommerce-payments/pull/2373

**Pull request merged**
