### PR TITLE
Add WP_UnitTestCase stub to support IDEs

### PR DESCRIPTION
**Pull request by htdat**
Fixes #
See p1690788060666279/1690552526.889459-slack-CGGCLBN58

#### Changes proposed in this Pull Request

- Add WP_UnitTestCase stub to support IDEs.
- This is similar to the previous effort here https://github.com/Automattic/woocommerce-payments/pull/2845

#### Testing instructions

- All tests run fine.
- PhpStorm and VSCode can now recognize and suggest PHPUnit methods. 

*

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6877` or branch name `dev/add-stub-WP_UnitTestCase` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=dev/add-stub-WP_UnitTestCase) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 0d14fd74a6b6d2075a4b2716b820d20936f473dd
- Build time: 2023-07-31 08:17:13 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by naman03malhotra — COMMENTED** [review]
>This is similar to the previous effort here https://github.com/Automattic/woocommerce-payments/pull/2845

I am curious why this was removed. Probably worth documenting in this PR for future context.

**Review by RadoslavGeorgiev — APPROVED** [review]
Changes look great, thank you for figuring this one out quickly, @htdat! 👏 :shipit:

**Comment by RadoslavGeorgiev** [comment]
> I am curious why this was removed.

@naman03malhotra [this PR](https://github.com/Automattic/woocommerce-payments/pull/4302) did some modifications to allow tests to run on WPCOM. Changing the base class for tests seems to have been one of the requirements to make that happen. Because the new base class does not exist in local codebases, as a side effect, editors are unaware of it.

> Probably worth documenting in this PR for future context.

The stub that's being introduced in this PR is purely a stub (otherwise unused), I see no reason why someone would remove it. The PHPDoc comment is meaningful enough.

**Pull request merged**
