### PR TITLE
Update links to use the woocommerce.com domain

### LINKED ISSUE #8573: Switch URLs from woo.com to woocommerce.com
### Description

We are switching back to using the `woocommerce.com` domain instead of the current `woo.com` one. All URLs should reflect this change, even if there will be redirects in place.

### Acceptance criteria

* All URLs using `woo.com `should be using `woocommerce.com`

### Dev context
The PR that handled the previous domain switch: https://github.com/Automattic/woocommerce-payments/pull/7643

### Additional context
p6q6po-fKm-p2
paqDfi-9z5-p2

### PR DESCRIPTION
**Pull request by vladolaru**
Fixes #8573 

#### Changes proposed in this Pull Request

- Update hyperlinks across the plugin to refer to the `woocommerce.com` domain rather than `woo.com`
- Update plugin URL to point to `woocommerce.com` in the `woocommerce-payments.php` file.

#### Testing instructions

Currently, `woocommerce.com` redirects to `woo.com`. As you test the links, it is expected to be redirected to `woo.com` links. The needed changes will be handled upstream.

* Spot-check a few of the URLs in the diff to ensure they go to the correct pages (no 404 or other errors).
* Check a few of the links in the plugin (for example, there are some hyperlinks on the `Payments > Settings` page like the Multi-Currency documentation link).

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8574` or branch name `update/8573-switch-links-to-woocommerce-com-domain` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=update/8573-switch-links-to-woocommerce-com-domain) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: d424195cbdbc73534778c65845bb77134268ae74
- Build time: 2024-04-08 06:48:59 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by oaratovskyi — APPROVED** [review]
Looks good to me! 
Pre-approving

I have a few questions:
`const DEFAULT_WOOPAY_URL = 'https://pay.woo.com';`
should it remain the same?

and woocommerce changes - would they be handled in a separate issue? I found a lot of woo.com occurences in woocommerce repo

**Comment by vladolaru** [comment]
Thanks for doing the review, @oaratovskyi 

> I have a few questions:
> const DEFAULT_WOOPAY_URL = 'https://pay.woo.com';
> should it remain the same?

I will leave it like this because it may have other implications (like APIs) and the timing might need to be different (for example, I noticed that `pay.woocommerce.com` doesn't currently work) cc @pierorocca 

> and woocommerce changes - would they be handled in a separate issue? I found a lot of woo.com occurences in woocommerce repo

That should be a separate issue on the WooCommerce repo, as were the Nov 2023 changes (https://github.com/woocommerce/woocommerce/pull/41241) cc @lsinger

**Comment by pierorocca** [comment]
@vladolaru Yes pay.woo.com is correct. WooPay has never been on the woocommerce domain.

**Comment by pierorocca** [comment]
cc @c-shultz in case any of these domain changes are breaking to WooPay.

**Pull request merged**
