### PR TITLE
Show "Download" label on documents list view table

### LINKED ISSUE #7014: Download column not labeled in columns list under Payments > Documents
If you have a WooPayments site which receives VAT invoices, you can see under Payments > Documents that the column containing the download links does not have a header. This causes there to be an unlabelled column in the three dots menu.

Screenshot taken on 2023-08-16 at 16 41 06 UTC@2x

Screenshot taken on 2023-08-16 at 16 41 25 UTC@2x

### PR DESCRIPTION
**Pull request by Jinksi**
Fixes #7014

#### Changes proposed in this Pull Request

Adds the missing "Download" column heading label and toggle menu option to the Payments → Documents list view table.

I've also:
* adjusted the padding of the "Download" buttons to align with the new column heading
* replaced the deprecated `isLink` Button component prop with `variant="link"` on the download button

**Before/After gifs**

Document list view table:
table

Document list view table toggle menu:
toggle

#### Testing instructions

* Pre-requisite: ensure you have VAT tax documents and can see Payments → Documents
* Navigate to Payments → Documents
* Ensure you can see the "Download" column label
* Open the three dots menu and ensure the menu includes a "Download" toggle
* Check on mobile viewpots

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : **Minor change, release testing not required**
- [x] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable. **N/A**
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9763` or branch name `fix/7014-documents-list-view-table-download-label` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/7014-documents-list-view-table-download-label) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 8fade7bedf48910958ca6e290f0f094d8421ce8d
- Build time: 2024-11-20 22:48:33 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by Jinksi** [comment]
Requesting a review from @jessy-p as a fellow reporting quality squad member this sprint. 🙏

**Comment by nagpai** [comment]
#### Manual test

✅ - Ensure you can see the "Download" column label



✅  - Open the three dots menu and ensure the menu includes a "Download" toggle

I am able to see this, however the menu itself seems clipped on the right side. The issue seems to be with an upstream component though since I am seeing the same issue with Woo core analytics pages. ( I will test later and create a core issue if needed )

**Review by nagpai — APPROVED** [review]
The code changes look fine to me.

The changes test well manually too and this is ready to ship 🚢

**Comment by Jinksi** [comment]
> I am able to see this, however the menu itself seems clipped on the right side. The issue seems to be with an upstream component though since I am seeing the same issue with Woo core analytics pages. ( I will test later and create a core issue if needed )

@nagpai +1 and there's an open issue for it https://github.com/woocommerce/woocommerce/issues/43256, so I've added some context to it, mentioning that this impacts downstream consumers of `TableCard`.

**Comment by tomalec** [comment]
I made a fix for TableCard in https://github.com/woocommerce/woocommerce/pull/53066
FWIW, if you face a similar issue with `EllipsisMenu` elsewhere, you can use `<EllipsisMenu placement="bottom-end">` to fix it  (once the PR gets merged).

**Comment by Jinksi** [comment]
🎉 Thanks @tomalec – I'll open an issue to consume your `TableCard` fix downstream in WooPayments once it is published in a new `@woocommerce/components` version.

**Comment by Jinksi** [comment]
> I made a fix for TableCard in https://github.com/woocommerce/woocommerce/pull/53066

I've opened issue #9870 to handle this `@woocommerce/components` fix downstream in WooPayments.

**Pull request merged**
