### PR TITLE
Implement pending account status

### LINKED ISSUE #5672: Support pending account status
### Description
Currently, when our merchants complete the KYC, the account goes into the `Pending` state on Stripe. But it's not supported yet on our side, and we show the account status as Restricted. Need to implement this both on the server and client.

### Acceptance criteria
After completing the KYC account status is Pending (not Restricted as of now).

### Designs
To be updated after discussion in Slack p1677489197405299-slack-C03PGHYA8TG.

Probably we should have a tooltip like this 
image

### Dev notes
On the server, we should return new status only for clients that have a version more than the version it'll be released in.

### Additional context
p1678112824209089-slack-C03KTTK2YMA

### PR DESCRIPTION
**Pull request by oaratovskyi**
Fixes #5672 

### Changes proposed in this Pull Request

* Support `Pending` status in the `StatusChip` component.
* Support tooltip in the `Chip` component.
* Support pending states for `DepositsStatus` and `PaymentsStatus` components.
* Apply pending status for all the components listed above is `accountStatus.status` is `pending_verification`.
* Update tests accordingly.

#### Pre-requisites
* Checkout to `add/5672-support-pending-account-status`
* Change client version to `5.9.0` in https://github.com/Automattic/woocommerce-payments/blob/4f10067f81222300ac480791a7ebc7d822a62a56/woocommerce-payments.php#L15-L15

#### Local testing
* Follow testing instructions from server PR (Local testing)
* Onboard new account (non-progressive). You can pick estimated timeline as `6+ months` for Full KYC
* You should see this state of account details 
image
* Hover on `Pending` status and verify you can see the tooltip 
image
* Roll-back changes from the server PR, clear the account cache.
* You should see that account is complete now 
image

#### Sandbox testing

* Follow testing instructions from server PR (Sandbox testing)
* Onboard new account (non-progressive). You can pick estimated timeline as 6+ months for Full KYC
* You should see this state of account details 
image
* Hover on `Pending` status and verify you can see the tooltip 
image
* Wait a few mins, clear the cache and reload the page, now it should be complete 
image

#### Bonus
* You could test that for client version less than `5.9.0` pending status is overridden to `Restricted` (as it was before this PR)
-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _ 'QA Testing Not Applicable'_
- [x] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [x] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6148` or branch name `add/5672-support-pending-account-status` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=add/5672-support-pending-account-status) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 33480f7ce51c0fd9ee9e22645267ca88b3bb473e
- Build time: 2023-05-03 07:09:41 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by dmallory42 — APPROVED** [review]
LGTM! Tested locally and works as expected, thanks for working on this!

Making a note that I tested these changes locally, but wasn't able to test on sandbox due to an (unrelated to this PR) error with my sandbox jetpack authentication.

**Comment by vladolaru** [comment]
@oaratovskyi I've tested with the sandbox, and all works as expected (including the bonus testing). 

What I am a little puzzled about is this "You can pick estimated timeline as 6+ months for Full KYC" when we are not using progressive. I went with a Full Stripe KYC, not the PO. I hope that is as expected.

**Comment by oaratovskyi** [comment]
Thanks, @vladolaru !
> What I am a little puzzled about is this "You can pick estimated timeline as 6+ months for Full KYC" when we are not using progressive. I went with a Full Stripe KYC, not the PO. I hope that is as expected.

I specified this param because if you select `Already live` or `within 1 month` combined with revenue `less than 250k`, you'll end up with PO path. Yep, proceeding with the Full Stripe KYC using another way is also fine!

**Pull request merged**
