### PR TITLE
Update cache after persisting the User session

### PR DESCRIPTION
**Pull request by asumaran**
Fixes https://github.com/Automattic/woopay/issues/2774 

#### Changes proposed in this Pull Request

When a user clicks the “Buy with WooPay” button from the product page, the product is added to the cart, and an empty WC session is created. The session identifier is sent to WooPay and used for Store API requests. These requests are handled by the `WCPay\Platform_Checkout\SessionHandler` class although when visiting the checkout page, the session is handled by the `WC_Session_Handler` class.

As a result, we end up with two classes managing the same WC session.

`WC_Session_Handler` tries to retrieve the session from the cache after it has been updated by WooPay via the Store API. However, it fetches an outdated state of the session (last updated when the user clicked the “Buy with WooPay” button), causing the checkout pages to appear empty.

To resolve this, we replicate the steps performed by the `WC_Session_Handler` in its `save_data` method. We update the cache in `WCPay\Platform_Checkout\SessionHandler` via `wp_cache_set`, ensuring that the session is synchronized and ready for the consumption of the `WC_Session_Handler` class.

### Testing instructions

> [!IMPORTANT]  
> In order to get the bug we need to enable object cache. An easy way to do that is by installing the [W3 Total Cache plugin](https://pe.wordpress.org/plugins/w3-total-cache/). Go through its settings and make sure to enable the Object Cache with the save to "Disk" option.

**Required setup**
- WooPay is enabled.
- Make sure your site W3 Total Cache plugin is properly set up with Object Cache enabled.
- Make sure you are logged into your local WooPay account.
- Make sure you have both, block-based and a shortcode-based checkout pages.
- Make sure you have shipping options defined.

**Reproduce the bug.**

1. Checkout to the `develop` branch.
2. Go to the merchant store and click on a simple product that requires shipping.
3. Click "Buy with WooPay"
4. In WooPay expand the "Pay with" section. Then click "Alternative payment methods"
5. Notice your WooPay customer details are not pre-filled in the checkout form.
6. Go to the other checkout page and notice customer details are also missing.

**Bug fix confirmation.**
1. Checkout to the `as-fix-woopay-data-mismatch` branch.
2. Remove cookies in your merchant store to ensure you are creating a new WC session.
2. Go to the store and click on a simple product that requires shipping.
3. Click "Buy with WooPay"
4. In WooPay expand the "Pay with" section. Then click "Alternative payment methods"
5. Notice your WooPay customer details **are pre-filled** in the checkout form.
6. Go to the other checkout page and notice customer details are pe-filled correctly.

#### Note
- The billing address is not currently populated on the block-based checkout page. It used to work, but it seems that recent changes to the billing area have made it no longer work. It's behaving like this even without Object Cache, so it's a separate issue. Shortcode-based checkout should work fine.

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9277` or branch name `as-fix-woopay-data-mismatch` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=as-fix-woopay-data-mismatch) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: f01f462a8211bd1c52cad43a50a3277af2a80927
- Build time: 2024-08-19 17:26:00 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by bborman22 — COMMENTED** [review]
I tested this in several scenarios:
- From shortcode and blocks checkout as default page.
- From product page, cart, and checkout blocks to get to WooPay.
- From cart page using Direct Checkout.
- With a caching plugin and without one. 

I was able to confirm that without these changes combined with a caching plugin, the checkout page was not getting the shopper's data from WooPay. Once I applied this branch I was successfully getting the WooPay data to populate either the shortcode or the blocks checkout page.

As an additional confirmation, I was able to build this branch and apply it to our test merchant site and confirmed the issue was reproducible and that this branch fixed the issue!

From a code review perspective, adding this line makes sense as it is copied from the `WC_Session_Handler`. With that in mind I had two questions and I don't think either require any changes, but wanted to get your opinion.

1. Do you think we should add any of the additional checks from `WC_Session_Handler::save_data`, namely the `$this->has_session()` check in the beginning and the delete session check if user IDs don't match?
2. Is there any need for some hardening in the case that some things are undefined or not as expected? I'm not sure how it exactly it might play out as I think we'd run into issues earlier (and bigger problems anyway), but in `init_session_from_token` we aren't doing any confirmation of the payload pieces existing or being in the right data format. This might fall outside the scope of this PR, but wanted to ask in a case where customer ID was not properly parsed and so could mess up the cache key to just be the prefix for example.

Neither issue is required in my opinion, but wanted to get your input on it as well. If you agree there isn't a concern relevant to this PR then I'll approve and we can merge!

**Comment by asumaran** [comment]
>Do you think we should add any of the additional checks from WC_Session_Handler::save_data, namely the $this->has_session() check in the beginning and the delete session check if user IDs don't match?

@bborman22 Initially, I considered that option; I had even added the code. However, I had to remove it since we didn’t have the `$old_session_key` data.​ We need to find a case where the session key changes from a "key" to "User ID" when using the Store API from WooPay.

>Is there any need for some hardening in the case that some things are undefined or not as expected? I'm not sure how it exactly it might play out as I think we'd run into issues earlier (and bigger problems anyway), but in init_session_from_token we aren't doing any confirmation of the payload pieces existing or being in the right data format. This might fall outside the scope of this PR, but wanted to ask in a case where customer ID was not properly parsed and so could mess up the cache key to just be the prefix for example.

I believe the session ID does change when the user logs in. Not sure if that's ever the case on the Store API with/without WooPay.

Besides that, we are using the Store API the way it's documented. What do you think exactly we should validate? We validate the Cart Token in `WooPay_Session::add_woopay_store_api_session_handler`.

https://github.com/Automattic/woocommerce-payments/blob/106db15e504912b1561da4139d900d8fba47d284/includes/woopay/class-woopay-session.php#L68

If we want to validate the token payload then I guess we could do that if we know exactly what to expect from the decoded payload. I don't see a filter in `JsonWebtoken` to include payload validation based on our own criteria.

**Review by bborman22 — APPROVED** [review]
> However, I had to remove it since we didn’t have the $old_session_key data.

Ah ok, that makes sense. 

> We validate the Cart Token in WooPay_Session::add_woopay_store_api_session_handler.

This was one piece I was missing, thanks!

**Pull request merged**
