### PR TITLE
 Remove unnecessary console.warn statements added in #9121

### PR DESCRIPTION
**Pull request by anu-rock**
#### Changes proposed in this Pull Request

We have seemingly unnecessary `console.warn` statements in a few Jest unit tests, probably added to debug issues caused by the Node 20 upgrade #9121.

If one or more of these warn statements are required, we can suppress linter warnings by putting an ignore comment in front of them like this:

```js
console.warn( error ); // eslint-disable-line no-console
```

For now, I have removed all of them as they did not seem to add value post the upgrade.

P.S. I noticed them in the linter-generated warnings in my PR:

image

#### Testing instructions

This is a harmful change, nothing really to test here.

* Code changes look good.
* All tests are passing.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (does not apply)
- [ ] Tested on mobile (does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9242` or branch name `fix/remove-console-warns` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/remove-console-warns) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 8d06df1768d48028857ce27249d0dee95ba603c1
- Build time: 2024-08-12 06:32:31 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by danielmx-dev — CHANGES_REQUESTED** [review]
I think it's fine to remove the `console.warn` statements but we can't remove the try/catch blocks since that will cause some tests to fail.  Example: https://github.com/Automattic/woocommerce-payments/actions/runs/10319750700/job/28568782950 

```
FAIL tests/e2e/specs/wcpay/merchant/merchant-payment-settings-manual-capture.spec.js (6.097 s)


  ● Test suite failed to run

    Cannot accept dialog which is already handled!

      137 | 	capturePageEventsForTearDown();
      138 | 	page.on( 'dialog', async function ( dialog ) {
    > 139 | 		await dialog.accept();
          | 		             ^
      140 | 	} );
      141 | 	setTestTimeouts();
      142 | 	await setupBrowser();
```

**Comment by anu-rock** [comment]
@danielmx-dev Interesting. Thanks for the feedback. For now, I have restored the try-catch blocks and triggered a [re-run of E2Es](https://github.com/Automattic/woocommerce-payments/actions/runs/10347001230).

But shouldn't we instead fix the root cause? FWIU, try-catch blocks are suppressing the errors caused by duplicate `dialog.accept()` calls - eg. it's called in the global `beforeAll` in tests/e2e/config/jest.setup.js and then again in individual test suites. Shouldn't we just remove the duplicate calls? Or is that tricky enough to be not worth doing?

**Comment by anu-rock** [comment]
> and triggered a [re-run of E2Es](https://github.com/Automattic/woocommerce-payments/actions/runs/10347001230)

**Update:** All previous failing tests are passing now.

**Review by danielmx-dev — APPROVED** [review]
Looks good!

**Comment by danielmx-dev** [comment]
> But shouldn't we instead fix the root cause? FWIU, try-catch blocks are suppressing the errors caused by duplicate `dialog.accept()` calls - eg. it's called in the global `beforeAll` in tests/e2e/config/jest.setup.js and then again in individual test suites. Shouldn't we just remove the duplicate calls? Or is that tricky enough to be not worth doing?

I think the tricky part comes from different WC versions having different logic on when to show the dialogs. We would need to debug every version separately and then add different assertions based on the versions. It'll probably require a lot of effort for something that has no effect on the end result of what we are actually testing.

**Comment by anu-rock** [comment]
> I think the tricky part comes from different WC versions having different logic on when to show the dialogs. We would need to debug every version separately and then add different assertions based on the versions. It'll probably require a lot of effort for something that has no effect on the end result of what we are actually testing.

Thanks for clearly explaining that. In that case, we'll let the try-catch blocks be as it's not worth doing all that extra work.

Thanks also for taking the time to review and approve my PR 🙌

**Pull request merged**
