### PR TITLE
Adds subscription invoice service

### PR DESCRIPTION
**Pull request by james-allan**
See pb0GrA-1g9-p2

#### Changes proposed in this Pull Request

This PR adds the subscription invoice service class that facilitates the generating of invoice item data, the processing of the first invoice on sign up and storing invoice IDs on subscriptions and orders. 

Because of the nature of this class as a pure service object, it isn't put to use until it's plugged into a subscription service object that will come in the following PRs.

#### Testing instructions

Because the functions in this class don't do anything on their own, there aren't steps to really test this yet. Having said that, I've added unit tests to test every function being introduced. 

-------------------

- [ ] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

### CODE REVIEW

**Comment by james-allan** [comment]
I'm going to self merge this given it's into a WIP branch. There are a few psalm errors however they all related to classes not existing because they haven't been copied over yet. 

Screen Shot 2021-08-20 at 3 32 55 pm

They will fix themselves once we introduce them in upcoming PRs.

**Comment by chickenn00dle** [comment]
Ah. I was actually in the process of looking into this one. But I'm happy to hold off on reviewing until the entire WIP branch is ready for review.

One thing I wanted to note was since we decided to change up how we are dealing with tax rates, there should no longer be a need for a tax rate service in the plugin itself. Instead, tax rate ids will be created and updated from the server, and corresponding rate ids should be stored directly on subscription/subscription item meta.

**Comment by james-allan** [comment]
Oh dang, sorry @chickenn00dle I didn't realise you were looking at it. 🤦‍♂️ Given the next PRs are all building off each other I didn't want this to be a bottleneck. 

> One thing I wanted to note was since we decided to change up how we are dealing with tax rates, there should no longer be a need for a tax rate service in the plugin itself.

Ah yeah, that's a good point. With that in mind, I'm assuming we can get rid of the tax rate ID handling from this class and just replace it with the raw tax data and let the server deal with it when dealing with invoice item requests similar to what you're doing with subscription?

**Comment by chickenn00dle** [comment]
> Oh dang, sorry @chickenn00dle I didn't realise you were looking at it. 🤦‍♂️ Given the next PRs are all building off each other I didn't want this to be a bottleneck.

No problem! I think it makes more sense to wait for the entire branch to be ready before reviewing anyway.

>  I'm assuming we can get rid of the tax rate ID handling from this class and just replace it with the raw tax data and let the server deal with it when dealing with invoice item requests similar to what you're doing with subscription?

That's a good question. I actually forgot about invoice items until I started looking at this PR 😓 

Initially, I was pretty focused on subscriptions and thought that once a subscription is created, tax rates would be stored on the subscription/items for later use with renewals. But I was forgetting that we create invoice items for new subscriptions as well! 

In any case, I don't think it will be a problem to do the same thing we are doing with subscriptions for the invoice service as well, although if possible it would be great to implement it such that only the subscription service has to worry about tax rate ids, and the invoice service can simply fetch these ids from subscription/item meta.

**Comment by chickenn00dle** [comment]
Just one more note, it might be best to just ignore taxes for invoice items for now while we work this out so this doesn't hold things up.

**Comment by chickenn00dle** [comment]
I did a bit of digging into this, and remembered the reason we are [creating invoice items prior to creating the subscription](https://github.com/Automattic/woocommerce-subscriptions-stripe-billing/blob/ca7fbe22d0bb5faaab031d51f5517594bf3f2bdf/includes/class-wcs-stripe-billing-subscription-service.php#L146-L159) was we were working on the prototype, so triggering the create subscription call would mark the payment complete right away. This meant if we created the invoice items afterward they wouldn't be added to the first invoice.

I think now that we are moving into WCPay and don't have to use any workaround code, this shouldn't be the case anymore, and we should be able to change the order. So:

**Create subscription** > **Store subscription/subscription_item/tax_rate ID meta** > **Create invoice items** > **Trigger payment complete**

If we do this, then in the invoice service, it should be possible to just always fetch tax rate ids from WC meta.  I hope this makes sense! Let me know if we need to clear anything up.

**Comment by chickenn00dle** [comment]
It looks like I was wrong about the above. Once the subscription is created, Stripe will create an invoice for it with a status of open, which is too late to add additional items. I've gone ahead and implemented the tax service logic for the invoice endpoint as well, so you can just pass the raw tax data as we do in subscriptions @james-allan.

I've also adjusted the endpoint so you can pass an array of invoice items so there is only one request to the server for this.

Sorry about the confusion 🙇 

Update to the endpoint details here: 1005-gh-Automattic/woocommerce-payments-server#issue-954552539

**Pull request merged**
