### PR TITLE
Update: remove asset blocking from E2E tests

### PR DESCRIPTION
**Pull request by deepakpathania**
#### Changes proposed in this Pull Request
- While debugging some flaky tests, I noticed that the asset blocking we introduced for CSS is leading to issues in certain scenarios. Since in CI, it isn't contributing that much to the overall performance either, have decided to remove it and the corresponding changes. 
- Not putting this behind a CI feature flag to keep the dev environment consistent for now, can consider that if any argument in favor of it is presented.

#### Testing instructions

* Config change so run the E2E workflow against this branch and notice the tests pass, [reference job](https://github.com/Automattic/woocommerce-payments/actions/runs/1696955130). 

-------------------

- [x] Added changelog entries to both `readme.txt` and `changelog.txt` (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) : QA Testing Not Applicable

### CODE REVIEW

**Review by htdat — COMMENTED** [review]
If I understand correctly, this PR is to remove changes added in two previous PRs https://github.com/Automattic/woocommerce-payments/pull/3623 and https://github.com/Automattic/woocommerce-payments/pull/3332

And this PR does that work. I would like to get more specific details on "why" below. 

> While debugging some flaky tests, I noticed that the asset blocking we introduced for CSS is leading to issues in certain scenarios. 

Can you provide more info for "issues in certain scenarios"? 

If possible, it's still worth finding a solution to suppress a lot of console logs such as `Failed to load resource: the server responded with a status of 404`. 

> Since in CI, it isn't contributing that much to the overall performance either, have decided to remove it and the corresponding changes.

This is based on your observation, or is there a reasoning behind?

**Comment by deepakpathania** [comment]
> Can you provide more info for "issues in certain scenarios"?

Yeah so the request interception was set to ignore assets like fonts, images etc and whitelisted certain patterns of stylesheets to be loaded. This whitelist wasn't exhaustive and was added based on what I found were important files to render the page properly based on observation.
In certain tests, not loading some of the stylesheets lead to timeouts for the selectors but not consistently which is why they were missed initially. It is tricky to maintain this whitelist to load since future changes can break it easily.

> This is based on your observation, or is there a reasoning behind?

CI runs tests in headless mode already in which the asset blocking doesn't provide any noticeable improvements, this was there to improve local dev experience while running tests in `dev` mode where not loading assets could improve overall time of the suite.

**Review by htdat — APPROVED** [review]
Thanks for the extra explanation. 🚢 it! 

> If possible, it's still worth finding a solution to suppress a lot of console logs such as Failed to load resource: the server responded with a status of 404.

I would recommend creating a GitHub issue to address this issue later.

For example, the latest E2E run here https://github.com/Automattic/woocommerce-payments/runs/4837760891?check_suite_focus=true is still showing 100 errors for `console.error`.
Markup on 2022-01-17 at 16:12:21

**Comment by deepakpathania** [comment]
Once the asset blocking changes are reverted, most of these errors should go away. Will see if it still remains to be an issue and open a ticket accordingly.

**Pull request merged**
