### PR TITLE
Add redirect to view Capital financing offers

### LINKED ISSUE #3655: View Capital financing offer redirect
### Description

Merchants should have access to a wp-admin page that automatically redirects them to the loan offer, after validating that they have the appropriate permissions.

### Acceptance criteria

* A new intermediate page should be created to redirect merchants to the loan offer page
* Only authenticated users should have access to it

### Designs

This page has no design since it's just a redirect. The designs for this flow can be checked in paJDYF-2Yf-p2.

### PR DESCRIPTION
**Pull request by luizreis**
Fixes #3655 

#### Changes proposed in this Pull Request

This PR prepares the changes from #3673 to be included on `develop`. This includes merging the original changes and adding them behind a feature flag.

**Question 1:** The Capital work won't be very extensive, so I decided to apply the feature flag directly where appropriate instead of pulling all changes to a specific class. Does that make sense, or should we extract Capital related code to a separate class before merging?

**Question 2:** Should we add a changelog and QA testing instructions in this case? We're shipping a feature to the client, but it won't be included/usable by default.

#### Testing instructions

_The redirect view has been tested as part of #3673, so a quick smoke test should suffice here._

* Before enabling the feature flag:
    * Navigate to `/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Foverview&wcpay-loan-offer-error=1` and assert that no error messages show up
    * Navigate to `/wp-admin/admin.php?wcpay-loan-offer` and assert you get a blank page
* Install 47-gh-Automattic/woocommerce-payments-dev-tools and enable Stripe Capital
    * Navigate to `/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Foverview&wcpay-loan-offer-error=1` and assert that the "There was a problem redirecting you to the loan offer..." error is displayed
    * Navigate to `/wp-admin/admin.php?wcpay-loan-offer` and assert that you're redirected to the loan details page (or, if using the platform account, to the overview page as the request will fail) 

-------------------

- [ ] Added changelog entries to both `readme.txt` and `changelog.txt` (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) : _Add link here / 'QA Testing Not Applicable'_

### CODE REVIEW

**Comment by tpaksu** [comment]
Hey, thanks for handling this issue, I'll try to give some answers to your questions: 

Q1: Capital work on the client side doesn't require much structured PHP code as you say, so we can keep the current code in their classes, no need to collect them into their own folder. 

Q2: you added the changelog after we removed the feature flag for multi-currency here, so we can do the same in this project. https://github.com/Automattic/woocommerce-payments/pull/2552

Hope it helps.

**Comment by luizreis** [comment]
Thanks @tpaksu! The answers do help 🙂 

> And the PR title seems odd, I guess you forgot to change it :)

It was intentional. We have nothing else on the `feature/stripe-capital` branch, besides the "Add redirect to view Capital financing offers" (and the feature flag) work. So, I thought it'd be fitting to merge it to develop with the same name to make clear what changes that are being included.

**Comment by tpaksu** [comment]
> So, I thought it'd be fitting to merge it to develop with the same name to make clear what changes that are being included.

Yep, that makes sense. Thanks for doing it.

**Review by tpaksu — APPROVED** [review]
Code looks good, tested and it works, thanks for taking care of the feature flag, 🚢  it!

**Pull request merged**
