### PR TITLE
Migrate Evidence component to TypeScript

### PR DESCRIPTION
**Pull request by reykjalin**
#### Changes proposed in this Pull Request

Migrates the evidence submission component (and associated data layers) to TypeScript following the work in #2757 .

#### Testing instructions

Same as in #2757; there should be no functional differences.

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply)

### CODE REVIEW

**Comment by kalessil** [comment]
Yay, more TS incoming :tada:

**Comment by reykjalin** [comment]
This PR is ready to review, but the tests have to be fixed; first they need to be fixed in #2757 where they started failing for some reason (https://github.com/Automattic/woocommerce-payments/pull/2757#discussion_r693259673), and then those updates need to be brought into this branch.

I also had to change the shape of the data store to make full use of the type system, and haven't had time to update the data store tests to match the new shape.

**Comment by vbelolapotkov** [comment]
Removing review label since the PR seem to be on hold

**Comment by reykjalin** [comment]
Too old to keep working on, so closing this.

**Pull request closed without merging**
