### PR TITLE
Fix WooPay opt-in blocks field

### LINKED ISSUE #9102: Fix WooPay opt-in layout
### Describe the bug
WooPay opt-in check box is too close to the add a note to order checkbox in the latest WooCommerce. Also the design does not fully match the figma ones 2JyXNimI4oGeJZhgQNZE9V-fi-1143%3A9115

### To Reproduce
- Install WooCommerce 9.1.2
- Add products to your cart
- Visit the blocks checkout page
- The WooPa opt-in checkbox will look like this:
Screenshot 2024-07-16 at 11 12 11

While it should look like this:
Screenshot 2024-07-16 at 11 16 09

### Additional context
Design Figma file:
2JyXNimI4oGeJZhgQNZE9V-fi-1143%3A9115

### PR DESCRIPTION
**Pull request by alefesouza**
Fixes #9102

#### Changes proposed in this Pull Request

Fix the WooPay opt-in blocks fields spacing issue when running on WooCommerce 9.1+.

Probably related to https://github.com/woocommerce/woocommerce/pull/47565.

#### Testing instructions

* Install WooCommerce 9.1.2.
* Add products to your cart.
* Visit the blocks checkout page.
* Type an email that is not registered to WooPay.
* The spacing should work as expected.

Screenshot 2024-07-18 at 2 48 37 PM

* Click the checkbox.
* Use the browser autofill to fill out the number.
* The text should be right positioned.

Screenshot 2024-07-18 at 2 49 51 PM

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9131` or branch name `fix/woopay-opt-in-blocks-field` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/woopay-opt-in-blocks-field) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 7df0452d12a78a1290f28d1bea944dfff2f66348
- Build time: 2024-07-23 03:38:29 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by leonardola — CHANGES_REQUESTED** [review]
The mobile view still looks a bit weird:

Screenshot 2024-07-19 at 11 35 01

I also noticed that the hr element should be below the opt-in checkbox not before according to the figma file:

Screenshot 2024-07-19 at 11 36 55

**Comment by pierorocca** [comment]
Could you also check please autofill of the phone number? Manual entry works as expected but autofill looks incorrect.

**Comment by alefesouza** [comment]
@leonardola fixed on https://github.com/Automattic/woocommerce-payments/pull/9131/commits/3480ce034e7315580f1f7fd0c9eef2f1dd2644b2

**Comment by alefesouza** [comment]
@pierorocca this PR addresses that too.

**Comment by pierorocca** [comment]
I thought so Alefe based on the field color. Thanks for confirming.

**Comment by pierorocca** [comment]
I thought so Alefe based on the field color. Thanks for confirming.

**Review by leonardola — CHANGES_REQUESTED** [review]
Mobile view now has two hr

Screenshot 2024-07-22 at 11 56 43

Desktop view does not have any

Screenshot 2024-07-22 at 11 57 05

**Comment by alefesouza** [comment]
@leonardola I think this is expected, one `hr` for each section on mobile and none for desktop, all other sections work like that. It's possible that other plugins add content below WooPay section so each section adds its own separator below.

**Comment by alefesouza** [comment]
@nikkivias could you confirm?

**Comment by pierorocca** [comment]
While we're waiting for design input, looking at the original Figma designs from the Blocks refresh work, "Save my info" looks clearly associated with the Payment Options section. When there's a section below, the hr is introduced. When there isn't an additional section, it doesn't look like an hr is added.

image

image

**Comment by pierorocca** [comment]
image

**Comment by alefesouza** [comment]
@pierorocca at least on WooCommerce 9.1, on mobile the hr is added on every section.

**Comment by pierorocca** [comment]
Gotch @alefesouza. Yeah definitely need design validation.

**Comment by nikivias** [comment]
Hi team, confirming that the line separator shows up per section on mobile. You will notice the same if your scroll higher and inspect other sections. Although I thought `Save my info` is meant to be part of Payment section?

**Comment by alefesouza** [comment]
@nikkivias got it, looking Leonardo's screenshots [here](https://github.com/Automattic/woocommerce-payments/pull/9131#pullrequestreview-2191828252), do you think any change is needed?

**Comment by nikivias** [comment]
Hi @pierorocca @alefesouza @leonardola and team

Coming in here with screenshots

I would say that `Save my info` needs to be more clearly associated with `Payment options`, but at the moment the Checkout blocks does not do visual "associations", so on mobile they will appear as separate because they are in fact, "separate blocks." This is why I've been pushing for subsections, but that's an issue for another day.

### Desktop

Add separator line above `Add a note...` (or below Save my info? not sure) to associate `Save my info` with Payments more

CleanShot 2024-07-23 at 10 12 49@2x

### Mobile

Keep as is.

CleanShot 2024-07-23 at 10 05 56@2x

**Comment by pierorocca** [comment]
I think the ideal state is possible @alefesouza since that's our WooPayments component correct?

**Comment by alefesouza** [comment]
@pierorocca yes, I've implemented it on the latest commit.

**Review by leonardola — APPROVED** [review]
Looks good to me

**Review by leonardola — APPROVED** [review]
Looks good to me

**Review by leonardola — APPROVED** [review]
Looks good to me

**Pull request merged**
