### PR TITLE
Update CSV export language codes to align with the languages supported by the server

### PR DESCRIPTION
**Pull request by mordeth**
#### Changes proposed in this Pull Request
At present, the default WordPress locale codes do not align with the supported languages on the server. This PR modifies the WordPress locale codes to match the supported languages. 

Additionally, it hides the CSV export modal if the language is not supported.

#### Testing instructions
*Case 1*
- Go to `Settings` -> `General`.
- Set the site language to `Spanish`.
- Go to `Payments` -> `Settings`.
- Scroll down to the Reporting section.
- Confirm that the export language selection box is displayed.

*Case 2*
- Go to `Settings` -> `General`.
- Set the site language to `Bulgarian`.
- Go to `Payments` -> `Settings`.
- Confirm that the Report section is not displayed.

*Case 3*
- Go to `Settings` -> `General`.
- Set the site language to `Spanish`.
- Go to `Payments` -> `Transactions`.
- Click the Download button on the top right corner of the table.
- A modal will be displayed prompting to select the download language.
- Uncheck the `Remember the language` settings checkbox.
- Select `Site language `-> `Spanish` and click download.
- Verify the `locale` param in the request is `es`.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8190` or branch name `fix/csv-export-localization-locale` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/csv-export-localization-locale) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: fd9d4f9f9d4bd4419f92dcf44c75b8864622353c
- Build time: 2024-02-14 10:01:10 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by allie500 — COMMENTED** [review]
Thanks for working on this quick fix. The code looks good. Test cases 1 and 2 passed for me. Test case 3 didn't fully pass for me. Locale query string param was `es`, but the CSV is not in Spanish.

**Comment by mordeth** [comment]
Thank you for the quick review!

The behavior you're experiencing is expected because the Spanish translation files are not present in your environment, they are only available in production.

I've made the necessary updates to the steps.

**Review by allie500 — APPROVED** [review]
Thanks for the update and the explanation. All three test cases are passing for me. 

LGTM :shipit:

**Review by elazzabi — APPROVED** [review]
Looks good!

**Review by dpaun1985 — APPROVED** [review]
✅  LGTM

**Pull request merged**
