### PR TITLE
Fixes Pay for Order page for non-card payment methods

### PR DESCRIPTION
**Pull request by FangedParakeet**
#### Changes proposed in this Pull Request

# Fixes Pay for Order page for non-card payment methods

In #8089, we attempted to prevent our gateway from intercepting other gateways when the order pay form is submitted. Unfortunately, this also prevented non-card payment methods from being used by our own plugin too. This PR provides a solution to this problem: instead of simply checking whether the `woocommerce_payments` gateway is selected (the card method), we check whether any WooPayments payment method is selected. 

#### Testing instructions

1. Create a new order and proceed to the Pay for Order page for the order.
2. Checkout for card and all non-card payment methods should succeed.
3. Install another payment gateway (e.g. Stripe) and ensure that this gateway also works on the Pay for Order page.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8111` or branch name `fix/order-pay-with-non-card-method` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/order-pay-with-non-card-method) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 04d3283d0624693fcd090bb58a40845cfedbed86
- Build time: 2024-02-06 08:16:24 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by frosso — APPROVED** [review]
thanks for the fix!

**Comment by allie500** [comment]
Thanks for this fix, @FangedParakeet! I tested it against the [Pay for Order](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#pay-for-order) critical flow and the tests all passed.

**Comment by FangedParakeet** [comment]
Failing E2E tests have been resolved in #8123, failing compatibility tests will be resolved in #8131: was initially hesitant to continue with merging this fix, but see no more purpose to postpone progress. Thanks all for helping to test out this PR! 🚀

**Pull request merged**
