### PR TITLE
Temporarily use WC 7.7 in the E2E tests wcpay-subscriptions tests matrix

### LINKED ISSUE #7451: Depencendies requirements & workflow issues
### Describe the bug

Last time we tried to bump the requirement for WC and WP, it ended up in a production incident with reports of null issues.
We're still stuck on min WC 7.6 and min WP 6.0.

We need to publish a P2 post to initiate a discussion and look at our options.

It also impacts some GitHub workflows like E2E tests or compatibility ones, that we should fix with temp workarounds if possible.

### PR DESCRIPTION
**Pull request by jbordonado**
Fixes #7451 

#### Changes proposed in this Pull Request

WCS 5.5 is not compatible with WC 7.6, the minimum WC it supports is 7.7

- As a quick fix, replace WC `7.6.0` by `7.7.0` for the `wcpay-subscriptions-tests` job in the E2E tests workflow

#### Testing instructions

* Trigger a run for the E2E tests based on this branch and confirm it no longer fails due to WC 7.6

Test run I triggered: https://github.com/Automattic/woocommerce-payments/actions/runs/6484728285

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7452` or branch name `fix/e2e-tests` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/e2e-tests) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 18ceb3f5113135860fe6f22f2009c031c4695c40
- Build time: 2023-10-11 15:40:56 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by achyuthajoy** [comment]
@jbordonado Changes look good to me.

1 test is failing `tests/e2e/specs/wcpay/merchant/merchant-orders-status-change.spec.js`, but not related to your change.

**Review by achyuthajoy — APPROVED** [review]
LGTM 🚢

**Comment by achyuthajoy** [comment]
@jbordonado The test started failing on a scheduled run, doesn't seem to be related to any PR. Ref - https://github.com/Automattic/woocommerce-payments/actions/runs/6476215665

Not sure if it's caused by a dependency change.

**Comment by jbordonado** [comment]
> https://github.com/Automattic/woocommerce-payments/actions/runs/6476215665

Some tests started to fail once WC 8.2 was released, indeed. We noticed it yesterday. The investigation is still ongoing. We thought to fix this first before fixing the rest.

**Pull request merged**
