### PR TITLE
Move test notice for transactions to the top

### LINKED ISSUE #7733: Update banner notice to use the new modern component
Per my conversation with @daquinons, attached is a collection of places across WooPayments where we currently display the older low contrast banner notification, specifically when a store is in test mode. We should update these to use our modern notice components.
- Payments Overview
- WooPayments Settings
- Deposits list
- Deposit details
- Transactions list
- Transaction details

### Designs
Existing on the left, new on the right.

**Payments Overview**
Payments Overview
- `Ready to go live?` link should click through to WooPayments Settings

**Deposits list**
Deposits

**Deposit details**
Deposit details
- Replace the banner notice with an inline notice and place it in the deposit details card.

**Transactions list**
Transactions

**Transaction details**
Transaction details
- Replace the banner notice with an inline notice and place it in the payment details card.

### PR DESCRIPTION
**Pull request by vladolaru**
Fixes #7733

#### Changes proposed in this Pull Request

- Moved the test mode notice out of the transactions tab to the top
- Removed the duplicate page wrapper.
- Minor styling fixes around spacing

| Before | After |
|--------|--------|
|Screenshot 2024-03-21 at 11 30 07|Screenshot 2024-03-21 at 11 27 42|

#### Testing instructions

* Checkout the PR branch on your local client installation
* Build the client assets by running `npm run build:client`
* Make sure that dev mode is activated
* Go to [the transactions page](http://localhost:8082/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Ftransactions) and the notice should appear at the top
* Disable dev mode and the notice should not show

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8430` or branch name `fix/7733-minor-test-mode-notice-adjustments-for-transactions` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/7733-minor-test-mode-notice-adjustments-for-transactions) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: adc243c9549b6147253976769b00e930854cf461
- Build time: 2024-03-22 12:02:40 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by elazzabi — APPROVED** [review]
This looks cleaner, code-wise and design-wise. Thank you for working on this!

Screenshot 2024-03-21 at 10 09 16

Tested locally and works fine!

**Review by anu-rock — APPROVED** [review]
I second @elazzabi's comment. This looks cleaner in both code and UI ❤️ 

___

#### Review checklist

| Parameter  | Result |
| ------------- | ------------- |
| Approach  | ✅ All good |
| Implementation  | ✅ All good |
| Automated tests  | ✅ Not applicable |
| Naming  | ✅ Not applicable |
| Typing  | ✅ Not applicable |
| Code comments  | ✅ Not applicable |
| Changelog  | ✅ All good |
| Testing instructions  | ✅ All good |
| Manual testing  | Skipped |

**Comment by vladolaru** [comment]
Thank you, @elazzabi and @anu-rock, for the review and show of appreciation! Making stuff better with every opportunity. 💪 

PS: Anurag, that PR review checklist is just something else. Next-level stuff 😄

**Comment by anu-rock** [comment]
> PS: Anurag, that PR review checklist is just something else. Next-level stuff 😄

It'll be more helpful for larger PRs when I have stuff to say 👿

**Pull request merged**
