### PR TITLE
Release branch for 5.9.0

### PR DESCRIPTION
**Pull request by botwoo**
:warning: Please do not merge the PR from the GitHub interface. :warning:

 Instead, you can use the following command:
```
 git checkout release/5.9.0 && git pull 
 git checkout trunk && git pull 
 git merge --no-ff release/5.9.0 -m 'Merge release/5.9.0 into trunk' 
 git push origin trunk 
``` 
 Changelog: 
```
* Add - Adds the minimal functionality for the new Stripe payment flow that allows deferred payment/setup intent creation. The functionality is hidden behind the feature flag.
* Add - Add support for 6 new countries in WCPay: Bulgaria, Croatia, and Romania
* Add - Add support for complete_kyc_link wcpay-link-handler
* Add - Disable the WooPay auto-redirect and SMS OTP modal in unsupported contexts.
* Add - Hide WooPay button in unsupported contexts
* Add - PO fields data and controls, behind a feature flag.
* Add - Support pending verification account status
* Fix - Add fraud prevention token to cart and checkout payment request buttons
* Fix - Check for the `AbstractCartRoute` class before making WooPay available.
* Fix - Fix AJAX response notice for multi-currency due to empty currencies data
* Fix - Fixed blocks currency switcher widget
* Fix - fixed php 8.1 wp-admin errors
* Fix - Handle WooPay requests using Store API cart token and Jetpack blog token.
* Fix - Minor change for i18n - Remove extra trailing space in translation string, outside of the __ tag.
* Fix - No longer display the Deposits card on the Payments Overview page for new merchants who don't have an estimated deposit
* Fix - Prevent express checkout buttons from displaying when payments are disabled.
* Fix - Prevent WooPay redirection when OTP frame is closed
* Fix - Remove WooPay subscriptions user check endpoint.
* Fix - Supply correct payment method instance to process_redirect_payment.
* Fix - Usage tracking props when placing WooPay orders
* Fix - Use timezone to check WooPay available countries
* Update - Change from convention Platform Checkout to WooPay consistently.
* Update - Handle incorrect address errors in terminal location API
* Update - Refactor express payment method button display
* Update - Show a link to the documentation in the tooltip when the pending balance is negative.
* Update - Update @woocommerce/experimental to v3.2.0
* Update - Update @wordpress/data-controls to v2.6.1
* Update - Update fraud and risk tools banner to match the latest design changes.
* Update - Update fraud and risk tools welcome tour copy.
* Update - Update the title on fraud risk metabox for flagged but approved orders.
* Update - WooPay specific admin area usage tracking
* Dev - Adds HTML coverage report for developer reference.
* Dev - Behind progressive onboarding feature flag – Add PO eligibility modal.
* Dev - Convert fraud protection settings related JavaScript files to TypeScript.
* Dev - covered by PR #6188
* Dev - Explicitly mention gridicons and @wordpress/primitives as dev dependencies.
* Dev - Remove pinned composer version 2.0.6 from workflows
* Dev - Run only pending timers to avoid recursive loop for AddPaymentMethodsTask tests.
* Dev - Update @woocommerce/currency to v 4.2.0
* Dev - Update @woocommerce/date to v4.2.0
* Dev - Update @woocommerce/explat to v2.3.0
* Dev - Update @wordpress/api-fetch to v6.3.1
* Dev - Update @wordpress/babel-plugin-makepot to v4.3.2
* Dev - Update @wordpress/base-styles to v4.3.1
* Dev - Update @wordpress/block-editor to v8.5.10
* Dev - Update @wordpress/blocks to v11.5.3
* Dev - Update @wordpress/data to v6.6.1
* Dev - Update @wordpress/date to v4.5.0
* Dev - Update @wordpress/element dependency to 4.4.1
* Dev - Update @wordpress/hooks to v3.6.1
* Dev - Update @wordpress/html-entities to v3.6.1
* Dev - Update @wordpress/i18n to v4.6.1
* Dev - Update @wordpress/icons to v8.2.3
* Dev - Update @wordpress/jest-preset-default to v8.1.2
* Dev - Update @wordpress/plugins to v.4.4.3
* Dev - Update @wordpress/scripts to v19.2.3
* Dev - Update @wordpress/url to v3.7.1
* Dev - Update react-dom dependency to 17.0.2
* Dev - Update react dev dependency to 17.0.2
* Dev - Update version detection API for subscriptions-core
* Dev - Update `@wordpress/dom-ready` to v3.6.1
* Dev - Usage tracking for deposits admin UI.
```

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6292` or branch name `release/5.9.0` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=release/5.9.0) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 8a050009d15d5e15c4d3e2c4cfb23deeebc3aa6e
- Build time: 2023-05-16 20:40:21 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by mattallan** [comment]
@shendy-a8c FYI: I've cherry-picked https://github.com/Automattic/woocommerce-payments/pull/6210 into this release branch

**Comment by shendy-a8c** [comment]
Quite a lot of things to be included in this release branch the didn't make it to the code freeze, so I'm going to list them out here:

- `subscriptions-core` version update. +cc @mattallan 
Slack: p1684111395926799-slack-CGGCLBN58.
PR: https://github.com/Automattic/woocommerce-payments/pull/6292.
Cherry-pick commit: https://github.com/Automattic/woocommerce-payments/pull/6292/commits/130fe427b7809d725cbf794426e63a2855d44fbe.

- @malithsen's PRs.
@malithsen DM'd me about 2 PRs he wanted to include in this release:
https://github.com/Automattic/woocommerce-payments/pull/6175 (commit made it to this branch https://github.com/Automattic/woocommerce-payments/pull/6292/commits/137a781fe12538c3c6f1e4fac72d76633659234c) and https://github.com/Automattic/woocommerce-payments/pull/6265 (commit made it to this branch https://github.com/Automattic/woocommerce-payments/pull/6292/commits/8d3db0c01026f6a09fcb9da8a5e6b5be15a2e0be). Both made it before code freeze, so I didn't have to cherry-pick.

- @malithsen's fix to an error when updating plugin.
Slack: p1684148049557989-slack-CGGCLBN58.
PR: https://github.com/Automattic/woocommerce-payments/pull/6303.
Cherry-pick commit: https://github.com/Automattic/woocommerce-payments/pull/6292/commits/85d8791ed9e2cad6c14b1ce791e9258a7e7d134b.

- @Automattic/helix's deposit project.
PR: https://github.com/Automattic/woocommerce-payments/pull/6268 (cherry-pick commit  https://github.com/Automattic/woocommerce-payments/pull/6292/commits/18f553b23dfbf4fec31d7837b295ed8622112697).
PR: https://github.com/Automattic/woocommerce-payments/pull/6280 (cherry-pick commit  https://github.com/Automattic/woocommerce-payments/pull/6292/commits/d18c821655d6227f8dcc98e99b28c486444fc02b).
PR: https://github.com/Automattic/woocommerce-payments/pull/6252 (cherry-pick commit  https://github.com/Automattic/woocommerce-payments/pull/6292/commits/93df79069a881d00acf1c336c3eb2541f1e8fa95).

- @Automattic/sigma's PRs.
Slack: p1684137546651329-slack-CGGCLBN58.
PR: https://github.com/Automattic/woocommerce-payments/pull/6275 (cherry-pick commit https://github.com/Automattic/woocommerce-payments/pull/6292/commits/9bec48534af08a97cafa2c21f46347a04e654474).
PR: https://github.com/Automattic/woocommerce-payments/pull/6299 (cherry-pick commit https://github.com/Automattic/woocommerce-payments/pull/6292/commits/27ec4d6629102b367ed126f6f9b89a05b0b94c13).
PR: https://github.com/Automattic/woocommerce-payments/pull/6302 (cherry-pick commit https://github.com/Automattic/woocommerce-payments/pull/6292/commits/de25f524bd6692e5d14b47449dc7d3ca0cc46a5f).

**Comment by shendy-a8c** [comment]
Removed some changelog entries https://github.com/Automattic/woocommerce-payments/pull/6292/commits/8a050009d15d5e15c4d3e2c4cfb23deeebc3aa6e per this Slack message p1684217670390829/1684137546.651329-slack-CGGCLBN58.

+cc @dwainm

**Review by shendy-a8c — APPROVED** [review]

**Review by shendy-a8c — APPROVED** [review]

**Pull request merged**
