### PR TITLE
Fix: Changed the word from cancelation to cancellation

### LINKED ISSUE #6550: Resolve usage of "cancelation" vs "cancellation"
### Describe the bug

`cancelation` and `cancellation` are both used within WCPay. We should be consistent in our spelling.

Using one `l` is preferred for `cancel`, `canceling`, and `canceled`. While `cancelation` isn't necessarily incorrect, `cancellation` is more commonly used.

### Examples

https://github.com/Automattic/woocommerce-payments/blob/9dc0b955669368916fd1d847266b71a4618b1133/client/disputes/strings.ts#L273

https://github.com/Automattic/woocommerce-payments/blob/9dc0b955669368916fd1d847266b71a4618b1133/client/disputes/strings.ts#L300

### See also
- https://www.dictionary.com/e/canceled-vs-cancelled/
- https://en.wiktionary.org/wiki/cancelation#:~:text=the%20word%20cancellation%20is%20still%20much%20more%20widely
- https://www.merriam-webster.com/dictionary/cancellation

### PR DESCRIPTION
**Pull request by vishalpawarR**
Fixes #6550

#### Changes proposed in this Pull Request
Changed the word from cancelation to cancellation

### CODE REVIEW

**Comment by brucealdridge** [comment]
Thank you for working on this @vishalpawarR.
Are you able to add a changelog entry for this? This can be done by running `npm run changelog`

**Comment by vishalpawarR** [comment]
@brucealdridge Hey I ran the command I dont see any changes but I am getting this error can you help me in it?
```
npm run changelog

> woocommerce-payments@6.0.0 changelog
> ./vendor/bin/changelogger add

'.' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by brucealdridge** [comment]
> Hey I ran the command I dont see any changes but I am getting this error can you help me in it?

It looks like composer dependencies are missing. Have you run `npm install`? This should run `composer install` as part of the script.

**Comment by vishalpawarR** [comment]
I am facing issue in the camposer
```
woocommerce-payments@6.0.0 postinstall
> composer install

'composer' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code 1
npm ERR! path C:\Users\Vishal Pawar\Documents\GitHub\woocommerce-payments
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c composer install
```

**Comment by leonardola** [comment]
Closing in favor of #7354

**Pull request closed without merging**
