### PR TITLE
Make MC Settings screen to use a 2 column layout

### LINKED ISSUE #2745: Update settings UI to match WCpay settings
Update the MC settings page to use the same layout/style/functionality as the new 2 column payments grouped settings page.

### PR DESCRIPTION
**Pull request by daquinons**
Fixes #2745 

#### Changes proposed in this Pull Request

Make MC Settings screen to use a 2 column layout

MC settings need to match the new design of the WC Payments settings screen, using the same 2 column layour.

In order to do that, I've moved some parts of the MC Settings screen rendered by PHP to React. The titles and descriptions are all now in React. The Store Settings section checkboxes are still rendered by PHP but position accordingly inside of the SettingsSection for achieving the desired layout. 

Before:

image

After:

image

#### Testing instructions

* Go to Payments - Settings - Multi-currency
* See new design
* See that the settings are still functional

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply)

### CODE REVIEW

**Review by dmallory42 — APPROVED** [review]
LGTM, works well upon testing and code looks good. Nice work @daquinons! 🚀 

I'm approving this, but I think we should also ask @LevinMedia for a design review before we 🚢 .

**Comment by daquinons** [comment]
> LGTM, works well upon testing and code looks good. Nice work @daquinons! 🚀
> 
> I'm approving this, but I think we should also ask @LevinMedia for a design review before we 🚢 .

Thank you @dmallory42! Yes please, let me know if this is what it's supposed to look like @LevinMedia 😸

**Review by jessepearson — DISMISSED** [review]
Hey @daquinons, I believe this is a good start in getting the changes applied. I believe what @LevinMedia is looking for is the same exact design and styling that exists for the screen under Payments > Settings with the grouped settings enabled, for example: 

Markup 2021-09-02 at 13 31 24

I believe in order to do this, we may need to borrow/reuse some of the components from that page to use for the _Store settings_ section. I think the two main things that we're going to need to get into this is the additional open whitespace on either side of the settings, and then the white boxes to hold the actual settings. Hopefully the Enabled Currencies table will fit nicely in there without being crammed.

**Comment by daquinons** [comment]
> Hey @daquinons, I believe this is a good start in getting the changes applied. I believe what @LevinMedia is looking for is the same exact design and styling that exists for the screen under Payments > Settings with the grouped settings enabled, for example:
> 
> Markup 2021-09-02 at 13 31 24
> 
> I believe in order to do this, we may need to borrow/reuse some of the components from that page to use for the _Store settings_ section. I think the two main things that we're going to need to get into this is the additional open whitespace on either side of the settings, and then the white boxes to hold the actual settings. Hopefully the Enabled Currencies table will fit nicely in there without being crammed.

Thank you @jessepearson! I've updated it to match everything

Screenshot 2021-09-02 at 19 25 15

**Comment by daquinons** [comment]
Probably that table need some adjustment

**Comment by LevinMedia** [comment]
@daquinons this is a great start - I'm sorry the link to the p2 post with the designs didn't make it into the issue, but you still got really close with out it. There's a few things I'd like to update before we merge this. 

here's a like to the p2 paJDYF-1gf-p2 it includes links to the figma files for closer inspection. I'll add some screen shots for reference here as well:

Main settings screen: 

Screen Shot 2021-09-02 at 8 32 18 PM

The content wrapper for the columns should have a max width of 1032 pixels. That makes the right column 680, and the left column 328px, with a 24 px gutter. 

The settings in the store settings section should be wrapped in a card, and the style of the contents (checkboxes, text styles, padding etc) should match the styles in the design linked above (which should also match what's in the new WCpay settings as well.)  

The content on the edit currency pages should use the same styles as well: 

Screen Shot 2021-09-02 at 8 39 02 PM

**Comment by daquinons** [comment]
> @daquinons this is a great start - I'm sorry the link to the p2 post with the designs didn't make it into the issue, but you still got really close with out it. There's a few things I'd like to update before we merge this.
> 
> here's a like to the p2 paJDYF-1gf-p2 it includes links to the figma files for closer inspection. I'll add some screen shots for reference here as well:
> 
> Main settings screen:
> 
> Screen Shot 2021-09-02 at 8 32 18 PM
> 
> The content wrapper for the columns should have a max width of 1032 pixels. That makes the right column 680, and the left column 328px, with a 24 px gutter.
> 
> The settings in the store settings section should be wrapped in a card, and the style of the contents (checkboxes, text styles, padding etc) should match the styles in the design linked above (which should also match what's in the new WCpay settings as well.)
> 
> The content on the edit currency pages should use the same styles as well:
> 
> Screen Shot 2021-09-02 at 8 39 02 PM

Thank you! I've added what was missing.

We also talked about redefining the scope of this issue here, take a look p1630659640146600-slack-C01B8KNUYSW

**Comment by LevinMedia** [comment]
@daquinons I pulled down the latest updates from your branch - I've got just a little more feedback on the settings in the card at the bottom. 

There should be 8px of space between the checkbox and the helper text 12px of margin between the two settings. The last child element of the container should have 0px bottom margin, and just rely in the card container padding. 

Screen Shot 2021-09-03 at 1 39 19 PM

**Comment by daquinons** [comment]
> @daquinons I pulled down the latest updates from your branch - I've got just a little more feedback on the settings in the card at the bottom.
> 
> There should be 8px of space between the checkbox and the helper text 12px of margin between the two settings. The last child element of the container should have 0px bottom margin, and just rely in the card container padding.
> 
> Screen Shot 2021-09-03 at 1 39 19 PM

Oops, thanks for your eyes! 👀 Fixed

image

**Comment by daquinons** [comment]
It's being impossible to get the four E2E tests in the same run, posting proof that they passed at least in different runs

image

image

**Pull request merged**
