### PR TITLE
SEPA: remove declaration of subscriptions support

### LINKED ISSUE #3776: `invalid_request_error` breaks subscription renewals using SEPA payment method
### Describe the bug
We've had a report from a merchant via customer support that subscriptions (recurring) payments are failing with SEPA payment method. Thanks @jrodger @felipelousantos cc @madisoncmiller 

Store is using WooCommerce Subscriptions extension with WCPay.

Here's an example request (details removed) and error message:

```
**Request** 400 ERR | POST | /v1/payment_intents
**Request body** 
{
  "amount": "xxxx",
  "currency": "eur",
  "confirm": "true",
  "payment_method": "pm_1234",
  "customer": "cus_2345",
  "capture_method": "automatic",
  "metadata": {
    "customer_name": "Xx Yyyy",
    "customer_email": "a@b.com",
    "site_url": "https://____.com",
    "order_id": "1234",
    "order_key": "wc_order_4567",
    "payment_type": "recurring"
  },
  "description": "------",
  "payment_method_types": {
    "0": "card"
  },
  "off_session": "true",
  "expand": {
    "0": "charges.data.balance_transaction"
  },
  "application_fee_amount": "123"
}

**Error response** invalid_request_error
The PaymentMethod provided (sepa_debit) is not allowed for this PaymentIntent. Please attach a PaymentMethod of one of the following types: card. Alternatively, update the allowed payment_method_types for this PaymentIntent to include "sepa_debit".
```

Linking in some Stripe docs relating to SEPA:

- https://stripe.com/docs/payments/sepa-debit/accept-a-payment
- https://stripe.com/docs/sources/sepa-debit

Internal reference: p1643974407798379-slack-C02BW3Z8SHK p1643785082212209-slack-C7U3Y3VMY

### To Reproduce
I don't have reproduce details and haven't tried reproducing as I'm unfamiliar with SEPA and don't know how to test it locally.

Next step would be for someone familiar with SEPA to reproduce this issue to find out if it's unique to this store or more common.

I imagine the steps are something like:

1. Enable and onboard to WCPay.
2. Activate WooCommerce Subscriptions and create a subscription product.
3. Activate / enable SEPA (via UPE?).
4. Purchase a subscription as a customer. 
5. Wait for renewal or trigger early renewal.
6. Renewal fails with error.

### PR DESCRIPTION
**Pull request by kalessil**
Fixes #3776

#### Changes proposed in this Pull Request

- Remove subscriptions support declaration for SEPA payment method.
- Note the saved token will reveal, and we keep the underlying SEPA+subs integrations which need more work. Hence our changes are kinda cosmetic.

#### Testing instructions

* Enable SEPA in WooCommerce Payments settings
* Create a subscription product
* Add a subscription to cart and proceed to checkout
* Ensure SEPA is NOT available as payment method there
* Clear cart, add a regular product in there and proceed to checkout
* Ensure SEPA is available there
* Complete the purchase and ensure transaction details are available

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6062` or branch name `update/3776-disable-sepa-for-subscriptions` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=update/3776-disable-sepa-for-subscriptions) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 02f9ab6f3de6729f2fa2fc7a3dbd46e56cc1e2ff
- Build time: 2023-04-18 13:48:06 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by frosso — APPROVED** [review]
👍

**Comment by kalessil** [comment]
Blocked until further clarifications: p1682497734908719/1681492078.610059-slack-C02C00HCJ8J

**Comment by kalessil** [comment]
Closing this PR: Hopefully, the root cause for failing renewals will be addressed in https://github.com/Automattic/woocommerce-payments/pull/6965.

**Pull request closed without merging**
