### PR TITLE
Add progressive onboarding mode choice

### LINKED ISSUE #5480: Handle Merchant/Builder Choice and alternate builder flow
### Description

We need to handle in the UI having both a merchant and a builder path, with an option to onboard in dev mode if the user is a builder. This issue will cover the frontend work to create this flow as per the designs. The merchant flow would be handled by #5473, so this would cover any changes required for the builder flow.

### Acceptance Criteria

* The builder flow UX matches the designs (link to follow).

### PR DESCRIPTION
**Pull request by ismaeldcom**
Fixes #5480 

#### Changes proposed in this Pull Request
- Add required icon as JSX components to allow color adjustment through CSS.
- Implement reusable component `TipBox` with `purple` and `blue` colors.
  - Not needed anymore, but I'll leave it there as it might be required soon.
- Implement reusable component `RadioCard`.
- Add missing color variables to `_variables.scss`.
- Add `ModeChoice` step matching design requirements.
- Update `WC_Payments_Onboarding_Service` to hook into `wcpay_dev_mode` and enable it based on the new option `wcpay_onboarding_test_mode`.
- Enable onboarding test mode in `init_stripe_onboarding` based on `$_GET['test_mode']`.

To let merchants onboard and use a test account we need to enable `dev_mode`. Right now we offer them the option to do it using `WCPAY_DEV_MODE` constant. To allow it to be enabled while onboarding I've chosen to add a new option, and filter `dev_mode` based on it.

#### Testing instructions
- Ensure you're not connected to an account (for example, you can mark it as deleted in the DB)
- Ensure `Dev mode enabled` is unchecked and `Enable Progressive Onboarding` is checked in `WCPay Dev` plugin.
- Go to **Payments** and click on **Get started**
- The live option should be selected and clicking on **Continue** should move to the next step (personal details form).
- Refresh, choose the test option and click on **Continue**.
- You should be redirected to Stripe full KYC in test mode, complete it.
- After being redirected back, the site should have a fully functional test account onboarded.

#### Images
| Live | Test|
|-|-|
|Screenshot 2023-03-31 at 11 53 11|Screenshot 2023-03-31 at 11 53 25|

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [x] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [x] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `5842` or branch name `add/5480-test-payments-choice` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=add/5480-test-payments-choice) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 6635449c17fc48318ef4c7257b7c802024ee90c5
- Build time: 2023-04-03 07:29:02 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by daquinons** [comment]
👀 @elizaan36 just in case you want to take a look

**Comment by kellychoffman** [comment]
@elizaan36 - i didn't see a design on the corresponding issue, so commenting here that think this needs another design pass
- right aligned radio inputs? what about right aligning the icons instead
- icons below input label are confusing - are they adding anything? 
- the list of 3 things below the title, including the info notice are all variations of the same sentence. can we combine these smartly?
- hierarchy is off and info is super dense in general. let's simplify

**Comment by elizaan36** [comment]
@kellychoffman Thanks for these notes, will take another pass at the design. And I'll share the full prototype/Figma with you in Slack.

**Review by oaratovskyi — APPROVED** [review]
Thanks for wrangling it @ismaeldcom ! Looks amazing to me, approving!

One small question: 
image
Can this radio button circle size be customized? (I guess not)

And a suggestion to change the second heading as a scope of this PR from `What would you like to do?` to `Select the option that best fits your needs.` as in design. But it can be done in the #4744 too!

🚢 🚢 🚢

**Comment by elizaan36** [comment]
Nice @ismaeldcom 🙏

Where does the "our test data" link go to? I'm wary of linking people out of the flow.

Also "set up" is two words for both options.

**Comment by ismaeldcom** [comment]
> And a suggestion to change the second heading as a scope of this PR from What would you like to do? to Select the option that best fits your needs. as in design

Totally, I was just looking at the cards and forgot about the step headings 🙂 I'll address it after clarifying the question from @elizaan36.

>Where does the "our test data" link go to? I'm wary of linking people out of the flow.

To [this documentation page](https://woocommerce.com/document/woocommerce-payments/testing-and-troubleshooting/dev-mode/), it was used before, and I thought you forgot it with the update. It has some useful information about the test data. But thinking on your concern maybe it's better to remove it. Let me know what you prefer 🙂 

>Also "set up" is two words for both options.

Nice catch! I always copy & paste them to avoid any issue, I probably missed this one.

>Can this radio button circle size be customized?

Yep we can customize it, in fact I scaled it a bit to make it closer to the proposed design, without manually adjusting every size property. But the inner circle looks smaller on mobile (smaller screens) on purpose by WP. So I’m not sure if we should make that additional change.

We can leave it as it is, move back to default WP design or fully match our proposed one. @elizaan36 what do you think about this?

For comparison those are the different variations:

| Original (bigger screen) | Original (smaller screen) | Modified (bigger screen only) | Design |
|-|-|-|-|
|Screenshot 2023-03-31 at 13 03 13|Screenshot 2023-03-31 at 12 59 43|Screenshot 2023-03-31 at 12 59 25|Screenshot 2023-03-31 at 13 02 35|

**Comment by elizaan36** [comment]
> But thinking on your concern maybe it's better to remove it. Let me know what you prefer

I think it's ok to remove the link. I don't think the doc will provide enough value if it could potentially distract people from setup.

> fully match our proposed one. @elizaan36 what do you think about this?

For the radio selection, if we could match the design that would be ideal. I know the core profiler work will also customize this component to increase the size of the inner circle so would be good to align there.

**Comment by ismaeldcom** [comment]
Thanks for your input, addressed both the copy and input radio style.

Screenshot 2023-04-03 at 09 23 07

**Pull request merged**
