### PR TITLE
Normalize HK addresses for Apple Pay

### LINKED ISSUE #9123: Hong Kong addresses always fail validation via Apple Pay
**Describe the bug**

Apple Pay currently sends us an address in a format we don't expect; the Hong Kong Region (e.g. "New Territories") is put into the postalCode property of the paymentRequest object, instead of the region like we would expect.

This makes it so that when you try to pay via Apple Pay with a Hong Kong address the payment always fails with a very cryptic error message.

This means customers are unable to pay merchants through Apple Pay when using a Hong Kong address.

__FYI_: This was an issue that was also present in WC Stripe but they managed to fix it/close it: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1630

This was also discussed [in a Slack thread internally](https://a8c.slack.com/archives/CU6SYV31A/p1721236582584489?thread_ts=1721236162.125269&cid=CU6SYV31A) (access only available to Automattic agents) before creating the report here._

**To Reproduce**

Reproduction and testing steps available in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1593

**Expected behavior**

Address validation succeeds for valid addresses and payments can be processed.

### PR DESCRIPTION
**Pull request by asumaran**
Fixes https://github.com/Automattic/woocommerce-payments/issues/9123

#### Changes proposed in this Pull Request.

This PR is a port of the WC Stripe implementation for the same issue. Please refer to the [PR](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1593) on their repo for more information.

Basically, the changes introduced are as follows:

>Instead of using the billing_state or shipping_state to normalize the region for a Hong Kong address, we instead use the billing_postcode and shipping_postcode which seem to contain the equivalent for Hong Kong addresses.

#### Testing instructions

1. Add the following address to your Apple Pay shipping options:
    - Country: `Hong Kong`
    - Region: `New Territories`
    - District: `Taipo`
    - Address: `9 Feng Yuen Road`
2. `git checkout develop`.
3. Add any product to your cart.
4. Attempt to checkout via Apple Pay using the address you just entered as a billing address and/or shipping address.
5. Notice that you are unable to checkout and no WooCommerce order is created.
6. `git checkout as-hk-address`
7. Try checking out via Apple Pay using the Hong Kong address.
8. Notice that you can now check out successfully.

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by asumaran** [comment]
@reykjalin, do you think we should include a reference to the original source code? If yes, where do you think it would be most appropriate?

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9869` or branch name `as-hk-address` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=as-hk-address) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 91b19e09093f3ddf57e4c6462a0280008a05635e
- Build time: 2024-12-06 19:06:56 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by reykjalin** [comment]
> do you think we should include a reference to the original source code? If yes, where do you think it would be most appropriate?

Hmm, I don't really think we need it, but maybe a comment in the code would be nice just to help keep things in-sync? Maybe just at the top of the HK states file?

I wrote the array by hand based on information in the PDF linked here:

https://github.com/Automattic/woocommerce-payments/blob/4db7fd039ca5b6a53d626142bd2448bd40bb34bd/includes/constants/class-express-checkout-hong-kong-states.php#L26

So there isn't really on official source for the information in code; it's all based on a PDF from the HK government.

**Review by bborman22 — APPROVED** [review]
I was able to test this successfully. I confirmed the issue happening on `develop` and confirmed I was able to successfully checkout on this branch. I tested against 6 different addresses to cover the three regions in Hong Kong, all successfully. I also tested against the blocks and shortcode carts and checkout pages also successfully. 

From a code perspective the changes look good and have already been reviewed and used in the Stripe plugin. It seemed all failure states are handled properly and input is sanitized. 

In testing I only ran into two problems that are unrelated to this PR, but wanted to mention to see if they are worth addressing:
1. At first I entered Hong Kong Island as the region and it was rejected, I then confirmed that it's not common to use that as the region name and instead to just use Hong Kong. Only thing I'd note is that WC core uses Hong Kong as the region key, but Hong Kong Island as the display text, so might be worth just adding Hong Kong Island to the list?
2. I was unable to complete a checkout using the Mandarin spellings as WC's validation checked against only the English keys. I'm not sure though if this is just due to my store settings?

Neither issue is a blocker and this code looks good and tests well!

**Comment by asumaran** [comment]
>might be worth just adding Hong Kong Island to the list?

@bborman22 I've added "hong kong island" to the region/states array [1e26e09](https://github.com/Automattic/woocommerce-payments/pull/9869/commits/1e26e098927825b4ff240fac92b90362634dc4a0). 

>I was unable to complete a checkout using the Mandarin spellings as WC's validation checked against only the English keys. I'm not sure though if this is just due to my store settings?

Do we officially support Chinese characters? Either way, I’m merging this PR, and we can revisit it if any reports come up.

**Pull request merged**
