### PR TITLE
Fix - HPOS compatibility on Edit Order Screen

### LINKED ISSUE #7466: Order status not reverted to the original status on HPOS-enabled stores using WC 8.2
### Describe the bug

WC 8.2 was released, and HPOS is enabled by default for new installations (see the [blog post](https://developer.woocommerce.com/2023/10/10/woocommerce-8-2-0-released/)).

As a result, two tests in the E2E suite stopped working, and it turns out it is a real bug.
When you try to update an order status with `Cancelled` but decide to "do nothing", the order status doesn't show the initial status, instead, it stays empty.
Same problem when you try to change to `Refunded` but decide to "cancel"

See the E2E test failures logs for reference: https://github.com/Automattic/woocommerce-payments/actions/runs/6491026598/job/17627695841

⚠️ Unskip the E2E tests in https://github.com/Automattic/woocommerce-payments/blob/develop/tests/e2e/specs/wcpay/merchant/merchant-orders-status-change.spec.js once the fix is implemented to confirm the tests pass again

### To Reproduce

1. Ensure your store has HPOS feature enabled (see in WooCommerce > Settings > Advanced > Features)
2. Make a new order
3. Edit that order ( WooCommerce > Orders and select it)
4. Select the `Cancelled` status and click on "Do Nothing"
5. The order status is empty instead of showing the initial status (`Processing` or `Completed)

Same steps but choosing `Refunded` and clicking on `cancel` for the second bug

### Actual behavior
Order status is not reverted to the original status when you select "Do Nothing" in the confirmation popup

### Screenshots

- `Cancelled` status bug

https://github.com/Automattic/woocommerce-payments/assets/28830738/78180e8f-bd34-4459-abab-8c0b569b4986

- `Refunded` status bug

https://github.com/Automattic/woocommerce-payments/assets/28830738/c51fe971-352a-40da-b454-c48562ded0fe

### Expected behavior
Order status is reverted to the original status when you select "Do Nothing" in the confirmation popup

### Additional context
- WC 8.2
- HPOS-enabled store (see in WooCommerce > Settings > Advanced > Features)

The code saving the original status can be found here: https://github.com/Automattic/woocommerce-payments/blob/c8ad2ae03fe557dabae7e89cde2124cd919fb5eb/client/order/index.js#L59

On HPOS-enabled stores, there is no hidden input field with ID `original_post_status`. But there is one with ID `original_order_status`

### PR DESCRIPTION
**Pull request by jessy-p**
Fixes #7466

#### Changes proposed in this Pull Request

When HPOS is enabled, the order status should be fetched from `#original_order_status` and not `#original_post_status`. 
- Modified the code to work with both HPOS and POSTS.
- Added a workaround for core issue https://github.com/woocommerce/woocommerce/issues/40871
Ref: p1697706516222469-slack-C0E1AV8T0

#### Testing instructions

- Enable HPOS
- On Order Edit screen, change the Order Status in the dropdown to Cancelled or Refunded
- In the modal, click on "Do Nothing" ( on the Cancel Modal) or "Cancelled" (on the Refund Modal)
- Verify that the original status is set back correctly in the dropdown. 

(Without the fix in this branch, the dropdown is not set correctly when user cancels the action)

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7527` or branch name `7466/fix-hpos-compat-order-edit` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=7466/fix-hpos-compat-order-edit) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 1ea5a20e37e052f404d2f46fae795d16aafb7fe9
- Build time: 2023-10-24 13:03:34 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by naman03malhotra — COMMENTED** [review]
@jessy-p in case when I press cancel on the Modal, it does set it to cancelled on the current develop branch. However when I press do nothing, it set it to blank. Can you please check once?
https://github.com/Automattic/woocommerce-payments/assets/15019298/4c7a7dda-08b2-4af0-9adc-d82a9dba9aa0

**Comment by naman03malhotra** [comment]
https://github.com/Automattic/woocommerce-payments/assets/15019298/a2b0fd7d-3c26-4867-8f51-7dba9a10c7bc

**Review by naman03malhotra — APPROVED** [review]
LGTM! tests well 🚢

**Pull request merged**
