### PR TITLE
Revert deposit schedule tooltip refactor commit - accidentally pushed to `develop`

### PR DESCRIPTION
**Pull request by haszari**
This reverts commit 518ced4666cf83496db7ca8e794c45334eee3f55.

Was pushed to `develop` accidentally when splitting work-in-progress branche for #8026 and #8260

Fixes #

#### Testing instructions

*

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8262` or branch name `revert/commit-518ced4666cf83496db7ca8e794c45334eee3f55` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=revert/commit-518ced4666cf83496db7ca8e794c45334eee3f55) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 1e95e80450022efd07efa14f2f642b03d39e507c
- Build time: 2024-02-23 00:39:02 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by haszari — COMMENTED** [review]
Merging with no / my own review. 

Low risk as is a pure revert of last commit on `develop` 518ced4666cf83496db7ca8e794c45334eee3f55

**Comment by haszari** [comment]
Skipping PR, I'm going to revert the PR direct on `develop`. The PR won't auto merge without a review (and maybe passing checks?). 

I'm prioritising getting `develop` back into a good state and I'm responsible for any issues (I'm not anticipating problems).

**Comment by haszari** [comment]
Reverted in this commit: 1e95e80450022efd07efa14f2f642b03d39e507c

**Pull request closed without merging**
