### PR TITLE
Revert Symfony polyfills

### PR DESCRIPTION
**Pull request by jrodger**
Reverts PR #3475 to restore PHP 7.0 compatibility

#### Details

* Reverts #3475
* Some conflicts were handled, most notably we no longer have one of the affected files thanks to https://github.com/Automattic/woocommerce-payments/pull/3586
* The changes in `phpcs-compat.xml.dist` don't seem completely related. Should we be reverting that as well or not?

#### Testing instructions
* Review changes against the original PR
* Smoke test the plugin on a couple of PHP versions (7.0 and something else)

-------------------

- [x] Added changelog entries to both `readme.txt` and `changelog.txt` (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

**Review by htdat — APPROVED** [review]
The revert looks good.

I manually tested with a PHP 7.0 Jurassic site with these flows: 

- Onboarding.
- Checkout with traditional way (only cards) and UPE.
- Checkout with a card to create disputes.
- Multi-currency activation.
- Admin screens: Overview, Transactions, Deposits, Disputes, and settings.

**Review by kalessil — APPROVED** [review]
LGTM!

**Comment by kalessil** [comment]
@htdat : IIUC, we'll re-revert this once PHP 7.0 support is dropped and the change will be back.

**Comment by jrodger** [comment]
There was a mistake in the revert of `composer.json`. I've re-applied the changes by manually removing the polyfill packages with Composer. This also ensures that the lock file is in a sensible state.

**Comment by haszari** [comment]
Tagging in @mattallan to review this on behalf of Helix - to ensure subscriptions is not impacted by the revert (`subscriptions-core` dependency).

**Comment by mattallan** [comment]
> to ensure subscriptions is not impacted by the revert (subscriptions-core dependency).

1.6.2 is the latest version of subscriptions-core and it doesn't look like this revert changes that, so this is all good from a WCPay + Subscriptions perspective :100:

**Review by ricardo — APPROVED** [review]
I was asked to give this another look too.

Changes LGTM.

Smoke tested checkout, transactions search, admin pages and multi-currency with PHP 7.0, 7.4 and 8.0 on Docker. Everything seems to work as expected.

However, on PHP 8.1, I see a deprecation warning on package `myclabs/php-enum`.

> Deprecated: Return type of MyCLabs\Enum\Enum::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in [file] on [line].

I also see a couple warnings on the latest version of WooCommerce, so I understand we're probably not there yet. I tried updating `myclabs/php-enum` to the latest version, but it didn't fix the notice.

I think this is out of the scope for this PR, so approving 👍.

Can someone else double-check the notice problem on their environment with PHP 8.1? Then I can open an issue.

Thanks for the fix @jrodger. Also props to @htdat for fixing the dev utils plugin for PHP 7.0 in the meanwhile. 46-gh-Automattic/woocommerce-payments-dev-tools 👏

**Pull request merged**
