### PR TITLE
Fix Jetpack Sync config

### LINKED ISSUE #9151: Fix Jetpack Sync configuration
### Description

As discussed here (pfKYZu-vc-p2#comment-404), our current, limited, Jetpack Sync is too limited and doesn't include the necessary modules for full WooCommerce syncing.

We need to add the missing modules.

### PR DESCRIPTION
**Pull request by vladolaru**
Fixes #9151

#### Changes proposed in this Pull Request

We add the `Automattic\Jetpack\Sync\Modules\Posts` and `Automattic\Jetpack\Sync\Modules\Meta` Jetpack Sync modules when activating the sync.

#### Testing instructions

* The code changes make sense.
* On your local WooPayments installation, checkout the PR branch.
* Make sure you don't have Jetpack-the-plugin activated.
* Install and activate the [Jetpack Debug Helper](https://github.com/Automattic/jetpack-debug-helper) plugin on our local WooPayments installation and enable the `Sync Debug Utilities` and `Sync Data Settings Utility`.
* Go to WooCommerce > Settings > Advanced > WooCommerce.com and enable WooCommerce usage tracking.
* There should be no errors as you navigate the WP dashboard.
* Go to Jetpack Debug > Sync Data Settings Tester and you should see the following list of modules:

* Go to WooCommerce > Settings > Advanced > WooCommerce.com and disable WooCommerce usage tracking.
* Go to Jetpack Debug > Sync Data Settings Tester and you should see the following list of modules (no WooCommerce module):

* Activate Jetpack and activate the Sync feature. Make sure there are no errors as you navigate the WP admin.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9152` or branch name `fix/9151-jeptack-sync-config` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/9151-jeptack-sync-config) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 85882a8aff9fb4f4b0bb5268a38c47a1fc783a7e
- Build time: 2024-07-24 10:02:28 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by elazzabi — APPROVED** [review]
Looks good. Tested locally and I can confirm `WooCommerce` doesn't show after disabling the tracking.

Just to double check. `Posts` and `Meta` are still showing even after disabling the tracking. That's expected?

**Comment by vladolaru** [comment]
Thank you for reviewing, @elazzabi!

> Just to double check. Posts and Meta are still showing even after disabling the tracking. That's expected?

If you don't have Jetpack-the-plugin activated or other Woo extensions, `Posts` and `Meta` should NOT be there, as in my second screenshot. Could you check your local env state?

**Comment by elazzabi** [comment]
If I deactivate Jetpack, I get the same list as yours (second screenshot)

**Comment by vladolaru** [comment]
> If I deactivate Jetpack, I get the same list as yours (second screenshot)

Good. That is the expected behavior. Jetpack uses the default set of modules, that is why you see `Post` and `Meta`. I will update the testing instructions.

**Review by fgiannar — CHANGES_REQUESTED** [review]
Thanks for working on this,

I was able to reproduce a bug with this configuration, present since WCPay `7.4.0` where the `WooCommerce_HPOS_Orders` and `WooCommerce` modules are loaded twice and resulting in HPOS orders not being synced.

I'm still testing atm and will suggest an alternate configuration asap.

**Comment by vladolaru** [comment]
@fgiannar I've [applied your changes](https://github.com/Automattic/woocommerce-payments/pull/9152/commits/85882a8aff9fb4f4b0bb5268a38c47a1fc783a7e) proposed in p9dueE-8kC-p2

**Review by fgiannar — APPROVED** [review]
LGTM 👍

**Pull request merged**
