### PR TITLE
Load subscriptions-core via composer and remove the "includes/subscriptions/subscriptions-base" directory

### LINKED ISSUE #2958: Remove `includes/subscriptions/subscriptions-base` and load it via composer
### Description

Once `includes/subscriptions/subscriptions-base` is moved out to a new public repo, we'll need to remove the entire `subscriptions-base` folder (currently found on the `feature/stripe_billing` branch) and load it into WC Payments via composer.json. Something like:

```
"repositories": [
    {
        "type": "git",
        "url": "https://github.com/Automattic/woocommerce-subscriptions-core.git"
    }
],
"require": {
    "woocommerce/subscriptions-core": "1.0.0",
},
```

As part of this change, we'll also need to update the [`WCPAY_SUBSCRIPTIONS_ABSPATH` definition set in `woocommerce-payments.php`](https://github.com/Automattic/woocommerce-payments/blob/30057b76a6d83bbfab8f7b8cc16a6d9392d42eca/woocommerce-payments.php#L24) to load subscriptions from `vendor/woocommerce/subscriptions-core`

### PR DESCRIPTION
**Pull request by mattallan**
Fixes #2958 

#### Changes proposed in this Pull Request

Now that Subscriptions Core has been moved to it's own repository](https://github.com/Automattic/woocommerce-subscriptions-core), we no longer need to include `subscriptions-base` inside woocommerce-payments and instead, can load subscriptions-core via composer.

The changes in this PR are pretty straight forward:
 - Update `composer.json` to include the subscriptions-core repo
 - Rename `wcpay_init_subscriptions_base()` to `wcpay_init_subscriptions_core()` and update references to base
 - Update `WCPAY_SUBSCRIPTIONS_ABSPATH` to locate subscriptions from `vendor/`

#### Testing instructions

- Deactivate WooCommerce Subscriptions extension
- run `composer update` to pull subscriptions-core
- Check subscriptions functionality is loaded
  1. Check **WooCommerce > Subscriptions** is there
  2. Check **WooCommerce > Settings > Subscriptions** has limited settings (mixed checkout and syncing)
- Activate WooCommerce Subscriptions and confirm all the premium extension settings are being loaded

### CODE REVIEW

**Comment by mattallan** [comment]
Some compatibility checks are failing with error "The PHPUnit Polyfills library is a requirement for running the WP test suite.". I think these can be ignored and should be fixed in https://github.com/Automattic/woocommerce-payments/pull/2945

**Comment by aprea** [comment]
I see the following on `composer update`:

```
Loading composer repositories with package information
GitHub API limit (0 calls/hr) is exhausted, could not fetch https://api.github.com/repos/automattic/woocommerce-subscriptions-core. Create a GitHub OAuth token to go over the API rate limit. You can also wait until ? for the rate limit to reset.

Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+Chriss-MBP-2+2021-09-23+0358
to retrieve a token. It will be stored in "/Users/chrisaprea/.composer/auth.json" for future use by Composer.
```

Just wanted to check if this is expected?

**Comment by haszari** [comment]
> `Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+Chriss-MBP-2+2021-09-23+0358
to retrieve a token. It will be stored in "/Users/chrisaprea/.composer/auth.json"`

> Just wanted to check if this is expected?

Good question! If we have any additional requirements on dev machines for setup/update we should document them in the readme.

**Review by aprea — APPROVED** [review]
LGTM :shipit:

**Comment by mattallan** [comment]
Thanks @aprea for looking over this!

> I see the following on composer update:

Hmm interesting! I didn't get this error but I'm guessing that's because I already had an auth token stored?

Definitely would be good to document this as I'm assuming this will come up again for whoever tries to deploy this code.
To fix this, did you follow the link and then copy the token and paste it into your console, and then it continued after that?

**Comment by mattallan** [comment]
> If we have any additional requirements on dev machines for setup/update we should document them in the readme.

Added with 08941a1.

Thanks for the review all 😄 Merging since this has been approved and I only changed a small secant of the readme.md

**Comment by haszari** [comment]
@mattallan Do we need to update any scripts to automatically include subs core library? If so, can you log an issue for this - thanks (cc @chickenn00dle).

I just tried doing a release build (`npm run build`). I needed to run `composer update` manually; if not, the release build fails with fatal error when subs-core is not present. (Note this was with feature flag enabled, e.g. `wp option set _wcpay_feature_subscriptions 1`.) Related, perhaps we should protect against the fatal with a try/catch.

**Comment by mattallan** [comment]
@haszari I believe @shendy-a8c is all over this 😄 
There's an open a PR which pushes up the updated composer lock file so that subscriptions core library is properly installed when running `composer install`: https://github.com/Automattic/woocommerce-payments/pull/3001

`composer install` is ran during `npm run build` so that should fix the issues you're seeing.

>  perhaps we should protect against the fatal with a try/catch.

yeah this is also a nice fallback to have in place.

**Pull request merged**
