### PR TITLE
Dev: Fix merchant disputes save draft E2E tests

### LINKED ISSUE #9281: Disputes > Merchant can save and resume draft dispute challenge E2E test failure
### Description

**Before reporting an issue, are you sure this e2e test is failing consistently?**
Yes, this e2e test failed 4 times consistently with the same error while creating the 8.1.0 release branch

**Issue**
`Disputes > Merchant can save and resume draft dispute challenge` fails with the error `Element [data-testid="dispute-challenge-product-type-selector"] (text: "Offline service") not found`

**Output from the test failure**:
```
FAIL tests/e2e/specs/wcpay/merchant/merchant-disputes-save-draft-challenge.spec.js (43.931 s)
  Disputes > Merchant can save and resume draft dispute challenge
    ✕ should be able to save a draft dispute challenge and resume (13525 ms)

  ● Disputes > Merchant can save and resume draft dispute challenge › should be able to save a draft dispute challenge and resume

    TimeoutError: Element [data-testid="dispute-challenge-product-type-selector"] (text: "Offline service") not found
    Waiting failed: 3000ms exceeded

      114 |
      115 | 		// Verify the previously selected Product type was saved
    > 116 | 		await expect( page ).toMatchElement(
          | 		^
      117 | 			'[data-testid="dispute-challenge-product-type-selector"]',
      118 | 			{
      119 | 				text: 'Offline service',

      at tests/e2e/specs/wcpay/merchant/merchant-disputes-save-draft-challenge.spec.js:116:3
```

### Additional context
https://github.com/Automattic/woocommerce-payments/actions/runs/10440457389/job/28938598192

### Priority
low
Looks like E2E test are flaky on all previous release

### Reason why this e2e test is broken
e2e: broken test

> [!Important]
> Please, ensure when closing this issue (PR fix) that only one `e2e: broken` label is added and it is accurate.
> - [x] I confirmed there's only one `e2e: broken` label in this issue and it is accurate.

### PR DESCRIPTION
**Pull request by danielmx-dev**
Fixes https://github.com/Automattic/woocommerce-payments/issues/9281

#### Changes proposed in this Pull Request
 
After #9109 was merged, the following E2E test started to [fail consistently:](https://github.com/Automattic/woocommerce-payments/actions/runs/10423228918) 

```
Disputes > Merchant can save and resume draft dispute challenge > should be able to save a draft dispute challenge and resume
```

After some debugging, I found out that the changes in the PR didn't modify any of the behavior tested, but affected the load times of the page (given that the change forces the account cache to be refreshed every time an admin page related to WCPay is accessed).

I found that this change fixes the race condition that caused the test to fail.

Additionally, I also added more messages to be suppressed to clean up the tests output to the console.

#### Testing instructions

* You can manually run the E2E tests for this branch on https://github.com/Automattic/woocommerce-payments/actions/workflows/e2e-test.yml or locally by following the instructions in `tests/e2e/README.md`

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply) N/A

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : N/A
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable: N/A
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable: N/A

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9275` or branch name `dev/fix-merchant-disputes-save-draft-e2e-tests` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=dev/fix-merchant-disputes-save-draft-e2e-tests) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 022acafe3dad6804770d1362b07884a5d4638ea0
- Build time: 2024-08-19 13:38:15 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by danielmx-dev** [comment]
Successful run using these changes. https://github.com/Automattic/woocommerce-payments/actions/runs/10425477395/job/28876458915

**Review by timur27 — APPROVED** [review]
Thanks for fixing this! 💪 🥇  I saw your fix together with https://github.com/Automattic/woocommerce-payments/pull/9284 which solves the same problem. https://github.com/Automattic/woocommerce-payments/pull/9284 might run a little bit slower, but it includes additional page navigation, which contributes to improved robustness I believe. It's up to you and @Jinksi to decide which one you'd prefer to eventually merge.

**Comment by danielmx-dev** [comment]
Closing this, we should go with the solution from #9284

**Pull request closed without merging**
