### PR TITLE
Update multi currency settings UX

### LINKED ISSUE #2335: UX Updates for Edit Currency Settings
There are a few UX changes required for the edit currency settings page originally mentioned by @LevinMedia in https://github.com/Automattic/woocommerce-payments/issues/2280#issuecomment-870986954:

> For zero-decimal currencies, I'm wondering whether we should even allow None as an option for price rounding?

> @dmallory42 @luizreis after giving this a test, I agree that we should make 1 the minimum rounding option for non-decimal currencies. Also where we're showing the preview of a non decimal currency, we shouldn't show the decimal - for example, with yen - this should simply read 1700

Screen Shot 2021-06-29 at 4 30 43 PM

> I also noticed when testing this that decimal currencies are defaulting to no rounding, rather than to 1.00 - could we please update that to match this screen shot too?

Screen Shot 2021-06-29 at 4 35 42 PM

### PR DESCRIPTION
**Pull request by luizreis**
Fixes #2335

#### Changes proposed in this Pull Request

- Remove none and add 1 to zero-decimal rounding options
- Fix decimal currency rounding defaulting to none instead of 1
- Do not render decimals for zero-decimal currencies preview

#### Testing instructions

*Decimal currency*

* Add a new decimal currency
* Open its settings and check that the preview has decimal places
* Check that the default rounding option is 1.00

*Zero-decimal currency*

* Open the currency settings for a zero-decimal currency
* Check that the minimum rounding option is 1
* Check that the preview doesn't have any decimal places

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

**Comment by LevinMedia** [comment]
hey @luizreis looking good!

A few small details: the conversion preview is missing the thousands separator. More specifically, I think it should use the local currencies format, (currency position, thousand and decimal separators) since it's representing what the customer will see on the site, formatted for their locale. 

Also, I added Euros as a currency, and it didn't default to 1.00 for rounding, but I think this might be because I'd added it before and fiddled with the settings. Can you check to make sure that when you remove, then re-add a currency that is resets to the defaults? 

Screen Shot 2021-07-01 at 12 34 25 PM


Last little thing, even though the preview currency is in the admin -

**Comment by jessepearson** [comment]
> Also, I added Euros as a currency, and it didn't default to 1.00 for rounding, but I think this might be because I'd added it before and fiddled with the settings. Can you check to make sure that when you remove, then re-add a currency that is resets to the defaults?

@LevinMedia @luizreis Just wanted to note this is a double edged sword due to if we remove the settings for a currency once it is no longer enabled, the merchant may assume that the settings will automatically return once enabled again. For instance, if they accidentally remove a currency by unchecking the box when adding new currencies, then see the currency is missing from the list, then they add it again.

**Comment by luizreis** [comment]
@LevinMedia - good catch! I created #2375 and #2376 to track those two issues.

**Review by dmallory42 — APPROVED** [review]
LGTM and works as expected. :shipit:

**Pull request merged**
