### PR TITLE
Gracefully handle missing payment method constants

### PR DESCRIPTION
**Pull request by dmvrtx**
#### Changes proposed in this Pull Request

 - Fix the payment method lookup error when a payment method constant goes missing. There is a graceful handling for the case when payment method class is not present, but if constant is not defined, but stored in payment settings, the following error would occur on the website.

```
Fatal error: Uncaught InvalidArgumentException: Constant with value '...' does not exist. in /var/www/html/wp-content/plugins/woocommerce-payments/includes/constants/class-base-constant.php on line 79 InvalidArgumentException: Constant with value 'affirm' does not exist. in /var/www/html/wp-content/plugins/woocommerce-payments/includes/constants/class-base-constant.php on line 79 Call Stack: 0.0007 366064 1. {main}() /var/www/html/wp-admin/admin.php:0 0.2818 17792264 2. require_once('/var/www/html/wp-admin/admin-header.php') /var/www/html/wp-admin/admin.php:239 0.3389 19224360 3. do_action() /var/www/html/wp-admin/admin-header.php:163 0.3389 19224736 4. WP_Hook->do_action() /var/www/html/wp-includes/plugin.php:517 0.3389 19224736 5. WP_Hook->apply_filters() /var/www/html/wp-includes/class-wp-hook.php:332 0.3390 19225112 6. WCPay\MultiCurrency\PaymentMethodsCompatibility->add_payment_method_currency_dependencies_script() /var/www/html/wp-includes/class-wp-hook.php:308 0.3390 19225112 7. WCPay\MultiCurrency\PaymentMethodsCompatibility->get_enabled_payment_method_currencies() /var/www/html/wp-content/plugins/woocommerce-payments/includes/multi-currency/PaymentMethodsCompatibility.php:138 0.3390 19225528 8. array_reduce() /var/www/html/wp-content/plugins/woocommerce-payments/includes/multi-currency/PaymentMethodsCompatibility.php:84 0.3390 19225528 9. WCPay\MultiCurrency\PaymentMethodsCompatibility->WCPay\MultiCurrency\{closure:/var/www/html/wp-content/plugins/woocommerce-payments/includes/multi-currency/PaymentMethodsCompatibility.php:65-83}() /var/www/html/wp-content/plugins/woocommerce-payments/includes/multi-currency/PaymentMethodsCompatibility.php:84 0.3390 19225528 10. WCPay\Constants\Base_Constant::search() /var/www/html/wp-content/plugins/woocommerce-payments/includes/multi-currency/PaymentMethodsCompatibility.php:69
 instructions.
```

Providing a graceful fallback here would improve resilience of merchant's sites.
#### Testing instructions

* To trigger an error the easiest way is to rename one of the constants in the `Payment_Method` class. Preferrably, of the payment method already enabled on the test site.
  * Without the patch, an aforementioned error will occur.
  * With the patch, payment method will be excluded from available payment method and site will operate without errors.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `5991` or branch name `tweak/gracefully-handle-missing-payment-method-constant` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=tweak/gracefully-handle-missing-payment-method-constant) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: aa626e0ac38105b241afe5def51c8bccfb158b99
- Build time: 2023-06-15 12:02:36 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by mgascam — COMMENTED** [review]
Code looks good. I intend to do some manual testing later today before giving my final approval.

**Comment by kalessil** [comment]
@dmvrtx, while the changes look harmless, I'd like to learn more about the original context. How this exception surface originally?

**Comment by dmvrtx** [comment]
@kalessil It appeared when I was switching between development branches while testing new payment methods and eventually impeded any work on branches where new payment methods were not present.

**Comment by kalessil** [comment]
@dmvrtx , gotcha!

It looks like your changes are also covering the preceding if-statement:
```php
if ( in_array( $method, [ 'card', 'card_present' ], true ) ) {
    return $result;
}
```

Can you check if it can be dropped and add an explaining comment why making our changes, please?

**Comment by dmvrtx** [comment]
> Can you check if it can be dropped and add an explaining comment why making our changes, please?

`card` and `card_present` are valid constant values, so the mentioned check is required for something else and my changes have no effect on this flow.

**Review by mgascam — APPROVED** [review]
LGTM! I was able to reproduce the issue in `develop` and confirmed that this change fixes it.

**Review by kalessil — APPROVED** [review]
LGTM!

**Pull request merged**
