### PR TITLE
correct case of `Id` for Transaction ID column label in transactions list screen

### LINKED ISSUE #9910: Change `Transaction Id` to `Transaction ID` for consistency
The column heading within `Payments > Transactions` reads as `Transaction Id`. We consistently spell ID with all-caps at various places in our UI.  For consistency, `Transaction Id` should be changed to `Transaction ID` 

### To Reproduce

1. Browse to `Payments > Transactions` 
2. Click the ellipsis menu at the top right of the report table. 
3. You will see a hidden column - `Transaction Id` 

5. If you enable the column, the header will read as `Transaction Id` too

### PR DESCRIPTION
**Pull request by nagpai**
Fixes #9910 

#### Changes proposed in this Pull Request

Change column name `Transaction Id` to `Transaction ID` for consistency with how unique ID's are labelled across the UI. 

#### Testing instructions

1. Browse to Payments > Transactions
2. Click the ellipsis menu at the top right of the report table.
3. You should see `Transaction ID` instead of `Transaction Id` . Toggle that control on 

4. In the report you should now see an additional column - `Transaction ID`

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9911` or branch name `update/9910-transaction-id-label` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=update/9910-transaction-id-label) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 9faeba4a4541e863db0baa44031502afd3747589
- Build time: 2024-12-12 21:29:42 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by jessy-p — COMMENTED** [review]
Looks good. But on my screen, it wrapped like this, is that OK?
It wasn't doing that before.

image

**Before**:
image

Do we need to increase the size of that modal a bit?

**Comment by nagpai** [comment]
>Looks good. But on my screen, it wrapped like this, is that OK?
It wasn't doing that before.

@jessy-p  - IIRC there is an issue logged at the core component level. It gets clipped currently. It may be related to that. The capitalized `ID` may be crossing the width threshold for warping to a new line. I will give this a closer look though.

Update- I checked and it does not seem to be doing on my browser 🤔 . Can you share an output from whatismybrowser.com ? Also if you can check if there is any browser zoom enabled? Thanks

**Comment by nagpai** [comment]
Adding Helix back as a reviewer for some more reviews to see if the warping mentioned by @jessy-p  is visible elsewhere. 

If it exists with other reviewers, It will be worth checking if the issue gets resolved by https://github.com/woocommerce/woocommerce/pull/53066

**Review by haszari — APPROVED** [review]
Code changes are zero risk and awesome, `ID` is definitely the right spelling 😁 

Tested and I did not see any new wrapping - looks just as good as before:

Screenshot 2024-12-13 at 10 24 27 AM

The positioning and size of the menu is not ideal (as before):

- Menu is clipped by edge of browser
- Some items wrap

But that's a totally different issue! 

- https://github.com/Automattic/woocommerce-payments/issues/9870

**Pull request merged**
