### PR TITLE
Use paragraph selector instead of label for pmme appearance

### LINKED ISSUE #9803: PMME text color should not be using the label color
### Describe the bug
In #9621 we fixed the Apparence API not being correctly applied to the PMME, however, we are using the label color as text color for this element. Because the Blocks Checkout uses floating labels, this color might not look good. We should update it to use the text color of a paragraph.

Image

### To Reproduce

1. Use a dark theme, or use CSS to update your background color to a dark color and the text color to a light color.
2. **Do not enable** Blocks Checkout dark mode.
3. Go to the blocks checkout and see the PMME does not look good.

### Additional context
p1731716238180769-slack-CU6SYV31A

### PR DESCRIPTION
**Pull request by gpressutto5**
Fixes #9803

#### Changes proposed in this Pull Request

We were using the Label text styles for the `.Text` class for in Stripe Appearance API. This works well in the shortcode checkout because they have similar styles, but the Blocks checkout uses floating labels, so their style is very different from paragraph text.
This PR updates the selector for all location, however it is noticeable only in the blocks checkout.

| Before | After |
|--------|--------|
| image | image |

#### Testing instructions

1. Comment [these lines](https://github.com/Automattic/woocommerce-payments/blob/447eb9b446e7583928d1d6fa23c4403d5221d757/includes/class-wc-payments-checkout.php#L227-L233) to prevent the appearance object from caching
1. Use a dark theme, or use CSS to update your background color to a dark color and the text color to a light color.
1. Do not enable Blocks Checkout dark mode.
1. Go to the blocks checkout and see the PMME does not look good in `develop`, but it looks good in this branch.
2. Ensure no other place the pmme is displayed is broken:
	- Shortcode checkout
	- Shortcode cart
	- Blocks cart
	- Product page

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9840` or branch name `fix-pmme-appearance-blocks` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix-pmme-appearance-blocks) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: eec857dbcedfa4e1d7c60ed371c8455fdf2c80f8
- Build time: 2024-11-28 15:06:08 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by gpressutto5** [comment]
@pierorocca, Could you please take a look to see if it looks better now?
This PR aims to fix the color issue and, possibly as a side effect, items 2-6 from [this comment](https://github.com/Automattic/woocommerce-payments/pull/9805#issuecomment-2499168177).
It **does not** aim to style the text **differently** than a paragraph. This will be done in #9818.

**Comment by danielmx-dev** [comment]
@gpressutto5 Can you please share which theme you are using and which customizations (colors, additional CSS) are set? I'm having some issues replicating the behavior locally.

**Comment by gpressutto5** [comment]
@danielmx-dev I'm using Storefront with this additional css:

```css
* {
	background-color: #4342da;
	color: white;
}

a {
		color: white !important;
}
```

**Comment by danielmx-dev** [comment]
> @danielmx-dev I'm using Storefront with this additional css:

Thanks, the only thing that I was missing was clearing the transients between branch changes. I'm able to replicate the issue now.

**Review by danielmx-dev — APPROVED** [review]
Works as expected !

**Comment by pierorocca** [comment]
Colors looks good. Is the font sizing being addressed in the other PRs?

**Comment by gpressutto5** [comment]
@pierorocca Yes, because #9818 aims to set a custom size for this text there's no need to understand what is causing the size inconsistencies from [this comment](https://github.com/Automattic/woocommerce-payments/pull/9805#issuecomment-2499168177) here.

**Pull request merged**
