### PR TITLE
Add Tracks to Place Order button

### PR DESCRIPTION
**Pull request by malithsen**
#### Changes proposed in this Pull Request

Record Tracks event when clicking the Place Order button when using WooPayments.

#### Testing instructions

1. Add a product to the cart.
2. Go to the classic checkout page.
3. Make sure WooPayments is selected in Payment Methods
4. Click on the Place Order button
5. In ~5 minutes, check MC live view for a `wcpay_checkout_place_order_button_click` event from your site.
6. Select a different gateway (Stripe, Check Payments"
7. Click on the Place Order Button
8. No event should be recorded.
9. Repeat the above steps with Blocks checkout.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7854` or branch name `add/place-order-tracks` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=add/place-order-tracks) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: a6dc3d784f1f2f5ec7741dcee0bfacc6d903c9a0
- Build time: 2024-01-03 17:29:46 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by hsingyuc — APPROVED** [review]
@malithsen Thank you for working on this!  I see the event logged when placing the order with WooPayments on both Blocks and shortcode checkout, and the code makes sense to me.

I want to note that `wcpay_checkout_place_order_button_click` logged twice each time.

Screen Shot 2023-12-21 at 1 28 58 PM

But the function is only triggered once in the merchant, so maybe that's something wrong with tracks.

**Comment by malithsen** [comment]
> I want to note that wcpay_checkout_place_order_button_click logged twice each time.

Ah good catch. Looks like the form is submitted twice when placing the order. Fixed with https://github.com/Automattic/woocommerce-payments/pull/7854/commits/52ba858e339f3f86ef3a1cd31048c5576aa12292

**Review by hsingyuc — APPROVED** [review]
Tested few more times.  Both classic and blocks checkout getting only one event logged.

**Pull request merged**
