### PR TITLE
Add footer elements to the new deposits overview card

### LINKED ISSUE #5719: Simplify deposits UI - Add Deposit card footer actions (button / link)
### Description

This issue is part of the larger Epic to add the Payments Overview Deposits card (https://github.com/Automattic/woocommerce-payments/issues/5686).

As part of this issue, the card should altered to include the following acceptance criteria: 

### Acceptance criteria 

* "**View full deposit history**" button
* **"Change deposit scheduled"** link

image

### Designs

P2: paJDYF-7fi-p2

image

### Additional context

Project: pdjTHR-2i5-p2

### PR DESCRIPTION
**Pull request by james-allan**
Fixes #5719 

#### Changes proposed in this Pull Request

This PR adds the footer which contains the button (links to deposits list table), and a link to the deposit schedule settings. 

Screenshot 2023-03-24 at 11 26 09 am

> **Note**
> This PR doesn't include any JS tests because there's currently no test stubs set up for this card. This will be done as part of https://github.com/Automattic/woocommerce-payments/pull/5799 or a follow up PR. These elements don't have any complex states or logic that needs specific testing.

#### Testing instructions

1. Set `wcpay_feature_simplify_deposits_ui` to `1` in the wp-options table
2. From WP Admin go to Payments to view the Overview page
3. Check the Next deposits card contains a footer and the button and link send you to the correct locations.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `5849` or branch name `issue/5719-add-deposit-card-footer` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=issue/5719-add-deposit-card-footer) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 44542b75cc4b6146e31eef74d5d9eed2f47fe770
- Build time: 2023-03-26 23:12:55 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by shendy-a8c** [comment]
> **Note**
> This PR doesn't include any JS tests because there's currently no test stubs set up for this card. This will be done as part of https://github.com/Automattic/woocommerce-payments/pull/5799 or a follow up PR. These elements don't have any complex states or logic that needs specific testing.

I don't see `client/components/deposits-overview/test` yet in base branch. Maybe it makes sense to add the test in a separate PR when all to-be-implemented UIs have been added.

What do you think?

**Review by shendy-a8c — APPROVED** [review]
Changes look good. I can see the 'View full deposits history' button and 'Change deposit schedule' link. They are functional.

Other than my comment about test and resolving conflicts, this PR looks good to merge.

**Comment by shendy-a8c** [comment]
> Maybe it makes sense to add the test in a separate PR when all to-be-implemented UIs have been added.

Or maybe that PR is needed sooner so the UIs that are to be added can just add to the test file. I can work on that PR if it makes sense.

**Comment by james-allan** [comment]
> Maybe it makes sense to add the test in a separate PR when all to-be-implemented UIs have been added.
>
> What do you think?

I was under the impression that with https://github.com/Automattic/woocommerce-payments/pull/5799 the base tests were being introduced so I didnt want to introduce a tests dir only for it to conflict once this PR or #5799 was merged. Now that #5799 has been merged though there's a base file I could build on and add tests too. 

Having said that, I'm not sure what tests for this footer would look like given there's no variance to it. I suspect the footer just needs to be part of the broader UI snapshot test.

**Comment by james-allan** [comment]
To avoid forgetting to add a snapshot test that includes the footer, I'm going to add a basic test that tests that the footer renders but like you mentioned earlier I think there will need to be a test at the end that checks that the full card renders.

**Comment by shendy-a8c** [comment]
That makes sense, @james-allan.

I think I misread or something when I said:
> I don't see client/components/deposits-overview/test yet in base branch

which made me thing that `client/components/deposits-overview/test` folder it's not part of https://github.com/Automattic/woocommerce-payments/pull/5799 and it was not there in `develop` where in fact it was there. Now I see it.

Sorry for the confusion.

This PR looks good to merge.

**Pull request merged**
