### PR TITLE
Pass the pay-for-order params to the first-party auth flow

### LINKED ISSUE #7762: First-party auth flow doesn't pass the pay-for-order params to WooPay
### Describe the bug
With the first-party auth flow enabled, we are not passing the pay-for-order params to WooPay in the session. Without the pay-for-order params, we are making the request to the `/cart`, not to the `/order` endpoint, so we are not getting the pay-for-order order on WooPay.

Note: There's another first-party auth flow and pay-for-order flow incompatibility issue, so we'll need to **add a product in the cart** to be able to test the first-party auth flow with pay-for-order. This issue will be addressed in another PR.

### To Reproduce
1. Enable the Pay-for-order flow for WooPay
2. Create a pay-for-order order with WooCommerce Pre-Orders
3. Open the pay-for-order order
4. Add a product to your cart
5. Click the WooPay button
6. See there are no pay-for-order params passing to WooPay

### Actual behavior with screenshot
When we enabled the first-party auth flow and test the pay-for-order flow, we can't get the pay-for-order order on WooPay site. That's because we are not passing the pay-for-order params from the merchant to the WooPay site.

*See we don't have the pay-for-order params in the URL*
Screen Shot 2023-11-21 at 2 12 45 PM

### Expected behavior with screenshot
We should pass the pay-for-order params from the merchant to the WooPay site so we can get the pay-for-order order.

Screen Shot 2023-11-21 at 2 30 45 PM

### PR DESCRIPTION
**Pull request by hsingyuc**
Fixes #7762

#### Changes proposed in this Pull Request
This PR passes the pay-for-order params to the first-party auth flow so we can get the pay-for-order order on WooPay.

#### Testing instructions
1. Enable the Pay-for-order flow for WooPay
2. Create a pay-for-order order with WooCommerce Pre-Orders
3. Open the pay-for-order order
4. Add a product to your cart
5. Click the WooPay button
6. You should see the pay-for-order params `pay_for_order`, `order_id`, `key`, and the `billing_email` passing to WooPay

#### Screenshots
|Before|After|
|-|-|
|Screen Shot 2023-11-21 at 2 12 45 PM|Screen Shot 2023-11-21 at 3 02 50 PM|

-------------------

- [X] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7763` or branch name `fix/pass-pay-for-order-params-to-first-party-auth-flow` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/pass-pay-for-order-params-to-first-party-auth-flow) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 60e1d02060fe5a798425ed9d2f792415344f950c
- Build time: 2023-11-22 19:08:19 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by hsingyuc** [comment]
Note: The checkout error on the WooPay site is expected.

Screen Shot 2023-11-21 at 4 30 44 PM

**Review by malithsen — APPROVED** [review]
Looks good. I can see the pay for order params in the redirected URL in WooPay.

**Comment by hsingyuc** [comment]
This PR is part of the fix of https://github.com/Automattic/woopay/issues/2250

**Pull request merged**
