### PR TITLE
Split translations workflow

### PR DESCRIPTION
**Pull request by dmvrtx**
**Changes**

_Introduce a workflow to publish pre-releases for pushed tags._

Workflow `pre-release-publish-on-tag.yaml`: Workflow that fires on tag push event and creates a pre-release for this tag. It listens to tag `push` events but ignores tags with pure SemVer, e.g. `2.9.0` to avoid conflicts with release tool and tags like `i18n-20210801` to prevent conflicts with translation workflow.

It picks release name from a tag annotation and also tries to retrieve change log updates for release description.

**Notes**

 * To give release a name use annotated tags, e.g. `git tag -a -m "<tag_name>" <tag_name>`. Otherwise, release will be named after the latest commit message on the tag.

**How to test**

 * Checkout branch
 * Create annotated tag and push it

```bash
git checkout -b feature/1118-split-translations-workflow origin/feature/1118-split-translations-workflow
git tag -a -m "Test workflow" test-workflow && git push origin test-workflow
```

As a result a new pre-release will be created in a matter of minutes. Progress of workflow can be checked on the [Actions tab](https://github.com/Automattic/woocommerce-payments/actions/workflows/pre-release-publish-on-tag.yaml) of the repository. Please remove resulting pre-release after testing.

**How to remove accidental release**

 * GitHub releases are tightly coupled with tags. To remove (pre-)release we first have to remove a relevant tag in  the remote repository: `git push --delete origin <tag_name>`. It is also worth it to drop a tag locally: `git tag -d <tag_name>`.
 * Go to [Releases](https://github.com/Automattic/woocommerce-payments/releases) page. Release with removed tag  becomes a _Draft Release_. Click on **Edit** next to it and use **Discard Draft** button on the edit page to remove it completely. 

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

**Comment by dmvrtx** [comment]
I've reduced the scope of this PR to only introduce a workflow that publishes a new pre-release for pushed tags. How to automate tag creation will be a topic of a separate work.

**Review by diegocurbelo — CHANGES_REQUESTED** [review]
Great work @dmvrtx!. I like the `set-output` and `fromJson` combo 😄.

Works well, just one detail... in case of an error in the `curl` command the job is halted and no response is printed to the console:

Screen Shot 2021-09-04 at 00 02 45

**Comment by dmvrtx** [comment]
>  in case of an error in the curl command the job is halted and no response is printed to the console

@diegocurbelo, good catch, I haven't fixed the `curl` flow yet.

**Comment by dmvrtx** [comment]
I updated handling of `curl` interactions to avoid use of temporary files but still provide error response when needed. Also made errors more visible in the GitHub workflow logs.

**Review by diegocurbelo — APPROVED** [review]
LGTM 🚢

**Pull request merged**
