### PR TITLE
Update `react` & `react-dom` dependency to version 17.0.2

### LINKED ISSUE #6097: Update `react` dependency to version 17.0.2
### Description

We want to update the [react](https://www.npmjs.com/package/react) package to a more recent version, the one being used by our minimum supported version of WordPress:

- Current version: [16.14.0](https://www.npmjs.com/package/react/v/16.14.0)
- Target version: [17.0.2](https://www.npmjs.com/package/react/v/17.0.2)

### Acceptance criteria

- JS unit tests are passing
- For TypeScript libraries, ensure we're using the [DefinitelyTyped](https://www.npmjs.com/package/@types/react/v/17.0.39) types available with the target version instead of our custom types, if applicable.
  - If it's too much or it seems too complicated because of a lack of expertise in the relevant frontend areas, feel free to document what's missing to be confident about the update and ask for help from [the team owning this area](https://wootransactp2.wordpress.com/welcome-to-transact/product-responsibilities/)
- The review process from the [dependencies doc](https://github.com/Automattic/woocommerce-payments/blob/develop/docs/dependencies.md#javascript-dev-dependencies) was followed and now has an entry for this package with all the relevant details for future iterations

### Dev notes

Run `npm install --save-exact <packageName@version>` to update a package by an exact version.

Manual UI checks or/and E2E tests don't have any added value here because we're using the bundled version in WordPress, and updating the version locally will not impact the version used when using WCPay.

### LINKED ISSUE #6098: Update`react-dom` dependency to version 17.0.2
### Description

We want to update the [react-dom](https://www.npmjs.com/package/react-dom) package to a more recent version, the one being used by our minimum supported version of WooCommerce:

- Current version: [16.14.0](https://www.npmjs.com/package/react-dom/v/16.14.0)
- Target version: [17.0.2](https://www.npmjs.com/package/react-dom/v/17.0.2)

### Acceptance criteria

- JS unit tests are passing
- For TypeScript libraries, ensure we're using the [DefinitelyTyped](https://www.npmjs.com/package/@types/react-dom/v/17.0.11) types available with the target version instead of our custom types, if applicable.
  - If it's too much or it seems too complicated because of a lack of expertise in the relevant frontend areas, feel free to document what's missing to be confident about the update and ask for help from [the team owning this area](https://wootransactp2.wordpress.com/welcome-to-transact/product-responsibilities/)
- The review process from the [dependencies doc](https://github.com/Automattic/woocommerce-payments/blob/develop/docs/dependencies.md#javascript-dev-dependencies) was followed and now has an entry for this package with all the relevant details for future iterations

### Dev notes

Run `npm install --save-exact <packageName@version>` to update a package by an exact version.

Manual UI checks or/and E2E tests don't have any added value here because we're using the bundled version in WordPress, and updating the version locally will not impact the version used when using WCPay.

### PR DESCRIPTION
**Pull request by achyuthajoy**
Fixes #6097 
Fixes #6098 

#### Changes proposed in this Pull Request
- Update `react` to v17.0.2
- Update `react-dom` to v17.0.2
- Update `@types/react` to 17.0.2
- Added workaround for failing phone-number-control test `toggles focused class as expected` caused by `jsdom` not firing onBlur / onFocus events (https://github.com/testing-library/user-event/issues/592) https://github.com/Automattic/woocommerce-payments/blob/b7634468560d905a479d50066233f807da62413f/client/components/phone-number-control/test/index.test.tsx#L88-L100

#### Testing instructions

* Ensure JS tests as passing

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6180` or branch name `update/dependency/react` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=update/dependency/react) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 268eb855b8b54ad92a231a241971a39b266ffb27
- Build time: 2023-05-12 07:56:17 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by achyuthajoy** [comment]
Hey @Jinksi 👋 Could you check the failing JS tests related to tooltips? I'm not sure why it fails, but could be related to the jsdom issue mentioned on the PR description. Can you check and confirm?

**Comment by Jinksi** [comment]
Thanks @achyuthajoy 👍 

I've pushed a commit with a fix for the failing `Tooltip` tests (d5c0001).

We were toggling between fake/real timers for each test, which was causing hidden side-effects making the tests fail. Toggling these timers before/after all tests fixes this problem.

https://github.com/Automattic/woocommerce-payments/blob/d5c0001545bb97b882154d2585c9cf3cb53da832/client/components/tooltip/test/index.test.tsx#L15-L22

**Review by jbordonado — APPROVED** [review]
That one was not straightforward. Thanks to everyone who contributed to these updates.

LGTM!

**Pull request merged**
