### PR TITLE
Adding the enabled status and the logic to render the Chip component.

### LINKED ISSUE #5966: "Restricted Soon" account status can be displayed without any call to action or additional information.
### Describe the bug
There appear to be circumstances where the account is going to be reviewed by Stripe and shows 'Restricted Soon', but the merchant has no way to know when they will be restricted or what to do next in either their WooCommerce dashboard nor the Stripe Express dashboard.

Presumably, Stripe will reach out the merchant in some cases like this when required, but this is an anxious situation for a business owner who wants to ensure continuity in payment operations, and often results in a support request.

### Actual behavior
'Restricted soon' can be displayed in the WooCommerce Payments dashboard without any qualifying information in the WooCommerce Payment nor Stripe Express account areas.

### Expected behavior
A 'Restricted soon' notice should always be accompanied with a timeline or call to action, even if the action is to wait.

### Additional context
This might be considered an enhancement request, but I'm starting with a bug report since this feels like missing functionality, not a nice-to-have.

p1680632713348389/1680632644.340149-slack-C3NCP7ZJ6

### PR DESCRIPTION
**Pull request by dmallory42**
Fixes #5966 

#### Changes proposed in this Pull Request

Update to add compatibility for a server PR which returns the status as `Enabled` when there is a future requirement but no deadline. This will replace `Restricted Soon` in cases where there is no deadline for the user to take action.

#### Testing instructions

* Pull this branch and run `npm run watch`
* Ensure you have an account with no requirements (status should be `Complete`)
* Adjust the `get_basic_account_info` function on the server to return `enabled` as the `status` in the account response.
* Go to the `Payments > Overview` page, verify that the account status display looks as follows:

Screenshot 2023-08-03 at 11 41 35

* Reverse the change you made to the account status response.
* Refresh the page and verify that the `Complete` status displays as follows (note that it has changed from blue to green, because enabled is blue matching how Stripe display it): 

Screenshot 2023-08-03 at 11 41 53

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6913` or branch name `dev/5966-restricted-soon-fix` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=dev/5966-restricted-soon-fix) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: c23427c1bad52da17d86859a9a09fdbe21b00938
- Build time: 2023-08-04 15:00:48 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by ismaeldcom — APPROVED** [review]
Looks good to me, thanks for handling this status case. The only missing thing is to update the failing test snapshots, but I'm preapproving it 🙂

**Comment by dmallory42** [comment]
@aheckler I just wanted to check if there are any documentation updates required as a result of this change.

We have a new account status called `Enabled` for an account which is in good standing, but will be required to provide information in the future once a payment volume is hit. 

Previously, merchants in this state would see an account status of `Restricted soon` (which is confusing and suboptimal for the merchant because there's no action needed to take **at that time**).

Functionally, this account status is the same as `Complete`, the only difference is that an `Enabled` account will be required to provide information to Stripe in the future (whereas a `Complete` account is already fully verified).

I couldn't see any documentation page about WooPayments account statuses, so maybe no change is needed but just wanted to flag it.

Thanks!

**Comment by aheckler** [comment]
@dmallory42 

> I couldn't see any documentation page about WooPayments account statuses, so maybe no change is needed but just wanted to flag it.

Yeah, I don't think we have an exhaustive list of the possible account statuses anywhere. I'm happy to add a bit to our docs about this though, but that brings me to the question: what _are_ all of the account statuses and their meanings? I'm not sure I know them all.

Seems like maybe they are defined [here](https://github.com/Automattic/woocommerce-payments/blob/829d5b995376fd7a5c4694e9ee7d2f1ae52a7db3/client/account-status-settings/index.js#L43-L114)?

**Comment by dmallory42** [comment]
Hi @aheckler!

Good question! AFAIK, the possible statuses we have are as follows (along with my understanding of them):

- Complete - The account is fully verified and active.
- Enabled - The account is active but may require some extra verification in future (usually when a threshold is hit e.g. time/volume)
- Restricted Soon - The account is active but has a verification requirement (along with a deadline) that will cause it to become restricted in future.
- Restricted Partially - The account is restricted because of missing data (I'm unsure how this status differs from `restricted`).
- Pending Verification - Some account features like payouts may be limited until Stripe approves data provided by the account. This is usually a temporary status and the account will then transition to either Restricted or Complete/Enabled.
- Rejected - The account has been rejected by Stripe (or by us on behalf of Stripe), usually for fraud or TOS violation.
- Restricted - The account is restricted for any other reason than a rejection (they cannot make payouts or payments). 

Most of these statuses are mirrors of [Stripe's account statuses](https://stripe.com/docs/connect/dashboard).

**Pull request merged**
