### PR TITLE
E2E: skip failing test suite `shopper-bnpls-checkout`

### PR DESCRIPTION
**Pull request by Jinksi**
#### Changes proposed in this Pull Request

> [!CAUTION]
> This PR targets `trunk` which is required to fix e2e tests for server and client repos.

This PR temporarily skips the e2e test suite `shopper-bnpls-checkout.spec.js` due to test failure for both client and server GH checks – missing selector when changing account currency reported in #8354.

#### Testing instructions

* Ensure GH checks on this PR pass for `E2E Tests - Pull Request / WC - latest | wcpay - shopper` `shopper-bnpls-checkout.spec.js`

-------------------

- [x] Run `npm run changelog` **N/A when targeting `trunk`** 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile **N/A**

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8355` or branch name `e2e/skip-broken-test-shopper-bnpls-checkout` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=e2e/skip-broken-test-shopper-bnpls-checkout) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 2dc65b43731777d961289923683a09f189d97a00
- Build time: 2024-03-08 02:09:38 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by brucealdridge — APPROVED** [review]
Approving untested. 
Issue has been created for failing E2E test.

**Comment by Jinksi** [comment]
Re-running E2E tests due to unexpected failure.

**Comment by Jinksi** [comment]
E2E test failing for an unrelated reason `shopper-klarna-checkout.spec.js` 

```
Error: Protocol error (Runtime.callFunctionOn): Target closed.
```

May be related to #4482

**Update**: I also see this when running locally:
`npm run test:e2e -- tests/e2e/specs/wcpay/shopper/shopper-klarna-checkout.spec.js`

**Pull request merged**
