### PR TITLE
Release branch for 6.9.2

### PR DESCRIPTION
**Pull request by botwoo**
:warning: Please do not merge the PR from the GitHub interface. :warning:

 Instead, you can use the following command:
```
 git checkout release/6.9.2 && git pull 
 git checkout trunk && git pull 
 git merge --no-ff release/6.9.2 -m 'Merge release/6.9.2 into trunk' 
 git push origin trunk 
``` 
 Changelog: 
```

```

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7894` or branch name `release/6.9.2` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=release/6.9.2) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 7343bb2b0f39958fab005102cba86a31bcf5b32b
- Build time: 2023-12-14 03:37:26 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by shendy-a8c** [comment]
Zip file: https://github.com/Automattic/woocommerce-payments/suites/19032945345/artifacts/1113774406

**Comment by shendy-a8c** [comment]
Despite retries, some e2e tests are failing.
[Release PR for 6.9.1](https://github.com/Automattic/woocommerce-payments/pull/7853) had some e2e tests failed too but in this PR, there is more test failing.

**Review by shendy-a8c — APPROVED** [review]
Going ahead approving this PR as the failing e2e tests do not seem related to this PR changes and also I don't find problems with smoke test.

**Pull request merged**
