### PR TITLE
Added tests and workflows for sub product with signup fee

### PR DESCRIPTION
**Pull request by zhongruige**
Fixes https://github.com/Automattic/woocommerce-payments/issues/1490

The changes proposed on this PR adds a new test around the `Merchant / Subscriptions / Purchase subscription with signup fee` workflow. Additionally, this also adds in new helper functions for merchant workflows, including adding a new subscription product.

#### Testing instructions

*Prereqs*

As these changes rely on having the WooCommerce Subscriptions plugin installed in the test environment to work, please make sure you have the following set in your `local.env` in the `tests/e2e/config` folder:

```
E2E_GH_TOKEN='githubPersonalAccessToken'
WC_SUBSCRIPTIONS_REPO='{owner}/{repo}'
```

To create the `E2E_GH_TOKEN`, follow [these instructions to generate a GitHub Personal Access Token](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) and assign the `repo` scope to it.

Once that is configured, proceed to spin up the test environment and run through the test steps below.

- Make sure the CI tests pass
- Run the new test locally in either headless or non-headless mode and verify it passes:
    * `npm run test:e2e ./tests/e2e/specs/subscriptions/purchase-sign-up-fee-subscription.spec.js`
    * `npm run test:e2e-dev ./tests/e2e/specs/subscriptions/purchase-sign-up-fee-subscription.spec.js`

### CODE REVIEW

**Review by reykjalin — APPROVED** [review]
The changes look good to me.

The CI tests have passed, and I was able to get the e2e tests to pass with `npm run test:e2e-dev`, but the headless test never worked for me. I always get this error:

```
  ● Subscriptions > Purchase subscription with signup fee › should be able to purchase a subscription with signup fee

    : Timeout - Async callback was not invoked within the 100000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 100000ms timeout specified by jest.setTimeout.Error:

      at new Spec (node_modules/@wordpress/scripts/node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at _callee2$ (node_modules/@automattic/puppeteer-utils/lib/jest.test.failure.js:43:20)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:293:22)
      at Generator.next (node_modules/regenerator-runtime/runtime.js:118:21)

  ● Subscriptions > Purchase subscription with signup fee › should have an active subscription

    TimeoutError: Text not found "Order received"

      waiting for function failed: timeout 500ms exceeded
```

I'm approving the PR despite that because this is the first time I'm running the e2e tests and I'm pretty sure this is an issue with my setup, and not the tests themselves.

If you do happen to know what the problem is, fixing it would be great, but otherwise let's go ahead and merge this 🙂

**Comment by zhongruige** [comment]
Thank you for the review @reykjalin!

Ah! I bet I know the issue. This is because the subscription product creates a user:

Screen Shot 2021-05-18 at 3 23 54 PM

So, if you ran these tests right after each other, then you will see this error in the UI:

Screen Shot 2021-05-18 at 3 22 56 PM

As a result, it causes subsequent tests to fail. 

To fix this issue, once it's available in the newest `@woocommerce/e2e-utils` package, I will be adding `deleteCustomerByEmail()` to the `afterAll()` of this and subsequent subscription tests: https://github.com/woocommerce/woocommerce/blob/trunk/tests/e2e/utils/src/flows/with-rest-api.js#L108

I did want to make sure nothing was being weird, so I did re-run the tests just to make sure:

Screen Shot 2021-05-18 at 3 19 18 PM

Let me know if you have any questions/concerns on the above before merging this in.

Thanks!

**Comment by reykjalin** [comment]
@zhongruige Sorry for the late reply! This dropped of my radar 😬 

>Let me know if you have any questions/concerns on the above before merging this in.

Just this one; do you think we should wait until `deleteCustomerByEmail()` is available, or do you think that's not necessary?

If you think we should wait, let's tag this PR with `status: blocked` until we can add that function call.

If you think we don't have to wait, we can merge this PR, but please create a new issue so we can track the status of adding that the call to `deleteCustomerByEmail()` 🙂

**Comment by zhongruige** [comment]
> @zhongruige Sorry for the late reply! This dropped of my radar 😬
> 
> > Let me know if you have any questions/concerns on the above before merging this in.
> 
> Just this one; do you think we should wait until `deleteCustomerByEmail()` is available, or do you think that's not necessary?
> 
> If you think we should wait, let's tag this PR with `status: blocked` until we can add that function call.
> 
> If you think we don't have to wait, we can merge this PR, but please create a new issue so we can track the status of adding that the call to `deleteCustomerByEmail()` 🙂

No worries at all for the delay @reykjalin! Appreciate the reply! Actually this worked out great as just recently a new version of `@woocommerce/e2e-utils` was released with support for the `withRestApi()`. So I will be updating this test and pulling in the latest package versions so we can take advantage of the updates.

So, I am going to drop the `pr: ready for review` / `pr: ready to merge` labels for now and will add it back on once those changes have been incorporated and verified working.

**Review by reykjalin — APPROVED** [review]
Looks good, and test well.

Let's merge 🚀

**Comment by zhongruige** [comment]
Thanks so much for the helpful review and comments along the way @reykjalin!

**Pull request merged**
