### PR TITLE
Speedup PHPUnit tests

### LINKED ISSUE #9016: PHPUnit tests are too slow to run
### Describe the issue

Our PHPUnit tests are annoyingly slow to run (4-5 minutes on my local env) and we need to make them run faster 😤 

Sometimes they are excruciatingly slow (40+ minutes), as detailed in this Slack thread: p1718964876480489-slack-CGGCLBN58

### To Reproduce

Run `npm run test:php` and sit back.

### PR DESCRIPTION
**Pull request by vladolaru**
Fixes #9016 

#### Changes proposed in this Pull Request

Currently, the PHPUnit tests run somewhere **between 4 and 5 minutes** on my local env. Not pleasant. I investigated and tried:
- messing with the MariaDB config - no effect since we already have the `START TRANSACTION` and `ROLLBACK` mechanism for avoiding DB commits
- checked slow file loading (like for fixtures) - not an issue

I wasn't going to get into our test arrangements and how efficiently we make use of DB operations. That is too much work and I don't think it's worth it.

I was lost until I glanced over on some random StackOverflow that someone discovered that their tests were much faster _without an internet connection_ 🤨 Voodoo, but it couldn't hurt to try it. I did, and they were much faster! 😵

It turns out our client is making external calls to our WPCOM APIs (e.g., for fetching the fraud services config) - any caching mechanisms are moot during tests and **the requests were retried on every test case** and, via the WC core, to geolocation APIs.

Well, not anymore.

This PR introduces changes to our `WCPAY_UnitTestCase` base class for tests to intercept HTTP requests and defaults to mocking a service unavailable (503) HTTP response. Individual tests can hook in to the `pre_http_request` filter and provide other responses (e.g., [like we do for incentives](https://github.com/Automattic/woocommerce-payments/blob/6aaf6a40814967a93b0d1916d590dfe4e80d369c/tests/unit/test-class-wc-payments-incentives-service.php#L217-L217)).

For geolocation, this PR introduces [a JSON file](https://github.com/Automattic/woocommerce-payments/blob/6aaf6a40814967a93b0d1916d590dfe4e80d369c/tests/unit/test-data/ip-geolocation.json#L222-L222) with test data for IP geolocation and will intercept all WC core geolocation external requests.

The result? Now, the PHPUnit tests run in **1 minute and 15 seconds** on the same local env. **3x faster!**

#### Testing instructions

* Checkout the PR branch on your local client
* Run the tests with `npm run test:php` and they should all pass (and be much faster)

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9018` or branch name `update/speedup-phpunit-tests` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=update/speedup-phpunit-tests) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: bbbc1cb7dff85f8d86f50eb4d8223c1cb8d293bb
- Build time: 2024-06-25 13:09:43 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by dmallory42 — APPROVED** [review]
Amazing work! Tests ran in 45 seconds for me. Thanks for working on this!

**Review by elazzabi — APPROVED** [review]
I 100% agree with this PR :shipit:

**Review by dmvrtx — APPROVED** [review]
:shipit:

**Pull request merged**
