### PR TITLE
Update connect account page

### LINKED ISSUE #5508: Unify onboarding logic and experience
### Description
With the new progressive onboarding flow, we're also changing how WCPay onboarding works. So it will be good to update the existing code and come with a unified solution to avoid making tricky redirections based on the flow we want to use.

For now, we have the connect page, that's skipped when the merchant comes from a task, and the new onboarding page that's injected before the Stripe redirection.

We could simplify it having just a single onboarding page, to avoid making so many conditions and redirections.

We also need to consider what to do with the current connect page in terms of UI/UX.

### Acceptance criteria
- Every merchant lands on the same WCPay page after being redirected to onboarding.
- The connect account page design is implemented.
- Jetpack connection is made at the appropriate step.

### PR DESCRIPTION
**Pull request by ismaeldcom**
Fixes #5508 

#### Changes proposed in this Pull Request
- Remove unused experiment code.
- Implement new design.
- Migrate modified code to TypeScript.
- Refactor affected code.

Also confirmed that Jetpack connection happens just before the new onboarding flow, and every redirection to Stripe KYC lands also on the new onboarding flow, making a consistent experience.

- Disconnect your existing account or enable `Force the plugin to act as disconnected from WCPay` in **WCPay Dev**.
- Go to **Payments**
- The connect account page should load and the design match.
- Check the following variations work as expected:
  - Clicking on `Learn more about how to receive payouts` shows a modal.
  - Setting `wcpaySettings.connect.country = ''` and clicking on `Finish setup` shows a modal.
  - Setting `wcpaySettings.errorMessage = 'Sample error message'` shows an error notice at the top.
  - Setting `wcpaySettings.onBoardingDisabled = true` only shows the disable message.

#### Screenshots
| Desktop | Mobile |
|-|-|
|Screenshot 2023-05-12 at 08 42 46|Screenshot 2023-05-12 at 08 45 59|

| Country modal | Learn more modal |
|-|-|
|Screenshot 2023-05-12 at 08 56 45|Screenshot 2023-05-12 at 09 08 26|

| Error notice | Disable message |
|-|-|
|Screenshot 2023-05-12 at 08 57 14|Screenshot 2023-05-12 at 08 58 27|

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6282` or branch name `update/5508-connect-account-page` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=update/5508-connect-account-page) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: fa54c73db90d538abb5bdcac54232f5b8ec2f18d
- Build time: 2023-05-16 07:53:51 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by oaratovskyi — APPROVED** [review]
@ismaeldcom amazing work!
Everything works as it should, with no comment on the code - it totally makes sense to me :shipit: 
Just one confidence check question about this title (see attached image) - should it be this big?

**Comment by ismaeldcom** [comment]
Thanks for the review!

>Just one confidence check question about this title (see attached image) - should it be this big?

The style comes from the previous experiment, I've only replaced the old logo with the new one. We don't have a mobile design rerefence, but yes, it also looks quite big to me 🙂 Probably a 50% of that will look better. What do you think?

**Comment by oaratovskyi** [comment]
> Probably a 50% of that will look better

I agree, that would work.

**Comment by ismaeldcom** [comment]
Addressed in fa54c73
Screenshot 2023-05-16 at 09 49 42

**Pull request merged**
