### PR TITLE
Fix AED and SAR currencies format

### LINKED ISSUE #6633: Incorrect format for Saudi Riyal (SAR) and United Arab Emirates Dirham (AED) currencies
### Describe the bug

We were recently informed by a merchant that WCPay displays an incorrect format for Saudi Riyal (SAR) and Dubai Dirham (AED) currencies (see ticket 6461033). We are currently setting the thousand separator to a comma and the decimal separator to a period for both currencies. It should be the inverse.

UAE related localization and currency data:
https://github.com/Automattic/woocommerce-payments/blob/develop/i18n/locale-info.php#L30-L45
https://github.com/Automattic/woocommerce-payments/blob/develop/i18n/currency-info.php#L129-L132

KSA related localization and currency data:
https://github.com/Automattic/woocommerce-payments/blob/develop/i18n/locale-info.php#L3070-L3085
https://github.com/Automattic/woocommerce-payments/blob/develop/i18n/currency-info.php#L725-L728

As part of my investigation, I checked with our team that handles i18n. They shared their sources that showed it should be a comma as the thousands separator and a period as the decimal separator. One of the sources was [CLDR](https://www.unicode.org/cldr/cldr-aux/charts/24/summary/ar.html) which is what we used when Multi-Currency was being developed and the two above linked files were being built. Apparently it was just an error during development.

[CLDR - Arabic - Number Formatting Patterns - Standard Patterns when using Western Digits (latn) - standard-currency](https://www.unicode.org/cldr/cldr-aux/charts/24/summary/ar.html#3471)

`¤#,##0.00`

### To Reproduce

1. Go to WooCommerce > Settings > Multi-currency
2. Add SAR and AED as currencies.
3. Add the multi-currency widget to your site's sidebar if not already there.
4. Go to a single product page and select SAR and then AED to see the incorrect format. See screenshots below.

### Actual behavior

The price is displayed with the incorrect currency format: `1.234,56`

### Screenshots

SAR format incorrect:
Screenshot on 2023-06-29 at 15_40_06

AED format incorrect:
Screenshot on 2023-06-29 at 15_41_21

### Expected behavior

The price is displayed with the correct currency format: `1,234.56`

### Additional context

Slack links:
- p1687923858267909-slack-C7U3Y3VMY
- p1687957037838519-slack-C01B8KNUYSW
- p1687967942985629-slack-C02AED43D

### PR DESCRIPTION
**Pull request by allie500**
Fixes #6633 

#### Changes proposed in this Pull Request

This PR fixes the currency format for AED and SAR currencies. 

Previously, the AED and SAR currencies had the incorrect characters in use for the thousands and decimal separators. They were using the period for the thousands separator and the comma for the decimal separator. The correct format is the inverse of that. This PR only changes hardcoded values.

#### Testing instructions

* Check out this PR branch.
* All tests should pass.
* Create a product with a high price (ex. $1,234.56) if you don't have one already.
* Enable SAR and AED currencies in WooCommerce > Settings > Multi-currency.
* Add the multi-currency widget to your site's sidebar if not already there.
* Clear locale info and currency format transients: `npm run wp transient delete wcpay_locale_info && npm run wp transient delete wcpay_currency_format`
* Then comment out the AED and SAR entries in the WC core files:
  * AED locale: `/wp-content/plugins/woocommerce/i18n/locale-info.php:30-45`
  * SAR locale: `/wp-content/plugins/woocommerce/i18n/locale-info.php:3070-3085`
  * AED currency: `/wp-content/plugins/woocommerce/i18n/currency-info.php:129-132`
  * SAR currency: `/wp-content/plugins/woocommerce/i18n/currency-info.php:725-728`
* Navigate to the single product page that has the high price.
* Switch your currency to AED and observe the price. The format should have a comma thousands separator and a period decimal separator. 
* Switch your currency to SAR and observe the price. The format should have a comma thousands separator and a period decimal separator.

Example screenshots with the correct thousands and decimal separators:

#### AED

Screenshot on 2023-08-28 at 15_08_00

#### SAR

Screenshot on 2023-08-28 at 15_07_30

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7083` or branch name `fix/6633-sar-aed-currencies-formatting` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/6633-sar-aed-currencies-formatting) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: def9a4aaab2b2bcf65873e69f6983b273e70ea1c
- Build time: 2023-08-30 16:22:57 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by jessepearson** [comment]
@allie500 Do we have a PR open to fix this in WC core, as well, or are you waiting for this to be merged before that's done?

Scratch that, I just saw your thread: p1693251521243719-slack-C01B8KNUYSW

**Comment by allie500** [comment]
> @allie500 Do we have a PR open to fix this in WC core, as well, or are you waiting for this to be merged before that's done?
> 
> Scratch that, I just saw your thread: p1693251521243719-slack-C01B8KNUYSW

@jessepearson, yea, I'll open an issue for it in core once we get this one wrapped up. As you see in the thread you linked to, we should be good to go with the formatting introduced in this PR.

**Review by jessepearson — APPROVED** [review]
Changes are straight forward and work as described.

Noting that I talked to you about the currency symbol location in p1693398649497549-slack-C01B8KNUYSW

**Pull request merged**
