### PR TITLE
Bump Required Versions for 2.5 Release

### PR DESCRIPTION
**Pull request by adrianduffell**
#### Changes proposed in this Pull Request

Bumps minimum required versions for the 2.5 release.

This PR bumps the required WordPress version to 5.5, and WooCommerce version to 4.8, as per the [L-2 transition timeline](https://developer.woocommerce.com/2021/05/12/woocommerce-payments-is-adopting-a-new-version-support-policy/).

The `WC requires at least` version remains at 4.0, as it is pending improvements in issue https://github.com/Automattic/woocommerce-payments/issues/1775 first.

#### Testing instructions

* Check that versions match the [L-2 transition timeline](https://developer.woocommerce.com/2021/05/12/woocommerce-payments-is-adopting-a-new-version-support-policy/).

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

**Comment by shendy-a8c** [comment]
Looking at the last time we bumped version done [here](https://github.com/Automattic/woocommerce-payments/pull/1549/files) by @jrodger, do you think we also need to add the changelog, `phpcs.xml.dist`, and `.github/workflows/compatibility.yml`?

**Review by shendy-a8c — COMMENTED** [review]
Looking at the last time we bumped version done [here](https://github.com/Automattic/woocommerce-payments/pull/1549/files) by @jrodger, do you think we also need to add the changelog, `phpcs.xml.dist`, and `.github/workflows/compatibility.yml`?

Other than that, looks good!

**Comment by adrianduffell** [comment]
> Looking at the last time we bumped version done [here](https://github.com/Automattic/woocommerce-payments/pull/1549/files) by @jrodger, do you think we also need to add the changelog, `phpcs.xml.dist`, and `.github/workflows/compatibility.yml`?
> 
> Other than that, looks good!

@shendy-a8c Thanks for pointing me the previous PR. Those additions all sound good to me!

I've made them in 92d6374 b28fbab bffcdf3

I was thinking we should document on the wiki all the places to make version bump changes. What do you think?

**Comment by adrianduffell** [comment]
Note: In PR https://github.com/Automattic/woocommerce-payments/pull/1747, we decided to keep the older WooCommerce versions in CI so I have kept them in place here for now as well.

**Comment by adrianduffell** [comment]
I noticed bffcdf3 caused a check to fail. Created an issue for it here #1972

@shendy-a8c do you think it's a blocker for this PR?

**Comment by jrodger** [comment]
> do you think it's a blocker for this PR?

I don't think we need to let that issue block this PR. I'd rather not leave the CI checks failing though, so perhaps we can rollback that part to 5.4 and put it back to 5.5. when #1972 is fixed?

**Comment by adrianduffell** [comment]
> I don't think we need to let that issue block this PR. I'd rather not leave the CI checks failing though, so perhaps we can rollback that part to 5.4 and put it back to 5.5. when #1972 is fixed?

I've now rolled this back in adb14ef and all tests are passing again.

@shendy-a8c or @jrodger could you please re-review before the 2.5 release?

**Review by shendy-a8c — APPROVED** [review]
Looks good! Thank you for opening #1972.

**Pull request merged**
