### PR TITLE
Prevent browser error on dispute evidence submission

### LINKED ISSUE #9830: When submitting dispute evidence the browser warns about unsaved data
### Describe the bug

When dispute evidence is submitted the browser warns about unsaved data. Clicking `Leave` allows submission to occur successfully.

Image

### To Reproduce

Respond to an open dispute.

I was able to trigger with the following steps on a fresh site using `develop` branch.

1. View a dispute
2. Click `Submit Evidence` 
3. Select `Physical Product`
4. Enter `winning_evidence` in `Additional Details`
5. Click `Submit evidence`
6. See browser warning.

### PR DESCRIPTION
**Pull request by brucealdridge**
Fixes #9830

#### Changes proposed in this Pull Request

Successful dispute evidence submission causes the browser to navigate to refresh the page. This was triggering the browser alert due to a hook on `onbeforeunload`.

Screenshot 2024-11-28 at 3 47 21 PM

This change ensures the evidence is reset before attempting to navigate away which prevents the browser alert.

It looks like this bug may have been introduced in #4458 when the browser navigation was introduced due to caching issues.

I chatted with @Jinksi about the best way to approach this change as there are a few improvements that could be made. For now, we agreed that the one-line fix approach is best. p1732845547215289-slack-C02BW3Z8SHK

**Update**: The one line fix did not work in all cases due to the way that react batches state updates async. This PR has been updated to handle this case and support both Submission and Saving of evidence.

#### Testing instructions

1. Open dispute 
2. Save draft evidence, confirm browser pop-up does not occur.
3. Re-open dispute
4. Submit evidence.
5. Confirm browser alert about changes not being saved does not show.

-------------------

- [x] Run `npm run changelog` to add a changelog file.
- [x] Covered with tests
- [x] Tested on mobile

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9847` or branch name `fix/9830-browser-error-on-dispute-submission` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/9830-browser-error-on-dispute-submission) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 9e3c539f1289e30ac797b5fb5df7e307400726ad
- Build time: 2024-12-02 21:31:50 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by nagpai** [comment]
I did a manual test and continued seeing the popup 

image

**Comment by brucealdridge** [comment]
> I did a manual test and continued seeing the popup

thanks @nagpai, that's unfortunate but no unexpected. I've refactored the change to work in all cases. Additionally I found that saving draft evidence still had the popup so I've added a fix for that as well.

**Review by jessy-p — APPROVED** [review]
Reviewed the code, tested it. The browser popup is not longer displayed after the fix. ✅

**Pull request merged**
