### PR TITLE
Use the customer ID saved in the subscription to process renewal payments

### LINKED ISSUE #8892: Review Customer ID logic
8247182-zen

This is based on my observation, please feel free to close this report if not relevant or incorrect. 

The user decided to migrate their site to GoDaddy but it seems something went wrong during migration and they started seeing failed renewals with the following message:

> A payment of $225.00 failed to complete with the following message: Error: The PaymentMethod pm_xx does not belong to the Customer you supplied cus_xx. Please use this PaymentMethod with the Customer that it belongs to instead.

User migrated back to Atomic hosting and we decided to help them with this issue. 

My suspicion is that meta _wcpay_customer_id_live might have gone missing and resulted in creation of new user on Stripe via `create_customer_for_user()`

This new customer ID created on Stripe was stored as `_wcpay_customer_id_live` meta and possibly the failed renewal order was updated with this new Stripe customer ID as well. My question is should we ensure subscriptions is always renewed with customer ID attached to the subscription or renewal order rather than user meta `_wcpay_customer_id_live`? 

I tried updating `_wcpay_customer_id_live` to the correct cus_ ID however it did not work even though there were no traces of the incorrect new cus_ ID at all in the database. It threw the same error.

Later I found `$customer_id = get_user_option( '_wcpay_customer_id_live', 207285275 );` returns the incorrect ID due to caching on Atomic hosting.

Clearing the cache helped fix the issue.

---

Edit:

Or perhaps what I am thinking is `get_user_option()` would have returned blank value when the database prefix changed on migration causing creation of a new ID? 

https://github.com/Automattic/woocommerce-payments/blob/1bd1b1d253cc8e5a7d3f57e4686abb5c6c7c1a91/includes/class-wc-payments-customer-service.php#L132

### PR DESCRIPTION
**Pull request by danielmx-dev**
Fixes #8892

#### Changes proposed in this Pull Request

When processing renewals using WooCommerce subscriptions, WooPayments will try to retrieve the Customer ID from the user meta. In most scenarios this is acceptable; however, we have received reports that after performing a migration, the Customer ID in the User meta may get lost, when this happens, a new Customer ID will be created, but this will cause an error since the Payment details stored in the subscription won't match the new Customer ID.

This PR will use the Customer ID saved in the subscription to make sure there are no mismatches between it and the payment details during renewals.

#### Testing instructions

* Install WooPayments and WooCommerce Subscriptions
* Set up a Subscription Product and purchase it. 
* In WP Admin, find the generated subscription. Note the User ID of the customer and the Subscription ID.
* In a mysql console (or using phpMyAdmin) run the following commands, replace the USER_ID and SUBSCRIPTION_ID:
```sql
SELECT * FROM `wp_usermeta` WHERE user_id = <USER_ID> AND meta_key LIKE 'wp__wcpay%';

SELECT * FROM `wp_wc_orders_meta` WHERE meta_key LIKE '%customer_id' AND order_id = <SUBSCRIPTION_ID>;
```
* Both values should match.
* Run the following command to update the WooPayments Customer ID in the user meta:
```sql
UPDATE `wp_usermeta` SET `meta_value` = 'cus_INVALID' WHERE user_id = <USER_ID> AND meta_key LIKE 'wp__wcpay%' LIMIT 1;
``` 
* In WP Admin, open the Subscription details, on the right side find the Order Actions, and then select "Process Renewal'. Click "Update".

##### Before
* The payment of the renewal order fails. Note the renewal order ID, and run this SQL:
```sql
SELECT * FROM `wp_wc_orders_meta` WHERE meta_key LIKE '%customer_id' AND order_id = <RENEWAL_ORDER_ID>;
```
* The customer ID value should be: `cus_INVALID`

##### After
* The payment of the renewal order succeeds. Note the renewal order ID, and run this SQL:
```sql
SELECT * FROM `wp_wc_orders_meta` WHERE meta_key LIKE '%customer_id' AND order_id = <RENEWAL_ORDER_ID>;
```
* The customer ID value should be the same as the one in the Subscription.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9065` or branch name `fix/8892-use-correct-customer-id-in-renewals` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/8892-use-correct-customer-id-in-renewals) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 2af4333340b9867181c9492a2ff5edb45e0b0548
- Build time: 2024-07-10 18:49:49 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by brettshumaker — APPROVED** [review]
This works as described. 👍

**Comment by geektzu** [comment]
Hi team,

Thank you for fixing this issue. Just to double-confirm, has this fix been released for the latest version of WooPayments?

**Comment by geektzu** [comment]
[Release of WooPayments 8.0.0]
* Fix - Use the customer id saved in the subscription to process renewal payments.

I found this, but I am just double-confirming here.

**Comment by danielmx-dev** [comment]
> Hi team,
> 
> Thank you for fixing this issue. Just to double-confirm, has this fix been released for the latest version of WooPayments?

That is correct, the fix is available now in version 8

**Pull request merged**
