### PR TITLE
WooPayments REST: conditional initialization.

### LINKED ISSUE #8797: Evaluate conditionally intializing REST APIs
### Description

We have at least two places where the rest initialization happens (`add_action( 'rest_api_init', ... );`).
To avoid unnecessary runtime operations, the initialization can be conditional - can be a wrapping if-statement around adding the hook or inside the invoked methods.

Note: the conditional ideas are
- ~~relying to `WC()->is_rest_api_request()`~~
- ~~match the rest URL to include `@^/wc/v3/payments/.+@`, that'll guard our rest APIs from loading in the wrong context.~~
- relying to `get_current_screen()`
- relying to `doing_action( 'woocommerce_admin_shared_settings' )`

### Acceptance criteria
- We evaluate that there is no higher-level logic which does it already
- CI checks pass after any implemented changes

### Additional context
- The side-quest discovery of p1715098461138369-slack-CGGCLBN58
- Ideally, we don't need such checks, but from the linked context, we have [this](https://github.com/woocommerce/woocommerce-admin/pull/1080/files#diff-e205675e31cf3d832ac1189ca39d437e3d9713f9ccd670903ec5ca0a085b8d87R150-R159) code fragment and want to explore if we can skip this context for loading our rest

### PR DESCRIPTION
**Pull request by kalessil**
Fixes #8797
Related to https://github.com/woocommerce/woocommerce/issues/47266

#### Changes proposed in this Pull Request

Initialize REST only in a guaranteed REST context to guarantee the runtime state matches the updated state.
This shall prevent crashes due to rest controllers constructor changes during manual plugin updates.

#### Testing instructions

* Prepare a WooCommerce setup with WooPayments installed (no need for onboarding)
* Build a new zip from this branch using `npm run build:release` and manually update the plugin.
* Modify `\WC_REST_Payments_Orders_Controller::__construct` and add a new mandatory parameter
* Build a new zip from this branch using `npm run build:release` and manually update the plugin.
* After the update we should not see any mentions of the fatal error.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8805` or branch name `add/8797-consitional-rest-apis-init` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=add/8797-consitional-rest-apis-init) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 17c3f2ec8abc9a0dc8255629bc1c121abdb8690e
- Build time: 2024-05-21 06:48:17 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by kalessil** [comment]
@RadoslavGeorgiev: I have yet to test the manual update process, but the UI works and the PR is available for early feedback.

**Comment by kalessil** [comment]
@RadoslavGeorgiev: this PR is ready for review. I'd also ask you to confirm the results of the manual testing - on my end the taken approach works, but I want to avoid "works on my machine" scenario :rofl:

**Review by RadoslavGeorgiev — APPROVED** [review]
The changes look good to me! I only tested locally, simulating a plugin upload, and it worked right as expected. :shipit:

**Pull request merged**
