### PR TITLE
Migrate Woopay item to TypeScript

### LINKED ISSUE #7052: Migrate link-item.js and woopay-item.js to typescript.
### Description

Migrate `link-item.js` and `woopay-item.js` to typescript.

As part of https://github.com/Automattic/woocommerce-payments/issues/6428 improvements, it would be good to convert all the js files to tsx. It would be nice to handle it as a separate issue as target in `tsconfig` needs to be updated to `es6` to convert `link-item` to tsx.
### Acceptance criteria

* Migrate `link-item.js` and `woopay-item.js` to typescript.

### Testing instructions

1. Perfome smoke testing
2. Make sure there are on ts related errors
3. E2E tests should pass

### PR DESCRIPTION
**Pull request by naman03malhotra**
Fixes #7052 
Extension of #7080 

#### Changes proposed in this Pull Request
- Migrated `woopay-item.js` to typescript.

#### Testing instructions

* Test if woopay-item is working as expected in settings page in both desktop and mobile
* Please verify it visually as I have moved CSS in JS to CSS file in #7080 

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [x] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [x] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7081` or branch name `imp/7052-migrate-to-ts-woopay` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=imp/7052-migrate-to-ts-woopay) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 8ab26c9c397ef2dd10355712f84f8f10f48ac5e8
- Build time: 2023-08-28 16:59:35 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by ismaeldcom — APPROVED** [review]
LGTM! I assume you're declaring `WooPayEnabledSettingsHook` type in `interfaces.ts` to avoid migrating the whole `data/settings/hooks.js` to TS, right? Makes sense for now, if that's the case 🙂

**Comment by naman03malhotra** [comment]
>LGTM! I assume you're declaring WooPayEnabledSettingsHook type in interfaces.ts to avoid migrating the whole data/settings/hooks.js to TS, right?

Yes, for now. Also, I think having interface files for each component is good for easier discovery and maintenance. But this is open for discussion.

**Comment by zmaglica** [comment]
Tested and it's working for me. :shipit:

**Pull request merged**
