### PR TITLE
Wrap logos to not overlap the container

### LINKED ISSUE #6590: Decrease payment provider logos in confirmation screen of Enable local payment method page
### Description

There is not enough space available in the confirmation screen of the `Add additional payment methods` page to display all the payment provider logos when all of them are enabled.

Screenshot 2023-06-27 at 12 37 21

### Acceptance criteria

*Payment method logos do not overrun available space when all of them are enabled.

### Designs

Please check this thread: p1687862667003019-slack-C04VCT34PCP

### PR DESCRIPTION
**Pull request by KarlisJ**
Fixes #6590 

#### Changes proposed in this Pull Request

Add CSS wrapping for logos on the payment method confirmation screen so they wouldn't overlap the container if all PMs are selected. 

With the addition of Affirm & Affterpay the number of possible PMs have reached the critical limit where we need this wrap to force them to be displayed in second line.

**Before**
image

**After** 
image

#### Testing instructions

- Go to Payments -> settings and disable "Payment Methods"
- Re-enable them
- Select all possible payment methods and click "continue"
- Observe that logos are properly displayed 

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6614` or branch name `fix/6590-wrap-logos-on-confirmation-screen` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=fix/6590-wrap-logos-on-confirmation-screen) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 9ffa6f17bee948ea711f6feeeed90093cdd4082d
- Build time: 2023-06-29 10:57:15 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by dmvrtx — APPROVED** [review]
Looks good to me!

**Review by kalessil — COMMENTED** [review]
Message in change log is missing.

**Review by kalessil — APPROVED** [review]
Pre-approving.

**Review by mgascam — APPROVED** [review]
LGTM!

**Review by nagpai — APPROVED** [review]
LGTM!

**Pull request merged**
