### PR TITLE
Temporarily don't show the payments notification badge at all

### PR DESCRIPTION
**Pull request by becdetat**
Temporarily helps with https://github.com/automattic/woocommerce-payments/issues/2071

#### Changes proposed in this Pull Request

This change just doesn't run the code that adds the notification badge at all. Further work will be needed to show the badge after 7 days as specified in https://github.com/automattic/woocommerce-payments/issues/2071 (which should be done in the next version of WooCommerce Payments).

There's not a lot to test since it essentially just skips the code path that conditionally adds the badge. You can get the site in a state where the badge would normally be shown and confirm that the badge is not shown.

- [-] Added changelog entry (or does not apply)
- [-] Covered with tests (or have a good reason not to test in description ☝️)
- [-] Tested on mobile (or does not apply)

### CODE REVIEW

**Review by ilyasfoo — APPROVED** [review]
I think PHP static analyzer is smart enough to see the `true` will never be `false` and we're not wasting CPU cycles here even 😆 

LGTM!

**Comment by becdetat** [comment]
@ilyasfoo cool, unfortunately I had to mangle it a bit so the linter didn't pick it up

**Comment by becdetat** [comment]
@ilyasfoo I updated from `develop` and PHP unit tests stopped working - turned out unit tests covering this area had been added. I've temporarily disabled this in this PR too. Can you have another look?

**Comment by ilyasfoo** [comment]
@becdetat Ah, I forgot about the unit tests as well. LGTM!

**Pull request merged**
