### PR TITLE
Use Docker container for running Playwright e2e tests locally to make visual comparisons more robust

### PR DESCRIPTION
**Pull request by Jinksi**
#### Changes proposed in this Pull Request

Based on #7671 – this PR changes the commands for running Playwright locally (`npm run test:e2e-pw`) to now use the official Playwright Docker container.

This means visual comparison tests are generated from a Linux container when running locally on macOS, ensuring consistent font-rendering.

> [!IMPORTANT]  
> This PR changes the e2e client's `wp-config.php` to make the WP hostname dynamic, which is necessary for Playwright to access the e2e client WP site with the URL `host.docker.internal`.

#### Testing instructions

* Test Playwright headless mode with `npm run test:e2e-pw`
* Test Playwright UI mode with `npm run test:e2e-pw-ui`
* Ensure existing e2e Puppeteer tests are not impacted. I've run the e2e tests workflow against this branch [here](https://github.com/Automattic/woocommerce-payments/actions/runs/7840551041)

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. **N/A, merging to feature branch**
- [x] Covered with tests
- [x] Tested on mobile **N/A**

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8160` or branch name `try/playwright-e2e-tests-docker-local` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=try/playwright-e2e-tests-docker-local) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: fe9de6637c19c677c979f656a027d0819d539bd1
- Build time: 2024-02-09 05:58:20 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by Jinksi** [comment]
@ismaeldcom requesting your review to see what you think of this approach before merging into #7671 🙏

**Review by ismaeldcom — APPROVED** [review]
Impressive work! I was expecting the experience to be affected by adding Docker to the mix, but your solution works flawlessly 🎉 

Tested both Playwright and Puppeteer, working without issues.

**Comment by Jinksi** [comment]
@achyuthajoy I noticed you self-requested a review of – FYI this PR will be merged into the feature branch/PR #7671.

If you're still interested, would you prefer to review #7671 after I merge? FWIW I intended to request a Harmony review after merging this into it.

**Comment by achyuthajoy** [comment]
@Jinksi Sure. That works 👍

**Pull request merged**
