### PR TITLE
Update phpcs and related sniffs

### PR DESCRIPTION
**Pull request by reykjalin**
## Changes proposed in this Pull Request

* Update the WooCommerce and Slevomat PHPCS sniffs so we can update PHPCS itself.
* Update PHPCS so it can be run via PHP 8.1.

#### Testing instructions

> [!NOTE]
> There are currently _way more issues_ reported after the update. Not sure which ones are false positives, which can be silenced, and which ones we should fix.

1. Run `npm run lint:php` in `develop` and make a note of the issues reported (there should be none).
    - If you're already running PHP v8.1 you may have to run this using something like `/opt/homebrew/opt/php@7.4/bin/php ./vendor/bin/phpcs --standard=phpcs.xml.dist $(git ls-files | grep .php$)`
3. Checkout this branch and make sure you run `composer install`.
4. Run `npm run lint:php` and make sure you see the same issues reported as in `develop`.

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8415` or branch name `tweak/update-phpcs-composer-dependencies` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=tweak/update-phpcs-composer-dependencies) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 13857bd9c4e3c50bcb847733ed845ff4e1d38429
- Build time: 2024-03-22 18:27:22 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by reykjalin** [comment]
These are the rules that have issues reported after updating the sniffs:

| Rule | Fixed | Ignored | Commit | Comment|
|:---|:---:|:---:|:---:|:---:|
| "Generic.CodeAnalysis.EmptyPHPStatement.SemicolonWithoutCodeDetected" | x | | 3671304be6697a4b69cdf67525a98840585176e0 | Should've been caught before |
| "Generic.CodeAnalysis.UnusedFunctionParameter.Found" | | | | https://github.com/Automattic/woocommerce-payments/issues/8436 |
| "Generic.CodeAnalysis.UnusedFunctionParameter.FoundAfterLastUsed" | | | | https://github.com/Automattic/woocommerce-payments/issues/8436 |
| "Generic.WhiteSpace.IncrementDecrementSpacing.SpaceAfterIncrement" | x | | 3c95b0509f38ae27b7e3880bea03dafa036e993f | Should've been caught before |
| "Generic.WhiteSpace.SpreadOperatorSpacingAfter.TooMuchSpace" | x | | 5d16a92571f07a96737fcd354d4810e627aa5977 | Should've been caught before |
| "Modernize.FunctionCalls.Dirname.FileConstant" | x | | ec86e081774b11792a5e6517d9f284e5c27f19a8 | Should've been caught before |
| "PSR12.Functions.ReturnTypeDeclaration.SpaceBeforeColon" | x | | 5b650967d2c4f7e94944df00db1ddf20e2b42861 and b580e91db6e695aa3094595c8fea7e1ce537d2f2 | Should've been caught before |
| "PSR12.Functions.ReturnTypeDeclaration.SpaceBeforeReturnType" | x | | 5b650967d2c4f7e94944df00db1ddf20e2b42861 | Should've been caught before |
| "PSR12.Traits.UseDeclaration.MultipleImport" | x | | 47890f3bf1392a4039c6c2dc52c406909458c39a | Should've been caught before |
| "PSR2.Classes.ClassDeclaration.CloseBraceAfterBody" | x | | ea4e19ff88137d45063bd5affcbb6e21ce3e52fd | Should've been caught before |
| "PSR2.Files.EndFileNewline.TooMany" | x | | 0c288f593de22074c5c705f51041bfb6213572f3 and 985d05905e884a3babaa746198fea40064c43adc | Should've been caught before |
| "PSR2.Methods.FunctionClosingBrace.SpacingBeforeClose" | x | | 5d520f3fede345f045e41d8bb919ddf59cd5d929 | Should've been caught before |
| "Squiz.Functions.MultiLineFunctionDeclaration.ContentAfterBrace" | x | | b9170fe9870bade069015252961d69e40b88bafa | Should've been caught before |
| "Squiz.Functions.MultiLineFunctionDeclaration.Indent" | x | | 6343265febffc88f9d7470a423b9829e18b9482f | Should've been caught before |
| "Squiz.Functions.MultiLineFunctionDeclaration.OneParamPerLine" | x | | 8ac694e814dc79830018ecb5cf9170d1f3058ebe | Should've been caught before |
| "Squiz.Functions.MultiLineFunctionDeclaration.SpaceAfterFunction" | x | | da7ed2532fcaf948ef2bdf508a1808a66b0c9cb5 | Consistent with current code style |
| "Universal.Arrays.DisallowShortArraySyntax.Found" | | x | a4a2d40dc2165572cd3cf0ed6ca9820f7240ab9c | We were already ignoring this rule, but it was changed from `Generic.Arrays.…` to `Universal.Arrays.…` |
| "Universal.CodeAnalysis.ConstructorDestructorReturn.ReturnValueFound" | x | | 1e7850a61a231d19a76560fc5ed2ff59160c4965 | Constructors can't return values |
| "Universal.CodeAnalysis.NoEchoSprintf.Found" | x | | 393ba5e2b5e85f5ff04fcf71cb43ace009e6ba9e | Should've been caught before |
| "Universal.ControlStructures.DisallowLonelyIf.Found" | x | | 62ba856d2442399143fefda35ec8c8f25e41d57e | Should've been caught before |
| "Universal.Files.SeparateFunctionsFromOO.Mixed" | | x | 7f9455e120e6a9de67aec479c0ad9376dad4fd3f | The issue was only in test files, which I think is warranted in the cases reported. Ignored this rule for test files. |
| "Universal.NamingConventions.NoReservedKeywordParameterNames.arrayFound" | | | | https://github.com/Automattic/woocommerce-payments/issues/8438 |
| "Universal.NamingConventions.NoReservedKeywordParameterNames.boolFound" | | | | https://github.com/Automattic/woocommerce-payments/issues/8438 |
| "Universal.NamingConventions.NoReservedKeywordParameterNames.classFound" | | | | https://github.com/Automattic/woocommerce-payments/issues/8438 |
| "Universal.NamingConventions.NoReservedKeywordParameterNames.defaultFound" | | | | https://github.com/Automattic/woocommerce-payments/issues/8438 |
| "Universal.NamingConventions.NoReservedKeywordParameterNames.elseFound" | | | | https://github.com/Automattic/woocommerce-payments/issues/8438 |
| "Universal.NamingConventions.NoReservedKeywordParameterNames.functionFound" | | | | https://github.com/Automattic/woocommerce-payments/issues/8438 |
| "Universal.NamingConventions.NoReservedKeywordParameterNames.matchFound" | | | | https://github.com/Automattic/woocommerce-payments/issues/8438 |
| "Universal.NamingConventions.NoReservedKeywordParameterNames.objectFound" | | | | https://github.com/Automattic/woocommerce-payments/issues/8438 |
| "Universal.NamingConventions.NoReservedKeywordParameterNames.returnFound" | | | | https://github.com/Automattic/woocommerce-payments/issues/8438 |
| "Universal.NamingConventions.NoReservedKeywordParameterNames.stringFound" | | | | https://github.com/Automattic/woocommerce-payments/issues/8438 |
| "Universal.Operators.DisallowStandalonePostIncrementDecrement.PostIncrementFound" | x | | b079925fa32987680ed1037b202d6d27a9d07627 | Seems logical to follow common styles here |
| "Universal.UseStatements.NoLeadingBackslash.LeadingBackslashFound" | x | | 151c73a86949135e9bc0d276e0662fcaff6c141b | Should've been caught before |
| "WooCommerce.Commenting.CommentHooks.HookCommentWrongStyle" | | | | https://github.com/Automattic/woocommerce-payments/issues/8437 |
| "WooCommerce.Commenting.CommentHooks.MissingHookComment" | | | | https://github.com/Automattic/woocommerce-payments/issues/8437 |
| "WooCommerce.Commenting.CommentHooks.MissingSinceComment" | | | | https://github.com/Automattic/woocommerce-payments/issues/8437 |
| "WordPress.Security.EscapeOutput.ExceptionNotEscaped" | | | | https://github.com/Automattic/woocommerce-payments/issues/8434 |
| "WordPress.Security.EscapeOutput.OutputNotEscaped" | | | | https://github.com/Automattic/woocommerce-payments/issues/8434 |
| "WordPress.Security.ValidatedSanitizedInput.InputNotValidated" | | | | https://github.com/Automattic/woocommerce-payments/issues/8434 |
| "WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents" | | | | https://github.com/Automattic/woocommerce-payments/issues/8435 |
| "WordPress.WP.AlternativeFunctions.file_system_operations_touch" | | | | https://github.com/Automattic/woocommerce-payments/issues/8435 |
| "WordPress.WP.AlternativeFunctions.unlink_unlink" | | | | https://github.com/Automattic/woocommerce-payments/issues/8435 |
| "WordPress.WP.Capabilities.Unknown" | x | | 60140b06ee8aef290a986b090ece8669b8b0b859 | Added custom capabilities to `phpcs.xml.dist` |

And some leftovers fixed in b6301d62a0ad4283199e18ea98d3ea1f71f7be01.

So those are all rules we have to make a decision on.

I found these by writing the phpcs report to json and using `jq` to find the `source` of the issues reported:

```sh
./vendor/bin/phpcs --standard=phpcs.xml.dist (git ls-files | grep '.php$') --report=json > issues.json
vi issues.json # And remove the empty lines and PHPCS report
cat issues.json | jq '.. |."source"? | select(. != null )' | sort | uniq
```

**Comment by reykjalin** [comment]
I've been working through the list but it's taking a bit of time. I've settled on trying to use `phpcbf` as much as possible in a process that looks like this:

1. Pick a rule, e.g. `PSR12.Functions.ReturnTypeDeclaration.SpaceBeforeColon`.
2. Run PHPCS for that class of rules:

```sh
./vendor/bin/phpcs --standard=phpcs.xml.dist $(git ls-files | grep '.php$') --sniffs='PSR12.Functions.ReturnTypeDeclaration'
```

3. If it makes sense to fix them, and auto-fix is available, run `phpcbf` to auto-fix:

```sh
./vendor/bin/phpcbf --standard=phpcs.xml.dist $(git ls-files | grep '.php$') --sniffs='PSR12.Functions.ReturnTypeDeclaration'
```

4. Commit with a commit message that explains the change and update my previous comment.

***

@bborman22 this is taking longer than it's expected, but I think it's important that we get this done because:

1. PHPCS crashes under PHP 8.1 without these updates, and general PHP 8.1 usage is imminent due to the WPCOM migration.
2. There are some legitimate style inconsistencies caught here.
3. There are some (potentially) legitimate _issues_ caught here, such as (maybe?) unescaped output, confusing function parameter names (`$object`, `$array`, etc.), and more.

The longer this drags the harder it will be to merge due to the amount of files this touches. The things we can't auto-fix via `phpcbf` we could potentially save for a different PR or add ignores for since they won't be reported unless someone is changing the files containing those issues.

Note that all of these issues appeared _after_ I updated the sniffs and PHPCS, they were not present before.

***

@ricardo I've already seen some things that will probably need to discuss:

1. I think the `Universal.NamingConventions.NoReservedKeywordParameterNames.*` reports point to a legitimate issue, but I suspect these are all part of filters. Maybe we can just ignore this?
2. Same for `Generic.CodeAnalysis.UnusedFunctionParameter.*`. Maybe we can ignore this?

Probably some others similar to this, or maybe ones we have to fix, but this is as far as I've gotten today.

**Review by asumaran — APPROVED** [review]
PHP lint works well with PHP 8.1 now. While I see a lot of warnings and errors, I think it's fine to merge and address the rest separately.

**Comment by reykjalin** [comment]
Awesome! I just merged from `develop` and fixed the conflict (which introduced no new linting issues that can be auto-fixed AFAICT after running `./vendor/bin/phpcs --standard=phpcs.xml.dist $(git ls-files | grep '.php$') | grep '\[x\]'`).

I'll wait for tests to pass and add a changelog entry before I merge.

**Pull request merged**
