### PR TITLE
Subscribe extension to automated translation updates

### LINKED ISSUE #1558: Add filter to get translations from GlotPress
```
add_filter( 'woocommerce_translations_updates_for_{plugin-slug}', '__return_true' )
```

Reference: paJDYF-19f-p2#comment-5172

### PR DESCRIPTION
**Pull request by diegocurbelo**
Fixes #1558

#### Changes proposed in this Pull Request

This PR subscribes the extension to the WooCommerce automated translations updates, it just adds a filter:
```php
 add_filter( 'woocommerce_translations_updates_for_woocommerce-payments', '__return_true' );
```

The heavy lifting of fetching and updating the translations is taken care by WooCommerce Core.

#### Testing instructions

- Change the site language to one that has a [language pack available](https://translate.wordpress.com/projects/woocommerce/woocommerce-payments/)
- Go to `Dashboard > Updates`, at the bottom of the page click: `Update Translations`

- A breakpoint can be added here to test that the filter is called:
https://github.com/woocommerce/woocommerce/blob/a54df37363c881ef1ba855c5fce470caf67e7633/includes/admin/helper/class-wc-helper-updater.php#L213
```php
return apply_filters( 'woocommerce_translations_updates_for_' . $plugins[ $plugin ]['slug'], false );
```

-------------------

- [ ] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

### CODE REVIEW

**Review by ricardo — COMMENTED** [review]
Code LGTM 👍 

Do you have testing instructions? I don't know how to test this and couldn't verify the translation.

Any idea why WooCommerce Bookings and WooCommerce Subscriptions use an action instead of a filter?
- https://github.com/woocommerce/woocommerce-bookings/blob/de123ce559f91c32b5b730e58ee9a91a8612c30f/woocommerce-bookings.php#L393
- https://github.com/woocommerce/woocommerce-subscriptions/blob/ee549e3941cd6b52cafe16b80ad723639f4a99f4/woocommerce-subscriptions.php#L57

**Comment by diegocurbelo** [comment]
> Code LGTM 👍
> 
> Do you have testing instructions? I don't know how to test this and couldn't verify the translation.

I updated the testing instructions

> 
> Any idea why WooCommerce Bookings and WooCommerce Subscriptions use an action instead of a filter?
> 
> * https://github.com/woocommerce/woocommerce-bookings/blob/de123ce559f91c32b5b730e58ee9a91a8612c30f/woocommerce-bookings.php#L393
> * https://github.com/woocommerce/woocommerce-subscriptions/blob/ee549e3941cd6b52cafe16b80ad723639f4a99f4/woocommerce-subscriptions.php#L57

Not sure... the WC Core code calls `apply_filters(...)`:
- https://github.com/woocommerce/woocommerce/blob/a54df37363c881ef1ba855c5fce470caf67e7633/includes/admin/helper/class-wc-helper-updater.php#L213

**Comment by dechov** [comment]
Cc: contributors of those `woocommerce_translations_updates_for_{$plugin_name}` actions @roykho @budzanowski

**Comment by roykho** [comment]
Good catch, I think it may have been a copy/paste error. They should be filters.

**Review by ricardo — APPROVED** [review]
LGTM 🚢

**Pull request merged**
