### PR TITLE
Update Dev/Sandbox Mode Choice Design

### LINKED ISSUE #7731: The new onboarding mode selection screen should have a more prominent "live account" mode choice
### Description
Following up on this discussion with Design paJDYF-bnR-p2#comment-21892 we'll revisit the onboarding flow choices to give more weight to the live payments option and reduce it for the builder mode option.

image

### PR DESCRIPTION
**Pull request by dmallory42**
Fixes #7731

#### Changes proposed in this Pull Request

* Define new component, OnboardingCard to represent a card containing content on the onboarding flow.
* Remove RadioCard component which is no longer used.
* Update to match latest designs.

#### Screenshots

Screenshot 2024-01-10 at 11 53 19

Should match the design as laid out here: paJDYF-bGl-p2
 
Note: I haven't removed the subheading on the design yet as I wanted to double check this first.

#### Testing instructions

* Disconnect or delete your previous account in the DB so WooPayments thinks there is no account connected.
* Initiate a new onboarding flow.
* Verify that the new design for the first page of the flow looks as expected.
* Start the flow using the "live" option (if you have sandbox mode enabled it will still create a test account) and go through the flow and verify that you can create an account.
* Start the flow using the sandbox option and verify you get redirected to the Stripe test KYC and you can create an account.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8002` or branch name `dev/7731-update-dev-mode-choice` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=dev/7731-update-dev-mode-choice) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 99ecc69fe244305f9c3fb184d92437f683f58981
- Build time: 2024-01-19 14:52:04 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by dmallory42** [comment]
Hi @elizaan36! 👋  Would it be possible to get a review on the design for the updates to the first page of the onboarding flow to make sure it all looks okay? You should be able to test by [spinning up a new JN site from this PR](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=dev/7731-update-dev-mode-choice) and starting an onboarding. 

Thanks!

**Comment by elizaan36** [comment]
hey @dmallory42, I'm wondering why does this notice appear before the user has made a selection.

image

I think this would be very confusing for the new user because they'll wonder if they did something wrong.

In terms of the design, I proposed an update to this screen to give merchants some context before launching into the Jetpack connection flow. I shared this in a couple places but haven't heard any feedback.

Screenshot 2024-01-11 at 9 02 45 PM

Would it make sense to take a step back and update this screen as part of the initiative to provide more context for Jetpack?

There's also a timing consideration with moving the TOS copy. We need to create an issue to update the Woo Home task screen (in core and Woo Express). We're removing the incentive and TOS copy from the task, and not adding any marketing copy to replace it.

image

I think we should time both updates so the Home task is a fast follow as double TOS copy may impact conversion.

cc @vladolaru

**Comment by dmallory42** [comment]
Hi @elizaan36! 👋 

> hey @dmallory42, I'm wondering why does this notice appear before the user has made a selection.
image

image

This is unrelated to these changes, it was added in this issue: https://github.com/Automattic/woocommerce-payments/issues/6429 

The context to it is that it will only appear if Dev Mode is activated on a plugin-wide level (usually this would either be by installing the Dev Tools plugin or adding a special constant to the `wp-config.php`) - so this is something that would not be seen by 99% of users. The purpose is to warn that a test account will be created regardless of which option is selected - but as I mentioned, this is a pretty niche case that won't affect live accounts, only those who are testing the plugin like devs (Dev Tools is included when a JN site is spun up for testing).

> In terms of the design, I proposed an update to this screen to give merchants some context before launching into the Jetpack connection flow. I shared this in a couple places but haven't heard any feedback.

Apologies for crossed wires here - my understanding was that the design proposed in paJDYF-bGl-p2 was what we were going ahead with. I remember seeing your comment where you added an update to this screen but I didn't realise it was intended to supersede this design - I thought it was an ongoing discussion about future improvements to the flow as that would likely involve more changes such as replacing the Connect screen.

> Would it make sense to take a step back and update this screen as part of the initiative to provide more context for Jetpack?

We can definitely do that if you'd like - my feeling is that this design is improving on what we had previously because it de-emphasises the sandbox option, but we can either proceed with what we have here and then increment on it, or take a step back and implement the newer design. Let me know how you want to proceed! 

> There's also a timing consideration with moving the TOS copy. We need to create an issue to update the Woo Home task screen (in core and Woo Express). We're removing the incentive and TOS copy from the task, and not adding any marketing copy to replace it.

I think (but let me know if I misunderstood) that this has already been covered by @ismaeldcom's PR here: https://github.com/woocommerce/woocommerce/pull/43365

**Comment by vladolaru** [comment]
@dmallory42 @elizaan36 In light of the many discussions and proposals ( paJDYF-bWH-p2 ) around improving our onboarding flows through running experiments, I've decided to unblock this issue as we have the Woo core ToS changes timings to consider. 

Setting up the two variations for the experiments will take time and we need to keep up with core on the ToS moving to the MOX (part of this issue).

**Review by ismaeldcom — APPROVED** [review]
Thanks for working on this and accepting my suggestions 🙂 

There are a couple of style differences between the design and the implementation, all of them related with spacing and sizes. But knowing that it is consistent with the previous design, and that we will iterate on this soon, I think it's okay to proceed.

**Comment by elizaan36** [comment]
I see this is already merged but I was coming here to say that it makes sense to move forward with the proposed changes as-is, since finalizing the more holistic flow / experiment will take more time.

**Comment by elizaan36** [comment]
> we have the Woo core ToS changes timings to consider

@vladolaru Is there an issue for the task list changes?

**Comment by elizaan36** [comment]
Ah edit, I see that PR #43365 has already been merged as well.

**Pull request merged**
