### PR TITLE
Update the Fraud & Risk tools welcome tour copy

### LINKED ISSUE #6155: Update fraud & risk tools tour copy
Update the Fraud & Risk tools tour copy to match the latest changes from the design.

### Additional context

- WIM5w2Y10SCNBFdMLSVftj-fi-3696_269486

### PR DESCRIPTION
**Pull request by eduardoumpierre**
Fixes #6155

#### Changes proposed in this Pull Request

Update the Fraud & Risk tools welcome tour copy to match the latest design changes.

#### Testing instructions

* The unit tests should be passing
* Run `npm run wp option add wcpay_fraud_protection_settings_active 1` to enable the feature flag
* Run `npm run wp option delete wcpay_fraud_protection_welcome_tour_dismissed` to reset the welcome tour flag
* The component layout should match the Figma design ([WIM5w2Y10SCNBFdMLSVftj-fi-3696_268417](WIM5w2Y10SCNBFdMLSVftj-fi-3696_269486))

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6156` or branch name `update/6155-tour-copy` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=update/6155-tour-copy) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 67d60ee5cd2a922b61bf17028bb21b413041e49d
- Build time: 2023-05-11 09:36:31 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by allie500 — COMMENTED** [review]
Thanks for working on these design updates!

The link to the Figma design in the PR description is broken. I checked with @elizaan36 to confirm that the current Figma design is here: 
WIM5w2Y10SCNBFdMLSVftj-fi-3696_269486

I found a few small discrepancies while reviewing the tour cards. I don't know if they are necessarily blockers, but I've shared them just in case. My observations below are based on the above linked set of Figma designs. 

Tour card 2 on Figma shows a 'Previous' button, while the PR branch tour card 2 uses 'Back' button.

Figma design - Tour card 2:
WIM5w2Y10SCNBFdMLSVftj-fi-3696_269619

PR branch - Tour card 2:
Screenshot on 2023-05-01 at 10_16_45

Tour card 3 is a bit off. In the Figma design the first line of text includes the word 'each' before the line break while the version on this PR branch, the line breaks before the word 'each'. Also, the Figma design has the tour card arrow pointing at the Advanced radio from the right side, while on the PR branch card the arrow is pointed from the bottom. Lastly, like card 2 the Figma design uses 'Previous' and the PR branch card uses 'Back'.

Figma design - Tour card 3:
WIM5w2Y10SCNBFdMLSVftj-fi-3696_269752

PR branch - Tour card 3:
Screenshot on 2023-05-01 at 10_19_16

Tour card 4 has the 'back' button instead of the 'previous' button like the previous two cards. Its primary button text is 'Done' while the Figma design it is 'Got it'.

Figma design - Tour card 4:
WIM5w2Y10SCNBFdMLSVftj-fi-3696_269885

PR branch - Tour card 4:
Screenshot on 2023-05-01 at 10_20_24

Everything works as expected, those are the only minor differences that I found.

**Comment by eduardoumpierre** [comment]
> Tour card 2 on Figma shows a 'Previous' button, while the PR branch tour card 2 uses 'Back' button.

This is a [limitation on the component](https://github.com/woocommerce/woocommerce/blob/trunk/packages/js/components/src/tour-kit/components/step-navigation.tsx#L48) as it doesn't allow custom text. @elizaan36 would it be ok if we continue using "Back" instead of "Previous"?

> In the Figma design the first line of text includes the word 'each' before the line break while the version on this PR branch, the line breaks before the word 'each'.

I don't see it as an issue, the step items have the same width as the design, but I think the font from Figma is slightly different, so we have this discrepancy.

> Also, the Figma design has the tour card arrow pointing at the Advanced radio from the right side, while on the PR branch card the arrow is pointed from the bottom.

I tried to set a different preferred position for each step, but due to how the `TourKit` component was designed, it's not possible. I followed the [PopperJS documentation](https://popper.js.org/docs/v2/modifiers/flip/) and was successful to define a preferred placement, but then the flip behavior stopped working, so I decided to keep it as it is.

> Tour card 4 [...] Its primary button text is 'Done' while the Figma design it is 'Got it'.

It was updated on [1a6bc78](https://github.com/Automattic/woocommerce-payments/pull/6156/commits/1a6bc7839f2cef176b3bb1523c7a6a1b2178eab3).

Thanks for the review @allie500!

**Comment by elizaan36** [comment]
>  @elizaan36 would it be ok if we continue using "Back" instead of "Previous"?

Yes!

**Review by allie500 — APPROVED** [review]
Thanks for addressing my previous feedback. All your responses make sense. I also see the updated 'Got it' button on the last step. Code changes look good and the screen consistently auto-scrolls to the fraud protection section when the first step of the tour loads. Unit tests are passing. 

LGTM :shipit:

**Pull request merged**
