### PR TITLE
Multicurrency: Do not modify deposit percentage for display.

### PR DESCRIPTION
**Pull request by peterwilsoncc**
Fixes: WooCommerce Deposits #\506
Supersedes PR #6930

#### Changes proposed in this Pull Request

As reported in  WooCommerce Deposits #\506, enabling multi-currency modifies the display of percentage deposits.

The issue comes from `WooCommerceDeposits::modify_cart_item_deposit_amount_meta()` attempting to convert a percentage number although it were currency.

A store with a USD base selling a product with a 20% deposit results in the following displaying for select currencies:

AUD: 31%
CAD: 27%
INR: 1656%

I haven't written any tests as there are existing tests for multicurrency that are passing but as the plugin is using mocks the tests are passing as they're failing to account for the various filters running in this and deposits.

This is a sibling PR for https://github.com/woocommerce/woocommerce-deposits/pull/544

**Product page**
Screen Shot 2023-09-21 at 2 18 54 pm

**Cart page**

Screen Shot 2023-09-21 at 2 19 31 pm

**Checkout page**

Screen Shot 2023-09-21 at 2 20 21 pm

**Account > Order page**

Screen Shot 2023-09-21 at 2 20 58 pm

#### Testing instructions

1. Configure Multi-currency Payments: using USD (default) and INR will best demonstrate the bug
2. Check out the Deposits extension branch in https://github.com/woocommerce/woocommerce-deposits/pull/544
3. Build the Deposits extension following the instructions in the readme.
4. Configure and publish product to accept deposits:
    * Enable Deposits: Yes - Deposits are optional
    * Deposit Type:: percentage
    * Deposit Amount: 20
    * Default Deposit Selected Type: Pay Deposit
5. View the product on the front end
6. Switch to USD if required, observe the deposit amount is displayed as 20%
7. Switch the currency from USD to INR
8. On this branch the deposit amount should remain 20%, on trunk the amount is significantly over 20%

*

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by vikrampm1** [comment]
@Mayisha checking in here to see if you had a chance to review.

**Comment by Mayisha** [comment]
@vikrampm1 I have reviewed both the PRs and the issue I previously found is not happening anymore. I will go ahead and approve the PRs.

**Review by Mayisha — APPROVED** [review]
Along with the fix made in the Deposits plugin, the changes here seem to fix the deposit percentage issue for a percentage deposit set in individual products.

**Comment by jeffpaul** [comment]
@Mayisha please let us know if this gets milestoned into a plugin release so we can coordinate accordingly in the Deposits extension... thanks!

**Comment by Mayisha** [comment]
@jeffpaul We are planning to ship this in the next release which is scheduled on Nov 01.

**Pull request merged**
