### PR TITLE
Bump WC minimum supported version for 4.5.0 release

### PR DESCRIPTION
**Pull request by jbordonado**
#### Changes proposed in this Pull Request

- Minimum required WooCommerce version bumped from 5.8 to 6.0 (increasing by 2 versions with each release).
- Updated the L-2 version of WooCommerce to 6.5 since WooCommerce 6.7 will be available as of July 12th.
- WC tested up to bumped to 6.7.0
- Verify that [E2E tests are passing](https://github.com/Automattic/woocommerce-payments/actions/runs/2649859702).

#### Testing instructions
- Verify that wherever we used 5.8 as a minimum before, we now use 6.0.
- Verify that version numbers line up with the [WooCommerce release version numbers](https://developer.woocommerce.com/releases/).
-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Review by achyuthajoy — APPROVED** [review]
LGTM 🚢

**Comment by achyuthajoy** [comment]
@jbordonado Please confirm that E2E tests are clear before merging - https://github.com/Automattic/woocommerce-payments/runs/7281501171?check_suite_focus=true

**Comment by jbordonado** [comment]
> @jbordonado Please confirm that E2E tests are clear before merging - https://github.com/Automattic/woocommerce-payments/runs/7281501171?check_suite_focus=true

Thanks for checking.
There was an issue on most of the E2E tests following a merge that changed the currency format this morning.
It was fixed this afternoon, and all the E2E tests are now passing.

FYI, I'll merge this PR as soon as the announcement for Woo 6.7.0 release is made tomorrow.

**Comment by htdat** [comment]
I think we should bump WordPress core minimum from 5.7 to 5.8 too?
The current latest version of WP core is 6.0.

**Review by achyuthajoy — COMMENTED** [review]
@jbordonado The changes look good to me.

> I also noticed I missed updating the coverage.yml and php-lint-test.yml files with the new Woo version.

The change to `latest` looks good. However, let wait for a confirmation based on the discussion here - p1657613445107929-slack-C01BPL3ALGP, and hence I haven't approved the PR.

> PHP lint and PHP testing jobs then started to fail because the Woo L-2 version (6.5.1) requires at least PHP 7.2: Warning: The package could not be installed. "The PHP version on your server is 7.1.33-46+ubuntu18.04.1+deb.sury.org+1, however the uploaded plugin requires 7.2.". So I updated the PHP lint job to use PHP 7.2 and I removed PHP 7.1 from the matrix in PHP testing job. Let me know if this is also OK.

This is fine since WC requires a higher version of PHP.

**Pull request merged**
