### PR TITLE
Change payment method title for In Person Card Payment

### LINKED ISSUE #1757: [Mobile Payments] Orders paid for by in-person / card present payments show "via Pay on Delivery"
Orders paid  for by in-person / card present payments show "via Pay on Delivery"

Screen Shot 2021-05-10 at 5 42 27 PM

Could we change that to In-Person Card Payment or at least "via Credit Card" like we do for other WCPay orders?

Screen Shot 2021-05-10 at 5 44 13 PM

### PR DESCRIPTION
**Pull request by mgascam**
Fixes #1757 

#### Changes proposed in this Pull Request

The orders paid for by in-person / card present payments show "via WooCommerce Payments" in the order details page.
 
Screen Shot 2021-11-04 at 18 03 40

This PR replaces the text "via WooCommerce Payments" with "via In-Person Card Payment" for this type of orders.

Screen Shot 2021-11-04 at 18 09 10

#### Testing instructions
(inspired by testing instructions in this [PR](https://github.com/Automattic/woocommerce-payments/pull/1689))

* Create an order with Cash on Delivery as payment method. You can also create the order in wp-admin. Note the order id.
* In Stripe dashboard, create a new payment with manual capture (More options > Capture funds later). Note the intent ID
*[ Change the permission_callback on the new endpoint](https://github.com/Automattic/woocommerce-payments/blob/236e39b4d4f4b7efdd9e36121b19a6861c6ded53/includes/admin/class-wc-rest-payments-orders-controller.php#L61) to '__return_true'. You need this to be able to make the request to the endpoint in next step. 
```diff
-  'permission_callback' => [ $this, 'check_permission' ],
+  'permission_callback' => '__return_true',
```
* Capture the payment making a request to the `capture_terminal_payment` endpoint. For instance, `curl -i -X POST <YOUR_SITE_URL>/wp-json/wc/v3/payments/orders/<ORDER_ID>/capture_terminal_payment --data "payment_intent_id=<INTENT_ID>"`
* The request should succeed. You can go to the details page of the order and check that the payment information is updated, as well as the "via In-Person Card Payment" text (please check screenshot above for reference)

-------------------

- [X] Added changelog entry (or does not apply)
- [X] Covered with tests (or have a good reason not to test in description ☝️)
- [X] Tested on mobile (or does not apply)

**Post merge**

- [ ] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply)

### CODE REVIEW

**Comment by mgascam** [comment]
Hi @allendav I thought that maybe you'd like to review this one, since you reported the issue. Thanks!

**Review by dmvrtx — APPROVED** [review]
Looks good to me! 🚢

**Comment by kalessil** [comment]
@mgascam: can we use "WooCommerce In-Person Payments" here, so it's aligned with https://woocommerce.com/in-person-payments/?

**Comment by mgascam** [comment]
> @mgascam: can we use "WooCommerce In-Person Payments" here, so it's aligned with https://woocommerce.com/in-person-payments/?

Yes, makes sense. The issue says we should change it for "In-Person Card Payment", but I like this better. I asked if it is okay to change it.

**Comment by mgascam** [comment]
@kalessil I got confirmation that we should use "WooCommerce In-Person Payments".

**Comment by kalessil** [comment]
@mgascam, great !

**Comment by mgascam** [comment]
This is how it looks like after changing the text:
Screen Shot 2021-11-08 at 16 51 29

**Review by kalessil — APPROVED** [review]
LGTM, :shipit:

**Pull request merged**
