### PR TITLE
Fixes issue with QIT authentication parsing

### LINKED ISSUE #9750: QIT authentication fails if password contains spaces
### Describe the bug

When trying to set up QIT (see: PaJDYF-6n7-p2), I noticed that we pass the password string (which is set in an env file) in via the `common.sh` script without `"` quoting it. This means, if the password contains a space, it gets parsed as a new word rather than the same string, causing the script to fail.

### To Reproduce

1. On `develop`, use a password with a space in it in the `local.env` file for the `QIT_PASSWORD` variable (it doesn't need to be the correct password to see this error).
2. You should see an error similar to: `  No arguments expected for "partner:add" command, got "<password>".

### PR DESCRIPTION
**Pull request by dmallory42**
Fixes #9750 

#### Prerequisites

Please read the P2 post linked for context on QIT and create the `local.env` file as specified in the instructions.

#### Testing instructions

1. On `develop`, use a password with a space in it in the `local.env` file for the `QIT_PASSWORD` variable (it doesn't need to be the correct password to see this error).
2. Run the command `npm run test:qit-security`
3. You should see an error similar to: `  No arguments expected for "partner:add" command, got "<password>".`
4. Verify that this doesn't happen on this branch. (You can check that the steps on the p2 post linked on this page work as expected).

See: PaJDYF-6n7-p2 
-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9755` or branch name `dev/qit-auth-fix-take-2` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=dev/qit-auth-fix-take-2) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 46b10bb8426700f28aedd58fac24de49e4734ade
- Build time: 2024-12-05 07:46:47 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by oaratovskyi** [comment]
@dmallory42 following the [guide](https://github.com/Automattic/woocommerce-payments/tree/develop/tests/qit#setup-and-running) to set up QIT, I noticed there are `""` in the template itself!
```
# Create `local.env` and supply actual values.
QIT_USER=""
QIT_PASSWORD=""
```

In my case, the QIT thing works because it looks like this:
```
# Create `local.env` and supply actual values.
QIT_USER="user"
QIT_PASSWORD="password with spaces"
```

so, we may not need this improvement, WDYT?

**Comment by dmallory42** [comment]
Hi @oaratovskyi, sorry - only now seeing this comment! 

> so, we may not need this improvement, WDYT?

We still need it, even if you use `""` in the `.env` file, it breaks if there are certain special characters in the password field without this enhancement. You can try it out with the test instruction steps to see the problem. 🙂

**Review by oaratovskyi — APPROVED** [review]
Thanks for explanation @dmallory42 ! It's good to go then :shipit:

**Pull request merged**
