### PR TITLE
Display specific error message instead of a generic one in the checkout block when payments fail

### LINKED ISSUE #3099: Blocks checkout - Uninformative error messages when the non-UPE gateway fails
### Describe the bug

When the non-UPE gateway fails, the displayed message says "Something went wrong. Please contact us to get assistance." instead of the actual error.

### To Reproduce

* Make sure you're using the Blocks checkout
* Make sure UPE is disabled
* Add a product to the cart and proceed to the Blocks checkout

There are several issues that seem to come to this. You can go with any of these:
* Introducing incorrect card details (invalid postcode or CVC). Replicate with the card `4000000000000127`. Reported in #2803
* Using a card that gets declined. Replicate with the card `4000000000000002`. Reported in #1706
* Or probably any other error coming from the gateway processing (we'd have to check)

### Actual behavior

The message "Something went wrong. Please contact us to get assistance" is displayed.

### Screenshots

Generic error message:
image

Credit card form:
image

### Expected behavior

As described in the mentioned issues, I'd expect to read a message about the actual issue that happened instead of a generic one. For example, something like "Your card was declined" or "Your card’s security code is incorrect", as we see in the regular checkout.

### Desktop (please complete the following information):

* OS: macOS
* Browser: chrome
* Version: 94.0.4606.81

### Additional context

For reference and to avoid making the same mistake, the approach on [this other PR](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/4871) is not an option, as explained there. It works fine with UPE, so we could use it as a reference.

### PR DESCRIPTION
**Pull request by a-danae**
Fixes #3099 

#### Changes proposed in this Pull Request

Throw Exceptions with the error message instead of adding error notices when the payment processing fails.

* Remove `wc_add_notice()` for non-UPE payment methods, and for UPE when the limit is reached
* Throw an Exception with the message previously displayed via `wc_add_notice()`

This makes the error message be displayed both in the regular and in the blocks checkout.

This is the generic error that was displayed before
image

#### Testing instructions

For non-UPE errors:
* Make sure you're using the Blocks checkout
* Add 1 or more products to your cart
* Go to the blocks checkout page
* Pay with a card that will be declined, e.g. 4000 0000 0000 0002 or 4000 0000 0000 0127
* At the top of the page, an error message describing the error should be displayed, instead of the generic "Something went wrong. Please contact us to get assistance." one mentioned in the issue.

Error with the card 4000 0000 0000 0127
image

Error with the card 4000 0000 0000 0002
image

For UPE's cards:
* Make sure you're using the Blocks checkout
* Add 1 or more products to your cart
* Go to the blocks checkout page
* Attempt 6 times to pay with a card that will be declined, e.g. 4000 0000 0000 0002. This will reach the limiter's limit
* Instead of the generic error message, you should get "Your payment was not processed"
image

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply)

### CODE REVIEW

**Comment by malithsen** [comment]
Hi @a-danae changes in here so far test well and look good to me. Will have another look when the tests you're working on are ready.

**Comment by a-danae** [comment]
Tests updated 🙂 for the e2e ones to run properly, we'd need [this other PR](https://github.com/Automattic/woocommerce-payments/pull/3277) to be merged.

**Review by malithsen — APPROVED** [review]
Looks good with the adjusted tests :)

**Comment by ricardo** [comment]
@a-danae On the UPE checkout, I'm experiencing two error notices at the same time. I understand this is not related to the PR, but are you experiencing the same issue? Do you happen to know if we have already filed an issue to track this bug?

Error notices displayed twice on UPE checkout

**Review by ricardo — APPROVED** [review]
Re-throwing the exception after catching and logging the error seems like a clever idea. I'm not aware of any cons in doing that, so approving 👍 

LGTM.

**Comment by a-danae** [comment]
Thanks for the review @ricardo!

> but are you experiencing the same issue?

Yess, I've been experiencing it.

> Do you happen to know if we have already filed an issue to track this bug?

I thought I had created one for it but l couldn't find any related issue, so looks like I didn't. I've created it [here](https://github.com/Automattic/woocommerce-payments/issues/3373). Please feel free to update it 🙂 

Updating the typo, solving the conflicts, and proceeding to merge next. Thank you both!

**Pull request merged**
