### PR TITLE
Release branch for 5.1.1

### PR DESCRIPTION
**Pull request by jbordonado**
:warning: Please do not merge the PR from the GitHub interface. :warning:

 Instead, you can use the following command: ` git merge --no-ff release/5.1.1 -m 'Merge release/5.1.1 into trunk' `
```
* Fix - Minor patch fix to cron functionality that does not appear to have front-end ramifications for customers.
```

### CODE REVIEW

**Comment by jbordonado** [comment]
Here is the zip file that will be used to release the 5.1.1 patch: [woocommerce-payments.zip](https://github.com/Automattic/woocommerce-payments/files/10139337/woocommerce-payments.zip)

**Comment by jbordonado** [comment]
Here is the zip file that will be used to release the 5.1.1 patch: [woocommerce-payments.zip](https://github.com/Automattic/woocommerce-payments/files/10139405/woocommerce-payments.zip)

**Review by dwainm — COMMENTED** [review]
Changes look good.

**Comment by dwainm** [comment]
Sorry, this doesn't include the fix.

**Review by dwainm — APPROVED** [review]

**Pull request merged**
