### PR TITLE
Fix stripe.confirmSetup() expected either `elements` or `clientSecret`.

### LINKED ISSUE #3656: [GlobalStep] Error notice triggered "stripe.confirmSetup()" for "Change payment method (card) for an active subscription" on clicking "Change payment method" button when UPE enabled.
## Bug Description:
Error notice triggered "stripe.confirmSetup()" for "Change payment method (card) for an active subscription" on clicking "Change payment method" button when UPE enabled.

## Environment:
Woocommerce Version : WooCommerce  6.1.0 
WooCommerce Payments - 3.6.0-test-3
WordPress version: v5.8.3

PC:
Windows 10
Chrome(Version 97.0.4692.71)
Firefox(Version 96.0.1)
Safari: v14.1.2

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins.
1. Upload and activate  WooCommerce Payments - 3.6.0-test-3 plugin.
1. Click on woocommerce home page.
1. Complete the setup wizaed.
1. Add some products.
1. Go to Payments > Setting and make sure UPE is enabled.
1. Create a subscription product on backend.
1. Go to frontend and purchase a subscription product.
1. Navigate to My account > Subscriptions and open the newly created subscription entry.
1. Click "Change payment" button.
1. Select use a new payment method option.
1. Provide valid credit card details and click "Change payment method" button.
1. Observe that Error notice triggered "stripe.confirmSetup()" for "Change payment method (card) for an active subscription" on clicking "Change payment method" button..

## Actual Result:
Error notice triggered "stripe.confirmSetup()" for "Change payment method (card) for an active subscription" on clicking "Change payment method" button when UPE enabled.

## Expected Result:
Payment method should be successfully updated with success message after clicking "Change payment method" button.

## Screenshot:

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WC Version: 6.1.0
REST API Version: ✔ 6.1.0
WC Blocks Version: ✔ 6.5.1
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.0.3
Log Directory Writable: ✔
WP Version: 5.8.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.52 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.27
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.1.0
WC Database Prefix: wp_
Total Database Size: 7.24MB
Database Data Size: 5.29MB
Database Index Size: 1.95MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.48MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 0.41MB + Index: 0.41MB + Engine InnoDB
wp_posts: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
page: 10
post: 2
product: 26
product_variation: 7
revision: 4
shop_coupon: 1
shop_order: 64
shop_order_refund: 6
shop_subscription: 18

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Query Monitor: by John Blackbourn – 3.8.2
Code Snippets: by Code Snippets Pro – 2.14.3
Companion Plugin: by Osk – 1.21
WooCommerce Payments Dev Tools: by Automattic –
WooCommerce Payments: by Automattic – 3.6.0-test-3
WooCommerce: by Automattic – 6.1.0

### Inactive Plugins (5) ###

Akismet Anti-Spam: by Automattic – 4.2.1
Hello Dolly: by Matt Mullenweg – 1.7.2
Jetpack: by Automattic – 10.5
WooCommerce Blocks: by Automattic – 6.7.1
WooCommerce Subscriptions: by WooCommerce – 3.1.6

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.9.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://autonomous-kinkajou.jurassic.ninja
Subscription Statuses: wc-cancelled: 1
wc-active: 17

WooCommerce Account Connected: ❌ No

### Store Setup ###

Country / State: United States (US) — California

### Subscriptions by Payment Gateway ###

WooCommerce Payments: wc-active: 17
wc-cancelled: 1

### Payment Gateway Support ###

WooCommerce Payments: products
refunds
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions
tokenization
add_payment_method

### WooCommerce Payments ###

Version: 3.6.0-test-3
Connected to WPCOM: Yes
Blog ID: 201865612
Account ID: acct_1KJBW62EtjO2SGtr

### Action Scheduler ###

Canceled: 1
Oldest: 2022-01-18 08:40:37 +0000
Newest: 2022-01-18 08:40:37 +0000

Complete: 351
Oldest: 2022-01-18 07:10:48 +0000
Newest: 2022-01-18 12:09:25 +0000

Pending: 20
Oldest: 2022-01-18 16:38:48 +0000
Newest: 2022-04-18 13:13:37 +0000

### Status report information ###

Generated at: 2022-01-18 15:10:35 +00:00
`

</details>

### PR DESCRIPTION
**Pull request by shendy-a8c**
Fixes #3656

#### Changes proposed in this Pull Request

Pass `elements` instead of `element` to stripe.confirmSetup().

Note: I don't add changelog because this bug isn't present in previous release.

#### Testing instructions

Make sure adding payment methods works.
1. Go to My Account > Payment methods (/my-account/payment-methods/).
2. Click `Add payment method` button.
3. Select `Use a new payment method` and fill in card number `4242424242424242` and valid expiry and cvc.
4. Click `Add payment method` button.
5. Expect a success. With base branch, there should be an error like the screenshot in https://github.com/Automattic/woocommerce-payments/issues/3656.

Make sure changing payment for subscriptions works.
1. Create a subscription product.
2. Purchase that subscription product.
3. Go to My Account > Subscriptions (/my-account/subscriptions/).
4. Select one of the subscriptions.
5. Click `Change payment` button.
6. Select `Use a new payment method` and fill in card number `4242424242424242` and valid expiry and cvc.
7. Click `Change payment method` button.
8. Expect a success. With base branch, there should be an error like the screenshot in https://github.com/Automattic/woocommerce-payments/issues/3656.

-------------------

- [x] Added changelog entries to both `readme.txt` and `changelog.txt` (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) : _Add link here / 'QA Testing Not Applicable'_

### CODE REVIEW

**Comment by shendy-a8c** [comment]
I notice from https://stripe.com/docs/payments/payment-element/upgrade-from-beta that the parameter passed to `confirmPayment()` (and apparently `confirmSetup()` as well) need to be changed from `element` to `elements`.

I'm not too familiar with UPE work, but I also find `confirmPayment()` and `confirmSetup()` in https://github.com/Automattic/woocommerce-payments/blob/develop/client/checkout/blocks/confirm-upe-payment.js. Do we also need to pass `elements` instead of `element` there too? I don't see problem on checkout though and with this PR, problem with changing / adding payment from My account page are fixed, so I'm reluctant to make the change in `confirm-upe-payment.js` without knowing exactly what it does.

**Comment by FangedParakeet** [comment]
Nice catch! I tested this and can confirm that the changes herein have returned functionality to adding and changing payment methods from the account page. 

I think Stripe's new laws decree that the entire Stripe `elements` object must be passed to both ` confirmPayment` and `confirmSetup`, instead of the payment element (`upeElement`). I think this should also apply to the function call inside [`/blocks/confirm-upe-payment.js`](https://github.com/Automattic/woocommerce-payments/blob/develop/client/checkout/blocks/confirm-upe-payment.js). You can confirm that there is something wrong here by trying to complete a Blocks checkout. Currently, the UPE is failing to load in Blocks mode, displaying the following error.

> Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports. Check the render method of `c`.

However, I'm not incredibly familiar with the Blocks checkout and similarly unsure if the `elements` parameter is the only thing missing here that would resolve this error. @shendy-a8c, let me know if you feel like having a stab at amending this within this PR or if you'd like to open a new issue to save the Blocks checkout--if you choose the latter option, I'll gladly approve this PR, as it does resolve the subs issue. Cheers!

**Comment by shendy-a8c** [comment]
Thank you @FangedParakeet for the explanation that `confirm-upe-payment.js` is used for blocks checkout.

> let me know if you feel like having a stab at amending this within this PR or if you'd like to open a new issue to save the Blocks checkout--if you choose the latter option, I'll gladly approve this PR, as it does resolve the subs issue.

Let's do it in a separate issue (I'm creating the issue right now) and PR.

**Review by jessepearson — APPROVED** [review]
LGTM! Thank you for the fix on this :shipit:

**Pull request merged**
