### PR TITLE
Add IE, DK, FI, NO, and SE to Klarna

### PR DESCRIPTION
**Pull request by KarlisJ**
#### Changes proposed in this Pull Request

Add IE, DK, FI, NO, and SE to Klarna payment method.

Additionally adds the related currency support and their limits.

#### Testing instructions

For each new country:
- Onboard merchant in that country
- Make sure you've set the currency in `WooCommerce->settings->general` to domestic currency of that merchant
- Enable Klarna payments
   - Create related fees (https://github.com/Automattic/woocommerce-payments-server/pull/3968#issuecomment-1770920356)
   - Enable capability in the Stripe account
   - Add account meta `capability_klarna_payments = 1`  
- Test successful payment using Klarna (you have to specify valid domestic address in billing details)

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7518` or branch name `add/additional-countries-for-klarna` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=add/additional-countries-for-klarna) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 09d92bea13284e3c9b3873a7ee5522705c3aab24
- Build time: 2023-10-19 13:20:30 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by kalessil — CHANGES_REQUESTED** [review]
Can you please refer to your previous PR (https://github.com/Automattic/woocommerce-payments/pull/7282/files) and add the missing changes? Thanks!

**Comment by KarlisJ** [comment]
@kalessil apologies, for the pre-mature request for review. While going though testing I noticed too that the JS config was missing countries.

**Review by kalessil — APPROVED** [review]
LGTM (code review only)!

**Comment by kalessil** [comment]
@KarlisJ: no worries! Hope my writing didn't sound too pushy 😟

**Review by dmvrtx — APPROVED** [review]
Looks good to me code-wise. Will use it for testing later, but let it not block the merge.

**Comment by KarlisJ** [comment]
I've tested with SE, IE. Will go through all, but have high confidence at this point.

**Pull request merged**
