### PR TITLE
Customer facing prices compatibility with Product Add-Ons

### LINKED ISSUE #1901: Customer facing prices compatibility with Product Add-Ons
Follow up from #1769

We need to ensure compatibility with Customer multi-currency prices and Product Add-Ons.

### PR DESCRIPTION
**Pull request by daquinons**
Fixes #1901 

#### Changes proposed in this Pull Request

Adds compatibility for Product Add-Ons extension.

* Add new filters and actions needed to call our methods.
  * Note that a couple filters were needed specifically for ajax requests.
* `get_addons_price` takes care of most of the actual price conversions for add ons.
* `get_product_calculation_price` is used during ajax requests from the product page, seemingly only for the Quantity add on type.
  * The [ajax request from PAO](https://github.com/woocommerce/woocommerce-product-addons/blob/trunk/includes/class-wc-product-addons-ajax.php#L69-L76) actually gets the price with and without tax, so we have to account for both according to the filter that has been called. 
* As mentioned in the docblock, `get_item_data` will remove cart item data that PAO adds and add our own. 
  * This is done due to PAO does not have filters to easily modify this data for us to use. It's easier to hook into the same filter it does and completely replace the data.
  * PAO original `get_item_meta` is here: https://github.com/woocommerce/woocommerce-product-addons/blob/trunk/includes/class-wc-product-addons-cart.php#L592-L619
* Another override is `add_cart_item`.
  * Original `add_cart_item` in PAO actually hands off to `update_product_price`, and then [we disable that via a filter](https://github.com/woocommerce/woocommerce-product-addons/blob/trunk/includes/class-wc-product-addons-cart.php#L455).
  * Our method changes prices as needed, and also adds the `wcpay_mc_addons_converted` meta data to the cart item for us to determine if the add ons were already converted.
* `get_cart_item_from_session` is another override, but just gets the cart items from the session and adds them to the cart.
* `get_addon_order_display_price` gets the proper price for the add on to add to the order line item meta data for displaying the amounts in the thank you page, the order review page in My Account, and in the order review page in the admin.
* `product_addons_params` fixes currency formatting issues in PAO since it gets these values directly from the db options, bypassing our standard filters.
* `get_tax_adjusted_price` Checks if prices should have taxes added/removed and gets them for an item.
* `get_product_addon_tax_display_mode` Copied over from PAO to get the tax display mode.
* 

#### Testing instructions

* You will need to install the Product Add-Ons extension to test. The latest version can be found in the `all-plugins` repo.
* Create a product to add add ons to, and then use the _Import_ button under the _Add-ons_ section in the _Product data_ to import the json below.
* View your product and add different add ons making sure the values are calculated correctly:
  * On the product page.
  * In the cart widget aka the mini cart.
  * The cart page.
  * The checkout page.
  * The thank you page (once you place an order).
  * Under My Account > Orders, and in an order.
  * In the admin when viewing an order.
* Note: There are 4 main calculations:
  * Flat fee: This will calculate that amount once according to the exchange rate.
  * Percentage based: This will calculate the percentage of the converted price. Will show currency amount in add on name in cart.
  * Quantity based: Like flat fee, but the fee is multiplied by the quantity of the product.
  * Customer defined price: This _should not_ calculate at all.

```
a:7:{i:0;a:16:{s:4:"name";s:10:"Checkboxes";s:12:"title_format";s:5:"label";s:18:"description_enable";i:0;s:11:"description";s:0:"";s:4:"type";s:8:"checkbox";s:7:"display";s:6:"select";s:8:"position";i:0;s:8:"required";i:0;s:12:"restrictions";i:0;s:17:"restrictions_type";s:8:"any_text";s:12:"adjust_price";i:0;s:10:"price_type";s:8:"flat_fee";s:5:"price";s:0:"";s:3:"min";d:0;s:3:"max";d:0;s:7:"options";a:3:{i:0;a:4:{s:5:"label";s:4:"flat";s:5:"price";s:4:"1.50";s:5:"image";s:0:"";s:10:"price_type";s:8:"flat_fee";}i:1;a:4:{s:5:"label";s:5:"quant";s:5:"price";s:4:"2.25";s:5:"image";s:0:"";s:10:"price_type";s:14:"quantity_based";}i:2;a:4:{s:5:"label";s:7:"percent";s:5:"price";s:2:"10";s:5:"image";s:0:"";s:10:"price_type";s:16:"percentage_based";}}}i:1;a:16:{s:4:"name";s:15:"Multiple choice";s:12:"title_format";s:5:"label";s:18:"description_enable";i:0;s:11:"description";s:0:"";s:4:"type";s:15:"multiple_choice";s:7:"display";s:6:"select";s:8:"position";i:1;s:8:"required";i:0;s:12:"restrictions";i:0;s:17:"restrictions_type";s:8:"any_text";s:12:"adjust_price";i:0;s:10:"price_type";s:8:"flat_fee";s:5:"price";s:0:"";s:3:"min";d:0;s:3:"max";d:0;s:7:"options";a:3:{i:0;a:4:{s:5:"label";s:8:"flat fee";s:5:"price";s:4:"1.50";s:5:"image";s:0:"";s:10:"price_type";s:8:"flat_fee";}i:1;a:4:{s:5:"label";s:8:"quantity";s:5:"price";s:4:"2.25";s:5:"image";s:0:"";s:10:"price_type";s:14:"quantity_based";}i:2;a:4:{s:5:"label";s:10:"percentage";s:5:"price";s:1:"5";s:5:"image";s:0:"";s:10:"price_type";s:16:"percentage_based";}}}i:2;a:16:{s:4:"name";s:16:"Short text field";s:12:"title_format";s:5:"label";s:18:"description_enable";i:0;s:11:"description";s:0:"";s:4:"type";s:11:"custom_text";s:7:"display";s:6:"select";s:8:"position";i:2;s:8:"required";i:0;s:12:"restrictions";i:0;s:17:"restrictions_type";s:8:"any_text";s:12:"adjust_price";i:1;s:10:"price_type";s:14:"quantity_based";s:5:"price";s:4:"2.50";s:3:"min";d:0;s:3:"max";d:0;s:7:"options";a:1:{i:0;a:4:{s:5:"label";s:0:"";s:5:"price";s:0:"";s:5:"image";s:0:"";s:10:"price_type";s:8:"flat_fee";}}}i:3;a:16:{s:4:"name";s:15:"Long text field";s:12:"title_format";s:5:"label";s:18:"description_enable";i:0;s:11:"description";s:0:"";s:4:"type";s:15:"custom_textarea";s:7:"display";s:6:"select";s:8:"position";i:3;s:8:"required";i:0;s:12:"restrictions";i:0;s:17:"restrictions_type";s:8:"any_text";s:12:"adjust_price";i:1;s:10:"price_type";s:8:"flat_fee";s:5:"price";s:4:"1.50";s:3:"min";d:0;s:3:"max";d:0;s:7:"options";a:1:{i:0;a:4:{s:5:"label";s:0:"";s:5:"price";s:0:"";s:5:"image";s:0:"";s:10:"price_type";s:8:"flat_fee";}}}i:4;a:16:{s:4:"name";s:11:"File upload";s:12:"title_format";s:5:"label";s:18:"description_enable";i:0;s:11:"description";s:0:"";s:4:"type";s:11:"file_upload";s:7:"display";s:6:"select";s:8:"position";i:4;s:8:"required";i:0;s:12:"restrictions";i:0;s:17:"restrictions_type";s:8:"any_text";s:12:"adjust_price";i:1;s:10:"price_type";s:8:"flat_fee";s:5:"price";s:4:"1.50";s:3:"min";d:0;s:3:"max";d:0;s:7:"options";a:1:{i:0;a:4:{s:5:"label";s:0:"";s:5:"price";s:0:"";s:5:"image";s:0:"";s:10:"price_type";s:8:"flat_fee";}}}i:5;a:16:{s:4:"name";s:22:"Customer defined price";s:12:"title_format";s:5:"label";s:18:"description_enable";i:0;s:11:"description";s:0:"";s:4:"type";s:12:"custom_price";s:7:"display";s:6:"select";s:8:"position";i:5;s:8:"required";i:0;s:12:"restrictions";i:0;s:17:"restrictions_type";s:8:"any_text";s:12:"adjust_price";i:0;s:10:"price_type";s:14:"quantity_based";s:5:"price";s:0:"";s:3:"min";d:0;s:3:"max";d:0;s:7:"options";a:1:{i:0;a:4:{s:5:"label";s:0:"";s:5:"price";s:0:"";s:5:"image";s:0:"";s:10:"price_type";s:8:"flat_fee";}}}i:6;a:16:{s:4:"name";s:14:"Quantity field";s:12:"title_format";s:5:"label";s:18:"description_enable";i:0;s:11:"description";s:0:"";s:4:"type";s:16:"input_multiplier";s:7:"display";s:6:"select";s:8:"position";i:6;s:8:"required";i:0;s:12:"restrictions";i:0;s:17:"restrictions_type";s:8:"any_text";s:12:"adjust_price";i:1;s:10:"price_type";s:8:"flat_fee";s:5:"price";s:4:"3.25";s:3:"min";d:0;s:3:"max";d:0;s:7:"options";a:1:{i:0;a:4:{s:5:"label";s:0:"";s:5:"price";s:0:"";s:5:"image";s:0:"";s:10:"price_type";s:8:"flat_fee";}}}}
```

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply)

### CODE REVIEW

**Comment by tpaksu** [comment]
I couldn't get chromedriver to work on M1 Mac for PAO plugin, I'm looking for a solution. They use an old dependency that doesn't work on my machine..

**Comment by oaratovskyi** [comment]
Started testing, this is what I've noticed so far:
Multiple choice (dropdown) values from the import JSON are all Flat Fee.
image

I've updated it on my local.

@jessepearson should the last field be quantity fee rather than Flat Fee as well?
image

Let me know it is and I'll update it also and will share a new JSON for import.

And finally seems like the Japanese Yen is not being converted (¥100 every add-on). Other currencies are (EUR, GBP)
image

**Comment by tpaksu** [comment]
Looking around to understand what it does, but I think I've bumped into something here: 

<table><tr><td>
I selected those values and added to the cart</td>
<td>This is the cart item</td></tr>
<tr><td></td>
<td valign='top'></td></tr>
</table>

Those totals seem to be different, the differences is caused by the Quantity field, the item shows 4.00 DKK per quantity, but the cart shows 7.00 DKK as total, while it should be 8.00 DKK and the total should be 60.00 DKK instead 59.00 DKK.

**Comment by jessepearson** [comment]
@oaratovskyi 

> Multiple choice (dropdown) values from the import JSON are all Flat Fee.
I wonder if that's a bug with PAO and how it exports/imports the data. If you export and then import into a new product, does it work as expected?

> @jessepearson should the last field be quantity fee rather than Flat Fee as well?
That last one should be flat fee.

> And finally seems like the Japanese Yen is not being converted (¥100 every add-on). Other currencies are (EUR, GBP)
That is likely due to the low prices and rounding because it's a zero decimal currency. If you have higher amounts, does it work as expected?

**Comment by jessepearson** [comment]
@tpaksu 

> Those totals seem to be different, the differences is caused by the Quantity field, the item shows 4.00 DKK per quantity, but the cart shows 7.00 DKK as total, while it should be 8.00 DKK and the total should be 60.00 DKK instead 59.00 DKK.

Okay, that's likely a rounding issue somewhere. It's interesting that the totals are off, I will look into it.

**Comment by oaratovskyi** [comment]
> If you have higher amounts, does it work as expected?

@jessepearson yes, it works with greater values. My ratio between GBP and JPY was 1:1 and rounding to 100..
image

**Comment by oaratovskyi** [comment]
Something is wrong with displaying prices on 
- thank you page
- my accounts->orders->order
- edit order in admin
- view order in admin

I mean 
- Short text field 3 Yens, should be 300
- Long text field 3 Yens, should be 300
- File upload field 2 Yens, should be 200
image

**Comment by oaratovskyi** [comment]
>  If you export and then import into a new product, does it work as expected?

Yes, it does!
This is an updated JSON
```
a:7:{i:0;a:16:{s:4:"name";s:10:"Checkboxes";s:12:"title_format";s:5:"label";s:18:"description_enable";i:0;s:11:"description";s:0:"";s:4:"type";s:8:"checkbox";s:7:"display";s:6:"select";s:8:"position";i:0;s:8:"required";i:0;s:12:"restrictions";i:0;s:17:"restrictions_type";s:8:"any_text";s:12:"adjust_price";i:0;s:10:"price_type";s:8:"flat_fee";s:5:"price";s:0:"";s:3:"min";d:0;s:3:"max";d:0;s:7:"options";a:3:{i:0;a:4:{s:5:"label";s:4:"flat";s:5:"price";s:4:"1.50";s:5:"image";s:0:"";s:10:"price_type";s:8:"flat_fee";}i:1;a:4:{s:5:"label";s:5:"quant";s:5:"price";s:4:"2.25";s:5:"image";s:0:"";s:10:"price_type";s:14:"quantity_based";}i:2;a:4:{s:5:"label";s:7:"percent";s:5:"price";s:2:"10";s:5:"image";s:0:"";s:10:"price_type";s:16:"percentage_based";}}}i:1;a:16:{s:4:"name";s:15:"Multiple choice";s:12:"title_format";s:5:"label";s:18:"description_enable";i:0;s:11:"description";s:0:"";s:4:"type";s:15:"multiple_choice";s:7:"display";s:6:"select";s:8:"position";i:1;s:8:"required";i:0;s:12:"restrictions";i:0;s:17:"restrictions_type";s:8:"any_text";s:12:"adjust_price";i:0;s:10:"price_type";s:8:"flat_fee";s:5:"price";s:0:"";s:3:"min";d:0;s:3:"max";d:0;s:7:"options";a:3:{i:0;a:4:{s:5:"label";s:8:"flat fee";s:5:"price";s:4:"1.50";s:5:"image";s:0:"";s:10:"price_type";s:8:"flat_fee";}i:1;a:4:{s:5:"label";s:8:"quantity";s:5:"price";s:4:"2.25";s:5:"image";s:0:"";s:10:"price_type";s:14:"quantity_based";}i:2;a:4:{s:5:"label";s:10:"percentage";s:5:"price";s:1:"5";s:5:"image";s:0:"";s:10:"price_type";s:16:"percentage_based";}}}i:2;a:16:{s:4:"name";s:16:"Short text field";s:12:"title_format";s:5:"label";s:18:"description_enable";i:0;s:11:"description";s:0:"";s:4:"type";s:11:"custom_text";s:7:"display";s:6:"select";s:8:"position";i:2;s:8:"required";i:0;s:12:"restrictions";i:0;s:17:"restrictions_type";s:8:"any_text";s:12:"adjust_price";i:1;s:10:"price_type";s:14:"quantity_based";s:5:"price";s:4:"2.50";s:3:"min";d:0;s:3:"max";d:0;s:7:"options";a:1:{i:0;a:4:{s:5:"label";s:0:"";s:5:"price";s:0:"";s:5:"image";s:0:"";s:10:"price_type";s:8:"flat_fee";}}}i:3;a:16:{s:4:"name";s:15:"Long text field";s:12:"title_format";s:5:"label";s:18:"description_enable";i:0;s:11:"description";s:0:"";s:4:"type";s:15:"custom_textarea";s:7:"display";s:6:"select";s:8:"position";i:3;s:8:"required";i:0;s:12:"restrictions";i:0;s:17:"restrictions_type";s:8:"any_text";s:12:"adjust_price";i:1;s:10:"price_type";s:8:"flat_fee";s:5:"price";s:4:"1.50";s:3:"min";d:0;s:3:"max";d:0;s:7:"options";a:1:{i:0;a:4:{s:5:"label";s:0:"";s:5:"price";s:0:"";s:5:"image";s:0:"";s:10:"price_type";s:8:"flat_fee";}}}i:4;a:16:{s:4:"name";s:11:"File upload";s:12:"title_format";s:5:"label";s:18:"description_enable";i:0;s:11:"description";s:0:"";s:4:"type";s:11:"file_upload";s:7:"display";s:6:"select";s:8:"position";i:4;s:8:"required";i:0;s:12:"restrictions";i:0;s:17:"restrictions_type";s:8:"any_text";s:12:"adjust_price";i:1;s:10:"price_type";s:8:"flat_fee";s:5:"price";s:4:"1.50";s:3:"min";d:0;s:3:"max";d:0;s:7:"options";a:1:{i:0;a:4:{s:5:"label";s:0:"";s:5:"price";s:0:"";s:5:"image";s:0:"";s:10:"price_type";s:8:"flat_fee";}}}i:5;a:16:{s:4:"name";s:22:"Customer defined price";s:12:"title_format";s:5:"label";s:18:"description_enable";i:0;s:11:"description";s:0:"";s:4:"type";s:12:"custom_price";s:7:"display";s:6:"select";s:8:"position";i:5;s:8:"required";i:0;s:12:"restrictions";i:0;s:17:"restrictions_type";s:8:"any_text";s:12:"adjust_price";i:0;s:10:"price_type";s:14:"quantity_based";s:5:"price";s:0:"";s:3:"min";d:0;s:3:"max";d:0;s:7:"options";a:1:{i:0;a:4:{s:5:"label";s:0:"";s:5:"price";s:0:"";s:5:"image";s:0:"";s:10:"price_type";s:8:"flat_fee";}}}i:6;a:16:{s:4:"name";s:14:"Quantity field";s:12:"title_format";s:5:"label";s:18:"description_enable";i:0;s:11:"description";s:0:"";s:4:"type";s:16:"input_multiplier";s:7:"display";s:6:"select";s:8:"position";i:6;s:8:"required";i:0;s:12:"restrictions";i:0;s:17:"restrictions_type";s:8:"any_text";s:12:"adjust_price";i:1;s:10:"price_type";s:8:"flat_fee";s:5:"price";s:4:"3.25";s:3:"min";d:0;s:3:"max";d:0;s:7:"options";a:1:{i:0;a:4:{s:5:"label";s:0:"";s:5:"price";s:0:"";s:5:"image";s:0:"";s:10:"price_type";s:8:"flat_fee";}}}}
```

**Comment by oaratovskyi** [comment]
BTW, checked Block Cart and Block Checkout. It works and conversions look good.

**Comment by oaratovskyi** [comment]
@jessepearson I've tested the scenario with Japanese Yen again, it works with regular checkout.
image

However, for block checkout, it's still being reproduced
image

**Comment by jessepearson** [comment]
> However, for block checkout, it's still being reproduced
Fixed in https://github.com/Automattic/woocommerce-payments/pull/2873/commits/8b3b81fe8fc391c3b78581e5145424766c0755c5

**Comment by jessepearson** [comment]
> Those totals seem to be different, the differences is caused by the Quantity field, the item shows 4.00 DKK per quantity, but the cart shows 7.00 DKK as total, while it should be 8.00 DKK and the total should be 60.00 DKK instead 59.00 DKK.

Fixed in https://github.com/Automattic/woocommerce-payments/pull/2873/commits/a0c7df3c69bb8403603e3d6f97982deff65ff2fa

**Review by oaratovskyi — APPROVED** [review]
I've tested the Customer facing prices compatibility with Product Add-Ons one more time and looked into the code.
It works great! Great job @jessepearson! It was a tricky one.

**Comment by jessepearson** [comment]
Added _on hold_ tag pending the outcome of the RFC: paJDYF-2D9-p2 . Will likely be closed in favor of https://github.com/Automattic/woocommerce-payments/pull/2985

**Pull request closed without merging**
