### PR TITLE
chore: rename digital wallets components

### PR DESCRIPTION
**Pull request by frosso**
Fixes https://github.com/Automattic/woocommerce-payments/issues/2028

#### Changes proposed in this Pull Request

Renamed "Digital wallets" occurrences to "payment request" to be consistent with Stripe.

#### Testing instructions

- Go to http://localhost:8082/wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments
- Page works fine: previous settings are loaded, page loads data from backend, saves data to backend
- http://localhost:8082/wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments&method=payment_request
- Page works fine: previous settings are loaded, page loads data from backend, saves data to backend

-------------------

- [ ] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

### CODE REVIEW

**Comment by harriswong** [comment]
👀

**Review by harriswong — COMMENTED** [review]
I scrolled through the changes and they look good. Also tested the 2 pages linked in test instructions, settings save as expected.

I did 2 searches in the code base looking for "digital wallets" and "wallets", there are some occurrences of these. Do we want to update them as well?

**Comment by frosso** [comment]
Thanks @harriswong ! My apologies for missing them, I didn't think of looking for test cases!
I renamed additional strings in 3497011b. Let me know if I missed anything else - the remaining stuff should be only customer-facing strings.

**Review by harriswong — APPROVED** [review]
Assuming we don't have to replace customer facing strings, last commit looks good.

👍

**Pull request merged**
