### PR TITLE
Update WooPay theme checkbox copy in settings page

### LINKED ISSUE #9738: Update WooPay global theme settings copy
### Description
We will update the new global theme support label and copy to better express the value to the merchant, to include a link to documentation, and to be consistent with case, spacing, and font used in settings.

Image

### Acceptance criteria

1. The title is changed to "Checkout theme"
2. The checkbox label is changed to "Enable global theme support"
3. Add secondary text, on the next row: "When enabled, WooPay checkout will be themed with your store’s brand colors and fonts. Learn more [opens in new tab icon]."
4. Font family, size, and relative placement matches this pattern:
Image

cc @hsingyuc

### PR DESCRIPTION
**Pull request by malithsen**
Fixes #9738 

#### Changes proposed in this Pull Request

- The title is changed to "Checkout theme"
- The checkbox label is changed to "Enable global theme support"
- Add secondary text, on the next row: "When enabled, WooPay checkout will be themed with your store’s brand colors and fonts. Learn more"

Before
CleanShot 2024-11-28 at 11 44 29 
After
CleanShot 2024-11-28 at 11 43 55 

#### Testing instructions

* Make sure WooPay theming is enabled for you local site. I do this by forcing `true` in [this function](https://github.com/Automattic/transact-platform-server/blob/de52ab019b215320c021c4d5ece593555f95fe36/server/wp-content/rest-api-plugins/endpoints/wcpay/service/class-account-service.php#L2489)
* As a merchant, go to Payments -> Settings 
* Select 'Customize' button next to WooPay.
* Make sure checkout appearance section follows the acceptance criteria defined in #9738

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9843` or branch name `fix/change-woopay-theming-settings-copy` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/change-woopay-theming-settings-copy) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 760fd620875c11f830e035504e77c364d14d7477
- Build time: 2024-11-28 18:02:30 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by hsingyuc — APPROVED** [review]
Thank you for working on this, @malithsen! Code LGTM and tests as expected. The learn more link links to [Checkout appearance](https://woocommerce.com/document/woopay-merchant-documentation/#checkout-appearance)

**Comment by pierorocca** [comment]
Could we please add a Beta badge next to "Enable global theme support" as a new enhancement as we slow roll this out and expect there to be learnings?

Also could you confirm that for now it is not pre-checked for any merchant?

**Comment by malithsen** [comment]
> Could we please add a Beta badge next to "Enable global theme support" as a new enhancement as we slow roll this out and expect there to be learnings?

@pierorocca Do we have a design for this?

I can create a new PR as this one is merged.

> Also could you confirm that for now it is not pre-checked for any merchant?

It's not pre-checked for any merchant unless we explicitly turn on the feature via their Blog RC.

**Comment by pierorocca** [comment]
> It's not pre-checked for any merchant unless we explicitly turn on the feature via their Blog RC.

Got it. At some point until this is all hardened and we have good data that it works in most scenarios, even if there's a feature flag in place, the safer option is to have the merchant opt-in.

> @pierorocca Do we have a design for this?

I will get you this. We'd use the standard badge component used in wp-admin but I think the color would be Black instead of green, yellow, or red based on what I'm seeing used in Blocks FSE to denote a beta feature.

**Pull request merged**
