### PR TITLE
Handle IPP failure webhooks

### LINKED ISSUE #9220: Payment failed webhook handler ignores IPP payment method
### Describe the bug

The method that handles the `payment_intent.payment_failed` webhook takes not action when the payment method is specified as 'card_present'.

As a consequence, there is no note added to the order informing the merchant of the failure and the order status does not change to Failed

### To Reproduce

1. Place an order using Woocommerce mobile app
2. Try to capture it in a way that triggers a `payment_failed`error.

### Actual behavior

The order does not transition to failed status. There is no note added to the details of the order informing the merchant of the error.

### Expected behavior

The order transitions to failed status. A note is added to the order informing the merchant of the error.

### Additional context

We need to add the `card_present` payment method to the array of actionable payment methods in `process_webhook_payment_intent_failed` method.

### PR DESCRIPTION
**Pull request by mgascam**
Fixes #9220

#### Changes proposed in this Pull Request

These changes were already reviewed and approved in https://github.com/Automattic/woocommerce-payments/pull/9198, but we had to revert it due to an undesired side effect in the app https://github.com/Automattic/woocommerce-payments/pull/9229.

We intend to reapply the fix as per this conversation: https://woomobilep2.wordpress.com/2024/08/13/addressing-inconsistencies-in-ipp-payment-failure-handling/#comment-13525

#### Testing instructions

Please refer to the testing instructions in the linked PR

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by mgascam** [comment]
Hi @malinajirka @staskus I added you as reviewers mostly as a FYI that we are going to reapply this change as requested.

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9705` or branch name `fix/9220-payment-failed-webhook-handler-ignores-ipp-pm` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/9220-payment-failed-webhook-handler-ignores-ipp-pm) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: f853fcce6fedb212f07f3dbae2839caf211a838e
- Build time: 2024-11-12 09:02:08 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by deepakpathania — APPROVED** [review]
LGTM

**Review by malinajirka — APPROVED** [review]
Thanks! I've retested this and it seems to work as expected 🚢

**Pull request merged**
