### PR TITLE
Add welcome tour component

### PR DESCRIPTION
**Pull request by eduardoumpierre**
Fixes Automattic/woocommerce-payments-server#2786

#### Changes proposed in this Pull Request

Add the welcome tour components

This component provides a tour experience based on the configuration steps passed as parameters and should work in a generic way.

Figma reference (WIM5w2Y10SCNBFdMLSVftj-fi-1300%3A196843)

https://user-images.githubusercontent.com/16882226/223614496-1a57dc5a-0a6a-41f1-bcb6-45f416dfa270.mp4

#### Testing instructions

* Checkout to this branch `add/2786-welcome-tour`
* Run `npm start`
* Apply the "Example diff" below
* Go to **Payments > Settings**
* The tour modal should pop up
  * Navigate through it
  * You can close the modal by pressing the "X" button or clicking on the "Got it" button at the end
  * Try to resize the browser window
  * It should be centered on mobile

<details>
  <summary>Example diff</summary>

  ```diff
diff --git a/client/settings/settings-manager/index.js b/client/settings/settings-manager/index.js
index d6e0878b..43cb26c1 100644
--- a/client/settings/settings-manager/index.js
+++ b/client/settings/settings-manager/index.js
@@ -2,7 +2,7 @@
 /**
  * External dependencies
  */
-import React, { useContext, useState } from 'react';
+import React, { useContext, useState, useEffect } from 'react';
 import { ExternalLink } from '@wordpress/components';
 import { __, sprintf } from '@wordpress/i18n';
 
@@ -22,7 +22,8 @@ import WCPaySettingsContext from '../wcpay-settings-context';
 import LoadableSettingsSection from '../loadable-settings-section';
 import WcPayUpeContextProvider from '../wcpay-upe-toggle/provider';
 import ErrorBoundary from '../../components/error-boundary';
-import { useDepositDelayDays } from '../../data';
+import { useDepositDelayDays, useSettings } from '../../data';
+import Tour from 'components/tour';
 
 const PaymentMethodsDescription = () => (
 	<>
@@ -108,6 +109,96 @@ const DepositsDescription = () => {
 	);
 };
 
+const TourFirstStep = () => {
+	return (
+		<Tour.Step selector="#wpcontent" position={ { bottom: 20, left: 20 } }>
+			<Tour.Image
+				src="https://picsum.photos/350/204"
+				alt="Enhanced fraud protection is here 🔒"
+			/>
+
+			<Tour.Content
+				title="Enhanced fraud protection is here 🔒"
+				// eslint-disable-next-line max-len
+				description="Incoming transactions will now be screened for common risk factors, at the level of your choosing. Review any transactions caught by these filters and select whether you'd like to approve or decline them"
+			/>
+
+			<Tour.Footer showCounter={ false }>
+				<Tour.NextButton />
+			</Tour.Footer>
+		</Tour.Step>
+	);
+};
+
+const TourSecondStep = () => {
+	return (
+		<Tour.Step
+			selector=".deposits__bank-information > h4"
+			position="bottom"
+		>
+			<Tour.Image
+				src="https://picsum.photos/350/204"
+				alt="Choose your filter level 🚦"
+				mobileOnly
+			/>
+
+			<Tour.Content
+				title="Choose your filter level 🚦"
+				// eslint-disable-next-line max-len
+				description="Decide how aggressively you want to filter suspicious payments, from standard to advanced."
+			/>
+
+			<Tour.Footer />
+		</Tour.Step>
+	);
+};
+
+const TourThirdStep = () => {
+	return (
+		<Tour.Step selector=".express-checkout__label" position="left">
+			<Tour.Image
+				src="https://picsum.photos/350/204"
+				alt="Take more control 🎚️"
+				mobileOnly
+			/>
+
+			<Tour.Content
+				title="Take more control 🎚️"
+				// eslint-disable-next-line max-len
+				description="We recommend using one of the preset risk levels, but if you need more control, head to Advanced to fine-tune the various filters."
+			/>
+
+			<Tour.Footer />
+		</Tour.Step>
+	);
+};
+
+const TourFourthStep = () => {
+	return (
+		<Tour.Step
+			selector=".payment-methods__available-methods .payment-method:first-child .payment-method__label"
+			position="right"
+		>
+			<Tour.Image
+				src="https://picsum.photos/350/204"
+				alt="Ready for review 📥️"
+				mobileOnly
+			/>
+
+			<Tour.Content
+				title="Ready for review 📥️"
+				// eslint-disable-next-line max-len
+				description="Payments that have been caught by a risk filter will appear under Transactions > Payments. We'll let you know why each payment was flagged so that you can determine whether to approve or block it."
+			/>
+
+			<Tour.Footer>
+				<Tour.PreviousButton />
+				<Tour.NextButton>Got it!</Tour.NextButton>
+			</Tour.Footer>
+		</Tour.Step>
+	);
+};
+
 const SettingsManager = () => {
 	const {
 		featureFlags: {
@@ -119,6 +210,19 @@ const SettingsManager = () => {
 	const [ isTransactionInputsValid, setTransactionInputsValid ] = useState(
 		true
 	);
+	const { isLoading } = useSettings();
+
+	const [ showTour, setShowTour ] = useState( false );
+
+	useEffect( () => {
+		if ( ! isLoading ) {
+			setShowTour( true );
+		}
+	}, [ isLoading ] );
+
+	const handleTourEnd = () => {
+		setShowTour( false );
+	};
 
 	return (
 		<SettingsLayout>
@@ -176,6 +280,15 @@ const SettingsManager = () => {
 			</SettingsSection>
 			<AdvancedSettings />
 			<SaveSettingsSection disabled={ ! isTransactionInputsValid } />
+
+			{ showTour && (
+				<Tour onTourEnd={ handleTourEnd }>
+					<TourFirstStep />
+					<TourSecondStep />
+					<TourThirdStep />
+					<TourFourthStep />
+				</Tour>
+			) }
 		</SettingsLayout>
 	);
 };
  ```
</details>

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : QA Testing Not Applicable
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by dwainm** [comment]
@eduardoumpierre please update this issue to link to the PR

**Comment by eduardoumpierre** [comment]
I've updated the code ([f8ce3bc](https://github.com/Automattic/woocommerce-payments/pull/5606/commits/f8ce3bc90ebf13c81c84c666d94c6a9782dedfc5)) to address the suggestions from @tpaksu and @ismaeldcom on p1677579540908739-slack-C01B8KNUYSW.

Thanks for your input and let me know if you have more suggestions! 👍

**Review by tpaksu — APPROVED** [review]
Looks beautiful! Both visually and code-wise :) Thanks for addressing my concerns about splitting the code into multiple components. It works as described in the PR description. LGTM! :shipit: (BTW, the patch doesn't work again, so I needed to patch it manually.)

**Comment by ismaeldcom** [comment]
Awesome work @eduardoumpierre! You've made a good looking composable tour component, which works flawlessly.

It's just a matter of taste, but I personally prefer using component dot notation instead of a barrel file. So instead of importing every component you can just use them like `<Tour.Step>`.

And by the way, I've seen a few `wcpay/components/...` imports, not sure why the editor completes them like that, but you can safely remove `wcpay` from it 🙂

**Comment by eduardoumpierre** [comment]
> Thanks for addressing my concerns about splitting the code into multiple components.

Thanks for your input @tpaksu! 

> BTW, the patch doesn't work again, so I needed to patch it manually.

I've updated the PR description and started to generate the patch running `git diff -w > diff.patch`. I will keep using this flag when generating new diffs, and it should work fine for you now!

**Comment by eduardoumpierre** [comment]
> So instead of importing every component you can just use them like <Tour.Step>.

That's nice, it's way cleaner as we import just the main component. It was updated on [4166d49](https://github.com/Automattic/woocommerce-payments/pull/5606/commits/4166d49fa81becff9d67ad03268c336bcacb4751) and thanks for the suggestion!

> And by the way, I've seen a few wcpay/components/... imports, not sure why the editor completes them like that, but you can safely remove wcpay from it 🙂

I just found the `wcpay/components` imports in the diff from the PR description and updated them. Thanks!

**Comment by ismaeldcom** [comment]
Anytime! 🙂 

Just a little nitpick, you can ensure dot notation components has proper type definitions by doing it like:
```tsx
/* eslint-disable @typescript-eslint/naming-convention */
interface TourComponents {
	Step: typeof TourStep;
        ...
}
/* eslint-enable @typescript-eslint/naming-convention */

const Tour: React.FC< TourProps > & TourComponents = ...


Tour.Step = TourStep;
...

export default Tour;
```

**Comment by eduardoumpierre** [comment]
> Just a little nitpick, you can ensure dot notation components has proper type definitions by doing it like:

@ismaeldcom Nice tip, thanks for that! It was updated on [46623b9](https://github.com/Automattic/woocommerce-payments/pull/5606/commits/46623b9e7e5960b12d3146cbabc38e03cd26f468).

**Review by ismaeldcom — APPROVED** [review]

**Pull request merged**
