### PR TITLE
Increase font on WooPay button

### LINKED ISSUE #8136: Increase WooPay button label font so that it has equal prominence to competing PRBs
### Description
Competing PRB buttons have label text that significantly larger the WooPay text, create visual inequality. In order to provide equal treatment, the WooPay label text size will be increased for all button sizes.

### Acceptance criteria
Small button - The label text is 16px across all breakpoints
Default button - The label text is 18px across all breakpoints
Large button - The label text is 20px across all breakpoints

### Designs
@nikkivias for further details as needed. 
https://developer.woo.com/docs/user-experience-guidelines-payment-button-size-and-anatomy/ for reference.

Additional reference: [Figma](https://www.figma.com/file/qNVPHJXgRkftiSR7j2XOlj/Centralized-Payment-Button-Guidelines?type=design&node-id=892%3A38720&mode=design&t=8QL7Y3yrkDIzE3G2-1)

### Testing instructions
1. Enable Apple Pay/Google Pay and WooPay
2. Set button label to "Buy with" and enabled on all pages.
3. Test on Chrome and Safari desktop and note that the font size has been increased on the product, cart, and checkout pages.
4. Vary the browser window size to test various breakpoints
5. Test again on mobile
6. Test again with the other 2 label options.
7. Test again with the 'icon only' option and observe no label text and that the logo is centered.

### PR DESCRIPTION
**Pull request by LCmry**
Fixes #8136 

### Changes proposed in this Pull Request

The changes in this PR ensure the WooPay button label's font sizes are more in line with the other PRB/ECE buttons:
* Small button - The label text is `18px` across all breakpoints
* Default button - The label text is `22px` across all breakpoints
* Large button - The label text is `26px` across all breakpoints

Additionally, the WooPay button's design has been updated so that it matches better with the other PRB/ECE buttons.

### Testing instructions

**Test: Ensure WooPay font sizes display as intended**
1. As a merchant, enable Apple Pay/Google Pay and WooPay.
2. Navigate to WooPay settings and ensure the button is enabled on all pages.
3. Set the WooPay button **Call to action** to "Buy with" and **Button size** to "Small (40 px)".
4. As a shopper, navigate to the merchant shop, add an item to the cart, and navigate to the cart page.
5. Ensure the button's label font size is set to "18px" by right-clicking on the label and clicking "Inspect".
6. Ensure the button's label font size does not change throughout different breakpoints by resizing the window's width. Note: While testing, resize the window width to mobile width and ensure the button's text fits in the button.
7. Repeat steps 3 to 6 for the following **Button size**: 
   * "Medium (48 px)": The label's font size should be set to "22px".
   * "Large (56 px)": The label's font size should be set to "26px".
8. Repeat steps 3 to 7, but instead, set the **Call to action** to "Donate with".
9. Ensure the **Call to action**  "Donate with" and "Book with" do not cause any visual issues on the button.
10. Test again with the 'icon only' option and observe that there is no label text and that the logo is centered.
11. Test on both Chrome and Safari.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8715` or branch name `update/increase-woopay-button-font` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=update/increase-woopay-button-font) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 81cbef8de50acdf2b73b373f4cc2cb5925aa387d
- Build time: 2024-07-26 02:01:26 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by LCmry** [comment]
| Before | After |
| -------| ----- |
| Shortcode Cart | Shortcode Cart |
| ecb_before_cart | ecb_after_cart |
| Blocks Cart | Blocks Cart |
| ecb_before_cart2 | ecb_after_cart2 |
| Shortcode Checkout | Shortcode Checkout |
|  ecb_before_check | ecb_after_check |
| Blocks Checkout | Blocks Checkout |
| ecb_before_check2 | ecb_after_check2 |
| Product Page | Product Page |
| ecb_before_prod | ecb_after_prod |

**Comment by LCmry** [comment]
Shortcode Cart Default
ecb_after_cart 
Shortcode Cart Med
ecb_after_cart_med 
Shortcode Cart Large 
ecb_after_cart_lg 

Blocks Cart Default 
ecb_after_cart2 
Blocks Cart Med 
ecb_after_cart2_med 
Blocks Cart Large 
ecb_after_cart2_lg

**Comment by LCmry** [comment]
Shortcode Checkout Default - Before
ecb_before_check

After
Shortcode Checkout Default
ecb_after_check

Shortcode Checkout Med
ecb_after_check_med

Shortcode Checkout Large
ecb_after_check_lg

Blocks Checkout Default - Before
ecb_before_check2

After
Blocks Checkout Default
ecb_after_check2

Blocks Checkout Med
ecb_after_check2_med

Blocks Checkout Large
ecb_after_check2_lg

**Comment by LCmry** [comment]
Product Page - Before
ecb_before_prod

After
Product Page Default
ecb_after_prod

Product Page Med
ecb_after_prod_med

Product Page Large
ecb_after_prod_lg

**Comment by LCmry** [comment]
@pierorocca and @nikkivias for reviewing the look please.

**Comment by pierorocca** [comment]
I'm on mobile and afk. At a quick glance the  size looks good but the font weight seems heavier than the dev guidelines?

Could you confirm the logic is getting applied to the light and outline theme options?

**Comment by LCmry** [comment]
Thanks for taking a look @pierorocca .

> font weight seems heavier than the dev guidelines

I only changed the font size. Where are the guidelines for weight? I can check into them.

Can confirm it is the same for light and outline options.

**Comment by pierorocca** [comment]
@LCmry what I'm seeing in the Figma is SF Pro Text Medium. Here's the Figma Large 54 px button for comparison. What web font is being used and current weight?

image

image

**Comment by LCmry** [comment]
@pierorocca the current font is 'SF Pro Text' and current weight is 500.

**Comment by pierorocca** [comment]
Thanks @LCmry. 500 does correspond to Medium. It looks like Figma rendering can be different than what's actually rendered by different devices and browsers. https://forum.figma.com/t/font-sfprotext-medium-displays-different-between-figma-vs-ios/9513

@nikkivias any thoughts here? Keep weight at 500 or drop down to 400 to try and match Figma?

**Comment by lovo-h** [comment]
@nikkivias @pierorocca, I just wanted to follow up on [this question](https://github.com/Automattic/woocommerce-payments/pull/8715#issuecomment-2104833012):

> any thoughts here? Keep weight at 500 or drop down to 400 to try and match Figma?

~In the meantime, to keep things moving, I will request a code review of the current changes to the font sizes of the WooPay button labels.~

**Comment by pierorocca** [comment]
@lovo-h I recommended making the code implementation look true to the Figma visual which I believe in this case requires ignoring the Figma sizing.

**Comment by lovo-h** [comment]
@pierorocca @nikkivias, here are how the WooPay buttons look compared to the new ECE buttons.

Before and After: Small (40 px) button size
image
image

---

Before and After: Medium (48 px) button size
image
image

---

Before and After: Large (55 px) button size
image
image

The changes applied to the WooPay button in this PR are:
* Increased the label font size in [34b5aed](https://github.com/Automattic/woocommerce-payments/pull/8715/commits/34b5aedc1a8a87590e8671857581635559415279).
* Added a mechanism to prevent the logo from shrinking too much when resizing the window in [96a2cbb](https://github.com/Automattic/woocommerce-payments/pull/8715/commits/96a2cbb813762e2b6c3d3a043daa05777c68ac17).
* Reduced the font weight of the text in [a9d6802](https://github.com/Automattic/woocommerce-payments/pull/8715/commits/a9d68029e6cd10ceff0ea58f2ac2b3af428876dd).
* Updated the spacing between the text and logo in [5426fa8](https://github.com/Automattic/woocommerce-payments/pull/8715/commits/5426fa876273c607762d12b585456a5fb580d8e0).
* Set a minimum width for the button in [38b576e](https://github.com/Automattic/woocommerce-payments/pull/8715/commits/38b576e37143c216a2799bd87d9e27c9ebbd6fa6).

Given the scope of issue #8136, should we proceed as-is or should we consider making additional modifications?

**Comment by pierorocca** [comment]
Looking better @lovo-h. For reference is that Chrome or Safari? I'd like to rule out differences between browsers. The weighting looks right to me compared to at 500. The font sizing however, we're smaller than the other buttons in the medium and large sized buttons?

**Comment by pierorocca** [comment]
Comparing Figma to code, seems undersized? Is Google bigger than Figma or is WooPay smaller?

image 
image

**Comment by pierorocca** [comment]
Adding the visual as a reference. On my Mac, SF Pro was not installed and I'm going to safely assume Android and Windows don't include this font by default. Most machines are going to fall back Helvetica for WooPay and Segoe for Apple Pay. Google Pay is an SVG so is not impacted. Noting not having to deal with font availability and variability is a good reason to move forward with an SVG approach for WooPay.

image

**Comment by pierorocca** [comment]
Note that depending on your platform and browser, and installed fonts, you might see variations between another person's experience. There's variability.

To understand some of that variability, I've listed the font family for Stripe ECE, and WooPay.

### **Safari on MacOS Sonoma**

**[Stripe ECE](https://docs.stripe.com/elements/express-checkout-element)**
-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif

**WooPay**
"SF Pro Text","Helvetica Neue","Helvetica","Roboto","Arial",sans-serif

- Stripe has normalized the css which appears to be common for performance and cross-platform optimization. Not having `segoe ui` somewhere in the WooPay font family stack is a miss for Windows users who do not have Helvetica or Roboto which are not installed by default.

- `-apple-system`, the browser will choose to display either SF Pro Text or SF Pro Display depending on the text size
- Google Pay is rendered as an SVG so is not impacted.

image

**Comment by pierorocca** [comment]
@lovo-h per our discussion we'll update the WooPay font stack to increase our platform coverage and to allow Apple based browsers to choose the optimal SF Pro font based on mobile vs. desktop and text size. This results in:

`-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Helvetica Neue', 'Helvetica', 'Roboto', 'Arial', sans-serif;`

`-apple-system` - Apple system font SF Pro. Browser chooses between SF Pro Text and SF Pro Display. Safari and Firefox.
`BlinkMacSystemFont` - Apple system font applicable to Chrome
`Segoe UI` - Default Windows font
`Helvetica Neue, Helvetica` - Default Apple font for older devices and when SF Pro is not available
`Roboto` - Default Android font
`Arial` - Web safe font fallback

**Comment by lovo-h** [comment]
Thank you, @pierorocca. The font stack has been updated in [9b6986e](https://github.com/Automattic/woocommerce-payments/pull/8715/commits/9b6986e46c041e69179ae4f1128708a070796d65).

Here are the latest before and afters of how the WooPay buttons look compared to the ECE.

Before and After: Small (40 px) button size
image
---
image


---

Before and After: Medium (48 px) button size
image
---
image


---

Before and After: Large (55 px) button size
image
---
image

**Comment by pierorocca** [comment]
@nikkivias for final QA.

**Review by nikivias — APPROVED** [review]

**Review by bborman22 — APPROVED** [review]
I ran through all the test instructions covering the matrix of the following settings:
- CTA: Icon, Buy, Donate, Book
- Size: Small, Medium, Large
- Browser: Chrome, Safari
- Page: Product, Cart, Cart Block Checkout, Checkout Block

I only spotted two visual issues both on the Checkout Block, but I also confirmed that https://github.com/Automattic/woocommerce-payments/pull/9124 fixes both issues!!

- When Donate CTA is used on Chrome, the button text is too tight.
- With any CTA on Safari the Apple Pay button overlaps the WooPay button.

Again just to be clear both issues are resolved by https://github.com/Automattic/woocommerce-payments/pull/9124 so no action needs to be taken on this PR, but want to note that makes https://github.com/Automattic/woocommerce-payments/pull/9124 a required PR for this release.

LGTM!

**Pull request merged**
