### PR TITLE
Multi-Currency track enabled currencies update

### LINKED ISSUE #2760: MC tracks: Inbox note funnel completion
* Percentage of merchants who click note then add at least 1 customer currency within 1 day, 7 days and 30 days

This can and should be broken down into individual events for Tracks to track, e.g.
* Inbox note click – with timestamp
* Currencies added – with timestamp

Then the funnel can be built afterwards using those events.

Edit: Updated scope per comment: paJDYF-2o5-p2#comment-7834

### PR DESCRIPTION
**Pull request by ismaeldcom**
Fixes #2760 

#### Changes proposed in this Pull Request
Track enabled currencies update using the `submitEnabledCurrenciesUpdate` action. Though about doing it on the component, but this will end up being implemented twice with the new onboarding setup, where we can also add new currencies. And also to do it on the PHP side, but the method used to update the currencies is also called internally and could produce _falsy_ events. So I've chosen to do it on the action.

We only need to implement the new event `wcpay_multi_currency_enabled_currencies_updated`, because we already have `wcadmin_inbox_action_click` to track inbox note click. And timestamps are registered on every event, so no need to add it either.

Both events are tracked correctly and connected on funnels, you can take a look at funnel `Multi Currency Inbox note completion` for an example of previous implementation.

#### Testing instructions
**You'll need to wait 5 minutes until live events are available.**
- Click on the Multi-Currency inbox note and look at `Tracks Live View` to check that your event `wcadmin_inbox_action_click` is registered.
- Update enabled currencies adding and removing some of them, and look at `Tracks Live View` to check that your event `wcadmin_wcpay_multi_currency_enabled_currencies_updated` is registered with `added_currencies` and `removed_currencies` in `eventprops`.

#### TODO (After merge)
- [ ] Add the new event to `Tracks in WooCommerce Payments` Field Guide, after merge.

#### Screenshots
Screenshot 2021-09-02 at 09 26 56
Screenshot 2021-09-10 at 13 16 14

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**
- [x] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply)

### CODE REVIEW

**Review by jessepearson — CHANGES_REQUESTED** [review]
@ismaeldcom It's working, but it's not passing all of the info. You can see in your screenshots that `wcadmin_inbox_action_click` has `blogid` and `bloglang`, but `wcadmin_wcpay_multi_currency_currency_added` does not. I am not sure if the `bloglang` is needed, but I believe `blogid` is going to be needed.

I was looking for where that's set, but have been going in circles 😵‍💫

**Comment by ismaeldcom** [comment]
Hey @jessepearson! According to David's comment in paJDYF-2o5-p2#comment-7834 looks like the current implementation will work for the funnel purpose. Actually, they only need to know if any currency was added after the inbox note was clicked. I'm wondering now if we should simplify the event to call it once, on enabled currencies update, instead of calling it one time for each currency added. What do you think?

**Comment by jessepearson** [comment]
> Hey @jessepearson! According to David's comment in paJDYF-2o5-p2#comment-7834 looks like the current implementation will work for the funnel purpose. Actually, they only need to know if any currency was added after the inbox note was clicked. I'm wondering now if we should simplify the event to call it once, on enabled currencies update, instead of calling it one time for each currency added. What do you think?

@ismaeldcom I think a single call under `update_enabled_currencies` like we talked about in Slack works: p1630586738117400-slack-C01B8KNUYSW . The reason for doing it in PHP rather than JS would be to add the `blogid` to the event call, unless you are able to do that in JS. Without the `blogid`, then the two events can't be related to each other.

To my understanding this only needs a single event call, ever, and due to my misunderstanding of #2761 I added a way to track what's been tracked. There are two methods here: https://github.com/Automattic/woocommerce-payments/pull/2852/files#diff-ecbb43e971935161587ed8d6e60fdea6b1bd1f86e493419f96e6f55e46bd3a1dR134 . Do you think something like this would be useful?

**Comment by ismaeldcom** [comment]
@jessepearson I think this can be simplified. They only want to know if a user completes the funnel (inbox note click + add currency). And for that, even the JS track works. It doesn't need the `blogid`, it connects the events with the `userid`.

I would go for the simplest solution here. Maybe calling it on JS update currency with an array of currencies. This would be useful for the funnel completion and to have some stats on the added currencies, that might be useful in the future.

I think that those methods you added on Tracking class might be useful, but also think that might be overengineering it, for this case. But want to hear your opinion 🙂

**Comment by jessepearson** [comment]
> I think this can be simplified. They only want to know if a user completes the funnel (inbox note click + add currency). And for that, even the JS track works. It doesn't need the blogid, it connects the events with the userid.
> 
> I would go for the simplest solution here. Maybe calling it on JS update currency with an array of currencies. This would be useful for the funnel completion and to have some stats on the added currencies, that might be useful in the future.

I'm just wondering if the data here is needed to be per site (blogid), or just per user. If a user has 2 sites and they click the note on site A, then add currencies on site B (without clicking the note), is that going to count as funnel completion?

> I think that those methods you added on Tracking class might be useful, but also think that might be overengineering it, for this case. But want to hear your opinion 🙂

Ya, I initially added them before getting clarification on Tracker vs Tracks, had deleted them, but added them back to show as an example.

**Comment by ismaeldcom** [comment]
> I'm just wondering if the data here is needed to be per site (blogid), or just per user. If a user has 2 sites and they click the note on site A, then add currencies on site B (without clicking the note), is that going to count as funnel completion?

Sorry, I didn't provide enough details about it before. I was talking about `userid` in my case `woo:37VJFft43AItzkQFH6gZKEdp`. Not sure how this gets generated, but is not shared between sites. Looks like a unique identifier used for tracks, like the one other stats systems use.

**Comment by jessepearson** [comment]
> Sorry, I didn't provide enough details about it before. I was talking about userid in my case woo:37VJFft43AItzkQFH6gZKEdp. Not sure how this gets generated, but is not shared between sites. Looks like a unique identifier used for tracks, like the one other stats systems use.

Ah, very nice 😁 

I think the only issue we have now is that this event fires each time currencies are updated, which also includes when currencies are removed. I think we only need to track the first add, but just asked on the P2 for clarification: paJDYF-2o5-p2#comment-7886

**Comment by ismaeldcom** [comment]
@jessepearson Good catch! I forgot to check the length, with the loop there was no need to check it 🙂 

Checking the comment you linked, looks like now the scope of the issue is a bit different, and we should track it on the onboarding instead. Do you think we should hold this issue until the onboarding one is complete? Or maybe just integrate the track directly on that issue, knowing that there are only a few lines.

**Comment by tpaksu** [comment]
Onboarding will use the same `submitEnabledCurrenciesUpdate` call and the `update_currencies` REST endpoint method, so no need to wait for it. I changed the URL on the note button to point to the wizard instead the settings page. 

But, on a second thought, you may need to differentiate which one sent you the update request, the onboarding call, or the settings page call. You can add another parameter to the settings page call, and skip the tracking if it's the settings page sending that update request. This way you won't have to wait for #2786 to be merged. And when it's merged, it'll work as expected.

**Comment by ismaeldcom** [comment]
My thought about moving it to the onboarding, is that if we only want to track it only **once** and on the onboarding. Might be better to just call it from there.

I see the current implementation on `submitEnabledCurrenciesUpdate` a good fit to track the event on every currency added in both settings page and onboarding. But looks like we are going to track the enabled currencies in another way, and this issue will be only to the funnel completion of inbox note.

**Comment by tpaksu** [comment]
> My thought about moving it to the onboarding, is that if we only want to track it only once and on the onboarding. Might be better to just call it from there.

True, that'll be the most convenient way to do it. 👍🏼

**Comment by jessepearson** [comment]
> Checking the comment you linked, looks like now the scope of the issue is a bit different, and we should track it on the onboarding instead. Do you think we should hold this issue until the onboarding one is complete? Or maybe just integrate the track directly on that issue, knowing that there are only a few lines.

Correct, it appears that this should now be tracked only when the merchant is onboarding. I believe it's better to have a separate PR so that there's one for tracking and one for onboarding to match the open issues. Meaning, we should wait until onboarding is merged to add this tracking.

**Comment by ismaeldcom** [comment]
Updated code, title and description, now it should be ready to test when the onboarding PR got merged.

**Comment by ismaeldcom** [comment]
Tested after #2786 got merged, and it's working as expected. Look at the URLs from both events:

| Event from onboarding |
|-|
|Screenshot 2021-09-16 at 12 59 06|

|Event from settings|
|-|
|Screenshot 2021-09-16 at 13 02 56|

**Review by oaratovskyi — APPROVED** [review]
Works well and looks very good, no comment to code diff 👍

I was able to catch the events after enabling the tracking under WooCommerce > Settings > Advanced > WooCommerce.com.

image

**Review by jessepearson — APPROVED** [review]
It's working! :shipit: 
Screen Shot 2021-09-23 at 8 34 52 AM
Screen Shot 2021-09-23 at 8 35 01 AM

**Comment by htdat** [comment]
@ismaeldcom - I see the checkbox todo after this PR merge has not been done. You might want to do it now?

**Comment by ismaeldcom** [comment]
Hey @htdat! I didn't add this because AFAIK "GS" don't have access to MC Tracks tool. I checked it like "(does not apply)" 🙂

**Comment by htdat** [comment]
😮‍💨 That makes sense. Sorry about the false-positive ping 😬

**Pull request merged**
