### PR TITLE
Remove public key encryption feature

### LINKED ISSUE #8839: Remove "Enable Public Key Encryption" setting
The purpose of the public key encryption setting + mechanism was to protect the intent's `client_secret` prior to confirmation, so that a payment could not go through via the processing of checkout using the exposed secret [[PR](https://github.com/Automattic/woocommerce-payments/pull/4782)].

enable-public-key-encryption-setting

This is no longer being used, as we no longer need the `client_secret` until after confirmation, so we could simplify the settings and code by removing it.

### PR DESCRIPTION
**Pull request by tpaksu**
Fixes #8839

#### Changes proposed in this Pull Request

This PR removes the client secret encryption feature from WooPayments, which implementing the deferred intent creation mode (server side intent confirmation and creation) removed the need for the feature. The feature was added on PR #4782 to ensure the client secret is encrypted before exposing to the client, so reusing it as a card testing method via direct calls to Stripe REST API wouldn't be possible. 

#### Testing instructions

* All automated tests, especially the E2E tests should pass.
* If there's any checkout scenario that isn't tested on the E2E tests, they need to be tested manually.

**UI test:**

* Checkout this branch
* Run `npm ci`, all should install correctly.
* Run `npm run build:client`, all should build correctly.
* Go to your local store's Payments > Settings page
* In the advanced section, there shouldn't be a Client secret encryption checkbox anymore.
* Settings should be saving successfully.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8847` or branch name `remove/8839-public-key-encryption` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=remove/8839-public-key-encryption) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 9563b50acfd055452ddf42c48212fa3573de30b8
- Build time: 2024-05-21 08:56:12 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by timur27 — APPROVED** [review]
Looks good, thanks for the changes @tpaksu! I also see you switched from `Is_a` to `instanceof` in `class-wc-payment-gateway-wcpay.php` 👍 [E2E tests](https://github.com/Automattic/woocommerce-payments/actions/runs/9171776537/job/25216855534#logs) don't seem to fail after this PR either.

**Comment by timur27** [comment]
@tpaksu as per our quick discussion and the small finding on the Blocks checkout, I'm happy to re-test the flow quickly once we find out the reason behind the error notice. Thank you!

**Comment by tpaksu** [comment]
@timur27 thanks for your reviews, we've checked and figured out that the error also happens on the develop branch, so it isn't something related with this PR. If you're OK, I'm going to merge this.

**Review by timur27 — APPROVED** [review]
Thanks @tpaksu! Looks good to me!

**Pull request merged**
