### PR TITLE
Refactor WC_Payment_Gateway_WCPay Part 1

### PR DESCRIPTION
**Pull request by leonardola**
#### Changes proposed in this Pull Request
Related to #823 
This PR is the first part of a series of refactors of the WC_Payment_Gateway_WCPay class.

#### Testing instructions
- With test mode active
- Go to WooCommerce > Payments
- Make sure the notice `Test mode active: All transactions are simulated. Customers can't make real purchases through WooCommerce Payments.` shows up

- Go to plugins
- Make sure the Settings link shows up and works

- Make [is_available_for_current_currency](https://github.com/Automattic/woocommerce-payments/blob/3d81b3467672c989c9143a16673adb4c4b0d72b1/includes/class-wc-payment-gateway-wcpay.php#L504) return false
- Make sure the `Unsupported currency: The selected currency is not available for the country set in your WooCommerce Payments account.` notice shows up on wp-admin

- As a shopper add a product to the cart
- Make sure you can see the card inputs
- Test again using UPE

- As a shopper buy any product
- As a shopper buy any product using WooPay

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Review by malithsen — CHANGES_REQUESTED** [review]
Nice work so far! 
This is not a full review, but I noticed some issues in my initial testing and wanted to get them out earlier. 

UPE checkout is broken. There is a reference to `parent::get_payment_fields_js_config` in `class-upe-payment-gateway` which we need to update to point to the correct class. This is breaking the UPE checkout for me at the moment.

While I did not manually test this, judging from the failing unit tests, it looks like wcpay onboarding is broken. It seems like we just need to update some broken references there as well.
```
WC_Payments_Account_Test::test_maybe_redirect_to_onboarding_account_error
Failed asserting that exception of type "Error" matches expected exception "Exception". Message was: "Class 'WC_Payments_Admin_Settings' not found" 
```

 Both above issues look straightforward to fix, and again great work in splitting the wcpay gateway class 👍

**Comment by leonardola** [comment]
@malithsen the errors seen on the e2e tests here started to happen after the last merge from develop. Discussion at p1665665849068839-slack-C026J0AL8NS. I've ran the tests before merging and they were all passing. So I think this is good to be reviewed

**Review by malithsen — COMMENTED** [review]
@leonardola New changes look good, and UPE checkout and onboarding are now functional. I noticed that wcpay-dev-tools is throwing an error as it relies on `WC_Payment_Gateway_WCPay::get_settings_url()`. Would there be other plugins that will break because of these changes? I am not sure of the best way to handle this, one option might be to keep the original public methods, but mark them deprecated and call the new functions internally.

**Comment by leonardola** [comment]
@malithsen yesterday I created this [PR](74-gh-Automattic/woocommerce-payments-dev-tools) to fix WC Pay dev tools and forgot to mention it here.

I've re-added the public functions. 

I haven't re-added `add_all_payment_methods_logos_column` and `add_all_payment_methods_icon_logos` because they were only being used by hooks and they were removed on #2530

I didn't re-add `display_test_mode_notice` and `display_not_supported_currency_notice` because they were also only being used by hooks. 

All those functions don't seem like functions that would be used by other plugins but I am ok to re-add them again in case you think that's better.

**Review by malithsen — APPROVED** [review]
Looks great now. I didn't notice any more regressions. Let's bump the versions in function deprecation notices to the correct version before the merge.

**Pull request merged**
