### PR TITLE
update: payment method fees in one line in settings

### LINKED ISSUE #9270: Payment method price bubble sizes vary in width even though the copy length is the same or similar
### Describe the bug
Most of the pricing has the same copy, same length yet the bubble sizes vary.

### Screenshots
image

### Expected
@nikkivias you'd expect these to all be equal in size?

### PR DESCRIPTION
**Pull request by frosso**
Fixes https://github.com/Automattic/woocommerce-payments/issues/9270

#### Changes proposed in this Pull Request

Displaying the fees into one line, instead of allowing them to wrap

Before:
Screenshot 2024-08-19 at 2 08 33 PM

After:
Screenshot 2024-08-20 at 12 19 55 PM
Screenshot 2024-08-20 at 12 19 40 PM
Screenshot 2024-08-20 at 12 19 30 PM

#### Testing instructions

- Go to the settings page https://github.com/Automattic/woocommerce-payments/issues/9270
- The fees will be displayed into one line

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9287` or branch name `refactor/payment-method-fees-oneline` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=refactor/payment-method-fees-oneline) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 0c66458b072c5c985865f09b12431cd7f7606dc4
- Build time: 2024-08-21 14:09:49 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by brettshumaker — APPROVED** [review]
:🚀

**Comment by pierorocca** [comment]
Much better! My remaining nitpick is the bubbles are of different sizes for a max. 3 character difference. Can live with that until we move to new settings pages.

**Comment by pierorocca** [comment]
@nikkivias any chance you have an alternative that could take this to the next level until we get payment settings refreshed?

**Pull request merged**
