### PR TITLE
PO Form UX & Copy Tweaks

### LINKED ISSUE #6741: PO UX & copies feedback from "LT/DRI weekly meeting"
July-11-2023 "New WCPay Active Merchants: DRIs <> LT Weekly Sync"
The team reviewed the new TOFU & PO UX, and had the following UX and Copy suggestions:

1) "Inconsistent punctuation (periods) usage on this screen"
Screenshot 2023-07-11 at 9 16 58 AM

2) "Consider using another word 'stakeholder' rather than 'shareholder' in this instruction"
Screenshot 2023-07-11 at 9 19 04 AM

should be fairly simple updates.

cc @daquinons  @elizaan36

### PR DESCRIPTION
**Pull request by dmallory42**
Fixes #6741 

#### Changes proposed in this Pull Request

- Some minor copy fixes based on the feedback in #6741.

Screenshot 2023-07-17 at 15 14 13

Screenshot 2023-07-17 at 15 14 18

Screenshot 2023-07-17 at 15 16 25

Screenshot 2023-07-17 at 15 16 38

Screenshot 2023-07-17 at 15 16 39

#### Testing instructions

* Check the supplied screenshots and verify that they match expectation.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6793` or branch name `dev/6741-po-copy-tweaks` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=dev/6741-po-copy-tweaks) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 7e7e14fc0654b9bc9a14cfff6721d97c3fb08668
- Build time: 2023-07-17 14:24:56 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by elizaan36 — APPROVED** [review]
Looks good to me!

**Review by daquinons — APPROVED** [review]
Ship it! :D

**Comment by dmallory42** [comment]
Thanks both! Shipping!. 🚀

**Pull request merged**
