### PR TITLE
Hide helper text related to Storefront theme in Multi-Currency settings when Storefront is not the active theme

### LINKED ISSUE #6182: With non-Storefront theme, multi-currency settings look off
### Describe the bug

Using WC Pay's multi-currency settings page, the Store settings section looks a bit off with a non-Storefront theme enabled.

With Storefront:

Screenshot taken on 2023-05-01 at 19 21 55 UTC@2x

Any other theme:

Screenshot taken on 2023-05-01 at 19 22 45 UTC@2x

The second line is accurate in that the widget is still available, but it just looks a bit odd like that on two lines. Maybe make both of those sentences on the same line?

### To Reproduce

1. WC Pay test site with WC Pay multi-currency and Storefront enabled.
2. Check `wp-admin/admin.php?page=wc-settings&tab=wcpay_multi_currency`.
3. See the first screenshot above.
4. Activate a different theme (e.g. Twenty Twenty-Two).
5. See the second screenshot above.

There's no real functional "bug" per se, everything works. It just looks a little weird?

### PR DESCRIPTION
**Pull request by jessepearson**
Fixes #6182

#### Changes proposed in this Pull Request

This PR will hide the helper text that went with the checkbox to enable the currency switcher on the Storefront theme:

Screenshot taken on 2023-05-01 at 19 21 55 UTC@2x

* Updates both the Multi-Currency settings page and onboarding wizard.
* The change just moves the closing parenthesis for the `true` response to be later so that it includes the `div` that holds the helper text.
* Additional _prettier_ formatting was applied.

#### Testing instructions

* Enable the Storefront theme on your site under Themes.
* Navigate to WooCommerce > Settings > Multi-Currency.
* Confirm the option to enable the currency switcher on the Storefront theme shows in the Store Settings.
* Navigate back to Themes and change your theme to one that is not Storefront.
* Navigate back to WooCommerce > Settings > Multi-Currency.
* Confirm the option to enable the currency switcher on the Storefront theme and its helper text no longer show in the Store Settings.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7336` or branch name `fix/6182-hide-storefront-tooltip` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/6182-hide-storefront-tooltip) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 63e77dc68cdaebadeb2a2ff92eb16a9044ac3068
- Build time: 2023-10-05 11:10:11 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by tpaksu** [comment]
@jessepearson I think the same problem also may exist on the MC onboarding page. Can you also fix that in this PR, so we don't return back to this in the future?

**Comment by jessepearson** [comment]
> I think the same problem also may exist on the MC onboarding page. Can you also fix that in this PR, so we don't return back to this in the future?

This was updated in this PR, that's what this is: https://github.com/Automattic/woocommerce-payments/pull/7336/files#diff-c7982e2ab02e0f981c2af11408001d8051a877370c9226be0c57c786311aba5cL130

You're referring to the wizard at `wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fmulti-currency-setup` right?

**Comment by tpaksu** [comment]
Yes, I'm referring to that file, sorry missed that one. I'll review this in a couple.

**Comment by jessepearson** [comment]
> Yes, I'm referring to that file, sorry missed that one. I'll review this in a couple.

No worries. I am not sure how often that wizard is even used.

**Review by tpaksu — APPROVED** [review]
Onboarding when theme is Storefront:
image

Onboarding when theme is NOT Storefront:
image

MC Settings when theme is Storefront:
image

MC Settings when theme is NOT Storefront:
image

LGTM! :shipit:

**Comment by jessepearson** [comment]
@tpaksu I fixed the styling issue in the wizard in https://github.com/Automattic/woocommerce-payments/pull/7336/commits/0329aeca9326ce6e610b9a8fabe33d427cf3f30a :

Screenshot 2023-10-04 at 12 07 04 PM

Can you give this a quick look, then I can get it merged. Thank you 😁

**Comment by tpaksu** [comment]
Yep, I can see the change. Thanks for fixing this!

image

**Pull request merged**
