### PR TITLE
Update .org icons and banners to new purple ones

### PR DESCRIPTION
**Pull request by kloon**
#### Changes proposed in this Pull Request

* Update the .org listing banners and icons to the new ones featuring the new Woo Purple as per https://woomarketingp2.wordpress.com/2020/08/15/woocommerce-plugins-new-icons-header-images/

#### Testing instructions

* N/A

-------------------

- [ ] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

### CODE REVIEW

**Review by dwainm — APPROVED** [review]
LGTM

**Comment by dechov** [comment]
Not sure if or how much it could matter but `icon-128x128.png` has an extra column on the right side.

**Comment by kloon** [comment]
@dechov nice catch. @slobtsov can you please correct the images? I am noticing slight canvas bleeding on all of the images, the icon-128x128.png one has the biggest noticeable bleeding.

**Comment by slobtsov** [comment]
@dechov thank you for catching it! Apparently, there is a weird bug in the Figma export (design software I'm using), the exported artboard needs to be on the x0y0 coordinates on the art canvas, overwise it glitches and adds an extra pixel to the exported assets!
@kloon here is an updated archive with re-exported icons and banners - 
[New Woo Icons and Banners.zip](https://github.com/Automattic/woocommerce-payments/files/5367751/New.Woo.Icons.and.Banners.zip)

**Review by dechov — APPROVED** [review]
Bleeding edge design work nonetheless 😄

**Comment by dwainm** [comment]
@vbelolapotkov we may need to do a manual copy to ensure these are updated on .org, not sure if Woo Deploy handles these.

**Comment by vbelolapotkov** [comment]
Merged to prepare for release.

**Pull request merged**
