### PR TITLE
Start 2.7.0 change log

### PR DESCRIPTION
**Pull request by jrodger**
Add the new 2.7.0 header and move items that weren't released in 2.6.0 into the 2.7.0 section.

### CODE REVIEW

**Review by vbelolapotkov — APPROVED** [review]
LGTM! I suppose the same changes need to be applied to readme before merging?

**Comment by jrodger** [comment]
> I suppose the same changes need to be applied to readme before merging?

🤦 ...every time. Thanks for checking!

**Review by vbelolapotkov — APPROVED** [review]
Thanks! :shipit:

**Comment by vbelolapotkov** [comment]
@jrodger sorry for stepping in, but merging it to unblock other changes targeting 2.7.0

**Pull request merged**
