### PR TITLE
Fix price on payment request for variable subscription products

### LINKED ISSUE #3536: Apple Pay and Google Pay buttons not showing correct dollar amount on product page
### Describe the bug
Using a variable subscription product of WooCommerce Subscriptions, say with options for $4, $5, and $9 per month, the Apple Pay and Google Pay (aka Express Checkout) buttons always show the $4 amount.  I am using WooCommerce, WooCommerce Payments and WooCommerce Subscriptions.

### To Reproduce
1.  Go to a Woo product page that has several payment levels.
2.  Select a non-default option from the product drop-down (e.g. $9)
3. Click G Pay or Apple Pay.  $4 or some other default will be shown in the Apple Pay / G Pay preview rather than the $9 amount you just picked.
4. If you complete the purchase anyway, the $9 amount (whatever you picked in step 2 above) will be correctly charged to your Apple Pay/ G Pay, so this appears to be a display-only issue on the product page.
Note this issue is specific to the Apple Pay and Google Pay buttons on the Product page, NOT the Checkout Page. 
Tested on both iPhone Safari with Apple Pay and desktop Chrome with G Pay.  Same behavior in both instances.
Not clear if this is a WooCommerce Payments bug and/or a WooCommerce Subscriptions bug.

### Expected behavior
Dollar amount shown in G Pay / Apple Pay should stay synchronized with the amount picked by the user from the product drop-down.

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### PR DESCRIPTION
**Pull request by jessy-p**
Fixes #3536 

For variable subscription products the payment request on Product page was using base product price. Fixed the condition for getting the variation pricing, which did not check for 'variable-subscription'.

#### Changes proposed in this Pull Request

- added check for 'variable-subscription' so that variation price calculation is not skipped for subscription variations

#### Testing instructions

 - Go to a Woo product page that has a subscription product with variation, each with a different pricing.
 - Select a non-default option from the product drop-down 
 - Click G Pay or Apple Pay. 
 - The correct variation price should be shown in the Apple Pay / G Pay preview

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) : _Add link here / 'QA Testing Not Applicable'_

### CODE REVIEW

**Review by asumaran — CHANGES_REQUESTED** [review]
@jessy-p Code looks good but there's an issue when we setting up the "Default Form Values" option. 

Screen Shot 2022-03-29 at 8 39 43 PM

Notice the "medium" variation is set as default. The "Small" variation's price is `30` and the "medium" one is `40`.



As you can see, if we click the "Buy now" button right after the page loads (while the "medium" variation is selected). The price is incorrect. It should be `40`.


This doesn't happen with variable products though. So it must be something you need to fix elsewhere.

**Review by achyuthajoy — DISMISSED** [review]
~~Changes look good to me @jessy-p. Works as expected on a variable subscription single product page.~~ ~~

~~Ready to 🚢 ~~ ~~

Didn't notice the issue raised above. Revoking approval

**Review by achyuthajoy — COMMENTED** [review]
@jessy-p While testing I've noticed that if shipping/taxes are configured, it's applied to the default variation. However, if the variation is changed to a different one, shipping/taxes are not present on order details displayed in GPay.

Screenshot

Screenshot

**Comment by jessy-p** [comment]
> Code looks good but there's an issue when we setting up the "Default Form Values" option.

Thanks @asumaran  for catching this!
It was due to a similar missing condition in `get_product_data() `function. Have added that now, and it is working.

**Comment by jessy-p** [comment]
>While testing I've noticed that if shipping/taxes are configured, it's applied to the default variation. However, if the variation is changed to a different one, shipping/taxes are not present on order details displayed in GPay.

Thanks @achyuthajoy  This issue occurs on normal variation products too. The fix is unrelated to the changes in this PR. Could you raise a new issue for this?

**Comment by achyuthajoy** [comment]
> Thanks @achyuthajoy This issue occurs on normal variation products too. The fix is unrelated to the changes in this PR. Could you raise a new issue for this?

Sure @jessy-p I'll add a new issue for this one.

**Comment by achyuthajoy** [comment]
> > While testing I've noticed that if shipping/taxes are configured, it's applied to the default variation. However, if the variation is changed to a different one, shipping/taxes are not present on order details displayed in GPay.
> 
> Thanks @achyuthajoy This issue occurs on normal variation products too. The fix is unrelated to the changes in this PR. Could you raise a new issue for this?

Issue created here - https://github.com/Automattic/woocommerce-payments/issues/4064

**Review by achyuthajoy — COMMENTED** [review]
Changes looks good to me @jessy-p. I can confirm that the bug reported by @asumaran is solved with the changes you've made.

Let's wait for @asumaran's review before we can merge :)

**Review by asumaran — APPROVED** [review]
LGTM!

**Pull request merged**
