### PR TITLE
Fix explat not caching when no variation is returned

### PR DESCRIPTION
**Pull request by ilyasfoo**
#### Changes proposed in this Pull Request

This PR fixes Explat A/B test not saving the result of experiment API when there are no variations returned.

#### Testing instructions

1. Delete the transient `_transient_abtest_variation_wcpay_empty_state_preview_mode_v2`.
2. Modify the following to make sure you get the "control" variant:

https://github.com/Automattic/woocommerce-payments/blob/266f9056751146caa4e00aae6482d86dc48ea9af/includes/class-experimental-abtest.php#L127

```
$results = array( 'variations' => array( 'wcpay_empty_state_preview_mode_v2' => null ), 'ttl' => 7200 );
```
3. Navigate to anywhere within wp-admin.
4. Query for `_transient_abtest_variation_wcpay_empty_state_preview_mode_v2` transient in your `options` table, observe that it exists with the value `control`.

-------------------

- [x] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

### CODE REVIEW

**Review by adrianduffell — APPROVED** [review]
LGTM thanks @ilyasfoo!! 🚀

**Comment by adrianduffell** [comment]
@ilyasfoo I'll merge this now ahead of the code freeze.

**Comment by ilyasfoo** [comment]
@adrianduffell Ah thanks, I was waiting for the e2e tests to finish, but I guess something went wrong? Thanks anyway!

**Comment by adrianduffell** [comment]
@ilyasfoo No worries, I had to merge the latest `develop` to get the tests to start. Maybe related to this new PR check https://github.com/Automattic/woocommerce-payments/commit/fa372dfa118e1b5847cac436c7aae5642150da19

**Pull request merged**
