### PR TITLE
Disable activation of LPM's requiring additional currencies when MC is disabled

### LINKED ISSUE #7154: Onboarding LPM's which require additional currencies while MC is disabled
When someone is enabling a LPM that requires another currency that isn't the store currency, we should do one of two things:

* Enable MC by default and state it in that message.
* Inform them that they need to enable MC manually so that the additional currency can be added. 

If we don't do either one of these then they will not be able to take payments with the LPM.

_Originally posted by @jessepearson in https://github.com/Automattic/woocommerce-payments/issues/7141#issuecomment-1710261667_

#### Reproduce with:

- Set your store currency to USD on WooCommerce > Settings
- Disable MC from Payments > Settings > Advanced.
- Navigate to: http://localhost:8082/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fadditional-payment-methods
- Enable iDeal, or any payment method that operates with EUR
- MC should be activated, EUR should get enabled, and EUR is missing warning needs to be shown, but none of these happen.

#### Acceptance criteria

- You should see the "will enable EUR on your store" warning, but it doesn't display
- You should have MC enabled back
- You should have EUR enabled as a payment currency

### PR DESCRIPTION
**Pull request by tpaksu**
Fixes #7154

#### Changes proposed in this Pull Request

This PR implements the disabled checkboxes and tooltips feature for LPM's that require additional currencies that doesn't match with the store currency to operate, when the multi currency feature is turned off. The fix both applies the LPM activation box on Payments > Settings, and the LPM onboarding page.

- The notice displayed while MC is on and the LPM requires another currency to be enabled:

image

- The current screen when MC is off

image

- Suggested fix

image

- Suggested fix on the Payments > Settings page
 
image

#### Testing instructions

* Go to WooCommerce > Settings and change the store currency to "USD" if not selected.
* Go to Payments > Settings > Advanced and uncheck the "Enable Multi-Currency" checkbox.
* Save Changes.
* Navigate to http://localhost:8082/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fadditional-payment-methods
* See the onboarding page shows the LPM's which require additional currencies as disabled, with the correct tooltip.
* Go to Payments > Settings and see the same effect on the Additional payment methods box too.
* Change the store currency to "EUR" and see that the LPM's are enabled, but the ones requiring currencies other than EUR got disabled on both screens.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7211` or branch name `fix/7154-onboarding-lpms-while-mc-is-disabled` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/7154-onboarding-lpms-while-mc-is-disabled) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 5bbddd0d35018eaf83f6f8e4a79eaaf7d169f132
- Build time: 2023-10-31 11:48:29 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by elizaan36 — COMMENTED** [review]
@tpaksu We discussed this in Slack. I think the wording can be tweaked based on whether MC is required.

Also, the most important thing is that once merchants are in settings they have a clear indication of what to do next. We can use this design pattern that's consistent with other payment methods that need additional steps for setup. The error icon presents a tooltip on hover. Discussed in `paJDYF-9Mc#comment-20802`
 
image

**Comment by tpaksu** [comment]
@elizaan36 thanks for the info, so we'll be removing the global notice and adding warning icon with tooltips instead per LPM to fix this issue, right?

**Comment by elizaan36** [comment]
hey @tpaksu I think the notice should remain in the modal to warn merchants about the situation. However, the settings pattern (warning icon with tooltip per LPM) is important as it's persistent once they've closed out of the modal.

Based on the Slack thread, I think the language in the modal could be tweaked to something like this,

> iDEAL requires the EUR currency. In order to enable the payment method you must add this currency to your store.

**Comment by tpaksu** [comment]
@elizaan36 they can't work together, as we'll be disabling selecting the LPM's with currency needs, and they won't be able to see the notice without being able to select them. And having them selected in onboarding, but not on the settings screen will be another issue. I suggest removing the notice and going with the checkbox -> warning icon replacement, and the tooltips. Or having them all checkable and showing the notice (as it is currently), without the tooltips. 

IMO, UX wise, letting them select the LPM's, showing the notice, suggesting them to enable the currency via a pill on the right side of the LPM title, stating something like `Needs EUR currency` and showing the tooltip on that with the `Learn more` link, will be a better solution.

**Comment by elizaan36** [comment]
> I suggest removing the notice and going with the checkbox -> warning icon replacement, and the tooltips.

This seems like the clearest pattern to indicate when a payment method requires more setup. Showing the checkbox indicates that the payment method can be enabled when in fact it can't.

Let's go with this approach for now and I'll ping @rikmantel since he's taking a look at Multi Currency setup in the near future. Rik, could you take a closer look at this setup flow - the use case is when the Multi Currency extension has been deactivated, then the merchant tries to enable payment methods with WooPayments.

**Comment by tpaksu** [comment]
@elizaan36 gotcha. Now to summarize what I understood: 

- If multi currency is enabled, we show the checkboxes, because when they select the LPM, the onboarding flow will automatically add the required currencies to the system. And when they select an LPM that requires another currency enabled, they'll see the notice.
- If multi currency is disabled, we disable the checkboxes, and show a tooltip that the LPM requires another currency active. And they because they can't select those, the notice won't be shown in any way.

And @rikmantel, welcome to the team! Looking forward to work with you!

**Comment by elizaan36** [comment]
Sounds good to me. You could use copy similar to what I proposed for the notice for the tooltip.

> iDEAL requires the EUR currency. In order to enable the payment method you must add this currency to your store.

**Comment by tpaksu** [comment]
@elizaan36 how does it look? 

image

And for multiple currencies on P24:
image

**Comment by jessepearson** [comment]
Noting that in testing this that if Multi-Currency is enabled and a currency is not enabled, we automatically enable the currency without a note to the merchant if they are enabling the additional payment method _outside_ of the wizard. I felt like I had come across this before, and I found where I asked about that here: p1684498606483579-slack-C01B8KNUYSW

**Review by jessepearson — APPROVED** [review]
LGTM! Works as described. I added a comment in the PR itself, but that's unrelated to this code, as it's an issue that's present on `develop`.

**Comment by tpaksu** [comment]
@jessepearson thanks for the review, I'll wait for @elizaan36's approval for merging this in. If Elizabeth approves it while I'm AFK, feel free to merge it.

**Review by elizaan36 — COMMENTED** [review]
Copy looks good to me. @tpaksu Could you share a screenshot of the tooltip in a mobile view? There's an accessibility issue that we worked on with this component. I believe @mordeth solved for this with another payment method that required the tooltip.

**Comment by jessepearson** [comment]
> Could you share a screenshot of the tooltip in a mobile view? There's an accessibility issue that we worked on with this component.

@elizaan36 Sorry for the late reply here, this is what I am seeing through the Chome dev tools when tapping on the payment method.

Screenshot 2023-10-12 at 12 16 04 PM

**Comment by elizaan36** [comment]
thanks for sharing @jessepearson! The tooltip looks off kilter.
Is it possible to create multiple positioning options for the arrow, so it can point left/right and up/down to be aligned with the icon that triggers it?

**Comment by tpaksu** [comment]
@elizaan36 possibly possible, but not on this PR :)

**Comment by tpaksu** [comment]
@jessepearson on Chrome's developer tools, when I switch to mobile view, the arrows don't show up. Which browser did you use? It may also be something coming with the latest pushes. I merged the latest develop to this branch, and even on the desktop view, the arrows don't show anymore. Interesting. 

@elizaan36 will it be OK to push it like it is now?

# Settings screen

image

image

# LPM Onboarding

image

image

**Comment by elizaan36** [comment]
Yes, this looks good! The arrow was removed [in this PR](https://github.com/Automattic/woocommerce-payments/pull/7515) when the mobile view was fixed.

**Pull request merged**
