### PR TITLE
Add setting to disable customer multi currency feature

### LINKED ISSUE #2906: Create setting option to disable Multi-Currency
### Describe the bug
If a merchant is using WCPay and a different Multi-Currency plugin, there can be conflicts. Presently a merchant has to use a filter to disable MC, which isn't ideal and support does not help with customizations like this. This happened and was discussed last week here: p1631274038411900-slack-C01B8KNUYSW

Option can be added under the Advanced Settings in WooCommerce Payments' settings:

Markup 2021-09-10 at 08 48 56

cc @LevinMedia for design input

### PR DESCRIPTION
**Pull request by tpaksu**
Fixes #2906

#### Changes proposed in this Pull Request

Add a setting to *WooCommerce > Payments* page, Advanced settings section to enable toggling the status of Customer Multi Currency feature 

This setting enables the merchant to disable customer multi currency feature bundled with WooCommerce Payments plugin, to prevent conflicts with other multi currency plugins the merchant is already using. This occured in one of the tickets we received (4283071-zd-woothemes) and discussed in thread p1631274038411900-slack-C01B8KNUYSW which @jessepearson created a gist (https://gist.github.com/jessepearson/0a4a2da18bdeef20b80b50ff0e727c61) for the user to temporarily fix the issue. This PR is removing the need for that code to be added to user's `functions.php` file.

The setting looks like:

image

##### Automatic testing

* Run `npm run test:js multi-currency-toggle``

##### Manual testing 

* Open `WooCommerce > Payments` page
* Scroll down to see the Advanced link, click it
* On the revealed form, uncheck the `Enable customer multi currency` toggle
* Save the changes
* Refresh the page and check if the *Multi-Currency* tab is still visible. It should be removed.
* On the same form, enable the checkbox back and save.
* Refresh the page and expect the *Multi-Currency* tab is back in its place again.

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply)

### CODE REVIEW

**Comment by tpaksu** [comment]
@LevinMedia I put some placeholder texts to the checkbox, and the location that the checkbox should appear isn't concrete yet, so can you review this and conduct me to a more suitable application of it :)

**Review by LevinMedia — COMMENTED** [review]
@tpaksu thanks! I think you can remove the header and just leave the lable next to the check box, which would read s same as the header does now: 

"Enabled multi-currency"

The helper text can read: "Allow customers to shop and pay in multiple currencies. Learn more" The learn more will link to the docs.

**Comment by tpaksu** [comment]
@LevinMedia you mean "Enable multi-currency", or is "Enabled multi-currency" right there? I think it may be a typo. Thanks for the clarification!

**Comment by tpaksu** [comment]
The new implementation looks like this:

image

Done in 258efaa.

**Review by LevinMedia — APPROVED** [review]

**Review by jessepearson — APPROVED** [review]
LGTM! Functions as expected, disables MC through a toggle. Thanks for taking this on 😁

**Pull request merged**
