### PR TITLE
Fix typo in payment collected notice

### PR DESCRIPTION
**Pull request by jrodger**
Just a quick type fix.

Visual inspection and making sure the unit tests run in the CI process should be sufficient review.

### CODE REVIEW

**Review by dmvrtx — APPROVED** [review]
Approving as this seems to be an innocuous change.

However, E2E tests are broken on any PR right now and I wonder if it is better to turn them off until a solution is found.

**Review by haszari — APPROVED** [review]
Thanks for catching this and successfully repairing the string @jrodger !

**Comment by haszari** [comment]
> However, E2E tests are broken on any PR right now and I wonder if it is better to turn them off until a solution is found.

That's worth considering - maybe log an issue or discuss in slack.

**Comment by jrodger** [comment]
> Thanks for catching this and successfully repairing the string @jrodger !

I needed a quick win 😆

**Pull request merged**
