### PR TITLE
remove unnecessary tracks events for acceptDispute submit success/fail

### LINKED ISSUE #8064: `wcadmin_wcpay_dispute_accept_*` tracks events don't track a user action and should be removed
### Describe the bug
As part of reviewing and registering tracks events related to disputes, I discovered the following two events:

- `wcadmin_wcpay_dispute_accept_success`
- `wcadmin_wcpay_dispute_accept_failed`

These are [fired from within a redux action that handles POSTing disputes](https://github.com/Automattic/woocommerce-payments/blob/f1a2d7c81570fc1c4eeb09abeb05cc710a226fc8/client/data/disputes/actions.js#L50). They track whether the submit succeeds or fails, which is not a user action. 

Tracks events are best for tracking user actions – e.g. button clicks or page/component views. I suggest we remove these events, and if we need to log this info, find a way to do so.

### PR DESCRIPTION
**Pull request by haszari**
Fixes #8064

#### Changes proposed in this Pull Request

This PR removes two events that are fired as part of request handling, and don't represent user actions.

- `wcadmin_wcpay_dispute_accept_success`
- `wcadmin_wcpay_dispute_accept_failed`

If we want to measure merchant behaviour when wrangling disputes, there are other events we can use (which track true user actions): 

- Merchant views transaction details page => accepts dispute: `wcadmin_page_view[page=transaction_details] > wcpay_dispute_accept_click`

#### Testing instructions
- Ensure your site is set up to send tracks events and you have a way to view fired events
- View a transaction details page for a live dispute
- Accept the dispute
- Ensure the `wcadmin_wcpay_dispute_accept_*` events are not fired
- Explore various dispute flows and ensure that relevant user actions are captured with events (e.g. merchant action to accept a disputes)

-------------------

#### Checklist

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8068` or branch name `fix/remove-dispute-accept-log-tracks-events` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/remove-dispute-accept-log-tracks-events) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 9c57780229c96b240f3acf6b8c181dc38fc87655
- Build time: 2024-01-24 23:58:32 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by haszari** [comment]
Still in progress on testing instructions and checking with @souravdebnath1986 / others that we don't actually need these events. Reviews welcome, the code is good to go and testable IMO!

**Review by brucealdridge — APPROVED** [review]
Changes not tested, code reviews well. 👍

**Comment by haszari** [comment]
Checked with @souravdebnath1986  and he's not using these for anything … merging! 🔥

**Pull request merged**
