### PR TITLE
Add helper to get request button handler class instance.

### LINKED ISSUE #2973: Customer facing prices compatibility with Name Your Price
### Description

The [Name Your Price](https://woocommerce.com/products/name-your-price) plugin enables a customer to enter a custom price for a product. Ideally, I'd like to see this price entered be the price that the payment request buttons use.. and enable/disable the request buttons when the price is not valid. 

In the short-term, I could get by with a way to disable the display of the request buttons on products that do not support them.

### Acceptance criteria

Long term
- [ ] Enable/disable buttons when price is/not valid
- [ ] Send dynamic price to payment processor

Short term
- [ ] PHP filter to disable display of buttons where not supported

### Testing instructions

1. Create a name your price product
2. Click on request buttons (apple/google pay) on single product page
3. see $0 price regardless of what price you've entered. 

### Additional context
https://woothemes.zendesk.com/agent/tickets/4313225 - while not much info is provided there, they've submitted a new ticket to contact me directly and explained their issue as $0 payments no matter what price is entered.

### PR DESCRIPTION
**Pull request by helgatheviking**
Fixes #2973 (short-term patch)

#### Changes proposed in this Pull Request

Add a class method to return the `WC_Payments_Payment_Request_Button_Handler` instance.

In the very short term, this would allow me to remove the payment request buttons on a product that uses Name Your Price since request buttons are not yet capable of getting the dynamically entered price.

#### Testing instructions

This snippet should remove the payment request buttons on simple products. 🤞 
```
/**
 * Remove Stripe's payment request buttons
 */
function kia_remove_request_buttons() {
    
    global $product;

    if ( is_callable( array( 'WC_Payments', 'get_payment_request_button_handler' ) ) && $product instanceof WC_Product && $product->is_type( 'simple' ) ) {
        remove_action( 'woocommerce_after_add_to_cart_quantity', [ WC_Payments::get_payment_request_button_handler(), 'display_payment_request_button_html' ], 1 );
        remove_action( 'woocommerce_after_add_to_cart_quantity', [ WC_Payments::get_payment_request_button_handler(), 'display_payment_request_button_separator_html' ], 2 );
    }

}
add_action( 'woocommerce_after_add_to_cart_quantity', 'kia_remove_request_buttons', -1 );
```

### CODE REVIEW

**Comment by helgatheviking** [comment]
That's correct. #3325 was my second attempt and is my preference. 

But being able to grab the instance of this class would then also make it possible to remove the hooks that the class is adding... So just a different way to disable these buttons in places where the buttons aren't supported.

If #3325 is merged, this isn't needed.. though I think it's a decent idea to be able to access class instances for extensibility in general.

**Comment by htdat** [comment]
👋 Hi @helgatheviking, thanks for providing more context to this PR.

> If #3325 is merged, this isn't needed... though I think it's a decent idea to be able to access class instances for extensibility in general.

Agreed that WCPay should be open for extensibility in general. However, in this specific case, I am not sure if we have enough use cases to get benefits with accessing class instances.

I would say we can review this idea when we see more benefits of allowing this access. If that happens, WooCommerce Payments team also needs to have extensive review and ensure the change has as less side effects as possible.

**Comment by helgatheviking** [comment]
> I am not sure if we have enough use cases to get benefits with accessing class instances.

Maybe/maybe not. We'll never know all the possible use cases. But being able to access any classes that are adding hooks/filters feels like good practice with respect to making the plugin open for other plugins to integrate with. This plugin is intentionally obfuscating hooks/filters. 

If #3325 is merged I no longer have an urgent need for this, but at the same time... what is the downside to making the plugin more accessible to fellow developers? There's no downside here because you aren't changing your functionality at all. The onus is on other developers to not break things... as it always has been.

**Comment by vbelolapotkov** [comment]
> > I am not sure if we have enough use cases to get benefits with accessing class instances.
> 
> Maybe/maybe not. We'll never know all the possible use cases. But being able to access any classes that are adding hooks/filters feels like good practice with respect to making the plugin open for other plugins to integrate with. This plugin is intentionally obfuscating hooks/filters.

@helgatheviking you're right, we'll never know all the possible use cases, however, I can't fully agree that access to **any** classes is a good practice. We want to be mindful about exposed API for extensibility (classes, hooks, instances, etc) and make such decisions with extra care, because it's hard to maintain backward compatibility and  revert such changes if necessary. 


> If #3325 is merged I no longer have an urgent need for this, 

Glad you can move forward now with #3325 merged.


> but at the same time... what is the downside to making the plugin more accessible to fellow developers? There's no downside here because you aren't changing your functionality at all. The onus is on other developers to not break things... as it always has been.

I hope I highlighted the downsides above. Those might affect the plugin and store stability due to the importance of payment service on the store. I think we'll be able to come up with good enough solution for extensibility without sacrificing the reliability of the merchants' stores.

Anyway, I want to thank you for submitting the PR and expressing the need for the plugin extensibility. So I'd appreciate if you share with us any additional cases or needs to extend the plugin.

**Comment by helgatheviking** [comment]
@vbelolapotkov 

>because it's hard to maintain backward compatibility and revert such changes if necessary.

I respect this... I too am super conservative when it comes to deciding what goes in to my plugin as I am aware that most additions are permanent.

>however, I can't fully agree that access to any classes is a good practice.

I disagree here. I think that any class that is adding hooks/filters should allow devs to unhook/unfilter those things. I know that devs can do some wild things, but the onus is on us to not break things.

A good example, is `WC_Payments_Multi_Currency()` exists to return an instance of the multi-currency class. So, in theory, it gives devs access to that class, which makes extensibility much easier (or would if not for [this issue](https://github.com/Automattic/woocommerce-payments/issues/3507#issuecomment-1057149254)) 

But in the end, my compatibility needs are solved by #3325 so I am not going push this. :)

**Comment by vbelolapotkov** [comment]
> I think that any class that is adding hooks/filters should allow devs to unhook/unfilter those things

That's fair point, and it doesn't conflict with idea of not providing access to **any** class 🙂 Unfortunately, there is no clear boundary of "public" vs "internal" classes in the plugin yet. Once we have it, it'll be much easier to provide ways of accessing any "public" class for extending and customizing plugin behavior.

> But in the end, my compatibility needs are solved by https://github.com/Automattic/woocommerce-payments/pull/3325 so I am not going push this. :)

Anyway, glad you've been unblocked. Are you ok with closing this PR?

**Comment by helgatheviking** [comment]
Lost track of this so clearly no longer a pressing issue.

**Pull request closed without merging**
