### PR TITLE
Adjustments to the wording of confirmation modals on the order and transaction details pages

### LINKED ISSUE #8243: Multiple modals alignment on used wording
### Describe the bug

In pdjVC1-2bG-p2 we identified the changes needed for some of the dialogs. Here short list of the changes we need
- pdjVC1-2bG-p2#comment-2849 (Title and buttons wording alignment, a dialog content actualization)
- pdjVC1-2bG-p2#comment-2856 (a dialog content actualization)
- pdjVC1-2bG-p2#comment-2858 (Title should be sentence cased)

### Additional context

- pdjVC1-2bG-p2

### PR DESCRIPTION
**Pull request by mgascam**
Fixes #8243 

#### Changes proposed in this Pull Request

Adjustments to the wording of the following confirmation modals:

**Enable manual capture**
| Before | After |
|--------|--------|
| Screenshot 2024-02-22 at 13 22 44 | Screenshot 2024-02-22 at 13 20 50 | 

**Capture payment**

| Before | After |
|--------|--------|
|Screenshot 2024-02-22 at 13 29 13 |Screenshot 2024-02-22 at 13 27 40| 

**Cancel payment**

| Before | After |
|--------|--------|
| Screenshot 2024-02-22 at 13 29 02 | Screenshot 2024-02-22 at 13 27 26 | 

**Refund transaction**

| Before | After |
|--------|--------|
| Screenshot 2024-02-22 at 13 29 48 | Screenshot 2024-02-22 at 13 31 05 | 

#### Testing instructions

I'm adding the before/after screenshots above to facilitate the review. Changes are restricted to strings so no functionality is changed. In case you want to manually test:

* In WP Admin, enable the capture later option. The modal should be the same as **Enable manual capture** above
* As a shopper, place an order.
* As a merchant go to the order details page.
* Change the status of the order to Cancelled and check the **Cancel payment** modal.
* Change the status of the order to Completed and check the **Capture payment** modal.
* Capture the payment and go to the transaction details page. Check the **Refund transaction** modal.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8244` or branch name `update/8243-multiple-modals-alignment-on-used-wording` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=update/8243-multiple-modals-alignment-on-used-wording) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: c8f06ccc60ae3f89b838858a1452dd0b39d5c190
- Build time: 2024-02-23 12:19:22 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by kalessil — APPROVED** [review]
LGTM! We can merge once we get more reviews. or confirmation in the P2.

**Review by elizaan36 — APPROVED** [review]
LGTM. 

Just one question, For the 2 auth capture modals do you think we should say "This order has been authorized but payment has not been captured yet." ? That seems more accurate.

**Comment by mgascam** [comment]
> but payment has not been captured yet

Yes, that's more precise thanks for the suggestion @elizaan36. This is how it looks after this change https://github.com/Automattic/woocommerce-payments/pull/8244/commits/d4d01e66554af40c758957a0eec6830ccf6df9f8

**Capture payment**
Screenshot 2024-02-22 at 17 53 35

**Cancel payment**
Screenshot 2024-02-22 at 17 54 30

**Comment by csmcneill** [comment]
@mgascam I was AFK so didn't have a chance to review this.

These changes look great and align with what was discussed in P2!

I did notice that the capture payment and cancel payment modals indicate (emphasis mine):

> This **order** has been authorized

However, it's the payment that has been authorized — not the order.

Perhaps replacing `order` with `payment` and removing `payment` from the hyperlink component is a better approach for accuracy.

This would (potentially) mean changing [L65](https://github.com/Automattic/woocommerce-payments/blob/c8f06ccc60ae3f89b838858a1452dd0b39d5c190/client/order/order-status-change-strategies/index.tsx#L65) to...

```
			'This payment has been {{authorizedNotCaptured/}} yet. Changing the status to ' +
```

...[L79](https://github.com/Automattic/woocommerce-payments/blob/c8f06ccc60ae3f89b838858a1452dd0b39d5c190/client/order/order-status-change-strategies/index.tsx#L79) to...

```
						'authorized but has not been captured',
```

...[L134](https://github.com/Automattic/woocommerce-payments/blob/c8f06ccc60ae3f89b838858a1452dd0b39d5c190/client/order/order-status-change-strategies/index.tsx#L134) to...

```
			'This payment has been {{authorizedNotCaptured/}} yet. Changing the status to ' +
```

...and [L148](https://github.com/Automattic/woocommerce-payments/blob/c8f06ccc60ae3f89b838858a1452dd0b39d5c190/client/order/order-status-change-strategies/index.tsx#L148) to...

```
						'authorized but has not been captured',
```

...but I'd love to hear y'all's thoughts :)

**Comment by kalessil** [comment]
@elizaan36 WDYT about Chris' proposal here?

**Comment by elizaan36** [comment]
I do think it's nuanced since the payment is being authorized but from the user perspective they may think that's one and the same with the order. 

The copy should mention "order" somewhere since the user is taking action on the order, so if the copy is changed to Chris's suggestion, "Payment has been authorized but not captured yet", then we should say "changing the _order_ status" to make it a bit more clear.

**Comment by kalessil** [comment]
Gotcha, thank you for double-checking @elizaan36 !

**Pull request merged**
