### PR TITLE
Use a proper mechanism to determine when the page is loaded after paying for order

### PR DESCRIPTION
**Pull request by timur27**
Fixes https://github.com/Automattic/woopay/issues/1691

#### Changes proposed in this Pull Request
This PR replaces `uiUnblocked();` with `waitUntil: 'networkidle0',` in the E2E test for the _Pay for order_ page. The former was wrongly used, as it should be considered an option for checking a loading state within the page, but not the page reload. In the effect, it seems that the test was looking for `Order received` text too early. Since `networkidle0` is generally considered the most reliable option for determining when a page is fully loaded and ready for further testing, it should be the solution. The post-fix test runs described below confirm this.

#### My results
I've run a command that consequently runs the test 20 times to gather some metrics of the problem and confirm the test's flaky-ness.

Before the fix, 20 test runs gave us:
* 12 successful results
* 3 failures because of the connection reset (these failures can be ignored)
* 5 failures due to `TimeoutError: Text not found "Order received"`

After the fix: 
* 17 successful runs
* 3 failures because of the connection reset (these failures can be ignored)

#### Testing instructions
1️⃣ On your local environment, checkout to `develop` and run the following command in your terminal:

```
for i in {1..20}; do
  npm run test:e2e tests/e2e/specs/wcpay/shopper/shopper-pay-for-order.spec.js
done
```

2️⃣ After the run, confirm that some part has failed because of `TimeoutError: Text not found "Order received"`. 
3️⃣ Checkout to `fix/flaky-e2e-test`, run the command from step 1️⃣ once more
4️⃣ Confirm that there are no failing tests with the message `TimeoutError: Text not found "Order received"`
5️⃣ Run [this job](https://github.com/Automattic/woocommerce-payments/actions/runs/4304845140/jobs/7506799139) 1-2 times from GH Actions and confirm it's green. 

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Review by mdmoore — APPROVED** [review]
Thanks for working on this @timur27. I'm running into a strange problem when running the test locally. The `Shopper > Pay for Order › should be able to pay for a failed order` case is failing constantly: 



When manually testing checkout with a failing card, `4000 0000 0000 0002`, I can see why this test would fail. 

1. The error message text is actually `Your card has been declined.`, without the prefix, `Error: `. 
2. `div.woocommerce-NoticeGroup > ul.woocommerce-error > li` - This `li` doesn't exist on the page. Only the containing`ul.woocommerce-error`



Have you encountered the this? It's confusing because the above would mean that Stripe has changed it's error message *and* WooCommerce has a new bug that's excluding the list item from error messages.

With that said, those problems appear to only exist on local environments, as the job on GH has completed successfully several times now. I'm happy to approve this change now, but am curious if you've experienced the above mentioned failures.

**Comment by timur27** [comment]
Hey, @mdmoore, thanks for your previous comment. 

> When manually testing checkout with a failing card

Have you tested it on the merchant site or the test site used for the e2e setup locally? For me, it's `localhost:8082` that is the merchant site, and `localhost:8084` is the site that is used for the testing. The latter should be used.

>   Shopper > Pay for Order › should be able to pay for a failed order 
TimeoutError: Element div.woocommerce-NoticeGroup > ul.woocommerce-error > li (text: "Error: Your card was declined.") not found

This error could potentially occur on the `localhost:8084` if there database containers used for the e2e setup are not started. If I turn them off:

image

and then run the test, I'm getting 
image


and the reason for this is that the error message is different and relates to the containers being turned off:

image


But if I have all the containers turned on and run the test it's green. Also, if I go to `localhost:8084` and pay manually, I see the expected message with `Error: ` prefix:

image


image


Having this said, please let me know if you tested on `localhost:8084` and if you have all the Docker containers up and running. If yes to both, I can wrangle more to find the cause.

**Comment by mdmoore** [comment]
>Have you tested it on the merchant site or the test site used for the e2e setup locally?

I've been running manual tests on `localhost:8084`. All containers are up and running. Here's a screenshot of the error: 



Here's a system status from the test environment, in case it helps.
<details>
<summary>SSR</summary>
### WordPress Environment ###

WordPress address (URL): http://localhost:8084
Site address (URL): http://localhost:8084
WC Version: 7.3.0
REST API Version: ✔ 7.3.0
WC Blocks Version: ✔ 9.1.5
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Debian)
PHP Version: 7.4.32
PHP Post Max Size: 8 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.8-MariaDB-1:10.5.8+maria~focal
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.5.1
WC Database Prefix: wp_
Total Database Size: 6.24MB
Database Data Size: 4.35MB
Database Index Size: 1.89MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.25MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.06MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.20MB + Index: 0.19MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 23
page: 7
post: 2
product: 30
product_variation: 7
shop_order: 21
shop_order_refund: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (5) ###

JSON Basic Authentication: by WordPress API Team – 0.1
WooCommerce Payments Dev Tools: by Automattic –
WooCommerce Payments: by Automattic – 5.5.0 (update to version 5.5.1 is available)
WooCommerce: by Automattic – 7.3.0 (update to version 7.4.1 is available)
WordPress Importer: by wordpressdotorg – 0.7

### Inactive Plugins (4) ###

Akismet Anti-Spam: by Automattic – 4.1.8
Gutenberg: by Gutenberg Team – 13.4.0
Hello Dolly: by Matt Mullenweg – 1.7.2
WooCommerce Payments Dev Tools: by Automattic –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.1.0 (update to version 4.2.0 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: http://localhost:8084
Subscriptions-core Library Version: 5.3.1
Subscription Statuses: –
WooCommerce Account Connected: ❌ No

### Store Setup ###

Country / State: United States (US) — California

### Subscriptions by Payment Gateway ###


### Payment Gateway Support ###

WooCommerce Payments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
gateway_scheduled_payments
tokenization
add_payment_method


### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-03-03 18:01:18 +00:00
Options: ✔
Notes: 46
Onboarding: completed

### WooCommerce Payments ###

Version: 5.5.0
Connected to WPCOM: Yes
Blog ID: 199665293
Account ID: acct_1Kh0asQsXyeg2MSN

### Action Scheduler ###

Complete: 91
Oldest: 2023-02-14 04:26:40 +0000
Newest: 2023-03-03 16:21:34 +0000

Failed: 32
Oldest: 2023-02-14 17:52:27 +0000
Newest: 2023-03-02 20:59:45 +0000

Pending: 1
Oldest: 2023-03-03 17:40:21 +0000
Newest: 2023-03-03 17:40:21 +0000


### Status report information ###

Generated at: 2023-03-03 16:31:07 +00:00
</details>

Let me know if there's anything else I can do to help track this down.

**Comment by timur27** [comment]
@mdmoore Looks like the underlying problem behind this misalignment was found, at least on my local machine. For me, UPE/split UPE card gateway outputs
```
Your card has been declined
```

whereas the non-UPE CC outputs
```
Error: Your card has been declined
```

It's probably a different implementation of error handling/payment processing that is used between these two groups. Could you confirm if you can overcome the issue by changing the gateway type? If this is confirmed, I'll create a small issue to align the error messages between non-UPE and UPE.

**Comment by mdmoore** [comment]
@timur27 That's it! The error message in the e2e seems to expect the legacy card element which, when declined, will result in the `Error: Your card was declined.` error message. My local e2e test environment is running this test through the UPE card element which gives the `Your card has been declined` error message, without the wrapping `<li>`. I can't see where we might have control over these error messages. It seems like we might be passing them through directly from Stripe.

IMO, we are ✅ on this PR but please let me know if there's anything further you'd like to change here.

**Comment by timur27** [comment]
@mdmoore yes, let's merge this PR. Regarding the error messages - given that we are now starting to work on the enhanced UPE flow, which should eventually result in only one UPE CC element available, I think the topic of error message type will be naturally aligned then.

**Pull request merged**
