### PR TITLE
Implement FingerprintJS on the checkout page

### LINKED ISSUE #4772: Improve fingerprinting mechanism on checkout page
### Description
We need to implement a more intelligent fingerprint solution that doesn’t only rely on HTTP headers, and probably we can implement a 3rd party solution like fingerprint.js, or Sift’s fingerprint library, or another one, but there’s a problem that their scripts can be blocked by ad-blockers. We need to find a way to safely load a fingerprinting library which can’t be blocked. To be sure, we can block loading our scripts if the fingerprint library is not loaded, but we need to check first if it’s feasible.

### Dev notes
Some 3rd party fingerprinting scripts are blocked automatically by ad blockers, you can get some insight of what's blocked from [this](https://github.com/Hackl0us/AdBlock-Rules-Mirror/blob/master/Easylist-Privacy.txt) list.

### PR DESCRIPTION
**Pull request by eduardoumpierre**
Fixes #4772 

#### Changes proposed in this Pull Request

- Add [FingerprintJS](https://github.com/fingerprintjs/fingerprintjs/blob/master/docs/api.md) to UPE and non-UPE checkout pages (classic and blocks). The fingerprint data is attached to the payment_intent on Stripe
- Replace the user agent fraud metadata with the user fingerprint

#### Testing instructions

**Pre-requisites**

- Checkout to this branch `add/4772-fingerprintjs`
- Run `npm install` and `npm run start`
- Listen to the Stripe webhooks in another console tab `npm run listen` – or equivalent
- Unit tests should pass
- Create a "Block checkout" page
  - Open `wp-admin`, go to **Pages > Add new**
  - Fill in the title "Block checkout"
  - Add the "Checkout" block, and then publish the page
image

**Non-UPE**
- Uncheck **Enable UPE checkout** on **WCPay Dev**, and then clear the account cache
- **Classic checkout**
  - Add a product to the cart
  - Go to the classic checkout page and place the order – it should work as expected
  - Follow the [base testing flow](#base-flow)
- **Block checkout**
  - Add a product to the cart
  - Go to the block checkout page and place the order – it should work as expected
  - Follow the [base testing flow](#base-flow)

**UPE**
- Check **Enable UPE checkout** on **WCPay Dev**, and then clear the account cache
- **Classic checkout**
  - Add a product to the cart
  - Go to the classic checkout page and place the order – it should work as expected
  - Follow the [base testing flow](#base-flow)
- **Block checkout**
  - Add a product to the cart
  - Go to the block checkout page and place the order – it should work as expected
  - Follow the [base testing flow](#base-flow)

<h4 id="base-flow">Base testing flow</h4>

- On the dashboard, go to **WooCommerce > Orders**, and click on the order you've just made
- Copy the payment intent id (`pi_xxxxxxx` identifier), and open your Stripe account's dashboard (https://dashboard.stripe.com/test/connect/accounts/acct_YOUR_STRIPE_ACCOUNT_ID/payments/pi_PAYMENT_INTENT_ID)
  - You can get the blog ID by visiting the WCPay Dev page `/wp-admin/admin.php?page=wcpaydev`
- Scroll down to the **Metadata** section
- The **fraud_prevention_data_shopper_ua_hash** entry should have a non-empty value similar to `1fd5405aa7d247abc0640b12b007362b`

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Review by allie500 — COMMENTED** [review]
Thanks for working on this feature, Eduardo! I learned a lot while shadowing you when working on this code. 

I have tested that the `fraud_prevention_data_shopper_ua_hash` was present and not empty in the PI metadata on the Stripe Dashboard for all tests. 

| Element | Classic Checkout | Block Checkout |
| ------- | ---------------- | -------------- |
| non-UPE | Pass | Pass |
| UPE | Pass | Pass |

JS and PHP unit tests passed on my local.

The code looks good to me, but I'd also like for a more experienced Sigma team member to review it to give final approval.

**Review by tpaksu — CHANGES_REQUESTED** [review]
Thanks for working on this! I've read the code, and it felt a bit complicated to understand what's going on, why you added the fingerprints as method parameters instead getting it directly using a library method call, like each one of them could be

```javascript
'wcpay-fingerprint': FingerprintJS.getFingerprint()
```
but I guess this is because the fingerprint is retrieved from an async method, right?

Here are my test results: 

 **UPE Status** | **Classic/Block** | **Card Type** | **Fingerprint Exists**                                    
----------------|-------------------|---------------|-----------------------------------------------------------
 Enabled        | Classic           | New Card      | Yes                                                       
 Enabled        | Classic           | Saved Card    | Double intent created, the unused one has the fingerprint 
 Enabled        | Blocks            | New Card      | Yes                                                       
 Enabled        | Blocks            | Saved Card    | No                                                        
 Disabled       | Classic           | New Card      | Yes                                                       
 Disabled       | Classic           | Saved Card    | Yes                                                       
 Disabled       | Blocks            | New Card      | No                                                        
 Disabled       | Blocks            | Saved Card    | No                                                        

I've removed all plugins and reinstalled the blocks plugin, but still getting the same results. Can you test it again?

Here's what I have active on my local setup: 

[WooCommerce Blocks](https://github.com/woocommerce/woocommerce-gutenberg-products-block)	 	by Automattic – 9.0.0
[WooCommerce Payments](https://woocommerce.com/payments/)	 	by Automattic – 5.0.3
[WooCommerce](https://woocommerce.com/)	 	by Automattic – 7.1.0

And the server is on the latest trunk.

**Review by dwainm — COMMENTED** [review]
I can confirm that the hash is present on the order Id for all testing scenarios.

I'm not 100% about UPE as the checkout for UPE and none-UPE look exactly the same.

**Review by tpaksu — APPROVED** [review]
I can now see all fingerprints on the payment intents generated, except the block checkout with a saved card. And I believe that's not so important because; 

1. we didn't see someone saving cards and using them in a carding attack yet, 
2. This may require extra effort because it's on the blocks' scope.

Maybe we should continue these two things in their respective PR's in the future: 

- Refactoring the fingerprint code
- Sending fingerprints on saving cards / Collecting fingerprints on setup intents

I think the approach is good enough for our current issue. We can ship this feature! Thanks for your efforts to get this alive!

**Pull request merged**
