### PR TITLE
Remove feature flag for simplify deposits ui that was re-added due to merge conflict

### PR DESCRIPTION
**Pull request by KarlisJ**
#### Changes proposed in this Pull Request

~~The code introduced in #5763  was most likely partially lost during incorrect merge conflict resolving upon merging #6288. This PR addressed the issue by adding code back in.~~

[#6280](https://github.com/Automattic/woocommerce-payments/pull/6280) removed the simplify deposits UI feature flag but incorrect merge conflict resolving in #6288 left one method in the codebase.

This PR addressed the issue by removing the method from the codebase as it's expected to not be there.

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6418` or branch name `fix/recover-simplify-deposits-ui-feature-flag` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=fix/recover-simplify-deposits-ui-feature-flag) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 5c02346814ee70400584c5d68e0cb3daed610723
- Build time: 2023-06-05 01:12:29 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by shendy-a8c — CHANGES_REQUESTED** [review]
You're right that the Simplify Deposits UI feature flag was introduced in https://github.com/Automattic/woocommerce-payments/pull/5763.

However, after we finished the project and rolled out the new UI 100% to user, we removed the feature flag and the related code in https://github.com/Automattic/woocommerce-payments/pull/6280. [Here](https://github.com/Automattic/woocommerce-payments/pull/6280/files#diff-a441a64d0adecb8d97d15e2ad40f34011f5cb32f50257b6a3d9061cdb5fb83f2L280-L288)'s the specific part that removed the feature flag from `includes/class-wc-payments-features.php`.

The merge conflict mistake is [re-adding the Simplify Deposits UI feature flag back in](https://github.com/Automattic/woocommerce-payments/pull/6288/files#diff-a441a64d0adecb8d97d15e2ad40f34011f5cb32f50257b6a3d9061cdb5fb83f2R280-R287) which it shouldn't.

Also on I notice there are extra spaces introduced in that [merge commit](https://github.com/Automattic/woocommerce-payments/pull/6288/commits/9cc3134c0afc7c1beac6fba9e65c457bc01af5ca).

Screenshot 2023-06-02 at 10 03 04

**Comment by shendy-a8c** [comment]
So I think what needs to be done in this PR to correct the merge commit mistake:
- Revert all the changes in `client/globals.d.ts` and `includes/class-wc-payments-features.php`, in this PR. They are not needed as we intentionally removed them in https://github.com/Automattic/woocommerce-payments/pull/6280.
- Remove `is_simplify_deposits_ui_enabled()` in `includes/class-wc-payments-features.php`.
- Remove extra line in the comment as I mentioned above.

If everything is done right, you will end up with `includes/class-wc-payments-features.php` that looks exactly like
https://github.com/Automattic/woocommerce-payments/blob/99de2876c4bd5335d87136ddc4673db847235857/includes/class-wc-payments-features.php but it has `is_bnpl_affirm_afterpay_enabled()` you wanted to add in https://github.com/Automattic/woocommerce-payments/pull/6288.

**Comment by shendy-a8c** [comment]
Also, to satisfy the changelog GitHub check, just add an empty patch changelog.
Not sure about the other failing GitHub check. Hopefully they are all greens after a re-run.

**Comment by shendy-a8c** [comment]
One more thing. Please rename the PR title and body to reflect the new intention, so it does not confuse other people who reads this PR in the future. We're not to recover the Simplify Deposits UI feature flag here.

**Review by shendy-a8c — APPROVED** [review]
Looks good!

**Comment by shendy-a8c** [comment]
I was contemplating whether we need to squeeze this to the next release as this PR didn't make it to the code freeze last Friday but decided that it does not need to be squeezed in.

Althought simplify deposits UI feature flag is re-added, it is not used anywhere in the code, so I think it's OK to be there and not critical to remove it urgently.

**Pull request merged**
