### PR TITLE
Implement a retry system to the WCPay Subscription migration process

### LINKED ISSUE #7038: Add an automatic retry system to the WCPay Subscription migration process
### Description

To enable merchants to switch to tokenised WooPayment subscriptions, we'll be introducing a new feature that allows the migration of Stripe Billing subscriptions to standard WC Pay tokens (see #6525). As part of this migration, there can occur  intermittent errors that prevent the migration. Some of these failures are recoverable. 

For this issue, we'll implement an automatic retry process. 

### Acceptance criteria

- [ ] Implement a way for failures to be caught (fatals, incorrect or invalid server responses etc). 
- [ ] When a failure occurs, schedule a follow up job based on how many attempts have been made - see example schedule below.  

1. Retry 1 minute later.
2. If failed, retry 5 minutes later.
3. If failed, retry 10 minutes later
4. If failed, retry 30 minutes later.
5. If failed, retry 1 hour later.
6. If failed, retry 6 hours later.
7. If failed, retry 12 hours later.
8. Throw an exception.

> The reason for the exception is because then you can leverage Action Scheduler’s error handling to handle the error. 

### Testing instructions

1. Follow the steps outlined in https://github.com/Automattic/woocommerce-payments/pull/6942 to set up the environment to test migrations. 
2. You'll likely need to throw fake errors to given the errors I've come across are intermittent.

### PR DESCRIPTION
**Pull request by mattallan**
Fixes #7038

#### Changes proposed in this Pull Request

When an exception is thrown during our migration process, the error is logged and the subscription remains as a Stripe Billing subscription until the merchant manually runs the migration script again.

In this PR we're implementing a retry system so that if the migration fails for whatever reason, another attempt is automatically scheduled in the future. With each failed attempt (up to 7 retries), we will increase the time between retrying the migration again.

Current retry schedule:
1. after 1 minute
2. after 5 minutes
3. after10 minutes
4. after 30 minutes
5. after 1 hour
6. after 6 hours
7. after 12 hours

When does a migration get rescheduled?

- When its number of attempts is less than 7
- When the `migrate_wcpay_subscription()` function throws a non-skip error/exception
- When the scheduled action throws an unexpected failure
- When an unexpected shutdown occurs

This PR also includes a few changes that aren't directly related to the retry system:
 - 4e6ebc73ceea25640164c5c9351c409aae7dd6d8 Manually hook onto the `wcpay_migrate_subscription` hook so that we can use two args on the hook
 - 3b69426b7dc23170ac45898e9b82325e5f28dc3f Update some of the logged messages to always include a subscription ID and/or WCPay subscription ID so that we have the context in the single log.

#### Testing instructions

I wanted to test some failing migrations and some successful ones in the same batch so I injected some faulty code surrounded by rand(0,1) to simulate errors being caused 50% of the time.

Here are some examples of code I used:

To throw unexpected errors:

```php
if ( rand( 0, 1 ) ) {
	throw new Error( 'foobar' );
}
```
```php
if ( rand( 0, 1 ) ) {
 $this->api_client = null;
}
```

To trigger Stripe API errors I updated the [`cancel_subscription()`](https://github.com/Automattic/woocommerce-payments/blob/e6e7c3be3d06153233bd14159bb2c4f0f1e120b4/includes/wc-payment-api/class-wc-payments-api-client.php#L1181) and [`get_subscription()`](https://github.com/Automattic/woocommerce-payments/blob/e6e7c3be3d06153233bd14159bb2c4f0f1e120b4/includes/wc-payment-api/class-wc-payments-api-client.php#L1129) functions to sometimes fetch subscriptions that don't exist:
```php
public function cancel_subscription( string $wcpay_subscription_id ) {
	return $this->request(
		[],
		self::SUBSCRIPTIONS_API . '/' . $wcpay_subscription_id . ( rand( 0, 1 ) ? '1234' : '' ),
		self::DELETE
	);
}
```

To test that skipped migrations don't get retried I manually added a scheduled action for a subscription I just migrated using WP Console:

```php
as_schedule_single_action( gmdate( 'U' ), 'wcpay_migrate_subscription', [ 'migrate_subscription' => 1918 ] );
```

**Testing instructions:**

1. Generate a bunch of WCPay Subscriptions using [this plugin/gist](https://gist.github.com/james-allan/38fa3f40fff586a8377bf629f380342c).
2. Enable migrations by setting `_wcpay_feature_allow_subscription_migrations` to `1` in `wp-options`
3. Enable WC Subscriptions extension
4. Go to **WooCommerce > Status > Tools** and manually run the migration tool
5. Go to **WooCommerce > Status > Logs** and search look in the latest `woopayments-subscription-migration`
6. Confirm logs are showing migrations being rescheduled on failures and the number of attempts are in the logs.
7. Open Action Scheduler and search `wcpay_migrate_subscription` to confirm that some migrations have an `attempt` arg.

In order to test the retry schedule and migration attempts stop after the 7th retry, I removed the rand(0,1) and made it so an error is always thrown. Then manually ran the migration action.

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7106` or branch name `issue/7038-retry-migration` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=issue/7038-retry-migration) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: fee65f4b206512da6295ad428cce087475c54783
- Build time: 2023-09-11 04:53:40 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by mattallan** [comment]
Just making a note that after the base branch was merged into `develop` I fixed up the conflicts and retested the retry process. This is now ready for review :)

**Comment by mattallan** [comment]
I've updated this branch to use a new hook for retries. There are two benefits to this:
1. We can return back to using the original `repair_item()` function to handle the first migration. This means the repairer class is no longer hooking on and doing nothing
2. We can find retry scheduled actions separately to single migrations

In my changes I made the retry scheduled action `$migrate_hook . '_retry'`.
This was because I figured it would be nice to be able to go to **Tools > Action Scheduler** and search for just the `wcpay_migrate_subscription` string and to have both single and retry jobs show up. Open to feedback/suggestions on this one.

I updated this branch to the latest `develop` and ran through the retry process with the latest changes.

**Comment by Jinksi** [comment]
FYI: the unrelated failing JS test is being addressed in #7164.

```
TestingLibraryElementError: Unable to find an element with the text: /The cardholder claims this is an unauthorized transaction/. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.
```

**Review by james-allan — APPROVED** [review]
This is so good! Thanks for providing examples of how to test the error conditions.

I tested migrating 20 Stripe Billing subscriptions where 50% of them failed migrating. I then tested what happens if every attempt fails to make sure it stops retrying and that worked as expected.

I tested `throw new Error`, `throw new exception` and fatal errors like `Call to a member function cancel_subscription() on null`.

Nice work on this @mattallan! 👍

**Pull request merged**
