### PR TITLE
Fix scrollable content in currencies modal

### LINKED ISSUE #2145: Improve overflow scroll on add currencies modal
The **Add currencies** modal scroll all the modal content except the header on overflow. As per paJDYF-1gf-p2 it should scroll only the currencies list, being the search bar and buttons toolbar sticky.

#### How it looks now
Screen Recording 2021-06-11 at 14 59 17

### PR DESCRIPTION
**Pull request by tpaksu**
Fixes #2145 

#### Changes proposed in this Pull Request

Fix scrollable area of "Add Currencies" Modal

The modal responsible for selecting active currencies for the multi-currency modal didn't have a maximum height, and when the currency count increased, it showed as a full height modal as described and pictured in #2145, also it had the title and search input also in the scroll content, this PR fixes it by wrapping the content which we want to scroll with a `div.add-enabled-currencies-modal__content`, and make it scrollable with `overflow-y: auto;` instead. 

Also this contains the fix for the mobile modal by stretching the list to fill the screen. The breakpoint chosen is `600px` to apply the fix, which is also the breakpoint when the modal turns to an overlay, but it can be changed.

#### Desktop Screenshot

Screen Capture on 2021-06-22 at 00-41-35

#### Testing instructions

* Navigate to WooCommerce > Settings
* Select the Multi-Currency tab
* Below the "Enabled Currencies" table, click the "Add currencies" button
* Desktop tests
	* Check the styling if the list height is bigger than 350px with more than 10-15 currencies visible (should be no)
	* Check the styling if the list height is smaller than 350px with less than 10-15 currencies visible (should be no, too)

* Mobile tests
	* Check if the buttons are on bottom, the header and search input is intact while the currency list is scrollable.

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

**Review by dmallory42 — APPROVED** [review]
LGTM, thanks for making this change! I have one question, but everything looks good and works well so I'm pre-approving this! 🚀 

Do you think we should also have a fixed max/min width on the modal as well as a fixed max height? I noticed on desktop it will scale depending on the content inside the modal, which can lead to it changing width when searching:

https://d.pr/i/qV1anx

cc. @ismaeldcom as he may also have thoughts on this!

**Comment by tpaksu** [comment]
@dmallory42 I thought that too, but there's a slight chance that there would be a longer text in another language that'll cause a text overflow to next line, and to prevent that, I don't suggest using CSS for this. Instead on the modal show event, it would be better to have a JavaScript code to fix the width to the longest text.

**Comment by dmallory42** [comment]
> I thought that too, but there's a slight chance that there would be a longer text in another language that'll cause a text overflow to next line, and to prevent that, I don't suggest using CSS for this. Instead on the modal show event, it would be better to have a JavaScript code to fix the width to the longest text.

Yeah, that sounds good to me, I didn't think of that. Maybe we should 🚢  this and then address that with a separate issue since it wasn't part of the original issue (just something I noticed while testing 😄 ), or I'm happy to include the fix here too if you want to.

Thanks for making this update and let me know if you want me to re-test!

**Comment by tpaksu** [comment]
@dmallory42 I'll include that in this merge, and I'll let you know when I'm finished to let you test it :) Thanks for pointing that out.

**Comment by tpaksu** [comment]
Here's the output of the last additions:



I completed the fix, you can test it again :) @dmallory42 @ismaeldcom

**Comment by dmallory42** [comment]
Thanks for making this change! I tested and it works well the width now stays consistent in all cases :) I think this is ready to 🚢  🎉 !

**Pull request merged**
