### PR TITLE
Add test mode notice in page order detail.

### LINKED ISSUE #334: Add a test mode warning notice to order details screen
I realized while working on #242 that adding test mode notices to the WC Order Details screen will take a significant amount of effort because it's directly controlled by WooCommerce, and it's really hard — at least AFAICT — to hook into _only_ that screen and add a notice. We could add a wp-admin wide notice, but I don't think that's what we want here.

We may even want to wait for upstream changes in WooCommerce that will store information on whether an order was made in test mode or not, as has been discussed in the past. For now we'll make do with waiting until further down the line to implement this.

### PR DESCRIPTION
**Pull request by htdat**
Fixes #334 

#### Changes proposed in this Pull Request

- Use the same foundation of https://github.com/Automattic/woocommerce-payments/pull/6373 to add a new notice for test mode in the order details. Changes for this in the JS change files, and this PHP code https://github.com/Automattic/woocommerce-payments/blob/25d96a577525c54ebbfffc64ea0e900342836365/includes/admin/class-wc-payments-admin.php#L737

- I also use this opportunity to introduce `Order_Mode` constant (enum) class, and `WC_Payments_Order_Service::WCPAY_MODE_KEY`. Changes for this is for the rest of PHP files. 

#### Testing instructions

* Check for orders in the test and dev mode, confirm that you're seeing the new notice. 
* Check for orders with dispute in the test and dev mode, see both notices: test mode and dispute. 

#### Screenshots

- Only testmode notice: 

only-testmode

- Both testmode and dispute notices: 

testmode-and-dispute

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [x] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7898` or branch name `add/334-test-mode-notice-order-details` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=add/334-test-mode-notice-order-details) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 217e22acb30cb8f04753ebfe750c7d5ab31a25b7
- Build time: 2023-12-21 06:27:00 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by htdat** [comment]
Note: all test failures are related to `WC beta` and that happens for other PRs too. 
p1701263468047559-slack-CGGCLBN58

_Update_: also be ready to get reviews.

**Review by jessy-p — COMMENTED** [review]
- Fix conflicts

Other nitpicks:
- Can add tests for the component to check that the modal displays. 
- Can use the key `WCPAY_MODE_META_KEY` instead of `WCPAY_MODE_KEY` for two reasons:
       -   Follows the pattern already followed in `WC_Payments_Order_Service` for other keys
       -   Jumps out to me easier in lines like 
         `\WCPay\Constants\Order_Mode::TEST === $order->get_meta( WC_Payments_Order_Service::WCPAY_MODE_KEY )` where we have the `Order_Mode` and the `WC_Payments::mode()` in addition to the meta_key

**Comment by htdat** [comment]
👋 @jessy-p Thanks for the feedback. I addressed for other comments except this one: 

> Can add tests for the component to check that the modal displays.

Actually, this is NOT a modal being triggered in a specific event such as `click` or `onchange`. Instead, it's an inline div, which is rendered via `ReactDOM.render` by jQuery after DOM content is loaded, i.e. `DOMContentLoaded` event. I know that ideally this would include some tests but given this, I think we can skip it here or create a follow-up issue (if needed) to refactor `client/order/index.js` so that it will be more testable.

**Review by jessy-p — APPROVED** [review]

**Pull request merged**
