### PR TITLE
Remove WooPay subscriptions user check endpoint

### PR DESCRIPTION
**Pull request by alefesouza**
#### Changes proposed in this Pull Request

This PR removes the endpoint used to check if a guest user buying a subscription has a merchant site account and ask them to login before redirect to WooPay, we do not support this flow (guest user +  WooPay subscription) anymore since https://github.com/Automattic/woocommerce-payments/issues/6131 so there's no need for this endpoint.

#### Testing instructions

As this endpoint is already not being called on `trunk`, just do a normal WooPay checkout test to ensure everything is working.

* With WooPay enable and a guest user on merchant site, add a non subscription product to the cart.
* Access checkout page and type a valid WooPay, the modal should appear.
* Add a subscription product to the cart.
* Access checkout page and type a valid WooPay, the modal should not appear.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6174` or branch name `fix/remove-woopay-subscriptions-user-check-endpoint` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=fix/remove-woopay-subscriptions-user-check-endpoint) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 49d2bd2e71158abf8cc95b586b5ac9c59c9414c7
- Build time: 2023-04-27 16:53:11 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by c-shultz** [comment]
@alefesouza https://github.com/Automattic/woocommerce-payments/issues/6131 is meant to be temporary measure. Do you think the endpoint needs to be removed since we plan on eventually building the compatibility with guest checkouts plus subscriptions?

**Comment by alefesouza** [comment]
@c-shultz this endpoint also needs to be reworked to be tied to the subscriptions flow, currently it can be used anywhere on WCPay so it is best to remove it and think on a new approach.

**Review by malithsen — APPROVED** [review]
Thanks for the PR @alefesouza and for your patience on the delayed review. The changes look good to me. I did some smoke tests and didn't notice any obvious issues. 

@c-shultz I'm also leaning towards removing this endpoint now than later, as keeping it could potentially result in dead code paths in the future.

**Pull request merged**
