### PR TITLE
Add SEPA payment method.

### PR DESCRIPTION
**Pull request by naman03malhotra**
Implements #2645 

#### Changes proposed in this Pull Request
- Added SEPA Direct Debit to UPE payment methods.
- Updated tests accordingly.
- Refactored some code to reduce redundancy.

#### Testing instructions
* Switch to this branch and `add/sepa-payment-method-fees` on server (Fee for CA is yet to be added).
* If EUR is your default currency, navigate to WooCommerce > Settings > General and change the currency to USD.
* If EUR is an enabled currency in your store, navigate to WooCommerce > Settings > Multi-Currency and remove EUR as a currency.
* Navigate to Payments > Settings.
* Click _Add payment method_, verify `SEPA Direct Debit` is in the modal, along with its icon.
Screen Shot 2021-09-11 at 1 11 25 AM

* Select `SEPA Direct Debit`, a notice should appear stating that Euros are being added to your store. Click _Add selected_, then scroll to the bottom and click _Save changes_.
image

* Verify `SEPA Direct Debit` and its logo are now in the _Payment methods_ area.
image

* Navigate to WooCommerce > Settings > Multi-Currency and verify EUR is now an enabled currency in your store.
* On the frontend, add an item to your cart, and go to checkout.
* Verify your currency *is not* EUR, payment method should show as _Credit card / debit card_ and when selecting _Use a new payment method_, `SEPA Direct Debit` should not appear.
* Switch your currency to EUR from the top right corner drop-down, the payment method should show as _Popular payment methods_ and when selecting _Use a new payment method_, `SEPA Debit` should appear.

image
* Select `SEPA Debit`.
Screen Shot 2021-09-11 at 1 13 09 AM

* Complete checkout/place order using IBANs given [here](https://stripe.com/docs/payments/sepa-debit/accept-a-payment?platform=checkout#test-integration).
* Once an order is received, navigate to WooCommerce > Orders in the admin.
* Find your order and select it.
* Click _Refund_, and then increase a line item in your order to 1.
* Click _Refund via WooCommerce Payments_, verify your refund completed.
* Navigate to Payments > Transactions, you should see your _Payment_ and _Payment refund_ listed for your order, verify both have the SEPA logo.

Screen Shot 2021-09-11 at 1 08 36 AM

* Click on the Payment, then verify the _Payment method_ both at the top and bottom are correctly formatted.
Screen Shot 2021-09-11 at 1 15 55 AM
image

* Navigate to Payments > Settings, then click the trash can icon to delete SEPA Debit. Verify the name and the logo in the modal are correct, then click _Remove_, scroll to the bottom and _Save changes_.
* VerifySEPA debit is no longer in the list of _Payment methods_.
image

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

**Comment by naman03malhotra** [comment]
We can merge this PR without enabling the SEPA payment (from `get_upe_available_payment_methods` function) for now until the server part is merged. We can enabled it with other PMs and add changelog then.

**Comment by vbelolapotkov** [comment]
> Implements #2854

@naman03malhotra did you mean fixes #2645 ?

**Review by RadoslavGeorgiev — APPROVED** [review]
Nice work, everything works like a charm and I don't notice a single thing that needs to be changed! 👌 👏 🚢 

Don't forget to edit `get_upe_available_payment_methods` before shipping though, and as @vbelolapotkov mentioned, the description needs to be be edited in order to point to the correct issue.

**Comment by naman03malhotra** [comment]
> did you mean fixes #2645 ?

Ah! somehow tagged the same PR, fixed it now.

**Comment by naman03malhotra** [comment]
Disabled SEPA from `get_upe_available_payment_methods`.

**Pull request merged**
