### PR TITLE
Add Multi-Currency Support to Page Caching via Cookies

### LINKED ISSUE #8130: Setting up a cookie to allow caching of product pages on a per currency basis
### Description

The request comes as a result of a high volume user of WooPayments requesting help with the creation of a caching mechanism that would allow multi-currency to be used in a reverse proxy cached environment.

After some discussion at p1705549584944779-slack-C7U3Y3VMY it was decided to open this request as a means to monitor demand.

### The mechanism

On switching currencies, the first request is parameterized with a query string. Following requests use the session cookie to monitor the currency in use by the user.

This makes it impossible to cache a product page on a site using multi-currency on a per currency basis.

The `woocommerce_currency` filter can be used now to set a cookie identifying the currency in use.

But building this into core WooPayments would allow us to set the cookie value to the exchange rate in use. This would provide a mechanism for cache invalidation.

Site managers could then set up VCL rules for Varnish, ACL rules for NGINX reverse proxy mechanisms, or custom rules for Cloudflare or Cloudfront instances.

While these mechanisms remain the responsibility of the site administration to set up, a cookie mechanism built into core could be documented for developers and sys-ops staff, and as a bonus allow them to share such VCL/ACL rules.

The cookie would not be needed by WooPayments, but provides great value to high volume sites seeking to improve performance.

### Additional context

We should aim to remove the WC session to store the currency in favor of the new cookie.

The cookie should not be set on every request as some caching mechanisms such as Batcache will read the response headers and prevent the page from being cached if any cookies are being set.

More context in https://github.com/Automattic/woocommerce-payments/issues/8130#issuecomment-2085975611.

Another thing to note when caching product pages is that if Apple Pay/Google Pay is enabled on the product page, it will create a WC session upon page load, thus preventing the page from being cached. We might want to open another issue for this.

### PR DESCRIPTION
**Pull request by rafaelzaleski**
Fixes #8130 

#### Changes proposed in this Pull Request

This PR introduces the `wcpay_currency` cookie, which consolidates the selected currency code and exchange rate into a single cookie, intended primarily for caching purposes on the frontend. This enhancement allows merchants to use this cookie within reverse proxy setups to efficiently cache product pages based on the currency. 

Note: The WooCommerce session cookie must be included in requests to accurately set currency cookies. If testing a reverse proxy solution involving these cookies, ensure caching rules do not strip the WooCommerce session cookies to preserve the multi-currency functionality.

#### Testing instructions

**Test 1: Multi-Currency Feature Disabled**

1. Ensure the multi-currency feature is disabled in WooPayments settings.
2. Clear any existing cookies related to your site to start with a clean slate.
3. Navigate through your site, visiting various pages including product pages, the homepage, and any other relevant pages.
4. Check your browser's developer tools under the Application or Storage tab to verify that the `wcpay_currency` cookie is not set.
5. Confirm that navigating through the site does not trigger these cookies to be set, indicating that with the multi-currency feature turned off, the mechanism is inactive.

**Test 2: Multi-Currency Feature Enabled with Currency Switching**

1. Enable the multi-currency feature in WooPayments settings and configure a few different currencies.
2. Clear your browser's cookies to ensure a fresh start for this test.
3. Visit your site and switch to a different currency using the currency switcher provided by WooPayments.
4. After switching currencies, check your browser's developer tools under the Application or Storage tab for the `wcpay_currency` cookie.
5. Verify that the `wcpay_currency` cookie reflects the code of the newly selected currency.
6. Continue to switch between different currencies and repeat steps 4-6, confirming that each time the currency is switched, both cookies update accurately to reflect the new currency code and exchange rate.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8534` or branch name `8130/add-cookie-product-cache-per-currency` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=8130/add-cookie-product-cache-per-currency) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 07f83e1ce7581cf999eb6a1486477103bbdf247e
- Build time: 2024-04-10 14:22:41 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by bborman22 — CHANGES_REQUESTED** [review]
I was able to test both scenarios with multi-currency enabled and disabled and confirmed that the cookie was only set when it was enabled. I also ran through tests with different pages and different currencies and everything worked as expected.

There was one oddity that I'm unsure how it would impact the caching in these cases and that is when you make the initial currency switch. So for example you have USD selected on the product listing page, then select EUR from the currency widget. This will set the currency URL parameter, but if you check the cookies they will still point to using USD. I believe this is because the `update_selected_currency_by_url` action is fired after the MultiCurrency::init function which sets the cookies. 

We discussed this on our call and felt that this should be addressed by updating the cookies as necessary in `update_selected_currency` function. We should still keep it in the `init` function though as we need to set cookies for instances where shopper hasn't updated their selected currency.

We also discussed the possible need to expire these cookies based on the current conversion rate cache time. This one was less clear on how to determine this time as the conversion rates can be cleared in multiple ways outside of cache expiration. 

And finally we discussed using a single cookie to capture the currency and rate in one cookie. Something like: `wcpay_currency: EUR+1.22` to simplify what needs to be checked when looking up the cache. This one we also weren't super clear on if this is necessary, but might simplify the process for the site manager and caching set up.

**Comment by rafaelzaleski** [comment]
> We also discussed the possible need to expire these cookies based on the current conversion rate cache time. This one was less clear on how to determine this time as the conversion rates can be cleared in multiple ways outside of cache expiration.

While it's possible to know when the cache was last fetched, checking the cache TTL for currencies outside of the `Database_Cache` class isn't possible (private method). As a result, predicting the next fetch time is challenging since the current 6-hour TTL might change in the future. Hardcoding a fetch time + 6 hours now could lead to non-future-proof code, especially if the TTL for multi-currency is later updated and this part of the code is overlooked.

Given that, I decided to don't assign an expiration date for the cookies.

**Review by bborman22 — APPROVED** [review]
I was able to test the same flows again and the currency cookie was always properly set. All of the discussed topics from the last review were addressed. 

LGTM!

@nicdwilson Just wanted to get confirmation that this approach will properly address the ability to cache product pages based on currency. In short, what we're doing is setting a cookie with name `wcpay_currency` and value `<currency_code>_<currency_conversion_rate>`. This should allow site admins to determine page cache for specific currencies and conversion rates based on this single cookie.

**Comment by bborman22** [comment]
@rafaelzaleski There was some interesting discussion around cookie expirations in https://github.com/Automattic/woopay/pull/2630#pullrequestreview-1980832273 that made me rethink our decision a little bit as this particular cookie we would want to avoid lasting too long. I was wondering what you'd think about setting something like a 1 hour expiration on the cookie just to guarantee it doesn't hang around longer than expected?

**Comment by rafaelzaleski** [comment]
> @rafaelzaleski There was some interesting discussion around cookie expirations in [Automattic/woopay#2630 (review)](2630-gh-Automattic/woopay#pullrequestreview-1980832273) that made me rethink our decision a little bit as this particular cookie we would want to avoid lasting too long. I was wondering what you'd think about setting something like a 1 hour expiration on the cookie just to guarantee it doesn't hang around longer than expected?

Sounds good to me.

**Comment by kiburisa** [comment]
I manually applied this fix to one of my sites to test it.

I've noticed that initially the **wcpay_currency** cookie adopts the value of the corresponding currency ("EUR" as I am accessing the site from Spain). However, the cookie value immediately changes to "AUD", the default currency of the e-commerce. Then, after a few seconds of scrolling, the currency returns to the initial value of "EUR".

When commenting the line `$this->maybe_add_cache_cookie();` inside the init function, the problem is solved (although I'm aware that this cannot be the solution).

What I just mentioned can be checked here: https://australstones.com.au/

Please notice that I'm well aware that this is not a support forum and that this comment is only intended to provide information in case it is, somehow, useful.

Regards

**Comment by bborman22** [comment]
Thanks so much for the additional information as it's always helpful to have! As you probably saw since you applied it manually, this got rolled back and while it wasn't for the same reason you listed, it was similar in that we were too aggressive in setting this cookie. Once we settle on a better approach here, you provided another good area to monitor to be sure we're setting this cookie efficiently.

**Pull request merged**
