### PR TITLE
feat: add UPE appearance filter

### LINKED ISSUE #3604: Add filters to modify the css styling for credit card fields
### Description
There are no filters to manually modify the fields on WooCommerce Payments UPE or legacy card fields. 

Currently, WCPay fields use Stripe's Universal Payment Element (UPE) as opposed to the previous card element and scans fonts and styles from existing inputs on the page in order to match existing themes as much as possible - but for some users they will want more control over the display.

For Legacy checkout, WC Pay lacks an equivalent to the Stripe plugin's `wc_stripe_elements_styling` filter ([described in the Stripe docs here](https://woocommerce.com/document/stripe-styling-fields/#section-4)), which allows site owners to add their own styling to the legacy form. In other words, disabling UPE doesn't allow for more styling options, unlike Stripe.

### Acceptance criteria
Having a filter to either change the CSS selector used to compute styles and/or a filter to manually set styling properties for the Stripe element.

Though I'm sure some developers would like this for the legacy fields, I think it would be acceptable to focus on the UPE for this request.

### Dev notes
For reference, Stripe's card element allows styling options in a [different format](https://stripe.com/docs/js/appendix/style) to the newer [UPE styling format](https://stripe.com/docs/stripe-js/appearance-api#rules), so it's not trivial to copy the legacy filter over the the new checkout. 

#1960 would allow merchants to choose the CSS selector that we use to dynamically scan CSS properties; however, this would still not allow merchants to manually set individual properties themselves, without changing the theme.

### Additional context
* 4647359-zen
* p1640947060027100-slack-C7U3Y3VMY

### PR DESCRIPTION
**Pull request by frosso**
Fixes https://github.com/Automattic/woocommerce-payments/issues/3604

#### Changes proposed in this Pull Request

Allows merchants to style the UPE elements via https://stripe.com/docs/elements/appearance-api .
Prior to this, merchants only had an option to hook into a filter for the `get_transient` function, which might not be too clean.

Examples:

Single override - purple label, achieved with this filter:
```php
add_filter( 'wcpay_upe_appearance', function ( $appearance ) {
	unset( $appearance->rules->{'.Label'} );
	$appearance->rules->{'.Label'} = [
		'color' => 'purple',
	];

	return $appearance;
} );
```
Screenshot 2023-10-30 at 9 43 10 AM

Stripe theme, achieved with this filter:
```php
add_filter( 'wcpay_upe_appearance', function () {
	return [ 'theme' => 'stripe' ];
} );
```
Screenshot 2023-10-30 at 9 33 43 AM

#### Testing instructions

- Add a filter in your theme's `functions.php` file, using one of the examples above
- Clear the transient data for the `wcpay_upe_appearance` and the `wcpay_wc_blocks_upe_appearance` transients
- You should get updated UPE element styling at checkout

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7578` or branch name `feat/add-upe-appearance-filter` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=feat/add-upe-appearance-filter) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 19e8eaf5705284a3efa6fb6bf65b29c877334734
- Build time: 2023-11-03 09:44:43 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by mdmoore — APPROVED** [review]
Great addition here! I see some failing e2e tests but it seems unrelated to these changes. Approving pending those tests passing.

**Comment by csmcneill** [comment]
Just to confirm, merchants can use `$appearance->rules->` to target [these specific three class names](https://stripe.com/docs/elements/appearance-api?platform=web#form-inputs---labels-above), correct? And from there, they can use [these variables](https://stripe.com/docs/elements/appearance-api?platform=web#variables) to modify the appearance of specific elements?

**Comment by frosso** [comment]
@csmcneill yep, that's accurate! It's also worth mentioning that we'll be looking into a global styles integration (https://github.com/Automattic/woocommerce-payments/issues/7610) as well, for block-based themes

**Comment by frosso** [comment]
I reverted this in https://github.com/Automattic/woocommerce-payments/pull/7722 , because it wasn't working well with code snippets. I think there might be another bug underlying in this solution. I'll rework it.

**Comment by hamadgill** [comment]
Request to also include the Afterpay plugin and change the text color in the payment box during checkout.

**Pull request merged**
