### PR TITLE
Remove redundant estimated deposit code

### LINKED ISSUE #7850: Remove estimated deposit code from WooPayments client once server no longer returns estimated deposits
In WooPayments 6.9, we introduced logic within the client that filtered out `estimated` deposits.

Once the server no longer returns this data, this logic should be deleted to remove redundant code.

We should ensure our TS interfaces accurately reflect the expected server API response data shape (see #7848).

### PR DESCRIPTION
**Pull request by Jinksi**
Fixes #7850

#### Changes proposed in this Pull Request

This PR removes code that is no longer necessary due to the removal of estimated deposits from server API responses. Server changes were deployed with PR https://github.com/Automattic/woocommerce-payments-server/pull/4500. No user-facing changes are expected.

#### Testing instructions

- Ensure all relevant GH checks pass
- View the deposit list screen → expect no estimated deposits
- View the payments overview screen → expect no estimated deposits in the recent deposits list
- View the transaction details for a new charge → expect no link to an estimated deposit in timeline
- Ensure an instant deposit request is successful
- Export a deposits list CSV → expect no estimated deposits

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests **Yes**
- [x] Tested on mobile **N/A – no user-facing changes**

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) **N/A**
- [x] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable. **N/A**
- [x] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable. **N/A**

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8057` or branch name `fix/7850-remove-redundant-estimated-deposits-code` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/7850-remove-redundant-estimated-deposits-code) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 3bc98fda92da59f8706f42101c3853a08f328347
- Build time: 2024-01-25 23:11:05 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by haszari — COMMENTED** [review]
Quick code review only, no testing.

Code looks good ✅ 

I didn't test as none of my test stores have deposit history (local and a recent jurassic ninja). So will need another review with some actual testing. (OR I could come back with better test setup)

**Review by shendy-a8c — APPROVED** [review]
Looks good!

Tested well per testing instructions but I think base branch would also pass all those tests. This PR deletes unused code and does not introduce any no user-facing changes as explained in the changelog.

Also, as sanity check, I searched for these terms: estimated, next_scheduled, transaction_ids, deposits_count, next_deposit. Found  no code that needs to be removed.

Finally, I looked at the related code from https://github.com/Automattic/woocommerce-payments/pull/7688 and https://github.com/Automattic/woocommerce-payments/pull/7632 to get the context around estimated deposits removal.

**Comment by Jinksi** [comment]
Thanks @haszari & @shendy-a8c 🌟

Adding to the merge queue.

**Comment by Jinksi** [comment]
Removing from the merge queue to fix some linter warnings introduced by this PR.

image

**Comment by Jinksi** [comment]
> Removing from the merge queue to fix some linter warnings introduced by this PR.

Resolved in 3bc98fd, will add to merge queue once I've confirmed the GH checks pass.

**Pull request merged**
