### PR TITLE
feat: add euro when euro payments enabled

### PR DESCRIPTION
**Pull request by frosso**
Helps with https://github.com/Automattic/woocommerce-payments/issues/2170

#### Changes proposed in this Pull Request

Ensuring that when a payment method is added, if it is a EU payment method (like SEPA/Sofort/giropay), Euro should be also added in the multi-currency settings.

#### Testing instructions

- Ensure you have "Enable grouped settings" enabled
- Ensure you have "Enable UPE checkout" enabled
- Ensure you have "Enable UPE settings changes" enabled
- Ensure you have "Enable Customer multi-currency" enabled
- Ensure your store's default currency is USD
- Go to http://localhost:8082/wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments
- Add one of the EU payment methods
- Save the settings
- Go to http://localhost:8082/wp-admin/admin.php?page=wc-settings&tab=wcpay_multi_currency
- Euro should be added as a currency

Progress:
Screen Shot 2021-07-15 at 5 19 04 PM
👇
Screen Shot 2021-07-15 at 5 19 10 PM
👇
Screen Shot 2021-07-15 at 5 19 17 PM
👇
Screen Shot 2021-07-15 at 5 20 08 PM

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

**Comment by harriswong** [comment]
👀

**Comment by harriswong** [comment]
When I delete existing payment method, it doesn't delete on first try. In `develop`, this doesn't seem to happen.
screen1

**Review by harriswong — APPROVED** [review]
Tested adding and deleting payment methods (beside cards). Confirmed EUR currency shows up in `wp-admin/admin.php?page=wc-settings&tab=wcpay_multi_currency`.

I suppose we only add multicurrency when we add a payment; but reversely, we shouldn't delete the currency when removing the payment? 

👍

**Comment by frosso** [comment]
@harriswong thanks for reviewing! 

> I suppose we only add multicurrency when we add a payment; but reversely, we shouldn't delete the currency when removing the payment?

That's correct! Also because we don't keep track if a currency has been recently added automatically via this script.

**Pull request merged**
