### PR TITLE
Fixed typo in businessInfo strings in strings.tsx file

### LINKED ISSUE #6368: Typo in businessInfo strings in strings.tsx file: "Type of businesss"
### Describe the bug
I ran into a typo in Woo Express when reading the content to `Learn more about how to receive deposits`, an extra S in the word business:

`Type of businesss`

I think this might be the [relevant line of code with the typo](https://github.com/Automattic/woocommerce-payments/blob/265a257b8532120a88dbb4199d870cc8cf127986/client/connect-account-page/strings.tsx#LL165C9-L165C53).

### To Reproduce

1. In a Woo Express site, go to the `Payments` menu.
2. Click on the `Learn more about how to receive deposits` link in the section title `You're only steps away from getting paid`.
3. Scroll down to the `Business info` section.

### Screenshots

wooexpress-payments-typo-1

wooexpress-payments-typo-2

### PR DESCRIPTION
**Pull request by naman03malhotra**
Fixes #6368 

#### Changes proposed in this Pull Request
Fixed typo in `Learn more about how to receive deposits`, an extra S in the word business:

image

#### Testing instructions
- Force WCPay account to be disconnected using dev plugin
- Click on Learn more... as mentioned in the screenshot below

image
image

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [x] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [x] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6580` or branch name `6368/fix-typo-business-info` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=6368/fix-typo-business-info) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 6036c479ba3043d9477e82e50c3da4ad2b315ba3
- Build time: 2023-06-29 03:09:04 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by htdat — APPROVED** [review]

**Review by htdat — CHANGES_REQUESTED** [review]
@naman03malhotra - Oh, I did not notice that there was a JS snapshot test failure. Could you update the test too?

**Comment by naman03malhotra** [comment]
Thanks @dat for review, I've updated the snapshot. Can you please check.

**Review by htdat — APPROVED** [review]
LGTM now 🚢 !

**Pull request merged**
