### PR TITLE
Fix Task List Title Style

### LINKED ISSUE #5436: Fix how the Task List title displays
### Describe the bug

While working on #5369, it was discovered that the task list title is not displaying as it should.

Screenshot 2023-01-20 at 15 14 12

> `Things to do` header is misaligned. The title should be the larger Title text size, and aligned horizontally with the count badge.

This issue will cover fixing this, and also checking to see if we can use less custom CSS in this section, instead relying directly on using Components. After discussion with @ismaeldcom on Slack, we think it may be possible to make improvements here.

### Expected behavior

The title should be aligned properly, with a larger text size.

### PR DESCRIPTION
**Pull request by dmallory42**
Fixes #5436 

#### Changes proposed in this Pull Request

* Fix how the task list title displays on the `Overview` page.
* Some CSS fixes to tidy up further.

#### Screenshots

**Before**

Screenshot 2023-01-25 at 10 02 23

**After**

Screenshot 2023-01-25 at 10 02 48

#### Testing instructions

* Go to `includes/class-wc-payments-account.php` and make the following change to the array returned by `get_account_status_data()`:

```php
		return [
			'email'               => $account['email'] ?? '',
			'country'             => $account['country'] ?? 'US',
			'status'              => 'restricted',
			'paymentsEnabled'     => $account['payments_enabled'],
			'deposits'            => $account['deposits'] ?? [],
			'depositsStatus'      => $account['deposits']['status'] ?? $account['deposits_status'] ?? '',
			'currentDeadline'     => $account['current_deadline'] ?? false,
			'pastDue'             => true,
			'accountLink'         => $this->get_login_url(),
			'hasSubmittedVatData' => $account['has_submitted_vat_data'] ?? false,
			'requirements'        => [
				'errors' => $account['requirements']['errors'] ?? [],
			],
		];
```

* Go to `Payments > Overview` and verify that the task list title matches the screenshot, that it is the same font size/style as the other headings on the page, and that everything looks as expected.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : QA Testing Not Applicable
- [x] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [x] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Review by ismaeldcom — APPROVED** [review]
Thanks for moving this part to a new PR and make it easier to review. Looks good to me, it accurately matches the design again.

I think we can go one step further a remove the following CSS code that it's not required anymore. Or at least I've not been able to find any other case where it is useful.
https://github.com/Automattic/woocommerce-payments/blob/f666ddd3ec0b9f0d21b53c9af166bdd292518d4f/client/overview/style.scss#L13-L25

Anyway, preapproving it now! 🙂

**Comment by dmallory42** [comment]
Thanks @ismaeldcom! I'm always a bit scared of removing CSS, but that seems safe to me.

The only thing is that there's a note about `IE` in the comment. Do you know whether we still officially support Internet Explorer? I've seen a few P2 posts when searching about dropping support for it since it's EOL, but couldn't find anything about WCPay's position on it.

**Comment by ismaeldcom** [comment]
>I'm always a bit scared of removing CSS, but that seems safe to me.

Yes, it's a bit harder to know if we still need some CSS code when we use it in this way. We need to dig deeper and check any existing code manually.

>Do you know whether we still officially support Internet Explorer?

We rely on [browserlist](https://github.com/browserslist/browserslist) for it, and more specifically on `@wordpress/browserslist-config`. You can check [here the supported list](https://github.com/WordPress/gutenberg/blob/%40wordpress/browserslist-config%405.3.0/packages/browserslist-config/index.js) from the version we're using in WCPay. As you can see we don't support `IE` anymore.

**Comment by dmallory42** [comment]
> We rely on [browserlist](https://github.com/browserslist/browserslist) for it, and more specifically on @wordpress/browserslist-config. You can check [here the supported list](https://github.com/WordPress/gutenberg/blob/%40wordpress/browserslist-config%405.3.0/packages/browserslist-config/index.js) from the version we're using in WCPay. As you can see we don't support IE anymore.

Thanks, this is useful! It's good to know how to check this in future. 🙂

**Pull request merged**
