### PR TITLE
Update payment assets to match partner brand guidelines

### LINKED ISSUE #7865: Payment asset outlines are being drawn incorrectly on the transactions screen(s)
### Describe the bug
On the transactions table, and the transaction details page, we're not applying an offset to the outline drawn around payment method assets.

### To Reproduce

1. Go to 'Payments -> Transactions'
2. Click on a row to view transaction details

### Actual behavior

The outline is drawn outside the asset

### Screenshots

Screenshot 2023-12-08 at 12 51 25
Screenshot 2023-12-08 at 12 51 18

### Expected behavior

The outline should be drawn with an asset so it appears _on top_ of the asset. The fix for this should be simple, we just need to update the `.payment-method__brand` css class to include
```outline-offset: -1px;```

### PR DESCRIPTION
**Pull request by bradyv**
Fixes #7865 

#### Changes proposed in this Pull Request

This updates payment method assets to match the latest brand guidelines from Amex, Diner's Club, Discover, and VISA. It also updates the credit card asset to use the marks that have been updated.

Screenshot 2023-12-07 at 13 45 53

#### Testing instructions

Ensure the assets are updated and displaying legibly everywhere we need to display them:
* WooPayments Settings
* WooPayments pre-activation prompt(s)

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by bradyv** [comment]
@KarlisJ Requesting your review as you've updated these assets in the past, but feel free to reassign to someone else.

I will also do a testing pass before we merge.

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7860` or branch name `fix/update-payment-assets` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/update-payment-assets) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 5bd8592b94c346de82c0f6f5e08065710a252d62
- Build time: 2023-12-11 09:28:00 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by KarlisJ — APPROVED** [review]
LGTM! From code change perspective everything looks good. Did a quick testing some of the most relevant places like transaction listing and settings and the new assets are there.

**Comment by kalessil** [comment]
@bradyv : do you need support with adding a changelog and merging this PR?

**Comment by bradyv** [comment]
Tested myself and I can see the correct assets being used across WooPayments! I've noticed that the outlines are being drawn incorrectly in the transactions screen(s) but I will file a separate ticket as another small fix.

Edit: filed #7865 for this

**Comment by bradyv** [comment]
@kalessil Yes, that'd be great if you're able to support! This is my first PR so I'm not up to speed on the merging procedure.

**Comment by kalessil** [comment]
@bradyv: I added a changelog entry and am merging. Congrats on your first PR into WooPayments :tada:!

**Pull request merged**
