### PR TITLE
Adds check to see if WC()->session is set in WooPay_Utilities::should_save_platform_customer

### LINKED ISSUE #7957: Add check for existence of Woo session before calling it in WooPay_Utilities::should_save_platform_customer
### Describe the bug
On TumblrPay, successful, subscription payment retries were not finishing completely.  The payment is successful, the order and subscription statuses are updated, and the next renewal is scheduled but the payment retry is not updated, and the successfully charged order note is not saved.

The issue was traced to calling `get()` on `null` in `WooPay_Utilities::should_save_platform_customer`.  The session is not set when this method is called which results in an error.  

### To Reproduce
I have been unable to reproduce this in my own testing.  Stripe has a test card that can be attached to a customer but will fail once charged but they do not have one that will fail and then be successful.  We only saw this error on payment retries where the card was declined and then the same card number was later successful.  

Modifying the `should_save_platform_customer()` method to check for the existence of the session before processing prevented the error for us.

```php
$session_data = [];

if ( isset( WC()->session ) && WC()->session->has_session() ) {
	$session_data = WC()->session->get( WooPay_Extension::WOOPAY_SESSION_KEY );
}

$availability = ! empty( $session_data ) ? 'available' : 'not available';
\wc_get_logger()->debug(
	"WooPay: Session $availability when checking if we should save platform customer.",
	[
		'extra' => [
			'session_data' => $session_data,
		],
	]
);
```

We also added logging to see how often this was called.  Over the past three days, we had this logged 270 times however only one of those was for a successful payment retry.

### Screenshots
_Order notes from an affected order:_
order-notes

_Retry data from the related subscription_
retry-data

### Additional context
Log entry with stack trace available: https://logstash.a8c.com/logstash/app/discover#/doc/log2logstash-*/log2logstash-1m-index-2023.12.29-001558?id=N_Ewt4wBizqA4NEXpH8f

### PR DESCRIPTION
**Pull request by billrobbins**
Fixes #7957

#### Changes proposed in this Pull Request

On TumblrPay, we noticed that subscription payment retries that were successful, using the original credit card were triggering a fatal error.  The payment would process and the subscription was updated but the subscription retry would not be cleared.  The issue was traced to calling `get()` on `null` inside `WooPay_Utilities::should_save_platform_customer`.

To address that on TumblrPay, we added a check to ensure the session exists before trying to call a method on it.  This PR adds the same changes here in the even that we'd like to merge these into the WooPayments core.

#### Testing instructions

I was unable to reproduce this issue in testing because Stripe does not have a test card that will be successful and then fail at a later time.  They do have one that you can attach to a customer that will fail when charged but since it will never work, I can't replicate this exactly.  

I will say that we ran into this issue daily on TumblrPay and since making this change a few weeks ago, we haven't seen the issue again.

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [X] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8188` or branch name `fix/check_for_session_before_calling_get` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/check_for_session_before_calling_get) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 82a10658d11f6951c12a715918732324b40ada09
- Build time: 2024-04-10 02:05:42 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by reykjalin — APPROVED** [review]
LGTM, let's get this updated (i.e. click the GH button) and merged 🎉

**Comment by reykjalin** [comment]
@billrobbins just want to check in to see if you have the capacity to merge this?

**Comment by billrobbins** [comment]
@reykjalin absolutely!  Sorry for the delay there.

**Pull request merged**
