### PR TITLE
Deprecate Sofort

### LINKED ISSUE #7490: Soft Deprecation of Sofort
### Describe the bug

As of October 20, Sofort will be soft [deprecated](https://woocommerce.com/document/woopayments/payment-methods/additional-payment-methods/#sofort-deprecation) meaning that it will no longer be allowed to be enabled as a payment method for new merchants (if it is already enabled it will continue to work as normal).

This issue covers informing users of the deprecation and preventing enablement of Sofort after October 20th on the client side.

### PR DESCRIPTION
**Pull request by dmallory42**
Fixes #7490 

#### Changes proposed in this Pull Request

* Remove references to Sofort in any places where we advertise supported WooPayment payment methods.
* Remove or gray-out Sofort from APM selection unless the user is already enabled onto Sofort (in which case, a warning about the future sunsetting will be displayed). Existing users will also need to know that if they disable Sofort, it **cannot** be re-enabled because Stripe will prevent it after October 20th.

#### WCPay Onboarding Page

* In the WCPay Dev Tools, enable the option to act as if the client is disconnected from the server. Click `Payments` - verify that the Sofort logo is not visible amongst the payment methods:

Screenshot 2023-10-13 at 13 36 30

**NOTE**: In order to test these steps, please also checkout the corresponding server/4029 PR. You may need to checkout `trunk` on the server in order to request Sofort for the second part of the tests, then switch back to this branch.
 
#### Payment Method Setup with Sofort disabled

In order to test this, please firstly checkout `trunk` on the server, clear the cache, and check whether Sofort is enabled as a payment method and disable it if it is enabled. Then checkout the corresponding server PR and clear the account cache.
  
* Go to `Payments > Settings` and you should see Sofort not present in the payment methods list:

Screenshot 2023-10-13 at 15 00 37

* Click the three-dot icon next to the APM menu and click disable. Then, a banner should pop up prompting you to enable UPE/APMs - click "Enable" and you'll be taken to the APM setup task. Verify that Sofort is not present on the list:

Screenshot 2023-10-13 at 15 00 54

* Enable APMs again by completing this setup. Now go to `WooCommerce > Settings > Payments` and disable WooPayments on the menu. You should see the following confirmation modal. Verify that Sofort is not in the list:

Screenshot 2023-10-13 at 15 00 17

#### Payment Method Setup with Sofort disabled

In order to test this, please firstly checkout `trunk` on the server and enable Sofort as a payment method in `Payments > Settings`. Then checkout the corresponding server branch again.

* Go to `Payments > Settings`. Verify that you see the Notice under Sofort in the list:

Screenshot 2023-10-16 at 11 42 55

* Click the checkmark icon to disable Sofort. Verify you see the notice in the confirmation modal:

Screenshot 2023-10-16 at 11 44 30

* Disable Sofort. After clearing the server cache, it should no longer be present on the list of payment methods.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

* Noting that prior to merge I need to update a few visual assets which reference Sofort, however this does not prevent code review.

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7480` or branch name `dev/sofort-deprecation` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=dev/sofort-deprecation) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 6a94393bd5d107650dacca063e478a73ce1a6a45
- Build time: 2023-10-19 13:33:53 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by csmcneill** [comment]
I spun up a JN site with this branch (using the link [here](https://github.com/Automattic/woocommerce-payments/pull/7480#issuecomment-1761457964)) and am still seeing Sofort when going through the "Set up payments" task at **WooCommerce > Home** (`/wp-admin/admin.php?page=wc-admin&task=payments`)

Markup on 2023-10-16 at 09:59:03

I'm not sure if this task is owned by WCPay or Woo core.

**Comment by dmallory42** [comment]
Hey @csmcneill! 

> I spun up a JN site with this branch (using the link https://github.com/Automattic/woocommerce-payments/pull/7480#issuecomment-1761457964) and am still seeing Sofort when going through the "Set up payments" task at WooCommerce > Home (/wp-admin/admin.php?page=wc-admin&task=payments)

That's because that page belongs to WC Core. That fix is addressed by this core PR: https://github.com/woocommerce/woocommerce/pull/40745

**Review by elizaan36 — COMMENTED** [review]
Looks good but please use the `inline-notice` component for the settings and in the modal. Design shared here: `paJDYF-aMc#comment-21219`.
image-14

**Comment by dmallory42** [comment]
Thanks @elizaan36! Good catch about using the `InlineNotice` component. I've updated to use that component with the icon - here's how they look now: 

Screenshot 2023-10-17 at 10 22 42

Screenshot 2023-10-17 at 10 22 53

**Review by ismaeldcom — APPROVED** [review]
Thanks for taking care of the deprecation, it's gone as intended and the inline notices appear for the right cases as expected. Ready to merge 🙂

**Comment by aheckler** [comment]
LGTM!

**Pull request merged**
