### PR TITLE
Add Stripe's Payment Method Messaging Element to checkout radio buttons

### LINKED ISSUE #8143: Add BNPL Payment Method Messaging to the dUPE BNPL radio button elements
### Description
BNPL is an important payment method that allows shoppers to spread payments over a longer time period. As a new category of online payment, consumer adoption and awareness continues to be in a growth phase. Thus, how this category of payment method is presented to shoppers is important to adoption and perception.

In the initial implementation of BNPL, [payment method messaging](https://stripe.com/docs/payments/payment-method-messaging) was added to the product page. This messaging e.g. As low as $14/month or 0% APR is critical to driving shopper awareness, usage, and conversion.

The problem is that not all shoppers will click into the product page to see that messaging. Even if they do see the messaging, it may be forgotten by the time the shopper completes filling up their basket/cart. 

WooPayments lacks that messaging at other important touch points such as the cart and checkout pages.

This feature adds the Stripe payment method messaging element to the checkout dUPE BNPL radio checkout buttons.

### Acceptance criteria
1. The dUPE element displays the payment method messaging copy for each BNPL radio button per the design, and each BNPL option used the appropriate `paymentMethodTypes` corresponding to the BNPL brand
2. The messaging language matches the browser locale language
3. TBD - Display text only messaging below the checkout Total amount

### Designs
Design needed - @nikkivias I'll connect with you directly with a few options for consideration

### Testing instructions
1. Enable Affirm on your store
2. Shop and add a simple $50+ product to the cart
3. Proceed to checkout
4. Observe that the Affirm radio button in the payment component displays the payments method message
5. Repeat for Afterpay/Clearpay and Klarna
6. Repeat testing on mobile 
7. Change the browser locale to a supported non en-US language and observe that the copy language matches the new locale.
8. TBD - Repeat above for Acceptance Criteria 3.

### Additional context
Inspirational examples

Image

Image

Image

Image

cc @FangedParakeet

### PR DESCRIPTION
**Pull request by brettshumaker**
Fixes #8143

#### Changes proposed in this Pull Request

This PR adds the PMME to both the blocks and classic checkout. I've done my best to introduce a base CSS style for aligning this new information according to the figma design, but fundamental differences in how themes handle rendering the radio input results in some variations from theme to theme. Some themes hide the radio input inside the payment method list item and use another method to make a fake radio button (like style a `:before` element or style the disc from the `li`). These differences are most apparent on the classic checkout.

Screenshot 2024-04-04 at 10 16 02 AM Screenshot 2024-04-04 at 10 16 11 AM Screenshot 2024-04-04 at 10 16 21 AM

#### Testing instructions

1. Enable BNPL methods, i.e. Affirm, After Pay, Klarna
2. Add a product to the cart
3. Ensure that the shopper currency, country, and total amounts align with the requirements for BNPL payment methods. Each set of requirements can be found in the payment methods class. For example, the Klarna requirements can be found [here](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/payment-methods/class-klarna-payment-method.php#L34-L102).
4. Check that the BNPL text is rendered under the title of the BNPL method on both the classic checkout and block checkout and that the displayed amount updates when cart totals change(shipping method change or coupons, etc.).
5. Also test with different themes to see if this information ever looks "broken."

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8452` or branch name `8143/add-bnpl-pmme-to-checkout-radio-buttons` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=8143/add-bnpl-pmme-to-checkout-radio-buttons) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 4783529c32a3cf81c8198277557ac7cb373e807f
- Build time: 2024-04-10 19:02:58 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by gpressutto5 — CHANGES_REQUESTED** [review]
I had a few issues with this branch:

1. I only get a generic BNPL message.
    image
2. When I select one of the methods the layout is broken.
    image
3. The payment method section is broken in the Blocks Checkout.
    image

It still works in the cart and product page:

image

**Comment by pierorocca** [comment]
Hey guys is this an issue with Stripe's fix for the hanging "with" or with our implementation?

**Comment by brettshumaker** [comment]
@pierorocca our implementation.

**Comment by brettshumaker** [comment]
@gpressutto5 - prematurely re-requested your review on this. I've fixed the layout issue you described and addressed the issue with the currency minor unit we discussed in Slack but I did find another issue if the customer chooses an unsupported country for their billing address. I'll let you know when this is ready.

**Review by gpressutto5 — APPROVED** [review]
It is working great!

image

image

**Pull request merged**
