### PR TITLE
Continue optimization work for Frontend Currencies.

### PR DESCRIPTION
**Pull request by jessepearson**
#### Changes proposed in this Pull Request

Further optimization of `FrontendCurrencies` based on the work of @millerf in https://github.com/Automattic/woocommerce-payments/pull/3450 . The purpose of the optimization was due to slow downs and timeouts within certain things in WordPress.com. I also created https://github.com/Automattic/woocommerce-payments/issues/3502 to further optimize the usage of `is_call_in_backtrace`.

* `Compatibility`
  *  Add a check in `init_compatibility_classes()` to make sure the classes are only initialized if there is more than 1 (the default) currency enabled.
  * Added `compatibility_classes` property and method to get the property to be able to do unit tests for the above mentioned check.
* `FrontendCurrencies`
  * Add new properties for caching purposes.
  * Add `selected_currency_changed()` method to reset cache properties.
  * Refactor existing methods to use or set cache properties.
  * Rename `should_override_currency_code` to `should_use_order_currency`.
  * Add `get_selected_currency_code` to get/set cache property value.
  * Refactor `should_use_order_currency` to check to make sure certain page is being viewed before calling intensive `is_call_in_backtrace``Utils` method.
* `MultiCurrency`
  * Reset cache in `FrontendCurrencies` when selected currency is changed.
* `Utils`
  * Add `is_page_with_vars` method that will check `$wp->query_vars` to see if a specific `pagename` is set and if any specific `vars` have been passed to it. This allows for checking for a specific page *before* calling `is_call_in_backtrace`.
* Add/update tests.

#### Testing instructions

* Unit tests should pass.
* Place an order for a product.
* On review page, change the selected currency.
* Order currency should remain the same.
* This also works by going to My Account > Orders, and then selecting a previous order.

-------------------

- [x] Added changelog entries to both `readme.txt` and `changelog.txt` (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

**Comment by jessepearson** [comment]
@millerf Can you look over this and test it out, if possible, to see if it still has the same improvised speed as your initial PR?

**Comment by millerf** [comment]
@jessepearson I have tested it and it still times out.
The request takes 19s on production right now (which has my optimisation), but times out at 30 seconds when sandboxed (which has this branch checked out)

**Comment by jessepearson** [comment]
@millerf I think the issue is right here:
https://github.com/Automattic/woocommerce-payments/pull/3466/files#diff-3be210d35eaea628e94c474e23329134c32b8632f567783d4fd88b3556b428a8R182

With your changes, you no longer call `get_currency_code`, and then I added it back. That, in turn, calls `should_use_order_currency` (old name `should_override_currency_code`), and that calls `Utils->is_call_in_backtrace()`. [The `is_call_in_backtrace` method](https://github.com/Automattic/woocommerce-payments/blob/3.3.0/includes/multi-currency/Utils.php#L23-L31) calls [`wp_debug_backtrace_summary`](https://developer.wordpress.org/reference/functions/wp_debug_backtrace_summary/), which can be resource intensive.

The `is_call_in_backtrace` method is used quite a lot, as there are not specific hooks or filters for some things, and we need to determine if we are in a specific location or not. Being this is called multiple times when WooCommerce is displaying a price, I can see why it would cause a slow down. I am not sure of a fix for this at the moment.

**Comment by jessepearson** [comment]
@millerf Continuing from above, I made some tweaks to the code so that `is_call_in_backtrace` is only called on certain pages now, not all of the pages. Unsure if this will make a change. Would you be able to give it a test, and/or share how you are testing this out?

**Comment by millerf** [comment]
> @millerf Continuing from above, I made some tweaks to the code so that `is_call_in_backtrace` is only called on certain pages now, not all of the pages. Unsure if this will make a change. Would you be able to give it a test, and/or share how you are testing this out?

I tested it and still getting a timeout unfortunately. Can you maybe check if it is a REST call and therefore not checking the whole backtrace, maybe?

**Comment by millerf** [comment]
> LGTM and works well! Tested the changes, they work and I don't see the timeouts. I'm happy to approve it and I think it's ready to 🚢 , but I'll leave the final word to @millerf because of more context in this issue.

From a pure feature perspective, it was tested and it solved the issue I had on this version, so I am happy for it to be deployed 🚢 🎉

**Review by millerf — APPROVED** [review]

**Pull request merged**
