### PR TITLE
Stop refund process when using an invalid amount

### LINKED ISSUE #2287: Don't attempt to refund an order with an invalid amount
When the order amount is invalid (e.g. when you try to refund an amount that's `0`) we still try to process a refund through Stripe. We should catch the issue on the API level and inform the merchant that the refund amount is invalid — without sending the refund request to the Stripe API.

> If you just click the refund button (without a valid amount) you get an alert with the error "Invalid refund amount"
>
> _Originally reported by @diegocurbelo in https://github.com/Automattic/woocommerce-payments/pull/2167#issuecomment-864270142_

## Reproduction steps

1. Pay for an order with `4242 4242 4242 4242`
2. Go to the order details screen
3. Click **Refund**
4. Try to refund an invalid amount via WCPay, e.g. `0`, negative amounts, and amounts greater than the order's cost.

### PR DESCRIPTION
**Pull request by daquinons**
Fixes #2287 

#### Changes proposed in this Pull Request

Don't attempt to refund an order with an invalid amount

When entering an amount for a refund, or when clicking without entering anything, we were making the request to the server and returning an error, so we should catch this before making that request.

https://user-images.githubusercontent.com/2612426/127121785-f0e14b7d-c61e-4dd6-aed9-78a35fdee1d7.mp4

#### Testing instructions

* Go to an order
* Click on Refund
* Click on "Refund 0 using WooCommerce Payments"
* See error message without making API request

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

**Review by dmallory42 — COMMENTED** [review]
LGTM and works well, nice job! I just have one question before approving - it looks like I am able to attempt a refund with a value greater than the total value of the order. For example:

Screenshot 2021-07-28 at 16 38 48

It gives me the following error:

Screenshot 2021-07-28 at 16 39 02

I am wondering whether we should also try and catch these cases where the value entered is greater than the total cost of the order? I think Kris mentions this here: https://github.com/Automattic/woocommerce-payments/issues/2287

I'm happy for us to either do that as part of this PR, or to make a follow-up PR for it, whichever is easier. 👍

**Comment by daquinons** [comment]
> LGTM and works well, nice job! I just have one question before approving - it looks like I am able to attempt a refund with a value greater than the total value of the order. For example:
> 
> Screenshot 2021-07-28 at 16 38 48
> 
> It gives me the following error:
> 
> Screenshot 2021-07-28 at 16 39 02
> 
> I am wondering whether we should also try and catch these cases where the value entered is greater than the total cost of the order? I think Kris mentions this here: #2287
> 
> I'm happy for us to either do that as part of this PR, or to make a follow-up PR for it, whichever is easier. 👍

Oh yes, definitely we can tackle that here. I'll let you know when I make the changes. Thank you! 👍

**Comment by daquinons** [comment]
@dmallory42 Done! Sorry, I totally missed that part of the sentence in the issue 😸 Here it is https://github.com/Automattic/woocommerce-payments/pull/2572/commits/337ef739ea9ed7ec23c9119939b66041b0a8c491

**Review by dmallory42 — APPROVED** [review]
LGTM and works well. Thanks for making those changes, I think `$order->get_total` is the correct way to get the order total, so that check looks good to me. :shipit:

**Pull request merged**
