### PR TITLE
Added a notice about custom checkout fields conflicting with express checkout

### LINKED ISSUE #8299: Detect custom fields and disclose when they may cause conflicts with express checkout methods
### Description

It appears that custom fields are currently incompatible with express checkout methods. For example, this is explicitly stated in [Apple Pay's documentation](https://developer.apple.com/design/human-interface-guidelines/apple-pay#Streamlining-checkout).

> Collect necessary information, like color and size options, before people reach the Apple Pay button. When additional information is needed at checkout time — perhaps because the customer forgot to choose an option — gracefully point out the problem and help them correct it. Use highlighting or warning text to identify missing information, and automatically navigate to the problematic field so people can correct it quickly and complete their purchase.
>
> Collect optional information before checkout begins. There’s no way to input optional data — like gift messages or delivery instructions — on the payment sheet, so collect this information ahead of time or even after the purchase is complete.

It would be great if we could detect when this scenario may be present and be able to warn store owners that one of their plugins responsible for adding these custom fields may cause conflicts with the express checkout methods that they present at checkout. It appears that the detection of these custom fields should be feasible from our perspective (see pb22l9-2s6-p2#comment-2665 and paJDYF-ckK-p2#comment-23071).

This issue is to explore a valid way to provide this warning to store owners and to implement a solution that offers this information in an acceptable manner. 

### Acceptance criteria

1. Confirm that detecting when custom fields are added to checkout is feasible.
2. Collaborate with design and product owners to devise appropriate feedback to store owners.
3. Implement a solution following the above discussions.

**Update: steps 1 & 2 have both been completed within this issue. Please read https://github.com/Automattic/woocommerce-payments/issues/8299#issuecomment-2314200704 for more up to date acceptance criteria on step 3.**

### Designs

Soon.

### Testing instructions

N/A

### Additional context

#5018 
#6539 
paJDYF-ckK-p2
paJDYF-ckK-p2#comment-23071
pb22l9-2s6-p2#comment-2665

CC @pierorocca and @nikkivias, to help us to decide the right format to provide this feedback to store owners.

### PR DESCRIPTION
**Pull request by gpressutto5**
Fixes #8299

#### Changes proposed in this Pull Request

Custom fields are currently incompatible with express checkout methods. This PR adds a notice next to the Apple Pay and Google Pay settings when a change in the checkout fields is detected.

image

image

#### Testing instructions

1. Go to WooPayments settings and notice there is no warning next to Google Pay / Apple Pay toggle section.
2. Go to Google Pay / Apple Pay page settings and notice there is no warning.
3. Install an extension to change/add checkout fields, or do it manually by using the filters `woocommerce_billing_fields`, `woocommerce_shipping_fields`, and `woocommerce_checkout_fields`.
4. Go back to 1. and 2. and ensure there is a warning.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8339` or branch name `express-checkout-incompatibility-notice` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=express-checkout-incompatibility-notice) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: cc4909b095ed4c188b215e4bd3363dfa948afa19
- Build time: 2024-03-18 15:23:45 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by timur27** [comment]
@gpressutto5  I enjoyed reviewing the implementation, and it tests well, thank you! Two things from my side:

1️⃣  I'm curious if checking the following hooks as well is worth consideration? They also allow adding custom fields. Happy to hear your opinion.

```php
woocommerce_before_checkout_billing_form
woocommerce_after_checkout_billing_form
woocommerce_before_checkout_shipping_form
woocommerce_after_checkout_shipping_form
```

2️⃣ On the Google Pay / Apple Pay settings page, the positioning of notification seems to be a little bit off

image

**Review by timur27 — COMMENTED** [review]
@gpressutto5  I enjoyed reviewing the implementation, and it tests well, thank you! Two things from my side:

1️⃣  I'm curious if checking the following hooks as well is worth consideration? They also allow adding custom fields. Happy to hear your opinion.

```php
woocommerce_before_checkout_billing_form
woocommerce_after_checkout_billing_form
woocommerce_before_checkout_shipping_form
woocommerce_after_checkout_shipping_form
```

2️⃣ On the Google Pay / Apple Pay settings page, the positioning of notification seems to be a little bit unexpected

image

**Comment by gpressutto5** [comment]
Hey @timur27 

1️⃣ The purpose of those filters we're checking is to be used to alter checkout fields. These actions are visual hooks and are not a safe way to add new fields. It can be challenging to check all the possible ways to add new fields, so I checked several different plugins and saw that they always use these filters. So, I believe we can use the filters, and if we still have problems in the future, we can think of another way. What do you think?

2️⃣ The notice component in your print seems different. Could you try rebuilding the bundle and clearing the cache? If the error still persists, please check how the notice is rendered in WooPay's settings page as we are using the same component.

image

**Review by timur27 — APPROVED** [review]
@gpressutto5 below are my responses but TL;DR is that I'm approving the PR and there's nothing blocking it from being merged. Thanks for the work you did here! 

> So, I believe we can use the filters, and if we still have problems in the future, we can think of another way. What do you think?

Totally agree with starting small and seeing if there is a need to extend the list of hooks we check. The reason I asked is I remember seeing these additional hooks in a pretty popular [third-party plugin](https://github.com/angelleye/paypal-woocommerce/blob/release/angelleye-includes/express-checkout/class-wc-gateway-paypal-express-helper-angelleye-v2.php#L267-L268). 


> The notice component in your print seems different. Could you try rebuilding the bundle and clearing the cache? If the error still persists, please check how the notice is rendered in WooPay's settings page as we are using the same component.

I rebuilt, and still, things display strangely. I tried using a different browser and cleared the cache, but had no luck. But then the WooPay notification on `develop` (screenshot below) displays the same way, so I am pretty sure this is unrelated to your PR.

image

**Pull request merged**
