### PR TITLE
Improve our job scheduling service for more resilience

### LINKED ISSUE #9434: Notices are triggered due to scheduling AS jobs too early
### Describe the bug

Sometimes we try to schedule ActionScheduler jobs via the WC_Payments_Action_Scheduler_Service::schedule_job() method before the ActionScheduler was properly initialized. This triggers a "doing it wrong" notice (see `ActionScheduler::is_initialized()`).

### To Reproduce

Most consistently, this can be reproduced by clearing the account cache:
1. Make sure you have WP_DEBUG active
1. Go to WP admin > WCPay Dev Tools and clear the account cache
1. You should see a notice at the top of the page:
```
Notice: Function as_has_scheduled_action was called incorrectly. as_has_scheduled_action() was called before the Action Scheduler data store was initialized Please see [Debugging in WordPress](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/) for more information. (This message was added in version 3.1.6.)
``` 

### Additional context
p1719838546986229-slack-C03KTTK2YMA

### PR DESCRIPTION
**Pull request by vladolaru**
Fixes #9434 
Related #6662 #5279 

#### Changes proposed in this Pull Request

We improved our job scheduling service to adjust to whether the ActionScheduler has been initialized or not. If it has, we schedule the job immediately. If it hasn't, we hook into the WP action that is fired on the ActionScheduler initialization (`action_scheduler_init`) and schedule the job then.

_Note:_ This will only work with WooCommerce 7.9.0+ (ActionScheduler 3.5.5+). The provided solution is backward compatible.

Additionally, I took the opportunity to snatch a performance gain and check with `as_has_scheduled_action` (introduced in ActionScheduler 3.3.0 - quite a while back) if there are scheduled jobs before un-scheduling them. We save up to 3 DB queries this way (see [details](https://github.com/woocommerce/action-scheduler/pull/688)).

#### Testing instructions

1. Checkout the PR's branch on your local client installation
1. Ensure your  client installation is talking to your local server
1. Make sure you don't have an account connected
1. Go to your client's WP dashboard > Tools > Scheduled Actions > Pending (`http://localhost:8082/wp-admin/tools.php?page=action-scheduler&status=pending`) and delete/run any `wcpay_` actions.
1. In another browser tab, go to WCPay Dev Tools and clear the account cache
1. In your pending scheduled actions list you should have an action with the `wcpay_update_compatibility_data` hook, scheduled for approx. 2 minutes into the future. Wait a couple of seconds, refresh the page, and see that the time for running the job is decreasing
1. Clear the account cache again and the action with the `wcpay_update_compatibility_data` hook should be rescheduled with a scheduled time of approx 2 minutes into the future
1. Onboard a sandbox account from the Payments page
1. On your local server, change [this line](https://github.com/Automattic/woocommerce-payments-server/blob/a12b669934caccbefef2f1349b0b2274782381ba/server/wp-content/rest-api-plugins/endpoints/wcpay/class-accounts-controller.php#L956-L956) to return the value `true`:
```
'has_more_failed_events'                  => true,
```
1. Clear the account cache again
1. Go to your client WP dashboard > Tools > Scheduled Actions > Pending page and you should now see two actions with the hooks `wcpay_update_compatibility_data` and `wcpay_webhook_fetch_events`
Screenshot 2024-09-13 at 18 36 16
1. Wait a couple of seconds, clear the account cache again, and you will notice that the two jobs got rescheduled (their scheduled datetimes have been reset)
1. Create a test order on your local store
1. After you've successfully completed the order, quickly go to the pending Scheduled Actions page and you should have a job with the `wcpay_track_new_order` hook.

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : QA Testing Not Applicable
- [x] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable: Not applicable
- [x] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable: Not applicable

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9435` or branch name `fix/9434-action-scheduler-service-schedule-job-init` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/9434-action-scheduler-service-schedule-job-init) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: b491c8aeddd05be25a0966fd95bf0ab1d1a8d847
- Build time: 2024-09-16 09:53:17 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by tpaksu — APPROVED** [review]
The logic makes sense, and nice catch @oaratovskyi. I think this would be sufficient to ensure AS is initialized before being used. Thanks for the fix! LGTM 🚀 it!

**Comment by vladolaru** [comment]
Thank you for digging into the flaky unit tests on GitHub CI, @tpaksu! I also thought about force-calling the AS init hook, but refrained from it because of the danger of side effects, the primary one being that the AS is not initialized, but we are "letting the world know" that it has.

But since we have no better way forward, and it is only affecting our unit tests, I think we can go with it and revisit if it turns out to bite us in the back.

**Comment by tpaksu** [comment]
@vladolaru the action `action_scheduler_init` doesn't seem to be triggered anywhere in the code on GH Actions, and because of that the job isn't scheduled. 

When I searched for `ActionScheduler::init` in my local client folder, it seems there are 4-5 different versions installed: 
- 3.7.2
- 3.1.6
- 3.8.0
- 3.8.2
- 3.7.4

and on `plugins_loaded` hook, it calls `ActionScheduler_Versions::initialize_latest_version()`  which seems to be stubbed in `/vendor/php-stubs/woocommerce-stubs/woocommerce-packages-stubs.php` with an empty body. 

I don't know if this is the real cause on GH, but maybe, we can add another clause to the function you modified on our side, that checks if the `plugins_loaded` hook did run, and `action_scheduler_init` is didn't run, and `ActionScheduler_Versions` class exists, then initialize the ActionScheduler manually with `ActionScheduler_Versions::initialize_latest_version()` or `ActionScheduler::init()`, to fix this on GH Actions.

**Comment by vladolaru** [comment]
**Update:** After much investigation with @tpaksu (see p1726471929778379/1719838546.986229-slack-C03KTTK2YMA), we found out why PHPUnit tests were failing in GitHub CI jobs, while they didn't locally. The reason is that we are using WC 7.6.0 in CI, and that version ships with a too-old version of ActionScheduler, one that doesn't fire the `action_scheduler_init` hook.

To maintain backward compatibility (until we increase the [minimum supported WC version](https://github.com/Automattic/woocommerce-payments/blob/307e0c0db4d5107e5a52fb85e35ce691fd8269ce/.github/workflows/compatibility.yml#L7-L7) - there was [an attempt](https://github.com/Automattic/woocommerce-payments/pull/7134#issuecomment-1715270236) to do so), we introduced logic to check for the WC 7.9.0 version.

**Review by oaratovskyi — APPROVED** [review]
Changes look good and work according to the instructions! :shipit:

**Pull request merged**
