### PR TITLE
Fixed Affirm using black logo on dark themes

### LINKED ISSUE #9804: Affirm logo not updating correctly according to the theme in Blocks checkout
### Describe the bug

The Affirm logo is not updating correctly according to the theme. It updates after using the blocks checkout page. It might be related to the transient not being updated when needed.

Image

### To Reproduce

1. Use a dark theme, or use CSS to update your background color to a dark color and the text color to a light color.
3. Go to the blocks checkout and see the affirm logo is black.
4. Go to the cart page, go back to the blocks checkout and see the affirm logo is now white

### Additional context
p1731716238180769-slack-CU6SYV31A

### PR DESCRIPTION
**Pull request by gpressutto5**
Fixes #9804

#### Changes proposed in this Pull Request

The Affirm logo was not updating correctly according to the theme. This PR fixes it by updating the theme after generating the appearance object. We can't use the same fix for shortcode checkout because it is rendered by PHP, so it requires refreshing the page after updating the appearance object.

p1731716238180769-slack-CU6SYV31A

#### Testing instructions

1. Comment [these lines](https://github.com/Automattic/woocommerce-payments/blob/447eb9b446e7583928d1d6fa23c4403d5221d757/includes/class-wc-payments-checkout.php#L227-L233) to prevent the appearance object from caching
1. Use a dark theme, or use CSS to update your background color to a dark color and the text color to a light color.
1. Go to the blocks checkout and see the affirm logo is white.
2. Switch to a light theme.
3. Go to the blocks checkout and see the affirm logo is black.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9805` or branch name `fix/upe-theme-block` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/upe-theme-block) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 683e34d25269df3b080700712a1f00cab1486277
- Build time: 2024-11-26 18:26:05 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by gpressutto5** [comment]
@pierorocca Could you test this build and see if it fixes the issue you found?

**Comment by pierorocca** [comment]
@gpressutto5 I'm still seeing inconsistencies. 

1. The logo theme, white on the product page and in the offer details on checkout, is different than the standard theme on the radio button on checkout.
2. The secondary font size "As low as.." is 18px while elsewhere on checkout it's 15.75px.
3. The offer text inside the expanded section is 16.74px. Not sure where that's being computed from. I'd have expected 15.75px?
4. "After submission, you will be redirected to securely complete next steps." is in the larger 18px font. I'd expect that to have been white font color?
5. Comparing Local Pickup font size 15.75px and color (117, 117, 117) vs. the font size 18px and color (89,89,89) of the offer secondary text, the forms looks out of balance. But also the Blocks color for the text looks arbitrary. It's not a theme color rather a Blocks color?

- Secondary question, what's the best element to compute the styles for "As low as.." and the offer details text within the expanded section? I don't think we have a clear answer for this.


image

image


image

**Comment by gpressutto5** [comment]
@pierorocca 

> 1. The logo theme, white on the product page and in the offer details on checkout, is different than the standard theme on the radio button on checkout.

I spent some time looking for a quick fix, but I couldn't find the cause. From what I understand, the logo on the Blocks checkout label, which is the focus of this issue, is now correct, and the error is in the PMME of the product page, and in the Payment Element, right?
If that's the case, can we create another issue to investigate this and continue with the fix for the label logo?

-----

We can handle items 2 to 5 + Secondary question in #9803. Maybe even the Payment Element part of the first item will be fixed in that.

**Comment by gpressutto5** [comment]
I don't have the "Available offers" text when I select the payment method.

p1732645887236539-slack-CU6SYV31A

image

**Review by timur27 — APPROVED** [review]
The tests and code look good. From the comments, I understand that the pending inconsistencies currently under discussion will be addressed in a separate PR. Please let me know if there's anything else I can assist with—happy to jump in as needed!

**Pull request merged**
