### PR TITLE
Address various platform checkout UI issues

### LINKED ISSUE #3856: Address various platform checkout UI issues.
### Description
While working on some other platform checkout features I discovered a few issues/bugs that need to be addressed.

For the "Remember your details" section:
* We need to capture the phone number from the main checkout fields and pre-fill that value into the phone number field.
* Before a user can process their checkout, if the `Save my information...` box is checked, the phone number field there must be filled out.
* Ensure that the phone number here is being validated.
* The selected country code from the phone number is not being sent with the form data.

Other items:
* I also noticed an error on the Order Received page coming from `email-input-iframe.js`
* Make the billing email validation consistent with how WordPress validates emails before checking if the user exists. This is causing 400 responses when an invalid-in-WordPress email is sent like `a@a`.

```
Uncaught TypeError: Cannot read properties of null (reading 'parentNode') at handlePlatformCheckoutEmailInput (email-input-iframe.js:13:47)
```

### Acceptance criteria

* If the checkout phone number field has a value when the `Save my information...` box is checked, pre-fill that value into the platform checkout phone number field.
* Checkout will display an error if there's an invalid phone number entered when the `Save my information...` box is checked.
* Phone numbers entered into the platform checkout phone number field are validated before checkout submission.
* The selected country code from the platform checkout phone number field is captured and sent with the rest of the form data.
* `email-input-frame.js` is properly checking for the existence of the email input field and no error occurs if it's not in the DOM.
* Email addresses are only checked after they pass validation consistent with how WordPress expects email addresses.

### PR DESCRIPTION
**Pull request by brettshumaker**
Fixes #3856 

#### Changes proposed in this Pull Request

This PR addresses the following issues:
- Capture the phone number from the main checkout fields `billing_phone` (if it exists) and pre-fill that value into our phone number field.
- Block checkout form submission if our `Save my information...` box is checked but the phone number entered is invalid.
- Run validation provided by the `intl-tel-input` on the phone number entered.
- Ensure that the full phone number (including country code) is being submitted with the rest of the form data.
- Check that the email field is present before attempting to do anything with it.
- Validate the email address consistent with `is_email()` in WordPress before pinging the platform checkout to check the user.

#### Testing instructions

- Checkout this PR.
- Run `npm start`.
- Add product to cart on your local merchant site.
- Go to shortcode checkout.
- **Email Verification:**
   - Enter in `a@a` and verify that the email **IS NOT** checked on the platform checkout.
   - Enter in `a@a.` and verify that the email **IS NOT** checked on the platform checkout.
   - Enter in `a@a.c` and verify that the email **IS NOT** checked on the platform checkout.
   - Enter in `a@a.co` and verify that the email **IS** checked on the platform checkout.
- **Prefill Phone Number:**
   - Enter a valid phone number in the main checkout fields.
   - Check the "Save my information for faster checkouts." box.
   - Ensure that the phone number is copied to the new phone number field.
- **Phone Number Validation:**
   - Change the phone number to an invalid number `1234` and click out of the field.
   - Ensure that the field is marked with an error with helper text beneath.
   - Ensure that the "Place Order" button is disabled.
   - Re-enter a valid phone number and click out of the field.
   - Ensure that the "Place Order" button is enabled.
- **Checkout `$_POST` data:**
   - Fill out all necessary checkout data (email, phone, address, payment info)
   - Check the "Save my information for faster checkouts." box.
   - Submit checkout form.
   - Check the posted data to make sure it includes `$_POST['platform_checkout_user_phone_field']['full']` and that it includes the country code with the phone number entered ex. `+12124567890`
- **No javascript error on the order received page.**
   - After submitting your order, make sure there's no javascript error coming from `email-input-iframe.js`.

### CODE REVIEW

**Review by harriswong — COMMENTED** [review]
Code LGTM. I tested the following:
- email verification with `a@a.co`
- prefill phone #
- phone number validation

There is 1 issue with the "Checkout $_POST data". In my test, the `full` field is empty:
image

I did this by doing the following:
1. enter email `a`, `a@`, `a@a.ne`
2. Then move to click "Save my information..."
3. Click dropdown to "United Kingdom +44", type in "1234567"
4. Type more random things (not sure if this mattered)
5. Type `6477788999`
6. Then switch dropdown to "Canada +1"
7. Scroll down page
8. Click "Place Order"
9. At this point, the $_POST is missing the `[full]` field for some reason.

**Comment by brettshumaker** [comment]
> There is 1 issue with the "Checkout $_POST data". In my test, the full field is empty:

@harriswong I'm not able to reproduce this. 😕 Did this happen multiple times for you?

**Comment by harriswong** [comment]
> @harriswong I'm not able to reproduce this. 😕 Did this happen multiple times for you?

It happened to me the first time as I stepped through the steps. Then I couldn't reproduce for a while. After a few tries changing phone number and the email field in a new tab, it happened once more. I didn't try further.

**Comment by brettshumaker** [comment]
@harriswong I think that since this isn't reliably reproducible, we can move forward with merging this in and I'll create a follow-up issue for adding some more thorough server-side validation to the phone number.

**Review by harriswong — APPROVED** [review]
LGTM :shipit: 

I also can't reproduce the same error after the 2 times I mentioned [here](https://github.com/Automattic/woocommerce-payments/pull/3873#pullrequestreview-896980759). 
If this issue comes up again, we will create a separate issue with and look into it.

**Pull request merged**
