### PR TITLE
Fix display of multiple payment method fees

### LINKED ISSUE #3241: Fees: Update how fees per payment method are displayed on the overview page
We've got plenty of payment methods available through UPE (7 and counting), most of which have different fee structures. Their fees need to be displayed on the Overview page of the plugin, as initially noted in https://github.com/Automattic/woocommerce-payments/issues/2377.

PR https://github.com/Automattic/woocommerce-payments/pull/3055 addressed this issue based on [these Figma designs](35wcSfexs3z8pxrj4daJnH-fi-0%3A1). However, before releasing `3.2.0` we realized that there's a bug, and even if the bug were fixed, the results are not ideal.

## Initial bug 

h/t @htdat for discovering this and suggesting a [fix for it](https://github.com/Automattic/woocommerce-payments/pull/3239):

Markup on 2021-10-28 at 10_22_28

The fix included:

- Making sure that fees are displayed even when there are no discounts.
- Adding translations for all available payment methods.
- Fixing a small conditional logic issue.

## After the fix

Screenshot 2021-10-28 at 8 54 14

- All PMs are displayed: This includes payment methods, which are not added to the particular store. h/t @aprea for noticing this. I did not, because I had already enabled all payment methods.
- With multiple payment methods, and without discounts, it looks like someone copy-pasted the data from Notepad 😆 
- There are repeating `Learn more` links, which point to the same page. Seems like we might want to add a top-level link to the page with all fees, and then only display `Learn more` whenever there is a promotion.

### PR DESCRIPTION
**Pull request by htdat**
Fixes: #3241
Discussion p1635391455166700-slack-CGGCLBN58
Related PR: #3055 

#### Changes proposed in this Pull Request
- show discounts only on overview page ( do not show the fees if there are no discounts )
- add translations for all available methods
- fix a small conditional logic issue.
- show only payment methods that are added to the particular store
- "Learn more" is be added only 1 time and not for every payment method

#### Testing instructions
- Add a discount fee with multiple payment methods. You can do this in 2 ways:
1. Select a fee structure on server side (wcpay/fees folder) and add it using the CLI command: 
`wp wcpay add_fee_structure_to_account <stripe_account_id> --fee_structure_id=<fee_structure_id>`
2. Add the fee manually in the database,`wcpay_test_account_fee_structures` table. In order to have the fee active `end_date` field should be in the future or null.

We should have only 1 fee structure active for an account. In theory, an account can have more than one account fee structure at the same time. However, the current implementation of promotions only allows a single fee structure to be applied at the point an account is created. So we're unlikely to see this in practice at the moment.

- Re-login or clear the account cache 
- Go to Payments -> Overview
- Check if the discount is displayed properly under the Account details->Active discounts  section for each payment method

-------------------

- [ ] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply)

### CODE REVIEW

**Comment by htdat** [comment]
@dpaun1985 - I am seeing you're working on this PR. Since we no longer target it for a patch release, you may want to change the target branch of this PR from `trunk` to `develop`.

**Review by dmvrtx — APPROVED** [review]
Visually looks well, works as expected! 🚢

**Comment by htdat** [comment]
@dpaun1985 and @dmvrtx: I've added `status: blocked` as this PR relies on https://github.com/Automattic/woocommerce-payments/issues/3285 to move forward.

**Comment by dpaun1985** [comment]
blocked by #3300

**Comment by tpaksu** [comment]
#3300 is merged now. Sorry for the delay.

**Pull request merged**
