### PR TITLE
Fixed tooltip in mobile settings view

### LINKED ISSUE #6950: Tooltips are getting cut off on mobile, switch to WP component for better accessibility
### Describe the bug
The `tooltip` component being used in WooPayments is not accessible on mobile. The text is cut off by the edge of the viewport which impacts readability. 

### To Reproduce

1. Go to Settings > Payments > WooPayments
2. Hover over any payment method that's disabled, or the fees pill in mobile view
3. See error

### Actual behavior
On smaller device sizes, the tooltips are getting cut off. When working with @mordeth on the [JCB rollout](https://github.com/Automattic/woocommerce-payments/pull/6905#issue-1833604777), it was discovered that the tooltips implemented in WCPay don't have any positioning options to account for different device sizes.

Screen Shot 2023-08-02 at 1 48 33 PM
Screen Shot 2023-08-02 at 1 48 24 PM

### Expected behavior
As discussed in `p6riRB-8NZ#comment-9534`, we should be using the existing tooltip component in the @wordpress/components package. This will provide the ability to use dynamic positioning based on the size of the viewport as shown in this screenshot from [Storybook](https://wordpress.github.io/gutenberg/?path=/docs/components-tooltip--default).
image

The main consideration with this update is that the tooltip persists on mouseover so the user is able to access any links included in the copy. Here are two designs to illustrate the dynamic positioning of the WP tooltip component.
Screen Shot 2023-08-08 at 3 06 25 PM
Screen Shot 2023-08-08 at 3 06 34 PM

Also related to #6917 cc @naman03malhotra Could this update be included as part of the #6903 scope of work?

### PR DESCRIPTION
**Pull request by naman03malhotra**
Fixes #6950 

#### Changes proposed in this Pull Request
In this PR I've fixed tooltip alignment for mobile view. I have done this in two ways.

- I've removed the downward arrow as per the design and now it is aligned to `woordpress/tooltip` design.
- I've made some changes to the how the position of the tooltip is calculated when the element goes outside of the view port.

Screenshot 2023-10-19 at 15 47 50
Screenshot 2023-10-19 at 15 48 03
Screenshot 2023-10-19 at 15 48 20
Screenshot 2023-10-19 at 15 49 35

Screenshot 2023-10-19 at 15 49 46

NOTE: This change will make the tooltip design change everywhere it is been used and align it more with wordpress/tooltip design as advised the issue.

#### Testing instructions

- Goto Payment > Settings
- Enable Multiple payment methods by switching store currency to EUR
- Open the browser dev tools and switch to the mobile view
- Check mobile responsiveness as expected
- Make sure the desktop version UI doesn't change and is as expected.
- Check the dropdown position in both mobile and desktop versions.
- Check if the functionality is intact and doesn't change on either desktop or mobile.

image

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [x] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [x] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7515` or branch name `fix/6950-fix-imp-mobile-tooltip` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/6950-fix-imp-mobile-tooltip) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 177781c5ce2126ff6fe330ecad2ea27b03cb2ee6
- Build time: 2023-10-24 08:13:09 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by elizaan36** [comment]
@naman03malhotra Looks great! A couple questions:
- Does this use the Gutenberg tooltip component? 
- Does the tooltip persist on hover so the link can easily be clicked?

**Comment by naman03malhotra** [comment]
>Does this use the Gutenberg tooltip component?

No, WCPayments has its own [Tooltip component](https://github.com/Automattic/woocommerce-payments/tree/develop/client/components/tooltip), which we use generally.

**Comment by naman03malhotra** [comment]
>Does the tooltip persist on hover so the link can easily be clicked?

Yes, as you can see in the screen-recorded video

https://github.com/Automattic/woocommerce-payments/assets/15019298/e2c2ba2a-ab33-4f77-b01a-b98f51dda3fb

**Comment by naman03malhotra** [comment]
@elizaan36 can please give a final review from a design perspective?

**Review by jessy-p — APPROVED** [review]
Tested, LGTM!

**Comment by elizaan36** [comment]
Thanks, Naman. LGTM!

**Pull request merged**
