### PR TITLE
chore: remove unused UPE JS functions

### PR DESCRIPTION
**Pull request by frosso**
Fixes #

#### Changes proposed in this Pull Request

The `getCookieValue` , `isWCPayChosen `, `getBillingDetails` and `getShippingDetails` functions are not used anywhere in the codebase.
Removing.

#### Testing instructions

*

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8296` or branch name `chore/remove-unused-upe-js-functions` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=chore/remove-unused-upe-js-functions) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 6236df855c13abf51dc0e9e78069a9b9ebb9fd03
- Build time: 2024-03-04 10:31:46 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by FangedParakeet — COMMENTED** [review]
Thanks for taking the time to throw these pesky stowaways overboard! Can we get rid of [this one](https://github.com/Automattic/woocommerce-payments/blob/develop/client/checkout/classic/test/3ds-flow-handling.test.js#L8) too? 

Looks like it's just a mock for a function that you've removed from the utils in here. Tests seem to be working fine now without it. 🤷

**Comment by frosso** [comment]
@FangedParakeet good catch, thank you!

**Review by FangedParakeet — APPROVED** [review]
Cheers for the litle addition! LGTM. :shipit:

**Pull request merged**
