### PR TITLE
Revemoved pre-fretch session for button

### LINKED ISSUE #7256: Trying to check out a "stock: 1" product fails with WooPay
### Describe the bug
When a product that has the stock level set to 1 is in the cart and I try to checkout with WooPay, I get the "WooPay is unavailable at this time. Sorry for the inconvenience." message on the Cart page.
image

### To Reproduce
1. Create a product that has Stock 1 set
2. Add this product to the cart
3. Try to pay for it with WooPay from the cart

### Actual behavior
Instead of redirecting to WooPay's checkout page, I'm getting errors.

**Cart page**
"WooPay is unavailable at this time. Sorry for the inconvenience." message on the Cart page.
image
Video:
https://github.com/Automattic/woocommerce-payments/assets/133644769/6192fd5b-5a2b-41f3-a955-2575f9aa3b12

**Checkout page**
Going to the Checkout page _sometimes_ I get an error:
"There are some issues with the items in your cart. Please go back to the cart page and resolve these issues before checking out."
image
Going back to the cart I can see a new message now:
"Sorry, we do not have enough “Stock 1” in stock to fulfill your order (0 available). We apologize for any inconvenience caused"
image
However, no purchase was made and the cart page before said there's 1 in stock. (The stock level is not actually reduced, but it seems like it is.)

Other times the same error is present what's on the Cart page.

### Expected behavior
I should be redirected to the WooPay checkout page to pay.

### Desktop:

* OS: Mac 13.5.2 (22G91)
* Browser Chrome
* Version 117.0.5938.88

### Additional context
Occurs at #7046997-zen

### PR DESCRIPTION
**Pull request by gpressutto5**
Fixes #7256

#### Changes proposed in this Pull Request

When we preload the checkout response to pass to WooPay, [it creates a draft order](https://github.com/woocommerce/woocommerce-blocks/blob/38ae651c9c3a19ae4ba32773d2d35b351cd081e7/src/StoreApi/Routes/V1/Checkout.php#L150C22-L150C22). Ever since the session data prefetch was implemented in #7199, this preload happens whenever the WooPay button is displayed. Because of this, a draft order is created just by going to the checkout page. This reserves the stock, but the checkout tries to create a new one, and it fails because there's no stock left.
This PR removes this prefetch, making it work.
It **doesn't fix** the same error after the modal is open and then closed, or redirected to WooPay and then getting back. These issues belong to #7257.

#### Testing instructions

1. Enable the WooPay button on the cart and checkout pages
1. Create an item with only 1 in stock and run a few test scenarios (you have to update the stock back to 1 after each test):
    1. Using the WooPay button from the cart page and paying with WooPay.
    1. Going to the cart page before going to the checkout page and paying with regular checkout (make sure not to type a valid woopay address in the field).
    1. Going to the cart page before going to the checkout page and paying with WooPay Button.
    1. Going to the cart page before going to the checkout page and paying with WooPay email input.
    1. Going directly to the checkout page and paying with regular checkout (make sure not to type a valid woopay address in the field).
    1. Going directly to the checkout page and paying with WooPay Button.
    1. Going directly to the checkout page and paying with WooPay email input.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7764` or branch name `revert-prefetch-session-for-button` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=revert-prefetch-session-for-button) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 21b2e93c459383fc8d3a1e566b1b10d4e1ee46ee
- Build time: 2023-12-01 20:41:16 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by hsingyuc — COMMENTED** [review]
@gpressutto5 Good work!  While testing iii., the modal doesn't show up for me. I got redirected to the WooPay checkout page on the first-party auth flow.  But when testing "Going directly to the checkout page".  I'm getting a checkout error, see below:

https://github.com/Automattic/woocommerce-payments/assets/56378160/c67a6a92-1dff-478c-8113-f0d32962cc0d

**Comment by gpressutto5** [comment]
Thanks @hsingyuc! I forgot to mention draft orders live for up to 10 minutes after each test. Could you try removing all existing draft orders before reproducing this issue again and check if it still happens? Assuming you start testing without any, no draft orders should be created unless the WooPay Modal is displayed or you get redirected to WooPay, and those orders should last only until the Payment is successful in WooPay.

**Review by hsingyuc — APPROVED** [review]
@gpressutto5 I removed draft order and tested again. All tests are as expected and LGTM.

**Comment by gmaysonnavefranck** [comment]
LGTM

**Pull request merged**
