### PR TITLE
perf: unneeded WooPay scripts

### PR DESCRIPTION
**Pull request by frosso**
Fixes #

#### Changes proposed in this Pull Request

[The `client/checkout/woopay/index.js` scripts](https://github.com/Automattic/woocommerce-payments/blob/develop/client/checkout/woopay/index.js) are used on checkout pages to render the "save user" section.

I noticed these scripts are enqueued on every page, even product pages.
Together with these, more than half a dozen additional WC Blocks scripts are being enqueued.

Since we don't need to render them on non-checkout pages, let's ensure they are not enqueued.

#### Testing instructions

- Ensure you have WooPay enabled
- Go to a product page
- You should no longer see the `dist/woopay.js` file enqueued
- Go to checkout
- You should see the `dist/woopay.js` file enqueued

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8829` or branch name `fix/woopay-save-user-on-non-checkout-pages` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/woopay-save-user-on-non-checkout-pages) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: daa772fb79c074db2b1927aa5d519e9b2f38ec10
- Build time: 2024-05-17 12:26:29 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by brettshumaker — APPROVED** [review]
🙌 Looks good

**Comment by frosso** [comment]
Thanks @brettshumaker - I'll be waiting for people's blessings in here before merging
p1715850513186709-slack-C022WMN88KG

**Comment by frosso** [comment]
It looks like this PR has been merged with only the changelog entry. This is because the same changes were also implemented in https://github.com/Automattic/woocommerce-payments/pull/8644 , which has been merged first.

**Pull request merged**
