### PR TITLE
Update elligibility flag worflows

### PR DESCRIPTION
**Pull request by dpaun1985**
#### Changes proposed in this Pull Request
- On account data, force `card_present_eligible` flag to false.

#### Testing instructions

* set card_present_enabled meta to 1 for the current store
* make an api call request to `v3/payments/accounts`
* `card_present_eligible` should be false

Screenshot 2021-10-25 at 15 56 43

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply)

### CODE REVIEW

**Review by anu-rock — APPROVED** [review]
LGTM :shipit: 
I've approved the PR with a nitpicky comment.

**Review by dmvrtx — APPROVED** [review]
Looks good to me! 🚢

**Comment by mgascam** [comment]
Looks good to me! I followed testing instructions and works as expected 🚀

**Review by mgascam — APPROVED** [review]
Looks good to me! I followed testing instructions and works as expected 🚀

**Pull request merged**
