### PR TITLE
Update/2194 replace connect account page exp

### LINKED ISSUE #2194: Replace connect account page experiment with the treatment experience
The experiment [here](https://github.com/Automattic/woocommerce-payments/blob/1d678c40e21c1cb16ba288d2d49d8c12f81cf36b/client/connect-account-page-experiment/index.js#L14-L23) relating to the connect account page, needs to be discontinued, with the treatment experience (`ConnectAccountPageVariant`) becoming the only experience (ie renamed to `ConnectAccountPage` and the experiment removed).

### PR DESCRIPTION
**Pull request by moon0326**
Fixes #2194 

#### Changes proposed in this Pull Request

This PR removes `wcpay_inapp_payments_connect_page_v2` experiment and replaces the default experience with the treatment experience. The treatment experience is now the default.

1. Renamed `connect-account-page-variant` to `connect-account-page`
2. Removed `connect-account-page-experiment` component.

#### Testing instructions

1. It is best to start testing in an Incognito window if you have been testing this experiment.
2. Navigate to Payments and confirm the treatment experience is shown.

#### Screenshots
Screen Shot 2021-06-15 at 4 15 20 PM

### CODE REVIEW

**Review by adrianduffell — APPROVED** [review]
@moon0326 Code looks good and it tested well. Thanks for picking up this one 🏅

**Comment by dechov** [comment]
👋 Was the centering of the text here an intentional change? I believe it was centered in the old version of the screen but (correct me if I'm wrong) not the new one.

**Comment by elizaan36** [comment]
No, it should be left aligned to match the original experiment.

**Comment by moon0326** [comment]
Thank you @dechov and @elizaan36. I will make a new PR to fix it.

**Pull request merged**
