### PR TITLE
Switch to proper input element when using Stripe Link autofill

### LINKED ISSUE #7791: Stripe Link payment with account having saved payment methods
### Description

I am a customer, with saved payment tokens & I want to use Stripe Link.
The saved CC payment token will appear as the default selected one on the checkout, which is good.
Screenshot 2023-11-27 at 1 45 21 PM

Once I select Stripe Link as a payment method by clicking the "link" icon on the email field, and I opt to autofill, the saved token is still the selected payment method.
Screenshot 2023-11-27 at 1 46 11 PM
Screenshot 2023-11-27 at 1 47 08 PM

Instead, I would expect Stripe Link to be selected 
Screenshot 2023-11-27 at 1 47 20 PM

### Acceptance criteria

When a customer selects "Stripe Link" as a payment method, Stripe Link becomes the selected payment method.

### Testing instructions

- Ensure Stripe Link is enabled in the WooPayments settings
- Ensure you're a customer with saved payment methods (if you don't add them into the "My account" page)
- Ensure you have a Stripe Link account
- Go to checkout
- Select Stripe Link
- Select autofill

### PR DESCRIPTION
**Pull request by timur27**
Closes https://github.com/Automattic/woocommerce-payments/issues/7791

#### Changes proposed in this Pull Request
This PR
* ensures that with saved payment tokens on the shortcode checkout page, when autofilling payment details with Link, the input element selected is switched from the default saved payment token to the auto-filled Stripe Link element
* switches from the default saved payment token to new payment token when users click the Stripe Link button within the email field
* focuses on introducing the above two changes in the shortcode checkout, because Blocks checkout stays unaffected due to different nature of rolling out Stripe Link on the page (it does so only after users select new payment token)

#### Testing instructions

> please remove all saved payment methods before starting.

* open the shortcode checkout and provide a non-registered Stripe Link email: you should be able to see the _save to Link_ checkbox after providing the card details. Select this checkbox & save details to Link.
* prepare another cart and open the shortcode checkout: click the Link button in the email element and confirm that autofill works as expected. Complete the transaction by either closing the page or purchasing the product.
* save a new payment method either by navigating to _My account -> Payment methods_ or by saving payment method during the payment. Make sure that the saved payment method is set as default.
* go to checkout page, confirm the saved payment token is selected by default
    * click Stripe Link button and verify that together with Link modal popping up, the selected payment method is switched from saved token to the new payment element which is used for injecting details from Link after completing its autofill modal 
    * complete the autofill modal steps and confirm you have the right payment method selected
    * complete the purchase, navigate to order details in the admin panel, open payment intent details and confirm payment method is Link 
    * confirm payment method is Link on Stripe side
* navigate to shortcode checkout page again but this time just pay with the saved payment token (card) which is selected by default
    * in the order details -> payment intent details, confirm that the payment method is now CC
    * confirm payment method is CC on Stripe side
 * ensure that the non-registered Stripe Link email is used on the shortcode checkout page and open it
 * the saved card should be now still selected by default
 * click the Stripe Link button and confirm that the input element selected is switched from the default saved payment token to the new payment token
 * provide card details and confirm you now see the _save to Link_ checkbox
 * use Stripe Link in Blocks checkout and confirm that main flows from above are working correctly.
     * among others, check the following specific scenario: while having saved payment tokens, 
         * open Blocks checkout & confirm the Stripe Link button is not displayed unless you click the new card element
         * switch back to selecting the saved payment token and confirm the Link button was removed (more details in https://github.com/Automattic/woocommerce-payments/issues/7791#issuecomment-1892418841 and https://github.com/Automattic/woocommerce-payments/issues/7791#issuecomment-1893639593)
         * choose new card payment method again and confirm Stripe Link button is back again and can be used without problems

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8017` or branch name `align/stripe-link-behavior` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=align/stripe-link-behavior) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 82b3547d2cab5044d7e0b9a6304e559db5f4f995
- Build time: 2024-01-18 09:22:19 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by timur27** [comment]
Failed tests are unrelated: more in p1705327107507089-slack-C026J0AL8NS
UPDATE: more e2e tests are failing and they are failing on other PRs as well ([example](https://github.com/Automattic/woocommerce-payments/actions/runs/7541032485))

**Review by gpressutto5 — APPROVED** [review]
Working as expected

**Comment by timur27** [comment]
Resolved conflicts, re-tested the flow, confirmed everything looks alright, merging.

**Pull request merged**
