### PR TITLE
Update customer multi-currency default settings and options

### LINKED ISSUE #2091: Default settings and additional options for price rounding and charm pricing
### **General updates:**

Update the "Charm pricing label to read "Price charm"
Remove the tool tips before the select menus
remove the "learn more" links from the select menu helper text. I think it should be easy enough to figure it out by playing with the settings and viewing the preview. 

### **Decimal currencies**

**Price rounding options**

None
0.25
0.50
1.00 (recommended) *default
5.00
10.00

**Price charm options**

None *default
-0.01
-0.05

Lets be sure we remove the (recommended) label from the -0.01 in charm pricing

### **Non-decimal currencies**

**Price rounding options**

None
10
25
50
100 (recommended) *default
500
1000

**Price charm options**

None *default
-1
-5
-10
-20
-25
-50
-100

### PR DESCRIPTION
**Pull request by luizreis**
Fixes #2091 

#### Changes proposed in this Pull Request

- Update the "Charm pricing" label to read "Price charm"
- Remove the tooltips for Price rounding and charm
- Remove the "Learn more" links from the Price rounding and charm descriptions
- Remove the "(recommended)" label from the -0.01 charm option
- Fix typo in preview description
- Modify get_ceil_price to accept an arbitrary rounding value
- Update decimal currency rounding options
- Add zero decimal currencies price rounding and charm options
- Update default price rounding option

It's worth noting that as part of this change, the `get_ceil_price` logic has been altered to work with arbitrary values, such as `0.25` and `0.5`. This is a breaking change with the previous values used by the rounding options, but it was not addressed automatically as part of this PR because multi-currency is not being used by merchants yet.

#### Testing instructions

* Make sure all the changes requested in #2091 are implemented by this PR
* Check that the new price rounding and charm options work properly in the shop and preview
* Check that the appropriate options for zero-decimal currencies are displayed

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

**Review by dmallory42 — APPROVED** [review]
LGTM and works well. I have one question but it may not even be related to this PR so I'm pre-approving this! 🚢 

For zero-decimal currencies, I'm wondering whether we should even allow `None` as an option for price rounding? I know that the exchange rate can contain decimals (e.g. in the case of USD -> VND it's 1 ->  22948.544398). However in practice, AFAIK Vietnam has no concept of decimal amounts in their currency, and if no price rounding is applied, a price of $20 USD would be converted to ₫458,920.89. I'm wondering whether for decimal currencies we should make 1 the lowest possible price charm that can be selected?

Again, apologies if this has been discussed elsewhere, I know it's not strictly related to the PR but just wanted to mention it.

**Comment by luizreis** [comment]
> For zero-decimal currencies, I'm wondering whether we should even allow `None` as an option for price rounding? I know that the exchange rate can contain decimals (e.g. in the case of USD -> VND it's 1 -> 22948.544398). However in practice, AFAIK Vietnam has no concept of decimal amounts in their currency, and if no price rounding is applied, a price of $20 USD would be converted to ₫458,920.89. I'm wondering whether for decimal currencies we should make 1 the lowest possible price charm that can be selected?

That makes sense, but I think we could keep it to give more control to merchants. Especially since it's not the default value. Once #2246 is resolved, zero-decimal currencies should be formatted appropriately, so WC would do the rounding because `wc_get_price_decimals` would be 0.

It might be worth confirming with @LevinMedia, though. In the meantime, I'll merge this PR and we can open a new issue if we want to remove it.

**Comment by LevinMedia** [comment]
>For zero-decimal currencies, I'm wondering whether we should even allow None as an option for price rounding?

@dmallory42 @luizreis after giving this a test, I agree that we should make 1 the minimum rounding option for non-decimal currencies. Also where we're showing the preview of a non decimal currency, we shouldn't show the decimal - for example, with yen - this should simply read 1700

Screen Shot 2021-06-29 at 4 30 43 PM

I also noticed when testing this that decimal currencies are defaulting to no rounding, rather than to 1.00 - could we please update that to match this screen shot too?

Screen Shot 2021-06-29 at 4 35 42 PM

**Comment by dmallory42** [comment]
@LevinMedia Thanks for getting back to us on this! I've opened a new issue to make those changes. 👍

**Pull request merged**
