### PR TITLE
Fix - Jurassic Tube Setup Script Directory Creation

### PR DESCRIPTION
**Pull request by achyuthajoy**
#### Changes proposed in this Pull Request

While setting up Jurassic Tube tunnel, the setup script tries to create the directories `bin/jt` under `docker`. However, the directory creation fails terminating the script since it involves creating a parent and a child directory.

This PR fix the problem by instructing `mkdir` to create both the parent & child directories.

Screenshot

#### Testing instructions

* Checkout `develop`, install dependencies & run the script `npm run setup:jurassic-tube`. (Make sure you haven't set this up earlier. Ideally run in a fresh copy of the repo).
* Notice that the script errors while creating the required directories.
* Checkout the branch `fix/jurassic-tube` & run the script `npm run setup:jurassic-tube` again.
* Notice that the script executes as expected and the tunnel is set up.

-------------------

- [ ] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

### CODE REVIEW

**Comment by naman03malhotra** [comment]
@achyuthajoy here is the PR https://github.com/Automattic/woocommerce-payments/pull/1578 for your reference.

Thread: p1618501000326400-slack-CGGCLBN58

**Comment by naman03malhotra** [comment]
Btw @achyuthajoy I didn't face this error while setting up my local. Maybe `bin` already existed for me 🤔? Not sure, need to check.

**Comment by achyuthajoy** [comment]
Hey @naman03malhotra I don't see `docker/bin` directory in the repo code itself. Try cloning the repo to a new location and try. I've tried it multiple times on my machine and every time I get the same error.

Also, I recommend keeping the change because it can handle creation of nested directories and doesn't fail.

**Comment by shendy-a8c** [comment]
LGTM.

**Review by shendy-a8c — APPROVED** [review]

**Comment by achyuthajoy** [comment]
E2E tests / E2E tests (4.0.0, 5.4, 7.0) failure not related to this PR. Merging

**Pull request merged**
