### PR TITLE
Add icons as a new column

### PR DESCRIPTION
**Pull request by harriswong**
Fixes https://github.com/Automattic/woocommerce-payments/issues/1989

#### Changes proposed in this Pull Request
- Add WCPay logos to the right of the "WooCommerce Payments" text in `wp-admin/admin.php?page=wc-settings&tab=checkout&section`. 
- Replace "Credit card" to "Popular payment methods" per design.

#### Testing instructions
1. Go to `wp-admin/admin.php?page=wc-settings&tab=checkout&section`
2. Make sure the logo shows up on the right as follow:
image

-------------------

- [ ] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

### CODE REVIEW

**Comment by harriswong** [comment]
Good question. The checkout shares the same "title" as the payment method. We added "Apple Pay" and "Google Pay" icons which really aren't "credit cards". 

I personally think "popular payment methods" and "credit card" are fine. But I am not sure; I'm going to ping design.

**Comment by harriswong** [comment]
Double checked latest design, looks like it will be "Credit card/ debit card". I am going to update the title.

**Comment by harriswong** [comment]
**Updated.**

Settings page now shows:
image

Checkout now shows:
image

**Review by frosso — APPROVED** [review]
Thanks for the changes!

**Pull request merged**
