### PR TITLE
Reduce multiple urgent dispute signals

### LINKED ISSUE #7504: Small UI fixes for Transaction details: Add separator on balance breakdown line at top & remove redundant deadline urgency string
### Description
A couple of follow-ups to ensure the Dispute modal follows the Figma design

### Acceptance criteria

1. Add a small separator line between converted currency and the next line item.

Currently the converted currency is right next to the balance breakdown items, and it is confusing trying to make out their relation to one another. We are adding this separation line after the converted currency so it doesn't appear as part of an equation, and visually becomes more connected to the main currency

Screenshot 2023-10-16 at 10 16 38 PM

2. For the 'Needs response' stage for Inquiries and disputes, please remove the 2nd appearance of the [X days left] string, which is in the last step of 'Steps to resolve'.

We have sufficient urgent signals in the modal such as the colored pill and banner, as well the 1st appearance of the string. So 2nd appearance has become redundant.

272725609-eed3158e-a1ad-458b-80a0-f3d29172c484

Screenshot 2023-10-16 at 10 20 36 PM

### Designs
[See on Figma](https://www.figma.com/file/RiEQmaKRI7u9USAI3lyZz0VX/Dispute-Flows?type=design&node-id=7733%3A81755&mode=dev&t=Gg0FaIJBj38ntmlx-1)

### PR DESCRIPTION
**Pull request by naman03malhotra**
Part 2 of #7504 

#### Changes proposed in this Pull Request
- Added `showRemainingDays` prop to due date for conditional rendering.
- This PR fixes removes the redundant due date in the dispute checklist. See issue.
- Removes "." from the end of the sentence

#### Testing instructions

- Tests should pass.
- Make sure the behavior is as expected in the issue.
image

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8274` or branch name `add/7504-prop-to-due-date` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=add/7504-prop-to-due-date) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 3965fcce7c0f3ba577fded3c2317e43b1127cae7
- Build time: 2024-02-28 07:03:24 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by naman03malhotra** [comment]
I created a follow up PR (https://github.com/Automattic/woocommerce-payments/pull/8275) based on this PR, as I wanted to make sure my approach is correct.

**Comment by haszari** [comment]
> Changes proposed in this Pull Request
Added showRemainingDays prop to due date for conditional rendering.

> Test it with https://github.com/Automattic/woocommerce-payments/pull/8275

Curious why this is split into two PRs? Recommend including all the changes necessary to fix the problem in a single PR; if they are split then we can't effectively review.

@naman03malhotra can you combine these - or is there something I'm missing? 

> I created a follow up PR (https://github.com/Automattic/woocommerce-payments/pull/8275) based on this PR, as I wanted to make sure my approach is correct.

All good to raise a single PR and work through feedback on approach in context of the problem :)

**Comment by naman03malhotra** [comment]
>All good to raise a single PR and work through feedback on approach in context of the problem :)

It makes sense for this case, but in general, I prefer to keep the structural change PR (especially when it big) and the PR that solves the issue separate, as solutioning is based on the base PR and is subjected to change after review and discussion. But here the PR was small, so makes sense for ease of testing.

I created a single PR, ready for review 👍

**Comment by jessy-p** [comment]
Tested and works as expected. Code looks alright, approving.

image

**Review by jessy-p — APPROVED** [review]

**Comment by haszari** [comment]
> > All good to raise a single PR and work through feedback on approach in context of the problem :)

> It makes sense for this case, but in general, I prefer to keep the structural change PR (especially when it big) and the PR that solves the issue separate, as solutioning is based on the base PR and is subjected to change after review and discussion. But here the PR was small, so makes sense for ease of testing.

> I created a single PR, ready for review 👍

Thanks @naman03malhotra ! Should this PR be closed?

**Comment by naman03malhotra** [comment]
@haszari this PR needs review, I've closed the follow-up one https://github.com/Automattic/woocommerce-payments/pull/8275 😄

**Comment by haszari** [comment]
> this PR needs review, I've closed the follow-up one https://github.com/Automattic/woocommerce-payments/pull/8275 😄

Aha I see! I recommend updating the title of this PR so it's accurate – i.e. this PR is fixing a merchant issue now 🎉

**Pull request merged**
