### PR TITLE
Use card component from wordpress/components and fix misc related styling issues

### LINKED ISSUE #1327: Use the <Card> WordPress component
All uses of the `<Card>` _WooCommerce_ component should be switched to the `<Card>` _WordPress_ component [[src](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/card), [story](https://wordpress.github.io/gutenberg/?path=/story/components-card--default)]. (The former was deprecated in https://github.com/woocommerce/woocommerce-admin/pull/5911.) See https://github.com/woocommerce/woocommerce-admin/issues/4002.

Note that the structure of the components is different – see PRs referenced at bottom of https://github.com/woocommerce/woocommerce-admin/issues/4002 timeline, for examples of the migration in WC Admin (including in the tables we are using in WCPay).

### PR DESCRIPTION
**Pull request by LevinMedia**
Fixes #1327

#### Changes proposed in this Pull Request

This PR switches out use of the woocommerce card component for the card component found in the @wordpress/components package. It updates the transaction details, disputes details, and dispute evidence submission screens. For reference, the WordPress card does not have a drop shadow. It has a 1px boarder, and 2px rounded corners. 

#### Example Before and after

**Transaction details before:**

screencapture-localhost-wp-admin-admin-php-2021-03-05-15_52_56

**Transaction details after:**

screencapture-localhost-wp-admin-admin-php-2021-03-05-15_49_15

#### Testing instructions

1. Load this branch
2. View the deposit details screen - ensure the deposit details component is wrapped with the WordPress Card component
3. View the transaction details screen - Ensure all cards are using the WordPress Card component
4. View the deposit details and evidence submissions screens - Ensure all cards are using the WordPress Card component

**Follow up issues**

- Revisit the design of the deposit details component on mobile
- [Bump the @wordpress/components version number and base components version number](https://github.com/Automattic/woocommerce-payments/issues/717)

-------------------

- [ ] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

**Comment by jrodger** [comment]
I've made some tweaks so that the CI server is happy:

* Fixed JS linting (https://github.com/Automattic/woocommerce-payments/pull/1378/commits/64943d646d4af9dc92f42d98a7a34f862dd4e86b) - Some mixing of tabs and spaces, but mostly the linter wanting certain things wrapped onto new lines thanks to the extra level of indentation we've added.
* Removed now unused imports (https://github.com/Automattic/woocommerce-payments/pull/1378/commits/d84bf3b0b1775e59efa59699025666e31d7aaf4b)
* Restored a key property (https://github.com/Automattic/woocommerce-payments/pull/1378/commits/a1f02c352ff95643558ed36b023de25e4425e25c) - React needs these for collections of elements, it got deleted in the cross fire.
* Updated the markup snapshots for the unit tests (https://github.com/Automattic/woocommerce-payments/pull/1378/commits/ecb853f91f5f92ba196733ddd1d95ae1d31679c8) - I think these look sensible, but the updates could do with another pair of eyes to double check. One thing that seems a bit strange is the CSS classes having generated IDs. I'm assuming these are stable and won't randomly break tests.
* Fixed CSS linting (https://github.com/Automattic/woocommerce-payments/pull/1378/commits/94c67e02a7dca26bf333acc15d5e550eac9eb20e) - The linter requires that 0 sizes don't have units.

Everything tests out well, I can see the new card on all the pages and the styling looks good 👍 

I wouldn't mind someone else having a quick look over the JavaScript to make sure I haven't missed anything. Perhaps @DanReyLop or @vbelolapotkov?

One specific question, I just wanted to double check my understanding of how we're using `@wordpress/components` at the moment, I know this has been discussed a lot, but I'm a bit out of the loop. The config for `WordPressExternalDependenciesPlugin` returns `null` for this package, but I've forgotten what that means exactly. Does that mean we'll be using the `8.5.0` version from our dev dependencies? Basically, I just want to make sure that this card component is available on every configuration we support.

**Comment by vbelolapotkov** [comment]
> One specific question, I just wanted to double check my understanding of how we're using @wordpress/components at the moment, I know this has been discussed a lot, but I'm a bit out of the loop. The config for WordPressExternalDependenciesPlugin returns null for this package, but I've forgotten what that means exactly. Does that mean we'll be using the 8.5.0 version from our dev dependencies? Basically, I just want to make sure that this card component is available on every configuration we support.

I've skimmed through the code and codewise changes look good to me. Yes, this is correct assumption our assets include own version of `@wp/components` but I think should move away from it at some point and bumpt min WP version when needed.

For this specific PR, I'd test it on WP 5.3 to stay safe. But I don't expect any issues there.

**Comment by jrodger** [comment]
I get some unrelated issues in WP 5.3 that I'll investigate separately. A quick test in 5.4 looks good though.

**Review by jrodger — APPROVED** [review]

**Comment by jrodger** [comment]
LGTM, let's merge it @LevinMedia

**Pull request merged**
