### PR TITLE
Reporting: Overview - improve mobile view of Balances card

### LINKED ISSUE #8599: Overview > Balances card should show balances in stacked layout on mobile
The `Balance` widget in the overview page, currently shows `Total balance` and  `Available funds` side-by-side on desktop as well as mobile view. 

 On mobile screen, we would want this one below the other. 

### To Reproduce

1. Browse to `Payments` section in admin
2. Check how the `Balance` widget currently appears

### Additional context

The responsive behavior improvement for the Balances tiles was recommended by design - @rogermattic , to make it consistent with the mobile view of the payment activity widget tiles. 

p1712249591796559/1712130711.969139-slack-C06BBFTF6EM

Props - @rogermattic 
### Design mockups

Mobile views

### PR DESCRIPTION
**Pull request by nagpai**
Fixes #8599 

#### Changes proposed in this Pull Request

* Make the items within the Balance card stack vertically on mobile view, as per recommended design
* Add card title - `Balances` 
* Use Card component instead of Flex

#### Screen recording
https://github.com/user-attachments/assets/2df4c486-0afd-4237-af13-b6cfdfd06671

#### Screen recording with instant deposit notice

https://github.com/user-attachments/assets/116af7a4-4b91-44c1-a4a8-6b3c58d39f4c

#### Screen recording with instant deposit button without notice

https://github.com/user-attachments/assets/3cd69845-ce0b-4ce1-b8fe-bec07551e503

#### Testing instructions

* Checkout this branch
* Browse to `Payments > Overview` and notice that the Balances card now appears with a title.
* Resize the browser window. When it falls below 660px, the card items should stack vertically, similar to the recording
* Use an account with an instant balance, or overwrite the index.tsx of the account balances component with [this code](https://gist.github.com/nagpai/7df1b5c3963b1539cff86f6044e8409c) ( take care not to push :D ) . 
* You should now see the instant deposit box and button. Check how it looks when you resize
* Remove the notice and have only the button by tweaking the code, or canceling the notice ( if you are using a test site with instant payout ) . Resize the window and check how it looks. 
* Compare all results with what is shown in the screen recordings, and the figma mockup.   

#### Notes
* Figma design - o5NOD3EJaKSoILbvvZiAwU-fi

Mobile views

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `10040` or branch name `fix/8599-balances-card-layout` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/8599-balances-card-layout) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 27c312480ccbff8855ec3771114f54a5bc2018ed
- Build time: 2024-12-30 09:59:04 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by shendy-a8c — APPROVED** [review]
Looks good but I see from the design that it says `Balance` instead of `Balances`.

Mobile views

Is this expected?

**Comment by nagpai** [comment]
Thanks for catching that @shendy-a8c - It should indeed be `Balance`. I have fixed it - [27c3124](https://github.com/Automattic/woocommerce-payments/pull/10040/commits/27c312480ccbff8855ec3771114f54a5bc2018ed) .

**Comment by rogermattic** [comment]
This looks great @nagpai ! Thanks for working on it:)

**Pull request merged**
