### PR TITLE
Fix Payment Method Titles After Checkout

### LINKED ISSUE #2434: Remove suffix from UPE Payment methods on Order Complete page
After a chat with @LevinMedia, we decided that we should drop the `WooCommerce Payments` suffix from the Order Complete page after checkout.

Remove this
_Suffix to be removed_

That's it!

### PR DESCRIPTION
**Pull request by FangedParakeet**
Fixes #2434 

#### Changes proposed in this Pull Request

# Rename UPE Payment Methods

> After a chat with @LevinMedia, we decided that we should drop the WooCommerce Payments suffix from the Order Complete page after checkout.

Before: 
Wrong
_Incorrectly titled payment method_

After:
Right
_Correctly titled payment method_

#### Testing instructions

1. Ensure you have pulled the changes in this PR and the latest version of the Payments Server. Also, please enable the UPE gateway using the WCPay Dev Plugin or simply set _wcpay_feature_upe to a value of 1 in your wp_options table.
2. Add a product to your cart and complete a checkout with either a credit card, Giropay, or Sofort (or preferably all three) using the UPE.
3. Confirm that the payment method is titled correctly on the Order Complete page.
4. That's all!

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

**Review by frosso — APPROVED** [review]
lol I remember when we added it, I was just a minnow back then 😅 

Tested locally, LGTM

I wonder if we should be doing the same for `Apple Pay`/`Google Pay` etc., which are still appending `(WooCommerce Payments)` 🤔 
But these changes in this PR look good so far 👍

**Comment by FangedParakeet** [comment]
> I wonder if we should be doing the same for Apple Pay/Google Pay etc., which are still appending (WooCommerce Payments) 🤔

Good point, @frosso ! Not sure why this didn't cross my mind. Turns out it was because we'd both be wrong. If I may quote @LevinMedia in answer to whether we should also drop the `(WooCommerce Payments)` tag from Apple/Google Pay.

> Nope! Difference is Apple Pay and google pay are consumer brands and woocommerce payments is not.
>Once we start rocking WooPay transactions we’d want to display that

**Comment by frosso** [comment]
Sounds great, thanks for checking on that!

**Comment by billrobbins** [comment]
We've had a few requests from merchants for the ability to remove this text.  Would it be possible to add a filter similar to what is in Stripe to allow them to alter the titles?

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/44f8f59a98b0fe8502008c28be8ab087e866723d/includes/payment-methods/class-wc-stripe-payment-request.php#L83

**Comment by FangedParakeet** [comment]
@billrobbins adding a filter for the suffix sounds like a dandy enough idea to me. @LevinMedia, can you suggest any reason why we might want to refuse the option to remove the "(WooCommerce Payments)" suffix for Google/Apply Pay? If there is none, I can probably add this tweak myself pretty quickly.

**Comment by LevinMedia** [comment]
@FangedParakeet I don't see an issue with that 👍

**Comment by FangedParakeet** [comment]
I just created #3519, but would appreciate someone with more experience with testing these payment request buttons than myself having a look. Cheers!

**Pull request merged**
