### PR TITLE
Transaction Details → fix typo in staged dispute challenge notice

### PR DESCRIPTION
**Pull request by Jinksi**
> **Note**
> This PR is behind feature flag `_wcpay_feature_dispute_on_transaction_page`

#### Changes proposed in this Pull Request

This PR corrects the text within the Transaction Details → staged dispute challenge notice, removing the strikethrough text below: 

_You initiated ~a dispute~ a challenge to this dispute. Click 'Continue with challenge' to proceed with your draft~ed~ response._

**Before**
image

**After**
image

#### Testing instructions

1. Create a disputed transaction with a staged evidence submission:
	* Enable feature flag by running `update_option( '_wcpay_feature_dispute_on_transaction_page', '1' );` in [WP Console](https://wordpress.org/plugins/wp-console/) or by modifying your database table `wp_options` directly.
	* Create a disputed transaction using the card `4000000000000259` at checkout.
	* Find the dispute in Payments → Disputes and click it to view the dispute details screen.
	* Click **Challenge**.
	* Make a small change to this form and click "Save for Later" to stage the dispute evidence submission.
* Navigate to the Transaction Details screen associated with this dispute.
* You should see the staged dispute evidence notice with the corrected text.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply) **N/A**

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7217` or branch name `fix/dispute-staged-evidence-notice-typo` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/dispute-staged-evidence-notice-typo) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 8023c2659b9d66e53f10c705a71277f5997aaa23
- Build time: 2023-09-15 09:20:35 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by brucealdridge — APPROVED** [review]
😱 How did I miss this the first time around?

Reviewed code, double-checked text, and tested. ✅

**Comment by Jinksi** [comment]
@brucealdridge Same! The typo remains in the design, but I carried it over. I even wrote a test for it and included the typo in the test 😆

**Comment by Jinksi** [comment]
Looks like something is going wrong with the GH check `PHP testing (7.3)`, preventing the auto merge from completing.

**Comment by Jinksi** [comment]
Ah, I see the php 7.3 check is failing due to #7134 and is being fixed with #7213.

I’ll merge with only the php 7.3 check failing/skipped.

**Pull request merged**
