### PR TITLE
Update Subscriptions with WooPayments eligibility as we move to deprecate this functionality

### LINKED ISSUE #6510: Deprecate subscriptions functionality bundled in WC Payments
### Description

As part of our project to sunset the subscriptions functionality bundled in WC Payments we will be deprecating that feature.

This issue will track the changes necessary to handle that deprecation. 

### Acceptance criteria

- [x] Do not load subscription functionality on new sites created after the release of the version of WC Pay containing these changes.
- [x] No longer load subscription functionality on existing WC Pay sites when:
    1. Store has no active Stripe Billing Subscriptions; and
    2. Store has no published subscription products in their catalog.

### Additional context

peNR48-2u-p2 project.

### PR DESCRIPTION
**Pull request by mattallan**
Fixes #6510 

#### Changes proposed in this Pull Request

As part of the [Subscriptions Primary Offering](https://github.com/Automattic/woocommerce-payments/milestone/34) project, we need to deprecate the existing WCPay Subscriptions feature so that merchants can opt into the new subscriptions setting.

In this PR we are updating the eligibility of the WCPay Subscriptions so that we:
 - Do not load the **Advanced > WCPay Subscription** setting on new sites created after the release of the version of WC Pay containing these changes.
 - No longer load subscription functionality on existing sites that have no active Stripe Billing Subscriptions or published subscription products.

To meet these new requirements I've changed `is_wcpay_subscriptions_eligible()` to only return true when:

1. Store located in the US
2. Doesn't have the WC Subscriptions extension active
3. Has either one of the following:
   1. the store has existing WCPay Subscriptions or,
   2. has published subscription products

#### Testing instructions

Testing this PR requires toggling the following:
 - Deactivate/activate WooCommerce Subscriptions
 - Update the store's base country to US and non-US
 - Has no published subscription products
 - Has no WCPay subscriptions (with `_wcpay_subscription_id` metadata)

With that information, here are the testing instructions to toggle through most of the new eligibility cases:

1. Setup the state of your store so that you have 1 subscription product, 1 WCPay Subscription, WC Subscriptions deactivated, and the store is based in the US
2. Confirm the **Enable Subscriptions with WooPayments** setting is found in **Payments > Settings > Advanced**
3. Activate Subscriptions, confirm the setting is gone
4. Deactivate Subscriptions to bring it back
5. Change the stores base country to a non-US country, confirm the WCPay Subscriptions setting is gone
6. Change the country back to the US
7. Set your subscriptions product to private and modify the `_wcpay_subscription_id` to something like `_wcpay_subscription_id_test`
8. Confirm the setting is no longer shown
9. Set the subscription product back to published, confirm the setting is back.
10. Put the product back to private and change the metadata on the subscription to bring back the `_wcpay_subscription_id` meta.
11. Confirm the WCPay subscription setting is loading.

With these instructions I have tested the following cases:

- **Setting doesn't show if any of the following conditions are met:**
   - [x] Has WC Subscriptions active
   - [x] Non-US based store
   - [x] Doesn't have existing subscriptions products
   - [x] Doesn't have any subscriptions with `__wcpay_subscriptions_id` meta (including pending, canceled, on-hold etc.)
- **Settings only shows when:**
   - [x] No WC Subscriptions active, country set to US, no subscriptions but has existing products
   - [x] No WC Subscriptions active, country set to US, has existing subscriptions 

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7117` or branch name `issue/6510-deprecate-wcpay-subscriptions` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=issue/6510-deprecate-wcpay-subscriptions) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: cd4050307d27c8045fdf1e6b523d172dfa25ae01
- Build time: 2023-09-11 23:22:21 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by mattallan — COMMENTED** [review]
I've tested the following:
- [x] Upgrading a site that is eligible for wcpay subscriptions
- [x] Upgrading a site that isn't eligible for wcpay subscriptions has the feature disabled
- [x] Test the setting isn't shown on stores that aren't eligible

**Comment by james-allan** [comment]
@mattallan there's a conflict on this PR due to the changes to `wcpay-subscriptions-toggle.js` in https://github.com/Automattic/woocommerce-payments/pull/7105.

**Review by james-allan — APPROVED** [review]
Works for me and changes look good. 

- [x] Not eligible - No subscriptions or products
- [x] Eligible 
   - [x] _Subscription_
   - [x] _Product_
- [x] Upgrade flow. _Enabled → updated → not eligible → disabled_ 
- [x] Upgrade flow. _Enabled → updated → eligible → enabled_
- [x] Setting hidden when Woo Subscriptions is active.

**Pull request merged**
