### PR TITLE
Update phpcompatibility to develop version to get sniffs for PHP 8

### PR DESCRIPTION
**Pull request by alopezari**
Closes 370-gh-Automattic/woocommerce-payments-meta

#### Changes proposed in this Pull Request

We use a PHPCS extension - [PHPCompatibility](https://github.com/PHPCompatibility/PHPCompatibility) - to check the compatibility of our plugin with multiple PHP versions.

We were using the latest stable version 9.3.5. However, this version was released in 2019 and it doesn't cover rules for PHP 8.

This PR adds the following changes:
* Switch to the `dev-develop` version of PHPCompatibility to include sniffs for all PHP 8 versions, including new sniffs for PHP 8.4 - yet to be released.
* This `dev-develop` version was tagged as fake `9.3.5` to keep compatibility with other dependencies.
* PHP versions to be checked in the standard `phpcs.xml.dist` config file are 7.3-7.4. This is because our code is fully compatible with these versions but there are some warnings and errors for PHP 8, which would break our pipelines since `phpcs.xml.dist` rules are required for PRs to be merged.
* There is another [PHP Compatibility workflow](https://github.com/Automattic/woocommerce-payments/blob/develop/.github/workflows/php-compatibility.yml) that was updated to cover from PHP 8.0 to 8.4 - latest. This one is not required, so if it fails, it won't block pipelines.

This way, we will be able to spot potential incompatibilities with PHP 8.4 before this PHP version is out.

> [!NOTE]  
> A follow up task will be created to fix the PHP 8 warnings and errors.

#### Testing instructions

* Apply the changes from this branch.
* Run `npm run lint:php -- --no-cache` and check that no errors appear.
* Run `./vendor/bin/phpcs --standard=phpcs-compat.xml.dist $(git ls-files | grep .php$)` and check that multiple errors and warnings appear, most of all of them related to PHP 8 incompatibilities (you can see in the log the PHP version each error/warning is related to).
* Check that all checks pass on this PR except `PR Compatibility`, that should fail due to PHP 8 errors and warnings.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9697` or branch name `update/phpcompatibility-latest` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=update/phpcompatibility-latest) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 953bc3cd6b9b32468703f7cebb81fe3b0868afa2
- Build time: 2024-11-26 11:13:46 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by achyuthajoy — CHANGES_REQUESTED** [review]
@alopezari The current changes in this PR looks good.

However, looking at the PHP compatibility workflow, we're using a different config file for compatibility tests - https://github.com/Automattic/woocommerce-payments/blob/develop/phpcs-compat.xml.dist

You'll need to update the above config to test PHP versions 7.3 to 8.4.

Also, it would be great to have an npm script for running compatibility tests locally. Can you add that as well?

**Review by achyuthajoy — CHANGES_REQUESTED** [review]
@alopezari Looking at the compatibility test result of this [PR](https://github.com/Automattic/woocommerce-payments/actions/runs/12009399336/job/33474037110?pr=9697), I noticed this error:

```
The function str_starts_with() is not present in PHP version 7.4 or earlier
```

I don't think it's an actual issue because our code works as expected on PHP 7.3 and above. If this was an actual issue, we would've received fatal errors. May be we're using some polyfills. Can you look into this as well?

**Comment by alopezari** [comment]
Thanks for the review @achyuthajoy!

> However, looking at the PHP compatibility workflow, we're using a different config file for compatibility tests - https://github.com/Automattic/woocommerce-payments/blob/develop/phpcs-compat.xml.dist
You'll need to update the above config to test PHP versions 7.3 to 8.4.

Yes! I'm aware of that. I left it as it is because it is `7.3-` covers between 7.3 until the latest PHP version we have sniffs for. Right now it's 8.4, but once PHPCompatibility is updated with sniffs for PHP 8.5, the current configuration will also include these ones. I think this is the behaviour we want to achieve, that's why I didn't update it.

> Also, it would be great to have an npm script for running compatibility tests locally. Can you add that as well?

Sure thing!

> I don't think it's an actual issue because our code works as expected on PHP 7.3 and above. If this was an actual issue, we would've received fatal errors. May be we're using some polyfills. Can you look into this as well?

Interesting, will check it!

**Comment by achyuthajoy** [comment]
> Yes! I'm aware of that. I left it as it is because it is 7.3- covers between 7.3 until the latest PHP version we have sniffs for.

@alopezari If I understand correctly, `7.3-` means it will test all PHP versions upto PHP 7.3. If you want to test higher versions, might want to use `7.3+`, which will test to the latest PHP version available.

**Comment by alopezari** [comment]
> Also, it would be great to have an npm script for running compatibility tests locally. Can you add that as well?

Added in [e6f4ccb](https://github.com/Automattic/woocommerce-payments/pull/9697/commits/e6f4ccbaf988602176254825b61cf9cf16923448)!

> The function str_starts_with() is not present in PHP version 7.4 or earlier

Okay, this error was found only on jetpack code. Our current `php-compat.xml.dist` excludes the `vendor` path to run checks only on our code and not on dependencies. But then in the `PHP Compatibility` workflow we run the script `phpcs-compat.sh` that installs prod dependencies in a `vendor-dir` path. The errors related to PHP 7.4 was found only on code from this `vendor-dir` path.

It makes sense to me to focus our tests and checks on the code we build, not dependencies, so - in addition to `vendor` - I've added another exclusion for the `vendor-dir` folder in `phpcs-compat.xml.dist`. This was also done in [e6f4ccb](https://github.com/Automattic/woocommerce-payments/pull/9697/commits/e6f4ccbaf988602176254825b61cf9cf16923448).

**Review by achyuthajoy — APPROVED** [review]
LGTM 🚢

**Pull request merged**
