### PR TITLE
Make test instructions copy icon use the same color as the text next to it

### LINKED ISSUE #9773: Test instructions copy icon color should match the text color to ensure it matches the theme colors.
### Description
When the test instructions include a copyable test card number, there's a copy icon beside the number. Currently, this is an SVG as the background image of an HTML element and is a static color (black). When the user clicks to copy the number and that's successful, the icon changes to a green checkmark. Ideally, both icons will match the text color based on the WooPayments computed styles for the theme so they don't blend in with the background.

Image
Image

### Acceptance criteria
* The "copy" icon matches the text color and is determined by the styles computed by WooPayments.
* The "check" icon matches the text color and is determined by the styles computed by WooPayments.

### Dev notes
I realize we can't directly affect the fill color of the SVG since it's being output as a `background-image`, but I think we can effectively achieve the same thing using masks. We'd need to ensure browser compatibility with all of the properties, but it could look something like this:

```
.icon-selector {
    mask-image: url('path/to/svg/copy.svg');
    mask-size: contain;
    mask-repeat: no-repeat;
    mask-position: center;
    background-color: var(--text-color-from-computed-styles);
}
```

### Additional Context
This was mentioned in #9488 so I split it out into its own issue.

### PR DESCRIPTION
**Pull request by gpressutto5**
Fixes #9773

#### Changes proposed in this Pull Request

This PR updates the color of the icon in the test instructions to be the same color as the text.

| Before | After |
|--------|--------|
| Screenshot 2024-12-02 at 18 37 34 | Screenshot 2024-12-02 at 18 34 49 |
| Screenshot 2024-12-02 at 18 36 16 | Screenshot 2024-12-02 at 18 35 35 | 

#### Testing instructions

Use the shortcode checkout and blocks checkout and ensure the copy icon and the success checkmark have the same color as the text next to it.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9868` or branch name `test-instructions-item-color` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=test-instructions-item-color) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: b4476b3b29cb45d418e041c7da55f389ea9e72ab
- Build time: 2024-12-02 21:36:14 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by gpressutto5** [comment]
@pierorocca This is ready in case you want to test it

**Review by mdmoore — APPROVED** [review]
Works great! 🚢

**Comment by pierorocca** [comment]
Thanks! One less color to worry about trying to match to the theme. Thanks for this quick fix.

**Pull request merged**
