### PR TITLE
Unify WooPay and Google/Apple pay settings

### PR DESCRIPTION
**Pull request by leonardola**
#### Changes proposed in this Pull Request
This PR merges the settings of WooPay and Apple/Google Pay to prevent merchants from configuring each button differently

Known Bug. If you open the settings for both buttons change one, save and then change the other and save it will revert the changes of the first one. This behavior was not introduced by this PR and will be fixed on other PR later.

#### Testing instructions
**WooPay**
- Go to wp-admin > Payments > Settings > Express Checkouts > WooPay > Customize
- Make sure `Enable WooPay on selected pages` is in the same section as the enable checkbox
- Make sure the notice `These settings will also apply to the Apple Pay/Google Pay buttons on your store.` shows up and looks like the one [in figma](C1r0Vzxh1mhbDJJnbjHp5q-fi-1299%3A63997&t=dyRuu0vjisLBdxd1-0)
- Enable all pages
- Make sure the button shows on those pages
- Disable all pages
- Make sure the button does not show on those pages anymore
- Change the other settings and make sure they reflect in the preview and in the pages

**Apple/Google Pay**
- Go to wp-admin > Payments > Settings > Express Checkouts > WooPay > Customize 
- Make sure `Enable Apple Pay and Google Pay on selected pages` is in the same section as the enable checkbox
- Make sure the notice `These settings will also apply to the WooPay buttons on your store.` shows up and looks like the one [in figma](C1r0Vzxh1mhbDJJnbjHp5q-fi-1299%3A63997&t=dyRuu0vjisLBdxd1-0)
- Enable all pages
- Make sure the button shows on those pages
- Disable all pages
- Make sure the button does not show on those pages anymore
- Change the other settings and make sure they reflect in the preview and in the pages

**Shared Settings**
- Change the settings in one express checkout and make sure they reflect on the other
- Change the `Enable on selected pages` and make sure they don't interfere with the other button
-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Review by alefesouza — APPROVED** [review]
Everything works as expected, thank you!

**Comment by leonardola** [comment]
@bborman22 I would like some eyes from Heisenberg on this PR.

**Review by bborman22 — APPROVED** [review]
This all worked really well for me and was very intuitive! It also is nice to get some of that additional code removed in this PR as well.

LGTM!

**Comment by leonardola** [comment]
@bborman22 there will be more PRs removing the duplicated code. Thanks for reviewing it.

**Comment by bborman22** [comment]
Something I noticed today that I must have missed in reviewing, or didn't have it configured as I thought, is that the `Enable WooPay on selected pages` setting is not being respected for blocks cart and checkout. For example, I am using blocks cart and checkout as my pages, I have WooPay set to only be on the Cart page and not on checkout. However, when I view checkout the WooPay button is still rendered.

I checked with an older branch and it respected the setting for blocks. I also checked through the `WC_Payments_Platform_Checkout_Button_Handler::should_show_platform_checkout_button` function and it is correctly finding the setting and [not including the scripts](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payments-platform-checkout-button-handler.php#L115) as expected. Nothing in this PR seems to indicate an issue here, so might be unrelated, but wanted to mention it as I missed it during the review.

@leonardola I'm guessing we'll just want a separate issue for this, but wanted to raise it on this PR just in case it rings a bell for a quick fix? Sorry again for missing this the first time I reviewed.

**Pull request merged**
