### PR TITLE
Add Reporting Authorization API endpoint

### LINKED ISSUE #6342: Create API endpoint for retrieving filtered list of transactions
### Description
Review the existing API endpoint for retrieving transactions to determine if it meets the schema requirements for data reporting while maintaining backward compatibility. If the existing endpoint is sufficient, modify it to include the ability to retrieve a filtered list of transactions based on the provided parameters. If the existing endpoint does not meet the requirements, create a new API endpoint to fulfill the transaction retrieval needs.

The following endpoint need to be checked/added:

[Captures](https://href.li/?https://github.com/Automattic/woocommerce-payments/commit/a3fabba4aff238cb4a0752fb5dd60432db3727dd#diff-f5ce5009262d1356eb28b2a0e36b3473d8bb278e2b61534579520ca7c4918ee3) – includes/core/server/request/class-list-transactions.md

## Filtering Parameters
- `date_before` (string, optional): Filters transactions that took place before this specified date. The date format should be in 'date-time'.
- `date_after` (string, optional): Filters transactions that happened after this particular date. The date format should be in 'date-time'.
- `date_between` (array): Allows you to filter transactions that occurred between specific dates.
- `order_id` (integer, optional): Filters transactions by their associated order ID.
- `deposit_id` (string, optional): Enables transaction filtering based on the linked deposit ID.
- `email` (string, optional): Filters transactions according to the customer's email.
- `payment_method_id` (string, optional): This parameter is for filtering transactions based on the payment method used.
- `type` (string, optional): Filters transactions where the type matches a specified value.
- `transaction_id` (string, optional): Filters transactions based on their unique transaction ID.
- `source_id` (string, optional): Filters transactions using their unique source ID.
- `match` (string, optional): A match filter for transactions.
- `search` (array, optional): A search parameter for transactions.
- `user_timezone` (string, optional): Incorporates the timezone into date filtering.
- `orderby` (string, optional): Sorts transactions based on the specified field. By default, it's sorted by 'date'.
- `order` (string, optional): Orders transactions based on the given field. By default, it's in descending ('desc') order. It can be either 'asc' (ascending) or 'desc' (descending).
- `page` (integer, optional): Indicates the page number. By default, it's set to 1, with a minimum limit of 1.
- `per_page` (integer, optional): Specifies the page size. By default, it's set to 25, with a minimum limit of 1 and a maximum limit of 100.

## Request Schema
The request schema for the API endpoint should follow the specifications outlined in the following GitHub issue: [#6336](https://github.com/Automattic/woocommerce-payments/issues/6336). Please refer to the schema provided in the issue and incorporate it into the API endpoint implementation.

## Response
The API endpoint should return a list of transactions that match the specified filters. Each transaction should include relevant information such as transaction ID, timestamp, type, order ID, deposit ID, customer email, payment method details, and transaction details.

## Note
Please ensure that the API endpoint implementation adheres to RESTful design principles and follows proper error handling practices. If the existing endpoint is sufficient, modify it to accommodate the new requirements. If it is not sufficient, create a new API endpoint to fulfill the transaction retrieval needs.

### LINKED ISSUE #6847: Create API endpoint for retrieving a filtered list of authorizations
### Description
Review the existing API endpoint for retrieving transactions to determine if it meets the schema requirements for data reporting while maintaining backward compatibility. If the existing endpoint is sufficient, modify it to include the ability to retrieve a filtered list of transactions based on the provided parameters. If the existing endpoint does not meet the requirements, create a new API endpoint to fulfill the transaction retrieval needs.

The following endpoint needs to be checked/added:

[Authorizations](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/core/server/request/class-list-authorizations.md) – includes/core/server/request/class-list-authorizations.md

## Filtering Parameters

- Date Before (`string` in `date-time` format, not required): This filters authorizations that happened before a certain date.
- Date After (`string` in `date-time` format, not required): This filters authorizations that happened after a certain date.
- Date Between (`array`): This filters authorizations that happened between two dates.
- Order ID (`integer`, not required): This filters authorizations associated with a specific order ID.
- Email (`string`, not required): This filters authorizations associated with a specific customer email.
- Payment Method ID (`string`, not required): This filters authorizations that used a specific payment method.
- Type (`string`, not required): This filters authorizations of a specific type. Acceptable values include 'failed', 'cancelled', 'expired', 'uncaptured'.
- Transaction ID (`string`, not required): This filters authorizations based on a unique transaction ID.
- Source ID (`string`, not required): This filters authorizations based on a unique source ID.
- Match (`string`, not required): This is used to match a filter for the authorizations.
- Search (`array`, not required): This parameter is used to search within the authorizations.
- User Timezone (`string`, not required): This includes the timezone in date filtering.
- Order By (`string`, not required, defaults to 'created'): This sorts the authorizations based on a specific field.
- Order (`string`, not required, defaults to 'desc'): This orders the authorizations based on a specific field. Acceptable values include 'asc' and 'desc'.
- Page (`integer`, not required, defaults to 1, minimum 1): This specifies the page number.
- Per Page (`integer`, not required, defaults to 25, minimum 1, maximum 100): This specifies the number of items per page.

## Request Schema
The request schema for the API endpoint should follow the specifications outlined in the following GitHub issue: [#6846](https://github.com/Automattic/woocommerce-payments/issues/6846). Please refer to the schema provided in the issue and incorporate it into the API endpoint implementation.

## Response
The API endpoint should return a list of transactions that match the specified filters. Each transaction should include relevant information such as transaction ID, timestamp, type, order ID, deposit ID, customer email, payment method details, and transaction details.

## Note
Please ensure that the API endpoint implementation adheres to RESTful design principles and follows proper error handling practices. If the existing endpoint is sufficient, modify it to accommodate the new requirements. If it is not sufficient, create a new API endpoint to fulfill the transaction retrieval needs.

### PR DESCRIPTION
**Pull request by jessy-p**
Fixes #6847

#### Changes proposed in this Pull Request
- Added GET `reports/authorizations` and GET `reports/authorizations/<authorization_id>` endpoint.
- Other improvements
    - moved `WC_REST_Payments_Reports_Transactions_Controller_Test` to the correct folder and corrected a typo in the file
    - refactored a common function to a utils class `Request_Utils`
- Fields supported by Authorization based on pcreKM-1Hp-p2 

| Field                | PRD Ref: pcreKM-1Hp-p2     | Included/Notes |
|----------------------|-----------------------|----------------|
| date                 | Timestamp (datetime)  | ✔️              |
| authorization_id       | Transaction id        | ✔️              |
| payment_id           | Slack Ref  : p1689933340655009/1689932880.163849-slack-C04KP8LPZHT            | ✔️              |
| channel              | Channel               | ✔️              |
| payment_method=>type  | Payment-method – Type | ✔️              |
|                      | Payment-method – Id   | Will be added in separate PR    |
|                      | Transaction type      | Not supported as only type is successful authorizations             |
| currency | Transaction Currency  | ✔️              |
| amount               | Amount                | ✔️              |
| fees                 | Fees                  | ✔️              |
| net_amount           | Net Amount            | ✔️              |
| amount_captured     | N/A               | ✔️              |
| risk_level           | Risk level            | ✔️              |
| order_id             | Order_id              | ✔️              |
| customer=>email       | Email                 | ✔️              |
| customer=>country     | Country               | ✔️              |

The following fields are NOT supported as the authorization does not relate to deposit until captured
| Field                | PRD Ref: pcreKM-1Hp-p2     | Included/Notes |
|----------------------|-----------------------|----------------|
| exchange_rate        | Exchange_rate         | Not supported              |
| deposit_currency     | Deposit_currency      | Not supported              |
| deposit_date         | Deposit_date          | Not supported              |
| deposit_id           | Deposit_id            | Not supported              |
| deposit_status       | Deposit_status        | Not supported              |

- Sample Authorization from response
```
{
  'authorization_id' : 'ch_123',
  'date'             : '2023-08-26 00:51:42',
  'payment_id'       : 'pi_321',
  'channel'          : 'online',
  'payment_method'   : {
    'type' : 'visa',
  },
  'currency'         : 'eur',
  'amount'           : 7300,
  'amount_captured'  : 0,
  'fees'             : 312,
  'customer'         : {
    'name'    : 'Test Customer',
    'email'   : 'test@woocommerce.com',
    'country' : 'US',
  },
  'net_amount'       : 6988,
  'order_id'         : 123,
  'risk_level'       : 0,
}
```
- Filters supported for GET `reports/authorizations`

| Filter field        | PRD Ref                            | Example |
|---------------------|------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| date_before         | Timestamp (datetime) - before      | `https://<host>/wp-json/wc/v3/payments/reports/authorizations?page=1&per_page=3&sort=created&direction=desc&date_before=2023-07-20 23:59:59&user_timezone=+05:30`|
| date_after          | Timestamp (datetime) - after       | `https://<host>/wp-json/wc/v3/payments/reports/transactions?page=1&per_page=3&sort=date&direction=desc&date_after=2023-07-19 00:00:00&user_timezone=+05:30`|
| date_between        | Timestamp (datetime) - between/ on | Not supported - Will be added in seperate PR |
| type                | Transaction type                   | Not supported - The only type is successful Authorizations|
| order_id            | Order_id                           | `https://<host>/wp-json/wc/v3/payments/reports/transactions?page=1&per_page=3&sort=date&direction=desc&order_id=204&user_timezone=+05:30`|
| customer_email      | Email                              | `https://<host>/wp-json/wc/v3/payments/reports/transactions?page=1&per_page=3&sort=date&direction=desc&customer_email=test@woocommerce.com&user_timezone=+05:30`|
| payment_method_type | Payment-method - Type              | `https://<host>/wp-json/wc/v3/payments/reports/transactions?page=1&per_page=3&sort=date&direction=desc&payment_method_type=visa&user_timezone=+05:30`|

- Other Fields Supported for GET `reports/transactions`

| Field         | Values              | Notes                                                        |
|---------------|---------------------|--------------------------------------------------------------|
| match         | any/all Default:all | Whether the filtering should be on ALL/ANY filter conditions |
| user_timezone |                     | User timezone, used for date filtering                       |
| page          |                     | Page number                                                  |
| per_page      | Default:25          | Number of records on a page                                  |
| sort          | Default:date        | Field on which the results will be sorted                    |
| direction     | Default:desc        | Direction of sort                                            |

#### Testing instructions
- Test with Server PR https://github.com/Automattic/woocommerce-payments-server/pull/3827 for the `customer_email`, `payment_method_type` and `order_id` and date filters to work.
- Create REST API Keys as described [here](https://woocommerce.github.io/woocommerce-rest-api-docs/#rest-api-keys)
- Sample curl URL for GET `reports/authorizations`
```
curl 'https://<host>/wp-json/wc/v3/payments/reports/authorizations?page=1&per_page=10&sort=date&direction=desc&user_timezone=+05:30' -u <ck_>:<cs_> -H "Content-Type: application/json"
```
- Test with the different combinations of filters and fields described in the table above.
- Sample curl URL for GET `reports/authorizations/<id>`
```
curl 'https://<host>/wp-json/wc/v3/payments/reports/authorizations/<id>' -u <ck_>:<cs_> -H "Content-Type: application/json"
```

**NOTES**:
- Split out from #6652 

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [x] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [x] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7066` or branch name `add/6342-reports-authorisations-api` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=add/6342-reports-authorisations-api) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 66f1159bf31da1773fab32e4bb6e8c8d633dd491
- Build time: 2023-10-10 15:00:20 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by zmaglica** [comment]
I believe the solution presented in this PR may not yield accurate results. The endpoint described in the PR might return charges, not just authorizations. If a date older than 7 days from the current time is passed, it's possible to retrieve charges that were never authorizations to begin with. In the original PR, additional checks were introduced to tackle this issue. However, the current implementation still lacks a method to retrieve expired authorizations. If the intent is not to return expired authorizations, then this approach is fine.

**Comment by jessy-p** [comment]
>However, the current implementation still lacks a method to retrieve expired authorizations.

Yes, if we play around with the date filter it is allowing to retrieve the older (probably expired) authorizations as per my testing. @souravdebnath1986 Do we need to retrieve older authorizations? After today's discussions, I was thinking it may not be a great idea to allow merchant to do that as it may lead to unintended consequences like additional charges if they try to capture those? My plan was to prevent it from retrieving that as mentioned in paJDYF-8Lh-p2#comment-20509 

>If a date older than 7 days from the current time is passed, it's possible to retrieve charges that were never authorizations to begin with. 

As far as I could understand, the type of charges stored in the charges table is controlled by `maybe_store_event_authorization` function in `Payment_Intent_Event_Handler` on server which only stores the valid authorizations. Also, in this API, we are backed by the same logic that is being used to populate the Transactions -> Uncaptured tab, which I assume is not showing any extra charges as merchants are using that to capture authorizations. So as long as we prevent showing older authorizations as discussed above, it should be fine.

**Comment by zmaglica** [comment]
>So as long as we prevent showing older authorizations as discussed above, it should be fine

Yes, you are right. I noticed that we are only adding ones that are captured manually. When I was checking the database a while ago, I noticed some authorizations that looked like charges, so I will investigate that a bit deeper, but overall you are right.

There's an issue with the date filters, as they're interpreted differently on the server. In the existing configuration, date filters are adjusted to only show authorizations eligible for capture within the past 7 days. For instance, if you specify a `to_date` in the past, like 2022-01-01, the server defaults to the current time. If you set `from_date` to yesterday, the server recalibrates to one week from the current date time. Furthermore, if you omit these filters, the server automatically defaults `from_date` to one week ago and `to_date` to the present time. This could lead to incorrect or invalid results. @souravdebnath1986 if you think that this is the correct flow and that we should keep the date filtering as explained above, we can approve the PR.

**Comment by jessy-p** [comment]
> For instance, if you specify a `to_date` in the past, like 2022-01-01, the server defaults to the current time. If you set `from_date` to yesterday, the server recalibrates to one week from the current date time. Furthermore, if you omit these filters, the server automatically defaults `from_date` to one week ago and `to_date` to the present time.

It is possible to get auths from past dates, which I plan to fix in separate issue. Other than that, if you use the before_date and after_date filter with **dates within the last 7 days**, it should work per my testing. Can you please add a specific testing scenario for which it is failing so that I can test it and fix if required?

**Comment by souravdebnath1986** [comment]
> Yes, if we play around with the date filter it is allowing to retrieve the older (probably expired) authorizations as per my testing. @souravdebnath1986 Do we need to retrieve older authorizations? After today's discussions, I was thinking it may not be a great idea to allow merchant to do that as it may lead to unintended consequences like additional charges if they try to capture those? My plan was to prevent it from retrieving that as mentioned in paJDYF-8Lh-p2#comment-20509

The authorisations-api should allow retrieving older expired authorisations. This will help the merchant analyse historical authorisations which weren't captured specially while reconciling orders without an associated transaction or checking if the payment-method was saved for off-session charges to be initiated later. 
The merchant can't capture an expired authorisation as Stripe blocks it. I asked Stripe the question and a scenario of a late capture of an authorisation where the auth-window has expired is not possible as Stripe always reverses authorisations once the auth-window has expired which may/may-not release the "pending" hold from the cardholder's account - slack thread [here](https://a8c.slack.com/archives/C9976E5MJ/p1693428824453509?thread_ts=1691418954.501049&cid=C9976E5MJ)

**Comment by jessy-p** [comment]
@souravdebnath1986  @zmaglica

Since the last update is that the API should retrieve older authorizations, I tested what the API does under different conditions

In the absence of any date filter, it will retrieve all the authorizations from 7 days ago till the present time, which is all valid authorizations as shown on the Uncaptured Transactions screen.
`https://<host>/wp-json/wc/v3/payments/reports/authorizations?page=1&per_page=3&sort=created&direction=desc&user_timezone=+05:30`
This seems OK to me as the default behaviour should be to return valid authorizations, but it does cause the filter to behave bit odd.

In the presence of `date_after` filter, it will return everything in the DB from the given date till the present time, including expired authorizations.
`https://<host>/wp-json/wc/v3/payments/reports/authorizations?page=1&per_page=3&sort=created&direction=desc&date_before=<date_before>&user_timezone=<timezone>`

The `date_before` filter, seems to act in a weird way, where it returns everything in DB from the given date till 7 days ago, i.e only expired authorizations.  I guess we could remove this filter completely. 

I suggest not confusing this by referring to the `to_date` and `from_date` used on the server API, but instead we should align (where it makes sense) with the `date_before` and `date_after` as it is used in the Reporting Transactions API.

I don't want to be biased by how the filters work currently, so @souravdebnath1986  you can define how the filters should work and then I can refactor as required to implement that.

**Comment by souravdebnath1986** [comment]
> The date_before filter, seems to act in a weird way, where it returns everything in DB from the given date till 7 days ago, i.e only expired authorizations. I guess we could remove this filter completely.

How does this work for [Transaction Reporting API](https://github.com/Automattic/woocommerce-payments/pull/6973). Does it fetch all transaction before the date ? Also the date filters i.e. `date_before` ,`date_after` and `date_between` filters can't be used together, have we factored for this ? I also think we should have a limit field as optional that limits the # of records fetched to the number called out in the field. We should also make these changes in the Transaction Reporting API. cc: @jessy-p @zmaglica

**Comment by jessy-p** [comment]
Created issue #7445  for fixing date filters.
Regarding limit being optional, @souravdebnath1986,  it may not be advisable to remove limit completely. In any case the server also enforces a default page size in case the parameter is not passed.

**Review by zmaglica — APPROVED** [review]

**Pull request merged**
