### PR TITLE
Added support to Cartes Bancaires

### LINKED ISSUE #8062: Enable card brand choice
### Description

Currently it is not possible for a customer to choose which card brand they want to use when paying with a co-branded card. When using a co-branded card, a customer should have the option to select which brand they want to run the payment through. The feature should also allow a merchant to set a default brand to use if the customer doesn't make a choice.

For additional information, please see Stripe's [card brand choice documentation](https://stripe.com/docs/card-brand-choice). This documentation includes details for implementing card brand choice within payment elements. At the bottom of the doc, you will find two co-brand test cards for testing during development.

Notice the dropdown arrow next to the card brand icon in the card number field in the Stripe payment element:

Annotation on 2024-01-19 at 15-01-57

### Acceptance criteria

* Ability to choose: If a co-branded credit card is entered into the payment element, a dropdown arrow should be active next to the card brand icon to allow for a shopper to select which card brand they prefer the payment to be processed through.

### Designs

See the above image taken from the Stripe documentation as some initial inspiration. 

### Testing instructions

After adding this feature the following test should pass.

1. Go to your test store, add an item to your card, go to the checkout page.
2. Enter shopper info in the required fields. 
3. In the card number field within the UPE, input this co-brand test card number: `4000 0025 0000 1001`.
4. Use the dropdown arrow next to the card brand icon to select `Cartes Bancaires`.
5. Place the order.
6. Login to the Stripe Dashboard and view the payment event data.
7. The charge object associated with a successful payment intent contains a network field indicating which card network the payment was processed on:

```
{
  "id": "ch_1Ff52K2eZvKYlo2CWe10i0s7",
  "object": "charge",
  ...
  "payment_method_details": {
    "card": {
      "brand": "visa",
      ...
      "network": "cartes_bancaires",
      "three_d_secure": null,
      "wallet": null
    },
    "type": "card"
  }
}
```

### Dev notes

None at this time.

### Additional context

This feature request is similar to the one I made on Friday in the Woo Stripe Gateway:
https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2844

Both of these feature requests have been made in relation to a merchant request.

Slack thread:
p1705610246121619-slack-C7U3Y3VMY

Merchant ticket:
7598919-zd-a8c

### PR DESCRIPTION
**Pull request by gpressutto5**
Fixes #8062 

#### Changes proposed in this Pull Request

> **Cartes Bancaires** is France’s local card network. More than 95% of these cards are co-branded with either Visa or Mastercard, meaning you can process these cards over either Cartes Bancaires or the Visa or Mastercard networks.

When these cards are used in Stores that do not support this branch, they default to Visa or Mastercard, otherwise, Stripe renders a dropdown with the brands.
To support CB, we nee you need to use EUR and use a French account. Other countries in the EEA require processing 50 EUR LIVE before Cartes Bancaires is enabled. Any country not part of the EEA does not support Cartes Bancaires, so the brands dropdown is never rendered.

image

#### Testing instructions

- Make sure you are using a French Stripe account and processing EUR.
- Go to checkout and use one of the cobranded [test cards](https://docs.stripe.com/testing?testing-method=card-numbers#cards)
- Test saving and reusing saved cards
- Check the transactions page and the transactions in Stripe dashboard to ensure the correct brand is being used

image

image

image

image

**Known error:**
The **transactions list** does not show CB, it will only render Visa or Mastercard. I'm working on a fix for that from the server and it will **not** require another PR for the client.

image

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8568` or branch name `cobranded-cards` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=cobranded-cards) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: dc017ec14e5bfc93d73d32669cfeb787ab54eb16
- Build time: 2024-04-05 18:40:41 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by timur27 — COMMENTED** [review]
The code looks good, I have a couple questions to the feature behavior and ACs:

1. Looking at the Stripe charge object [[example](https://dashboard.stripe.com/acct_1P27qICRDNYnVUwH/test/events/evt_3P27vnCRDNYnVUwH1ZFiZ8Es)], I'm seeing `"network": "visa"` although the ACs of https://github.com/Automattic/woocommerce-payments/issues/8062 expect `"network": "cartes_bancaires"`. Do you happen to know if it's us who need introduce more changes, or ACs need to change?
2. You mentioned that the transactions list does not show CB. I see in order details doesn't show CB either but Visa credit card instead [[example](https://github.com/Automattic/woocommerce-payments/assets/22319444/cac30b6c-c1e7-47e0-a653-702500e02ba9)]. Is this also something to handle in a separate issue/PR?
3. https://github.com/Automattic/woocommerce-payments/issues/8062 mentions `the card should default to the brand selected by the merchant`. Do you know if this expectation is still valid and if yes, how can merchant select the default brand?

**Comment by gpressutto5** [comment]
1. Did you select Cartes Bancaires when paying? The network should be visa only when you choose Visa, or you're not given a choice because the merchant does not support Cartes Bancaires.
2. The order details should show Cartes Banceires if you've selected Caertes Bancaires. I think this problem is related to 1. I'm adding a few screenshots to the PR description to help with what to expect.
    image
3. Oh, I missed that, thanks! I will work on that and request another review when it's done.

**Comment by gpressutto5** [comment]
@timur27 3. is potentially being removed from the AC list https://github.com/Automattic/woocommerce-payments/issues/8062#issuecomment-2040411034, so I'm request another review.

**Review by timur27 — APPROVED** [review]
@gpressutto5 understood about removing 3) from the ACs, can confirm that Cartes Bancaires appears in the charge object as well as in the order details. 👍 

I assume that `eftpos Australia` co-branded cards don't need to be covered or will be covered separately?

Other than the above question, we're good to merge. 🚢

**Pull request merged**
