### PR TITLE
Updated the woocommerce-sniffs version

### LINKED ISSUE #6776: Update woocommerce-sniffs version
### Description
The `woocommerce-sniffs` version being used is 0.1.0, oldest version released. Using the latest version will allow  us to take advantage of `CommentHooksSniff` for ensuring hooks usage are documented and other improvements in the package
Based on idea proposed in  [woocommerce-payments-meta]93

### Acceptance criteria
`woocommerce-sniffs` is updated to latest version

### PR DESCRIPTION
**Pull request by jessy-p**
Fixes #6776

#### Changes proposed in this Pull Request

- Updated `woocommerce-sniffs` to 0.1.3 from 0.1.0
- With this update, we can use `CommentHooksSniff` for ensuring hooks usage are documented
- Based on idea proposed in [woocommerce-payments-meta]93

#### Testing instructions

- Able to update dependencies and run code sniffer without any issues

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] N/A - Covered with tests (or have a good reason not to test in description ☝️)
- [x] N/A - Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6755` or branch name `update/woocommerce-sniffs-version` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=update/woocommerce-sniffs-version) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 3c0f8006d91b5dbc193eec80242397a637ee04ce
- Build time: 2023-07-13 11:31:55 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by htdat — COMMENTED** [review]
@jessy-p - Nice work to figure this out! 
However, CI run [PHP linting](https://github.com/Automattic/woocommerce-payments/actions/runs/5542506917/jobs/10117277538?pr=6755#logs) for this change creates a lot of issues due to missing comments for hooks.

Yeah, like you mentioned in the meta issue 93, we need to either ignore those or add up comments for existing hooks. This requires more thoughts and discussions within our Gamma team or even wider #wcpay devs.

**Comment by jessy-p** [comment]
TBD: Fix or ignore existing issues.

**Review by naman03malhotra — COMMENTED** [review]
Looks good however, it would be also nice to add a link to the guide on setting up the code sniffer for the reviewer in the testing instruction.

**Comment by jessy-p** [comment]
Outdated PR, closing

**Pull request closed without merging**
