### PR TITLE
Ensure highlight colors on the Payments Overview screen use custom admin theme colors

### LINKED ISSUE #9584: Payments → Overview highlight colours are inconsistent for users with a custom admin theme enabled
### Describe the bug

For users who have a custom WP admin theme enabled, highlights on the Payments → Overview screen are inconsistent, with some elements using the theme highlight colour and others using a hard-coded blue colour.

> [!IMPORTANT]  
> **This issue is blocked due to accessibility concerns with WP-admin themes.**
> Contrast ratios in some themes, e.g. "Sunset", may not be sufficient to meet accessibility standards for text legibility. We should fix these theme accessibility concerns upstream in Gutenberg or wp-admin before incorporating these theme accent colours in WooPayments. See https://github.com/Automattic/woocommerce-payments/pull/9641#issuecomment-2516187770.

**Also note** that this issue assumes that links should be, which is probably incorrect, and these should inherit the default WP-admin link text colour.

It is common for users to have a custom admin theme enabled, as some WordPress themes introduce additional admin themes that may be selected by default for users.

For example, WPCOM-hosted sites have custom admin themes available, including "Classic Dark" which was the default WooExpress theme, with magenta highlights.

### Screenshots

Image

Image

### To Reproduce

1. In WP Admin, navigate to Users → Profile
2. Select a different admin theme
  Image
4. Navigate to Payments → Overview
5. Notice that some links are coloured blue, while some match the admin theme colours.

### Expected behavior

Highlights should use custom theme colours. Maybe links should too.

### Additional context

Discussed in PR #9571
Accessibility concerns raised in https://github.com/Automattic/woocommerce-payments/pull/9641#issuecomment-2516187770.
Discussion on Slack about accessibility concerns: p1730304032554459-slack-CNGQYA3B9

### PR DESCRIPTION
**Pull request by Jinksi**
Fixes #9584

## Changes proposed in this Pull Request

> [!NOTE]  
> [We'll await design approval of these changes](https://github.com/Automattic/woocommerce-payments/pull/9641#issuecomment-2447693344) before proceeding

Links and highlights on the Payments → Overview screen will now use custom admin themes, if enabled. Hard-coded colors have been removed, where appropriate, replaced with the CSS var `--wp-admin-theme-color`, falling back to `$gutenberg-blue` if not set.

**Before/after of WPCOM (WooExpress) store with custom admin color theme "Classic Dark"**

wpcom

image

**Before/after with custom admin color theme "Sunset" enabled**

payments-overview

<details><summary>More before/after with custom admin color theme "Sunset" enabled.</summary>

payment-activity-card-tooltip
payment-activity-card-link
inbox-notification
deposits-card
account-balances-tooltip

</details>

**Before/after of default theme**

> [!NOTE]  
> There is a slight brightening of the tooltip highlight text color, but it is now consistent with the rest of the page accents

default-theme

## Testing instructions

* Navigate to Payments → Overview and check the colors of the tooltips, links buttons and notices on this page.
* Enable different custom color themes in Users → Profile and check the colors, ensuring that the colors are consistent and suitable.
* If you have a store hosted on WPCOM, e.g. WooExpress (like [this Helix Demo Site](https://woo-delectably-sparkly-ninja.wpcomstaging.com/wp-admin/admin.php)), you will see even more admin theme options (see https://github.com/Automattic/jetpack/blob/be9762ce4b728bc537009746987f4c55d1d821cb/projects/packages/masterbar/src/admin-color-schemes/class-admin-color-schemes.php).

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️) **No tests enabled for styling**
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9641` or branch name `fix/9584-payments-overview-custom-admin-theme-colors` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/9584-payments-overview-custom-admin-theme-colors) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 888f7b21657787153177c1db465698c42b60d667
- Build time: 2024-11-11 23:09:25 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by brucealdridge — APPROVED** [review]
I've checked through various screens with various themes. Visually everything looks good. I wonder if it is worth getting @rogermattic to quickly review

**Comment by rogermattic** [comment]
@brucealdridge thanks for pinging me here!
@Jinksi  thanks for the work on this!

> There is a slight brightening of the tooltip highlight text color, but it is now consistent with the rest of the page accents

That sounds right—the color was designed to be an explanatory element in the tooltip, using a custom shade from the Woo Palette (not an accent color) since it’s not a link. The idea was to keep it blue regardless of accent colors, but I get why that’s confusing—it does look similar to the original Gutenberg blue, so I see where this idea of adapting to the theme color comes from.

So, sorry for backtracking a bit, but as much as I can see we should probably revisit the colour choice (so that it's from the Gutenberg library), but being a different kind of element (not interactive) I'm not sure it should be reactive to the theme changes. 

On a separate note though...
What really worries me, though, is that in certain themes (like sunset), the accent color, even on white, doesn’t meet accessibility standards.

I'll ask the Design System folks for an opinion and get back to you!

**Comment by Jinksi** [comment]
To summarise some discussion about this from Slack (p1730304032554459-slack-CNGQYA3B9), cc @rogermattic:

- Contrast ratio issues in “Sunset” theme accent colours highlight an accessibility concern with custom wp-admin themes.
- **Possible fix A**: Adjust SCSS mixins **in Gutenberg** to meet standards while preserving theme integrity. We can then revisit this issue in WooPayments once these changes have occurred.
- **Possible fix B**: Align wp-admin and Gutenberg colour systems via a “theme provider” for algorithmic scales.

Either way, I think we should close this PR because we don't want to introduce accessibility issues into WooPayments UI elements.

The parent issue #9584 can remain open with clarification that a broader WP-admin design system accessibility overhaul may be required before we should use these colours in WooPayments.

**Comment by haszari** [comment]
> I think we should close this PR because we don't want to introduce accessibility issues into WooPayments UI elements.

I agree :) 

> blocked on design and / or upstream changes in WordPress core

Indeed! I'll comment on the issue so that discussion is in one place :)

- https://github.com/Automattic/woocommerce-payments/issues/9584

**Comment by Jinksi** [comment]
👍 I'm closing this PR because it's not a suitable change – we don't want to introduce accessibility issues into WooPayments UI elements, as mentioned above https://github.com/Automattic/woocommerce-payments/pull/9641#issuecomment-2516187770.

**Pull request closed without merging**
