### PR TITLE
Draft - hide affirm based on location

### PR DESCRIPTION
**Pull request by nagpai**
related to #6515 

Hides Affirm if the country on initial load is not US or CA.  Also updates if the country is changed in the dropdown ( borrowed from #6604 by @KarlisJ )

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6606` or branch name `fix/v1-6515-hide-affirm-based-on-location` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=fix/v1-6515-hide-affirm-based-on-location) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: a2c29595ad49d8a9c90f2313c50b51d942ceb48f
- Build time: 2023-06-28 08:38:33 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by kalessil** [comment]
In general, the solution is straightforward and the idea is clear.
What are the options to generalize this approach (so all available PMs are checked) and not hard-code countries in JS?

**Comment by KarlisJ** [comment]
@kalessil 
> What are the options to generalize this approach (so all available PMs are checked) and not hard-code countries in JS?

JS side we create the listener for the change event but generalise the handler function. Ideally, we should add something like `$this->customer_countries = [..]` to `UPE_Payment_Method` and pass that data to frontend. Then the JS handler can read that config and act accordingly. 

That would include changes in 
- `abstract class UPE_Payment_Method`
- any implementation of that class that have such restrictions
- `display_gateway_html` method on split UPE gateway which is where we can pass data as html attribute (we do that now for payment type)
- JS changes in the same place they are now

But we should be careful with applying these changes to existing PM as it could be considered unwanted behaviour for those methods.

**Comment by kalessil** [comment]
@nagpai: is this PR still relevant?

**Comment by nagpai** [comment]
@kalessil  No longer relevant. Closing this since the issue has been resolved by PR #6604 , merged yesterday. Thanks.

**Pull request closed without merging**
