### PR TITLE
Fix incorrect amounts on payment request button for zero decimal currencies

### LINKED ISSUE #3376: Payment Request causes 100x increase in price when paying in JPY
### Describe the bug

If your currency is set to JPY and you try to pay via Apple or Google Pay, the cost is multiplied by 100.

### To Reproduce

1. WC Pay test site with a test product and multi-currency enabled.
2. In the Multi-Currency tab, enabled JPY and leave the settings on defaults.
Screenshot taken on 2021-11-14 at 16 55 37 UTC@2x
3. On the frontend, under My Account > Account Details, switch your currency to JPY and save.
4. Frontend prices should now be shown in JPY, e.g.:
Screenshot taken on 2021-11-14 at 16 57 21 UTC@2x
5. Click the Apple or Google Pay button.
6. Your price has increased 100x!
Screenshot taken on 2021-11-14 at 16 58 08 UTC

### Expected behavior

Correct pricing.

Originally surfaced in 4451148-zen.

### PR DESCRIPTION
**Pull request by malithsen**
Fixes #3376

#### Changes proposed in this Pull Request
If the currency is set to Japanese yen (or any other currency listed [here](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payments-utils.php#L193)) the amounts shown are multiplied by 100 on Payment Request sheet in product page, cart page, or checkout page.  This is because the currency is not being passed into the `prepare_amount` method, which makes it use the incorrect conversion rate that is used for non-zero decimal currencies. This change passes in the value of `get_woocommerce_currency` to the above method

#### Testing instructions

* Add Japanese yen to the list of currencies in WooCommerce -> Settings -> Multi-currency
* On the frontend, under My Account > Account Details, switch your currency to JPY and save. (Or use currency switcher widget)
* Go to a product page
* Click the payment request button
* Ensure that the prices shown matches the correct amount for the product

Before
Screen Shot 2021-11-15 at 2 32 07 PM

After
Screen Shot 2021-11-15 at 2 30 03 PM

-------------------

- [x] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply)

### CODE REVIEW

**Review by brianyu28 — COMMENTED** [review]
This looks good to me, thanks @malithsen! I tested this with Google Pay and confirmed that this fixes the factor of 100 multiplication error for JPY while leaving currencies with decimals unaffected.

I did notice, though, that in my WCPay Multi-currency settings, the exchange rate for USD to JPY defaults to 1 USD = 1 JPY as the current rate, which causes the $18 USD beanie to show up as 100 JPY (rounded up to the nearest 100) when it should instead be closer to 2100 JPY at today's exchange rates. Based on your screenshots in this PR, it seems like you might be seeing the same thing? It seems to me that that's probably a separate issue than this one, though.

**Comment by malithsen** [comment]
Hey @brianyu28 Thanks for the review. 
> I did notice, though, that in my WCPay Multi-currency settings, the exchange rate for USD to JPY defaults to 1 USD = 1 JPY as the current rate

I didn't notice this earlier, thanks for pointing it out. It looks like this is a limitation of the local setup. I don't see the same issue on a JN site.  
Screen Shot 2021-11-16 at 10 31 09 AM

Digging a little more, found that on local sites, we return a set of hard-coded exchange rates (JPY is not on that list), we only fetch live rates when running on WPCOM. see `exchange-rate.php` in woocommerce-payments-server

**Review by brianyu28 — APPROVED** [review]
Makes sense, this looks good to me then @malithsen. Thanks!

**Comment by malithsen** [comment]
Hey @ricardo I am requesting a review on this as Axiom is still getting familiar with WCPay and I see that you've made changes to these files previously. Let me know if I should assign it to someone else instead.

**Review by ricardo — APPROVED** [review]
LGTM and tests well.

Thanks for fixing this.

**Pull request merged**
