### PR TITLE
Simplify deposit UI: rearrange next deposit notices and style them consistently

### LINKED ISSUE #6002: Simplify deposits UI - Add padding between notices
From pdjTHR-2u8-p2#comment-3235, when multiple notices show up, we need to add some breathing room (16px) between them.

Current:
Untitled

Should be:
Untitled2

### PR DESCRIPTION
**Pull request by james-allan**
Fixes #6002

#### Changes proposed in this Pull Request

This PR moves the Next deposit related notices into the same file and places them in the same container. This change enables us to target the notices in a relative way with css styles. eg to add margin-bottom to each notice except for the last child.

Prior to this change, the completed waiting period notice was handled by the `index.tsx` file but the capital loan payout notice was handled by the `next-deposit.tsx` file as it needed the next deposit for context.

This arrangement made it difficult to style these notices in a consistent way. ie there were 3 versions of the `margin:0` style being applied to `wcpay-banner-notice.components-notice` elements. 

#### Testing instructions

Testing these notices requires some level of hacking to bypass needing to meet the requirements.

**No notices**
_For me this is the default state_

1. Set the wp option `_wcpay_feature_simplify_deposits_ui` to 1 to enable the feature flag.
2. Go to the **Payments > Overview** page
3. Note the UI looks correct without any notices. ie there isn't any incorrect padding etc. 

<p align="center">
Screenshot 2023-04-13 at 3 52 16 pm
</p>

**Waiting period notice**
1. Set the `completedWaitingPeriod` const to `false`.
2. Refresh the page. 
3. Again, note the UI looks correct with this notice. ie there isn't any incorrect padding etc. 

<p align="center">
Screenshot 2023-04-13 at 3 56 55 pm
</p>

**Capital loan**
1. Set the `includesFinancingPayout` const to `true`.
2. Refresh the page. 
3. Again, note the UI looks correct with this notice. ie there isn't any incorrect padding etc.

<p align="center">
Screenshot 2023-04-13 at 3 57 45 pm
</p>

**Pending/In-transit deposit**
1. In the `recent-deposits-list.tsx` file, set the `deposits` const to the dummy value provided below.
3. Refresh the page. 
3. Again, note the UI looks correct with this notice. ie there isn't any incorrect padding etc.

<table>
<thead>
  <tr>
    <th>1 in-transit</th>
    <th>All in-transit</th>
    <th>Multiple in-transit deposits</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td>Screenshot 2023-04-13 at 4 14 58 pm</td>
    <td>Screenshot 2023-04-13 at 4 17 21 pm</td>
    <td>Screenshot 2023-04-13 at 4 18 39 pm</td>
  </tr>
  <tr>
    <td><pre lang="js">const deposits = [
	{
		id: '1',
		date: '2023-04-10',
		type: 'deposit',
		amount: 2982,
		currency: 'USD',
		fee_percentage: 0,
		fee: 0,
		status: 'in_transit',
		bankAccount: '123456789',
		automatic: true,
	} as CachedDeposit,
	{
		id: '2',
		date: '2023-03-09',
		type: 'deposit',
		amount: 13721,
		currency: 'USD',
		fee_percentage: 0,
		fee: 0,
		status: 'paid',
		bankAccount: '987654321',
		automatic: true,
	} as CachedDeposit,
	{
		id: '3',
		date: '2023-02-09',
		type: 'deposit',
		amount: 12314,
		currency: 'USD',
		fee_percentage: 0,
		fee: 0,
		status: 'paid',
		bankAccount: '987654321',
		automatic: true,
	} as CachedDeposit,
];</pre></td>
    <td><pre lang="js">const deposits = [
	{
		id: '1',
		date: '2023-13-10',
		type: 'deposit',
		amount: 2982,
		currency: 'USD',
		fee_percentage: 0,
		fee: 0,
		status: 'pending',
		bankAccount: '123456789',
		automatic: true,
	} as CachedDeposit,
	{
		id: '2',
		date: '2023-12-09',
		type: 'deposit',
		amount: 13721,
		currency: 'USD',
		fee_percentage: 0,
		fee: 0,
		status: 'in_transit',
		bankAccount: '987654321',
		automatic: true,
	} as CachedDeposit,
	{
		id: '3',
		date: '2023-10-09',
		type: 'deposit',
		amount: 12314,
		currency: 'USD',
		fee_percentage: 0,
		fee: 0,
		status: 'paid',
		bankAccount: '987654321',
		automatic: true,
	} as CachedDeposit,
];</pre></td>
    <td><pre lang="js">const deposits = [
	{
		id: '1',
		date: '2023-13-10',
		type: 'deposit',
		amount: 2982,
		currency: 'USD',
		fee_percentage: 0,
		fee: 0,
		status: 'pending',
		bankAccount: '123456789',
		automatic: true,
	} as CachedDeposit,
	{
		id: '2',
		date: '2023-12-09',
		type: 'deposit',
		amount: 13721,
		currency: 'USD',
		fee_percentage: 0,
		fee: 0,
		status: 'in_transit',
		bankAccount: '987654321',
		automatic: true,
	} as CachedDeposit,
];<pre></td>
  </tr>
</tbody>
</table>

For good measure, I also tested with all notices on the screen at once. 

Screenshot 2023-04-13 at 4 20 11 pm

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6022` or branch name `issue/6002-rearrange-next-deposit-notices-for-consistency` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=issue/6002-rearrange-next-deposit-notices-for-consistency) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: c439ba6767c752892400ba39ed75467aab5a68df
- Build time: 2023-04-14 00:34:42 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by shendy-a8c — APPROVED** [review]
Looks good! Tested well.

**Comment by shendy-a8c** [comment]
Wondering why the PR is still in draft. Do you plan to add more changes?

**Comment by james-allan** [comment]
> Wondering why the PR is still in draft. Do you plan to add more changes?


haha I came to this PR just now and asked myself the same question. It wasn't supposed to be a draft.

**Pull request merged**
