### PR TITLE
Warn about dev mode enabled on new onboarding flow choice

### LINKED ISSUE #6429: Warn about dev mode enabled on new onboarding flow choice
### Description
Dev mode interferes with the new onboarding flow mode choice. If it's enabled, live will behave as test, and test will fail. So we should warn about dev mode being manually enabled.

### Acceptance criteria
- Show a warning letting know that dev mode is enabled, with a link to our documentation about it.
- Explain how the flow will work – Live will work as test, test will fail.
- Don't show the warning if dev mode is enabled via `wcpay_onboarding_test_mode`.

### Designs
We will need to define the warning copy, the current flow design looks like:
Screenshot 2023-06-02 at 10 27 17

### PR DESCRIPTION
**Pull request by oaratovskyi**
Fixes #6429 

#### Changes proposed in this Pull Request

- Implemented Dev mode notice to inform user about it
- Programmatically delete test account to prevent error that is happening when test mode `$_GET['wcpay-disable-onboarding-test-mode']` and dev mode are on

image

#### Testing instructions

**Pre-requisites**
- Follow server testing instructions
- Use the sandbox instead of local server by configuring dev tools properly
- Checkout `add/6429-warn-about-dev-mode-on-new-onboarding`
- Start jurassic tube connection with `npm run tube:start`
- To perform another test you might need to delete wcpay account using MC account deletion tool

**Bugfix 1**
- Check that Dev mode and Progressive Onboarding flag are **enabled** in dev tools, enable if not
- Start onboarding new account
- Verify that you see the notice explaining how dev mode works
- Onboard new builder account (second radiobutton)
- After onboarding, click Set up live payments
- Now onboard live account (it'll be test because of test mode though)
- Verify that previous WCPay test account is deleted

**Bugfix 2**
- Check that Dev mode and Progressive Onboarding flag are **enabled** in dev tools, enable if not
- Start onboarding new account
- Verify that you see the notice explaining how dev mode works
- Onboard new builder account (second radiobutton)
- After onboarding, click Set up live payments
- After you see the mode choice with the notice, disable Dev Mode and try onboarding progressively live account (now it should be live). No dev mode notice should be shown.
- Check that progressive onboarding is successful and you're redirected to overview page

**Regression test**
- Check that Dev mode is **disabled** and Progressive Onboarding flag is still enabled in dev tools
- Start onboarding new account
- No dev mode notice should be shown.
- Onboard new builder account (second radiobutton)
- After onboarding, click Set up live payments
- Onboard progressively live account
- Check that progressive onboarding is successful and you're redirected to overview page

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions-for-WC-Payments-6.5.0#warn-about-dev-mode-enabled-on-new-onboarding-flow-choice
- [x] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [x] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7082` or branch name `add/6429-warn-about-dev-mode-on-new-onboarding` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=add/6429-warn-about-dev-mode-on-new-onboarding) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 6f7f4d2227be6acd1ec5e21d94f6151f31544880
- Build time: 2023-09-12 14:15:42 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by dmallory42 — APPROVED** [review]
LGTM and works well - one small issue I noticed when testing was that in my case, the notice appeared even when `dev mode` was disabled in the WCPay Dev Tools. I'm not sure why - it looks like the `$dev_mode = WC_Payments::mode()->is_dev();` function returns true if the dev mode constant is set OR if the environment of the site is set to `development` in the `wp-config.php` (which mine was), so maybe that was the reason - I think it will work without problem on a real site, so it's not an issue but just a little confusing.

If you want, you could deploy the server PR and then I can re-test on a JN site before merging this -  let me know and I'm happy to re-test just to be sure!

**Comment by oaratovskyi** [comment]
@dmallory42 thanks for review! 
Oh, that's expected! Anything that sets dev mode - the constant  or environment = development is also good! The key point here is that when we try onboard live account (Radio button 1) with constant enabled it should also trigger test mode in stripe and dev notice to be shown

When I merge server PR, I like your idea of double checking it using JN! 🙂

**Comment by oaratovskyi** [comment]
@dmallory42 server PR merged!

**Comment by ismaeldcom** [comment]
Hey @oaratovskyi! ~~With #7097 finally merged, you can replace `InlineNotice` with `BannerNotice` to match our design guidelines 🙂~~ 

**Edit:** As we discussed on Slack, this should still use `InlineNotice` because it's tied to this specific step and displayed inside the content area.

**Comment by dmallory42** [comment]
Tested the final scenario on a JN site and it all works perfectly. Thanks Oleks!  :shipit:

**Comment by oaratovskyi** [comment]
Thanks Dan, appreciate it!

**Pull request merged**
