### PR TITLE
Bump minimum WooCommerce version to 4.5

### PR DESCRIPTION
**Pull request by adrianduffell**
#### Changes proposed in this Pull Request

Bump the minimum supported version of WooCommerce to 4.5.

#### Testing instructions

Check that CI tests run as expected. These were updated to stop testing versions <4.5.

### CODE REVIEW

**Comment by jrodger** [comment]
Thanks for putting this together @adrianduffell (and the associated discussion and data gathering).

I think this is fine, especially given we haven't actually added anything that requires WC 4.5 or greater just yet. So I think if someone did upgrade while on an "unsupported" version of WooCommerce, everything would keep working (at least for now)?

There is one query I have around that though. We also have the minimum version stated in the main plugin file [here](https://github.com/Automattic/woocommerce-payments/blob/81b6da73caa18477488b8d94de0ca745d3b32b75/woocommerce-payments.php#L11). Usually we would increase this to 4.5 as well, however, that would cause our version checking to stop the plugin loading if that minimum version wasn't found ([here](https://github.com/Automattic/woocommerce-payments/blob/670a492a071e96c865edb3f3b1e046cd75e3c807/includes/class-wc-payments.php#L278) and [here](https://github.com/Automattic/woocommerce-payments/blob/670a492a071e96c865edb3f3b1e046cd75e3c807/includes/class-wc-payments.php#L137)).

So I think we could do one of 2 things:

1. Don't bump `WC requires at least` and try to ensure that the plugin maintains basic functionality in the event someone is running down to WC 4.0 (i.e. no fatal errors, checkout still works). That might involve adding version checks where we use newer functionality for example. We might also want to leave CI tests that operate on WC versions down to 4.0 in this case.
2. Bump `WC requires at least` to 4.5 and investigate what the merchant experience looks like in various upgrade situations. For example, if I was a merchant running 4.4 and I got auto-upgraded to the newest WCPay, does my checkout stop working? Or, does anything try to stop me upgrading manually if we know that means WCPay will disable itself?

What do you think?

cc @marcinbot since we've had a bit of discussion on this.

**Comment by dmvrtx** [comment]
> Usually we would increase this to 4.5 as well, however, that would cause our version checking to stop the plugin loading if that minimum version wasn't found ([here](https://github.com/Automattic/woocommerce-payments/blob/670a492a071e96c865edb3f3b1e046cd75e3c807/includes/class-wc-payments.php#L278) and [here](https://github.com/Automattic/woocommerce-payments/blob/670a492a071e96c865edb3f3b1e046cd75e3c807/includes/class-wc-payments.php#L137)).

Does this check only happen after the plugin has been updated? I wonder if it is possible to implement safeguards to stop upgrade process if this happens.

Or maybe it's worth to put a link to the latest WC 4.0 compatible plugin version in the notices before bumping up minimum version requirements in the plugin file.

**Comment by adrianduffell** [comment]
> So I think we could do one of 2 things:
> 
> 1. Don't bump `WC requires at least` and try to ensure that the plugin maintains basic functionality in the event someone is running down to WC 4.0 (i.e. no fatal errors, checkout still works). That might involve adding version checks where we use newer functionality for example. We might also want to leave CI tests that operate on WC versions down to 4.0 in this case.
> 2. Bump `WC requires at least` to 4.5 and investigate what the merchant experience looks like in various upgrade situations. For example, if I was a merchant running 4.4 and I got auto-upgraded to the newest WCPay, does my checkout stop working? Or, does anything try to stop me upgrading manually if we know that means WCPay will disable itself?
> 
> What do you think?

Thanks, I'm happy to go with option 1 for now, since we are close to the next release and it seems least riskiest.

I suspect we'll need to implement measures like what @dmvrtx mentions. I could test the impact of option 2 in the next cycle and report back?

**Comment by adrianduffell** [comment]
If we're happy with option 1, I'll undo the CI test changes.

**Comment by jrodger** [comment]
> If we're happy with option 1, I'll undo the CI test changes.

I'm happy with that since it moves us forward and doesn't have any significant downsides. We can try to figure out a more solid approach for the next version bump.

The only downside I can think of is WooCommerce won't inform people they're moving to an unsupported version, because it uses the header we're leaving at 4.0.

I wouldn't mind a second opinion from someone else though. What do you think @marcinbot, @DanReyLop?

**Comment by adrianduffell** [comment]
I've now reverted the CI test changes, making this PR now only update the `readme` and `changelog` documentation.

@dmvrtx can this still make it in the next release? 😅 

> The solution could be trying to hook into something like `upgrader_pre_download`

This approach sounds interesting. I've got some time available this week and could start investigating it.

**Comment by dmvrtx** [comment]
> @dmvrtx can this still make it in the next release? 😅

 I see no reason for it not to 🙂 Just make sure it is merged into `develop` before Wednesday noon UTC.

**Review by dmvrtx — APPROVED** [review]

**Pull request merged**
