### PR TITLE
Add filter to disable WooPay checkout auto-redirect and email OTP iframe

### PR DESCRIPTION
**Pull request by ricardo**
Fixes 2298-gh-Automattic/woopay

#### Changes proposed in this Pull Request

- Add filter to disable the WooPay email input hooks.

#### Testing instructions

1. Switch to this branch.
2. Run `npm run build:client`.
3. Install [Code Snippets](https://wordpress.org/plugins/code-snippets/) and enable the following filter:
```php
add_filter( 'wcpay_is_woopay_email_input_enabled', '__return_false' );
```
4. Ensure the checkout email input doesn't trigger the OTP iframe.
5. Ensure the checkout email input doesn't trigger auto-redirection to WooPay if the merchant site is under HTTPS and user already logged-in to WooPay.
6. Ensure the email input hooks work as expected if the filter is disabled.

Please test steps 4 - 6 with blocks and classic checkout.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7805` or branch name `add/2298-filter-disable-woopay-auto-redirect` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=add/2298-filter-disable-woopay-auto-redirect) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 9c7b9f739a769f1ee4b33453d8a2805a38228a44
- Build time: 2023-11-30 17:19:01 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by manzurahammed** [comment]
I've tested this PR and confirmed that the following issue is fixed after using the filter hook provided.
- OTP iframe didn't show 
- Preventing automatic redirection to the WooPay checkout page.

**Review by manzurahammed — APPROVED** [review]
Thanks @ricardo 
LGTM!

**Review by cesarcosta99 — APPROVED** [review]
Code changes look good and test well on both classic and Blocks checkouts:

- Ensure the checkout email input doesn't trigger the OTP iframe. ✅ 
- Ensure the checkout email input doesn't trigger auto-redirection to WooPay if the merchant site is under HTTPS and user already logged-in to WooPay. ✅ 
- Ensure the email input hooks work as expected if the filter is disabled. ✅ 

I have just one minor 🤏 suggestion that would be renaming the filter from `wcpay_woopay_email_input_enabled` to `wcpay_is_woopay_email_input_enabled`, but feel free to ignore it.

**Comment by ricardo** [comment]
@cesarcosta99 thanks for the quick review. 

> I have just one minor 🤏 suggestion that would be renaming the filter from `wcpay_woopay_email_input_enabled` to `wcpay_is_woopay_email_input_enabled`, but feel free to ignore it.

Good call, I just made the change. cc @manzurahammed to be aware of the update.

---

I'm going to merge the PR despite the compatibility checks failing as they are unrelated (p1701263468047559-slack-CGGCLBN58).

**Pull request merged**
