### PR TITLE
Code quality improvements for the Deposit Details component

### PR DESCRIPTION
**Pull request by Jinksi**
#### Changes proposed in this Pull Request

This PR tidies up the code in `client/deposits/details/index.tsx` to be more consistent with the [codebase TS guidelines](https://github.com/Automattic/woocommerce-payments/tree/develop/docs/typescript) and improve code readability. It has no impact on functionality.

#### Testing instructions

* Ensure all tests pass.
* Visit a Deposit Details screen to ensure no issues with rendering. 

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply) **N/A**

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7786` or branch name `dev/improve-deposit-details-code-quality` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=dev/improve-deposit-details-code-quality) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: d1fa124e883c719dc8bd1718341dd62336ad8ee5
- Build time: 2023-11-29 23:43:51 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by brucealdridge — APPROVED** [review]
Tested and read through code. 👍

**Comment by brucealdridge** [comment]
I notice there are some tests failing. I'm assuming these failures are unrelated.

**Comment by brucealdridge** [comment]
Marking as `needs author reply` to confirm failing tests are unrelated. Otherwise good to merge.

**Comment by Jinksi** [comment]
> Marking as needs author reply to confirm failing tests are unrelated. Otherwise good to merge.

Confirmed – falling tests on WC beta and shopper e2e are unrelated to this PR: failures due to checkout/shipping.

**Pull request merged**
