### PR TITLE
Ensure the BNPL PMME doesn't appear on carts with subscriptions

### LINKED ISSUE #9772: BNPL PMME incorrectly appears on carts with subscriptions
### Describe the bug

The BNPL PMME is appearing on the the classic cart when subscriptions on in the cart. The PMME shouldn't be displayed when subscriptions are in the cart.

### To Reproduce

1. Enable BNPL methods.
2. Add a subscription product to the cart.
3. Visit the classic cart and notice the PMME is present.

### Expected behavior

The PMME should not appear on the classic cart when a subscription is in the cart.

### PR DESCRIPTION
**Pull request by mdmoore**
Fixes #9772 

#### Changes proposed in this Pull Request

In an effort to fix [an issue on PDPs](https://github.com/Automattic/woocommerce-payments/pull/9626#pullrequestreview-2407990115), I made a change that caused the PMME to appear on the cart page when subscription products are in the cart. In fact, the cart page should indeed use `get_payment_method_ids_enabled_at_checkout()` which is a filtered list of enabled payment methods. The PDP still needs all enabled payment methods however, to solve the issue mentioned above. This PR adds adds some branching to ensure both page have the list of BNPL payment methods it needs.

#### Testing instructions

1. Enable BNPL methods.
2. Add a subscription product to the cart.
3. Visit the classic cart. The PMME should not appear.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9774` or branch name `fix/no-bnpl-subscriptions` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/no-bnpl-subscriptions) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: d8ac8bfd69e58496745f02541ed249731f702214
- Build time: 2024-11-21 16:20:23 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by timur27 — COMMENTED** [review]
I noticed that we already perform [the check against subscription products early in the PMME initialization](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payments.php#L1886), which I initially thought would cover the use case addressed by this PR.

However, it turns out that global `$product` is `null`, so the product type isn’t recognized as expected. To avoid introducing workarounds within the `init()` method, do you think it might make sense to integrate:

```php
WC_Subscriptions_Cart::cart_contains_subscription();
```

[here?](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payments.php#L1883)

Additionally, we could check if this type of subscription detection covers the use cases currently handled by `WC_Subscriptions_Product::is_subscription( $product )`. If it does, we might consider fully replacing it.

By properly blocking the execution of `init()` for PMME with subscriptions, we’ll also eliminate the redundant animation currently present:

https://github.com/user-attachments/assets/ce6e05d2-4959-457b-97ad-ed5b91746d36

What do you think of this approach?

**Comment by mdmoore** [comment]
Thanks @timur27! I was actually hoping to use something like the function you've mentioned, `WC_Subscriptions_Cart::cart_contains_subscription()` but I wasn't aware of it. It will be useful indeed. 

>it turns out that global $product is null

This is because we're on the cart page in this case. That check is for product pages. We're initializing here for both scenarios, cart and product. I don't see a way around checking the page we're on here. What's more, there's a sneaky scenario where there might be a subscription in the cart, but the shopper is viewing a non-subscription product. In that case, `WC_Subscriptions_Cart::cart_contains_subscription()` returns `true` and the PMME isn't displayed on the product page. 

With the above in mind, it's better to do these checks before the `init()` method like you mentioned. Let me know what you think of [d8ac8bf](https://github.com/Automattic/woocommerce-payments/pull/9774/commits/d8ac8bfd69e58496745f02541ed249731f702214) instead, which reverts the change within the `init()` method and runs the subscription check prior to init.

**Review by timur27 — APPROVED** [review]
Looks good, thank you! 🚢

**Pull request merged**
