### PR TITLE
Tracks for subscriptions product creation flow when not connected to Stripe yet.

### LINKED ISSUE #3419: Add tracks events to subscription product creation flow
### Description
We're improving the WCPay subscription product create flow to ensure that WCPay is onboarded and set up correctly (#3356).

While we're making those improvements, we can add tracks events to give us insight into how the flow is working for our merchants. Specifically:

- When user attempts to publish a subscription product (may be an existing event, can add props as needed)
- When modal is shown.
- When the user takes an action (dismiss or finish setup). 

We may need other events before (editing subscription product) and after (onboarding WCPay, publishing product) to understand the flow in the full context.

This issue is a placeholder for now, will add more details after further investigation. 

### Acceptance criteria
Tracks events are being sent when:
- No wcpay account connected and user tries to save / publish subscriptions product.
- After a wcpay account is connected and there are draft subscriptions products that are created prior account connection.
- User dismisses or clicks on the 'finish setup' button on the modal that is shown on the edit product page, after user creates or saves a subscriptions product, when not connected to any wcpay account.

### PR DESCRIPTION
**Pull request by shendy-a8c**
Fixes #3419

#### Changes proposed in this Pull Request

- Sends tracks event when user saves products but no wcpay account connected.
- Sends tracks event when wcpay account is connected and there are draft subscriptions products.
- Sends tracks event when user dismisses the modal from https://github.com/Automattic/woocommerce-payments/pull/3429 that is shown on the edit product page.
- Sends tracks event when user clicks the 'finish setup' button on the modal from https://github.com/Automattic/woocommerce-payments/pull/3429 that is shown on the edit product page.

Note: I need to register the track events but I thought I'd do that after the event names get blessing from this PR reviewers.

New tracks events:
- `wcpay_subscriptions_account_not_connected_save_product`
- `wcpay_subscriptions_account_not_connected_publish_products`
- `wcpay_subscriptions_account_not_connected_product_modal_finish_setup`
- `wcpay_subscriptions_account_not_connected_product_modal_dismiss`

Action item for me: register tracks events on the MC Tracks tool.

#### Testing instructions

1. Make sure WC Subscriptions is not active.
2. Enable tracking under WC settings > Advanced > WooCommerce.com (/wp-admin/admin.php?page=wc-settings&tab=advanced&section=woocommerce_com).
2. Make sure store is *not* connected to a wcpay account (by starting a new JN site or use wcpay dev tool with 'Force the plugin to act as disconnected from WCPay' checked).
3. Checkout this PR branch and run `npm start` to make sure JS files are built using the latest changes from this PR branch.
4. Creates a subscriptions product.
5. The status of that product should be draft.
6. There should be a track event named `wcpay_subscriptions_account_not_connected_save_product` being sent. Not sure how to verify tracks event being sent from PHP. Maybe from the MC Tracks Live View.
7. There should be a modal being shown. Refer to https://github.com/Automattic/woocommerce-payments/pull/3429 to see how the modal looks like.
8. Do not do anything with the modal. Open Chrome dev tool and go to the Network tab. Filter with string `wcpay_subscriptions_account_not_connected`. A more detailed instructions can be found from https://github.com/Automattic/woocommerce-payments/pull/3437.
9. Close the modal and expects a pixel request containing `wcpay_subscriptions_account_not_connected_product_modal_dismiss` in the URL.
10. Clicks on the 'Update' button to save the product. This is to trigger the modal again.
11. This time, click o nthe 'Finish setup' button on the modal and expects a pixel request containing `wcpay_subscriptions_account_not_connected_product_modal_finish_setup` in the URL.
12. Go through onboarding to connect the store with a wcpay account.
13. Check on the subscription product you created earlier and expect its status to be published this time.
14. There should be a track event named `wcpay_subscriptions_account_not_connected_publish_products` being sent. Not sure how to verify tracks event being sent from PHP. Maybe from the MC Tracks Live View.

-------------------

- [x] Added changelog entries to both `readme.txt` and `changelog.txt` (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply)

### CODE REVIEW

**Comment by aprea** [comment]
This is looking good. I performed some testing on a fresh JN site with the attached package.

Though I am running into one issue. I'm only able to observe 3 of the 4 events in the Tracks dashboard here → https://mc.a8c.com/tracks/live/?eventname=wcadmin_wcpay_subscriptions_account_not_connected_%25&user=&useragent=

Screen Shot 2021-12-02 at 3 01 24 pm

The 3 events I can see are:
- `wcadmin_wcpay_subscriptions_account_not_connected_product_modal_dismiss`
- `wcadmin_wcpay_subscriptions_account_not_connected_product_modal_finish_setup`
- `wcadmin_wcpay_subscriptions_account_not_connected_save_product`

The event I'm **not** able to see is `wcadmin_wcpay_subscriptions_account_not_connected_publish_products`.

I completed onboarding 3 times but was not able to see logs for this event in Tracks. Note that the flow is working correctly as I can see the subscription products are published as expected.

There might be a data sampling issue at play or maybe the event is not triggering properly in the client?

[woocommerce-payments.zip](https://github.com/Automattic/woocommerce-payments/files/7638751/woocommerce-payments.zip)

**Comment by shendy-a8c** [comment]
I too can't consistently see `wcadmin_wcpay_subscriptions_account_not_connected_publish_products` but occasionally I see it.

Screen Shot 2021-12-03 at 04 53 26

This is a bit concerning but after a long investigation, I can't come to a conclusion of what causes it to show / not show on live tracks tool.

I see that depending on whether the request is an AJAX or not, [we send track event differently](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/tracks/class-wc-tracks-event.php#L57-L61). We could send it by [making a request](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/tracks/class-wc-tracks-client.php#L110-L125) or [renders a pixel at the footer](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/tracks/class-wc-tracks-footer-pixel.php#L81-L97).

If I have to guess, when action `woocommerce_payments_account_refreshed` gets triggered, we send the event by rendering pixel in the footer of a page but then there is a redirect, so that pixel doesn't get loaded by the browser. I plan to dig deeper. Possibly, we need to move sending `wcadmin_wcpay_subscriptions_account_not_connected_publish_products` somewhere else or find a way to force it to send it by request.

The fact that the event *sometimes* show up, maybe it's OK to go ahead with this PR, for now and improve it later. Filed https://github.com/Automattic/woocommerce-payments/issues/3460 for now.

Also, I have opened PRs to register those events:
666-gh-Automattic/tracks-events-registration
665-gh-Automattic/tracks-events-registration
664-gh-Automattic/tracks-events-registration
663-gh-Automattic/tracks-events-registration

Do I just need to merge those PRs?

**Comment by shendy-a8c** [comment]
Another concern is that events sent via front-end using [window.wcTracks.recordEvent()](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/tracks/class-wc-site-tracking.php#L70-L86) doesn't pass blogid and user is anon. Since it's within Woo's codebase, I'll ask on Slack about this. It's not a problem specific for this PR.

**Comment by aprea** [comment]
Thanks for investigating this @shendy-a8c, I think we can proceed with this PR and then continue investigating in #3460.

I'll also merge your `tracks-events-registration` PRs.

**Review by aprea — APPROVED** [review]

**Pull request merged**
