### PR TITLE
Bump @woocommerce/e2e-utils to v0.1.6 

### LINKED ISSUE #3472: Spike: Upgrade E2E utils to the latest version, explore adding retries
### Description
A new version of the e2e utils package is available with support for retries. Explore if they can be utilized to improve the overall CI reliability.

### Acceptance criteria

* Update to the latest version.
* Explore if retries help in reducing flakiness.

### PR DESCRIPTION
**Pull request by deepakpathania**
Fixes #3472 

#### Changes proposed in this Pull Request
- Bump @woocommerce/e2e-utils to v0.1.6.
- Add missing grouped product details to test config.
- Skip task list test to avoid flakiness till retries are introduced (targeted Jan '22)

#### Testing instructions

- Updates E2E tests so existing tests should work fine.

-------------------

- [x] Added changelog entries to both `readme.txt` and `changelog.txt` (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply)

### CODE REVIEW

**Comment by deepakpathania** [comment]
Limiting the scope of this since retries for individual tests hasn't been released yet, reference: p1639672179046100/1638515774.029000-slack-C026J0AL8NS

**Review by achyuthajoy — COMMENTED** [review]
Changes look good to me @deepakpathania. However, one of the test fails for me while testing locally. Here is a screenshot - https://d.pr/i/81m9Xq

Is this expected?

**Comment by deepakpathania** [comment]
> However, one of the test fails for me while testing locally
I just checked and the test passes for me locally and in CI, could be an intermittent thing maybe. Does it fail consistently for you?

**Review by achyuthajoy — APPROVED** [review]
Thanks. All good on my end @deepakpathania. Tests are passing for me :)

**Pull request merged**
